### ISSUE TITLE
近期有考虑增加【显示源码】的功能么？

### ISSUE THREAD

**Issue by jy00504445** [wangfupeng1988/wangEditor#10]
虽然编辑器用起来挺好的，但毕竟没法满足所有情况，所以如果有【显示源码】的功能，至少在已有功能无法满足的情况下可以自行编辑html的源代码。
不知道近期有没这样的开发计划？

**Comment by wangfupeng1988** [comment]
【显示源码】功能可以增加上。不过，这需要网站后台加强对输入内容安全性的监控，因为暴露源码很容易进行xss攻击。
所以，我的建议是：有更加合理的建议，你可以在此提出，我会考虑增加。
最好不要开放源码编辑。

**Comment by wangfupeng1988** [comment]
该功能早就加上了，关闭该提问。
