### ISSUE TITLE
jQuery无法获得modal事件

### ISSUE THREAD

**Issue by legendweny** [wangfupeng1988/wangEditor#100]
使用plupload组件上传图片，jQuery无法选择 modal 并获得shown.sb.modal 事件唉
这是我的代码
$('.wangEditor-modal-container').on('shown.bs.modal', function () {
                uploader.refresh();
                console.log('open');
            });
测试页面 http://fork12.com/user/work/create

**Comment by legendweny** [comment]
$('.wangEditor-modal').on('shown.bs.modal', function () {
                uploader.refresh();
                console.log('open');
            }); 这样好像也不行

**Comment by wangfupeng1988** [comment]
`shown.sb.modal `事件是`plupload`里面定义的事件吗？我不知道。文档中介绍的集成`plupload`来上传图片没有用到这个事件。

另外，你为何要对`$('.wangEditor-modal')`或者`$('.wangEditor-modal-container')`实行这个事件？不明白。

如果你只是想集成`plupload`往编辑器中上传图片，那么参照文档中的做法来就是了，用不到你说的这两种情况。

如果你还有其他的需求，可以先吧需求描述清楚。

还有，我用你给出的测试页面 http://fork12.com/user/work/create 来上传了一张图片，上传成功了。

**Comment by wangfupeng1988** [comment]
长时间不回复
