### ISSUE TITLE
编辑器为何默认居中输入，想要从左边光标开始，怎么设置。疑似bug，谢谢解答

### ISSUE THREAD

**Issue by EthanDCX** [wangfupeng1988/wangEditor#1001]
![image](https://user-images.githubusercontent.com/18240991/30357775-1e0a84d6-9873-11e7-941e-037a77681d78.png)
默认光标就在每行中心，editor的div左右的空格都删了呀

**Comment by wangfupeng1988** [comment]
官网就没有这个问题，肯定是你其他 css 和编辑区域 css 的冲突，你检查一下吧。
