### ISSUE TITLE
是否可以提供wangeditor3通过js上传七牛云的demo

### ISSUE THREAD

**Issue by MrNiceWangwendi** [wangfupeng1988/wangEditor#1003]
根据wangeditor2文档中上传七牛云的方法在wangeditor3上无法适用 可否写一篇wangeditor3上传七牛云的文档或者demo

**Comment by wangfupeng1988** [comment]
我本周末关注该问题，升级之后即可有文档支持。请随时关注新版发布动态。

**Comment by wangfupeng1988** [comment]
v3.0.9 已经支持 https://www.kancloud.cn/wangfupeng/wangeditor3/405041
