### ISSUE TITLE
不能动态设置编辑器的样式

### ISSUE THREAD

**Issue by codinglilong** [wangfupeng1988/wangEditor#1004]
我想设置自定义编辑器的长宽，貌似不行。
外层定义的是200px，里面是貌似是写死的300,
我以为用editor.customConfig.height = 200;能解决，但是不起作用。
除非不定义，用默认的300.

**Comment by codinglilong** [comment]
![2](https://user-images.githubusercontent.com/20492424/30410296-bff3d8c8-993c-11e7-8ee0-61e69ed1e4b7.png)
![3](https://user-images.githubusercontent.com/20492424/30410299-c95604ea-993c-11e7-9969-c3bc87957a1c.png)
![4](https://user-images.githubusercontent.com/20492424/30410305-cda8e864-993c-11e7-924a-e2839ac3fd7b.png)

**Comment by yangxiaokun** [comment]
你还需要覆盖内层编辑框的高度 ，css类为w-e-text-container

**Comment by codinglilong** [comment]
@yangxiaokun 这种方法不可取啊，会很费事的。我做为一个组件，很多人会用，那么每个人都有自己想要的样式都要去覆盖这个样式会很费事。有可能会冲突不小心覆盖别人的，维护下来也有点不方便

**Comment by yangxiaokun** [comment]
@codinglilong 我这边项目里就用到了两三次富文本而已，加个前置css控制下范围就行了。
如果你项目里到处都要用到这个，那确实API更合适点，你可以问问作者为啥不设置这个API啊。。。
反正对我没啥影响，多写几行CSS就够了

**Comment by wangfupeng1988** [comment]
https://www.kancloud.cn/wangfupeng/wangeditor3/335771  试试这种方式

**Comment by gzanthony** [comment]
我的方法，是在 editor.create() 之后再加一句 

`
$("div.w-e-text-container").css({
    height: '100px'
});
`

搞定~
