### ISSUE TITLE
菜单栏能否支持自定义按钮？方便调用七牛直传sdk类方法

### ISSUE THREAD

**Issue by yangxiaokun** [wangfupeng1988/wangEditor#1005]
项目里用到的是七牛，基于七牛sdk封装了一层依赖按钮id进行触发的上传，
如果通过图片自定义上传的话，需要手写所有的七牛上传步骤，
能否在菜单栏新增自定义按钮项？传入id，文字或图标，在菜单栏内新增自定义菜单，以此来调用自有的方法

**Comment by yangxiaokun** [comment]
唔。。现在的方法是 create以后 通过document.getElement的方式 获取到 菜单栏，然后往里面插入一个图片按钮，倒也能实现自定义按钮的效果，哈哈哈

**Comment by MrNiceWangwendi** [comment]
请问是七牛云js上传吗 可否共享个demo 897136043@qq.com

**Comment by yangxiaokun** [comment]
demo就不必了，七牛上传的sdk不是基于 id选择按钮的么，思路就是create编辑器以后，通过css往菜单栏里插入一个带id的dom，七牛的方法指向这个 id 就可以啦

**Comment by wangfupeng1988** [comment]
参见 https://github.com/wangfupeng1988/wangEditor/issues/1003  本周末关注处理
