### ISSUE TITLE
请问下,菜单的图标是哪个的字体啊

### ISSUE THREAD

**Issue by oblivioussing** [wangfupeng1988/wangEditor#1006]
是从这儿http://fontello.com/选的嘛，但是看了下，图标貌似又不一样

**Comment by wangfupeng1988** [comment]
是从 https://icomoon.io/ 打包下载的。可以自定义选择字体打包，体积会很小。

**Comment by oblivioussing** [comment]
谢了😄

发自我的 iPhone

在 2017年9月16日，下午3:27，王福朋 <notifications@github.com<mailto:notifications@github.com>> 写道：


Closed #1006<https://github.com/wangfupeng1988/wangEditor/issues/1006>.
