### ISSUE TITLE
请大神解答

### ISSUE THREAD

**Issue by GoddessRong** [wangfupeng1988/wangEditor#1007]
如何判断是标题还是内容
比如  `editor.txt.html（）`获取的是所有内容  那我如何想要获取`<h1></h1>`标签的内容 该如何操作

**Comment by yangxiaokun** [comment]
通过h标签获取？没见过那个编辑器能实现这样的直接读取的功能。。

**Comment by wangfupeng1988** [comment]
获取了 html 内容之后，自己分析一下吧，没有现有的方法直接获取`<h1>`
