### ISSUE TITLE
编辑器的下拉菜单的样式可以进行编辑吗

### ISSUE THREAD

**Issue by xiaoqi18234090171** [wangfupeng1988/wangEditor#1008]
@wangfupeng1988 
现在的下拉菜单长度有点长，页面展示不是很友好，可以控制下拉菜单的高度或者下拉菜单出现的位置吗，例如菜单向上展开

**Comment by xiaoqi18234090171** [comment]
![qq 20170917140117](https://user-images.githubusercontent.com/13749815/30518436-c0e58c06-9bb0-11e7-8a35-4120e3bdc0bd.png)

**Comment by xiaoqi18234090171** [comment]
![image](https://user-images.githubusercontent.com/13749815/30518449-f50b86ca-9bb0-11e7-9b63-7aeff1c592c9.png)
编辑区域比较小，如图所示

**Comment by wangfupeng1988** [comment]
这个暂时没有配置支持。有兴趣可以看看源码中的 css 样式，自己去做一下修改。
