### ISSUE TITLE
从电脑剪切板删帖过来内容, 怎么去掉html标签

### ISSUE THREAD

**Issue by liaohui1080** [wangfupeng1988/wangEditor#101]
从电脑剪切板删帖过来内容, 怎么去掉html标签
,比如我从一个网友复制了一段内容, 粘贴到便器里面的时候,便器会把这段内容的html也一块粘贴进来

**Comment by wangfupeng1988** [comment]
目前官网demo的效果是：
1. 我复制：
<img width="398" alt="qq20151230-1 2x" src="https://cloud.githubusercontent.com/assets/9583120/12046470/9687e47c-aef4-11e5-9ee3-df9d2ffa1ba1.png">

2. 粘贴到编辑器中的样子：
<img width="359" alt="qq20151230-2 2x" src="https://cloud.githubusercontent.com/assets/9583120/12046471/9ba649f8-aef4-11e5-8ed7-55fc9141e1fb.png">

**Comment by liaohui1080** [comment]
我是复制什么样粘贴还是什么样

2015-12-30 12:55 GMT+08:00 王福朋 <notifications@github.com>:

**Comment by wangfupeng1988** [comment]
> 如果你的项目中编辑器没有这个效果，可去官网下载最新的js文件。

这句话你没看到吧？

**Comment by liaohui1080** [comment]
确实没看到,
github上,是最新的版本吗


原始邮件
发件人:王福朋notifications@github.com
收件人:wangfupeng1988/wangEditorwangEditor@noreply.github.com
抄送:china girlmy300ge@gmail.com
发送时间:2015年12月30日(周三) 13:32
主题:Re: [wangEditor] 从电脑剪切板删帖过来内容, 怎么去掉html标签 (#101)


如果你的项目中编辑器没有这个效果，可去官网下载最新的js文件。
这句话你没看到吧？

**Comment by wangfupeng1988** [comment]
https://github.com/wangfupeng1988/wangEditor/releases/tag/v1.3.13.2
