### ISSUE TITLE
Ctrl+A 全选在Ctrl+C、Ctrl+V第一次粘贴无效

### ISSUE THREAD

**Issue by zhixinglvren** [wangfupeng1988/wangEditor#1011]
Ctrl+A 全选在Ctrl+C、Ctrl+V第一次粘贴无效

这个问题在官网：http://www.wangeditor.com/ 的案例中同样存在。

**Comment by wangfupeng1988** [comment]
详细描述一下你的操作场景、包括系统、浏览器，我没有复现这个问题
