### ISSUE TITLE
空内容并不是真的空内容

### ISSUE THREAD

**Issue by jcplus** [wangfupeng1988/wangEditor#1013]
初始化后的编辑器内容应该是真正的空，目前初始化之后，立刻获取内容得到的html是
`<p><br></p>`
如果在刚刚初始化时候点字体样式但是不输入内容获取到的html是
`<p>​<u>​</u>​<br></p>`但是不局限于此
如果刚刚初始化插入图片获取到的html是
`<p><img src="http://media.ezydvd.com.au/170/ed2/49c68cbe-8eb5-11e7-9bcd-0242ac110004.jpg" style="max-width:100%;"><br></p>`
这样造成的结果是不好判断内容是不是为空，是不是可以存储到数据库。仅仅凭借text()得到空的结果无法判断是不是还有图片

**Comment by wangfupeng1988** [comment]
分多种情况判断啊：
第一，看没有图片
第二，如果没有图片，用 text() 判断
