### ISSUE TITLE
引用不能取消

### ISSUE THREAD

**Issue by jcplus** [wangfupeng1988/wangEditor#1014]
点引用“双引号”输入内容之后回车是一行新的引用
这时候点“双引号”并不能取消引用格式

**Comment by wangfupeng1988** [comment]
> 点引用“双引号”输入内容之后回车是一行新的引用

现在的情况是，选中一行点击，该行成为引用模式。如果光标定位到该行最后，回车之后，引用格式会自动取消。

> 这时候点“双引号”并不能取消引用格式

目前引用菜单没有取消功能，我记录下这个问题，近期升级改动。

**Comment by IVANLEE99** [comment]
![image](https://user-images.githubusercontent.com/18308725/30683744-383fd30a-9ee1-11e7-8aef-920956eb4194.png)
