### ISSUE TITLE
上传图片后，在服务器端如何获取数据？

### ISSUE THREAD

**Issue by taurusu28** [wangfupeng1988/wangEditor#1015]
服务器端语言是PHP，ajax提交到某个页面后如何得到上传上来的图片，以前都是写个input，input有个name值，靠这个值获取数据，在这个编辑器里该怎么用，谢谢！

**Comment by taurusu28** [comment]
解决了，editor.customConfig.uploadFileName = 'yourFileName'，第一次接触，还需要多学习！

**Comment by wangfupeng1988** [comment]
其实没啥可学习的，详细看一下文档就好，文档内容也不多

**Comment by taurusu28** [comment]
请问如果不设置默认值是啥？

**Comment by wangfupeng1988** [comment]
默认值是选中的图片文件的名称
