### ISSUE TITLE
求增加可以自己添加自定义功能按钮的钩子，和修改现有菜单项的功能

### ISSUE THREAD

**Issue by jojuniori** [wangfupeng1988/wangEditor#1016]
比如要在菜单里增加一个功能按钮
用于在光标处插入`<audio src="someaudio.wav">`
感觉现在的话就只有
1. 将wangEditor.js魔改
2. `editor.txt.append('<audio src="someaudio.wav">')`
这样不尽人意的实现方案

以及求增加可以修改现有菜单项的功能
比如要将head菜单中的 `<h1>H1</h1>` 修改为 `<p class="title">大标题</p>` 的时候
_(:з」∠)_ 现在也只能魔改wangEditor.js来实现……

**Comment by wangfupeng1988** [comment]
> 求增加可以修改现有菜单项的功能 

没明白啥意思

> 比如要将head菜单中的 <h1>H1</h1> 修改为 <p class="title">大标题</p> 的时候

这种修改无法通过固定的菜单实现

**Comment by jojuniori** [comment]
|ω•`) 好吧，那增加菜单的钩子的话呢？……

**Comment by jojuniori** [comment]
或者有个能在光标处插入数据而不是editor.txt.append那样增加在底部的功能？

**Comment by wangfupeng1988** [comment]
https://www.kancloud.cn/wangfupeng/wangeditor3/404586

试试`editor.do.cmd('insertHTML', '<p>...</p>')`
