### ISSUE TITLE
内容区使用textarea就无法使用工具栏了？

### ISSUE THREAD

**Issue by CQBoyBrand** [wangfupeng1988/wangEditor#1018]
还是我的方式不对？求助。。如何使用textarea。。没找到相关有效的资料。在我的系统中在用div方式输入内容后不能使用backspace键删除。。只能使用delete键删除。。

**Comment by wangfupeng1988** [comment]
> 如何使用textarea。。没找到相关有效的资料

查查已经关闭的 issue ，解答过好几次了

> 在我的系统中在用div方式输入内容后不能使用backspace键删除。。只能使用delete键删除

试试官网也这样吗？

**Comment by CQBoyBrand** [comment]
谢谢，已经解决，是和我们自己系统的框架有点冲突
