### ISSUE TITLE
liunx运行npm install wangeditor

### ISSUE THREAD

**Issue by chenyongwade** [wangfupeng1988/wangEditor#1019]
liunx运行npm install wangeditor后，laravel public目录下只有fonts，css，没有js，是没有装完整，还是其他什么原因

**Comment by wangfupeng1988** [comment]
那不应该，你再其他地方安装试一下

**Comment by chenyongwade** [comment]
root@iZ23b93s9duZ:/var/www/laravel/laravel54# cnpm install wangeditor
? Installed 1 packages
? Linked 0 latest versions
? Run 0 scripts
? All packages installed (used 152ms, speed 22.01kB/s, json 1(3.35kB), tarball 0B)
root@iZ23b93s9duZ:/var/www/laravel/laravel54# cd public/
root@iZ23b93s9duZ:/var/www/laravel/laravel54/public# ls
css  favicon.ico  fonts  index.php  js	mix-manifest.json  robots.txt  web.config
root@iZ23b93s9duZ:/var/www/laravel/laravel54/public# cd js/
root@iZ23b93s9duZ:/var/www/laravel/laravel54/public/js# ls
app.js	
root@iZ23b93s9duZ:/var/www/laravel/laravel54/public/js# 
试过了就是没有，运行cnpm install wangeditor它默认安装那个版本呀

**Comment by wangfupeng1988** [comment]
你先用 npm 安装，先别用 cnpm ，等 npm 安装OK之后，再用 cnpm

**Comment by chenyongwade** [comment]
嗯，可以了，是因为npm版本过低，感谢
