### ISSUE TITLE
能否下个版本更新一下新浪的表情包？

### ISSUE THREAD

**Issue by cdwmhcc** [wangfupeng1988/wangEditor#102]
https://api.weibo.com/2/emotions.json?source=1362404091

这是api地址

**Comment by wangfupeng1988** [comment]
我不知道这个表情包是给什么用的，如果给编辑器，里面的这个  `"value":"[挤眼]","picid":""` 有什么用呢？

**Comment by wangfupeng1988** [comment]
2.0.0基础版已经发布，接下来就是对2.0的升级和维护。其中标准表情包的这个功能，我也已经排在升级计划当中，年后会根据优先级来一步一步加上。
