### ISSUE TITLE
wangEditor3图片上传成功后，不能编辑图片大小，2版本是可以拖拽编辑的

### ISSUE THREAD

**Issue by mabi86** [wangfupeng1988/wangEditor#1020]
![qq 20170921141456](https://user-images.githubusercontent.com/8122404/30681269-48d700c6-9ed7-11e7-9894-1360c6fe27df.png)

老王你好，如上图，wangEditor2版本上传图片后可以调整图片大小，3版本好像没有这功能？

**Comment by wangfupeng1988** [comment]
选中图片，点击菜单栏中的“图片”菜单，可选择大小。

这块功能缩减了一下，为了好维护。此前那的功能设计过于复杂了，用的不多，维护成本太高。
