### ISSUE TITLE
点击图片上传后，如果这张图片不想要用delete删除了，怎么触发来删除已经上传的文件呢

### ISSUE THREAD

**Issue by tanghao0550** [wangfupeng1988/wangEditor#1021]
我目前的想法是等文本框编辑完之后，点击提交，获取文本框内的代码，然后获取所有img的src，没有的src就删除。但感觉不是太好，希望有一个可以直接触发删除的功能，也许有但我没发现，求作者知道，感谢

**Comment by wangfupeng1988** [comment]
这个前端不好监控，后端来做这件事情比较靠谱。

后端每接收到一次图片上传，都将图片地址记录到一个列表中。最终保存的时候，再分析文章中所有的 img 的 src ，然后对比图片的列表。列表中不存在的，就删除掉。
