### ISSUE TITLE
中文文字 设置字体失效

### ISSUE THREAD

**Issue by ChineseCabbageW** [wangfupeng1988/wangEditor#1022]
![image](https://user-images.githubusercontent.com/20508086/30770722-4ca029aa-a06a-11e7-8ba8-a6792e4e7a12.png)

字体设置失败 见上图

**Comment by wangfupeng1988** [comment]
你的是 v2 版本，现在已经不再技术支持，抱歉。

v3 版本开始，编辑器的内置功能已经不再包含“字体”和“字号”的设置了，这些都要通过自己的 css 来控制。如果自己有需要，可以 fork 源码再进行二次开发。
