### ISSUE TITLE
编辑器onchange监控输入bug

### ISSUE THREAD

**Issue by ScholatLouis** [wangfupeng1988/wangEditor#1025]
`if (currentHtml.length === beforeChangeHtml.length ) {
                    return;
                }`

对于keyup事件，通过该条件来判断是否更新内容存在bug。在实际应用过程中出现过当使用中文输入法输入如：dd，然后敲下空格输入如：等等。结果编辑器获取的内容为
`var currentHtml = this.txt.html();`
dd，而不是等等。

这个问题的出现跟这个判断有关系，在自己的项目中修改了该判断条件修复了此问题

**Comment by wangfupeng1988** [comment]
OK 我记录下，下次升级修复这个问题

**Comment by wangfupeng1988** [comment]
我试了一下，中文输入法输入“等等“之前，显示的并不是`dd`，而是`d’d`，因此还是能判断出来的

**Comment by ScholatLouis** [comment]
其实你要多试几次 这个判断无效的情况不是每次都出现的
然后在判断语句中你可以打印下console 一旦进入了 也就知道了

**Comment by wangfupeng1988** [comment]
你可以先把源码中`if (currentHtml.length === beforeChangeHtml.length ) { return; }`去掉

**Comment by xulei131401** [comment]
3.0.12中此问题依然存在

**Comment by wangfupeng1988** [comment]
@xulei131401 我试了一下，中文输入法输入“等等“之前，显示的并不是dd，而是d’d，因此还是能判断出来的。

你那里不是这种情况？
