### ISSUE TITLE
拓展性问题 请教

### ISSUE THREAD

**Issue by ScholatLouis** [wangfupeng1988/wangEditor#1028]
在使用编辑器的过程中，有个问题想请教下：
编辑器对于链接link 插入并没有做格式校验
我想请问 如果我要添加格式校验 是不是只能去修改源码？没有对外暴露的接口吗？

总的来说 菜单栏目定制相对薄弱，只能选择是否使用某个菜单选项，如果要对该菜单选项做定制 目前看到的好像只能去修改源码了

不知道是不是我没有了解清楚，如果有其他方法还请lz告知哈

**Comment by wangfupeng1988** [comment]
感谢反馈，插入样式的格式校验，确实应该加上。但是目前确实只能去修改源码。

我记录下这个问题，后面升级的时候，多考虑一下各个菜单的常用配置

**Comment by ScholatLouis** [comment]
建议提高编辑器的拓展性
比如url验证的这个问题 是根据不同业务决定的 如存在域名白名单或者其他要求什么的
如果把验证写到源码里 就会每次遇到不同业务就要去改源码 而且改了源码之后 packjson的文件依赖 也不能直接通过npm install解决问题 还要导出拷贝修改后的源码 对于编辑器的推广使用 感觉不友好哈

**Comment by wangfupeng1988** [comment]
> 比如url验证的这个问题 是根据不同业务决定的 如存在域名白名单或者其他要求什么的

直接开放一个验证函数

**Comment by wangfupeng1988** [comment]
链接的校验，下一个版本会升级发布（请关注升级动态）

其他的可配置项，再慢慢升级完善吧。
