### ISSUE TITLE
关于图片base64上传跟链接上传问题

### ISSUE THREAD

**Issue by dorneal** [wangfupeng1988/wangEditor#1029]
base64上传图片，如果上传过多，就会出现在chrome显示不完整，其他的浏览器可以，chrome浏览器缩小时，又完全显示。另外外加链接时，整个页面的样式都改变了，无下划线的变成了下划线的a:visited样式。
以及字体样式也发生了变化。详情请看www.nealblog.com的笔记模块中的“环境配置——Sublime Text3配置”,"环境配置——JDK配置"。

**Comment by wangfupeng1988** [comment]
请验证官网是否也有这个问题。如果有，给一个详细的复现步骤，能让我快速复现问题。

**Comment by dorneal** [comment]
详情请看www.nealblog.com的笔记模块中的“环境配置——Sublime Text3配置”,"环境配置——JDK配置"。
我后台使用的就是base64文件上传，以及关闭了粘贴样式，使用的word编辑的文本，然后在慢慢选择上传的图片，但是出现了这种情况，应该不是样式设置问题，其他上传过得笔记不带图片以及链接的并未出现这种情况。

**Comment by JankChen** [comment]
base64上传图片  如果 上传的图片尺寸过大 直接导致无法上传，

**Comment by wangfupeng1988** [comment]
过多或者过大图片的上传，建议还是直接传文件，base64用多了可能有分享
