### ISSUE TITLE
引用功能的两个bug（如图）

### ISSUE THREAD

**Issue by xcheese** [wangfupeng1988/wangEditor#103]
![image](https://cloud.githubusercontent.com/assets/9137396/12078233/9630225c-b244-11e5-97fe-b3a26551eebc.png)
![image](https://cloud.githubusercontent.com/assets/9137396/12078234/a10d5f3c-b244-11e5-8db3-a2a814dff354.png)

**Comment by wangfupeng1988** [comment]
恩。这个问题前几天有人提出来过，我也记录下来了，近期会改掉的。

**Comment by wangfupeng1988** [comment]
2.0已经发布，你说的问题都已经在2.0中修复。可去官网demo中验证一下。
