### ISSUE TITLE
关于图片名包含"[]"上传的问题

### ISSUE THREAD

**Issue by HSwift** [wangfupeng1988/wangEditor#1030]
服务器环境nginx+php7
上传的时候formdata的数据是正确的，但是php没有收到数据，也就是$_FILES为空
初步测试发现formdata.append方法的第一个参数不能包含方括号
而源码第3730行把文件名作为append方法的第一个参数，导致出错

------
至于问什么append方法的第一个参数不嫩包含方括号，我也没搞明白。。。

**Comment by wangfupeng1988** [comment]
> formdata.append方法的第一个参数不能包含方括号

这里我没做限制。不过，参数值中的特殊字符，是否应该 encode 之后再传递？

**Comment by HSwift** [comment]
我觉得可以把第一个参数固定下来比如formdata.append("name", file);

**Comment by wangfupeng1988** [comment]
> 我觉得可以把第一个参数固定下来比如formdata.append("file", file);

这跟`[]`有啥关系？

**Comment by HSwift** [comment]
避免第一个参数包含'[]'啊

**Comment by wangfupeng1988** [comment]
> 避免第一个参数包含'[]'啊

这些都是可配置的，编辑器本身不会出现'[]'

**Comment by anruyi** [comment]
有没有php上传图片的demo，求帮助！
