### ISSUE TITLE
创建编辑器之后无头部菜单, 实在是没发现哪里写错了.

### ISSUE THREAD

**Issue by 531086032** [wangfupeng1988/wangEditor#1031]
wangeditor使用的是最新版.往下的版本也试过. 
ueditor,quill,kindeditor,layeditor等富文本编辑器都写过例子测试过.创建均无问题.
页面代码:
![qq 20170927105445](https://user-images.githubusercontent.com/31950828/30894182-cb8900fe-a374-11e7-9a26-8853c3acca63.png)
效果图:
![qq 20170927105504](https://user-images.githubusercontent.com/31950828/30894197-e0ab7bc4-a374-11e7-9e4e-5ceac67a7521.png)

生成页面源码: 头部的class属性都是无空格连着标签元素的.本人并没有在页面做处理标签中空格的动作
![000001](https://user-images.githubusercontent.com/31950828/30894465-7a5ddd38-a376-11e7-99f9-a134e24f4a4a.png)

非常疑惑.如果页面有问题,其他富文本创建均无问题, 如果页面没问题,其他使用者好像都是创建成功的. 请前端找寻过原因,无果.望作者帮助

**Comment by wangfupeng1988** [comment]
你用一个空白页面创建一个wangEditor编辑器，看是否有头部菜单？
这种问题就得细分开来找，把你页面的其他影响部分，依次屏蔽掉，挨个试，就能找到哪部分影响了。
