### ISSUE TITLE
上传图片失败

### ISSUE THREAD

**Issue by chenyongwade** [wangfupeng1988/wangEditor#1032]
一直弹出上传图片失败
 //图片上传
    public function imageUpload(Request $request){

        $path = $request->file('chenyong')->storePublicly(md5(time()));
        return asset('public/storage/'.$path);
    }

    editor.customConfig.uploadImgHooks = {
        fail: function (xhr, editor, result) {          
        },
        error: function (xhr, editor) {
        },
        success: function (xhr, editor, result) {           
        },
    }
弹出上传图片失败，会进入到 fail: function方法中，
返回200，可以得到返回结果
http://study.chenyong1992.com/public/storage/e5b1a1e858a1a24148adacd60e140dc0/s5MYDTa1SONBwHVbBFreAU88AGuRW2lVQWkw1F01.png

**Comment by wangfupeng1988** [comment]
v3 版本的返回格式已经变了，详细查看文档 https://www.kancloud.cn/wangfupeng/wangeditor3/335782。

另外，图片上传出现问题，可以开启 debug 模式 https://www.kancloud.cn/wangfupeng/wangeditor3/335778 ，然后看看控制台的报错

**Comment by Zeus-Iqd** [comment]
我也遇到了，有时候会成功，有时候会失败。
