### ISSUE TITLE
关于每次上传图片修改参数问题

### ISSUE THREAD

**Issue by llforgit** [wangfupeng1988/wangEditor#1036]
由于页面风格的特殊性   ****每次上传图片的时候需要改变参数的值****  
不知道作者有没有好的实现方式
现在是基于wangeditor无法实现每次上传修改自定义参数的值

**Comment by wangfupeng1988** [comment]
哦 明白你意思了。这样，你每次上传图片之前，把`editor.config. uploadImgParams = {...}`就行了，试一下。

**Comment by llforgit** [comment]
首先感谢作者的回答

我试了，不行，我下面表述的可能不准确啊
我看了下你的源码，当每次执行自定义的方法的时候已经将参数添加到fordata中了，如果要达到想要的效果要执行下面类似的操作
`editor.customConfig.uploadImgHooks = {
    before: function (xhr, editor, files) {
        重新装填formdata参数(伪实现) 几乎不可能
        或者
        现在开始装填formdata参数    我觉得可行
    },`
或者作者有更好的方法  请指教

**Comment by llforgit** [comment]
作者你好， 我把源码修改了下 实现了每次上传图片的时候可以自定义参数和参数值，不知道可不可以经过你的审核并加入到下个版本里
修改部分：没有动主体代码 只是修改了下函数执行顺序
当执行hooks.before的时候再去装填formdata
望采纳，谢谢

**Comment by wangfupeng1988** [comment]
每次上传时候修改`editor.config.uploadImgParams`肯定是可行的，你可以监控一下
 https://github.com/wangfupeng1988/wangEditor/blob/master/release/wangEditor.js#L3737 这一行的变量值

**Comment by undermoodzyx** [comment]
如果是在上传图片的钩子里面添加或修改 formData 参数呢？
看了文档里面，好像是只能通过文件上传钩子获取文件对象，如果在上传前需要获取文件对象的内容，并做一些处理，同时修改 formData 里面的内容。根据目前的源码实现，好像是做不到的。
如果有方法能够实现，还请告知一下，谢谢。

**Comment by SANEBEN** [comment]
我也遇到同样的问题了，请问有好的解决办法了吗
