### ISSUE TITLE
wangEditor with angular 

### ISSUE THREAD

**Issue by losye** [wangfupeng1988/wangEditor#1037]
i use wangEditor in my angular project 

but some problem happened  like this 

Uncaught SyntaxError: Unexpected token . wangEditor.min.css:1

The given range isn't in document. wangEditor.js:3464

**Comment by wangfupeng1988** [comment]
ng 我没有用过，不过你可参考 https://www.kancloud.cn/wangfupeng/wangeditor3/365539
