### ISSUE TITLE
在react中禁用启用功能没用,报错undefined

### ISSUE THREAD

**Issue by wxxxxxxxx** [wangfupeng1988/wangEditor#1038]
editor.$textElem[0].contenteditable='false';

**Comment by wangfupeng1988** [comment]
打印`editor.$textElem[0]`看看是啥

**Comment by wxxxxxxxx** [comment]
打印出来都是undefined 啊

**Comment by wxxxxxxxx** [comment]
除了editor.id打印没问题,打印editor.xxxxxxx都是undefined

**Comment by wangfupeng1988** [comment]
你没执行`editor.create()`吧？

**Comment by wxxxxxxxx** [comment]
const editor = new E("#editorElem");
                // 使用 onchange 函数监听内容的变化，并实时更新到 state 中
                editor.customConfig.onchange = html => {
                    this.setState({
                        editorContent: html
                    });
                }
                console.log(editor)
                console.log(editor.uploadImg);
                // editor.$textElem[0].contenteditable='false';
                //contenteditable=false;
                // editor.textElem.attr('contenteditable', false);
                // $(editor.$textElem).attr('contenteditable', false);
                // console.log(editor.contentEditable);
                // editor.disable(false);
                editor.customConfig.menus = [
                        'head',  // 标题
                        'bold',  // 粗体
                        // 'italic',  // 斜体
                        // 'underline',  // 下划线
                        // 'strikeThrough',  // 删除线
                        'foreColor',  // 文字颜色
                        'backColor',  // 背景颜色
                        // 'link',  // 插入链接
                        'list',  // 列表
                        'justify',  // 对齐方式
                        // 'quote',  // 引用
                        // 'emoticon',  // 表情
                        // 'image',  // 插入图片
                        'table',  // 表格
                        // 'video',  // 插入视频
                        // 'code',  // 插入代码
                        'undo',  // 撤销
                        // 'redo'  // 重复
                ]

                editor.create()
            }
你所说的执行了的

**Comment by wangfupeng1988** [comment]
那你只能先抛开 React 环境，现在简单的静态页面上做一个 demo 看看有没有你上述的问题

**Comment by hyliuzhenhao** [comment]
我也是editor.disable()时报undefined,然后editor.$textElem[0]['contentEditable'] 这样可以获取到
