### ISSUE TITLE
图片上传后，查看生成的HTML中引号变成了 &quot;

### ISSUE THREAD

**Issue by bigrats** [wangfupeng1988/wangEditor#104]
``<img src=&quot;/zk/fs/down/2f11394640cb43f691394640cbd3f677
&quot; wangeditor_img_max_width_mark=&quot;1&quot; style=&quot;max-width: 100%;&quot;>``

![image](https://cloud.githubusercontent.com/assets/3138644/12112013/a9629936-b3d4-11e5-9726-aa2cb50e2509.png)

**Comment by wangfupeng1988** [comment]
可以这样简单的验证一下：
你上传图片到server端，server端要返回带有图片 url 的数据，你通过后台断点检测、或者浏览器抓包检测，看看返回的这个url是否也是这个样子的？

**Comment by bigrats** [comment]
![image](https://cloud.githubusercontent.com/assets/3138644/12161701/25c342cc-b534-11e5-840d-8b863027e44f.png)

![image](https://cloud.githubusercontent.com/assets/3138644/12161703/28615442-b534-11e5-8197-c4218e026c21.png)

![image](https://cloud.githubusercontent.com/assets/3138644/12161707/3082860a-b534-11e5-9b3c-bb3fe0a6c46b.png)

查看DOM：
![image](https://cloud.githubusercontent.com/assets/3138644/12161716/39b0b774-b534-11e5-85bf-8d3599965a86.png)

**Comment by wangfupeng1988** [comment]
这个情况我还真没见过。我现在看不到你的网页和代码，只能猜测着给你出出主意。

1. 你看看编辑器自带的插入网络图片之后，再查看源代码是不是也是这个情况；
2. 你返回的url目前不带后缀名的，你加上后缀名试试；

目前想到的就是这两点。。。

**Comment by bigrats** [comment]
好的，等你的新版本出来再检查

**Comment by wangfupeng1988** [comment]
2.0已经发布，可去官网demo来验证这个问题是否还存在。
