### ISSUE TITLE
设置uploadFileName上传多张图片问题

### ISSUE THREAD

**Issue by gd78861139** [wangfupeng1988/wangEditor#1043]
一旦设置了uploadFileName，就会导致上传多张图片的名称是一样的，这样PHP通过名称只能获取第一张图片，我不清楚是否需要再设置什么参数；
后来我是通过修改wangEditor解决的，增加了在循环里增加了i，让每张图片的名称都变成img1，img2...，类似这样，还请博主看下
`var formdata = new FormData();
        arrForEach(resultFiles, function (file,i) {
        	//根据i 区分不同的上传图片名称
            var name = uploadFileName+i || file.name;
            formdata.append(name, file);
        });`

**Comment by wangfupeng1988** [comment]
你可以不设置`uploadFileName`，wangEditor 会自动去文件名作为 filename，这样不能满足需求吗？

**Comment by zhuqingsong59** [comment]
遍历文件列表多次调用上传图片接口的方式来实现上传多张文件不可以么？我看webUploader就是这么做的

**Comment by wangfupeng1988** [comment]
这样会影响性能，一次上传多个比较高效

**Comment by muding** [comment]
不要设置名称，我是在php 进行遍历的，
