### ISSUE TITLE
在弹出层中使用编辑器, 工具栏无法使用.

### ISSUE THREAD

**Issue by Sydney710** [wangfupeng1988/wangEditor#1046]
我在bootstrap modal中使用tab-pane并在某个tab-pane中使用该编辑器.
现象:工具栏能正常显示但是无法使用(全部), 并且工具栏有弹出层的无法显示(已设置customConfig.zIndex)

光标能放到工具栏上
![image](https://user-images.githubusercontent.com/6048725/31374065-0a56ce4c-adcf-11e7-89c9-0fa371c1476f.png)

**Comment by wangfupeng1988** [comment]
从你的情况看来，怀疑上面有透明浮层覆盖了，用chrome检查工具看一下

**Comment by CodeKingxyz** [comment]
我也是这个问题，请问你现在解决了吗？
