### ISSUE TITLE
在vue里面使用wangeditor,带token上传本地图片到七牛（希望可以帮到大家）

### ISSUE THREAD

**Issue by zhongziqi** [wangfupeng1988/wangEditor#1047]
![image](https://user-images.githubusercontent.com/23629116/31480736-1eab98bc-af52-11e7-84bb-719155b6c82d.png)
这个是template下的代码
![image](https://user-images.githubusercontent.com/23629116/31480763-3c5ba9a6-af52-11e7-9e84-bb51dfab4ba1.png)
这个放在mounted里面，【在这里我用到了两个编辑器】
![image](https://user-images.githubusercontent.com/23629116/31480784-5d9b7ed4-af52-11e7-8299-90b43b5c0a7a.png)
里面的token是由后端传过来的，这里根据大家的情况啦

**Comment by zetianul** [comment]
您好，请问能提供更详细的代码吗，截图看起来不是很全面

**Comment by padipata** [comment]
楼主牛掰

**Comment by wangfupeng1988** [comment]
希望能把关键代码开源出来、发链接，给大家分享。👍

**Comment by linlin666** [comment]
请问有具体一些的代码吗

**Comment by wangfupeng1988** [comment]
@zhongziqi 希望可以帮助回答这个问题 https://github.com/wangfupeng1988/wangEditor/issues/1237 多谢！

**Comment by zhongziqi** [comment]
https://github.com/zhongziqi/wangEditor-vue.git
已经将我的代码整理出来了，这里再次谢谢王大哥的编辑器！

**Comment by shiliangL** [comment]
data() {
    return {
      // 文本
      initContent: '<p>要初始化的内容</p>',
      content: '',
      text: '', // 不含html标签，纯文本
      VueEditorOptions: {
        width: '750px', // 自定义单位，字符串
        height: '420px', // 自定义单位，字符串
        // 更多配置项请看官网或者官网文档
        // qiniu: true,
        uploadImgServer: 'http://up-z2.qiniu.com',
        uploadFileName: 'file',
        uploadImgHooks: {
          success: function(xhr, editor, result) {
            console.log(xhr, editor, result)
            // 图片上传并返回结果，图片插入成功之后触发
            // xhr 是 XMLHttpRequst 对象，editor 是编辑器对象，result 是服务器端返回的结果
          }
        },
        uploadImgParams: {
          token: tk
        },
        menus: [
          'head', // 标题
          'bold', // 粗体
          'fontSize', // 字号
          'italic', // 斜体
          'underline', // 下划线
          'strikeThrough', // 删除线
          'foreColor', // 文字颜色
          'backColor', // 背景颜色
          'list', // 列表
          'justify', // 对齐方式
          'image', // 插入图片
          'undo', // 撤销
          'redo' // 重复
        ],
        pasteFilterStyle: true // 打开/关闭粘贴样式的过滤
      }
    }
  },

vue 中配置使用，图片接口已经调通了，但是还是被 alert 弹出 报错失败，怎么处理
