### ISSUE TITLE
在弹出框里面，无法选中文字

### ISSUE THREAD

**Issue by yk0505** [wangfupeng1988/wangEditor#1049]
@wangfupeng1988 
你好，在弹出的窗体里面，无法选中编辑的文本，以下是效果图
![aa](https://user-images.githubusercontent.com/22908565/31486496-3c25404c-af6a-11e7-88c8-ff40d212c567.png)

**Comment by wangfupeng1988** [comment]
只有弹出窗口的时候有这个问题吗？普通的使用有没有这个问题？

无法选中，是从什么地方拖拽鼠标无法选中？从“文”字后面拖拽鼠标，看能否选中？

**Comment by yk0505** [comment]
谢谢 @wangfupeng1988 ，找到了解决方法。

形成上面那个原因是应为，我把富文本编辑器，用在了chrome浏览器的插件当中。

富文本编辑器插件本身是没什么问题的，可以直接运用在chrome的插件当中，但是如果在插件中弹出弹框在进行初始化富文本，就会发生一些意想不到的错误。

最后的解决方法是，我把弹框给删除掉了，用chrome再打开了，一个新的窗口，在新窗口里面和打开它的页面，两个页面使用chrome浏览器自带的sendMessage和onMessage进行通信，最后完成了我想要的效果，并且超出了我的预期。

感谢大神解答，谢谢。

10月24日  祝您节日愉快。
