### ISSUE TITLE
3.0版本有没有计划添加一个地图功能

### ISSUE THREAD

**Issue by chenshuai2144** [wangfupeng1988/wangEditor#1051]
没有地图功能感觉 很难受，只能变相实现！
![image](https://user-images.githubusercontent.com/8186664/31525782-4b7130ca-aff5-11e7-9b14-8a98a0d8ee70.png)

界面很丑

**Comment by wangfupeng1988** [comment]
地图目前基本没人提，用户较少，因此暂时先不加。

建议：可以通过 [API](https://www.kancloud.cn/wangfupeng/wangeditor3/404586) 插入地图的图片或者 iframe 。至于地图如何显示，就可以自己控制了。

**Comment by chenshuai2144** [comment]
嗯 最好还是自己实现了

**Comment by wangfupeng1988** [comment]
好的
