### ISSUE TITLE
功能菜单能再丰富一点就好了

### ISSUE THREAD

**Issue by rocker18** [wangfupeng1988/wangEditor#1053]
比如常用的格式刷、字号大小、颜色也能够自定义最好了。

**Comment by wangfupeng1988** [comment]
> 格式刷

目前基本没有用户提这个需求，因此优先级放低

> 字体大小

应该是通过 css 统一控制的，就像目前的 table code quote 等

> 颜色自定义

有人提过，但是当我问他都需要配置哪些颜色的时候，他却说不出来。那就是没有需求，因此暂时不加自定义配置。**原则：配置项尽量简单，能不加的就不加**

**Comment by fengshenju** [comment]
我补充一下 关于字体大小设置 这个需求的理解
比如一般的论坛编辑器 都是用户发帖时使用的，这是需要有些用户需要进行字体大小的编辑
所以论坛开发者通过css来统一控制，那么发帖者不就失去了这个编辑的方式了么？
不知道我的理解是否问题，还往指正。

**Comment by wangfupeng1988** [comment]
> 比如一般的论坛编辑器 都是用户发帖时使用的，这是需要有些用户需要进行字体大小的编辑

确实有这种需求，需要高亮、增大字体来重点标注一些内容。不过目前提出这种需求的用户不多，而且这俩功能很容易留坑，因此暂时不支持。有需要的话，只能暂时自己 fork 代码来开发了
