### ISSUE TITLE
如何设置高度？默认的300px太小了。。

### ISSUE THREAD

**Issue by mejinke** [wangfupeng1988/wangEditor#1055]

**Comment by lanmaomm** [comment]
直接给div设置css样式

**Comment by lanmaomm** [comment]
我的解决方案是直接用css给div设置高度

**Comment by wangfupeng1988** [comment]
参见 https://www.kancloud.cn/wangfupeng/wangeditor3/335771

**Comment by elfman** [comment]
除了最外边的容器，还有修改`w-e-text-container`的样式，因为文本框高度是用行内样式定义的，还要加上`!important`才能生效。
