### ISSUE TITLE
如何用文本域初始化编辑器？

### ISSUE THREAD

**Issue by zokio** [wangfupeng1988/wangEditor#1058]
貌似V2是支持用textarea初始化的，为什么V3不支持了？如果不支持textarea，在form方式提交内容时，如何将内容提交到后台？

**Comment by wangfupeng1988** [comment]
搜一下此前的关闭的 issue 回复过好几次了。

--------

这样吧，我把这块在文档中补充一下，随着下次发版一起更新。
