### ISSUE TITLE
富文本的全屏插件为何不能下载?

### ISSUE THREAD

**Issue by jierjie** [wangfupeng1988/wangEditor#1059]
wangEditor-fullscreen-plugin,请问这个全屏插件怎么安装在vue项目中?
给予的是这个链接:
git clone git@github.com:wangfupeng1988/wangEditor.git  但无法下载查看,作者求解

**Comment by wangfupeng1988** [comment]
`wangEditor-fullscreen-plugin`这个不是我做的，是一个使用者提供的，你需要在 github 中全局搜索并下载。不能通过我的账号下载。
