### ISSUE TITLE
重要！！！当窗口变小到600以下的时候上边的选择框会挤出

### ISSUE THREAD

**Issue by liliukuan** [wangfupeng1988/wangEditor#1060]
窗口变小，不会自适应的把标题栏分为两层。标题栏溢出

**Comment by wangfupeng1988** [comment]
这个已知。

v2 版本支持自动换行，但是我感觉那种样式非常难看。因此 v3 版本强制只保留一行，如果你不到 600px 宽度，请适当减少菜单的数量，不要搞的那么复杂。
