### ISSUE TITLE
图片上传到oss相结合

### ISSUE THREAD

**Issue by jierjie** [wangfupeng1988/wangEditor#1061]
如何将wangeditor与图片上传到阿里云服务器相结合,求解

**Comment by wangchen9321** [comment]
oss官方给了pulpload这个插件，可以配置使用。
个人觉得这个插件有些繁琐，就采用了formdata进行表单上传。有以下几个注意点：
1.上传时需要生成policy/secret/key等参数，需要引入官方demo中的几个js；
2.oss上传时formdata中，file应该位于表单最后，但是wangeditor是放在第一个，需要自己fork下来修改；
3.表单上传以后是没有response返回值的，所以wangeditor会报错，同样需要修改上传回调部分的代码；

**Comment by wangfupeng1988** [comment]
> file应该位于表单最后，但是wangeditor是放在第一个，需要自己fork下来修改

我来修改

> 表单上传以后是没有response返回值的，所以wangeditor会报错，同样需要修改上传回调部分的代码；

@wangchen9321 告诉我如何改动，我来改，我就不再弄繁琐的 demo 了

**Comment by jierjie** [comment]
@wangchen9321   我现在就是需要结合富文本上的图片上传功能,选择好图片之后,直接上传到阿里云的oss上,因为之前没有接触过,所以不清楚后台需要什么配置  可以扣扣联系么 490494907 不尽感激

**Comment by wangfupeng1988** [comment]
> 因为之前没有接触过,所以不清楚后台需要什么配置

上传 oss 的后台配置，我也没弄过，只能你自己去看文档了
