### ISSUE TITLE
初始化编辑框内容若为纯文字会出现异常

### ISSUE THREAD

**Issue by zuoliang0** [wangfupeng1988/wangEditor#1063]
html 初始化内容
直接将内容写到要创建编辑器的`<div>`标签中
```
<div id="div1">
   “纯文字纯文字纯文字纯文字纯文字纯文字纯文字纯文字纯文字纯文字纯文字纯文字”
</div>

<script type="text/javascript" src="/wangEditor.min.js"></script>
<script type="text/javascript">
    var E = window.wangEditor
    var editor = new E('#div1')
    editor.create()
</script>
```
会出现类似的问题
![image](https://user-images.githubusercontent.com/8434253/31644687-30b18702-b32a-11e7-8ed2-a422d44c8e33.png)
http://runjs.cn/detail/jtnocpg7

**Comment by Yusoo** [comment]
之前我就遇到这种情况 #957

**Comment by wangfupeng1988** [comment]
要求，必须在`“纯文字纯文字纯文字纯文字纯文字纯文字纯文字纯文字纯文字纯文字纯文字纯文字”`用`<p>...</p>`包裹

**Comment by zuoliang0** [comment]
大哥，这不是处理问题的办法啊，为什么纯文本就要用表情包裹一下呢。再说了后台也不知道这是纯文本还是已经编辑过的，请解决这个问题。谢谢

**Comment by wangfupeng1988** [comment]
怎么解决？—— 我自己在文字外面加`<p>...</p>`？

你后台不知道这是纯文本还是已经编辑过的，我也不知道啊……

**Comment by zuoliang0** [comment]
不是，这个问题是，其他的编辑器都不会出现你这种问题，你让我怎么说呢。。。

**Comment by zuoliang0** [comment]
不是说，你加或者不加一个p标签的问题，而是，怎么让纯文本和其他表情一视同仁的处理啊。

**Comment by wangfupeng1988** [comment]
每个工具都有自己的规则和使用方式，其实你做一个判断处理就是了，很简单的事情，没必要等待工具做啥升级

**Comment by aoeng** [comment]
@我也遇到了这个问题,然而`<p>...</p>`怎么加?选择第一行纯文字然后点击H吗?直接写`p`不会被解析吧? @wangfupeng1988 @zuoliang0 你最后是怎么解决的啊?

**Comment by zuoliang0** [comment]
我换了一个编辑器，自己写
