### ISSUE TITLE
请問支持从word拷贝复制吗

### ISSUE THREAD

**Issue by xiaoymin** [wangfupeng1988/wangEditor#1067]
word中存在图片，文字这种类型的，不知道是否支持？？

**Comment by hold-baby** [comment]
支持的

**Comment by xiaoymin** [comment]
需要配置什么参数吗？我现在程序里面应用 不行

**Comment by wangfupeng1988** [comment]
> 在程序里面应用 不行

什么程序？

**Comment by MohitLolo** [comment]
从word中直接复制粘贴真的不行，是我没配置对么？样式图片什么的全丢了

**Comment by wangfupeng1988** [comment]
word 粘贴目前确实有一些问题样式的问题需要解决，但是有一点需要声明：word 中的图片可能直接粘贴、上传到服务器的，图片上传还是需要手动上传。

至于 word 粘贴的文字样式问题，我后续会继续升级、改造。
