### ISSUE TITLE
有序列表和无序列表之间互相切换不会触发onchange事件

### ISSUE THREAD

**Issue by lanmaomm** [wangfupeng1988/wangEditor#1068]
下载了项目，利用on-vue演示模块测试。在chrome浏览器（版本号61.0.3163.100）中测试有序和无序列表功能，发现两种列表之间互相切换时无法触发onchange事件。在saferi浏览器中也进行了测试，没出现这个问题。

**Comment by wangfupeng1988** [comment]
我周末跟踪这个问题，如果存在，就近期版本解决

**Comment by wangfupeng1988** [comment]
复现了，周末发布`v3.0.11`版本修复，请关注升级动态
