### ISSUE TITLE
能否紧急修复customConfig.customUploadImg不触发的问题。

### ISSUE THREAD

**Issue by codinglilong** [wangfupeng1988/wangEditor#1069]
前面几个版本都好的升到3.0.10之后，customConfig.customUploadImg选中文件，回调不会触发。刚刚一个一个版本试的，只有3.0.10版本不会触发。我用的框架是react。
![qq 20171019161408](https://user-images.githubusercontent.com/20492424/31760825-8dff2b3e-b4e8-11e7-976e-80f1dd463d2e.png)

console.log(files); 不会被触发。。。

**Comment by wangfupeng1988** [comment]
先撤回到`3.0.9`，我周末试试你说的情况

**Comment by wangfupeng1988** [comment]
我发现这个问题了，本周末会发布`v3.0.11`修复这个问题，请关注版本升级动态
