### ISSUE TITLE
头部菜单显示不全

### ISSUE THREAD

**Issue by wufei19920201** [wangfupeng1988/wangEditor#1071]
![image](https://user-images.githubusercontent.com/23118826/31801204-092b2912-b579-11e7-996c-6fd8ca26410c.png)
请问我直接创建的怎么头部菜单显示不全？

**Comment by wufei19920201** [comment]
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="wangeditor/dist/css/wangEditor.css">
</head>
<body>
<div id="editor">
    <p>这是富文本编辑器demo</p>
</div>
</body>
</html>
<script src="jquery-3.2.1.min.js"></script>
<script src="wangeditor/dist/js/wangEditor.js"></script>

<script>
    var E = window.wangEditor;
    var editor = new E('editor')
    editor.create()
</script>`

**Comment by wangfupeng1988** [comment]
你用的哪个版本？现在都 v3.0.10 了
