### ISSUE TITLE
能否增加查看 HTML 代码的功能

### ISSUE THREAD

**Issue by zcnhonker** [wangfupeng1988/wangEditor#1074]
找了一下发现没有直接在 HTML 上修改内容的功能，请问能否加上呢？ 因为有时候确实会有这样的特殊需求。
另外不知道能不能加上代码高亮？ 这样就不用另外找插件了。

**Comment by wangfupeng1988** [comment]
找个功能完全可以自己做。第一，通过`editor.txt.html()`获取了内容，就可以显示出来；第二，自己修改了 html 代码之后，可以通过`editor.txt.html('...')`重新设置。

至于为何编辑器不自己实现好？因为这个功能并不是编辑器的核心功能，使用的人也比较少，而且开放修改源代码会有安全风险。
