### ISSUE TITLE
请问wangEditor3支持修改字体大小吗？

### ISSUE THREAD

**Issue by Yic-chen** [wangfupeng1988/wangEditor#1079]
我看了一遍文档，好像3.x版本菜单里面没有字号的选项，也没有看到像2.x那样可以自定义菜单的函数，是去掉了吗？

**Comment by wangfupeng1988** [comment]
> 3.x版本菜单里面没有字号的选项

字号和字体不在支持，应该用统一的 css 和 html 标签来控制

> 也没有看到像2.x那样可以自定义菜单的函数

v3 不支持了。因为之前 v2 支持 createMenu 但是使用的人并不多，而且 createMenu 的实现比较复杂，维护成本较高。
