### ISSUE TITLE
能否增加支持Markdown模式的功能？

### ISSUE THREAD

**Issue by oustn** [wangfupeng1988/wangEditor#108]
首先非常感谢作者的产品，我自己的博客在用...
现在我想实现富文本和Markdown的功能，当然Markdown转换是在后端处理，但是有一个问题，如果直接把wangEditor中的内容传到后端的Markdown处理的话，因为内容已经加上了html标签，所以Markdown处理器会自动忽略。我的想法是能否在wangEditor中加入一个Markdown模式按钮，选中之后wangEditor就不会转换任何输入框中的内容，并且禁用其他的编辑按钮。这样直接将内容传到后端，可以实现Markdown处理。
如果加入这个功能，相信可以很简单的实现Markdown的扩展。

**Comment by wangfupeng1988** [comment]
富文本编辑器无法和markdown编辑器很方便的做切换，wangEditor也不支持。

普通富文本编辑器是给大众用户使用的，markdown编辑器是给开发人员使用的，应用场景不一样。我知道一个很不错的markdown编辑器，可以推荐给你：https://pandao.github.io/editor.md/

**Comment by wangfupeng1988** [comment]
markdown 插件已经开发完了 https://github.com/wangeditor-team/wangEditor-plugin-md

不过只能用于 [v5](https://www.wangeditor.com/v5/) 。v5 近期会正式发布，v4 不再做功能升级了。

**Comment by zqxxjs** [comment]
那么如何配置呢？贴下vue3相关配置代码可以吗？

**Comment by cycleccc** [comment]
> 那么如何配置呢？贴下vue3相关配置代码可以吗？

github readme 里有写 链接在官方文档有
