### ISSUE TITLE
复制图片会出现两张

### ISSUE THREAD

**Issue by xmvper** [wangfupeng1988/wangEditor#1081]
问题：
找一篇文章（比如  https://www.kancloud.cn/wangfupeng/wangeditor3/335769 ），点图片，右键复制图片，然后在编辑器中粘贴，会出现两张图片
在本地和http://www.wangeditor.com 上都会有这种情况

浏览器：
win7+chrome 61

**Comment by wangfupeng1988** [comment]
为何我这里按你的操作，粘贴会出现如下文字？chrome， mac os 系统

```
https://camo.githubusercontent.com/f3d072718d8fcbbacf8cc80465a34cceffcf5b4a/687474703a2f2f696d61676573323031352e636e626c6f67732e636f6d2f626c6f672f3133383031322f3230313730352f3133383031322d32303137303533303230323930353633332d313834303135383938312e706e67
```

**Comment by jcplus** [comment]
测试了一下粘贴图片：
Win10+Chrome 会重复图片
Mac+Safari 正常
Mac+Chrome 正常

**Comment by Oacks** [comment]
同问

**Comment by wangfupeng1988** [comment]
我记录下，周末查

**Comment by laozhuorun** [comment]
同问，实测线上demo和我本地项目都会

**Comment by liuyuhui0111** [comment]
你先上传一张图片在编辑器里 然后右键点击图片--复制图片  再粘贴就会出现一次出两张的bug  在官网测试也有

**Comment by wangfupeng1988** [comment]
> Win10+Chrome 会重复图片

已经复现，我记录下来，下次更新高优修复该问题。感谢大家的反馈！

**Comment by beileixinqing** [comment]
不论是连文字带图片还是只是图片,右键复制的时候,图片原来链接的那张会出现,即连文字带图片粘贴,会出现一张图片,没有走上传图片接口,只是图片粘贴会一张走上传图片接口,一张原图,如果ctrl+v粘贴可以正常展示图片数量.

**Comment by wangfupeng1988** [comment]
10.0.13 版本修复了这个问题，官网已经看到效果了

**Comment by laizp** [comment]
好像又出现这个问题了，win10 + chrome/edge，官网已复现

**Comment by biology-w** [comment]
bug 描述
------------------------------------------------------------------------------------
环境：
windows10专业版 64位
chrome 91.0.4472.101
wangEditor 4.3.0

直接复制word或微信内单个图片,粘贴到编辑器，会显示两张。
![image](https://user-images.githubusercontent.com/25600705/121663085-9e267800-cad8-11eb-896f-90b47312ea7e.png)
![image](https://user-images.githubusercontent.com/25600705/121663215-c3b38180-cad8-11eb-831b-d2375b6242cb.png)
![image](https://user-images.githubusercontent.com/25600705/121663279-d8901500-cad8-11eb-97b7-dca4d51423ae.png)

**Comment by diduweiwu** [comment]
问题依然存在,在官网DEMO里面可复现, macos 12+edge 96

> 好像又出现这个问题了，win10 + chrome/edge，官网已复现
