### ISSUE TITLE
对wangEditor提几点建议

### ISSUE THREAD

**Issue by gavinliu6** [wangfupeng1988/wangEditor#1082]
1. 支持placeholder，有内容时隐藏，无内容时灰色显示；
2. 对获取的html内容进行过滤，筛选掉多余的无用标签，比如内容为空的<b></b>等；
3. 支持设置多少秒无操作后，才出发change事件，以便减少操作草稿箱的次数；
4. 对粘贴内容的解析优化，比如从京东的单品页复制的商品简介，目前是解析出的文本是乱的；
5. 当解析到粘贴内容中包含img图片时，支持提取并上传。
@wangfupeng1988

**Comment by wangfupeng1988** [comment]
> 支持placeholder，有内容时隐藏，无内容时灰色显示；

这是一个 div 不是一个 textarea ，不太好实现 placeholder

> 对获取的html内容进行过滤，筛选掉多余的无用标签，比如内容为空的等；

这个没有标准，内容为空的，并不一定是用户不需要的。使用方完全可以根据自己的需求，自己筛选。

> 支持设置多少秒无操作后，才出发change事件，以便减少操作草稿箱的次数；

恩，这个可以支持配置，我记录下

> 对粘贴内容的解析优化，比如从京东的单品页复制的商品简介，目前是解析出的文本是乱的

这个是目前的一个问题，后面要持续优化的

> 当解析到粘贴内容中包含img图片时，支持提取并上传。

这个问题有人提过，我也就下了，基于目前用户提需求的状态，并不是太高优

**Comment by laozhuorun** [comment]
当解析到粘贴内容中包含img图片时，支持提取并上传。这个太需要了，内容存放base64，相当于把图片存到数据库，一段时间后数据库会很臃肿，而且增加了返回内容的大小

**Comment by wangfupeng1988** [comment]
@laozhuorun 

> 当解析到粘贴内容中包含img图片时，支持提取并上传。

部分场景下可以实现（如从外部网页复制、粘贴），部分实现不了（如从word中复制、粘贴）

**Comment by laozhuorun** [comment]
@wangfupeng1988 我想很多人的使用场景是从粘贴面板直接粘贴到编辑器，我昨天刚使用你的编辑器，还没看过源码，我现在的处理方案是在onchange里面用正则匹配img并且提取src是base64的图片，上传后用url替换掉base64，同时用一个对象保存旧的图片，onchange最后与旧图片对比，找出被删的图片，然后请求七牛删除对应的图片

**Comment by wangfupeng1988** [comment]
能技术实现的，我也都记录下来了，后续会持续升级改造。无法计数实现的，只能等待浏览器的技术支持。
