### ISSUE TITLE
wangEditor 结合 BootStrap 全屏时，显示异常

### ISSUE THREAD

**Issue by xingwen1987** [wangfupeng1988/wangEditor#1083]
![bug](https://user-images.githubusercontent.com/15207100/31988841-05dfb52e-b9a3-11e7-9821-38025fdba262.gif)
如图所示，结合 BootStarp 的 modal，全屏时显示出现了异常。
版本是 2.x 最后一个版本。

**Comment by wangfupeng1988** [comment]
非常抱歉，2.x 版本已经不再技术支持了。个人精力有限，还请见谅。
