### ISSUE TITLE
V2的时候有扩展一个菜单的功能，V3没有了

### ISSUE THREAD

**Issue by zhanggoodzhi** [wangfupeng1988/wangEditor#1084]
我在V2版扩展了一个菜单，现在想升级到V3，但是V3没有看到这个功能，请问是去除这个功能了吗？

**Comment by wangfupeng1988** [comment]
v3 不支持了。因为之前 v2 支持 createMenu 但是使用的人并不多，而且 createMenu 的实现比较复杂，维护成本较高。

使用 v3 你可以自己 fork 代码去二次开发一个菜单吧，其实也挺简单的，有需要随时给我提问题，我来技术支持
