### ISSUE TITLE
编辑器高度自定义

### ISSUE THREAD

**Issue by jcplus** [wangfupeng1988/wangEditor#1085]
群里每天都有人在问怎么设置编辑器高度。
我看.w-e-text-container的高度是写死的300px，能不能换成：
`.w-e-text-container {  
    box-sizing: border-box;  
    height: 100%;  
}`
这样大家可以不用去覆盖这个高度的设置。

**Comment by wangfupeng1988** [comment]
看这个文档 https://www.kancloud.cn/wangfupeng/wangeditor3/335771 有描述

**Comment by bingcheng916** [comment]
> 看这个文档 https://www.kancloud.cn/wangfupeng/wangeditor3/335771 有描述

没用，只是编辑器的容器高度增加了，编辑器本身还是300px.
