### ISSUE TITLE
在没有网络环境的情况下支持ctrl+v粘贴图片吗？

### ISSUE THREAD

**Issue by DancingWing** [wangfupeng1988/wangEditor#1087]
在没有网络的情况下。使用wangEditor编辑器，直接快捷截图然后CTRL+V到编辑器里面，editor.customConfig.customUploadImg = function (files, insert)官方提供的这个方法里面的参数files获取不到值？

**Comment by wangfupeng1988** [comment]
customUploadImg 此前版本有问题，你要更新到最新版

**Comment by DancingWing** [comment]
使用的就是v3.0.11版本啊

**Comment by wangfupeng1988** [comment]
好，我周末再看一下

**Comment by wangfupeng1988** [comment]
我拿当前版本试了一下，无论是有网还是没网、粘贴图片还是直接上传，customUploadImg 中 files 都是可以拿到的。你可以 [下载运行 demo](https://github.com/wangfupeng1988/wangEditor#运行-demo) 然后在`http://localhost:3000/demo/test-uploadimg.html`这个 demo 页中**最后一个编辑器**上传图片试一下。
