### ISSUE TITLE
[新功能]支持工具栏的功能扩展

### ISSUE THREAD

**Issue by ArcRain** [wangfupeng1988/wangEditor#109]
很感谢作者提供了一个精简小巧的富文本编辑器，让人在苦苦寻觅之后觉得眼前一亮——正是所需要的富文本编辑器啊。
对于工具栏的功能，我觉得自建的功能已经能满足很大的普遍需求了。
不知道能不能提供这样一种功能，接入方可以方便的自定义扩展工具栏的新功能：只需要配置一个简单的功能数组（元素包括了功能标题、功能按钮），当用户点击功能按钮时，触发通知接入方自行处理。这样方便接入方在工具栏增加一些私有的业务功能，而又不影响富文本编辑器的功能。
最后希望作者能够继续完善该组件，持续关注ing...

**Comment by ArcRain** [comment]
自己改了下，也请作者帮忙Review看看逻辑是否可采用。:-) https://github.com/wangfupeng1988/wangEditor/compare/master...ArcRain:master

**Comment by wangfupeng1988** [comment]
自定义扩展工具栏不是那么简单的，你可以想想：目前编辑器上所有的菜单都通过你设计的这个扩展方法来扩展，是不是能很方便？

目前大家使用的这一版是在不到一年之前重构的，但是没有很看重工具栏的扩展。我现在正在重构下一版，一周之后即可看到效果。

到时用户可以很方便定义扩展工具栏。因为，编辑器所有的菜单，实质上都是扩展出来的。

希望再耐心等待一下。

**Comment by ArcRain** [comment]
的确我的方法很有限，也不便捷...
不过这是我能想到的解决我现在需求的最快捷方法了，因为我不需要工具栏提供modal的视图，仅需要提供一个功能按钮以及触发响应，响应里的视图界面功能，是自己通过其他三方组件来完成的，可以很好的契合现有的站点界面风格，同时也保留富文本编辑器的工具栏界面一致性。
期待作者的重构版~辛苦了！:-)

**Comment by secicl** [comment]
@wangfupeng1988  才看到您在重构，很感谢您辛苦的付出！
不知道您重构后对这些问题是否有所改善？
https://github.com/wangfupeng1988/wangEditor/issues/111
