### ISSUE TITLE
兼容性

### ISSUE THREAD

**Issue by baoxd** [wangfupeng1988/wangEditor#1090]
在做一个客户端的项目，想用这个编辑器，发现只支持到IE10+，只好放弃了。

**Comment by wangfupeng1988** [comment]
那非常遗憾了。不过，我做一个开源项目，肯定得考虑浏览器的整体情况以及未来发展趋势，因此放弃了IE10以下

**Comment by baoxd** [comment]
你做的非常棒！万恶的IE...
