### ISSUE TITLE
IE11上传图片成功后选中了该图片，导致我接着上传就覆盖了前一张上传的图片

### ISSUE THREAD

**Issue by ylovely** [wangfupeng1988/wangEditor#1095]
有没有办法上传成功后不要选中图片。
![image](https://user-images.githubusercontent.com/14031036/32152267-df02a164-bd5d-11e7-9db1-e60cd77fba62.png)

**Comment by wangfupeng1988** [comment]
是这样的，上传图片其实是一个`insertHTML`的过程，会把你之前选中的给替换掉，不过这块不同浏览器兼容性还不一样。

**Comment by ylovely** [comment]
您好，我的意思我上传成功后编辑器自动选中了这张图片，不是我手动选中的，我需要的是不让它自动选中这张图， @wangfupeng1988

**Comment by wangfupeng1988** [comment]
好，我记录下，周末看看这个问题。

**Comment by wangfupeng1988** [comment]
看了一下，IE 对`editor.selection.collapseRange()`有兼容性问题，暂时不好解决。

**Comment by wuhongchao-hscn** [comment]
`            // IE
            range.deleteContents();
            range.insertNode($(html)[0]);
            // 让ie创建新行
            editor.initSelection();`

我在ie上传多张图片，最后只显示一张，chrome没问题，
我的想法是， 3.1.1版本的3718行【editor.initSelection();】 通过initSelection方法，添加新行，
不知道对不对。。。
