### ISSUE TITLE
编辑器onchange监控输入bug

### ISSUE THREAD

**Issue by xulei131401** [wangfupeng1988/wangEditor#1097]
不能连笔输入汉字，会自动变为拼音

**Comment by xulei131401** [comment]
并且该bug不是必现的，但出现的频率很高

**Comment by wangfupeng1988** [comment]
什么叫做“连笔输入汉字”？

**Comment by xulei131401** [comment]
一次性打很多个汉字，不是一个汉字一个汉字打上去

**Comment by wangfupeng1988** [comment]
这个截图是你给我发到邮箱里面的？**如果是的话，以后不要发邮箱，邮箱的问题不受理！**因为问题需要共享，而不是私聊。

![fbb84b22 c852e23c 7f1ff759 jpg](https://user-images.githubusercontent.com/9583120/32204227-1dbd36dc-bdb6-11e7-8d10-deec1a823d9d.jpg)

**Comment by wangfupeng1988** [comment]
10.0.13 修复了通过 length 判断是否执行 change 的问题，这问题应该就修复了。可以去验证一下。
