### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by hahaniu666** [wangfupeng1988/wangEditor#1099]
1.希望编辑器在上传完图片的时候,选中图片,可以给这个图片加入超链接,现在的超链接只能加在文字中
2.希望后续的编辑器查看源码功能能够再次加上,虽然可以自己去修改控制,但是查出的源码没有换行等提示,

**Comment by wangfupeng1988** [comment]
第一，图片加超链接现在基本没有使用者提出过，反馈人数少说明不是大众问题，因此暂时先不加。

第二，编辑源码不是每个人都需要，而且是大部分编辑器的内容输入者都不需要，还是自己去弄吧。过程中有问题可以找我支持。
