### ISSUE TITLE
工具栏视频，不能插入腾讯的视频

### ISSUE THREAD

**Issue by khaoszeng** [wangfupeng1988/wangEditor#110]
工具栏视频，不能插入腾讯的视频

**Comment by wangfupeng1988** [comment]
吧要插入的视频地址发给我，我试试

**Comment by khaoszeng** [comment]
腾讯视频的分享地址：http://static.video.qq.com/TPout.swf?vid=b0180ir8tzh&auto=0
因为swf带了参数，所有不成功。。。

**Comment by wangfupeng1988** [comment]
哦，我知道了。。。。是这里验证的问题。
我现在正在忙活着开发2.0版本，我先告诉你一个解决方案。

你去wangeditor.js源码中搜索 `reg = /^\s*(http:\/\/|https:\/\/).+(\.swf|\.ogg|\.mp4|\.webm)\s*$/i,` 然后将这个正则修改为 `reg = /^\s*(http:\/\/|https:\/\/).+(\.swf|\.ogg|\.mp4|\.webm)\/i,`这样就去掉了后面参数的验证，就可以了

**Comment by wangfupeng1988** [comment]
2.0已发布，对这种视频支持没有问题，欢迎更新使用
