### ISSUE TITLE
编辑内容时候，选中图片或取消选中图片，都会触发onchange

### ISSUE THREAD

**Issue by laozhuorun** [wangfupeng1988/wangEditor#1100]
编辑内容时候，选中图片或取消选中图片，实际内容没有任何变化，但是都会触发onchange事件
chrome， win10

**Comment by heroofchina** [comment]
你在onchange里面通过正则过滤掉就行了

**Comment by heroofchina** [comment]
你在onchange里面通过正则过滤掉就行了

**Comment by wangfupeng1988** [comment]
我周末跟踪一下这个问题。

**Comment by wangfupeng1988** [comment]
> 你在onchange里面通过正则过滤掉就行了

着急的话，可以先这样自己处理

**Comment by wangfupeng1988** [comment]
修复了，本周末会更新 3.0.13 版本，请关注更新动态
