### ISSUE TITLE
Mac safari图片无法粘贴

### ISSUE THREAD

**Issue by aizaimenghuangu** [wangfupeng1988/wangEditor#1101]
## 在Mac + safari无法粘贴图片，粘贴后没有任何响应

1、使用官网的editort也会出现；
2、safari版本 10.1.1 (12603.2.4)  mac 10.12.5 (16F73)

**Comment by wangfupeng1988** [comment]
safari 目前没有直接粘贴图片的 API 。你可以看下 QQ 邮箱，在 safari 下也无法直接粘贴图片。有同学提供了一个方法 https://github.com/wangfupeng1988/wangEditor/issues/831 我还来得及实验。
