### ISSUE TITLE
在wangEditor弹出sweetalert2对话框，对话框的按钮不可点击

### ISSUE THREAD

**Issue by aizaimenghuangu** [wangfupeng1988/wangEditor#1103]
<img width="953" alt="wx20171031-125139 2x" src="https://user-images.githubusercontent.com/3993636/32207960-5dd2c73a-be3a-11e7-9857-a114c5629402.png">

如上图：在Editor上方弹出sweetalert2对话框，对话框的按钮不可点击，点击后的焦点是在编辑框里面。

**Comment by wangfupeng1988** [comment]
应该是 css 样式的冲突，调整一下编辑器的 zindex 试试
