### ISSUE TITLE
vue中应用无法实现双向绑定

### ISSUE THREAD

**Issue by zetianul** [wangfupeng1988/wangEditor#1104]
想用v-model绑定数据，让编辑器中的内容随着数据源变化而变化，但是并不能实现。查看了之前的issue，但是文档中并没有双向绑定的内容

**Comment by wangfupeng1988** [comment]
v-model 绑定到编辑器肯定不行啊，编辑器就是一个 div 不是 input 和 textarea ，v-model 不支持。参考文档中 vue 的例子，用 onchange 实现吧。
