### ISSUE TITLE
1.输入一段文字 选中 2.点击加粗按钮 3.然后再拷贝一段文字粘贴到加粗文字后面 4. 发现粘贴的文字没有加粗

### ISSUE THREAD

**Issue by heroofchina** [wangfupeng1988/wangEditor#1105]
1.输入一段文字 选中
2.点击加粗按钮 
3.然后再拷贝一段文字粘贴到加粗文字后面 
4. 发现粘贴的文字没有加粗
![image](https://user-images.githubusercontent.com/17189696/32219058-ea118c40-be67-11e7-8f95-522bf7eb9be7.png)

**Comment by heroofchina** [comment]
备注 在我本地和官网上面都有这个问题 我是mac 浏览器是谷歌

**Comment by wangfupeng1988** [comment]
看一下源码，是有了`<b>`或者`<strong>`标签 没有显示成加粗？还是直接没有`<b>`或者`<strong>`标签。
有些情况下，有加粗的标签，但是没有正常显示。

**Comment by heroofchina** [comment]
看一下源码，是有了<b>或者<strong>标签没有显示成加粗？还有直接没有<b>或者<strong>标签。
有些情况下，有加粗的标签，但是没有正常显示?

你的意思就是说有时候的确会出现这个问题 但是没有修正咯？

**Comment by wangfupeng1988** [comment]
> 有些情况下，有加粗的标签，但是没有正常显示?

遇到过这种情况，因此你得确认一下你是否是这种情况
