### ISSUE TITLE
插入网络图片链接地址出错也会插入一个img标签在页面里

### ISSUE THREAD

**Issue by liuyuhui0111** [wangfupeng1988/wangEditor#1106]
![image](https://user-images.githubusercontent.com/21170487/32220558-1f0b0da4-be6d-11e7-969d-7c1dbba5e581.png)

**Comment by wangfupeng1988** [comment]
感谢反馈。我记录下来，后续升级时候加一个插入图片地址的校验吧，类似[插入链接的校验](https://www.kancloud.cn/wangfupeng/wangeditor3/415032)

**Comment by wangfupeng1988** [comment]
看自定义插入网络图片的校验规则 https://www.kancloud.cn/wangfupeng/wangeditor3/448203 。 10.0.13 版本开始支持

**Comment by zero009** [comment]
您好，这个校验好像拦截不了，当我在这个校验里面对图片进行限制宽高的时候，return还是会插入到文档中不晓得是不是异步的缘故有没有解决的办法

**Comment by zero009** [comment]
editor.customConfig.linkImgCheck = function (src) {
        console.log(src) // 图片的链接
        var img2 = new Image()
        img2.src = src
        img2.onload = function () {
          if (img2.width > 1230 || img2.width < 600 || img2.height > 960) {
            _this.$message.error('商品图片尺寸宽度在600px至1230px之间,高度不超过960px')
            return '' // 返回字符串，即校验失败的提示信息
          }
        }
      }
