### ISSUE TITLE
customInsert 返回值是一个图片地址也不行么？

### ISSUE THREAD

**Issue by HuShao96** [wangfupeng1988/wangEditor#1107]
customInsert: function (insertImg, result, editor) {
             insertImg(result);
       }
result为：单纯的一个图片地址！
如果没有，
我想用editor.customConfig.customUploadImg 自定义上传，假如上传一张图片
editor.customConfig.customUploadImg = function (files, insert) {
        axios({
            url: fileServerUrl,
            method: 'POST',
            params: {file: files[0]}
        }).then(function (response) {
            alert(response);
            insert(response.data);
        });
    };
请求直接500.里面的参数 为file：{}
也就是说选中一个图片， files集合为空
难道是我写错了？

**Comment by wangfupeng1988** [comment]
你的问题，文档中有明确而且重点的说明
