### ISSUE TITLE
onchange事件不触发

### ISSUE THREAD

**Issue by trojan-ann** [wangfupeng1988/wangEditor#1109]
从H1切换到H2时，或者从Hi切换到Hj时，并没有触发onchange事件

**Comment by trojan-ann** [comment]
看了下代码，在editor的bindEvent里面是通过字符数来判断是否要触发onchange事件的，在设置标题时，字符数并没有改变，所以就没有触发出事件来

**Comment by wangfupeng1988** [comment]
感谢反馈，此前已经有人提到过这个问题，下次升级会高优改过来。

**Comment by wangfupeng1988** [comment]
3.0.13 版本已经修复这个问题
