### ISSUE TITLE
个人使用过程中遇到的问题：@(mention)、规定行间距段间距、引用功能的bug、工具栏不随屏幕滚动、支持 bilibili 的视频引用、markdown切换

### ISSUE THREAD

**Issue by secicl** [wangfupeng1988/wangEditor#111]
首先非常感谢您提供这么好的编辑器

个人在试用过程中遇到一些问题和建议

- 希望支持@人的功能，例如 https://github.com/mycolorway/simditor-mention （重要）
- 希望规定行间距和段间距，为了使编辑后的文章排版更美观，一般是段间距是行间距的2倍，可以参考 http://medium.com 或者 http://jianshu.com http://linkesch.com/medium-editor-insert-plugin/  甚至 simditor（重要）
- 引用功能存在 bug： 无法清除格式和取消引用 （重要）
- 希望支持工具栏不随屏幕滚动，这样能更好的编辑长文 （重要）
- 希望视频功能支持 bilibili http://www.bilibili.com/video/av3536739/ (一般重要)
- 希望支持 markdown 的切换 （不重要）

**Comment by wangfupeng1988** [comment]
感谢来信。

1. @人，我不明白你的应用场景是什么，你给出的链接也无法只管展示。另外，到底 @谁呀？冯小刚还是秦始皇？没人可 @ 呀，这又不是 QQ群。还是希望你能给出具体的应用场景。
2. 行间距和段间距这个，是应该做上的。这个也不难，就是几句css的事儿。
3. 引用的bug，我就关注并记录下了。我这几天正在重构2.0版本，`引用`菜单已经做完了，这些bug都已经修复了。过一周会发布预览版。
4. 工具栏吸顶这个我也将在2.0中考虑，这个是有必要的，特别是全屏的时候。
5. markdown暂时不支持。想用markdown，直接用markdown编辑器即可。

**Comment by secicl** [comment]
非常感谢您及时的回复。

###关于@人
一般是使用在社交网络中，比如微博、知乎，需要在发帖或发文时通过 @ 查询并提及某个用户
您在 github 这个输入框里输入"@"符号时，也是同样的使用情景，例如  @wangfupeng1988

**Comment by weijer** [comment]
我自己也修改增加了@功能

**Comment by wangfupeng1988** [comment]
@ 功能，需要的人不是很多，谁需要，就自己加吧。

我做编辑器到现在1年多了，有这种体验：你做一个不常用的功能，集成时有需要调用各种项目的接口，写的文档比较复杂，后期的管理成本是很高的。就是，菜鸟或者不懂看文档的人，会各种问你，你给他解释还解释不了；老鸟或者会看文档的人呢，基本上开发一个 @ 功能，也不成问题。

所以，你懂的。。。

**Comment by bigrats** [comment]
1.@功能： 编辑器不应该固化实现的，但编辑器可以通过插件方式让有需求者自己实现。
'@人，我不明白你的应用场景是什么，你给出的链接也无法只管展示。另外，到底 @谁呀？冯小刚还是秦始皇？没人可 @ 呀，这又不是 QQ群。还是希望你能给出具体的应用场景。

2.编辑内容样式： 每个应用对样式的需求是不同的，个人认为应该分为编辑器时的样式和内容展现时的样式。
内容展现时的样式应该由应用自己去定义，有可能会定义多套皮肤的；
编辑时的样式建议编辑器定义默认的样式（主要是p, table,img等），这样应用可以重新定义编辑样式来满足需求。
之前在一个WORD文档里面提过，建议编辑器输出的内容要尽可能的纯粹，只包括必要的HTML标记，尽量不包括 style="xxx" 的固化样式，毕竟修改已有的CSS样式现在不是一件很难的工作。
'行间距和段间距这个，是应该做上的。这个也不难，就是几句css的事儿。

**Comment by wangfupeng1988** [comment]
@ 功能，有群友提供了一个插件，你看看是否满足你的要求：http://ichord.github.io/At.js/
