### ISSUE TITLE
this.id = 'wangEditor-' + editorId++;---------> “Cannot set property 'id' of null”

### ISSUE THREAD

**Issue by kell90722** [wangfupeng1988/wangEditor#1110]
3975 ······// id，用以区分单个页面不同的编辑器对象
    this.id = 'wangEditor-' + editorId++;
//················为什么按照文档接入Editor.vue这个组件，回报id为null呢？是需要在初始化时传入什么值吗？

**Comment by wangfupeng1988** [comment]
这是 wangEditor.js 源码中的报错？
