### ISSUE TITLE
鼠标选中图片后，使用delete键或返回键无法删除图片

### ISSUE THREAD

**Issue by laozhuorun** [wangfupeng1988/wangEditor#1111]
鼠标选中图片后，使用delete键或返回键无法删除图片，而且会误删最后一张图

操作流程：
① 使用截图直接粘贴3张图片到编辑器
② 选中第一张使用delete键或返回键删除图片

预期：第一张图片被删除
实际结果：最后一张图片被删除

**Comment by zcnhonker** [comment]
借楼提一个问题。 在文档中看到说不把上传附件功能弄到编辑器的原因是删除附件而服务器附件没删除。 就有一个问题了，本地上传图片，但编辑的时候把图片删掉了，也没办法把服务器上已经上传的图片删除。 那是不是应该做一个记录这次已经上传的图片列表可以进行删除，或者是做一个删除图片的回调呢？

**Comment by wangfupeng1988** [comment]
@zcnhonker 你的问题参见 https://github.com/wangfupeng1988/wangEditor/issues/1121

**Comment by wangfupeng1988** [comment]
@laozhuorun 你提出的问题，我复现了，记录下来，会尽快高优修复，感谢反馈！

**Comment by muzi131313** [comment]
@wangfupeng1988 嗨，楼主说的误删最后一张图片，也碰到了同样的问题，现在修复了么？

**Comment by wangfupeng1988** [comment]
@muzi131313 升级版本都是周末干，平日上班没时间，个人维护的开源项目，还请体谅哈

**Comment by wangfupeng1988** [comment]
升级了 10.0.13，已经解决了这个问题

**Comment by muzi131313** [comment]
哈哈，👍🏻，太赞了，感谢

李彦风
