### ISSUE TITLE
在Vue中调用elementui的$prompt的遮罩层无法遮住编辑器部分

### ISSUE THREAD

**Issue by zetianul** [wangfupeng1988/wangEditor#1112]
![image](https://user-images.githubusercontent.com/22810595/32267476-60417736-bf26-11e7-94ae-1d048629732d.png)
编辑器的文字依然可以编辑，并且会遮住弹出的prompt框。应该是这个编辑器的这个div并没有被遮罩层遮住。

**Comment by zetianul** [comment]
环境是 windows+chrome

**Comment by wangfupeng1988** [comment]
修改 z-index 试试
