### ISSUE TITLE
输入连续汉字变成字母

### ISSUE THREAD

**Issue by liyi1008** [wangfupeng1988/wangEditor#1114]
比如输入啊啊啊啊啊啊啊啊，最后变成aaaaaaaaaaaa。噢噢噢噢噢噢噢噢噢噢，变成oooooooooooooo。

**Comment by zetianul** [comment]
不是输入法的问题吗？打完了没按回车或者空格？

**Comment by wangfupeng1988** [comment]
应该是输入法的问题

**Comment by liyi1008** [comment]
用的是textarea，用onchange把内容同步到textarea。这个完全参照文档，没有特别改变。其他都是默认。

至于输入法问题，我试验了下，发现打完字，如果光标紧挨着最后的字就直接提交，就会出现这个问题。但是，如果不是连续的字一样的字，比如打啊哈，它就不会变成拼音。

另外我试验了别的编辑器，不会如此。

**Comment by wangfupeng1988** [comment]
可以[下载运行demo](https://github.com/wangfupeng1988/wangEditor#运行-demo)，然后访问`http://localhost:3000/demo/test-textarea.html` ，我试验，没发现你说的问题

我能保证的只是 textarea 和编辑区域的内容完全一样，如果编辑区域也会有拼音，那么提交的时候肯定有拼音。

**Comment by liyi1008** [comment]
我想了下，应该是同步的问题。输入的时候，我按的键它同步过去了，但是选词之后它没有触发同步。

不过正常输入一般的句子或者词语就不会这样，可能在完成输入前输入法已经隐式把输入转成汉字了。我试验了下微软拼音输入法，也是输入连续字会这样，而且微软拼音输入连续字的很长的时候，会先把前面的部分显式转化成汉字，结果就是汉字加拼音。这个可能要看输入法和onchange对于按键事件的处理了。

**Comment by wangfupeng1988** [comment]
onchange 目前还有一个 bug ，就是通过 length 相同时就不触发 change 事件，这个 bug 会在下次升级版本的时候改过来。不过，我不确定你说的问题是否是这个 bug 导致的。
