### ISSUE TITLE
[已解决]有关代码高亮的问题

### ISSUE THREAD

**Issue by zcnhonker** [wangfupeng1988/wangEditor#1116]
准备用highlight做代码高亮，但是发现编辑器把代码标签里面的特殊字符都过滤了，虽然最终通过修改编辑器的代码实现了，但是还是建议做一下这方面处理可以让代码高亮做起来更方便一些。 

*PS：问题已解决，是我使用的问题，再仔细看下代码发现作者已经做了这方面的考虑了

**Comment by wangfupeng1988** [comment]
可以吧解决的方法简单描述一下，给其他使用者分享。
