### ISSUE TITLE
没有解绑事件

### ISSUE THREAD

**Issue by ifsmile** [wangfupeng1988/wangEditor#1117]
编辑器没有解绑事件，编辑器销毁的时候这些绑定事件依然存在

**Comment by hold-baby** [comment]
你遇到了哪些事件

**Comment by wangfupeng1988** [comment]
具体问题描述一下。

**Comment by ifsmile** [comment]
之前在一个vue的组件中用到了你们的编辑器，你们的插件中写了很多的绑定事件，在组件销毁的时候没有办法去解绑这些事件，所有占用了部分内存，如果重复调用这些组件，绑定组件会不断增多，导致内存泄露

**Comment by wangfupeng1988** [comment]
我明白你意思了，应该加一个销毁的方法，防止这种 SPA 重复 create 的情况。

我记录下，近期升级加上这个方法。

**Comment by ifsmile** [comment]
看好你们，加油~

**Comment by wangfupeng1988** [comment]
`v3.0.14`发布后，会增加一个`editor._offAllEvent()` API ，执行可以解绑所有事件。

你先用着这个，销毁的 API 时间原因还没有做出来，后面版本再升级。
