### ISSUE TITLE
建议可编辑区域dom 的min-height 100%适应上层dom高度

### ISSUE THREAD

**Issue by weijer** [wangfupeng1988/wangEditor#112]
<div class="wangEditor-textarea-container" style="max-height: none; height: 90%;">
<div class="wangEditor-textarea" contenteditable="true" style="min-height: 249px;">

主要是全屏后的体验！ 
1、height:90% 不准确 用 height: calc(100% - 34px); 更加精准

2、min-height 直接改成 100%自适应

**Comment by wangfupeng1988** [comment]
`min-height:100%`这个我会在新版中加上。不过 `height: calc(100% - 34px);` 得考虑浏览器兼容性问题，即使后面的2.0，也要兼容 IE8 的

目前win7的市场占有率还很高，IE8的用户还是很多的。

**Comment by wangfupeng1988** [comment]
2.0已发布，全屏功能已经不存在什么`90%`的问题啦
