### ISSUE TITLE
火狐浏览器下兼容性问题

### ISSUE THREAD

**Issue by zhuqingsong59** [wangfupeng1988/wangEditor#1120]
火狐浏览器下选择调整字体大小，加粗菜单自动高亮，且文字无加粗效果，无法取消高亮

**Comment by wangfupeng1988** [comment]
> 调整字体大小

V3 目前已经不支持，你使用的还是 V2 版本吗？

> 加粗菜单自动高亮，且文字无加粗效果，无法取消高亮

我在 windows macos 中都没有复现你说的问题。

**Comment by zhuqingsong59** [comment]
哦，我说的调整字体大小是指切换标题和正文类型的切换时，在火狐下加粗的会自动高亮，且无法取消

**Comment by wangfupeng1988** [comment]
> 指切换标题和正文类型的切换时

也没有遇到过高亮的情况
