### ISSUE TITLE
图片处理的两个问题

### ISSUE THREAD

**Issue by zcnhonker** [wangfupeng1988/wangEditor#1121]
一、在文档中看到说不把上传附件功能弄到编辑器的原因是删除附件而服务器附件没删除。 就有一个问题了，本地上传图片，但编辑的时候把图片删掉了，也没办法把服务器上已经上传的图片删除。 那是不是应该做一个记录这次已经上传的图片列表可以进行删除，或者是做一个删除图片的回调呢？

二、 插入图片后希望可以调整大小，而不是只能是图片本身的大小

**Comment by wangfupeng1988** [comment]
>  那是不是应该做一个记录这次已经上传的图片列表可以进行删除，或者是做一个删除图片的回调呢？

删除图片的场景太多，目前无法做统一的回调。你可以在 onchange 函数中自己去写逻辑做对比，这个完全可以实现。

> 插入图片后希望可以调整大小，而不是只能是图片本身的大小

那你是希望该变什么大小？

**Comment by zcnhonker** [comment]
增加可以改变图片尺寸的功能的

**Comment by wangfupeng1988** [comment]
本来就有啊。选中图片之后，再点击“图片”菜单，可以修改尺寸

**Comment by zero009** [comment]
<editor v-model="form.package_detail" class="editor" :menus="menus"/>
删除图片之后，发现在编辑器里是没了，可是在package_detail里还是存在该图片，只有在删除图片并且编辑器获取鼠标焦点后，detail才会发生变化，如果直接删除点提交仍存在问题，onchange我在源码放开并没发现有打印出啥，请问一下，可否知道解决方案

**Comment by zero009** [comment]
onchange只在编辑器获取焦点才会有反应
