### ISSUE TITLE
图片插入之后，我调用了customUploadImg方法，但是insert貌似没什么用

### ISSUE THREAD

**Issue by lovlin1990** [wangfupeng1988/wangEditor#1122]
我调用了插件，给压缩了一下，没有传到服务器
```
contentAttentionEditor.customConfig.customUploadImg = function (files, insert) {
				for(var i = 0;i < files.length;i++){
					lrz(files[i]).then(function (rst) {
						// 处理成功会执行
						console.log(rst);
						insert(rst.base64)
					})
					.catch(function (err) {
						// 处理失败会执行
						console.log(err);
					})
					.always(function () {
						// 不管是成功失败，都会执行
					});
				}
			}
```

**Comment by wangfupeng1988** [comment]
是用的最新版本吗？之前的版本这块有点 bug

**Comment by wangfupeng1988** [comment]
另外，参考我做的 demo https://github.com/wangfupeng1988/wangEditor/blob/master/example/demo/test-uploadimg.html#L51 我测试着是可以正常运行的

**Comment by lovlin1990** [comment]
3.0.12吗？ok，我可以再试试

**Comment by lovlin1990** [comment]
这个方法可以了，但是在文本里复制粘贴图片，出现两个

**Comment by wangfupeng1988** [comment]
> 但是在文本里复制粘贴图片，出现两个

window chrome 有这个问题，别人已经反馈了，我下次升级会修复这个问题。

**Comment by lovlin1990** [comment]
大概什么时间更新呢，因为我们这边的项目要上线，这个bug没法解决，要不你单独给我发一份吧，我的邮箱471260400@qq.com

**Comment by wangfupeng1988** [comment]
没啥特殊情况，会在下个周末更新。我现在还没有开始排查，你如果比较着急，可以自己看看这一块代码

https://github.com/wangfupeng1988/wangEditor/blob/master/release/wangEditor.js#L3187

**Comment by wangfupeng1988** [comment]
3.0.13 版本已经修复
