### ISSUE TITLE
wangedit自动聚焦没有提供配置？

### ISSUE THREAD

**Issue by laozhuorun** [wangfupeng1988/wangEditor#1123]
现在默认就是自动聚焦到富文本编辑器，看了下文档好像没有配置是否自动聚焦的？有没有临时处理方案？

**Comment by hold-baby** [comment]
因为目前是用的div焦点是浏览器自动获取的  你可以尝试使用trigger事件来达到失焦的目的

**Comment by laozhuorun** [comment]
@hold-baby trigger事件怎么使用可以达到失焦的目的

**Comment by hold-baby** [comment]
比如写个隐藏的input.trigger("blur")
