### ISSUE TITLE
从wps里面打开word，复制文本到编辑器里面，会携带一些杂乱的样式。

### ISSUE THREAD

**Issue by albedel** [wangfupeng1988/wangEditor#1124]
`\<h6\>\<h6calibri light';font-weight:="" bold;font-size:="" 16px;padding:="" 0px;box-sizing:="" border-box;color:="" rgb(72,="" 87,="" 106);font-style:="" normal;font-variant-ligatures:="" normal;font-variant-caps:="" normal;letter-spacing:="" normal;orphans:="" 2;text-indent:="" 0px;white-space:="" normal;widows:="" 2;word-spacing:="" 0px;line-height:="" 1.8;background-color:="" rgb(255,="" 255,="" 255)"=""><p><h6calibri light';font-weight:="" bold;font-size:="" 16px;padding:="" 0px;box-sizing:="" border-box;color:="" rgb(72,="" 87,="" 106);font-style:="" normal;font-variant-ligatures:="" normal;font-variant-caps:="" normal;letter-spacing:="" normal;orphans:="" 2;text-indent:="" 0px;white-space:="" normal;widows:="" 2;word-spacing:="" 0px;line-height: 1.8;background-color:="" rgb(255,="" 255,="" 255)"="">\<strong\>名词解释</strong></h6calibri></p><p>在估计预警指标的阈值时，本文使用了<strong>异常率</strong>。</p><p><h6calibri light';font-weight:="" bold;font-size:="" 16px;padding:="" 0px;box-sizing:="" border-box;color:="" rgb(72,="" 87,="" 106);font-style:="" normal;font-variant-ligatures:="" normal;font-variant-caps:="" normal;letter-spacing:="" normal;orphans:="" 2;text-indent:="" 0px;white-space:="" normal;widows:="" 2;word-spacing:="" 0px;line-height: 1.8;background-color:="" rgb(255,="" 255,="" 255)"=""></h6calibri></p><p><strong>异常率</strong>是指一天内订单数据中，发生异常订单的概率，它用于捕获用户或商户的异常行为。</p></h6calibri></h6>`

从word里面复制文本(标题和正文)，问题主要集中在错误的标签h6calibri 、错误的样式格式font-weight:="" bold;这两个。希望作者能够优化这两方面的问题。或者开放一个API出来，能够对黏贴的html片段进行操作，让我们自行处理掉这些标签或者样式。谢谢！

**Comment by wangfupeng1988** [comment]
> 或者开放一个API出来，能够对黏贴的html片段进行操作，让我们自行处理掉这些标签或者样式

这个建议不错，下次升级增加这个配置！

**Comment by wangfupeng1988** [comment]
https://www.kancloud.cn/wangfupeng/wangeditor3/448202

使用者可通过editor.customConfig.pasteTextHandle对粘贴的文本内容进行自定义的过滤，10.0.13 开始支持
