### ISSUE TITLE
希望下一版在部分菜单配置加上title，减少学习成本！

### ISSUE THREAD

**Issue by LastQuarterMoon** [wangfupeng1988/wangEditor#1126]
如题，如图
![15](https://user-images.githubusercontent.com/22828247/32535364-aa779bfa-c494-11e7-8742-ece9f77c4693.png)

**Comment by wangfupeng1988** [comment]
目前菜单图标的语意已经很明确了，而且很少有使用者提出这个问题。

这个优先级放低一些吧，不着急下一个版本就加。
