### ISSUE TITLE
提交bug全屏事件再小化后应该删掉z-index属性

### ISSUE THREAD

**Issue by weijer** [wangfupeng1988/wangEditor#113]
$editorContainer.css({
                    'position': 'relative',
                    'top': 0,
                    'left': 0,
                    'right': 0,
                    'bottom': 0,
                    //'z-index': 0, //删掉这个属性 会覆盖 下拉菜单z-index

                    '-webkit-box-shadow': '0 0 0 #CCC', 
                    '-moz-box-shadow': '0 0 0 #CCC',
                    'box-shadow': '0 0 0 #CCC'
                });

**Comment by wangfupeng1988** [comment]
> 删掉这个属性 会覆盖 下拉菜单z-index
我在目前线上的demo中没有发现全屏、覆盖之类的问题呀？

没明白你说的什么意思

**Comment by wangfupeng1988** [comment]
2.0已经发布，可验证官网demo中是否还存在这个问题。
