### ISSUE TITLE
关于列表的撤销操作问题

### ISSUE THREAD

**Issue by jay816314** [wangfupeng1988/wangEditor#1131]
环境：官网demo/本地均触发
浏览器：chrome 60.0.3112.113
问题：编辑区域中输入多行内容后，全选设置为有序/无序列表，ctrl+z撤销或者使用撤销按钮，列表变回无序的同时会删除第一行的内容。可无限复现。但不影响使用。

**Comment by wangfupeng1988** [comment]
列表撤销的问题，已经发现了，我正在跟踪解决。

> 列表变回无序的同时会删除第一行的内容。可无限复现。但不影响使用

这个我得具体查一查。

这个撤销问题，我会近期高优解决。

**Comment by wangfupeng1988** [comment]
> 列表变回无序的同时会删除第一行的内容

我复现了这个问题。这个问题的原因也是因为撤销的问题造成的，会一起修改。即便不是下一个版本马上修复，也会高优解决。

**Comment by liuwave** [comment]
这个问题什么时候能修复呢。

**Comment by wangfupeng1988** [comment]
已在修复计划中，会高优支持，目前个人精力问题不好确定具体时间

**Comment by yangfan0095** [comment]
这个问题怎么现在还没解决呀 9012年了都

**Comment by maojie0047** [comment]
2020年5.6日好像还没解决，哭哭

**Comment by yangfan0095** [comment]
之前看了下实现 感觉不好下手啊&nbsp; 没找到思路 囧囧



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "maojie0047"<notifications@github.com&gt;; 
发送时间: 2020年5月6日(星期三) 下午4:46
收件人: "wangfupeng1988/wangEditor"<wangEditor@noreply.github.com&gt;; 
抄送: "~~"<1056947355@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [wangfupeng1988/wangEditor] 关于列表的撤销操作问题 (#1131)





 
2020年5.6日好像还没解决，哭哭

**Comment by maojie0047** [comment]
我也下不了手。哎怎么办呐

**Comment by hongmx** [comment]
请问 问题解决了吗，具体代码是哪里呢，老项目是低版本，不好升级
