### ISSUE TITLE
不能用退格键

### ISSUE THREAD

**Issue by Fairfarren** [wangfupeng1988/wangEditor#1134]
我在backbone里面使用，分别用了两个方式引用，CDN和下载的文件。
直接下载的文件，是通过backbone的方式去引用的文件。
编辑器可以正常使用，但是不能用退格键，但是可以用删除键。
因为是接手的别人的项目，所以只能用backbone框架。

**Comment by wangfupeng1988** [comment]
首先，你得分清不能用退格键，是编辑器的问题，还是集成到backbone才发生的问题。先拿官网试一下。

如果是编辑器的问题，即官网的 demo 退格键也不好使，那需要我来修改。如果是引用到 backbone 才发生的问题，那就得你自己排查一下这个环境的问题了，看看是否哪里做了自定义的限制。
