### ISSUE TITLE
弹出对话框上的按钮在wangEditro编辑框上面会导致按钮不可点击，焦点会落在编辑框上

### ISSUE THREAD

**Issue by aizaimenghuangu** [wangfupeng1988/wangEditor#1135]
我使用的是sweetalert2 不确定时wangEditor的问题还是sweetalert2的问题
![default](https://user-images.githubusercontent.com/3993636/32612633-b8ab62b4-c5a3-11e7-8fef-192e4299aa3a.png)

**Comment by wangfupeng1988** [comment]
所有这些覆盖、被覆盖等问题，都是 z-index 的问题。去查一下相互有覆盖影响的元素的 z-index ，然后调整编辑器的 z-index 即可。
