### ISSUE TITLE
2个Editor太近会导致下拉框按钮不可点击

### ISSUE THREAD

**Issue by aizaimenghuangu** [wangfupeng1988/wangEditor#1136]
第一个Editor的下拉框按钮覆盖了第二个Editor，会导致覆盖的按钮不可点击，鼠标移动到该区域自动缩回。
详细如图描述：

![default](https://user-images.githubusercontent.com/3993636/32613236-4d125f1a-c5a5-11e7-9fd0-2d829ffa05c6.png)

**Comment by wangfupeng1988** [comment]
想办法调的距离远一点吧。或者，从源码中把标题 droplist 中的选项缩减几个。

**Comment by aizaimenghuangu** [comment]
有道理，综合评估最终还是将：$title: $('<p>设置标题</p>'), 这个去掉
