### ISSUE TITLE
复制word内容不过滤

### ISSUE THREAD

**Issue by flower233** [wangfupeng1988/wangEditor#1139]
将word的内容复制到editor，word样式不过滤，保存后全都保存到数据库了

**Comment by wangfupeng1988** [comment]
参考这里 https://www.kancloud.cn/wangfupeng/wangeditor3/448202 先通过`pasteTextHandle`自己过滤吧。

编辑器统一的粘贴 word excel 过滤规则，正在优化中，尚未发布。
