### ISSUE TITLE
换行bug 

### ISSUE THREAD

**Issue by weijer** [wangfupeng1988/wangEditor#114]
1、当把输入框内容全部按键盘删除完 在chrome下会保留一个<p><br></p> 但在火狐中直接完全删除了
2、在火狐中回车换行只要增加了表情 <p>标签就会删除！
3、还会莫名其妙的按回车换行新增的标签是<div></div>

**Comment by wangfupeng1988** [comment]
我理解的是全部删除之后，再新增内容或者换行时出的问题。其实问题的本质在于，全部删除之后，再换行浏览器就会默认用`<div>`换行，而不是`<p>`

我在目前的版本中修改了一部分，就是普通的删除，删除到没有内容的，编辑器会阻止继续删除。

而今天看群里大家讨论，我又发现了另外一个问题：`ctrl + a`全选之后再删除，就又不行了。

这段时间我忙着重构2.0版本，这个我会在2.0版本中加上。

**Comment by wangfupeng1988** [comment]
2.0已经发布，可以去官网demo中，再验证一下这个问题。如果还存在，可再提交问题反馈给我。
