### ISSUE TITLE
关于代码高亮的问题

### ISSUE THREAD

**Issue by NanShanJi** [wangfupeng1988/wangEditor#1140]
请问编辑器是否支持插入代码的时候选择代码是什么语言，好管理代码高亮。就像 [highlight.js](https://highlightjs.org/) 这种代码高亮插件我应该怎么在编辑器中调用，感谢

**Comment by wangfupeng1988** [comment]
3.0 版本开始，弱化了插入代码的功能。因为，使用编辑器的人群中，大部分还是不需要插入代码的（程序员不是主要群体），因此将不太重要的功能弱化，以减少插件的体积、复杂度、维护成本。

个人开源项目，还请体谅。

**Comment by cttaohua** [comment]
代码高亮很重要的啊，可不可以开一个程序员专用的版本
