### ISSUE TITLE
无法从code模式中退出

### ISSUE THREAD

**Issue by Treagzhao** [wangfupeng1988/wangEditor#1141]
我先写一小段文字，然后选中，在点击“代码”那个按钮，这段文字就会变成有背景色的代码。可是我输入完了之后回车，编辑器会自动另起一个新的代码块，这样我无论如何都无法从code模式中退出了。

ps：强烈渴望能有一个自动配置前景色和背景色的api

**Comment by wangfupeng1988** [comment]
> 无法从code模式中退出

去官网试试，我用 mac chrome 试着，在 code 块中，连续两次回车，能退出来。如果你的还是有问题，给我反馈系统、浏览器。

> 强烈渴望能有一个自动配置前景色和背景色的api

这我记录下，下次升级加上吧。

**Comment by Treagzhao** [comment]
确实不行。操作系统 mac os  浏览器 chrome 61。要不要给我发个邮箱地址，我录个视频给你发过去。

**Comment by Treagzhao** [comment]
那个代码按钮有两种用法，一种是点击打开一个输入框，然后在里面输入内容；另一种是我先写好一些文字，然后选中，在点击“代码”按钮。这两种情况展示效果也是不一样的。你刚才说的双击能够退出，我试过了，是第一种，确实可以退出，但是第二种操作是不能退出的。

**Comment by wangfupeng1988** [comment]
第二种，你是不是选中整个段落，然后点击“代码”按钮了？

**Comment by Treagzhao** [comment]
没错 ，这样做会有问题么？

**Comment by wangfupeng1988** [comment]
确实会有这样的问题。

你说的第二种用法，本来是选中一行句子中的一个单词，然后点击“代码”按钮，让这个单词出现 code 效果。

而你现在选中整个句子，我试了一下会出现你所述的问题，我会记录下来，后期升级做修复。

**Comment by Treagzhao** [comment]
万分感谢😭😭🙏🙏

**Comment by wangfupeng1988** [comment]
修复了，更新`v3.0.14`试一下

**Comment by Treagzhao** [comment]
太感谢啦  mua
