### ISSUE TITLE
如何改变编辑器的图片上传顺序

### ISSUE THREAD

**Issue by huxiuhang** [wangfupeng1988/wangEditor#1142]
我刚刚遇到一个问题，一次选择多个图片上传，图片上传的顺序不是按照选择的顺序进行上传的，麻烦问一下这个可以怎么样修改一下

**Comment by wangfupeng1988** [comment]
是按照选择的顺序添加的，可以通过`editor.customConfig.customUploadImg`这个函数来看一下`files`里面的顺序。 https://www.kancloud.cn/wangfupeng/wangeditor3/335782

但是，上传之后返回的图片顺序，就是你自己的 server 端决定的了。
