### ISSUE TITLE
请问V3没有查看源码的功能么？

### ISSUE THREAD

**Issue by kanganxi** [wangfupeng1988/wangEditor#1143]
请问是否支持？如果支持如何修改？谢谢！

**Comment by hold-baby** [comment]
查看源码指的是什么

**Comment by kanganxi** [comment]
不好意思，是我没表达清楚，就是显示源码的功能

**Comment by hold-baby** [comment]
![image](https://user-images.githubusercontent.com/21041219/32772899-58af13ca-c962-11e7-9960-7fd4590f4e25.png)

**Comment by hold-baby** [comment]
这两个有什么区别？

**Comment by wangfupeng1988** [comment]
v3 的显示源码去掉了，不作为编辑器默认提供的功能。因为，真正使用编辑器的用户，能自己写 html 代码的毕竟是少数（如果使用者都是程序猿，那干脆用 markdown 好了）。另外，开放编辑器 html 代码会有安全风险。

最后，如果你自己确实需要，那就自己实现吧。编辑内容的 html 代码可以获取，获取之后自己展示即可。修改之后，也可以通过既有的 API 更新到编辑内容中。

**Comment by kanganxi** [comment]
@wangfupeng1988  感谢兄弟回复，明白了，非常感谢

**Comment by wangfupeng1988** [comment]
客气了！
