### ISSUE TITLE
从word中粘贴过来文本会默认生成一大堆注释

### ISSUE THREAD

**Issue by zhiainan** [wangfupeng1988/wangEditor#1147]
从word中粘贴过来文本，会自动生成一个p标签，立面包含一大堆注释，请问阻止这个p标签生成

**Comment by wangfupeng1988** [comment]
先用`editor.customConfig.pasteTextHandle`自行处理吧 https://www.kancloud.cn/wangfupeng/wangeditor3/448202

对 word excel 等的粘贴过滤，我后续升级统一做。
