### ISSUE TITLE
【表格动态操作体验不友好】

### ISSUE THREAD

**Issue by MerlChen** [wangfupeng1988/wangEditor#1148]
#### 发现的问题：
> 1、表格的增加行、增加列、删除行、删除列，需要在菜单栏中进行操作，这样体验不够好。
> 2、没有右键菜单，右键菜单可设置常用属性
> 3、图片上传只能采取在线图片形式，无法本地进行图片上传并预览

tks.

**Comment by wangfupeng1988** [comment]
> 1、表格的增加行、增加列、删除行、删除列，需要在菜单栏中进行操作，这样体验不够好。2、没有右键菜单，右键菜单可设置常用属性

目前确实如你所说。从我的考虑，一个简洁的富文本编辑器的应用场景，表格的使用不会特别多，对表格的操作就会更少了。因此，我把使用场景比较少的功能直接弱化和隐藏，产品上能更加简洁，代码上会更加轻量和易维护。

> 3、图片上传只能采取在线图片形式，无法本地进行图片上传并预览

第一，可以支持本地图片上传，去看文档说明；第二，上传并没有预览功能，不过你可以通过`customUploadImg`来自己配置。 https://www.kancloud.cn/wangfupeng/wangeditor3/335782
