### ISSUE TITLE
onFocus和onBlur事件不太灵敏，建议使用form标签包裹起来，利用form的focus和blur事件提供回调

### ISSUE THREAD

**Issue by Char-Ten** [wangfupeng1988/wangEditor#1149]
之前使用了`editor.custom.customConfig.onblur`这个事件的时候，发现不太灵敏，有时触发有时不触发，也很难复现。
索性现在我是用一个form标签，把编辑器挂载在上面：
![image](https://user-images.githubusercontent.com/17474452/32931334-a20f94c0-cb9e-11e7-9937-a085e2faa3b9.png)
目前是在应付项目，未来我觉得可以的话可以试试实现placeholder

**Comment by wangfupeng1988** [comment]
放在 form 里面可能会有很多问题。例如之前那种提交时校验不通过这种问题。
