### ISSUE TITLE
批量上传图片页面卡死

### ISSUE THREAD

**Issue by damienzhong** [wangfupeng1988/wangEditor#1150]
在vue中引用wangEditor,后台返回数据格式为
`{"code":"0","message":"成功","result":"success","data":["url","url2".....]}`,
我想进行批量图片上传，遍历图片路径，通过循环插入多个图片，customInsert的代码如下
`editor.customConfig.uploadImgHooks = {
        customInsert: function (insertImg, result, editor) {
          for(var i=0;result.data.length;i++){
            insertImg(result.data[i])
          }
        }
      }`
点击上传之后，页面卡死，控制台也没报错。
请问批量上传图片如何处理？

**Comment by wangfupeng1988** [comment]
先看下卡顿的时候，`customInsert`触发了吗？看看到底是上传卡还是插入图片卡。

**Comment by damienzhong** [comment]
是我造成了死循环，打扰了

**Comment by hwhgit** [comment]
进行多张图片上传,点击确认但是console.log(result)，里面始终只有一张图片地址editor.customConfig.uploadImgHooks = { customInsert: function (insertImg, result, editor) { console.log(result) } }
