### ISSUE TITLE
关于附文本编辑器动态赋值问题

### ISSUE THREAD

**Issue by JackieGGu** [wangfupeng1988/wangEditor#1151]
附文本编辑器的图片上传地址在editor.create();之后如果需要改变其editor.customConfig.uploadImgServer的值怎么处理，或者提供一个reload()方法，有没有?

**Comment by wangfupeng1988** [comment]
`create()`之后没法修改。如果你必须有这种`create()`之后需要修改 server 地址的需求，可以使用`editor.customConfig.customUploadImg` https://www.kancloud.cn/wangfupeng/wangeditor3/335782
