### ISSUE TITLE
wangEditor 粘贴网页代码，被解析成具体样式

### ISSUE THREAD

**Issue by zhangps110** [wangfupeng1988/wangEditor#1152]
wangEditor 粘贴网页代码，被解析成具体样式。怎么破~

**Comment by wangfupeng1988** [comment]
> 被解析成具体样式

不懂

**Comment by zhangps110** [comment]
能发图片就好了。那我详细说一下是怎么出现的吧！在其他网页上找一个textarea或者input text标签（不是文本），然后复制到编辑器中去。编辑器中显示的是解析过后的，也就是长方形元素。

正确的显示应该是文本，或者直接不能复制进去。

下面是编辑器处理粘贴内容的源码，被我稍稍修改了下。没有出现上面所述问题。

希望作者指导下，这样修改会不会带来其他问题。谢谢作者大大了！

`        // 处理粘贴的内容
        function handle(elem) {
            if (!elem || !elem.nodeType || !elem.nodeName) {
                return;
            }
            var $elem;
            var nodeName = elem.nodeName.toLowerCase();
            var nodeType = elem.nodeType;
            var childNodesClone;

            // 只处理文本和普通node标签
            if (nodeType !== 3 && nodeType !== 1) {
                return;
            }

            $elem = $(elem);

            // 如果是容器，则继续深度遍历
            if (nodeName === 'div') {
                childNodesClone = [];
                $.each(elem.childNodes, function (index, item) {
                    // elem.childNodes 可获取TEXT节点，而 $elem.children() 就获取不到
                    // 先将 elem.childNodes 拷贝一份，一面在循环递归过程中 elem 发生变化
                    childNodesClone.push(item);
                });
                // 遍历子元素，执行操作
                $.each(childNodesClone, function () {
                    handle(this);
                });
                return;
            }
            
            if (legalTagArr.indexOf(nodeName) >= 0) {
                // 如果是合法标签之内的，则根据元素类型，获取值
                resultHtml += getResult(elem);
            } else if (nodeType === 3) {
                // 如果是文本，则直接插入 p 标签
                resultHtml += '<p>' + elem.textContent + '</p>';
            } else if (nodeName === 'br') {
                // <br>保留
                resultHtml += '<br/>';
            }
            else {
                 **//------------------------这里被我修改了------------------------------------
				var ignoreTag=[ //这里被我修改了。可以显示
					'meta', 'style', 'script', 'object', 'form', 'iframe', 'hr', 'textarea', 'input', 
					'META', 'STYLE', 'SCRIPT', 'OBJECT', 'FROM', 'IFRAME', 'HR', 'TEXTAREA', 'INPUT'
				];
                // 忽略的标签
                if (ignoreTag.indexOf(nodeName) >= 0) {
                    return;
                }
            //------------------------这里被我修改了------------------------------------**
                // 其他标签，移除属性，插入 p 标签
                $elem = $(removeAttrs(elem));
                // 注意，这里的 clone() 是必须的，否则会出错
                resultHtml += $('<div>').append($elem.clone()).html();
            }
        }`

**Comment by zhangps110** [comment]
[](http://www.jb51.net/article/14397.htm)  复制这个链接中正文的全部内容到编辑器，就能浮现此bug。

**Comment by zhangps110** [comment]
复制这个[链接](http://www.jb51.net/article/14397.html)中正文的全部内容到编辑器，就能浮现此bug。

**Comment by zhangps110** [comment]
复制这个[链接](http://www.jb51.net/article/14397.htm)中正文的全部内容到编辑器，就能浮现此bug。

**Comment by wangfupeng1988** [comment]
先不要修改源码，先用`editor.customConfig.pasteTextHandle`来自定义过滤粘贴的内容 https://www.kancloud.cn/wangfupeng/wangeditor3/448202  （修改了源码，你以后还怎么升级了？）

然后把你写的`editor.customConfig.pasteTextHandle`函数内容发给我，我看一下。

**Comment by zhangps110** [comment]
这个自定义操作 只有v3才有的吧！目前我用的是之前v2的最新版。我测试了下，这个问题在v3的最新版本（官网的demo）中依旧存在。

**Comment by wangfupeng1988** [comment]
> 这个自定义操作 只有v3才有的吧！

是的

> 这个问题在v3的最新版本（官网的demo）中依旧存在。

后面会修复。暂时用`editor.customConfig.pasteTextHandle`自己解决。

------

另外，v2 目前已经不再技术支持了。个人精力有限，请体谅。
