### ISSUE TITLE
表格问题

### ISSUE THREAD

**Issue by sunnylu28** [wangfupeng1988/wangEditor#1153]
表格列宽不能自定义，在word复制进来的表格不能满屏。

**Comment by wangfupeng1988** [comment]
word excel 等粘贴样式的问题，我会在后续升级中统一处理。

现在可以先使用`editor.customConfig.pasteTextHandle`自定义处理粘贴的内容  https://www.kancloud.cn/wangfupeng/wangeditor3/448202
