### ISSUE TITLE
希望增加H5 VIDEO支持

### ISSUE THREAD

**Issue by AspenLuoQiang** [wangfupeng1988/wangEditor#1154]

**Comment by wangfupeng1988** [comment]
那视频怎么办？上传上去还是弄个链接？

**Comment by AspenLuoQiang** [comment]
@wangfupeng1988 其实跟图片是一个道理吧，可以直接链接，也可以上传吧，最终就是里面插入一个video标签就行了

**Comment by wangfupeng1988** [comment]
这个暂时不会支持。

第一，提出这个需求的用户比较少。第二，上传视频可和上传图片不一样，上传图片现在都有各种问题和学习成本，上传视频那就太麻烦了。
