### ISSUE TITLE
给上传的图片加跳转链接要怎么做？

### ISSUE THREAD

**Issue by ChenBo233** [wangfupeng1988/wangEditor#1156]
要给上传的图片加跳转链接要自己扩展功能么？能简单说一下怎么实现么，O(∩_∩)O谢谢

**Comment by wangfupeng1988** [comment]
1. 服务器端返回的数据格式，自己去定义（有图片地址、有图片链接），然后使用`customInsert`自定义插入 https://www.kancloud.cn/wangfupeng/wangeditor3/335782
2. 修改 https://github.com/wangfupeng1988/wangEditor/blob/master/release/wangEditor.js#L3846 ，`editor.cmd.do('insertHTML', '<img src="' + link + '" style="max-width:100%;"/>');` 插入图片的时候把链接也一起插入进去。

目前只能你自己去修改源码实现了，默认情况下不支持。
