### ISSUE TITLE
建议增加自定义菜单按钮的管理功能

### ISSUE THREAD

**Issue by dclovec** [wangfupeng1988/wangEditor#1159]
比如我需要添加一个自定义的格式化样式功能，在菜单栏上放一个图标按钮，点一下就执行这个功能

**Comment by wangfupeng1988** [comment]
这个功能 v2 有，但是使用的人太少了，成本和收益不匹配。
因此 v3 去掉了，降低了很多维护成本。

如果需要自定义，可以 fork 源码自己去修改。目前源码中的菜单也都是分文件写的，扩展一个也不麻烦。遇到问题可以提给我。

**Comment by dclovec** [comment]
@wangfupeng1988 好的，谢谢
