### ISSUE TITLE
粘贴时有自定义标签无法过滤掉

### ISSUE THREAD

**Issue by argb** [wangfupeng1988/wangEditor#1162]
从一个app上复制了一句话，粘贴的编辑器里后上面有一大堆自定义标签和样式，过滤不掉。
我看了文档，说是默认设置是会过滤冗余标签的，然并卵。

**Comment by wangfupeng1988** [comment]
https://www.kancloud.cn/wangfupeng/wangeditor3/448202  先使用`editor.customConfig.pasteTextHandle`自己过滤一下

**Comment by argb** [comment]
建议加一个白名单，因为外部粘贴过来的东西总可能有各种奇怪的标签，没办法一一列举。有白名单的话便于控制。

**Comment by argb** [comment]
可否加一个插入音频的按钮或者插入html，或者只加入一个音频的字体，我改了下代码，但是没有字体，我加了个好丑的按钮，这是扬声器符号的unicode: 1F508

**Comment by wangfupeng1988** [comment]
> 可否加一个插入音频的按钮或者插入html，或者只加入一个音频的字体

个性化需求不会在编辑器中支持，需要自己去二次开发
