### ISSUE TITLE
Firefox 57 下，选中删除全部内容后，会丢失默认格式

### ISSUE THREAD

**Issue by mattchen** [wangfupeng1988/wangEditor#1163]
简单测试了下，可能是 Firefox 57+ 的专属 bug，测试平台 macOS 10.13

具体如下：
编辑器中填写任意内容，比如打开官网中默认编辑器，按 Cmd + A 选中所有内容，按「Del」键删掉内容，这时如果再输入新内容，会被 `<div>` 包装，而不是默认的 `<p>` 标签，在 Chrome 下测试无此问题。

**Comment by wangfupeng1988** [comment]
我试了一下你说的复现场景，并没有复现。我是 macOS 10.13 firefox57

> 编辑器中填写任意内容，比如打开官网中默认编辑器，按 Cmd + A 选中所有内容，按「Del」键删掉内容，这时如果再输入新内容，会被 `<div> `包装，而不是默认的 `<p>` 标签

我试的结果是，重新输入内容依然会正确的被`<p>`包裹，只不过前面多了一个`<br>`而已

**Comment by mattchen** [comment]
录了个视频，不会裁剪，又截了图，如下：

默认情况：
![screen shot 2017-11-24 at 6 27 18 pm](https://user-images.githubusercontent.com/88584/33206495-6a078d92-d145-11e7-88ee-413a899d7abd.png)

Cmd + A 全选删除后：
![screen shot 2017-11-24 at 6 27 24 pm](https://user-images.githubusercontent.com/88584/33206496-6a32ea8c-d145-11e7-948f-c2450355b252.png)

输入「abc」之后：
![screen shot 2017-11-24 at 6 27 30 pm](https://user-images.githubusercontent.com/88584/33206497-6a5d3602-d145-11e7-8714-dc787c6dfd78.png)

换行再输入 「123」之后：
![screen shot 2017-11-24 at 6 27 40 pm](https://user-images.githubusercontent.com/88584/33206498-6a89c280-d145-11e7-9ce9-941cfad163ba.png)

最后是版本号：
![screen shot 2017-11-24 at 6 28 36 pm](https://user-images.githubusercontent.com/88584/33206620-c5669f20-d145-11e7-899d-75d3943f950b.png)

**Comment by wangfupeng1988** [comment]
我这边的情况是：在你第二个截图的时候，即全部删除的时候，光标处会立刻自动创建一个`<p></p>`，必会暴露在`<div></div>`中

**Comment by brosegu** [comment]
火狐下，直接在全选状态下输入字母或者数字，输入内容会暴露在格式之外

**Comment by wangfupeng1988** [comment]
个人精力原因，先暂停修复 Firefox 的兼容性问题。Firefox 是在太多这种不好修复的兼容性问题了！！！
