### ISSUE TITLE
为什么表情和手势全是'😆'这样的符号

### ISSUE THREAD

**Issue by Chen1997c** [wangfupeng1988/wangEditor#1164]
RT.官网的demo 表情和手势也都是😆😆😆😆😆😆😆😆😆😆

**Comment by wangfupeng1988** [comment]
“手势”不是啊，你截图给我看看

**Comment by Chen1997c** [comment]
![5 jef7k6uofkso8qjq 7o1](https://user-images.githubusercontent.com/32232411/33207323-2df52d7a-d148-11e7-8ae4-e3d43abe1d35.png)
![9 36_ hyd4 32pahvg_i0o](https://user-images.githubusercontent.com/32232411/33207324-2e283364-d148-11e7-9caa-c1db01abffd6.png)

**Comment by wangfupeng1988** [comment]
和 https://github.com/wangfupeng1988/wangEditor/issues/1165 这个问题是一个情况，以后统一在 https://github.com/wangfupeng1988/wangEditor/issues/1165 这里回复
