### ISSUE TITLE
表情和手势部分是乱码，为什么

### ISSUE THREAD

**Issue by niannianliu** [wangfupeng1988/wangEditor#1165]
3.0.13版本，只引用了wangEditor.min.js，表情和手势部分是乱码，如下图，
![snap](https://user-images.githubusercontent.com/4651329/33199508-9ade44e8-d12b-11e7-9794-9fd6b5919cd3.png)
![snap2](https://user-images.githubusercontent.com/4651329/33199967-90d2fafa-d12d-11e7-893d-9e584bcb5d4e.png)

**Comment by niannianliu** [comment]
![snap2](https://user-images.githubusercontent.com/4651329/33199788-d869870e-d12c-11e7-82c3-b4febe7b64e0.png)

**Comment by wangfupeng1988** [comment]
应该是你浏览器或者系统还不支持这些 emoji 表情。这块的兼容性问题，我后续升级会有限考虑。是在不行，还支持之前的自己配置图片的形式。

**Comment by wangfupeng1988** [comment]
如果暂时因为 emoji 兼容性无法使用，可以自定义配置成图片格式的表情 https://www.kancloud.cn/wangfupeng/wangeditor3/460259
