### ISSUE TITLE
建议菜单栏增加文字大小的设置

### ISSUE THREAD

**Issue by dmbjzql** [wangfupeng1988/wangEditor#1166]
也不需要太多
就默认几个
[小，一般，大，极大]
几个选项就行了
每次都要改html很不方便
如有采纳，万分感谢...

**Comment by wangfupeng1988** [comment]
字体、字号，应该由 html 标签和 css 统一控制，暂时不会加这俩功能。

也是因为，字体、字号看似简单的功能，其实坑很多，用的人并不多，因此暂时放弃。
