### ISSUE TITLE
要做修改功能，默认绑定数据，无法绑定到富文本里面

### ISSUE THREAD

**Issue by chinahxf** [wangfupeng1988/wangEditor#1167]
```
<div id="editorElem" v-model="form_data.body_html" style="text-align:left">
                    {{form_data.body_html}}
</div>
```
在form_data.body_html中有值，可是无法绑定到编辑器里面，这种写法被绑定到了外面，html部分格式如下
```
<div 绑定的div>
      我要绑定的内容
     <div>富文本的头部</div>
     <div>富文本的内容区域</div>
</div>
```

这是什么原因呢？
设置了简单文本也在外面，
用js的方法，简单文本可以设置进去，可是带有p标签的文本就无法设置进去，看html的格式里显示，设置的纯文本不带标签的在编辑器自带p标签的外面。有没有遇到这种事情的，或者大家都是怎么解决这个问题的

修改功能富文本绑定原来的数据

**Comment by wangfupeng1988** [comment]
你把` {{form_data.body_html}}`换成静态的 html 代码，如`<p>123123</p>`试试，应该没问题。

另外，你的`v-model`应该不会起作用，`v-model`我理解应该是针对 input textarea 才会起作用
