### ISSUE TITLE
3.0.15版本自定义表情不起作用

### ISSUE THREAD

**Issue by niannianliu** [wangfupeng1988/wangEditor#1169]
[https://github.com/wangfupeng1988/wangEditor/issues/1165]
之前提1165问题，建议更新到3.0.15版本自定义表情，更新后发现 editor.customConfig.emotions = [xxx];不起作用。简单测试比如editor.customConfig.emotions = []；数组传空，还是原来显示表情和手势两个tab，内容也不变

**Comment by wangfupeng1988** [comment]
按照这个例子做一遍，这个我测试过 https://github.com/wangfupeng1988/wangEditor/blob/master/example/demo/test-emot.html

**Comment by kylin007** [comment]
遇到了同样的问题，我是想要自己配置表情，按照作者的样例写的html页面没有问题，但是放在我的页面就会出现无效（显示还是默认的tab）（两次代码相同）   我使用的是.Net MVC框架，MVC5视图页，求助
