### ISSUE TITLE
当textarea 的属性存在 disabled 时，能否禁止输入。

### ISSUE THREAD

**Issue by jhack77** [wangfupeng1988/wangEditor#117]
一般情况，用户未登陆是不允许发表问题的。此时textarea 会设置为disabled，，希望编辑器在初始时能检测这个属性，然后禁用输入，禁止点击菜单图标。如果用户点击时，会跳出提示之类的。。

个人认为这样做对用户体验好。

**Comment by wangfupeng1988** [comment]
恩，这个我在2.0版本的升级计划中早就加上了。这个功能不打算在当前版本中维护了，我会在2.0发布之后，按照所有升级计划的优先级，加上这个功能。敬请期待吧

**Comment by wangfupeng1988** [comment]
http://www.kancloud.cn/wangfupeng/wangeditor2/115073  目前已经支持 启用/禁用 功能。

不过没有像你说的那样实现，因为现在编辑器不仅仅支持 textarea 还支持 div，所以，就用API的形式了
