### ISSUE TITLE
请问embed标签是如何粘贴到编辑器中的？

### ISSUE THREAD

**Issue by qianxuemin** [wangfupeng1988/wangEditor#1170]
我将如下链接打开，选择有视频的部分，复制粘贴到编辑器，为什么在你的编辑器中可以显示视频，但是放到百度编辑器，或者直接在任意属性设置为contenteditable=true的div中，粘贴时embed标签被过滤了？

http://www.gov.cn/premier/2017-09/06/content_5223073.htm

**Comment by qianxuemin** [comment]
我在使用百度编辑器的过程中，embed标签被过滤了，后来发现你这里可以不过滤，想问一下你是如何做到的。

**Comment by wangfupeng1988** [comment]
https://www.kancloud.cn/wangfupeng/wangeditor3/448202 可以使用`https://www.kancloud.cn/wangfupeng/wangeditor3/448202`自定义过滤掉 embed

**Comment by qianxuemin** [comment]
昨天通宵把问题解决了😅，从你这找到灵感，不胜感激。我找到的原因是：百度编辑器使用的是浏览器自带的paste事件，粘贴时为了安全，embed标签被过滤了；后来采用阻止浏览器默认事件，使用自定义的paste方法直接从剪切板获取复制的内容，就可以粘贴了。

**Comment by wangfupeng1988** [comment]
👍
