### ISSUE TITLE
粘贴到编辑区域的图片能否添加监听及处理事件

### ISSUE THREAD

**Issue by spiritjp** [wangfupeng1988/wangEditor#1171]
目前在工具栏上上传图片有对应的回调，并且可以禁止网络图片。能否在内容区域粘贴图片时也提供类似的回调方法，或者可以提供将粘贴到能容中的网络图片直接保存到服务器上的方法。谢谢！

**Comment by wangfupeng1988** [comment]
https://www.kancloud.cn/wangfupeng/wangeditor3/448202  用`editor.customConfig.pasteTextHandle`即可做到。

分析拿到粘贴内容中的图片，做一下**标记**。然后将图片的 url 传递给 server ，由 server 下载图片并保存，然后 server 将保存后的图片的 url 返回给前端。前端再将之前做过**标记**的图片的 src 修改为获取的 url
