### ISSUE TITLE
图片上传

### ISSUE THREAD

**Issue by anruyi** [wangfupeng1988/wangEditor#1173]
那位前辈能提供一下3.*版本的图片上传demo？
急需，想要借鉴学习一下 （php）

**Comment by hold-baby** [comment]
https://www.kancloud.cn/wangfupeng/wangeditor3/335782
文档已经很详细了

**Comment by anruyi** [comment]
@hold-baby 
文档确实很详细，但着实需要一个php demo对照学习一下。

**Comment by anruyi** [comment]
@hold-baby 
`Uncaught Error: wangEditor: 上传图片返回结果错误，返回结果是: uploadImage[]array(1) {
  ["chuanghushuicaihuatupian_jpg"]=>
  array(5) {
    ["name"]=>
    string(28) "chuanghushuicaihuatupian.jpg"
    ["type"]=>
    string(10) "image/jpeg"
    ["tmp_name"]=>
    string(22) "C:\Windows\php13E4.tmp"
    ["error"]=>
    int(0)
    ["size"]=>
    int(88488)
  }
}


    at T._alert (wangEditor.js:3335)
    at XMLHttpRequest.E.onreadystatechange (wangEditor.js:3495)`

主要还是自己写有bug，而且还找不到原因

**Comment by wangfupeng1988** [comment]
https://github.com/wangfupeng1988/wangEditor#运行-demo  参照这里运行起来，有上传图片的功能，不过使用 nodejs 写的。

php 的代码，我也不会写，可以去 QQ 群问一下。

交流QQ群 164999061 281268320

**Comment by anruyi** [comment]
我去试一下，谢谢！ @wangfupeng1988
