### ISSUE TITLE
wangEditor2 时代支持plupload，在wangEditor3 里找不到了，难道不支持了吗？

### ISSUE THREAD

**Issue by muding** [wangfupeng1988/wangEditor#1175]
我需要在前端处理好图片大小再上传，这个功能没有，不方便啊？

**Comment by wangfupeng1988** [comment]
https://www.kancloud.cn/wangfupeng/wangeditor3/335782 看`editor.customConfig.customUploadImg`这个配置能满足你的需求吗？

**Comment by awokelee** [comment]
同问
