### ISSUE TITLE
图片上传后，怎么修改图片显示大小

### ISSUE THREAD

**Issue by oenday87** [wangfupeng1988/wangEditor#1176]
1。图片上传后，怎么修改图片显示大小
2。能不能多定义几种字体大小
3。字体颜色能多定义几种不

**Comment by wangfupeng1988** [comment]
> 图片上传后，怎么修改图片显示大小

点击图片，使图片处于选中状态，然后点击菜单栏里面的“图片”菜单，即可

> 能不能多定义几种字体大小

v3 开始不再支持字体和字号

> 字体颜色能多定义几种不

https://www.kancloud.cn/wangfupeng/wangeditor3/455793

**Comment by oenday87** [comment]
v3 开始不再支持字体和字号，那功能就不强大啊！！！

**Comment by oenday87** [comment]
能不修改js，直接设置editor的宽高吗

**Comment by wangfupeng1988** [comment]
不在于强大不强大，需求不同而已。
