### ISSUE TITLE
菜单不能自动换行，会跑到编辑框外面去

### ISSUE THREAD

**Issue by matthewton** [wangfupeng1988/wangEditor#1177]
打开
http://www.wangeditor.com/index.html，
把浏览器窗口拖窄，会发现菜单跑到浏览器可视区的外面去了，而编辑框比较小，菜单根据点不到。可惜这里不能上传图片。

**Comment by wangfupeng1988** [comment]
菜单栏强制不能换行，如果编辑区域很小，就精简菜单吧。v2 支持菜单栏换行，但是显示效果太差。

> 可惜这里不能上传图片。

不明白啥意思

**Comment by matthewton** [comment]
嗯，我刚在文档中找到这个信息：“编辑器创建之前，可使用editor.customConfig.menus定义显示哪些菜单和菜单的顺序。注意：v3 版本的菜单不支持换行折叠了（因为换行之后菜单栏是在太难看），如果菜单栏宽度不够，建议精简菜单项。”
我的建议是，当窗口变小的时候，把菜单栏做成多行。不知是否可行？
因为不能换行，显示又没有调整，按钮跑到外面去也很难看。精简，呃？就是让用户忍忍呐

**Comment by KaiyangJi** [comment]
其实你可以自己改样式就好了。
.w-e-toolbar {
    flex-wrap: wrap;
}
setzIndex() {
                console.log(document.querySelectorAll('.w-e-menu'));
                const menuNodes = document.querySelectorAll('.w-e-menu');
                for(let i =0; i < menuNodes.length; i++ ) {
                    menuNodes[i].style.zIndex = menuNodes.length - i + 100000;
                }
            },

**Comment by wangfupeng1988** [comment]
@matthewton 改变一下页面排列布局吧。从产品角度考虑：需要这么多菜单功能的编辑器，应该要占比较宽大的一块页面区域，而不是小小的一个角落

**Comment by wangfupeng1988** [comment]
@KaiyangJi 这么做也可以，但是还是不建议。因为我觉得菜单换行确实太难看了。
