### ISSUE TITLE
浏览器粘贴图片不成功，（chrome,火狐等）

### ISSUE THREAD

**Issue by paocaijun** [wangfupeng1988/wangEditor#1179]
富文本框内粘贴图片无反应。在粘贴图片时，canDo()执行了两次。希望作者能解决下，3.0.15版本

**Comment by wangfupeng1988** [comment]
请写出详细的复现步骤（图片是如何复制、粘贴的）。另外，官网有这个问题吗？

**Comment by paocaijun** [comment]
官网也有问题。1、用win10自带的照片查看器打开一张图片，在图片上右键，选择‘复制’，打开http://www.wangeditor.com/，在富文本框内ctrl+v（或右键选择“粘贴”）,浏览器无反应。2、选择word里面的图片ctrl + c，富文本框内ctrl+v，浏览器无反应。3、在百度上找张图片右键选择‘复制‘，富文本框内粘贴成功。


![image](https://user-images.githubusercontent.com/24297271/33471458-806af3f4-d6a8-11e7-8a67-cf0cc57dbcda.png)

**Comment by wangfupeng1988** [comment]
> 1、用win10自带的照片查看器打开一张图片，在图片上右键，选择‘复制’，打开http://www.wangeditor.com/ ，在富文本框内ctrl+v（或右键选择“粘贴”）,浏览器无反应。

符合预期

> 2、选择word里面的图片ctrl + c，富文本框内ctrl+v，浏览器无反应。

符合预期

> 3、在百度上找张图片右键选择‘复制‘，富文本框内粘贴成功

符合预期

**Comment by wangfupeng1988** [comment]
浏览器中的粘贴，本来就不支持 word 等其他软件的复制内容

**Comment by tanxuewei** [comment]
粘贴过来的图片可以直接过滤过么，有没有简单的做法

**Comment by vvLu** [comment]
遇到了同样的问题，不能截图粘贴

**Comment by Wchaos** [comment]
1、只复制文字：获取到图片，只执行文字复制
2、只复制图片：没有获取到文字，只执行图片复制
3、既有文字又有图片：获取文字，执行文字复制；获取图片失败（有文字会忽略图片）
所以这个canDo函数有完全美没有存在的必要啊，这个canDo函数的存在导致图片复制永远都不会执行
