### ISSUE TITLE
Java上传代码例子里返回的永远都是最后一张图的地址

### ISSUE THREAD

**Issue by liygheart** [wangfupeng1988/wangEditor#118]
![image](https://cloud.githubusercontent.com/assets/6915570/12541612/42e59cdc-c354-11e5-895a-cd16e73f7c37.png)

上图中在取图片的时候是使用list 便利保存图片到服务器里的，结果到最先out.write()的时候是在循环结束的时候，也就是说返回到客户端的永远都是最后一张图片的地址

个人建议：
1. 这地方要不就只给传一张图片（不支持传多张图片）
2. 返回的数据也使用集合返回， 然后在前台页面里接受处理显示在textarea里

**Comment by wangfupeng1988** [comment]
哦。。。这个代码是群友提供的，用来给大家作为参考的，那位群友可能没想到那么复杂。在 2.0 的文档中，我会去改正这个问题。感谢反馈！

**Comment by liygheart** [comment]
好的，我测试过了，用list装起来，然后out.write(list.toString())就可以了，
如果只是一张图片的话，直接返回图片的访问地址，不要放在list里，然后toString()了（这样会在地址两边多出[]）
