### ISSUE TITLE
3.0.15  tab和text分开时。  tab上斜体 点击激活状态没有样式

### ISSUE THREAD

**Issue by zhuchaoyang** [wangfupeng1988/wangEditor#1181]

**Comment by zhuchaoyang** [comment]
是在 文本中斜体 i元素标签的  font-style: italic; 被禁掉的情况下 会发生。

**Comment by wangfupeng1988** [comment]
> ab上斜体 点击激活状态没有样式

没明白啥意思。。。

**Comment by zhuchaoyang** [comment]
比如说我项目里基础样式 有 i， em {font-style: normal;}
你的编辑器没有重定义 i元素标签的斜体 来覆盖掉我的样式。
这样子编辑器就会出现 斜体无效，bar上的斜体小图标也没有激活样式的情况。还得手动加上如：    .w-e-text i{font-style: italic;}  才可以

**Comment by wangfupeng1988** [comment]
像这种 css 冲突的问题，你先自己手动加一下吧，好在问题比较简单
