### ISSUE TITLE
关于编号#1179问题的追问

### ISSUE THREAD

**Issue by paocaijun** [wangfupeng1988/wangEditor#1183]
这是之前问题的截图![image](https://user-images.githubusercontent.com/24297271/33490187-3f269378-d6f1-11e7-8c9b-ce9eb7060cef.png)

想问下是出于什么考虑不支持 word 等软件的复制图片的粘贴。因为1、注释掉源码3521-3523行，执行  ‘   选择word里面的图片ctrl + c，富文本框内ctrl+v   ’，是能成功的。（图为源码3521-3523行）
![image](https://user-images.githubusercontent.com/24297271/33490733-0f9d806a-d6f3-11e7-9e0b-9ec0d26e2ff2.png)
2、如果不支持此种情况的粘贴，那么源码3513-3546的代码是处理哪种情况的图片粘贴？（如图是部分代码截图）
![image](https://user-images.githubusercontent.com/24297271/33490498-5db2e1ce-d6f2-11e7-9f14-a804a98a4915.png)

希望您解释下，不胜感激。

**Comment by wangfupeng1988** [comment]
不是不支持，是实现不了啊。。。

**Comment by paocaijun** [comment]
我和我一个同事试过。1中的情况是成立的，我的理解是注释掉那段代码就能实现word中图片的粘贴。如果我错误解读了你的意思，麻烦您耐心解释下

**Comment by wangfupeng1988** [comment]
> 我的理解是注释掉那段代码就能实现word中图片的粘贴

你说的是`canDo()`这个方法吧？这个是为了解决在 windows 下 chrome 粘贴图片，会出现粘贴两次的情况。并不是为了屏蔽 word 中的图片。

**Comment by paocaijun** [comment]
为了满足在编辑框内粘贴任何地方复制过来的图片的需求，我们采取的方式是，把源码拷过来放在项目下，注释掉"粘贴图片"方法里面的cando（）。再引进来用，（以前我们是直接npm，然后引进项目的）。没发现chrome粘贴两次的问题
