### ISSUE TITLE
移动端使用textarea 在js中写入var $text1 = $('#text1')，会式编辑器无法使用

### ISSUE THREAD

**Issue by feifeipang** [wangfupeng1988/wangEditor#1184]
移动端使用textarea 在js中写入var $text1 = $('#text1')，会式编辑器无法使用；编辑器的样式全部丢失！我的网页是在微信中打开的,是否有冲突。。。。

**Comment by wangfupeng1988** [comment]
首先，编辑器目前不支持移动端编辑内容，但是编辑的内容可以放在移动端展示。

其次:

> 移动端使用textarea 在js中写入var $text1 = $('#text1')

不明白你说的啥意思

**Comment by feifeipang** [comment]
这代码中！var $text1 = $('#text1');加上这句，编辑器就不能使用了！

**Comment by feifeipang** [comment]
在pc端模拟器中，可以使用！

**Comment by wangfupeng1988** [comment]
js 没有报错？不可能莫名其妙不能用了吧

**Comment by feifeipang** [comment]
我是在微信公众号里的页面里使用该项目的！

**Comment by feifeipang** [comment]
经过微信开发者工具的查看！终于找到原因！谢谢解答！打打辛苦了！！！
