### ISSUE TITLE
【图片上传问题】，已成功通过服务器上传图片，但DEBUG显示下载该链接失败

### ISSUE THREAD

**Issue by xu509** [wangfupeng1988/wangEditor#1185]
如题，已经成功通过服务器上传图片，能够直接从浏览器打开图片地址，但是编辑器显示下载该链接失败。

`Error: wangEditor: wangEditor: 插入图片出错，图片链接是 "https://image.artplanet.cn/article/fad0ee06-14ae-46bf-91d8-edeb730f87c7.jpg_img02"，下载该链接失败`

**Comment by wangfupeng1988** [comment]
这个问题复现的很频繁吗？

**Comment by miyga** [comment]
这个问题可能是接口返回数据造成的。
官方文档是这样演示的
`{
    // errno 即错误代码，0 表示没有错误。
    //       如果有错误，errno != 0，可通过下文中的监听函数 fail 拿到该错误码进行自定义处理
    errno: 0,

    // data 是一个数组，返回若干图片的线上地址
    data: [
        '图片1地址',
        '图片2地址',
        '……'
    ]
}
`实际上应该是这种格式：
`{
    “errno”: 0,
    “data”: [
        “图片1地址”,
        “图片2地址”,
        “……”
    ]
}`
注意后台将json字符串全部用“\""这种方式转成双引号即可。

**Comment by wangfupeng1988** [comment]
OK，我去改文档
