### ISSUE TITLE
编辑器上传到七牛图片情况下，选中已上传的图片，无法更改图片大小

### ISSUE THREAD

**Issue by Baiang** [wangfupeng1988/wangEditor#1187]
wangEditor v 3.0.15：编辑器配置图片上传到七牛情况下，选中已上传图片，无法更改图片大小，还是弹出上传图片框。

**Comment by wangfupeng1988** [comment]
什么系统，什么浏览器？

**Comment by Baiang** [comment]
系统：win10，浏览器：chrome、火狐、IE11
只有上传七牛才这样、添加网络图片正常。上传服务器还未测试。IE上传成功，但图片不显示。
官网上传图片、添加网络图片正常

**Comment by wangfupeng1988** [comment]
这个问题我这边还不好整环境，毕竟配置上传七牛也挺麻烦的。你上传到七牛并且显示了图片之后，编辑器与的 html 结构是啥样子的，把`.w-e-text`的`innerHTML`给我发一下呗

**Comment by Baiang** [comment]
代码结构：
<div contenteditable="true" style="width: 100%; height: 100%; position: relative;" class="w-e-text" id="text-elem39571185846117873"><p>啊实打实大啊实打实</p><p><br></p><p><br></p><p style="text-align: center;"><img src="http://rs.dafangya.com/1513059149823_oPHmPxTl" style="max-width:100%;"><br></p></div>

**Comment by kennygp** [comment]
问题同上，求解决方法。。我浏览器是谷歌浏览器。要是不好整环境可以加我QQ136932853，远程给你看看呀。

**Comment by wangfupeng1988** [comment]
@Baiang 按理说代码结构这样不会出现你数的问题，我修复的时候用 window 看下吧。最近业务忙，更新慢，请体谅。

**Comment by wangfupeng1988** [comment]
@kennygp QQ 加不上，有验证问题

**Comment by kennygp** [comment]
@wangfupeng1988 额。那个验证随便填的

**Comment by javed119** [comment]
请问一下这个问题解决了吗？

**Comment by 3kqing** [comment]
我的也无法更改图片大小

**Comment by wangfupeng1988** [comment]
我近期升级，加一个外露的修改大小的按钮吧

**Comment by 3kqing** [comment]
多谢，支持支持

**Comment by 619569891** [comment]
我上传后的图片也无法更改大小，怎么才能弄成鼠标拖动大小？

**Comment by wangfupeng1988** [comment]
@619569891 目前还不支持。可点击图片，然后点击“图片”菜单，修改图片大小。
