### ISSUE TITLE
为什么我下载下来之后发现只能上传网络图片，而不能上传本地图片啊？

### ISSUE THREAD

**Issue by darrenliuwei** [wangfupeng1988/wangEditor#1188]
![1](https://user-images.githubusercontent.com/10508248/33600311-d46a2856-d9e3-11e7-839e-b049072c5a2f.png)

![2](https://user-images.githubusercontent.com/10508248/33600431-2f3e8380-d9e4-11e7-8108-09a05d42a490.png)

## 宣传首页上显示可以上传本地图片，为什么我下载下来之后就不行了呢？

![3](https://user-images.githubusercontent.com/10508248/33600520-6adbde42-d9e4-11e7-96e0-7498038ded75.png)

## .....\Downloads\wangEditor-3.0.15\release   我是直接在这个目录下新建了一个 test.html 文件进行测试的

![4](https://user-images.githubusercontent.com/10508248/33600640-c70e8a02-d9e4-11e7-821a-2e8a68a7ea75.png)
## 这个是 test.html 文件的代码

# 希望维护者能帮忙解答一下，谢谢啦

**Comment by wangfupeng1988** [comment]
看文档

**Comment by heweixiang** [comment]
把地址配置好,然后创建就好了
![image](https://user-images.githubusercontent.com/49872030/125402890-7c762480-e3e7-11eb-93bb-9f888617bd5c.png)
