### ISSUE TITLE
没有使用location地图菜单的情况下，仍然提示地图不能同时使用。

### ISSUE THREAD

**Issue by firesh** [wangfupeng1988/wangEditor#119]
wangEditor提示: 目前不支持在一个页面多个编辑器上同时使用地图，可通过自定义菜单配置去掉地图菜单$.each.E.(anonymous function) @ wangEditor.js:2301(anonymous function) @ wangEditor.js:4707(anonymous function) @ wangEditor.js:2802m.extend.each @ jquery-1.11.3.min.js:2E.fn.addMenus @ wangEditor.js:2801E.fn.create @ wangEditor.js:860(anonymous function) @ detail.js:219
wangEditor.js:2301 wangEditor提示: 目前不支持在一个页面多个编辑器上同时使用地图，可通过自定义菜单配置去掉地图菜单

**Comment by wangfupeng1988** [comment]
好的，我今晚验证一下吧，白天比较忙。验证完，在这里回复。

**Comment by wangfupeng1988** [comment]
你好，实在不好意思，到现在才回复这个问题。

我看了，确实存在这个问题，不过还好不复杂。我已经修复了，今晚就可以更新上，你明天注意看看 https://github.com/wangfupeng1988/wangEditor/releases 的更新记录
