### ISSUE TITLE
关于图片上传到服务器成功但是返回错误结果的问题

### ISSUE THREAD

**Issue by LiuZhEn1120** [wangfupeng1988/wangEditor#1191]
![image](https://user-images.githubusercontent.com/19721912/33652190-6b893e10-daa3-11e7-9065-d4fcc9b6a111.png)
使用图片上传功能上传到服务器，请请发送成功并有结果返回，但是组件报错！
![image](https://user-images.githubusercontent.com/19721912/33652241-a24db67e-daa3-11e7-8f41-0b8f4d48b482.png)
请问下是什么问题

**Comment by wangfupeng1988** [comment]
请按照文档规定的格式返回数据。
