### ISSUE TITLE
customConfig是不是改成了config

### ISSUE THREAD

**Issue by liunewshine** [wangfupeng1988/wangEditor#1194]
editor.customConfig.uploadImgServer = '/upload'无效
editor.config.uploadImgServer = '/upload'可以

**Comment by liunewshine** [comment]
"wangeditor": "^3.0.15"

**Comment by wangfupeng1988** [comment]
按文档来

**Comment by liunewshine** [comment]
按照文档来无效.只有用config才回显示上传按钮

**Comment by wangfupeng1988** [comment]
不可能的，你看官网 http://www.wangeditor.com/index.js 的配置，也是用的`customConfig `

**Comment by misuqian** [comment]
create()创建之前是customConfig来配置
create()之后可以修改config对象来动态修改
