### ISSUE TITLE
字号样式需要自己用css控制的最佳实践 

### ISSUE THREAD

**Issue by MonsterL** [wangfupeng1988/wangEditor#1196]
发现v3版本取消字体设置，推荐大家用样式来设置字体，想问下实践方式就是重置 H1~H5的样式么？组件显示以及生成的标签还是H对吧？

**Comment by wangfupeng1988** [comment]
编辑器生成的是纯 HTML 代码，尽量不带有任何 css 样式。至于显示的时候，自己如何定义，那就是自己控制了。
