### ISSUE TITLE
上传图片不稳定，还时能显示在富文本里，有时显示不了

### ISSUE THREAD

**Issue by hemuqiu** [wangfupeng1988/wangEditor#1197]
![image](https://user-images.githubusercontent.com/20644383/33747907-8d1084b8-dc00-11e7-9b79-826a962a8401.png)
能监听到上传成功
![image](https://user-images.githubusercontent.com/20644383/33747920-a03c482e-dc00-11e7-9fdd-b55cfe129e6a.png)
但有时候能监听到插入的DOM，有时候监听不到DOM变化了。

**Comment by wangfupeng1988** [comment]
返回数据正常吧？
