### ISSUE TITLE
在vue 版本中 在QT 内核 下的浏览器中获取文本不全或者获取不到

### ISSUE THREAD

**Issue by jiaopianjun** [wangfupeng1988/wangEditor#1198]
在vue 版本中 在QT 内核 下的浏览器中获取文本不全或者获取不到

**Comment by wangfupeng1988** [comment]
> 浏览器中获取文本不全或者获取不到

具体哪个 API 有问题？

**Comment by jiaopianjun** [comment]
editor.customConfig.onchange = (html) => {
        this.editorContent = html
      }

**Comment by wangfupeng1988** [comment]
在你的环境下运行 https://www.kancloud.cn/wangfupeng/wangeditor3/335789 这个 demo 看是否有同样的问题？

**Comment by jiaopianjun** [comment]
一样的问题  还是获取不到

**Comment by jiaopianjun** [comment]
还有在微软的  edge 下   也会有   获取输入内容 不全的现象，但是  只是偶尔

**Comment by yandw** [comment]
追看了你的源码，在Editor.vue中
`      mounted() {
        var editor = new E('#editorElem')
        editor.customConfig.onchange = html => {
          this.editorContent = html
        }
        editor.create()
      }
`
如果是内嵌浏览器以及Edge, 最后的一次的 onchange 没有被触发。

**Comment by jiaopianjun** [comment]
是的  ，已经找到原因了   谢谢   利用了其他写法来获取
