### ISSUE TITLE
chrome浏览器中的一个小兼容问题求解决

### ISSUE THREAD

**Issue by huitouke120** [wangfupeng1988/wangEditor#1199]
1 初始化之后，赋值`editor.txt.html('这里是普通文本，不是html格式')`。
2 用chrome浏览器打开，此时光标默认会在文本的下一行闪烁。
3 将鼠标移到第一行最后一个字后面，点击鼠标左键，光标在第一行最后一个字后面闪烁
4 点击enter，光标会迅速跳到下一行并又返回到第一行最后一个字后面。

注意：1 初始化内容时，是普通文本，不是带有html标签内容
           2 chrome有此现象，但是firefox并未有此现象。

**Comment by wangfupeng1988** [comment]
> 1 初始化内容时，是普通文本，不是带有html标签内容

这本身就不符合使用要求，应该是 `editor.txt.html('<p>xxxx</p>')`
