### ISSUE TITLE
jQuery版本问题

### ISSUE THREAD

**Issue by huangjinjin914** [wangfupeng1988/wangEditor#12]
为什么我使用1.11.1版本不能用，用你的1.10.2就可以。请作者看看，谢谢

**Comment by wangfupeng1988** [comment]
不能用表现为什么？有哪些错误提示？

**Comment by huangjinjin914** [comment]
就是直接说到不到wangEditor这个函数，而且我用的是你网站上的demo
另外，如果加上这个用户体验更好一点点
$(".wangEditor-mask").click(function(){$(".wangEditor-modal-header-close").click();$(".wangEditor-textarea").focus()})

**Comment by wangfupeng1988** [comment]
可以把你的demo打包发到qq群的共享文件，我来看看代码。

**Comment by wangfupeng1988** [comment]
另外，你注意jquery和wangEditor两个js的引用顺序，不能颠倒。当然，这是个低级问题，只是提醒一下

**Comment by huangjinjin914** [comment]
是我的错。。晕。你的代码没问题

**Comment by huangjinjin914** [comment]
谢谢作者热情回答：）

**Comment by wangfupeng1988** [comment]
你这么一说，我就猜出来是一个低级错误。不过没关系，人都这样，低级错误往往自己发现不了
