### ISSUE TITLE
关于编辑框的高度自适应？

### ISSUE THREAD

**Issue by hyf101070** [wangfupeng1988/wangEditor#120]
您好，我想问下能不能实现编辑框高度随浏览器窗口大小改变自动适应，我试过将editor的高度设为100%，但是一直不行
![image](https://cloud.githubusercontent.com/assets/6482094/12844692/eb2059ce-cc3b-11e5-965d-e0ca87e2c32f.png)
只能这么高

**Comment by wangfupeng1988** [comment]
目前不支持自适应高度，对于高度的配置只能是：http://www.kancloud.cn/wangfupeng/wangeditor2/113966

-----

不过，你可以自己试着写一个插件，来让编辑器自适应高度啊 
http://www.kancloud.cn/wangfupeng/wangeditor2/113997

**Comment by hyf101070** [comment]
@wangfupeng1988 好的，我试试看
