### ISSUE TITLE
editor.txt.text()的问题

### ISSUE THREAD

**Issue by codinglilong** [wangfupeng1988/wangEditor#1201]
`editor.txt.text()`获取的并不是纯文本内容还有html实体(`&.nbsp.;`)这种内容。比如我想判断他是否输入了内容感觉不好判断呀，比如他敲了个空格还是可以提交，因为拿出来的内容是 `&.nbsp;`这就判断不了？能否优化一下这个方法？

**Comment by wangfupeng1988** [comment]
这个还是自己搞吧，获取了`editor.txt.text()`在加一层自己的过滤逻辑。

这种特殊需求放在`editor.txt.text()`统一处理不合适，并不能确定每个用户都不需要`&nbsp;`
