### ISSUE TITLE
按照文档配置onchange事件，不触发

### ISSUE THREAD

**Issue by yyh1102** [wangfupeng1988/wangEditor#1203]
version:v3.0.15
按照官方文档配置editor的onchange事件，页面都渲染成功了，但事件不触发。
代码如下：
html:
![image](https://user-images.githubusercontent.com/10328169/33871140-2a92a916-df4c-11e7-8337-3f73e2371889.png)

js:
![image](https://user-images.githubusercontent.com/10328169/33871135-23a16b92-df4c-11e7-8a73-67d29ac31370.png)

**Comment by wangfupeng1988** [comment]
把`editor.create()`放在后面，不要一开始就 create

**Comment by yyh1102** [comment]
谢谢，已解决。
