### ISSUE TITLE
选区问题

### ISSUE THREAD

**Issue by WangAnQinga** [wangfupeng1988/wangEditor#1204]
选中文字之后，点击droplist类型的按钮，比如给文字添加颜色，点击颜色之后被选中的文字选区丢失了，导致添加颜色失败

**Comment by wangfupeng1988** [comment]
什么系统，什么浏览器？官网能否复现这个 bug ？

**Comment by WangAnQinga** [comment]
@wangfupeng1988   win10  chrome  官网多试几次可以复原

**Comment by WangAnQinga** [comment]
@wangfupeng1988 把手势放在图标中间偏上的位置，可以完美复原

**Comment by WangAnQinga** [comment]
@wangfupeng1988  点击事件的问题，默认点击事件绑定在i标签上面，cursor：pointer放在i标签外面的li标签，可能点击到了外层的li标签，却没有点击到里面i标签，没有触发事件，导致选区丢失。

**Comment by wangfupeng1988** [comment]
> 可能点击到了外层的li标签，却没有点击到里面i标签，没有触发事件，导致选区丢失

应该是这个原因，我抽时间看一下。

近期业余时间有其他事情，升级较慢，还望体谅。

**Comment by wangfupeng1988** [comment]
v3.0.16 修复，今晚发布
