### ISSUE TITLE
提两个火狐下的实在bug

### ISSUE THREAD

**Issue by brosegu** [wangfupeng1988/wangEditor#1206]
火狐下（官网demo实测也存在）
1，使用键盘Tab按键切入编辑器让编辑器聚焦直接输入数字或者字母，会出现输入内容不在标签内的情况。回显数据时，导致页面报错，编辑器初始化错误
2，初始数据使用Ctrl+A全选之后直接输入数字或者字母，会出现输入内容不在标签内的情况。回显数据时，导致页面报错，编辑器初始化错误

**Comment by wangfupeng1988** [comment]
这个问题确实存在，我抽时间改一下。

近期业余有其他事情，升级进度有点慢，还望体谅。

**Comment by longFeiLi** [comment]
win下火狐  
1.选择一个文字改变背景颜色会先改变文本颜色，然后点击编辑器才会改变背景色。
测试网站： http://www.wangeditor.com/

**Comment by wangfupeng1988** [comment]
很抱歉，个人精力原因， Firefox 的兼容性问题暂时先不处理 —— Firefox 兼容性问题太多，而且处理难度都挺大。
