### ISSUE TITLE
请问支持上传视频么

### ISSUE THREAD

**Issue by wuyanghou** [wangfupeng1988/wangEditor#1207]
你好，目前在项目中需要上传视频，请问支持么，看了一下，好像只支持插入

**Comment by wangfupeng1988** [comment]
暂时不支持视频上传。

**Comment by antaintan** [comment]
你好, 请问呆以支持视频插入URL吗, 像图片一样

**Comment by wxw1314** [comment]
是不是可以暴露接口给想修改功能的开发者增加方法呢

**Comment by momokanni** [comment]
没有的功能可以自己添加，毕竟是开源的，源码都有。各位都有贡献代码的权利，别总是拿来主义
