### ISSUE TITLE
选择图片完毕的事件

### ISSUE THREAD

**Issue by niannianliu** [wangfupeng1988/wangEditor#1208]
想在选择图片完毕时设置自定义参数，看源码选择图片完成触发的是onchange事件，onchange事件中能判断出是图片事件吗

**Comment by niannianliu** [comment]
在onchange中设置参数，对于其他事件触发的忽略，只想在图片选择完毕时设置以下参数
editor.customConfig.uploadImgParams = {
    					    uuid: $('#uuid').val()
    					}

**Comment by wangfupeng1988** [comment]
`editor.customConfig.uploadImgParams`的设置只能在`editor.create()`之前，在其他地方设置无效。
