### ISSUE TITLE
工具栏的一些问题

### ISSUE THREAD

**Issue by hyf101070** [wangfupeng1988/wangEditor#121]
![image](https://cloud.githubusercontent.com/assets/6482094/12844723/266299d4-cc3c-11e5-8662-086b37ac6204.png)
menu-tip的宽度有些问题
![image](https://cloud.githubusercontent.com/assets/6482094/12844736/3982bb98-cc3c-11e5-8413-80a78b789715.png)
用的是2.0.3版本

**Comment by RangerWolf** [comment]
我这边遇到跟你类似的问题~  
我的场景是在bootstrap modal 显示之前就调用editor.create() 这时候就会这样~  如果是modal显示出来之后再editor.create() 就好了~  类似下面这样：  
`	$("#updateRecordModal").modal({
		keyboard: true,		// ESC 关闭窗体
		backdrop: false		// 点击窗体其他地方无效
	});
	
	// 初始化富文本编辑器
	var editor = new wangEditor('acmtcontent');
	editor.create();`

**Comment by hyf101070** [comment]
@RangerWolf 谢谢你的回答，我刚刚试了下，成功解决了，我的div事先是隐藏的，然后调用editor.create()，div显示的时候就出现了那样的问题，改成在div显示后再调用editor.create();就没问题了

**Comment by wangfupeng1988** [comment]
是的，编辑器的一些位置、大小、尺寸的计算，会依赖于父容器的位置和大小等参数。因此，父容器不显示，计算就会有问题。
