### ISSUE TITLE
粗体、斜体、下划线等功能生成的HTML存在问题

### ISSUE THREAD

**Issue by LastQuarterMoon** [wangfupeng1988/wangEditor#1212]
我在编辑器onchange的时候打印了三项：
1.HTML
2.HTML的长度
3.分解后的HTML
如图，编辑器不输入内容直接点击蓝色框框中的按钮，打印内容见红色框框，
第一行HTML，肉眼可见为11位，但是打印出的长度是12位，分解后发现第四位是空，但缺独占一位，
不明白这个东西是什么，

![qq 20171215165249](https://user-images.githubusercontent.com/22828247/34034313-e6967bf6-e1b8-11e7-9d19-56fda12173c4.png)

多点击几次之后，在我的项目中，存入oracle取出来显示就是‘？’。各式各样的‘？’

![image](https://user-images.githubusercontent.com/22828247/34034708-84cc6d84-e1ba-11e7-9200-d114a3170f65.png)

代码就是最基础的编辑器加上onchange事件就行

```js
var editor = new window.wangEditor('#editor');

editor.customConfig.onchange = function (html) {
	console.log('输出HTML：' + html);
    console.log('HTML长度：' + html.length);
    console.log('HTML分解：',html.split(''));
}

editor.create();
```
最后，希望作者尽快处理，我项目赶着上线，多谢了！

**Comment by wangfupeng1988** [comment]
> 分解后发现第四位是空，但缺独占一位，不明白这个东西是什么，

因为你未选中任何内容的时候点击“加粗”或者“斜体”等按钮，就得需要一个空的占位符，否则无法实现“先点击加粗，后输入加粗内容”这一个功能。

> 在我的项目中，存入oracle取出来显示就是‘？’。各式各样的‘？’

那你看一下存入数据库之前，你从前端获取的内容是什么？获取的内容中有 “？” 吗？

**Comment by LastQuarterMoon** [comment]
@wangfupeng1988 我在后台打断点看了下，存入之前跟上面console.log打印出来的一样，不是‘？’而是空的占位符

**Comment by wangfupeng1988** [comment]
那就自己手动替换一下吧，这个空的占位符是`&#8203;`

**Comment by LastQuarterMoon** [comment]
@wangfupeng1988 好的，非常感谢

**Comment by LastQuarterMoon** [comment]
@wangfupeng1988 这个问题我在前端通过charCodeAt方法遍历html的Unicode编码，从而删掉了8023，但我建议作者能加到源码中处理下html。

**Comment by wangfupeng1988** [comment]
嗯嗯，我记录下，下次升级处理一下

**Comment by wangfupeng1988** [comment]
v3.0.16 修复，今晚发布。

已经在`editor.txt.html()`和`editor.txt.text()`中对`&#8203;`做了替换。
