### ISSUE TITLE
提一个图片大小计算的小问题

### ISSUE THREAD

**Issue by LastQuarterMoon** [wangfupeng1988/wangEditor#1215]
最新版本源码762行
// 默认上传图片 max size: 5M
`uploadImgMaxSize: 5 * 1024 * 1024,`

然后4074,4075行
`var maxSize = config.uploadImgMaxSize;`
`var maxSizeM = maxSize / 1000 / 1000;`

这样子默认提示会变成如图所示
![image](https://user-images.githubusercontent.com/22828247/34099227-d9e37af4-e419-11e7-9def-19e8369dd524.png)

**Comment by wangfupeng1988** [comment]
那么，具体的问题是啥？

**Comment by LastQuarterMoon** [comment]
不应该是5而不是5.24288么

**Comment by wangfupeng1988** [comment]
就是`maxSize / 1000 / 1000`要改成`maxSize / 1024 / 1024`呗

**Comment by LastQuarterMoon** [comment]
@wangfupeng1988 是的是的。

**Comment by wangfupeng1988** [comment]
我抽空改一下，近期业余时间有其他事情，更新有点慢，请体谅

**Comment by LastQuarterMoon** [comment]
没事小问题，你记录下就行

**Comment by wangfupeng1988** [comment]
嗯嗯，感谢你的认真反馈！

**Comment by wangfupeng1988** [comment]
v3.0.16 修复，今晚发布
