### ISSUE TITLE
居中“无序／有序列表“，列表数字和文字内容分离

### ISSUE THREAD

**Issue by Baiang** [wangfupeng1988/wangEditor#1217]
居中“无序／有序列表“，列表数字和文字内容分离
![tim 20171219145428](https://user-images.githubusercontent.com/8638857/34144856-721cedd2-e4ce-11e7-89a2-67534c2014fc.png)

**Comment by wangfupeng1988** [comment]
这是 html 本身的特性，并没有写任何 css 做这个干预。
