### ISSUE TITLE
我想给上传的图片增加一个 class 属性, 要怎么做呢?

### ISSUE THREAD

**Issue by weir008** [wangfupeng1988/wangEditor#1218]
如果编辑器内容是在浏览器显示, 直接通过 CSS 控制样式就行了 .
但最近有个需求要在微信小程序里面显示编辑器的内容, 需要给上传的图片添加一个class属性, 才能在小程序里面做处理 ,请问有办法实现吗?

**Comment by wangfupeng1988** [comment]
先自己修改 https://github.com/wangfupeng1988/wangEditor/blob/master/release/wangEditor.js#L4036 这里的代码吧。
