### ISSUE TITLE
什么时候富文本编辑器可以支持work和excel上面的样式和效果？

### ISSUE THREAD

**Issue by pshaoyi** [wangfupeng1988/wangEditor#1220]
什么时候富文本编辑器可以支持work和excel上面的样式和效果？

**Comment by wangfupeng1988** [comment]
永远都不会支持，我做的是一个简洁的 web 端的富文本编辑器，不是重造一个 word + excel 。

如果你有这方面需求，干脆直接去用 office 的 web 版本
