### ISSUE TITLE
无法同时上传很多图片

### ISSUE THREAD

**Issue by songyuanxiao** [wangfupeng1988/wangEditor#1221]
多张图片同时上传，点击提交会页面崩溃（具体是会导致重新加载页面，有时直接退出）

**Comment by wangfupeng1988** [comment]
什么系统？什么浏览器？同时上传了多少张图片？奔溃前上传请求的状态是啥？服务器是否接收到了数据。

你什么信息都不提供给我，让我猜问题吗？
