### ISSUE TITLE
请教下作者大大editor.customConfig.pasteTextHandle这个方法为啥会执行两次的？

### ISSUE THREAD

**Issue by wangl1989** [wangfupeng1988/wangEditor#1222]
我每次复制粘贴的时候 发现这个方法执行了两次 导致了我粘贴的内容的样式没有了  请教下有没有什么解决的办法？

**Comment by wangfupeng1988** [comment]
恩 我复现这个问题了。你先自己在 pasteTextHandle 中处理一下（如 500ms 只允许执行一次，这种），等我升级修复这个问题，到时候会在这里回复你。

**Comment by irenexixi** [comment]
@wangfupeng1988  这个问题解决了吗。两次的content不一样

**Comment by wangfupeng1988** [comment]
别急哈，我业余忙的事情还没弄完，完事儿就更新，你的问题我早就记录下了。

估计得忙到过春节。

**Comment by wangfupeng1988** [comment]
v3.0.16 已经修复
