### ISSUE TITLE
1.貌似在设置居中后,在插入的图片前按 enter 键bug

### ISSUE THREAD

**Issue by ghostFlyTiger** [wangfupeng1988/wangEditor#1225]
在图片前按enter键后,图片会消失,后面发现,在按enter前,在前面加个字符,然后在此字符前enter后删除这个字符.这样子才能避免图片消失.

**Comment by wangfupeng1988** [comment]
我记得以前修复过这个问题。

1. 你是否用的最新的版本？
2. 官网是否能复现你这个问题？
3. 你用的是什么系统什么浏览器？

**Comment by ghostFlyTiger** [comment]
是最新的,在官网下的. win7,google.官网还没试.我试看看.谢谢!!!

**Comment by ghostFlyTiger** [comment]
我可能找到问题了.是有css 冲突了.已经解决.谢谢解答!
