### ISSUE TITLE
怎么插入内容?

### ISSUE THREAD

**Issue by ghostFlyTiger** [wangfupeng1988/wangEditor#1226]
可以追加内容,怎么实现插入内容呢?在当前水标处插入内容.

**Comment by iamcharieli2016** [comment]
editor.cmd.do('insertHtml', '<img src="' + sourceLink + '" style="max-width:100%;"/>')
这样可以插入

**Comment by wangfupeng1988** [comment]
楼上正解。

文档中有相关的 API 描述，可以去找一下。
