### ISSUE TITLE
3.0版本不能设置字体大小很不方便呀，编辑器这个是基本的功能吧！

### ISSUE THREAD

**Issue by iamcharieli2016** [wangfupeng1988/wangEditor#1227]

**Comment by xusheng1987** [comment]
我也好奇为什么没这个基本的功能

**Comment by moonscu** [comment]
这个功能确实很需要啊，要不是我菜，自己就修改了，哈哈~~
希望作者完善一下，感谢感谢！！

**Comment by wangfupeng1988** [comment]
可以找一下之前 closed 掉的问题，字体和字号都不会加到默认功能中，如果需要自己去二次开发。

原因只有一个：我希望编辑器输出的尽量是纯净的 html 代码，尽量不带有任何 css 或者 style 。
