### ISSUE TITLE
为什么不能直接编辑源码

### ISSUE THREAD

**Issue by CodingJabber** [wangfupeng1988/wangEditor#1229]
推荐同事用了一段时间后，产品要求能编辑源码，然后来找我，我才发现竟然连编辑源码都没有，受不了啊

**Comment by hold-baby** [comment]
构建好的源码在release目录下 
推荐使用script引入
如果是npm引入 你需要找到本地的包修改构建

**Comment by wangfupeng1988** [comment]
编辑源码完全可以自己开发。不要总是做伸手党。

**Comment by CodingJabber** [comment]
换了simditor了

**Comment by boySang** [comment]
看来众口难调啊，作者不容易
