### ISSUE TITLE
点击其他区域如何隐藏上传面板？

### ISSUE THREAD

**Issue by wenbo0820** [wangfupeng1988/wangEditor#123]
在官网的demo中没有这个问题，但是下载后测试时发现点击了上传图片菜单弹出面板后，点击文本区域无法隐藏上传面板。

**Comment by wangfupeng1988** [comment]
参考 [https://github.com/wangfupeng1988/wangEditor#3-本地运行demo](https://github.com/wangfupeng1988/wangEditor#3-本地运行demo) ，然后看看本地运行demo行不行？

不行再回复我。

**Comment by wenbo0820** [comment]
本地运行demo没出现该现象，
测试项目依旧：
![12](https://cloud.githubusercontent.com/assets/15955439/13100834/09a1db5e-d57c-11e5-9658-4e8936f18bec.png)

**Comment by wangfupeng1988** [comment]
我怀疑是你的项目环境影响导致的，这就得具体问题具体分析了。
你可以在项目环境中一步一步的试着去掉一些代码，来测试到底是哪一块影响了这个问题。

ps：我在日常工作中遇到问题，也经常用这种排除法

**Comment by wenbo0820** [comment]
刚删除了重新解压建立测试项目，突然这个问题消失了,囧rz..

与这个问题无关，有一个比较别扭的地方就是，对字体样式进行更改的时候必须得先选中字体，后续的加粗。斜体颜色等操作才有效，假如我想直接上来就进行 斜体字编辑，但是点击斜体字然后输入的文字还是正常文本
