### ISSUE TITLE
从word直接选择图片加文字复制到编辑框，图片不能上传到服务器

### ISSUE THREAD

**Issue by fankq** [wangfupeng1988/wangEditor#1230]
从word直接选择图片加文字ctrl+c，在文本编辑框ctrl+v之后，插入的是word中图片的本地路径，没有触发图片上传方法：如下所示
`<img src="file:///C:\Users\fankq\AppData\Local\Temp\msohtmlclip1\01\clip_image002.jpg" v:shapes="图片_x0020_1" width="553" height="299">`
而且不能显示；
前辈，您看这个是我哪里没有配置好吗？

**Comment by wangfupeng1988** [comment]
从 word 赋值的内容，图片本来就无法直接上传。你看下`img`的`src`，明显是一个本地文件路径，而 JS是无法操作本地文件的。

**Comment by xixihappy** [comment]
你好， 请问能支持Word中的图片上传吗？因为有时候Word中的图片太多

**Comment by yishu-git** [comment]
请问现在这个问题解决了吗？

**Comment by wangfupeng1988** [comment]
@yishu-git  目前尚不支持，可以使用 customPaste 自定义 https://www.wangeditor.com/v5/editor-config.html#custompaste
