### ISSUE TITLE
编辑器高度问题【关于原问题#969的提问】

### ISSUE THREAD

**Issue by lijun1243939149** [wangfupeng1988/wangEditor#1232]
[原问题#969链接](https://github.com/wangfupeng1988/wangEditor/issues/969)

运行过demo中的 `example/demo/test-sperate.html`，但是可编辑区域，仍然不是父级div的高度的100%～
我的是mac系统，chrome (Version 63.0.3239.84 )浏览器。。
【详见如下截图】
![wechatimg1811](https://user-images.githubusercontent.com/13789967/34338033-7f645cfc-e99f-11e7-871b-189641bf8f29.jpeg)

**Comment by wangfupeng1988** [comment]
恩，我发现这个问题了，你先手动改一下`$('.w-e-text')`的元素高度吧，我再升级的时候看看修复一下这个问题
