### ISSUE TITLE
使用引用按钮后无法在引用下方继续输入文字

### ISSUE THREAD

**Issue by jjiale** [wangfupeng1988/wangEditor#1234]
你好：
    使用引用后，光标就被限制在引用中，或者可以在引用上方编辑。但是下方无法跳出引用继续编辑。

**Comment by wangfupeng1988** [comment]
将光标放在引用内容的最后面，连续点击两次回车键，就能跳出引用块。

如果按照我说的方法不行，告诉我你的系统和浏览器。

**Comment by jjiale** [comment]
连续2次回车换了2行，没有出引用块。
win7 64 + firefox 57.0.2

**Comment by wangfupeng1988** [comment]
我在 mac 的 firefox 也看到这个问题了，我记录下，下次升级看一下。

近期业余比较忙，升级有点慢，个人开源项目，望体谅

**Comment by jjiale** [comment]
赞,辛苦了

**Comment by wangfupeng1988** [comment]
看了一下，firefox 在引用块之内的回车行为和 chrome 都不一样，firefox 有很多这类的兼容性问题，都不好处理。哎……对于这种情况我现在也很无奈。

近期我还没精力去处理这些浏览器兼容性的问题，目前只能先这样。
