### ISSUE TITLE
请问一下关于图片上传的问题

### ISSUE THREAD

**Issue by Jackstraw007** [wangfupeng1988/wangEditor#1236]
路径配置确定没问题，但是图片上传之后到配置的路径里找不到，开启了debug也没报错。

**Comment by wangfupeng1988** [comment]
> 但是图片上传之后到配置的路径里找不到

这个得从 server 端的代码中跟踪看一下

**Comment by Jackstraw007** [comment]
解决啦，谢谢。
我自己搞错了，我把这段文档理解错了
**// 配置服务器端地址
 editor.customConfig.uploadImgServer = '/upload'**
以为‘/upload’是个存储图片的文件夹，居然没去写服务端脚本，尴尬

**Comment by lsoy** [comment]
我也是这个问题，以为是路径，在那里配置脚本呢
