### ISSUE TITLE
最新的编辑器怎么没有字体的按钮

### ISSUE THREAD

**Issue by 250815674** [wangfupeng1988/wangEditor#1239]
![image](https://user-images.githubusercontent.com/31196476/34375669-a39e4d06-eb22-11e7-9eb8-3ce43e7778e7.png)
我看到css里面有 font-family的参数，但是我在配置里面加上 ‘font-family‘是无效的。文档里面也没有说明，大神能告知一下吗？

**Comment by wangfupeng1988** [comment]
v3 版本之后去掉字体和字号的功能了，编辑器要输出尽量纯净的 html 内容，字体和字号应该都通过标签和样式来统一控制

**Comment by 250815674** [comment]
哦，知道了，我还以为可以用什么办法召唤出来，看来是少了这个神兽了！
