### ISSUE TITLE
为什么代码存进数据库后显示出来不自动换行了

### ISSUE THREAD

**Issue by tzfun** [wangfupeng1988/wangEditor#1240]
我做一个简单的demo在页面上，富文本里面插入代码，然后获取富文本内html然后显示在另一个div里面，格式是正常的有自动换行，但是把相同的html代码存进数据库之后再显示在页面上就没有自定换行了，请教作者这个应该怎么做？还有我的highlight老是配置不好，能不能给个demo？？

**Comment by wangfupeng1988** [comment]
> 为什么代码存进数据库后显示出来不自动换行了

这个问题得从 server 端和数据库存储的内容着手看，我只提供前端的编辑器插件，因此我也不知道该怎么解决。

> 还有我的highlight老是配置不好，能不能给个demo？？

v3 版本之后暂时不支持 highlight
