### ISSUE TITLE
请问删除table的时候是怎么做到把table当作一个整体删除的？

### ISSUE THREAD

**Issue by liping1994** [wangfupeng1988/wangEditor#1242]
我这里自定义插入一大块 东西包在div里面，在删除的时候，光标会跳到子元素的位置把子元素删掉，而div最后才可以删掉。
我想的办法是把那一大块东西放在iframe里面（iframe可以直接删掉），但是不方便的就是要把样式给他，在向后台存的时候也需要把iframe单独存起来。
![image](https://user-images.githubusercontent.com/23331306/34401678-a88602c2-ebd7-11e7-9a23-757256dce9aa.png)
所以我也想用删除table的方法， 直接把最外面的div删掉。
![image](https://user-images.githubusercontent.com/23331306/34401432-1d841e3a-ebd6-11e7-883d-f0c19009849f.png)

**Comment by liping1994** [comment]
找到一办法  大概是下面的流程  但是我感觉性能可能会不好，每次都没办法取舍， 纠结。
（1） 插入的时候插入一个有标记的div， 如他的class为 baibiao

![image](https://user-images.githubusercontent.com/23331306/34403476-679ff77a-ebe3-11e7-8097-b61e4207cdfd.png)

（2）监听编辑区域的onkeyup事件， 如果发现当前按的是退格键，并且该元素的父元素中存在class为baobiao的div， 对编辑区域的html进行替换。

![image](https://user-images.githubusercontent.com/23331306/34404379-30298cfc-ebe8-11e7-9d68-6121822282da.png)

这种方式和保存iframe的innerHTML的方式， 哪种方式更好？

**Comment by liping1994** [comment]
向同事请教了， 这种方法比起iframe更不好。

**Comment by wangfupeng1988** [comment]
> 我这里自定义插入一大块 东西包在div里面

案例说，编辑器中不能出现`<div>`，只能是一个一个的`<p>`标签

> 请问删除table的时候是怎么做到把table当作一个整体删除的？

v3 版本之后，点击表格，然后点击菜单栏中的“表格”菜单，会弹出面板，有删除整个表格的方法

**Comment by liping1994** [comment]
蟹蟹您， 我找到了，准备自己尝试下。
因为我们的项目需要扩展编辑器（根据后台数据， 渲染出图表， 放到编辑器中， 生成一篇报告）， 所以我仍然使用的2。
