### ISSUE TITLE
粘贴内容到编辑器有问题？

### ISSUE THREAD

**Issue by lijun1243939149** [wangfupeng1988/wangEditor#1245]
**【软件环境】**
    mac笔记本、Chrome（V63.0.3239.108）浏览器
**【代码片段】**
```
    // 关闭粘贴样式的过滤
    editor.customConfig.pasteFilterStyle = false
    editor.customConfig.pasteTextHandle = function (content) {
        console.log(content)
        // content 即粘贴过来的内容（html 或 纯文本），可进行自定义处理然后返回
        return content
    }
```
**【场景描述】**
    在秀米图文编辑工具（[工具链接](https://xiumi.us/studio/v5#/paper/for/new)）里面编辑好样式，复制粘贴到wangeditor编辑器，样式完全错掉了，于是我就在浏览器console打印了一下看看复制过来的东西是什么，于是发现原来很多标签的属性`  style="` 都没有了。。。截图如下（红色划线部分）
**【截图】**
![wechatimg1839](https://user-images.githubusercontent.com/13789967/34405111-67e177b4-ebec-11e7-984e-f999c067c4be.png)

**Comment by wangfupeng1988** [comment]
按理说配置了`editor.customConfig.pasteFilterStyle = false`就不会去处理粘贴的内容，我抽时间看下这个问题吧。

近期业余忙，更新有点慢，请体谅。

**Comment by lijun1243939149** [comment]
好的，辛苦大神了～

**Comment by NoBugsss** [comment]
我也是这个问题editor.customConfig.pasteFilterStyle = false配置后图片粘贴过来就没了

**Comment by wangfupeng1988** [comment]
我亲自试了一下，复制如下内容：

![](https://images2017.cnblogs.com/blog/138012/201802/138012-20180214183107546-921737837.png)

默认情况是

![](https://images2017.cnblogs.com/blog/138012/201802/138012-20180214183125890-156102438.png)

设置了`editor.customConfig.pasteFilterStyle = false`之后是

![](https://images2017.cnblogs.com/blog/138012/201802/138012-20180214183305390-2084631079.png)

可见这个配置还是符合预期的，至于你说的问题，会不会是个特殊情况？看能否使用 editor.customConfig.pasteTextHandle 来控制？

**Comment by NoBugsss** [comment]
这种我试也是成功的，但是我在秀米https://xiumi.us上复制排版好的内容就有问题，试其他编辑器是可以的

在 2018-02-14 18:35:23，"王福朋" <notifications@github.com> 写道：


我亲自试了一下，复制如下内容：

默认情况是

设置了editor.customConfig.pasteFilterStyle = false之后是

可见这个配置还是符合预期的，至于你说的问题，会不会是个特殊情况？看能否使用 editor.customConfig.pasteTextHandle 来控制？

**Comment by tao-jia8** [comment]
的确有这个问题，直接把秀米编辑好的内容复制粘贴到http://www.wangeditor.com/index.html 就会发现部分样式丢失

**Comment by wangfupeng1988** [comment]
如果你用了`editor.customConfig.pasteFilterStyle = false`之后，复制样式还是有问题，那应该就是浏览器的问题了，JS 此时不会做任何限制。
