### ISSUE TITLE
php后端接收不到上传的图片

### ISSUE THREAD

**Issue by minorzhang** [wangfupeng1988/wangEditor#1246]
PHP后端用$_FILES接收不到图片？？怎么处理？

**Comment by 250815674** [comment]
我也遇到了这个情况，怎么处理的呢？

**Comment by wangfupeng1988** [comment]
看一下 request 中的所有数据，肯定有图片文件。

**Comment by qwe4251782** [comment]
request 里只有一个PHPSESSID,内容是:nt98ne2gd9nej3mj36rlrvh547,  求助

**Comment by wangfupeng1988** [comment]
看 http 请求啊，图片肯定是发过去了
