### ISSUE TITLE
插入链接校验时，只要返回不是true，都会有一个alert弹框，这个能去掉么？

### ISSUE THREAD

**Issue by tanxuewei** [wangfupeng1988/wangEditor#1249]

**Comment by wangfupeng1988** [comment]
你返回`true`不行吗？

**Comment by tanxuewei** [comment]
就是我要加个校验判断一下，但是只要不是return true, 我返回或不返回，都会有alert弹框

**Comment by tanxuewei** [comment]
我就是希望能把默认的alert弹框去掉

**Comment by wangfupeng1988** [comment]
> 只要不是return true, 我返回或不返回，都会有alert弹框

JS 函数如果没有明文的`return`，会默认`return undefined`，你在函数最后一行加一个`return true`就可以了。

即，函数体上面的其他部分，如果识别有问题，那就直接`return false`，如果识别没问题，代码继续往下走，总归后走到最后一行的`return true`的

**Comment by tanxuewei** [comment]
return false 会有alert弹框出来，我想用自己的弹框

**Comment by yangfandashuaige** [comment]
> return false 会有alert弹框出来，我想用自己的弹框

其实可以禁止alert
在你点击的时候 直接  
```
editor.customConfig.linkCheck = ()=>{
 window.alert = ()=>{ return false }
 return true
}
```
注意：
 这样的话 所有的alert 都会禁止🚫

**Comment by hanxyan** [comment]
补充上楼，的确可以去掉alert弹框。
我是想改超链接的样式，但是因为其他应用也会用到插入的内容，如果用官方文档推荐的获取html文章里的样式定义，其他应用也要配合改样式，所以想直接加在style上。
如果插件在插入标签的时候，允许自己配置标签的一部分属性（比如style,自定义属性）就好了，因为自己使用感觉蛮多地方（比如上传图片项目要求图片带自定义数属性标识方便回收、样式设置）都会和默认插入的标签产生偏差、以及搜索的时候也看到一些文章通过改源码来修改标签的属性，感觉是蛮普遍的需求（虽然现在都有折中的办法editor.cmd.do和暴露的配置如customConfig来实现）。
`this.editor.customConfig.linkCheck = (text, link) => {
                    // text-插入的文字,link-插入的链接
                    this.editor.cmd.do('insertHTML', `<a href="${link}" target="_blank" style="color:#2440b3;text-decoration:underline;">${text}</a>`)
                    let orignalAlertMethod = window.alert
                    window.alert = ()=>{ return false }
                    setTimeout(()=>{
                        window.alert = orignalAlertMethod
                    },100)
                    // return true // 返回 true 表示校验成功
                    return '' // 返回字符串，即校验失败的提示信息
                }`
