### ISSUE TITLE
容器宽度设定为80%的时候，加载宽度异常

### ISSUE THREAD

**Issue by xingwen1987** [wangfupeng1988/wangEditor#125]
加载容器为div，设定为40%的时候，加载编辑器，会出现编辑器头部超宽，内容部分正常，滚动条不贴边的情况。版本为最新的V2.0.5.1版本

**Comment by xingwen1987** [comment]
![image](https://cloud.githubusercontent.com/assets/15207100/13101549/93a94d5e-d582-11e5-8107-d7d17df23828.png)
同时，使用文档上的方法 var editor = $(...).wangEditor();
会提示如下问题：
![image](https://cloud.githubusercontent.com/assets/15207100/13101609/f39852dc-d582-11e5-89be-50ef187d2e90.png)

**Comment by wangfupeng1988** [comment]
问题解决了吗？干嘛刚提交就把问题关闭了？

**Comment by xingwen1987** [comment]
我看错说明文档了，我收藏夹收藏的是 wangEditor 1.X 的文档，看了 2.X 的文档以后，修正问题了！
