### ISSUE TITLE
复制的文本等如果有换行会识别不了，因为换行默认的是br标签

### ISSUE THREAD

**Issue by zhou-chengcheng** [wangfupeng1988/wangEditor#1250]
从外面复制的如果有换行的话，到富文本里面解析成`换行前<br>换行后`，转换不了？

**Comment by wangfupeng1988** [comment]
可使用`editor.customConfig.pasteTextHandle`做处理 https://www.kancloud.cn/wangfupeng/wangeditor3/448202
