### ISSUE TITLE
angularjs使用wangEditor报错The given range isn't in document.

### ISSUE THREAD

**Issue by webignorant** [wangfupeng1988/wangEditor#1251]
@wangfupeng1988 
根据教程 https://www.kancloud.cn/wangfupeng/wangeditor2/132884 把wangEditor3集成到angularjs_1.5.5.

`
(function() {
    'use strict';

    angular.module('test')
    /**
     * 指令 angularWangEditor
     * @return {undefined}        [无]
     */
    .directive('angularWangEditor', function() {
        return {
            restrict: 'A' ,
            require: '?ngModel',
            link: function(scope, element, attrs, ngModel) {
                // 初始化 编辑器内容
                if (!ngModel) {
                    return;
                } // do nothing if no ng-model
                // Specify how UI should be updated
                ngModel.$render = function() {
                    element.html(ngModel.$viewValue || '');
                };
                // Listen for change events to enable binding
                element.on('blur keyup change', function() {
                    scope.$apply(readViewText);
                });
                // No need to initialize, AngularJS will initialize the text based on ng-model attribute
                // Write data to the model
                function readViewText() {
                    var html = element.html();
                    // When we clear the content editable the browser leaves a <br> behind
                    // If strip-br attribute is provided then we strip this out
                    if (attrs.stripBr && html === '<br>') {
                        html = '';
                    }
                    ngModel.$setViewValue(html);
                }

                // 创建编辑器
                var editor = new wangEditor(element);
                editor.customConfig.menus = ["source", "|", "bold", "underline", "italic", "eraser", "forecolor", "|", "head","|", "link", "unlink", "|", "undo", "redo","|",'close'];
                editor.create();
            }
        };
    });
})();
`

Console报**The given range isn't in document.**
打断点检查，发现Window.getSelection()的返回值都是null.
相同的directive，换成wangEditor2(editor.customConfig改成editor.config)完美通过.
问问大大啥情况来的，是否是onload的问题呢？

**Comment by wangfupeng1988** [comment]
编辑器早就升级了 v3.x 版本 https://www.kancloud.cn/wangfupeng/wangeditor3/335768 

此前的 v2.x 的版本不维护了，个人开源项目，精力不够

**Comment by zhouxiongking** [comment]
@webignorant 很赞，我遇到这个问题，按照你的提示，解决了
