### ISSUE TITLE
后台获取带样式内容

### ISSUE THREAD

**Issue by jixinpeng** [wangfupeng1988/wangEditor#1252]
php后台怎样获取带样式的内容，例如加粗或者倾斜等
还有我的编辑器加粗和倾斜不能使用是怎么回事

**Comment by wangfupeng1988** [comment]
> php后台怎样获取带样式的内容，例如加粗或者倾斜等

通过`editor.txt.html()`获取内容，传递给后端保存即可 https://www.kancloud.cn/wangfupeng/wangeditor3/335775

> 还有我的编辑器加粗和倾斜不能使用是怎么回事

看一下加粗、斜体这些是否都有对应的`<b>`或者`<i>`标签包裹，如果有标签，那就是 html 内容没问题，浏览器不显示的问题

**Comment by jixinpeng** [comment]
table.customTableClassName {margin-bottom: 10px;border-collapse: collapse;display: table;}.customTableClassName td, .customTableClassName th {border: 1px solid #ddd;}您好 我在用到贵富文本编辑器时加粗和倾斜不好用，您上次是让我看有没有相应的i标签包裹，这是加粗对应的标签，但是我用google浏览器和火狐浏览器都试了都不行，请问是什么问题呢From: "王福朋 <notifications@github.com>"To: "wangfupeng1988/wangEditor <wangEditor@noreply.github.com>"CC: "jixinpeng <jixinpeng@100tal.com>","Author <author@noreply.github.com>"Sent: 2018-01-04 12:29Subject: Re: [wangfupeng1988/wangEditor] 后台获取带样式内容 (#1252)Closed #1252.&mdash;You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by wangfupeng1988** [comment]
> 您上次是让我看有没有相应的i标签包裹，这是加粗对应的标签，但是我用google浏览器和火狐浏览器都试了都不行

都不行，是都没有`<i>`和`<b>`标签，还是有标签但是不加粗啊？严谨一些，“不行”描述太模糊了

**Comment by jixinpeng** [comment]
table.customTableClassName {margin-bottom: 10px;border-collapse: collapse;display: table;}.customTableClassName td, .customTableClassName th {border: 1px solid #ddd;}是有标签不加粗。  我给您发那个图片就是加粗那个标签。From: "王福朋 <notifications@github.com>"To: "wangfupeng1988/wangEditor <wangEditor@noreply.github.com>"CC: "jixinpeng <jixinpeng@100tal.com>","Author <author@noreply.github.com>"Sent: 2018-01-12 20:05Subject: Re: [wangfupeng1988/wangEditor] 后台获取带样式内容 (#1252)您上次是让我看有没有相应的i标签包裹，这是加粗对应的标签，但是我用google浏览器和火狐浏览器都试了都不行都不行，是都没有<i>和<b>标签，还是有标签但是不加粗啊？严谨一些，“不行”描述太模糊了&mdash;You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
