### ISSUE TITLE
编辑器的序列号在火狐上大小不会随H级别的变化而变化

### ISSUE THREAD

**Issue by cordywei** [wangfupeng1988/wangEditor#1255]
在火狐浏览器上，点击有序排列，再点击H按钮，序列号大小没有变化~

**Comment by wangfupeng1988** [comment]
你是用 windows 吗？我在 mac 上倒是没看到这个问题

**Comment by cordywei** [comment]
对的，win7操作系统，谷歌浏览器的结构是 <h1><ol><li></li></ol></h1>    火狐的就<ol><li> <h1></h1></li></ol>

**Comment by wangfupeng1988** [comment]
我下次升级测试一下这个问题，先记录下。

近期业余时间忙，更新较慢，请体谅。

**Comment by wangfupeng1988** [comment]
> 谷歌浏览器的结构是h1 ol li /li /ol /h1 火狐的就ol li h1 /h1 /li /ol

这个问题，是火狐浏览器针对`document.execCommand`这个 API 的兼容性问题，我记得火狐还有很多个类似的这种问题，都不太好解决。

除非像 google doc 那样自己实现一套 selection range execCommand 的功能，但是那样成本就太高了。
