### ISSUE TITLE
预设文字和判断内容问题

### ISSUE THREAD

**Issue by lsoy** [wangfupeng1988/wangEditor#1256]
输入的时候，预设文字不会自动消失，这不利于体验啊，我看作者网站的也是这样。如果不用textarea，那内容字段在哪里设置，还有如何判断内容为空，因为如果空单提交，会向数据库里写一些字符，那前台页面就无法判断这个字段是不是为空。

**Comment by wangfupeng1988** [comment]
https://www.kancloud.cn/wangfupeng/wangeditor3/435978 可以在 onfocus 的时候判断预设的内容，然后清空
