### ISSUE TITLE
第三版不支持destroy了吗

### ISSUE THREAD

**Issue by kkiigg** [wangfupeng1988/wangEditor#1258]

**Comment by wangfupeng1988** [comment]
目前还不支持，这个需求没几个人提，可见用的不是很多。

**Comment by kkiigg** [comment]
吼吼 最近做一个项目需要这个功能      -_-||
请问第二版中 只支持div textarea ，不支持别的标签创建，有什么特殊原因吗？ 注释这段是否会有bug
if (nodeName !== 'TEXTAREA' && nodeName !== 'DIV') {
            // 只能是 textarea 和 div ，其他类型的元素不行
            //return;   
  //}

**Comment by wangfupeng1988** [comment]
> 只支持div textarea ，不支持别的标签创建

编辑器中就这么一个限制。你是想再其他什么标签创建？

**Comment by kkiigg** [comment]
需求是所有的标签都需要  (╯‵□′)╯︵┻━┻
要做个可视化编辑器
想想看有没有别的做法吧   ╮(╯▽╰)╭
