### ISSUE TITLE
关于编辑器复制粘贴的图片样式被更改的问题

### ISSUE THREAD

**Issue by kzb4535303** [wangfupeng1988/wangEditor#1259]
业务需要，一个页面有两个编辑器，A编辑器插入了图片，这张图片是JS加入的 有width=100%的属性 上传成功之后 再把 A编辑器的图片内容复制到B编辑器， B编辑器里的这一张图片 width变为了 图片在A编辑器里的实际宽度(是一个实际的数字了)，width被覆盖了。 请问怎么样可以解决呢

**Comment by wangfupeng1988** [comment]
这种特殊情况，用`editor.customConfig.pasteTextHandle`来自己做处理吧 https://www.kancloud.cn/wangfupeng/wangeditor3/448202
