### ISSUE TITLE
百度地图API故障

### ISSUE THREAD

**Issue by xingwen1987** [wangfupeng1988/wangEditor#126]
点击编辑器的百度地图按钮，提示KEY无效，但是登陆百度地图，重新复制KEY并设置后，仍然提示KEY无效。
![image](https://cloud.githubusercontent.com/assets/15207100/13101474/f7e4c948-d581-11e5-9b6e-80b273794444.png)

**Comment by wangfupeng1988** [comment]
问题解决了吗？干嘛刚提交就把问题关闭了？
