### ISSUE TITLE
把项目集成到React中会出现故障

### ISSUE THREAD

**Issue by TonyGGC** [wangfupeng1988/wangEditor#1262]
@wangfupeng1988   
问题: 在react中把’wangEditor‘封装成一个组件， 以showmodel的形式显示, 会出现两个问题？
1.  菜单不显示
2.  内容区域，无输入文字

请看一下问题 ， 谢谢！

**Comment by wangfupeng1988** [comment]
首先，文档中有一个简单的集成到 React 的 demo 可供参考 https://www.kancloud.cn/wangfupeng/wangeditor3/335788

> 菜单不显示

看是否有 JS 报错？看菜单部分的 DOM 是否被渲染了？—— 总之这个得具体问题具体分析

> 内容区域，无输入文字

看是否有透明的 div 覆盖到了编辑器区域之上，有的话去修改编辑器配置项的`z-index`

另外，你先把“以showmodel的形式显示”这种方式去掉，简单的集成到 React 中，看是否有你说的两个问题？

**Comment by TonyGGC** [comment]
@wangfupeng1988 去掉是正常的

**Comment by TonyGGC** [comment]
@wangfupeng1988 不存在遮罩问题，代码干净的只剩下菜单栏和编辑区域的两个div

**Comment by wangfupeng1988** [comment]
有 JS 报错吗？DOM 都渲染出来了吗？

**Comment by TonyGGC** [comment]
@wangfupeng1988 没有报错  菜单栏是可以点击的

**Comment by TonyGGC** [comment]
问题已解决： 问题在于antd出了问题， Modal用的是antd的
自定义个弹框，没有问题了

**Comment by wujingacross** [comment]
@TonyGGC  你好，麻烦问下你在react中使用的wangEditor，用来回显内容并修改内容时，菜单操作还好使吗？ [我在react的antd的form表单中用了wangEditor进行内容的初始化回显及修改，在修改的时候，选中内容，再操作菜单，效果都不生效，发现光标直接跑到了最后的位置。
`export default class WEditer extends Component {
  constructor(props, context) {
    super(props, context);
    this.state = {
      editorContent: '',
    };
  }

  componentDidMount() {
    const elem = this.refs.editorElem;
    const editor = new E(elem);
    // editor.customConfig.uploadImgServer = '/upload';
    // editor.customConfig.lang = {
    //   'upload image': '上传图片',
    // };
    // 使用 onchange 函数监听内容的变化，并实时更新到 state 中
    editor.customConfig.onchange = (html) => {
      this.setState({
        editorContent: html,
      });
      this.props.onChange(html);
    };
    editor.customConfig.debug = true;
    editor.create();
    this.wEditor = editor;
  }

// 在这个生命周期处理editor的内容回显，但是回显后再编辑，菜单效果就不生效了，光标还跑到了最后，去掉componentWillReceiveProps这个生命周期editor的使用就正常了
  componentWillReceiveProps(nextProps) {
    this.setState({
      editorContent: nextProps.value,
    });
    this.wEditor.txt.html(nextProps.value);
  }

  clickHandle() {
    this.props.onChange(this.state.editorContent);
  }

  render() {
    return (
      <div style={{ background: '#fff' }}>
        {/* 将生成编辑器 */}
        <div ref="editorElem" style={{ textAlign: 'left' }} onBlur={this.clickHandle.bind(this)} />
      </div>
    );
  }
}`
