### ISSUE TITLE
富文本自动焦点  怎么才能取消富文本的自动焦点？

### ISSUE THREAD

**Issue by ej777ej** [wangfupeng1988/wangEditor#1263]

**Comment by hold-baby** [comment]
现在没有提供这个接口
你可以尝试其他方法达到目的，如：页面初始化一个隐藏的button获取焦点来达到让富文本失焦的效果

**Comment by lcl-101** [comment]
@hold-baby 加了，没有起作用

**Comment by wangfupeng1988** [comment]
可先自行将 https://github.com/wangfupeng1988/wangEditor/blob/master/release/wangEditor.js#L4504 这里的`this.selection.restoreSelection();`这一样注释掉，即可。

现在提出这个需求的用户还不多，因此先不做成可配置的。

**Comment by kaykie** [comment]
这个问题还是需要改一下的吧,毕竟还是有需要的

**Comment by ismumu** [comment]
求开放配置项...

**Comment by qilvnuanqingyou** [comment]
求开放配置项... o(╥﹏╥)o@wangfupeng1988

**Comment by monsterboom** [comment]
把selection.restoreSelection()这个方法全部注释掉，就行了～亲测有效

**Comment by Xiaoweizhi** [comment]
可以加个配置么？这个聚焦问题怎么解决

**Comment by weiq** [comment]
应该加个配置的

**Comment by lichengjie19** [comment]
![image](https://user-images.githubusercontent.com/44294887/54755848-dbfe0400-4c21-11e9-84f1-0742492d397b.png)
应该是L4550

**Comment by tanwei0425** [comment]
问题1：个人感觉还是可以配置得把  需求不少。。 
问题2：在有初始化内容的时候，我用鼠标滑动直接选中内容删除，这个时候是没有触发onchange事件的。。

**Comment by Aiiroo** [comment]
这个自动聚焦还不会触发editor.customConfig.onfocus方法。

**Comment by ZeroJsus** [comment]
真的蛋疼这么设置 另外tab进控件中 也不会触发对应的focus方法

**Comment by haitaodesign** [comment]
弃坑了

**Comment by bkdwei** [comment]
editor.txt.append()后面要是能增加个flag也行,设置插入到文末还是光标处.

**Comment by ZeroJsus** [comment]
弃坑了 现在用draft

**Comment by MyAlphaGo** [comment]
有大佬知道别的什么富文本好用吗？

**Comment by MyAlphaGo** [comment]
想当然的做
