### ISSUE TITLE
html数据有问题

### ISSUE THREAD

**Issue by TonyGGC** [wangfupeng1988/wangEditor#1264]
@wangfupeng1988  麻烦看一下    谢谢了
前提: 将图片转成块级(目的在于插入图片时，图片一行显示)
html数据有问题: 
例子: 模拟编辑框数据
       1.  **普通文本emoji链接** (图片在此后边插入)
       2. **图片** (## _注解1_: 下边文本：2133131， 是在图片后边输入的， 然后自动换行)
       3. **2133131**
抓取的html数据:

```
<p>就好舍不得舍不得不是的
<img src="http://img.t.sinajs.cn/t4/appstyl/40/pcmoren_tian_org.png" alt="😃" data-w-e="1">
<a href="http://baidu" target="_blank" style="background-color: white;">6565656516511</a>
</p>
<img src="data:image/png;base64," style="max-width:50%; display:block;">
2133131
```

抓取数据结束
按照步骤123， 输入
问题：  html数据，图片下文本没有任何标签？？？？？？？

另外， 注解1的地方:
输入”2133131“后， 将光标放置”2133131“后按回车，无法进行换行？？？？？？？？？

**Comment by wangfupeng1988** [comment]
编辑区域所有的数据，一定要要用`<p>`包裹。你这些，就没有包裹起来

```
<img src="data:image/png;base64," style="max-width:50%; display:block;">
2133131
```

**Comment by TonyGGC** [comment]
@wangfupeng1988  唯一做的就是把图片变成块级的， 然后数据从html中拿出来就是上边贴出来的
问题就在图片变成块级元素
