### ISSUE TITLE
粘贴图片报错：Not allowed to load local resource: 

### ISSUE THREAD

**Issue by fankq** [wangfupeng1988/wangEditor#1266]
从word中粘贴图片到富文本编辑器时，图片只显示白色的一个框，没有图片，debug后console报错，
Not allowed to load local resource: file:///C:/Users/fankq/AppData/Local/Temp/ksohtml/wpsA6F3.tmp.jpg
图片不能上传到服务器，希望您能抽空看看

**Comment by wangfupeng1988** [comment]
参考 https://github.com/wangfupeng1988/wangEditor/issues/1230 同一个问题
