### ISSUE TITLE
用的wangeditor3 如何设置代码高亮了，插入代码也不显示选择语言

### ISSUE THREAD

**Issue by hiwangqi** [wangfupeng1988/wangEditor#1267]
2的时候还有到3就没有了啊？ 该怎么设置呢

**Comment by wangfupeng1988** [comment]
v3 开始暂时不支持代码高亮。
原因：代码高亮复杂度很高，不太容易很简单的做出效果，而该编辑器追求简洁易用。而且，使用编辑器的程序猿占比不会太大，因此代码高亮的使用比例也就不会太多。
