### ISSUE TITLE
不支持谷歌浏览器吗?

### ISSUE THREAD

**Issue by claa** [wangfupeng1988/wangEditor#1268]
报错问题：The given range isn't in document.
在wangEditor.js :3850

**Comment by wangfupeng1988** [comment]
肯定支持 chrome 浏览器啊！

报错你得把核心的使用代码贴出来啊，光贴个报错信息，我也不知道你是不是用的不对导致的。提问题，信息描述尽量详细。

**Comment by claa** [comment]
谢谢你。文档中介绍的使用方法是
`<script type="text/javascript">
        var E = window.wangEditor
        var editor = new E('#editor')
        // 或者 var editor = new E( document.getElementById('editor') )
        editor.create()
    </script>
`
会报错 :The given range isn't in document.

`<script type="text/javascript">
        window.onload = function(){
        var E = window.wangEditor
        var editor = new E('#editor')
        // 或者 var editor = new E( document.getElementById('editor') )
        editor.create()
        }
    </script>`
这样后就解决了。原因是没有DOM Ready ， 使用window.onload用以保证页面的所有资源都加载完毕后才执行当中的js代码 。

**Comment by wangfupeng1988** [comment]
那你没有没想过：为何文档（或者我做的 demo）中没有用`window.onload`，却也没有发生`The given range isn't in document.`的错误？
