### ISSUE TITLE
按钮提示样式异常

### ISSUE THREAD

**Issue by Ttou** [wangfupeng1988/wangEditor#127]
如果编辑器默认是隐藏的，显示后按钮的提示信息宽度会变成5px
![qq 20160217142531](https://cloud.githubusercontent.com/assets/4298437/13101516/52273710-d582-11e5-9aa9-64db45188ce0.png)

**Comment by wangfupeng1988** [comment]
编辑器中一些区域的尺寸计算，会收到外部容器大小的影响，你如果隐藏了，那么宽度和高度就取不到了。因此，不要强制隐藏编辑器。

如果想要隐藏，也要在 `editor.create()` 之后再执行隐藏，即保证编辑器的计算全部完成之后，再隐藏。

有问题再反馈
