### ISSUE TITLE
如何设置拖拽的方式插入图片？

### ISSUE THREAD

**Issue by ashfengh** [wangfupeng1988/wangEditor#1271]
demo里可以实现拖拽插入图片，可是在本地却不行，请问如何配置？

**Comment by wangfupeng1988** [comment]
你配置图片上传了吗？ https://www.kancloud.cn/wangfupeng/wangeditor3/335782

**Comment by wangfupeng1988** [comment]
拖拽上传图片，是编辑器默认支持的
