### ISSUE TITLE
你好，上传多张图片顺序不是选择图片的顺序？

### ISSUE THREAD

**Issue by nathanwang** [wangfupeng1988/wangEditor#1272]
```
descEditor.customConfig.customUploadImg = function (files, insert) {
    console.log(files);
}
```

这样调试看了 files 的输出结果 和我选择上传的顺序不一致，有没有什么解决方法呢？

**Comment by wangfupeng1988** [comment]
上传本来就是一个异步的过程，大家同时异步，那就是说先上传完，谁就先返回，没有串联的顺序。

如果要实现类似的功能，目前的情况，你只能从你的 server 端找一下看能否识别出来选择图片的顺序，然后 server 端返回的时候，按照顺序返回。
