### ISSUE TITLE
初始化默认会有内容

### ISSUE THREAD

**Issue by xiatianlong** [wangfupeng1988/wangEditor#1274]
默认就会有一个p标签，里面有br ??   这样的话我只能获取到html内容，判断内容是不是p标签+br，如果是这，就代表用户啥也没输入？
![image](https://user-images.githubusercontent.com/16421040/34993339-fb3a4cb6-fb0a-11e7-8aad-0ee6a932d4bb.png)

**Comment by wangfupeng1988** [comment]
看用户有没有输入，可以通过`editor.txt.text()`来看啊。

另外，编辑器默认有`<p><br></p>`这是避免不了的，必须有。

**Comment by xiatianlong** [comment]
假如用户只输入一个表情，即一个img标签插进去，这时候`editor.txt.text()`是获取不到内容的，但是也不能说用户没输入。所以感觉只有判断`editor.txt.html() === '<p><br></p>'`来判定用户是否输入了。
