### ISSUE TITLE
建议在菜单栏最右侧加上一个"提交"功能

### ISSUE THREAD

**Issue by fuxiaofeng** [wangfupeng1988/wangEditor#1275]
看到大师的作品真是爱不释手，建议在菜单栏右侧增加一个提交功能，因为在下觉得这样不会破坏作品的美感，更酷
作为一个前端菜鸟，麻烦指点下如何下手修改，请问前端有什么经典的书籍推荐么？^_^

**Comment by wangfupeng1988** [comment]
> 建议在菜单栏最右侧加上一个"提交"功能

严重不符合设计原则

> 请问前端有什么经典的书籍推荐么

大众经典书籍，百度、知乎一搜就好了，这个不用专门问。某个专门领域的书籍，不要查的，可以问我。

**Comment by fuxiaofeng** [comment]
好的，多谢
