### ISSUE TITLE
插入图片将选中并切换格式的内容覆盖了

### ISSUE THREAD

**Issue by chen-yin** [wangfupeng1988/wangEditor#1276]
您好，我们这边发现一个不知道是设定还是bug的问题。
当我选中一段文字时，点击上面的斜体按钮。然后点击文本框，再点击上面的其他按钮时会作用到之前选中的内容中。所以当我点击上面图片的按钮时，就会将之前选中的文字干掉。
官网就可以复现。

**Comment by wangfupeng1988** [comment]
这个很正常，你的先取消选区，否则接下来的操作会影响到这个选区的。
