### ISSUE TITLE
请问菜单栏上可以定义一个自己的选项吗？

### ISSUE THREAD

**Issue by TonyGGC** [wangfupeng1988/wangEditor#1278]
另外请教一下， 如何在输入内容的时候， 控制内容字符长度和图片的数量？   O(∩_∩)O谢谢

**Comment by wangfupeng1988** [comment]
第一，v3 之后不再支持自定义菜单了，至于原因，在之前关闭掉的 issue 中回复过很多次了

第二，可以通过 onchange 随时监听最新的 html ，然后分析文字长度和图片数量，然后做控制处理
