### ISSUE TITLE
建议：上传文件的name可配

### ISSUE THREAD

**Issue by Ttou** [wangfupeng1988/wangEditor#128]
当前name为wangEditorH5File，能不能在参数里进行配置

**Comment by wangfupeng1988** [comment]
`name `可不仅仅只是`wangEditorH5File `啊，IE9上传、拖拽上传、截图上传，`name`都不一样。
其实你没必要用`name`取值啊，遍历`request`中的`files`来取就行啊，干嘛非得用`name`取啊？
