### ISSUE TITLE
跨域问题，后端用的是bmob

### ISSUE THREAD

**Issue by ZongDuCha** [wangfupeng1988/wangEditor#1281]
Failed to load https://api.bmob.cn/1/classes/news: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8081' is therefore not allowed access. The response had HTTP status code 502.
怎么破？

**Comment by wangfupeng1988** [comment]
无论后端用什么，解决跨域都是 http 标准的解决方式。跨域问题现在都有现成的解决方案，无论用啥语言、框架，你得自己去找。server 端的事情，我帮不了你。
