### ISSUE TITLE
textarea的问题

### ISSUE THREAD

**Issue by xnnnnnn** [wangfupeng1988/wangEditor#1282]

**Comment by wangfupeng1988** [comment]
不受理`一句话问题`

**Comment by logofun** [comment]
真的希望 wangEditor还是能够绑定textarea
这样前后台传值时方便多了，不需要监听onchange 还需转存一遍文本内容

**Comment by xnnnnnn** [comment]
您好，您的邮件发错了呢！


------------------ 原始邮件 ------------------
发件人: "logofun"<notifications@github.com>;
发送时间: 2019年8月29日(星期四) 中午11:44
收件人: "wangfupeng1988/wangEditor"<wangEditor@noreply.github.com>;
抄送: "楠楠"<609009281@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wangfupeng1988/wangEditor] textarea的问题 (#1282)




真的希望 wangEditor还是能够绑定textarea
 这样前后台传值时方便多了，不需要监听onchange 还需转存一遍文本内容
