### ISSUE TITLE
3.0.15 无法粘贴base64图片Bug

### ISSUE THREAD

**Issue by laozhuorun** [wangfupeng1988/wangEditor#1286]
打开设置`customConfig.uploadImgShowBase64 = true; `后，无法粘贴 base64 图片（github上的demo下载后在本地运行也无法粘贴），js降到3.0.12之后可以粘贴base64，最新的js有问题？

**Comment by wangfupeng1988** [comment]
有可能是，我看官网粘贴也有问题了，我记录下，下次升级排查

**Comment by laozhuorun** [comment]
@wangfupeng1988 我上次提了个bug，选中图片后回车无法删除，好像修复了这个问题之后粘贴base64就不行了，我尝试把js降到3.0.14和3.0.13都有这个问题

**Comment by wangfupeng1988** [comment]
对的，我猜测也是修复这个问题的时候，影响了粘贴功能

**Comment by wangfupeng1988** [comment]
v3.0.16 修复，将今晚发布，请关注发布动态
