### ISSUE TITLE
删除格式

### ISSUE THREAD

**Issue by LeslieZhang** [wangfupeng1988/wangEditor#1287]
有删除格式的功能吗？比如，从其他拷贝过来，然后可以删除粘贴过来的格式。

**Comment by wangfupeng1988** [comment]
第一，想要选中一段文字，点击按钮来删除格式，目前不支持。
第二，想要删除粘贴文本的格式，可参考这里 https://www.kancloud.cn/wangfupeng/wangeditor3/448202
