### ISSUE TITLE
插入链接 体验问题

### ISSUE THREAD

**Issue by laozhuorun** [wangfupeng1988/wangEditor#1288]
操作步骤：如果在插入链接时候不填写链接文字，只填入链接：http://www.wangeditor.com/
结果：插入了空字符或没有插入（没详细看源码）
期望：插入把连接作为文本插入一个链接（文本内容和链接都是http://www.wangeditor.com/）
![image](https://user-images.githubusercontent.com/5772553/35137640-635d1adc-fd25-11e7-9773-dafddae03688.png)

**Comment by wangfupeng1988** [comment]
看看 https://www.kancloud.cn/wangfupeng/wangeditor3/415032 ，可以强制让用户填写链接文字

**Comment by laozhuorun** [comment]
但是如果文字或链接为空，linkCheck 方法根本不执行
![image](https://user-images.githubusercontent.com/5772553/35140123-0a61f482-fd31-11e7-9104-0b7a58f668ea.png)

**Comment by laozhuorun** [comment]
@wangfupeng1988 老铁，有点尴尬哦，直接return了
