### ISSUE TITLE
如果文字或链接为空，linkCheck 方法不执行，Bug

### ISSUE THREAD

**Issue by laozhuorun** [wangfupeng1988/wangEditor#1289]
_insertLink function 第一句，判断如果 text或link任意为空的话直接return了，下面的linkCheck 不会被执行

![image](https://user-images.githubusercontent.com/5772553/35140448-3c9415c4-fd32-11e7-9a1f-a5385b05339d.png)

**Comment by wangfupeng1988** [comment]
OK 感谢反馈。

你先自己改一下源码，我下次升级就立马改成这个 bug 。

**Comment by wangfupeng1988** [comment]
v3.0.16 修复，将于今晚发布，请关注发布动态
