### ISSUE TITLE
粘贴文本，自定义文本过滤方法pasteTextHandle方法会执行两次导致报错。

### ISSUE THREAD

**Issue by Nathanlee2010** [wangfupeng1988/wangEditor#1290]
```js
var E = window.wangEditor

        var editor1 = new E('#div1', '#div2');

        editor1.customConfig.pasteFilterStyle = false;

        editor1.customConfig.pasteTextHandle = function (content) {
            console.log(1111);
            return "1111"
        };

        editor1.create()
```

实际项目中，因为第二次执行的时候会报错，所以导致无法return

**Comment by wangfupeng1988** [comment]
> 因为第二次执行的时候会报错

具体说清楚第二次执行哪里，报什么错。你得让我最快的复现问题，而不是让我猜。

**Comment by Nathanlee2010** [comment]
复制的原文本是个html文本

比如我的pasteTextHandle 方法是这么写的：
let noAttrStr = content.replace(/<([a-zA-Z]+)\s*[^><]*>/g,"<$1>"); //去掉标签属性
let newStr = (noAttrStr.split('<body>')[1]).replace('</body>',''); //去掉<body>之前的内容和</body>之后的内容。newStr实际上就是粘贴文本中的body标签之间的内容。
return newStr;

程序在第一次执行方法后 返回的就是不包含</body>的文本，在第二次执行的时候replace方法就会报错。

从使用者角度来说，我可以增加一个判断避免报错。但是我感觉pasteTextHandle执行两次有点怪怪的并且文档里面也没有说会执行两次。

从来没有在git上提过issues,若有冒犯请多包涵。。。

**Comment by wangfupeng1988** [comment]
> 但是我感觉pasteTextHandle执行两次有点怪怪的并且文档里面也没有说会执行两次。

哈哈，正常情况怎么可能执行两次？这是一个 bug ，被你发现了。其实早就有用户反馈过这个 bug （如果你翻看之前 close 掉的 issue），我让他先手动自己处理，因为我近期业余太忙，没时间弄这个。

这个问题我下次升级会高优处理！我大约会忙到春节，然后就有时间升级了。

感谢反馈！另外，markdown 的语法建议再看看。

**Comment by wangfupeng1988** [comment]
将在 v3.0.16 版本中修复，将今晚发布，请关注发布记录。
