### ISSUE TITLE
集成到vue里面一直报这个错误...是不是我哪里整错了

### ISSUE THREAD

**Issue by zl-qiuhuimin** [wangfupeng1988/wangEditor#1294]
![image](https://user-images.githubusercontent.com/35475962/35253585-264d8be6-0021-11e8-934e-29dc0112c4db.png)
这是报错
![image](https://user-images.githubusercontent.com/35475962/35253591-333a19d2-0021-11e8-845e-6a3a1cd33ae0.png)
![image](https://user-images.githubusercontent.com/35475962/35253603-424cd946-0021-11e8-91d4-ebdc702c509a.png)
这是代码

**Comment by wangfupeng1988** [comment]
文档中有 vue 的示例 demo ，去参照做一下。

**Comment by zl-qiuhuimin** [comment]
@wangfupeng1988  我是照着你的demo写的，只是我没有把富文本编辑器单独申明成组件， 而是直接写到了页面里面。

**Comment by wangfupeng1988** [comment]
单独弄一个组件也是一样的。看你这个错误，像是在 DOM 未初始化就执行了`create()`，你是在组件的哪个生成周期执行的`create()`？

**Comment by zl-qiuhuimin** [comment]
@wangfupeng1988  
![image](https://user-images.githubusercontent.com/35475962/35260569-439bc7b4-0047-11e8-9cf7-99d5d1676f07.png)
跟你的demo一样的

**Comment by zl-qiuhuimin** [comment]
@wangfupeng1988  我试过了 你说的可能是DOM还没初始化就生成周期的问题， 问题不在这， 我把生成组件放到弹框里面去，在点击弹框的时候生成编辑器组件 它还是报这个错误

**Comment by zl-qiuhuimin** [comment]
@wangfupeng1988  找到问题了， 加一个setTimeout事件就可以了 等它创建完成
