### ISSUE TITLE
点击上面的图片没有反应

### ISSUE THREAD

**Issue by LeslieZhang** [wangfupeng1988/wangEditor#1296]
![image](https://user-images.githubusercontent.com/24609152/35262282-ef43ba98-004e-11e8-921f-2c04d68a0459.png)
点击上面的图片没有反应，同是下面的输入框只能输入，删除操作不可以用。
用的jquery,在bootstrap的模态框中使用

**Comment by wangfupeng1988** [comment]
> 点击上面的图片没有反应

这个“上面的图片”是哪里？截图的所有菜单吗？问题要描述清楚。

另外，你先去掉模态框，仅用 jquery 和 bootstrap 试一下，看是否有问题。
