### ISSUE TITLE
从word文档里面复制粘贴样式出问题？

### ISSUE THREAD

**Issue by lliiuu** [wangfupeng1988/wangEditor#1297]
第一个问题：

如果内容里面有`<style></style>`包含的样式，内容就会多出`<style></style>`这个字段。

第二个问题：复制的内容的样式有时候会影响其他的样式

**Comment by wangfupeng1988** [comment]
可用`editor.customConfig.pasteTextHandle`单独处理 https://www.kancloud.cn/wangfupeng/wangeditor3/448202

**Comment by lliiuu** [comment]
粘贴文字显示是没问题的
![image](https://user-images.githubusercontent.com/21049382/35367392-074df6ba-01b9-11e8-81bb-20284ef8d3e3.png)
，是存editor.html()到后台后，从后台取存的数据到页面会多出来<style></style>
![image](https://user-images.githubusercontent.com/21049382/35367361-e2c296e8-01b8-11e8-9002-5d951bf318fd.png)

**Comment by wangfupeng1988** [comment]
> 会多出来<style></style>

用`editor.customConfig.pasteTextHandle`过滤掉就是了
