### ISSUE TITLE
编辑后如何存库，以及表情存入mysql报错

### ISSUE THREAD

**Issue by qinshaokang** [wangfupeng1988/wangEditor#1298]
编辑后存入库中的为html标签，展示的时候会进行转义如何解决，表情如何存入mysql中，会报错，谢谢

**Comment by wangfupeng1988** [comment]
我这边能帮到你的是：**获取到的编辑器区域的 html 内容没问题**，就行了。其他的转义、报错，都是后端的事情，每个人的情况都不一样，只能靠你自己去解决。

最后，如果获取到的编辑器区域的内容没问题，那后面就不该有问题

**Comment by qinshaokang** [comment]
为什么我上传图片只有上传网络图片这个tab,没有上传本地图片这个tab

**Comment by wangfupeng1988** [comment]
要上传本地图片，请认真阅读文档。

这种问题不应该先来提问，而是先去看看文档，哪怕你花 1 分钟看一下文档目录，也就知道了。
