### ISSUE TITLE
关于限制编辑框中字符长度和图片张数问题

### ISSUE THREAD

**Issue by TonyGGC** [wangfupeng1988/wangEditor#1299]
@wangfupeng1988 
1. 首先我是从dom节点中拿到图片的张数的和wangEditor提供的editor.txt.text()拿到字符长度
2. 拿到参数后，进行了字符长度与图片张数限制(到上限就return)
 问题: 达到上限以后， 内容依然可以往编辑框中输入，图片依然可以往编辑框中添加

请问： 源码中哪里可以禁止往编辑框中添加文字和图片？？？？  3ku

**Comment by wangfupeng1988** [comment]
禁止输入文字 https://www.kancloud.cn/wangfupeng/wangeditor3/368562

进入添加图片，试一下 https://www.kancloud.cn/wangfupeng/wangeditor3/448203 看行不行，不行再来反馈。

**Comment by TonyGGC** [comment]
@wangfupeng1988 

文字:  这么操作的话， 就没法操作了（获取不到焦点， div处于非编辑状态）
图片:  不行， 我是做了计数，达到上限再return

**Comment by TonyGGC** [comment]
文字: 这么操作的话， 后续就没法再编辑了（获取不到焦点， div处于非编辑状态）

**Comment by wangfupeng1988** [comment]
那暂时没法支持了，后期升级会考虑做接口
