### ISSUE TITLE
为什么会出现垂直滚动条？

### ISSUE THREAD

**Issue by jhack77** [wangfupeng1988/wangEditor#13]
加载完成后，看到有条垂直滚动条， 是故意这样设计的吗，还是就我的浏览器有这个情况？
我感觉一开始最好没有滚动条，否则有时候看不到自己的光标位置。

**Comment by wangfupeng1988** [comment]
滚动条一开始就有，不是个别浏览器的问题。
你是第二个提出这个问题的，我会把这个问题排到升版计划中，近期后做出调整。

**Comment by wangfupeng1988** [comment]
已经优化
