### ISSUE TITLE
出现TypeError: Cannot read property 'bold' of undefined

### ISSUE THREAD

**Issue by liuww111** [wangfupeng1988/wangEditor#130]
在异步渲染的时候出现，错误行号2817，js文件版本2.0.1

**Comment by wangfupeng1988** [comment]
把html代码粘贴出来。
并且把复现步骤描述一下，例如是点击某个地方才报错，还是一加载页面就报错？

**有问题一定要描述清楚，尽可能的详细，我不嫌罗嗦**

**Comment by liuww111** [comment]
问题找到了，是我全局变量定义的问题
