### ISSUE TITLE
源码如何启用

### ISSUE THREAD

**Issue by zhai8479** [wangfupeng1988/wangEditor#1303]
我想在编辑器中实现查看源码，但是这里的文档写的我不是很理解，求大佬讲解
![image](https://user-images.githubusercontent.com/31183284/35496618-b49574c4-0501-11e8-8cd2-07fb131b8d10.png)

**Comment by wangfupeng1988** [comment]
意思就是，可通过`editor.txt.html()`获取到源码的内容，然后至于如何查看，需要自己来实现。
