### ISSUE TITLE
自定义配置能否支持键值对写法

### ISSUE THREAD

**Issue by cupida** [wangfupeng1988/wangEditor#1307]
之前按照官网的写法自定义配置，没出现问题，然后想把重复的地方用大括号括起来，改成一个object键值对的形式，如下图，然后配置不生效了，包括上面的onchange也是如此
![1](https://user-images.githubusercontent.com/23434111/35509667-01497116-0530-11e8-9993-9c43d3f9b376.png)

**Comment by 3kqing** [comment]
支持一下，这样的方式好一点

**Comment by wangfupeng1988** [comment]
截图中 `editor.customConfig = {...}` 这样一来就把上面的`editor.customConfig.onchange = ...` 覆盖了。语法上就是这样的。
