### ISSUE TITLE
IE所有版本下，编辑器编辑区会出现一个框框，非常不好操作，请问如何清除？

### ISSUE THREAD

**Issue by xingwen1987** [wangfupeng1988/wangEditor#131]
![image](https://cloud.githubusercontent.com/assets/15207100/13131618/af5ce4ca-d627-11e5-89cf-cef81f8ddc56.png)
如上图所示，请问图和清除掉这个编辑器上的框框？

**Comment by wangfupeng1988** [comment]
你使用wangEditor哪个版本？另外IE哪个版本？还有，这个框是如何操作才出来的？

这些问题复现步骤一定要描述清楚，否则我无法判断问题！

**Comment by xingwen1987** [comment]
我使用的是 wangEditor V2.0.5.1
所有IE版本均出现此框
`var editor = new wangEditor("Pinfo");
    editor.create();`
这是我生成编辑器的JS代码

**Comment by xingwen1987** [comment]
生成编辑器后，即出现这个框体。

**Comment by wangfupeng1988** [comment]
我用IE8访问官网 wangEditor.github.io ，看官网的demo，就没有你说的这个问题。
你那里用IE8或者IE8+访问官网，看看demo，有上述问题吗？

如果没有，就给出详细的复现步骤

**Comment by xingwen1987** [comment]
[bug Demo.zip](https://github.com/wangfupeng1988/wangEditor/files/135616/bug.Demo.zip)
这是纯静态的DEMO，请查收，在IE8，9，10，11中出现。
随便在编辑器中输入文字，回车，即出现。

**Comment by wangfupeng1988** [comment]
我运行了你的demo看了，确实有这个问题，我也看到IE中的你所述的效果了。

但是我发现你生成编辑器，即`editor.create()`，是在如下代码中进行的
```
XW.ready(function () {
    pageInit(); //页面初始化 （这个方法中生成编辑器）
});
```
而我试着直接在页面中增加`<script>`执行`editor.create()`是报错的。
你引用的代码太多，我没有时间很详细的挨个看，因此我不明白这是为什么。

但是我又重新实验，验证传统的使用方法在IE下是没有问题的，IE8-IE11都没问题，官网demo就可以验证。而放在你的项目环境中就出现这个问题，那肯定你项目中依赖的某些特性，和编辑器的这个特性有冲突。

我看你在群里说`ueditor`没有这个问题，`ueditor`是用`iframe`实现的编辑器，可能冲突的地方不太一样，但是`iframe`实现也有它不好的地方、也有它的坑。

**我对你的项目环境不熟悉，因此我建议你针对出问题的这个页面，做一个全面的排插，其实也花不了多少时间——即，先做一个基本的编辑器页面（不依赖当前页面中的其他js库），然后将当前页面中的其他js库，一个一个往上加，加的过程中，随时测试，这样就能找出冲突所在。**

找到问题，就好解决了。

祝顺利！
