### ISSUE TITLE
关于开发文档中的一些小建议

### ISSUE THREAD

**Issue by mgsky1** [wangfupeng1988/wangEditor#1310]
这是一款很好的编辑器，刚好这几天自己的站点在更新有用到。但是在使用的过程中，开发文档中“将图片上传至服务器”部分关于`editor.customConfig.uploadImgServer`的讲解不是很详细，就只说明了这个是配置服务器端的地址，给了一个服务器应该返回的格式就没有了，没有说怎么获取我们上传的图片对象。官方的demo也是用base64格式存储的，并不是上传到服务器目录，这个折腾了我好长时间，才发现获取上传的file对象不是使用传统`input`标签中`name`属性获取(我是用ThinkPHP框架)。虽然Web后台编程语言有很多，如果有可能的话建议能不能像获取编辑器值一样稍微说明一下~ 可以让新手少走些弯路

**Comment by wangfupeng1988** [comment]
理解。

不过，你说的这个“稍微说明”，我觉得很鸡肋。对于老手来说，不用说明，对于新手来说，稍微说明没啥用。

最好的方式就是给一段示例代码，但是后端语言太多，我又写不过来，源码中只有 nodejs 的。
