### ISSUE TITLE
复制内容问题

### ISSUE THREAD

**Issue by hackbomb** [wangfupeng1988/wangEditor#1312]
问下，从txt复制内容到wangeditor，保存到数据库，再加载内容就无法显示编辑器了，调用wangeditor的html方法，在Firefox下正常，其他浏览器都无法使用，谁知道怎么解决吗？

**Comment by wangfupeng1988** [comment]
> 再加载内容就无法显示编辑器了

没看明白

> 调用wangeditor的html方法，在Firefox下正常，其他浏览器都无法使用

其他浏览器无法使用是什么意思？报什么错了吗？

**Comment by lihuibo128** [comment]
通过editor.txt.html() 这个接口把获取到的数据直接写入到数据库，没有做任何转换
大部分的字符数据都没有问题，但是拷贝了一些特殊的，比如插入代码，重新读取出来在js中操作数据出现了错误，uncaught： SyntaxError unexpected token
写入数据库是最好需要对数据进行编码吗？然后读取出来解码再显示？

**Comment by wangfupeng1988** [comment]
@lihuibo128 这个得具体看看报错是什么导致的，然后具体分析。当然，保险起见，还是存储数据库时就进行一次 encode 操作
