### ISSUE TITLE
有没有方便的对字数限制的方法

### ISSUE THREAD

**Issue by BruceAKABear** [wangfupeng1988/wangEditor#1313]
本着不想新造轮子的想法，向问一下如果我想对输入字数进行限制，有没有现成的方法？

**Comment by TonyGGC** [comment]
通过这个editor.txt.text() 拿到输入的字符，再进行业务逻辑
源码是没有方法提供的

**Comment by wangfupeng1988** [comment]
楼上回答正确

**Comment by gefangshuai** [comment]
editor.txt.text() 拿到的是纯文本，而实际应用中是控制用户禁止输入，将多余的字符截取掉，而且要带样式，带样式，带样式！
