### ISSUE TITLE
菜单图标无法显示

### ISSUE THREAD

**Issue by Mrli2016** [wangfupeng1988/wangEditor#1314]
![default](https://user-images.githubusercontent.com/27286851/35615860-63080578-06ae-11e8-96f6-20749fd8d095.png)
线上的编辑器样式无法显示
![94936e9c-2da6-4b24-8b9b-da04f31e3fa8](https://user-images.githubusercontent.com/27286851/35615910-87f508b8-06ae-11e8-8c40-a93409324cf1.png)
是因为同源策略问题吗 在https下无法加载

**Comment by wangfupeng1988** [comment]
应该不是这个问题。官网地址是`http://www.wangeditor.com/`，加载的 JS 地址是`https://unpkg.com/wangeditor@3.0.15/release/wangEditor.min.js` ，就没问题。

再者，字体都是通过 base64 编码写在 JS 内部的，JS 加载不受同源策略影响。

**Comment by wangfupeng1988** [comment]
具体原因，可以根据错误提示的关键字，去搜索一下。我这边无法复现，也没法帮你查找原因。

**Comment by Mrli2016** [comment]
是的 就是因为字体是通过js添加base64的 所以那个地址无法引用 我通过下载你git里面的font文件 然后添加到项目里面 在我的.css文件里面复写字体图标样式引用，通过css升权的方式解决了
