### ISSUE TITLE
复制粘贴文字问题——word文档复制过来的文字提交内容为空字符串

### ISSUE THREAD

**Issue by zeemood** [wangfupeng1988/wangEditor#1315]
从word文档复制的文字内容粘贴到编辑器时，提交到后台为空字符串。但是先把word文档里的文字贴到QQ聊天窗口的时候，在复制粘贴过来就没问题

**Comment by wangfupeng1988** [comment]
> 提交到后台为空字符串

你说的跨度有点大。先不要管提交到后台如何，你就看，从 word 复制过来，然后通过`editor.txt.html()`获取的内容是否正确？
