### ISSUE TITLE
复制文本编辑器内内容并粘贴换行符和dom标签会偶发性出现nbsp

### ISSUE THREAD

**Issue by jiexika** [wangfupeng1988/wangEditor#1316]
重复复制粘贴会不间断失灵，复制内容在windows系统的chrome上出现标题的问题，mac上没有，希望回复，然后想办法重现，然后贴码，谢谢

**Comment by wangfupeng1988** [comment]
还得麻烦你看下，如何能让我准确的、快速的、直接复现这个 bug ，偶发性复现，这个问题就不好改了，因为我也不知道咋操作啥时候会复现。

**Comment by 547011926** [comment]
可以用正则去掉nbsp; replace(/&nbsp;/gi,'')
