### ISSUE TITLE
wangEditor3能否像ueditor那样有个属性设置可以设置粘贴的时候只粘贴纯文本，菜单里面有清除格式的按钮

### ISSUE THREAD

**Issue by zhengwen6300** [wangfupeng1988/wangEditor#1317]
你好，请教个问题，wangEditor3能否像ueditor那样有个属性设置可以设置粘贴的时候只粘贴纯文本，菜单里面有清除格式的按钮

**Comment by wangfupeng1988** [comment]
> 粘贴的时候只粘贴纯文本

看这里能支持吗 https://www.kancloud.cn/wangfupeng/wangeditor3/448202

> 菜单里面有清除格式的按钮

这个暂时不支持

**Comment by zhengwen6300** [comment]
谢谢解答，过滤样式因为保留了链接和标题让我以为样式没有过滤，后面比较了下确实过滤了，现在需要一个缩进菜单，这个必须要修改源码吗？

**Comment by wangfupeng1988** [comment]
> 现在需要一个缩进菜单，这个必须要修改源码吗

目前，扩展菜单都需要修改源码，毕竟编辑器不可能满足所有用户的菜单需求。
