### ISSUE TITLE
editor.customConfig.pasteTextHandle 这个事件在ie下失灵，粘贴word文档时过滤不了样式wangEditor3的

### ISSUE THREAD

**Issue by Ben199011** [wangfupeng1988/wangEditor#1318]

**Comment by wangfupeng1988** [comment]
是 IE 哪个版本？

**Comment by Ben199011** [comment]
![1518503432 1](https://user-images.githubusercontent.com/30291896/36136262-81e53602-10ca-11e8-9037-6c9095d66d58.jpg)谷歌的，
![abc](https://user-images.githubusercontent.com/30291896/36136310-bb918892-10ca-11e8-80e5-02e6803ed9ad.jpg)代码，
IE11的打印不出来

**Comment by Ben199011** [comment]
IE11的

**Comment by Ben199011** [comment]
ie的截图上传不了，就是这个函数没法触发，也打印不了，只有IE有这个情况

**Comment by Ben199011** [comment]
![q](https://user-images.githubusercontent.com/30291896/36136818-3dead4d6-10cd-11e8-9bce-ef0de7a8aad7.jpg)

![m](https://user-images.githubusercontent.com/30291896/36136816-3ae239e6-10cd-11e8-9d66-1bc29b30116e.jpg)
![a](https://user-images.githubusercontent.com/30291896/36136719-cbe49728-10cc-11e8-9204-bd86bfdfa57c.jpg)
![c](https://user-images.githubusercontent.com/30291896/36136812-362d2212-10cd-11e8-9131-0e960a97a864.jpg)
粘贴work文档之类的会带各种各样的样式代码，过滤不了，还有一些work的一些内置注释

**Comment by wangfupeng1988** [comment]
https://www.kancloud.cn/wangfupeng/wangeditor3/448202  文档里写了**“注意，以下配置暂时对 IE 无效。IE 暂时使用系统自带的粘贴功能，没有样式过滤！”**

另外，IE 也不支持粘贴上传图片，API 不支持。
