### ISSUE TITLE
v3菜单没有行高和段落？

### ISSUE THREAD

**Issue by awokelee** [wangfupeng1988/wangEditor#1319]
![image](https://user-images.githubusercontent.com/25177843/35763964-349e81e4-08f2-11e8-9afa-e4e91fb5112f.png)

**Comment by NetworkBaby** [comment]
同问

**Comment by wangfupeng1988** [comment]
v3 之后去掉了。行高、字号等，都需要通过 css 统一控制，编辑器不做特殊处理了。

**Comment by IVANLEE99** [comment]
@wangfupeng1988 行高怎么用css精准控制？用户就不能为选中的用户设置行高了？

**Comment by IVANLEE99** [comment]
@wangfupeng1988 行高怎么用css精准控制？用户就不能为选中的字符设置行高了？

**Comment by fplun** [comment]
唉

**Comment by xieting123** [comment]
哎
