### ISSUE TITLE
如何添加本地图片到文本编辑器中？

### ISSUE THREAD

**Issue by Zhang-Yida** [wangfupeng1988/wangEditor#132]
使用最新版本的wangEditor，但是添加图片只有指定url，没有上传本地图片一项，请问，上传本地图片那个是那个版本里的？

**Comment by Zhang-Yida** [comment]
刚才通过这个配置 http://www.kancloud.cn/wangfupeng/wangeditor2/113992 找到了解决方案，但是目前我的需求是添加图片后不上传到服务器端，直接显示到编辑器中，最后表单提交的时候上传文本编辑器中的内容，图片在编辑中以base64格式显示。

**Comment by wangfupeng1988** [comment]
> 但是目前我的需求是添加图片后不上传到服务器端，直接显示到编辑器中，最后表单提交的时候上传文本编辑器中的内容，图片在编辑中以base64格式显示。

这个需求目前不支持，有兴趣可以看看文档中的自定义插件，用自定义插件来解决。
有问题可以继续交流

**Comment by Zhang-Yida** [comment]
@wangfupeng1988 目前工程使用angular搭建。 在$modal 中使用该富文本编辑器时会出现
TypeError: Cannot read property 'menus' of undefined 的问题，请问这个如何解决？

**Comment by Zhang-Yida** [comment]
经过调查 可在$modal的controller中使用$timeout服务来避免此问题出现，问题出现原因是在page没加载进来之前就加载controller，创建了空的editor对象。
处理方法：$timeout(function(){var editor = new wangEditor('test') , editor.create()},0);

您有没有把这个控件迁移到angular的想法？

**Comment by wangfupeng1988** [comment]
有此想法，就是和目前流行的vue、react、angular集成，不过我还没研究工作量大不大。你能帮我大体评估一下吗？

**Comment by Zhang-Yida** [comment]
@wangfupeng1988 小弟也是刚接触angular不久， 如果做angular集成， 小弟愿意帮助贡献code。咱们可以通过QQ沟通， 576218435
