### ISSUE TITLE
有多个选项卡都需要使用富文本时，切换选项卡 富文本会出现重叠 

### ISSUE THREAD

**Issue by xiongjunhao** [wangfupeng1988/wangEditor#1321]
请问editor.destroy 在v3版本中还有吗 只在v2版本看见了  我在v3版本使用了但是没有用，如题这样的问题不销毁之前的富文本的话应该怎样处理，谢谢

**Comment by wangfupeng1988** [comment]
destroy 在 v3 中没有。如果想 destroy 的话，将编辑器对应的 DOM 节点 remove ，然后将编辑器对象赋值为 null 就行了。
