### ISSUE TITLE
被介绍来使用，结果发现字体颜色用了color属性而不是内联style，这不合理吧？

### ISSUE THREAD

**Issue by owenliang** [wangfupeng1988/wangEditor#1322]
如题。

**Comment by wangfupeng1988** [comment]
这个没办法，因为编辑操作是直接用的浏览器提供的`document.execCommand`，这个 API 就是设置 color 属性。

我也知道这样不好，内联 style 更好。但是，如果要搞成内联 style 的话，就得自己实现一套`document.execCommand`，那就太复杂了。
