### ISSUE TITLE
几个多语言的问题

### ISSUE THREAD

**Issue by liping1994** [wangfupeng1988/wangEditor#1324]
1、字体为“黑体”，“微软雅黑”
2、标题为“标题1”， “标题2”....
3、插入链接、插入图片的 “提交”， “取消” 
应该怎么做多语言？ 我用的wangEditor2 (我们的业务需要扩展编辑器，没办法)
![image](https://user-images.githubusercontent.com/23331306/35900898-45e5deb4-0c0f-11e8-9f34-d37dbef9d6d2.png)
![image](https://user-images.githubusercontent.com/23331306/35900905-4c263fa8-0c0f-11e8-94b7-5a166ea3ff2f.png)
![image](https://user-images.githubusercontent.com/23331306/35900909-50ed71be-0c0f-11e8-8884-afbd6c2e6bd1.png)
![image](https://user-images.githubusercontent.com/23331306/35900918-57a91724-0c0f-11e8-9e8e-52d839016b89.png)

**Comment by liping1994** [comment]
我用js把内容给替换掉了
![image](https://user-images.githubusercontent.com/23331306/36021572-2df5ab28-0dc1-11e8-9fe1-9498e3577ba9.png)

**Comment by wangfupeng1988** [comment]
v2.x 版本只能自己做处理了，我不在技术支持。个人开源项目，精力有限，希望体谅
