### ISSUE TITLE
使用require.js加载wangEditor3不成功

### ISSUE THREAD

**Issue by yxzq** [wangfupeng1988/wangEditor#1325]
之前项目用require.js加载wangEditor2,没有问题,现在使用wangEditor3却加载失败,老是报错: E is not a constructor,单独的页面引入wangEditor3也没有问题的,请问大神这个怎么解决

**Comment by wangfupeng1988** [comment]
https://www.kancloud.cn/wangfupeng/wangeditor3/335770 参考这里，先做一个非常简单的 demo 试试（暂时抛开复杂的项目环境）

源代码  https://github.com/wangfupeng1988/wangEditor/tree/master/example/demo 这里，`test-amd.html`是我自己做的 demo ，你也可以下载下来试试
