### ISSUE TITLE
截图粘贴功能，暂时用paste-image实现了····

### ISSUE THREAD

**Issue by webssyu** [wangfupeng1988/wangEditor#1326]
环境：vue的框架，用的wangEditor3
但是主要是复制excel的内容的时候，会自动生成一个图片，粘贴到编辑器的时候，会出现一个表格、一个表格的图片。目前我展示可以屏蔽这个问题，但是总感觉是坑。

**Comment by wangfupeng1988** [comment]
> …… 会自动生成一个图片 …… 会出现一个表格、一个表格的图片。

看现象，复制的内容就这样，并不是粘贴的问题。可暂时使用`editor.customConfig.pasteTextHandle`来自行屏蔽处理，用法参考 https://www.kancloud.cn/wangfupeng/wangeditor3/448202 

有问题再回复
