### ISSUE TITLE
禁用编辑器时，有些小问题

### ISSUE THREAD

**Issue by LWD8** [wangfupeng1988/wangEditor#1329]
（菜单和文本域不分离的情况）

禁用编辑器时，菜单还是可以编辑。虽然点击不会修改原本内容，不过如果上传图片是七牛或服务器的，如果不保存一直上传这也不好。

建议有个可以隐藏菜单的状态或者禁用编译器时，菜单也是不可点击状态

**Comment by LWD8** [comment]
现在找到另一个方法，直接把菜单配置成空数组就行了

**Comment by LWD8** [comment]
![image](https://user-images.githubusercontent.com/28432674/36017212-af419db4-0db1-11e8-9103-c0144f27cc9b.png)
![image](https://user-images.githubusercontent.com/28432674/36017219-bde110a2-0db1-11e8-8315-5cb4491414f8.png)
![image](https://user-images.githubusercontent.com/28432674/36017243-da5343f4-0db1-11e8-8ec6-4b2cfab8acc8.png)
![image](https://user-images.githubusercontent.com/28432674/36017261-f1367514-0db1-11e8-9df2-cd31c573f604.png)


现在有新问题，如果我配置菜单为空数组的话，image菜单是必填的，否则控制台出现错误。需要没什么影响内容和操作，第一条都出一个错误，显示太多。

建议：菜单设置空数组，不用菜单的时候也是可以的，没有显示必填错误

**Comment by wangfupeng1988** [comment]
我这样试了一下，是不会报错的。你可以试试，做一个最简单的 demo 试试

```html
    <div id="div3">
        <p>欢迎使用 wangEditor 富文本编辑器</p>
    </div>

    <script type="text/javascript" src="/wangEditor.min.js"></script>
    <script type="text/javascript">
        var E = window.wangEditor
        var editor2 = new E('#div3')
        editor2.customConfig.menus = []
        editor2.create()
    </script>
```

**Comment by LWD8** [comment]
今天才有空看了一下，是初始化七牛的问题。上传按钮ID是必填的，如果菜单上没有image菜单时，初始化七牛会出错。
![image](https://user-images.githubusercontent.com/28432674/36652145-c6655bc8-1ae7-11e8-9e94-a03bd567490a.png)
![image](https://user-images.githubusercontent.com/28432674/36652154-d3f13122-1ae7-11e8-91bb-6eb723e5d5d2.png)

**Comment by heihei001** [comment]
@LWD8 可以使用$toolbarElem属性直接操作工具栏的display，不过要注意显示的时候要用flex，父级节点还需要加一个border-top
