### ISSUE TITLE
关于wangEditor无法使用表格的问题！

### ISSUE THREAD

**Issue by ibtoncom** [wangfupeng1988/wangEditor#133]
点击表格，无法显示，直接空白的。不知道是不是没有引用？

**Comment by ibtoncom** [comment]
我使用环境是wordpress+bbpress，还有一个问题是无法@回复

**Comment by ibtoncom** [comment]
![qq 20160218235910](https://cloud.githubusercontent.com/assets/17318618/13149881/354ebb1e-d69e-11e5-9726-6af9bec6a852.png)

**Comment by wangfupeng1988** [comment]
**点击表格，无法显示，直接空白的。不知道是不是没有引用？**

这个问题我没有发现过，不过你可以这样验证一下：首先，用你的浏览器访问官网demo，看看行不行，我估计这个是没有问题的。如果行的话，我怀疑是你的项目环境和编辑器的样式有冲突。你试着一个一个删除项目页面中的其他css或者js，然后随时测试，看看是不是其他css、js冲突的问题。

**Comment by ibtoncom** [comment]
用我的电脑访问官网DEMO是正常的，可以显示。我排查了没发现什么CSS、JS冲突问题。是不是表格功能还需要类似表情那样配置呢？

**Comment by wangfupeng1988** [comment]
排查是没用的，你亲自按照文档做一个demo，肯定没问题。然后你再在这个demo的基础上，一步一步增加你的项目内容，随时测试着，就能发现是哪里的原因了
