### ISSUE TITLE
复制文字过来 会出现css样式的字符串 是什么问题？

### ISSUE THREAD

**Issue by LinDingTong** [wangfupeng1988/wangEditor#1331]
类似这样的   .............@font-face{ font-family:"Times New Roman"; } @font-face{ font-family:"宋体"; } @font-face{ font-family:"Calibri"; } @font-face{ font-family:"黑体"; } @font-face{ font-family:"Cambria"; } @font-face{ font-family:"华文仿宋"; } @font-face{ font-family:"Symbol"; } @font-face{ font-family:"仿宋"; } @list l0:level1{ mso-level-number-format:decimal; mso-level-suffix:tab; mso-level-text:"%1"; mso-level-tab-stop:21.6000pt; mso-level-number-position:left; margin-left:21.6000pt;text-indent:-21.6000pt;font-family:,Times New Roman,;} @list l0:level2{ mso-level-number-format:decimal; mso-level-suffix:tab;

**Comment by hold-baby** [comment]
什么系统 复制的哪里的文字  用的什么浏览器

**Comment by itcats** [comment]
同样问题，+1  360浏览器

**Comment by LinDingTong** [comment]
在win7系统上，谷歌浏览器，从word文档复制的 ，有点文本不会出现这样的问题，有的会

**Comment by LinDingTong** [comment]
复制在编辑器上是没有问题，上传到服务器上，服务器返回给我，在浏览器上渲染出现这样的情况是要怎么处理？

**Comment by hold-baby** [comment]
我这边没有复现到你的问题 你贴一下 手动获取到的富文本的值

**Comment by wangfupeng1988** [comment]
大家先用`editor.customConfig.pasteTextHandle`自己来处理哈，用法参考 https://www.kancloud.cn/wangfupeng/wangeditor3/448202

`editor.customConfig.pasteTextHandle` 由用户提出会执行两次的 bug ，我会这两天修复，到时候就可以正常使用了。
