### ISSUE TITLE
怎么编辑 html 源代码

### ISSUE THREAD

**Issue by qxwei** [wangfupeng1988/wangEditor#1333]
怎么编辑 html 源代码

**Comment by wangfupeng1988** [comment]
第一，可以通过 API 获取到 html 源码；第二，可以通过 API 设置 html ；—— 然后自己去实现编辑源码功能吧。

编辑器默认不支持。

**Comment by aoeng** [comment]
@wangfupeng1988  大神,可是自己不会实现啊,可以做个菜单扩展吗?默认关闭都可以

**Comment by wangfupeng1988** [comment]
编辑器作为一个公共 SDK ，得考虑 JS 文件的大小，尽量精简，不要冗余任何代码。因此，你提到的扩展只能你自己去实现。而且，按照我说的实现方式，难度并不大，你遇到任何问题可以具体咨询我，或者去 qq 群里跟其他使用者聊。

**Comment by qxwei** [comment]
OK
