### ISSUE TITLE
一般都会引入reset css

### ISSUE THREAD

**Issue by yuu2lee4** [wangfupeng1988/wangEditor#1334]
然后就尴尬了，。。。。

**Comment by wangfupeng1988** [comment]
具体说下你的问题

**Comment by yuu2lee4** [comment]
http://meyerweb.com/eric/tools/css/reset/    全局的reset css会影响到编辑器里的样式展示。。。。

**Comment by wangfupeng1988** [comment]
OK  我记录下，下次版本修复。
感谢反馈

**Comment by yuu2lee4** [comment]
我看了一下其它的几个编辑器  他们的做法是内容区域是一个iframe  这样就不会受到影响了

**Comment by wangfupeng1988** [comment]
我试了一下，受影响有`H` 还有有序、无序列表，大部分都没事儿。这几个有问题，你手动调整一下吧，成本也不大。
