### ISSUE TITLE
二次开发的模块，gulp没有加入到wangeditor.js中

### ISSUE THREAD

**Issue by powercheng** [wangfupeng1988/wangEditor#1337]
对gulp，不熟悉。二次开发的模块，gulp没有监听到加入wangeditor.js。
哪个地方需要配置？poly-fill这个类的作用是什么？

**Comment by wangfupeng1988** [comment]
下载下来源码，然后`npm i`，然后运行`npm run release`，能正常执行吗？

**Comment by hold-baby** [comment]
npm i  
npm run release
修改src下的js 不要直接修改release下面的js
引用release下的js

**Comment by powercheng** [comment]
已解决，谢谢
