### ISSUE TITLE
vue和webpack的环境使用wangeditor本地引用正常，build的时候告诉我cannot resolve ‘wangeditor’

### ISSUE THREAD

**Issue by yayaqu** [wangfupeng1988/wangEditor#1339]
不知道为什么，本地用的时候没报错，build就不行。import WangEditor from 'wangeditor/dist/js/wangEditor'，import WangEditor from 'wangeditor'，var wangEditor = require('wangeditor');全都build不出来，老是报错，报cannot resolve ‘wangeditor’

**Comment by wangfupeng1988** [comment]
参考 https://www.kancloud.cn/wangfupeng/wangeditor3/335789 这里，就是用 npm 安装的 wangEditor，能正常运行。

**Comment by yayaqu** [comment]
老哥，对不住不是wangeditor的锅。。。。是docker的锅，添加了这个插件，docker的base镜像要重新打，把这个插件添加进去才行，所以本地才没的问题，build的时候有问题，因为用的是docker build
