### ISSUE TITLE
上传很大的图片时，无法改变图片大小

### ISSUE THREAD

**Issue by yrcourage** [wangfupeng1988/wangEditor#134]
在上传一张很大的图片导致出现滚动条之后，几乎无法调整这张图片的大小

**Comment by wangfupeng1988** [comment]
好，我看到这个问题了，回头跟踪改一下。感谢提出来哈。改完了，我会在这里回复的。

**Comment by wangfupeng1988** [comment]
已经解决，下载最新版本验证即可。

**Comment by lmandy** [comment]
我这base64和网络图片可以弹出调整图片尺寸的框，使用七牛上传的不行啊，请问大佬们有什么方法没
