### ISSUE TITLE
上传图片成功但图片无法显示

### ISSUE THREAD

**Issue by Mayness** [wangfupeng1988/wangEditor#1340]
本地服务器上传图片成功都可以成功预览的，但是放在云服务器上面后上传成功了却无法获取该图片，控制台显示404。后台用的nodejs，上传后重置了静态资源路径，都是按照王大大的操作来的，请问这是什么问题呢？

**Comment by wangfupeng1988** [comment]
> 控制台显示404

那就是返回的图片 url 不对啊。

如你所述的这种“本地可以，云服务器不行”问题，很正常，本地和线上环境不一样，很可能会出问题。而且这种问题不太好查，我确实也帮不上啥忙，只能自己从现象一点一点入手看。

**Comment by Mayness** [comment]
url是对的，因为当我再次传入一张图片的时候，上一张图片通过url访问又显示的出来，就很奇怪。我猜测应该是静态资源刷新有问题，但明明做了操作的，会不会是云服务器上的硬盘刷新有限制呢？

**Comment by wangfupeng1988** [comment]
> 会不会是云服务器上的硬盘刷新有限制呢？

这个可以通过 server 日志看一下

**Comment by Mayness** [comment]
好的，谢谢！
