### ISSUE TITLE
文档勘误

### ISSUE THREAD

**Issue by ericjjj** [wangfupeng1988/wangEditor#1341]
https://www.kancloud.cn/wangfupeng/wangeditor3/404586
https://github.com/wangfupeng1988/wangEditor/blob/5920a3e2cdec7b20706c9cf01f5b34a99b1232a9/docs/usage/05-other/08-api.md

文档中
```js
editor.do.cmd('insertHTML', '<p>...</p>')
```

应该为
```js
editor.cmd.do('insertHTML', '<p>...</p>')
```

**Comment by wangfupeng1988** [comment]
多谢反馈，源码中的已经改过来了。
但是 kancloud.cn 上的，我看原本就是正确的，请再确认一下。
