### ISSUE TITLE
关于V3版本兼容IE9的疑问

### ISSUE THREAD

**Issue by xjArea** [wangfupeng1988/wangEditor#1342]
之前我留言过说事件的重复绑定和不会自动解绑问题，现在V3的版本已经解决了，好得很，不过IE9目前市场占有率还挺高的，现在使用V3比较纠结的就是这个兼容···
我想了解一下究竟只是那些菜单按钮的样式布局问题(这个其实很好解决···)，还是说有其他的功能是IE9比较难实现的？如果说是图片的上传和预览问题，这个可以用webshim或webUploader来解决，类似jQuery的migrate，让有需要兼容IE9的人自己引入咯。
目前我只想到这两点，我自己没写过编辑器不了解细节问题，希望福朋能解答一番，不少用户相信都有这个兼容的需求，所以希望福朋能再考虑一下···

**Comment by wangfupeng1988** [comment]
不兼容 IE9 不仅仅是你提到的这几点，还有编辑器最核心的 selection 和 range 的 API ，即选取、范围这些。该放弃我就全面放弃了，没有做任何妥协。毕竟个人精力有限，我只能向前看，望体谅。
