### ISSUE TITLE
字体颜色被CSS覆盖

### ISSUE THREAD

**Issue by GawainRong** [wangfupeng1988/wangEditor#1343]
字体颜色目前使用font的color属性设置，会被CSS的color值覆盖，该如何解决？

**Comment by wangfupeng1988** [comment]
在你的 css 代码中做兼容吧，你的 css 代码不应该直接用标签选择器，应该改为 class 选择器

**Comment by GawainRong** [comment]
可以使用styleWithCSS，富文本内容将使用CSS而不是HTML标签控制样式：
```
document.execCommand("styleWithCSS", null, true);
```

使用标签选择器的css代码是遗留文件，直接修改风险较大。

**Comment by wangfupeng1988** [comment]
感谢反馈，我去研究一下

**Comment by wangfupeng1988** [comment]
`document.execCommand("styleWithCSS", null, true);`，加上了，下一个版本发布
