### ISSUE TITLE
复制粘贴word问题

### ISSUE THREAD

**Issue by awokelee** [wangfupeng1988/wangEditor#1344]
![image](https://user-images.githubusercontent.com/25177843/36724166-4b231f3e-1bed-11e8-9de9-128a5409df2f.png)

**Comment by wangfupeng1988** [comment]
你用的哪个版本？

- v2.x 的已经不再技术支持
- v3.x 的可以使用`editor.customConfig.pasteTextHandle`自定义过滤，文档参考 https://www.kancloud.cn/wangfupeng/wangeditor3/448202
