### ISSUE TITLE
w-e-menu的z-index 有点大

### ISSUE THREAD

**Issue by zhangdaren** [wangfupeng1988/wangEditor#1346]
w-e-menu的z-index 有点大啊，都到10001了，这样的设计原理是基于什么考虑的？

**Comment by wangfupeng1988** [comment]
可以自己修改，文档中有说明。

**Comment by zhangdaren** [comment]
谢谢，我还是加多两行css吧。

**Comment by wangfupeng1988** [comment]
> 这样的设计原理是基于什么考虑的？

其实也没啥考虑的，毕竟编辑器是一个插件，用于各种各样的项目，每个项目大家对 z-index 的标准和规定都不同，因此就写了个 10001 ，也可以用户自定义，就这样
