### ISSUE TITLE
v3 用plupload上传图片

### ISSUE THREAD

**Issue by polkYu** [wangfupeng1988/wangEditor#1347]
看了文档，v2的可以配置plupload，v3怎么不行呀，要怎么自定义上传呢

**Comment by wangfupeng1988** [comment]
先去看下文档吧，关于图片上传的，文档中描述的还算详细。目前哪里没有满足需求的，再提给我。

**Comment by polkYu** [comment]
嗯。。文档研究过了，v2关于自定义上传配置的描述挺清晰的，V3好像没有关于plupload的描述，我使用v2版本解决了问题，不知道v3应该怎么操作·····感谢大大的回复

**Comment by wangfupeng1988** [comment]
> V3好像没有关于plupload的描述

v3 不再支持 plupload 了。编辑器要保持独立，不能什么事儿都依赖于其他库，局限性太大，就像 v3 不再依赖 jquery 一样
