### ISSUE TITLE
window.wangeditor 的值为undefined

### ISSUE THREAD

**Issue by ljc930611** [wangfupeng1988/wangEditor#1349]
![image](https://user-images.githubusercontent.com/26054566/36831233-da081932-1d61-11e8-9918-e7250ef1dca3.png)
![image](https://user-images.githubusercontent.com/26054566/36831252-ee3aab7c-1d61-11e8-957f-8dce26100a0a.png)

不管是用js引用还是npm安装window.wangeditor都是undifined是我什么地方写错了吗

**Comment by ljc930611** [comment]
看了一下window对象里面没有wangEditor对象，不知道是我需要做什么才能把对象放进去，npm已经显示安装成功了，能使用import E form ‘wangEditor’这种方式显示，但是当我需用自定义全屏按钮时我将window.wangEditor改为E的时候会提示E未定义，所以想转为window.wangEditor来引入E对象

**Comment by wangfupeng1988** [comment]
抛开你的项目环境，从文档中最简单的 demo 入手，`window.wangEditor`肯定不能是`undefined`

- 直接引用 JS 参考 https://www.kancloud.cn/wangfupeng/wangeditor3/335769
- npm 安装参考 https://www.kancloud.cn/wangfupeng/wangeditor3/335789

**Comment by ljc930611** [comment]
好吧。。。发现问题了。。你那个window一定要是DHTML.js里的window吗

**Comment by ljc930611** [comment]
vue文件里的window是lib.es6.d.ts里的，并不是DHTML.js里的

**Comment by ljc930611** [comment]
对比了一下你使用vue的方式，也是是用的 import E from 'wangeditor' 导入，那像这种有没有实现自定义添加按钮的例子、官方文档上的那一种在vue里用不了

**Comment by wangfupeng1988** [comment]
第一，`window`就是 JS 在浏览器运行时的全局变量；
第二，“实现自定义添加按钮”—— v3.x 版本已经不支持了
