### ISSUE TITLE
关于配置文件的问题

### ISSUE THREAD

**Issue by xiaxs** [wangfupeng1988/wangEditor#135]
请问 自定义菜单的 视频 按钮,英文应该是 video, 我看文档显示的是 vedio,不知作者是否有其他用意

**Comment by wangfupeng1988** [comment]
没有啊。。。那就是错别字了，我回头改过来，感谢提示哈！

**Comment by wangfupeng1988** [comment]
代码中已经改了，尚未发布，下一个版本即可看到效果。
