### ISSUE TITLE
插入的代码不能换行

### ISSUE THREAD

**Issue by thenCoding** [wangfupeng1988/wangEditor#1350]
使用插入代码的功能，在代码编辑区内输入多行代码，点击插入后，代码呈现在内容区全都是没换行的代码。怎么解决，是我的配置不对吗？版本3.0.15

**Comment by wangfupeng1988** [comment]
你看下，用你的电脑和浏览器，能在官网复现这个问题吗？

我在官网试了一下，不能复现。

**Comment by thenCoding** [comment]
@wangfupeng1988 在官网试了一下，换行没问题，我本地和线上都不行。是配置不对吗？同一个浏览器

**Comment by thenCoding** [comment]
找到问题了，自己设置了code标签的样式

**Comment by fengandzhy** [comment]
> 找到问题了，自己设置了code标签的样式

请问怎么设置code标签的样式？
