### ISSUE TITLE
onChange bug

### ISSUE THREAD

**Issue by qinshaokang** [wangfupeng1988/wangEditor#1351]
只输入一个字符，例如“a”,编辑器里显示的是‘‘啊’’，但是实际获得的value是‘‘a’’，但是如果输入多个字符就没问题，例如“wm”,编辑器里显示“我们”，实际获得的value也是“我们”

**Comment by wangfupeng1988** [comment]
你是使用的最新版？最新版已经修复了一个拼音输入法和 onchange 冲突的问题 https://github.com/wangfupeng1988/wangEditor/blob/master/ISSUE.md#v3016

**Comment by qinshaokang** [comment]
我的不是最新版，换到最新版已解决问题，谢谢
