### ISSUE TITLE
大神求问，设置lang属性的问题

### ISSUE THREAD

**Issue by 8824PPZ** [wangfupeng1988/wangEditor#1352]
按照文档通过lang配置英文，但不生效，是什么问题

**Comment by wangfupeng1988** [comment]
你确定看的是 https://www.kancloud.cn/wangfupeng/wangeditor3/356777 这个文档？

**Comment by 8824PPZ** [comment]
我确实是按照你的文档那样写的。
`<script type="text/javascript" src="js/plugins/editor/wangEditor.min.js"></script>
<script type="text/javascript">

	var E = window.wangEditor;
	var editor = new E('#edit');
	editor.customConfig.lang = {
		'设置标题' : 'title',
		'正文' : 'p',
		'链接文字' : 'link text',
		'链接' : 'link',
		'上传图片' : 'upload image',
		'上传' : 'upload',
		'创建' : 'init'
	};
	editor.create();`

是不是还要导入css

**Comment by 8824PPZ** [comment]
TIM截图20180306093209.png…]()

**Comment by wangfupeng1988** [comment]
第一，确定你引入的`wangEditor.js`是不是最新版？
第二，看一下你的浏览器控制台是否报错？

**Comment by 8824PPZ** [comment]
我引入的是wangEditor-3.0.16，控制台也并没有报错

**Comment by wangfupeng1988** [comment]
我亲自试了一下，没问题，我的代码如下：

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>wangEditor lang test</title>
</head>
<body>
    <p>多语言测试</p>
    <div id="div1">
        <p>欢迎使用 <b>wangEditor</b> 富文本编辑器</p>
    </div>

    <script type="text/javascript" src="/wangEditor.js"></script>
    <script type="text/javascript">
        var E = window.wangEditor
        var editor = new E('#div1')

        editor.customConfig.lang = {
            '设置标题': 'title',
            '正文': 'p',
            '链接文字': 'link text',
            '链接': 'link',
            '上传图片': 'upload image',
            '上传': 'upload',
            '创建': 'init'
        }

        editor.create()
    </script>
</body>
</html>
```

运行页面出来，然后看一下插入标题的 droplist ，以及点击“插入链接”菜单，弹出的 panel ，显示的都是英语

**Comment by 8824PPZ** [comment]
确实单网页运行出来是有英文的，但这个带富文本编辑的网页是通过`$().load()`加载到别的网页里面去。

**Comment by 8824PPZ** [comment]
这样的话运行出来就英文替换不了

**Comment by wangfupeng1988** [comment]
> 是通过`$().load()`加载到别的网页里面去

跟这个应该没有关系。只要你执行`editor.create()`，就会执行替换

**Comment by 8824PPZ** [comment]
还是没有找到问题，我还是直接替换原js文件的里面的中文。谢谢你了，大神！
