### ISSUE TITLE
3.0.16版本的一些bug

### ISSUE THREAD

**Issue by weekn** [wangfupeng1988/wangEditor#1353]
1.菜单和编辑器分离后，onfocus无效
2.火狐浏览器，使用字体加粗，倾斜等修饰后，无法还原使用默认原始字体格式

**Comment by wangfupeng1988** [comment]
> 1.菜单和编辑器分离后，onfocus无效

该问题还在解决中，有人提交了 pr https://github.com/wangfupeng1988/wangEditor/pulls ，我还没来得及合并。你如果着急解决这个问题，看一下这个 pr ，自己先改一改源码也行。

> 2.火狐浏览器，使用字体加粗，倾斜等修饰后，无法还原使用默认原始字体格式

火狐浏览器兼容性问题较多，暂时不做高优支持。个人精力有限，望体谅。
