### ISSUE TITLE
用弹出窗口（或对话框）实现预览，弹出窗口中无法获取操作焦点

### ISSUE THREAD

**Issue by jjsun2018** [wangfupeng1988/wangEditor#1354]
一个页面中使用本editor，之后又用easyui做了一个弹出窗口（或对话框）以实现预览，新弹出的窗口不能获得焦点，即鼠标移到新弹出窗口上的按钮，不能点击。去除edior，弹出窗口正常。请问什么原因？如下图中弹出窗口右上部的关闭按钮无法点击

**Comment by wangfupeng1988** [comment]
怀疑是编辑器 DOM 节点的`z-index`比较大导致的，改一下应该就可以了，参考文档 https://www.kancloud.cn/wangfupeng/wangeditor3/342612
