### ISSUE TITLE
vue example中没有本地图片上传

### ISSUE THREAD

**Issue by 247163569** [wangfupeng1988/wangEditor#1359]
![tim 20180305183940](https://user-images.githubusercontent.com/22336766/36970762-9b1485f8-20a4-11e8-8c0b-8f4e3e4fc337.png)
![Uploading TIM截图20180305183903.png…]()

**Comment by wangfupeng1988** [comment]
1. vue example 知识演示编辑器在 vue 中如何使用
2. 图片上传需要另外单独配置，文档中写的详细
