### ISSUE TITLE
两点建议，希望采纳

### ISSUE THREAD

**Issue by xcheese** [wangfupeng1988/wangEditor#136]
1、建议支持传入js对象或者jquery对象都可，id实在是在多富文本地方有些不方便
2、对齐和列表，在1.X版本里是可折叠的，但是新版本都放出来了。。（现在菜单栏按钮有些过多了，很多地方都放不下了）

**Comment by wangfupeng1988** [comment]
> 1、建议支持传入js对象或者jquery对象都可，id实在是在多富文本地方有些不方便

你说的这一点也是有道理的，什么东西当然是越灵活越好啊。但是灵活导致的解决就是复杂度提高，而大家希望的解决是复杂度越低越好。因此这两者就产生了冲突，需要一个均衡。
这样，你不妨把传入id不合适的场景描述一下，咱们可以就事论事的讨论如何解决这个问题。

------

> 2、对齐和列表，在1.X版本里是可折叠的，但是新版本都放出来了。。（现在菜单栏按钮有些过多了，很多地方都放不下了）

对于这一问题，我会在后续升级时，把『折叠』功能加上。因为后续随着扩展的菜单越来越多，肯定会有显示拥挤的问题。不过目前这个功能优先级还不算高（对于这款产品来说），因此放在后面处理。不过在此也感谢你的反馈。

**Comment by xcheese** [comment]
@wangfupeng1988 比如页面里有10个地方回复的地方需要富文本，若是不该源码，只能循环id传进去这样了

**Comment by xcheese** [comment]
『折叠』功能还是希望早些加。。。原先1.X版本的升级这里很坑。。。根本放不下了。。

**Comment by wangfupeng1988** [comment]
知道了。
不过原先1.x版本的折叠太固定了，我再做折叠，肯定要做成可配置的。
