### ISSUE TITLE
粘贴图片问题

### ISSUE THREAD

**Issue by tanxuewei** [wangfupeng1988/wangEditor#1361]
https://github.com/wangfupeng1988/wangEditor/issues/1171
看了这个issue，我想过滤文本样式，但是把图片上传，如果自定义粘贴内容的话，是不是过滤文本样式的要自己重写一遍？？请教下有没有什么好的办法可以处理？

**Comment by tanxuewei** [comment]
或者是我看到之前有个issue：https://github.com/wangfupeng1988/wangEditor/issues/512
增加一个禁止粘贴图片的配置也可以

**Comment by wangfupeng1988** [comment]
加 https://github.com/wangfupeng1988/wangEditor/issues/512 吧，下次升级会加上，到时候统一在 https://github.com/wangfupeng1988/wangEditor/issues/512 这反馈。

**Comment by tanxuewei** [comment]
可以加一个粘贴时候可以标签过滤的配置么

**Comment by wangfupeng1988** [comment]
用`editor.customConfig.pasteTextHandle`过滤不行吗 https://www.kancloud.cn/wangfupeng/wangeditor3/448202

**Comment by tanxuewei** [comment]
https://www.kancloud.cn/wangfupeng/wangeditor3/448202  自己过滤是可以的

**Comment by tanxuewei** [comment]
pasteHtml = pasteHtml.replace(/\s?data-.+?=('|").+?('|")/igm, '')  应该是这里正则匹配有些问题
