### ISSUE TITLE
单页面有两个编辑器，页面初始化会自动聚焦到第二个编辑器，请问如果设置不自动聚焦？

### ISSUE THREAD

**Issue by GuoGuo13** [wangfupeng1988/wangEditor#1365]

**Comment by wangfupeng1988** [comment]
目前不支持这个配置，你先手动删掉这一行 https://github.com/wangfupeng1988/wangEditor/blob/master/release/wangEditor.js#L4548

即`this.selection.restoreSelection();`这一行
