### ISSUE TITLE
一个对div，placeholder的插件，楼主看看能不能加上

### ISSUE THREAD

**Issue by xcheese** [wangfupeng1988/wangEditor#137]
(function (E, $) {
        // 通过 E.plugin 注入插件代码
        E.plugin(function () {
            // 此处的 this 指向 editor 对象本身
            var editor = this;
            var $txt = editor.$valueContainer;
            var $container = editor.$editorContainer;
            editor.$placeholder = $('<div class="wangEditor-placeholder" style="position: absolute;top: 52px;left: 15px;background: transparent;color: rgb(91,93,99);z-index: 1;">'+$txt.attr('placeholder')+'</div>')
            if(!$txt.text()|| $txt.find('img').length > 0){
                editor.$placeholder.addClass('hide')
            }
            $container.append(editor.$placeholder)
            editor.$placeholder.on('click',function(e){
                $txt.focus()
            })
            $txt.on('input', function (e) {
                if($txt.text() || $txt.find('img').length > 0 || $txt.find('blockquote').length > 0){
                    editor.$placeholder.hide();
                }else{
                    editor.$placeholder.show();
                }
            });
        });

    })(window.wangEditor, window.jQuery);

**Comment by wangfupeng1988** [comment]
哈哈，你是第一位向这款编辑器贡献插件的使用者，在此感谢对本产品的支持！

这个我觉得不用集成到源码中，完全可以作为一个插件来存在。你可以自己在github上创建一个项目，把代码传上去，然后写明白说明文档，写明白怎么使用，分享到QQ群里。

我很希望大家能积极写插件，这样插件慢慢积攒，我就能整一个插件库！
