### ISSUE TITLE
在上传图片前添加签名

### ISSUE THREAD

**Issue by ErebusST** [wangfupeng1988/wangEditor#1372]
在  editor.customConfig.uploadImgHooks中的before方法中修改editor.customConfig.uploadImgParams的值，此时将数据和签名放到里面，到后台的时候 接收不到 formdata中的值，怎么能处理呢？

**Comment by ErebusST** [comment]
或者说 有没有一个方法 可以在before的时候更新一下要传的参数？

**Comment by wangfupeng1988** [comment]
`editor.customConfig.uploadImgHooks`是不能在`before`中修改的，目前也没有开发的接口可以如你说的这种方式来修改。

想要更新参数的值，你只能在上传图片之前去修改`editor.config.uploadImgHooks`的值（注意这里是`config`，不是`customConfig `），这里需要你手动修改一下代码。

https://github.com/wangfupeng1988/wangEditor/blob/master/release/wangEditor.js#L4084 这里是统一上传图片的 API ，你可以在这里加入你自己的代码，然后修改`editor.config.uploadImgHooks`的值
