### ISSUE TITLE
使用editor.txt.append向富文本框中添加初始内容，总是多一个空行<p><br></p>

### ISSUE THREAD

**Issue by jjsun2018** [wangfupeng1988/wangEditor#1379]
如题，对于一个已存在的内容记录进行编辑时，通过`editor.txt.clear();`清空，通过`editor.txt.append`设置初始值，但总是显示多出一个空行。相关代码如下，`row.content`为要增加的内容。日志输出显示，`row.content`中无空行，通过`append`增加到富文本框后出现空行

```
console.log('editRecord:1,'+row.content)
editor.txt.clear();
editor.txt.append(row.content);
console.log('editRecord:2,'+editor.txt.html())
```

![2](https://user-images.githubusercontent.com/37031929/37238670-3c9c3f6e-2466-11e8-8b1f-d048eac99ad8.PNG)

![default](https://user-images.githubusercontent.com/37031929/37238647-d7532780-2465-11e8-8fd1-4531905df12c.PNG)

**Comment by wangfupeng1988** [comment]
> 通过`editor.txt.append`设置初始值

应该通过`editor.txt.html`设置初始值
