### ISSUE TITLE
在微信中使用wangEditor的时候，点击底部文字点不出来提示。

### ISSUE THREAD

**Issue by xueleziran** [wangfupeng1988/wangEditor#138]
在微信中使用wangEditor的时候，点击底部文字点不出来提示。
这个问题安卓和ios都存在。
ios上还有一个问题，弹出来的文字编辑跟ios原生态的复制粘贴重合在一起，wangeditor无法使用。

**Comment by wangfupeng1988** [comment]
你问的应该是 mobile 版本的吧？那应该去 https://github.com/wangfupeng1988/wangEditor-mobile/issues 提交问题。

目前 wangEditor 对移动端的支持还是比较弱的，首先，PC版的不支持手机端，其次，mobile版的虽然是为手机端来设计的，但是也只是一个尝试而已。现在我有限的精力都放在2.0PC版的升级上去了，mobile版一直没有更新过。还是存在很多问题的，特别是android系统。

目前，网络上没有很好的适用于移动端的编辑器，看着不错的，都是app做的，而不是javascript写的。

因此，你说的这个问题，我现在确实没有精力去解决，我目前的首要目标，还是要把2.0PC端搞好再说。请见谅吧！
