### ISSUE TITLE
新版的没有了清除样式的功能？

### ISSUE THREAD

**Issue by lhyh-zl** [wangfupeng1988/wangEditor#1380]
记的原来的版本，有一个清除样式的功能，现在没有了。在复制网络文本时，十分不方便啊？还是我没在3里面找对配置吗，望作者大大回复

**Comment by wangfupeng1988** [comment]
v3.x 没有“清楚格式”菜单了。

复制网络文本的格式问题，我会在接下来的版本升级中优先修改。
