### ISSUE TITLE
请问v3版本 图片怎么上传到服务器呀  用php后台怎么接收？

### ISSUE THREAD

**Issue by iIASDAFDF** [wangfupeng1988/wangEditor#1381]
请问v3版本 图片怎么上传到服务器呀  用php后台怎么接收？ 急急急

**Comment by iIASDAFDF** [comment]
@wangfupeng1988

**Comment by iIASDAFDF** [comment]
图片上传到服务器了  但是前段显示上传错误  怎么弄 php设置返回{“url”:asdasda}格式的吗？前台如何接收  生成图片

**Comment by wangfupeng1988** [comment]
php 如何接收图片以及如何返回内容，你得自己去想办法，这并不是编辑器的事情。

你想啊，你就是不用编辑器，单独做一个图片上传的功能，你不照样做不出来吗。因此，先把 php 如何接收图片搞清楚再说。
