### ISSUE TITLE
根据光标聚焦追加内容问题

### ISSUE THREAD

**Issue by fengdou902** [wangfupeng1988/wangEditor#1382]
写了个插件现在主要有两个问题？
一.使用`editor.txt.append('<p>追加的内容</p>')`追加内容，保存的时候无法保存成功，貌似没有textarea同步追加。
二.我想在任意聚焦的光标处添加内容如何操作？在文档中没有找到相关方法

**Comment by wangfupeng1988** [comment]
第一个问题，你试试在`editor.txt.append('<p>追加的内容</p>')`之后再执行一次`editor.change()`，参考文档 https://www.kancloud.cn/wangfupeng/wangeditor3/338872

第二个问题，看看`editor.cmd.do('insertHTML', '<p>...</p>')`是否能满足，文档 https://www.kancloud.cn/wangfupeng/wangeditor3/404586

**Comment by fengdou902** [comment]
已经解决了，非常感谢
