### ISSUE TITLE
输入Python 代码， 没有代码高亮

### ISSUE THREAD

**Issue by wanghaiqing2015** [wangfupeng1988/wangEditor#1383]
没有这个功能了吗， 还是我需要配置一下

**Comment by wangfupeng1988** [comment]
v3.x 版本没有了代码高亮功能。原因：实现起来比较复杂，依赖于其他 js 库，用的人不是很多。

**Comment by wanghaiqing2015** [comment]
_(¦3」∠)_， 代码高亮没人用?  还不如直接把 代码选项去了. 也不能为了精简而精简。

**Comment by wangfupeng1988** [comment]
不是没人用，而是用的人占比不多。如果编辑器是主要是给程序员使用的，我建议你还是直接用 markdown 编辑器比价合适。

**Comment by wanghaiqing2015** [comment]
可是markdown 编辑器， 都太丑了啊， 只有wangEditor 比较漂亮。
