### ISSUE TITLE
上传的图版居中问题

### ISSUE THREAD

**Issue by wsnokia** [wangfupeng1988/wangEditor#1384]
上传的后的图片点击居中，在编辑器中是居中的，但是浏览时不居中

**Comment by wsnokia** [comment]
没有问题。是我的冲突了，不好意思

**Comment by aloehh** [comment]
我也遇到同样的问题： 上传后的图片点击居中，在编辑器中是居中的，但是导出的html 解析后浏览时不居中

**Comment by aloehh** [comment]
解决方式： img 的display 属性不能是： block

**Comment by ela1998** [comment]
> 

有用
