### ISSUE TITLE
ie兼容问题

### ISSUE THREAD

**Issue by hdzakk** [wangfupeng1988/wangEditor#1385]
ie11不能过滤标签吗？

**Comment by wangfupeng1988** [comment]
你说粘贴的时候吧。暂时不支持哈，后期会优先考虑升级。

**Comment by hdzakk** [comment]
是的，粘贴不能过滤内容

**Comment by aasailan** [comment]
关于编辑器无法在ie下粘贴时过滤标签，以及回调自定义处理函数。我粗略看了下源码。发现是这些代码把ie的处理过滤掉了，请问这样做的用意是什么？？以下是源码截图
![image](https://user-images.githubusercontent.com/12505615/40483729-8451c0f8-5f8b-11e8-8105-1adf8b6ec08d.png)
我可以把那段过滤ie的代码注释掉吗？会出现什么bug吗

**Comment by wangfupeng1988** [comment]
IE 中，截图中的代码无法正确执行，可能不会出现什么 bug ，但是该获取的内容可能会获取不到。我记得是，IE 获取剪切板内容的 API 不行（时间久了，具体忘记了）。

你可以注释掉，自己测试一下。

**Comment by aasailan** [comment]
@wangfupeng1988 我在ie11里面测试过，没什么问题。其他版本的还没测试过。
