### ISSUE TITLE
插入代码问题

### ISSUE THREAD

**Issue by hanyuanqiang** [wangfupeng1988/wangEditor#1387]
插入java含泛型的代码提交后，泛型部分全部没了，就是`<>`中的内容

**Comment by wangfupeng1988** [comment]
我在官网试了，插入`<html><div></div></html>`都没问题呀。

你说的“没了”，太不专业，到底是怎么没了？

**Comment by hanyuanqiang** [comment]
`就是插入的代码中如果包含泛型如：Map<String,Object> result = new HashMap<String, Object>();，通过editor.txt.html()获取编辑器内容会变成：Map result = new HashMap();也就是说泛型部分被清除掉了

**Comment by wangfupeng1988** [comment]
我用 https://github.com/wangfupeng1988/wangEditor/blob/master/example/demo/test-get-content.html 这个 demo 试了一下。

清空编辑器内容，然后插入代码`Map<String,Object> result = new HashMap<String, Object>();`，然后点击“获取 html”（即`editor.txt.html()`）按钮，弹出来的内容是：

```
<pre><code>Map&lt;String,Object&gt; result = new HashMap&lt;String, Object&gt;();</code></pre><p><br></p>
```

你自己拿这个 demo 试一试看看
