### ISSUE TITLE
上传图片后台接不到任何数据

### ISSUE THREAD

**Issue by Hyurl** [wangfupeng1988/wangEditor#139]
$_REQUEST 和 $_FILES 都是空的

**Comment by wangfupeng1988** [comment]
后台语言我只用过C#，其他了解不多。

上传图片的问题，可以根据两个地方协助查看。第一，文档中提到的查看`console.log`的日志输出，看看哪里有问题；第二，用chrome抓包一下上传图片的`http请求`，看看是否有数据，request的是什么，response是什么。

**Comment by Hyurl** [comment]
chrome 显示的信息都正确，也有 request payload, 但是 php 获取的输入流却是空的，

**Comment by wangfupeng1988** [comment]
php获取不到信息，那就肯定返回不了数据，形成不了一个完整的流程，这样console.log输出的日志不可能是正常的。

如果你能通过chrome抓包http看到request中的file信息，说明浏览器已经发起了文件的上传，那你的php为何还获取不到数据呢，这肯定不正常啊。

**Comment by Hyurl** [comment]
不过，post 请求被 301 跳转了，是这个原因吗

**Comment by wangfupeng1988** [comment]
301跳转？那估计有问题。

上传图片时，编辑器是直接想后台post一个http请求的，301跳转肯定是你后台服务器做的，你可以去具体查证一下为何要跳转。
