### ISSUE TITLE
能否添加一个事件，就是用户选择编辑器内的文字后，触发一个事件。

### ISSUE THREAD

**Issue by popmanhe** [wangfupeng1988/wangEditor#1394]
编辑器有这个方法：editor.selection.getSelectionText()
能不能加个事件，比如： onselect， 传出来editor.selection.getSelectionText() 的内容呢， 选择起始和截止的字符的index

**Comment by wangfupeng1988** [comment]
你自己监听编辑区域的 click 和 keyup 事件，然后判断`editor.selection.getSelectionText()`就可以了。

浏览器本身没有你说的`onselect`的事件，只能自己实现。按照我说的试试吧。
