### ISSUE TITLE
js主动触发onchange失效

### ISSUE THREAD

**Issue by conan2008** [wangfupeng1988/wangEditor#1398]
`editor.change && editor.change()`执行，onchange没有响应。
chrome，v3.1.0版本。

用手册提供的例子也会失败。

**Comment by wangfupeng1988** [comment]
你得内容有改动，然后再触发`editor.change()`才行啊。你触发`editor.change()`之前，编辑区域的内容相比之前有改动吗？

**Comment by conan2008** [comment]
内容没有改动的时候，无法触发change事件。

**Comment by wangfupeng1988** [comment]
那肯定啊，触发 change 事件之前是要进行对比的
