### ISSUE TITLE
IE10 & firefox 下测试本地图片上传问题

### ISSUE THREAD

**Issue by jhack77** [wangfupeng1988/wangEditor#14]
IE10 和 Firefox 下测试本地图片上传，出现问题。
alert 弹窗返回 iframe 和url之后卡住不动了。
也即图片没有被插入至textarea中。

**Comment by wangfupeng1988** [comment]
不好意思，我文档中写错了，没有加“ok|”，现在已经修改。
再查看文档，按照文档中来操作即可了。
