### ISSUE TITLE
编辑器图标的提示样式出现问题

### ISSUE THREAD

**Issue by linjiaju8** [wangfupeng1988/wangEditor#140]
我在bootstrap3.x中使用了编辑器，是在bootstrap3的modal窗中使用的，不知道是不是样式冲突了，编辑器图标的提示语出了问题，如图：
![20160224163730](https://cloud.githubusercontent.com/assets/6505182/13279840/53b37db2-db15-11e5-82b1-e3d1dc5af6ba.png)

大概看了下不知道为什么tip上自动加了内联样式，把宽度调成了5
![20160224164731](https://cloud.githubusercontent.com/assets/6505182/13279994/51d709fe-db16-11e5-8279-f8131bd2d076.png)

**Comment by wangfupeng1988** [comment]
官网 http://wangeditor.github.io/ 使用了 bootstrap3.3，正常按照文档来配置，是不会有问题的。所以，我猜测这里不是bootstrap引发的问题。

你先把bootstrap的引用去掉，然后测试会不会有这个问题，如果引用了其他的库或者框架，也先去掉测试。一步一步排查问题，就能找到原因了。

**Comment by linjiaju8** [comment]
暂时自己写了样式覆盖解决，后面有时间在细看问题在哪。

**Comment by wangfupeng1988** [comment]
估计和bootstrap的modal窗口有关系，还有提出modal中无法focus编辑器区域，我会尽快验证。

**Comment by wangfupeng1988** [comment]
我使用boostrap的modal，复现了这个问题了，并且修复了，下个版本（v1.0.10）的更新将修复该问题。

**Comment by wangfupeng1988** [comment]
注意，js要写在body的最后，否则也可能导致这个问题。

即便是为了提高稳定性和性能，js也应该写在body最后。
