### ISSUE TITLE
粘贴的图片无法在自定义的时候获取到

### ISSUE THREAD

**Issue by 87liaoqiang** [wangfupeng1988/wangEditor#1400]
我想在自定义上传图片中把复制过来的图片也做一个上传，我看base64的时候是可以获取到复制图片的数据的，我建议在上传到服务器的时候能告知获取粘贴图片base64形式数据的方法，万分感谢！

**Comment by wangfupeng1988** [comment]
抱歉，没看明白你说的是啥意思。能举一个实际的场景说明一下吗？

**Comment by 87liaoqiang** [comment]
hi，您好
   您好，我的场景是，我想把CTRL+C复制的图片的数据放到上传的内容中之前试过一直不行，今天试了下没有问题了
   http://www.pesataweb.com/SSMLQPRODUCT/SSOlogin/fuText
   



Best Regards,
Qiang，Liao
Dedicated Delivery Center
Application Services Global Delivery China
HP Enterprise Services
Telephone +86 15179104857
 
发件人： 王福朋
发送时间： 2018-03-19 11:11
收件人： wangfupeng1988/wangEditor
抄送： 87liaoqiang; Author
主题： Re: [wangfupeng1988/wangEditor] 粘贴的图片无法在自定义的时候获取到 (#1400)
抱歉，没看明白你说的是啥意思。能举一个实际的场景说明一下吗？
