### ISSUE TITLE
关于异步获取粘贴内容

### ISSUE THREAD

**Issue by cycle07** [wangfupeng1988/wangEditor#1401]
这里因为有粘贴内容前判断的需求曾尝试修改您的源码，将pasteTextHandle的判断插入改为支持回调，但后发现document.execCommand因为一些安全机制不支持异步更新，重新写入$textElem也会造成编辑的一些bug，如果可以能否在今后支持这个功能呢?多谢大佬!

**Comment by wangfupeng1988** [comment]
> 发现document.execCommand因为一些安全机制不支持异步更新

这个问题我也发现过，对此没有更好的办法。设计越复杂，坑越多，尽量简单吧。简单实现不了的，就去考虑其他途径来实现，例如能否放在 server 端实现。
