### ISSUE TITLE
支持nuxt的后端加载吗

### ISSUE THREAD

**Issue by zhang8h** [wangfupeng1988/wangEditor#1403]
支持vue的nuxt框架后端加载吗？由于nuxt第页个页面是后端加载的，编辑器不放在首页可以使用，但是按F5刷新就会报错误；有方法解决吗？

**Comment by wangfupeng1988** [comment]
暂时不支持 ssr

**Comment by BranDanny** [comment]
有办法解决，参考链接：https://stackoverflow.com/questions/53806318/window-is-not-defined-nuxt-for-vue-slick
