### ISSUE TITLE
下划线属性建议修改为text-decoration

### ISSUE THREAD

**Issue by yongerhappy** [wangfupeng1988/wangEditor#1405]
现在选择编辑文本加上下划线默认加的属性是text-decoration-line，这个属性兼容性很差，在iOS端都不支持这个属性，所有下划线显示不出来，需要自己手动替换。

所以建议下划线属性建议修改为text-decoration。

**Comment by wangfupeng1988** [comment]
这个暂时还改不了，因为设置下划线都是统一使用了浏览器的`document.execCommand('underline')`这个 API 。如果按照你说的要求，自己实现一个话，成本会非常高。

**Comment by yangfandashuaige** [comment]
我目前也遇到这个问题 
打算在选中的时候状态的时候做一些逻辑操作
