### ISSUE TITLE
在modal中显示无法获得焦点

### ISSUE THREAD

**Issue by 18060006730** [wangfupeng1988/wangEditor#141]
在弹出的modal使用，编辑框就无法获得焦点

**Comment by wangfupeng1988** [comment]
无视『一句话问题』，请详细描述问题复现场景。

**Comment by 18060006730** [comment]
`    <div class="modal fade" id="aaa">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Modal title</h4>
                </div>
                <div class="modal-body">
                    <div id="div1">
                        <p>请输入内容...</p>
                    </div>
                    <script>
                        $(function () {
                            var editor = new wangEditor('div1');
                            editor.create();
                        })
                    </script>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>`
使用的是Bootstrap，$("#aaa"),modal()之后编辑器无法获得焦点

**Comment by wangfupeng1988** [comment]
做一个静态demo，然后QQ邮件发给我吧。
demo要能复现问题，demo要纯静态（不要有后台代码），demo要只包含bootstrap，不能再有其他第三方的库和插件。
邮件中描述清楚如何复现问题。
我根据demo来实际查一下问题的原因。
