### ISSUE TITLE
字号缺少，不能具体指定

### ISSUE THREAD

**Issue by musicWind** [wangfupeng1988/wangEditor#1413]
字号少，14px ，20px之类

**Comment by wangfupeng1988** [comment]
可以看下源码中这一行 https://github.com/wangfupeng1988/wangEditor/blob/master/release/wangEditor.js#L1077 ，字号不是根据 px 来的，而是根据 css 标签来的

**Comment by musicWind** [comment]
是只能提供像small，large这种大小的字体，而不是具体的数字吗

**Comment by wangfupeng1988** [comment]
是的，这受限于`document.execCommand`的 API 参数规范，目前只能这样。如果要用你说的数字来表示，那我需要自己实现这个 API ，那复杂度就高太多了。因此暂时先这样。
