### ISSUE TITLE
建议能增加代码高亮

### ISSUE THREAD

**Issue by SpiritLing** [wangfupeng1988/wangEditor#1415]
代码高亮一直以来是编辑器最大的问题，网上找到的不一定可以匹配，所以希望可以出一个

**Comment by wangfupeng1988** [comment]
代码高亮还是挺麻烦的：第一，自己做很麻烦；第二，集成其他的库也需要不少成本，而且和各种框架的兼容性还是一个未知问题。这是成本问题。

还有一个问题你可能作为使用者考虑不到，就是真正使用富文本编辑器的用户，能有多少人会往编辑器中输入代码？在这些输入代码的人当中，又有多少人非常非常在乎代码高亮。即真正使用编辑器的人，有多少是输入代码的重度用户？我相信这个占比会很大，这也我不会加代码高亮的重要的原因。

另外，如果你的产品的重度用户很多都是程序猿，我还是推荐你使用 markdown 的编辑器。
