### ISSUE TITLE
word复制粘贴到编辑器出现的问题

### ISSUE THREAD

**Issue by zsj1029** [wangfupeng1988/wangEditor#1416]
从word排版好的样式
复制进入编辑器，通过text.html 获取内容发现会携带
`<w:LsdException>`类似这样的标签，实际这些标签对样式没有作用
能否获取的时候把这种非html的标签去除掉，否则保存入库后，后续处理很麻烦

**Comment by wangfupeng1988** [comment]
你可以先通过`editor.customConfig.pasteTextHandle`自己处理一下 https://www.kancloud.cn/wangfupeng/wangeditor3/448202 ，后续编辑器会针对 word excel 的粘贴做统一处理。
