### ISSUE TITLE
与easyui集成的时候，不能编辑内容

### ISSUE THREAD

**Issue by wa114d** [wangfupeng1988/wangEditor#1417]
问题如这样https://segmentfault.com/q/1010000013947817?_ea=3502741，
两个问题：
1、当在文本框中输入内容后，光标选定内容，不能删除内容，只可以ctrl+A全部选中回车删除，JS也没有报错提示
2、这里是个模板，我想点击radio的时候，把radio设置的值插入到文本内容中，用了提供的追加方法，可是却换行添加，多个p标签。
希望能得到回答呢。[https://segmentfault.com/q/1010000013947817?_ea=3502741](url)

**Comment by wangfupeng1988** [comment]
这种问题基本和`z-index`有关系，试着修改一下看看行吗 https://www.kancloud.cn/wangfupeng/wangeditor3/342612

**Comment by wangfupeng1988** [comment]
无回复暂时关闭

**Comment by Sweetjqq** [comment]
let link = '<div><img style="width:400px;height:80px" id="DefaultAudio" src=' + this.imgSrc +
              '><audio style="width=50%;display:none" src=' + audioLink +
              ' controls=controls></audio></div>';
            this.editor.txt.append(link);
使用这段代码在wangeditor文本里面插入内容，可是无法删除，怎么回事儿
