### ISSUE TITLE
不支持amd啊

### ISSUE THREAD

**Issue by ysk2014** [wangfupeng1988/wangEditor#142]
不支持amd啊

**Comment by wangfupeng1988** [comment]
看文档了没？

**Comment by ysk2014** [comment]
Uncaught TypeError: $(...).wangEditor is not a function

**Comment by wangfupeng1988** [comment]
哦，我看了，文档中有些1.x的写法，当时忘记改过来了。我又重新调整了，然后自己也验证了一遍，看看吧。有问题继续回复。
http://www.kancloud.cn/wangfupeng/wangeditor2/113995
