### ISSUE TITLE
使用require.js加载初始化过程会先加载textarea样式再加载富文本样式

### ISSUE THREAD

**Issue by yxzq** [wangfupeng1988/wangEditor#1421]
我使用require.js加载插件的形式进行加载wangeditor的，页面初始化的时候会先加载textarea的样式再加载wangeditor的样坏，中间会有一个很明显的样式切换过程，用户体验很不好，敢问大神这个怎么解决

**Comment by wangfupeng1988** [comment]
你可以在 AMD 加载的 callback 里面初始化 textarea 啊，即在执行`editor.create()`时初始化 textarea ，这样就不会卡顿了。

**Comment by yxzq** [comment]
还是不太明白，怎么在editor。create（）时初始化textarea呀，我是采用jQuery封装插件的形式把wangeditor的创建和上传到七牛云存储功能封装到一块的，参考的文章是您的这篇文章：https://github.com/wangfupeng1988/js-sdk/blob/master/demo/views/wangEditor2.html，加载的时候采用require.js进项加载的，我刚开始分析的时候觉得根据require.js的原理页面先加载HTML的dom结构，（里面包含textarea）再异步加载wangeditor插件js的，所以才导致先渲染textarea的样式再渲染wangeitor的样式的，不知道是不是这个原因，最后这几句创建的代码：
// 生成编辑器
        var editor = new wangEditor('editor-trigger');
        editor.config.customUpload = true;
        editor.config.customUploadInit = uploadInit;
        editor.create();
具体要怎么改？
