### ISSUE TITLE
发现一个体验很不好的BUG

### ISSUE THREAD

**Issue by xuyanchao** [wangfupeng1988/wangEditor#1422]
在项目中发现当你打开粘贴样式的时候，从wps或者office粘贴过来一些文本（其中很可能带有<style>标签），当你再次手动删除所有文本的时候（不要用Ctrl+A）；这时候style标签是还存在的，当你用editor.txt.text()做非空校验的时候他会通过检测（这其实无可厚非），但是他还会吧style标签去除把里面的样式作为文本传给后台。。。

**Comment by vikingleo** [comment]
既然说到粘贴，我也发现一个情况：无法连续粘贴。
按ctrl+v，粘贴出来的只能一次，要连续粘贴，只能松开ctrl再按ctrl+v，才能再次粘贴相同内容

**Comment by leafiy** [comment]
@vikingleo 是节流的问题，更改onChangeTimeoutId就好了，或者直接不用节流

**Comment by wangfupeng1988** [comment]
@xuyanchao 因为你已经打开了粘贴样式，因此会粘贴到`<style>`的内容，这是符合预期的。你又没通过 ctrl + a 删除，因此删除之后存在`<style>`内容也是符合预期的。而既然存在，编辑器肯定会把`<style>`内容获取到，因为如果强行把`<style>`内容干掉，那就不符合你“打开粘贴样式”的需求了。

因此，这个问题只能是你自己单独处理一下，编辑器没有太好的解决方案。

**Comment by sumu1024** [comment]
editor.txt.text()没有过滤&nbsp;，这个由编辑器来做是不是更好一点？

**Comment by wangfupeng1988** [comment]
@sumu1024 `editor.txt.text()`还能再怎么做？

**Comment by leafiy** [comment]
我用比较曲折的方法实现了，已经用于生产环境
1.粘贴时给style和粘贴进来的内容加一个关联ID，比如 copied-content-123
2.使用MutationObserver监控dom变化，当删除元素为copied-content-123 时，从文本中删除对应的style
`const x = new MutationObserver((events) => {
            for (let event of events) {
                if (event.removedNodes.length) {
                   // do want you want
                }
            }

        });
        x.observe(document.getElementById(this.textElemId), { childList: true });`

ps. MutationObserver 很好用性能也很好

**Comment by Hannicke** [comment]
> @xuyanchao 因为你已经打开了粘贴样式，因此会粘贴到`<style>`的内容，这是符合预期的。你又没通过 ctrl + a 删除，因此删除之后存在`<style>`内容也是符合预期的。而既然存在，编辑器肯定会把`<style>`内容获取到，因为如果强行把`<style>`内容干掉，那就不符合你“打开粘贴样式”的需求了。
> 
> 因此，这个问题只能是你自己单独处理一下，编辑器没有太好的解决方案。

默认editor.customConfig.pasteFilterStyle = true是过滤掉样式对吧，但是不管true还是false，还是会有style标签
![image](https://user-images.githubusercontent.com/20440348/50533133-9ff55e80-0b5e-11e9-9131-0baec0ceb3fd.png)
