### ISSUE TITLE
上传图片成功，编辑器不显示

### ISSUE THREAD

**Issue by cocos3ds** [wangfupeng1988/wangEditor#1423]
图片上传成功，按照要求返回格式，但不会自动插入到编辑器，插入到编辑器的逻辑是要自己完成了吗

**Comment by wangfupeng1988** [comment]
https://www.kancloud.cn/wangfupeng/wangeditor3/335782  看下文档，你有没有用自定义上传的方式？

**Comment by ks3dev** [comment]
应该是编辑器焦点没对上~

**Comment by shanezhiu** [comment]
可能不是自定义上传方式，而是自定义返回的数据格式。
`[
    "errno" => 0,
    "data" => [
         // 数据
    ] 
]`

**Comment by dongyidongyi1111** [comment]
您好，我也遇到相同的问题，请问您解决了吗

**Comment by dongyidongyi1111** [comment]
我是用自定义上传方法，也调用了文档中说的insert方法了
