### ISSUE TITLE
使编辑器只读

### ISSUE THREAD

**Issue by YanShuiYuan** [wangfupeng1988/wangEditor#1424]
我的内容是一些类似协议的东西，只给用户看，不能编辑，找了很久没找到相关属性

**Comment by YanShuiYuan** [comment]
解决了，通过vue使用时，按照文档的方法使用disable()方法禁用不起效果，后来审查元素发现有好几个元素有contenteditable属性，起效果的为包裹内容的那个，于是手动获取dom将其设置为false

**Comment by wangfupeng1988** [comment]
> 后来审查元素发现有好几个元素有contenteditable属性，起效果的为包裹内容的那个，于是手动获取dom将其设置为false

其实文档中有些

**Comment by sensuwang** [comment]
emmm 文档中没找到关于disable的讲解啊
