### ISSUE TITLE
在onblur事件里，我想获取wangEdit挂在的div的id

### ISSUE THREAD

**Issue by warmer911** [wangfupeng1988/wangEditor#1425]
因为我的页面需要生成很多wangEdit，但是用户可以随意修改任何一个，我想获取用户操作的那一个的id,然后对这一个div做隐藏等操作，怎么获取呢？

**Comment by wangfupeng1988** [comment]
https://www.kancloud.cn/wangfupeng/wangeditor3/404586 这里有获取编辑区域 dom 节点的 API
