### ISSUE TITLE
I have found this editor can't process image correctly when paste a whole word document use ctrl + a,  but it work normally when paste a single image from word  at your demo site

### ISSUE THREAD

**Issue by Richard2050** [wangfupeng1988/wangEditor#1426]
I have found this editor can't process image correctly when paste a whole Word document use ctrl + a,  but it work normally when paste a single image from word  at your demo site. The word document contain a grid and a image. I think if we can display a single image, we can display the whole document.

By the way, I found I can paste a image at your demo site: http://www.wangeditor.com/index.html
but I can't parse in my test site use the source code download from your link: https://github.com/wangfupeng1988/wangEditor/releases
Can you tell me why?

**Comment by Richard2050** [comment]
I have found below config can solve my demo issue:
  editor.customConfig.uploadImgShowBase64 = true;

**Comment by 417606028** [comment]
because the editor can understand the image from anywhere, so you must be set the image show rules

**Comment by wangfupeng1988** [comment]
> when paste a whole word document use ctrl + a

this way, editor can not process image
