### ISSUE TITLE
如何自适应

### ISSUE THREAD

**Issue by MildSYang** [wangfupeng1988/wangEditor#1427]
![image](https://user-images.githubusercontent.com/11704527/38025994-ff849058-32bc-11e8-8573-692369038282.png)

我看了一个代码 
    /* flex-wrap: wrap; */ 是被注释掉了，而且js 并没有修改它的代码？没有这个功能吗？
如果css 强制修改，它内部的
![image](https://user-images.githubusercontent.com/11704527/38026087-5a8720ce-32bd-11e8-89df-e4622edac67f.png)
会被挡住？

**Comment by wangfupeng1988** [comment]
不支持菜单换行。如果编辑器宽度不够，通过菜单配置来去掉几个菜单吧。换行之后，UI 太难看了。
