### ISSUE TITLE
IE9下本地上传图片失败

### ISSUE THREAD

**Issue by lxm23** [wangfupeng1988/wangEditor#143]
![screen_1456382429_12287](https://cloud.githubusercontent.com/assets/8690938/13311993/e17a0eaa-dbcd-11e5-9ffe-ad92c71f31a1.png)

**Comment by wangfupeng1988** [comment]
是不是跨域了？

另外，你去试试 https://github.com/wangfupeng1988/wangEditor#3-本地运行demo 配置本地demo，试试本次测试有没有问题。我试过是没问题的。

**Comment by lxm23** [comment]
试了下本地demo  log提示如下
![qq 20160225155317](https://cloud.githubusercontent.com/assets/8690938/13313323/0a7eef78-dbd8-11e5-9cb4-0ee31438c6c6.png)

**Comment by wangfupeng1988** [comment]
这个问题，以及IE8的图片上传，我周末一起解决了吧，你再稍等一两天。

**Comment by wangfupeng1988** [comment]
IE8上传图片的功能已经完成，IE9也跟着做了调整，你可下载最新版本再试试这个问题。
有问题再给我反馈。

**Comment by lxm23** [comment]
更新版本后, 可以上传了 谢谢
