### ISSUE TITLE
配置使所有样式内联style

### ISSUE THREAD

**Issue by gitWhatever** [wangfupeng1988/wangEditor#1431]
业务需要，能否配置参数，使生成内容的所有样式都是内联style的，现在默认情况一部分是依赖公共样式的。

**Comment by wangfupeng1988** [comment]
目前不支持。编辑器产出的内容，应该尽量用精简的 html 而不是带有 style 的繁杂的 html 。

**Comment by AllenYangFly** [comment]
从功能上考虑可扩展性强是很好的，从公司业务线上考虑非常糟糕。

这意味着一处编辑，各个富文本数据使用方都需要引入维护一份css样式表。

**Comment by wtto00** [comment]
同样需要这个功能。

自己维护的内容，可能是给别人使用的。不能要求使用人加载一个css等任何操作。
