### ISSUE TITLE
如何更好地做错误回调

### ISSUE THREAD

**Issue by vxhly** [wangfupeng1988/wangEditor#1432]
![image](https://user-images.githubusercontent.com/17906558/38158550-5dc3cf36-34c9-11e8-992c-8f57b50245da.png)
![image](https://user-images.githubusercontent.com/17906558/38158553-701b547e-34c9-11e8-9870-ec1dcbd0dd43.png)
这边写了几个验证，验证图片的大小和只允许上传一张图片，
但是发现错误回调不会写了，他只会在控制台输出，比如
![image](https://user-images.githubusercontent.com/17906558/38158573-c140b786-34c9-11e8-9102-cd20a09c003e.png)
如何将类似于这样的错误，显现出来

**Comment by leafiy** [comment]
关闭debug模式，用customAlert

**Comment by wangfupeng1988** [comment]
楼上正解
