### ISSUE TITLE
如何调用内置功能，或者添加新的自定义钩子？

### ISSUE THREAD

**Issue by leafiy** [wangfupeng1988/wangEditor#1434]
1 比如添加了自定义按钮，如何调用内置的panel功能
2 比如插入视频iframe后的验证钩子

**Comment by wangfupeng1988** [comment]
目前尚未提供统一的接口。如果你有这方面需求，还是得你自己去查阅源码，自己加上，抱歉。

**Comment by wangfupeng1988** [comment]
另外，如果要查阅源码的话，有任何问题随时提问
