### ISSUE TITLE
没有销毁方法么？

### ISSUE THREAD

**Issue by mtsee** [wangfupeng1988/wangEditor#1435]
如果采用react，组件销毁的时候，也想销毁编辑器，避免内存泄露。有销毁的方法么？性能很重要

**Comment by leafiy** [comment]
editor = null ？

**Comment by wangfupeng1988** [comment]
目前还没有统一的销毁 API（前期考虑不周到，后面升级会加上）。暂时可自己封装一个，将编辑器创建的 DOM 节点全部移除，然后`editor = null `

**Comment by mtsee** [comment]
editor = null 不能销毁啊，只是清除实力的引用地址而已，实例内部还有很多引用地址，内存没法释放
