### ISSUE TITLE
上传图片过大导致图片在展示页面超过DIV

### ISSUE THREAD

**Issue by 3kqing** [wangfupeng1988/wangEditor#1437]
上传图片过大导致图片在展示页面超过DIV，所以上传图片的时候能不能做高宽设置呢？

**Comment by leafiy** [comment]
img max-width:100%

**Comment by wangfupeng1988** [comment]
所有图片，无论是上传的还是插入网络链接的，插入`<img>`时都会有`max-width:100%`。你可以在上传完图片之后，查阅 DOM 结构看一下。
