### ISSUE TITLE
styleWithCSS问题

### ISSUE THREAD

**Issue by cxcshuaige** [wangfupeng1988/wangEditor#1439]
Command类23行中增加了 document.execCommand("styleWithCSS", null, true); 这句以后 导致 cmd.do('bold')  也用样式控制了 输出为 ` <span style="font-weight:bold"></span>`
    而且不能在config配置中找到 styleWithCSS 开启或关闭。

我暂时的解决办法是：
3.1.0版本中可暂时在create之前 写上  this.editor._useStyleWithCSS = true  来规避 styleWithCSS 使用

**Comment by wangfupeng1988** [comment]
>  导致 cmd.do('bold') 也用样式控制了 输出为 `<span style="font-weight:bold"></span>`

这样会给你打来什么问题吗？

增加`document.execCommand("styleWithCSS", null, true);`其实是为了字体、字号和颜色，让这些按照 css 的方式来表现，至今未有用户反映过增加了之后的问题。

**Comment by wangfupeng1988** [comment]
> 我暂时的解决办法是：3.1.0版本中可暂时在create之前 写上 this.editor._useStyleWithCSS = true 来规避 styleWithCSS 使用

你如果感觉有问题，可以先通过这种方式来解决。
