### ISSUE TITLE
编辑器粘贴xls处理换行问题

### ISSUE THREAD

**Issue by longFeiLi** [wangfupeng1988/wangEditor#1440]
编辑器版本：v3.1.0 
浏览器: Chrome 65.0.3325.181

**测试文件**:
[test.xlsx](https://github.com/wangfupeng1988/wangEditor/files/1874917/test.xlsx)

把文件中的内容粘贴到编辑器中会变成一行
![image](https://user-images.githubusercontent.com/10267141/38297842-414862b0-3828-11e8-9567-08cf4f40c40d.png)

**期望结果是换行显示**

建议在粘贴公共处理格式位置加上
`replace(/(\r\n|\r|\n)/g, '<br/>')`

**Comment by wangfupeng1988** [comment]
我的 mac os 没有复现你的问题，不过你提出的建议我加到源码中了，感谢反馈。下次升级发布。

```js
export function replaceHtmlSymbol(html) {
    if (html == null) {
        return ''
    }
    return html.replace(/</gm, '&lt;')
                .replace(/>/gm, '&gt;')
                .replace(/"/gm, '&quot;')
                .replace(/(\r\n|\r|\n)/g, '<br/>')
}
```
