### ISSUE TITLE
i标签结束全部写错了<i/> ???

### ISSUE THREAD

**Issue by leafiy** [wangfupeng1988/wangEditor#1441]
比如`this.$elem = $('<div class="w-e-menu"><i class="w-e-icon-paint-brush"><i/></div>')`

**Comment by wangfupeng1988** [comment]
感谢反馈，发现了，源码已经改了，随着下次发版生效。

**Comment by wangfupeng1988** [comment]
感谢反馈，发现了，源码已经改了，随着下次发版生效。
