### ISSUE TITLE
chrome浏览器下 敲回车键换行问题

### ISSUE THREAD

**Issue by Dream-wu** [wangfupeng1988/wangEditor#1443]
某行文字的父标签`p`设置的`display:flex`布局样式，在行末敲回车，只是增加了`<span><br></span>`标签，没有实现增加`<p>`标签换行。在火狐浏览器下是OK的。

**Comment by wangfupeng1988** [comment]
> 某行文字的父标签`p`设置的`display:flex`布局样式

编辑器内的`<p>`标签必须是没有样式的，不能设置`flex`。如果你有特殊需求，暂时不会受理。
