### ISSUE TITLE
<br>可不可以换成闭合的<br/>标签？？

### ISSUE THREAD

**Issue by Dream-wu** [wangfupeng1988/wangEditor#1444]
因为项目需求，需要将html段代码导成PDF格式。html中使用富文本编辑换行时会插入<br>，导出PDF时报错，因为<br>是未闭合的标签。

**Comment by wbswjc** [comment]
导出之前正则一下不行吗?

**Comment by wangfupeng1988** [comment]
自己替换一下吧，这个修改并不是大家都需要。
