### ISSUE TITLE
富文本输出框中插入表格，第一行第一列输入内容，第一行第二列，首字母无法唤起中文输入法

### ISSUE THREAD

**Issue by ylg58** [wangfupeng1988/wangEditor#1445]
react项目
1.浏览器及版本：Chrome 63.0.3239.84
2. 富文本输入框 插入5行5列的表格
3.在第一行第一列输入内容
4.光标切换至第一行第二列中 输入内容
5.首字母无法唤起中文输入法，第二个字母就能识别了
![default](https://user-images.githubusercontent.com/23647187/38466480-6b3ff90c-3b5c-11e8-9cc3-f12aac36f941.gif)

**Comment by wangfupeng1988** [comment]
是只有单元格内有这个问题吗？普通的段落输入内容时，会有这个问题？

**Comment by ylg58** [comment]
目前只发现单元格有这种问题

**Comment by wangfupeng1988** [comment]
我发现这个问题，我记录下查一下吧。不过，我预计这个问题不太好处理，因为这个现象很怪异，没道理会这样……
我先看看吧，有结论在这里回复。

**Comment by wangfupeng1988** [comment]
另外，我发现 safari 和 firefox 就没有这个问题。如果是浏览器兼容性问题，那就更加不好解决了……

**Comment by KrisBiuBiu** [comment]
chrome 版本 65.0.3325.162
我也试了一下，确实有这个问题
除了第一列的单元格，其他列的th或者td都有这个问题
但是，每一个单元格中都有一个空格，如果在空格之后输入内容就会出现这个问题，在空格之前输入内容就不会

**Comment by ylg58** [comment]
谢谢大佬回复，我自己尝试去解决，也是没找到问题原因；上周二项目上线了，这个bug项目中改成了暂不解决；感谢你的开源组件，用了好几个基于react的富文本组件；你的是易用性及兼容性最好的

**Comment by wangfupeng1988** [comment]
@ylg58 如果是纯基于 React 的编辑器，建议用 Draft.js ，facebook 出品，质量更有保证
