### ISSUE TITLE
建议实现七牛上传的功能能更优雅一点

### ISSUE THREAD

**Issue by 3kqing** [wangfupeng1988/wangEditor#1448]
建议实现七牛上传的功能能更优雅一点，之前的很多issues里面提到了如何更好的实现上传到七牛

**Comment by wangfupeng1988** [comment]
https://www.kancloud.cn/wangfupeng/wangeditor3/405041 文档中列出的代码，绝大部分都是七牛云的配置代码，和 editor 相关的没几行。

不过大家提出的问题多，肯定是因为我的文档写的不够详细或者 API 封装程度不够，我抽空看看。你如果有更好的建议，欢迎随时回复我。
