### ISSUE TITLE
图片大小修改

### ISSUE THREAD

**Issue by Ben199011** [wangfupeng1988/wangEditor#1449]
我想问一下，调整编辑器内容图片大小怎么做的，或者通过鼠标点击然后拖动图片调整大小

**Comment by KrisBiuBiu** [comment]
如果编辑器里面有图片，先点击图片，再点击图标栏里的图片按钮就可以调整大小了

**Comment by Ben199011** [comment]
@KrisBiuBiu 哪有这个功能

**Comment by KrisBiuBiu** [comment]
![Uploading 666.png…]()

**Comment by shanezhiu** [comment]
是的，还发现那里可以手动输入调整大小。

**Comment by wangfupeng1988** [comment]
> 如果编辑器里面有图片，先点击图片，再点击图标栏里的图片按钮就可以调整大小了

目前是这种方法

> 通过鼠标点击然后拖动图片调整大小

该方法还在计划中，后续可能会加上去，但是时间尚未确定。

------

wangEditor 定位为一个简洁易用的编辑器，能减少的功能尽量减少。上传或者粘贴的图片，都已经设置了`max-width=100%`，因此绝大部分情况不需要手动调整。

**Comment by IVANLEE99** [comment]
还可以

**Comment by liaozh** [comment]
我使用vue,点击图片按钮更改图片宽度为30%，但是vue绑定的数据宽度还是100%，证明点击图片按钮更改宽度没有映射到真正的数据上。这个如何解决？

**Comment by webbill** [comment]
![image](https://user-images.githubusercontent.com/2249028/59734644-d9449680-9284-11e9-9fb5-96e8b3ac1fe0.png)

对wangEditor.js进行如上修改即可，修改后效果图
![image](https://user-images.githubusercontent.com/2249028/59734671-f24d4780-9284-11e9-89bd-58b013efd4d5.png)

**Comment by nosizi** [comment]
@webbill 请问这个`tabsConfig`放在哪个API下？
