### ISSUE TITLE
textarea模式下， editor.$txt.html(data.content);不会同步更新textarea的值？

### ISSUE THREAD

**Issue by linjiaju8** [wangfupeng1988/wangEditor#145]
我使用下面的方法从服务器获取编辑器的值，并设置好，但是 textarea中仍是设定的默认值。
editor.$txt.html(data.content);

需要再调用下textarea设值方法才行。
$('#noticeEditor').val(data.content);

**Comment by wangfupeng1988** [comment]
哦，对，这是一个bug，我记录下，回头解决这个问题。感谢反馈！

**Comment by wangfupeng1988** [comment]
已经解决，下载最新版验证即可

**Comment by linjiaju8** [comment]
好响应好快啊！
