### ISSUE TITLE
修改复制的链接，会把原内容也删掉

### ISSUE THREAD

**Issue by Ben199011** [wangfupeng1988/wangEditor#1453]
![ba](https://user-images.githubusercontent.com/30291896/38712969-68fad524-3f01-11e8-90ed-9ab7495c86c9.jpg)
![af](https://user-images.githubusercontent.com/30291896/38713037-ce82ecba-3f01-11e8-9cfe-139901a81c0f.jpg)
![yr](https://user-images.githubusercontent.com/30291896/38713100-167283e6-3f02-11e8-8413-90928c2a4744.jpg)
添加和修改图片链接，能否不除去原图片啊

**Comment by wangfupeng1988** [comment]
尚不支持图片加链接。

不过这种操作确实应该提示一下，要不然用户都不知道，我记录下，待升级。
