### ISSUE TITLE
不能设置placehold属性吗?

### ISSUE THREAD

**Issue by kaykie** [wangfupeng1988/wangEditor#1455]
不能设置placehold属性吗? 我想设置一下placehold,不知道怎么弄!

**Comment by hold-baby** [comment]
https://github.com/wangfupeng1988/wangEditor/pull/1391

你可以拉这个pr 也可以自己改

**Comment by kaykie** [comment]
我也自己改写了 差不多也是用这个逻辑

在 2018-04-19 15:48:51，"hold-baby" <notifications@github.com> 写道：


#1391

你可以拉这个pr 也可以自己改
