### ISSUE TITLE
撤销跟回退两个功能的问题

### ISSUE THREAD

**Issue by webPpei** [wangfupeng1988/wangEditor#1456]
同一个页面多个editor的时候，其他的功能暂没发现功能间相互影响的问题，但是撤销跟回退两个功能就会相互影响。

**Comment by wangfupeng1988** [comment]
这个问题已知，算是编辑器核心函数`document.execCommand`的一个 bug （或者说考虑不全面），已列入修改计划中，不过由于个人精力问题，没法近期解决。因为，要解决这个问题，需要把撤销功能重写，还是比较麻烦的。

**Comment by BusyHe** [comment]
同样的问题，不知道有没有解决
