### ISSUE TITLE
wangedit 在mac电脑中safari 报告出错的问题。

### ISSUE THREAD

**Issue by WhiteSnowGirl** [wangfupeng1988/wangEditor#1457]
![image](https://user-images.githubusercontent.com/12612585/38924983-ef3c9086-4330-11e8-950e-a6979a3e95d6.png)
![image](https://user-images.githubusercontent.com/12612585/38924993-f545509e-4330-11e8-8194-20b77a3f93b7.png)
输入文字或者空格就会这样？

**Comment by wangfupeng1988** [comment]
试一下官网是不是也这样，我试着没啥问题。
如果官网没问题的话，就得查一下你自己的项目环境，哪里导致了这个问题。
