### ISSUE TITLE
关于富文本默认高度的问题

### ISSUE THREAD

**Issue by xiuxiumomo** [wangfupeng1988/wangEditor#1458]
找打了，源码里面
$textContainerElem.css('border', '1px solid #ccc').css('border-top', 'none').css('height', '100%');
把css height 300改掉就ok了。

**Comment by wangfupeng1988** [comment]
这样做也可以，不过还是推荐使用 https://www.kancloud.cn/wangfupeng/wangeditor3/335771 这种方式
