### ISSUE TITLE
是否可以份额装随form表单提交？

### ISSUE THREAD

**Issue by HoldMe** [wangfupeng1988/wangEditor#1459]
开发中基于hibernate，jsp页面中经常以表单形式提交，是否可以像ueditor一样封装成标签通过命名name随form表单提交实例化成对象。

**Comment by wangfupeng1988** [comment]
可以查一下已经关闭的 issue ，虽然 v3 不再支持 textarea ，但是可以通过 onchange 将编辑器的内容实时同步到 textarea 中，然后通过 form 提交。

**Comment by HoldMe** [comment]
👌，相当于在提交前存储到隐藏容器中随form表单提交

发自我的 iPhone
