### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by zzz999** [wangfupeng1988/wangEditor#146]
1、做成jquery插件，初始化时会少很多个步骤，可以全局统一配置一份config变量
2、表情包可以不在默认菜单里面，表情包的路径无法配置会比较忧伤
3、貌似很多富文本编辑器都不支持背景图片的设置，希望支持一下

**Comment by wangfupeng1988** [comment]
> 1、做成jquery插件，初始化时会少很多个步骤，可以全局统一配置一份config变量

1.x版本都是jquery插件形式，不过配置过多时，会导致代码复杂度提高，所以2.0之后修改成了现在的方式。各有各的好处和坏处，好在两者都不是很复杂，不会有太大影响。

> 2、表情包可以不在默认菜单里面，表情包的路径无法配置会比较忧伤

菜单可以自定义配置，不需要的可以配置隐藏。目前支持表情图标的配置，看文档。但是目前还不支持标准的表情包，不过这个已经加入开发计划中，会根据优先级增加。

> 3、貌似很多富文本编辑器都不支持背景图片的设置，希望支持一下

你说的背景，是不是类似QQ邮件中的信封背景的方式？这个你有兴趣，可以看看文档中的插件开发，自己自定义一个菜单。我如果要开发，也会是扩展一个菜单。
