### ISSUE TITLE
我在Myeclipse里面导入这个项目,但是Myeclipse不支持项目里面的一些js的新语法，报了很多错误？主要在const 和 => 代码附近

### ISSUE THREAD

**Issue by maodunUi** [wangfupeng1988/wangEditor#1460]
我在Myeclipse里面导入这个项目,但是Myeclipse不支持项目里面的一些js的新语法，报了很多错误？主要在const 和 => 代码附近，该怎么解决呢？谢谢！

**Comment by shanezhiu** [comment]
https://www.genuitec.com/tech/web-scripting/

**Comment by wangfupeng1988** [comment]
使用编译之后的产出代码，不会有`const`和`=>`。
