### ISSUE TITLE
没有<p>的情况下，文字排列很紧密

### ISSUE THREAD

**Issue by nierongcheng** [wangfupeng1988/wangEditor#1466]
![wx20180423-180418](https://user-images.githubusercontent.com/3412717/39120423-f7161efa-4720-11e8-80da-9228608971a4.png)
![wx20180423-180435](https://user-images.githubusercontent.com/3412717/39120430-ff586262-4720-11e8-83f6-8a399fd571f4.png)

**Comment by wangfupeng1988** [comment]
正常情况下，不允许编辑内容直接暴露，而是必须用`<p>`包裹。估计是你为编辑器赋值的时候，直接这样赋值了，应该每个段落都用`<p>`包裹才行。
