### ISSUE TITLE
关于wordpress中使用wangeditor

### ISSUE THREAD

**Issue by Violet-VE** [wangfupeng1988/wangEditor#1467]
在使用了国人开发的第三方baidueditor和WordPress自带的编辑器，最后发现还是wangeditor最优雅完美。但却有两个问题我不知是技术原因还是何原因没有做。
1：不能直接编辑源代码，这意味着有些依靠源代码写的功能无法实现。
2：不知道在WordPress或者其他的blog中如何使用

**Comment by wangfupeng1988** [comment]
> 1：不能直接编辑源代码，这意味着有些依靠源代码写的功能无法实现。

自身不支持，有需要可以自己进行二次开发。编辑器提供了获取 html 和设置 html 的 API ，是可以二次开发的。

> 2: 不知道在WordPress或者其他的blog中如何使用

文档中尚未完善该操作，可以去 QQ 群（官网有号码）和大家一起讨论

**Comment by Violet-VE** [comment]
好的
