### ISSUE TITLE
关于富文本编辑器列表的显示问题

### ISSUE THREAD

**Issue by Dendroaspis24** [wangfupeng1988/wangEditor#1468]
在编辑器中增加了一段有序列表或者无序列表，发现序列号的显示有点小问题，如图
![image](https://user-images.githubusercontent.com/35287446/39162047-2ad70cd8-47a6-11e8-8ba8-889e2d7f1ca5.png) 希望能帮忙解决一下!

**Comment by wangfupeng1988** [comment]
CSS 冲突，将`.w-e-text ul li`和`.w-e-text ol li`的样式重写一下就好了。
