### ISSUE TITLE
编辑器如何自动上传粘贴过来的网页里的图片

### ISSUE THREAD

**Issue by KrisBiuBiu** [wangfupeng1988/wangEditor#1469]
求大神解答：为什么粘贴html的时候，怎样获取里面的图片文件？

**Comment by shanezhiu** [comment]
使用js标记图片，上传到服务器脚本程序（假设是PHP），使用curl下载（推荐使用guzzle/http)，配置一下图片路径，将你自己处理后的图片地址返回到前台，替换标记的图片。so,完成。

**Comment by KrisBiuBiu** [comment]
一目了然，感谢
