### ISSUE TITLE
复制粘贴会出现多余的换行

### ISSUE THREAD

**Issue by linkdesu** [wangfupeng1988/wangEditor#147]
从 wangeditor 中复制文本，然后重新粘贴回同一个或另一个 wangeditor 时。文本内容会按照 。 号为分割自动分割为 n 行，经测试 demo 页的编辑器也有这问题。

重现这个问题时请注意，如果从其他地方复制文本粘贴至 wangeditor 不会出现这种问题。所以必须是从 wangeditor 中复制文本，然后又粘贴回去。

再次感谢王先生的为此编辑器付出的努力！:+1:

**Comment by wangfupeng1988** [comment]
好，我去官网demo看到这个bug了，感谢你的反馈，我会尽快fix，fixed之后会在此回复。

**Comment by wangfupeng1988** [comment]
已经修改，下载v2.0.10

**Comment by linkdesu** [comment]
如此效率！谢谢王先生！:+1:
