### ISSUE TITLE
初始化编辑器，编辑器一直处于focus状态，如何去掉？

### ISSUE THREAD

**Issue by tanxuewei** [wangfupeng1988/wangEditor#1470]

**Comment by wangfupeng1988** [comment]
可以搜索一下之前关闭的 issue ，有人问过这个问题，记得是删除一行代码就行了。

目前只能自己手动改，还不支持通过配置项控制。

**Comment by tjsome** [comment]
光标默认不显示有解决方案吗

**Comment by tjsome** [comment]
我也没有找到，尴尬，百度一些都没有解决，直接用blur这个方法是会报错的

**Comment by wangfupeng1988** [comment]
注释掉这一行 https://github.com/wangfupeng1988/wangEditor/blob/master/release/wangEditor.js#L4550

**Comment by wangfupeng1988** [comment]
我看这个问题有好多人提过了，我记录下，下次升级时加一个配置项。

如果你着急用的话，就按照我上面说的方式改。

**Comment by tanxuewei** [comment]
@wangfupeng1988 好的，辛苦啦

**Comment by tjsome** [comment]
多谢，已经好了

**Comment by dreamsye** [comment]
vue 引入的wangEditor 没有那一行代码 那怎么解决呢
