### ISSUE TITLE
wangEditor 在设置editor.txt.html(content)时候，content的length有时候会小于editor.txt.html().length

### ISSUE THREAD

**Issue by RichieChoo** [wangfupeng1988/wangEditor#1475]
官网打不开了。。

**Comment by RichieChoo** [comment]
wangEditor.js:62 第八届北京国际电影节电影市场将于4月18日至4月20日在北京国际饭店举办。作为电影市场的重要版块之一，今年特约活动招募得到诸多业内机构的积极响应。本届电影市场特约活动最终敲定30场形式多样、内容丰富的活动，数量再创新高。今年的特约活动版块将会继续参照国际著名电影节标准，在满足国内外电影机构及公司对自身品牌、业务及项目宣传需求的同时，积极整合行业资源，提供涵盖项目路演、企业发布、沙龙活动在内的多元化解决方案，为各公司的深度市场开发及合作提供平台。从内容上看，本届电影市场特约活动紧贴产业热点，主题丰富多元，话题不仅涵盖IP研发及衍生、影视工业化、数据洞察等近年持续热门话题，也有网络影视发展、中国电影“走出去”、国际影视合作、影视金融、特效技术等议题，呈现出新的讨论方向。活动安排如下（最终安排以当天活动实际情况为准）： <img src='http://image.huadongmedia.com/plat/content/image/url/20180418/097b1bd28bd24584aa5152f2f3e4672c.jpg'>

**Comment by RichieChoo** [comment]
wangEditor.js:62 第八届北京国际电影节电影市场将于4月18日至4月20日在北京国际饭店举办。作为电影市场的重要版块之一，今年特约活动招募得到诸多业内机构的积极响应。本届电影市场特约活动最终敲定30场形式多样、内容丰富的活动，数量再创新高。今年的特约活动版块将会继续参照国际著名电影节标准，在满足国内外电影机构及公司对自身品牌、业务及项目宣传需求的同时，积极整合行业资源，提供涵盖项目路演、企业发布、沙龙活动在内的多元化解决方案，为各公司的深度市场开发及合作提供平台。从内容上看，本届电影市场特约活动紧贴产业热点，主题丰富多元，话题不仅涵盖IP研发及衍生、影视工业化、数据洞察等近年持续热门话题，也有网络影视发展、中国电影“走出去”、国际影视合作、影视金融、特效技术等议题，呈现出新的讨论方向。活动安排如下（最终安排以当天活动实际情况为准）： 测试

**Comment by RichieChoo** [comment]
editor读取后变成

**Comment by wangfupeng1988** [comment]
> 官网打不开了。。

可能被墙

> wangEditor 在设置editor.txt.html(content)时候，content的length有时候会小于editor.txt.html().length

给我一个能简单复现的例子。

**Comment by RichieChoo** [comment]
第八届北京国际电影节电影市场将于4月18日至4月20日在北京国际饭店举办。作为电影市场的重要版块之一，今年特约活动招募得到诸多业内机构的积极响应。本届电影市场特约活动最终敲定30场形式多样、内容丰富的活动，数量再创新高。今年的特约活动版块将会继续参照国际著名电影节标准，在满足国内外电影机构及公司对自身品牌、业务及项目宣传需求的同时，积极整合行业资源，提供涵盖项目路演、企业发布、沙龙活动在内的多元化解决方案，为各公司的深度市场开发及合作提供平台。从内容上看，本届电影市场特约活动紧贴产业热点，主题丰富多元，话题不仅涵盖IP研发及衍生、影视工业化、数据洞察等近年持续热门话题，也有网络影视发展、中国电影“走出去”、国际影视合作、影视金融、特效技术等议题，呈现出新的讨论方向。活动安排如下（最终安排以当天活动实际情况为准）：&nbsp;测试

**Comment by RichieChoo** [comment]
它会把测试前面的空格变为&nbsp;

**Comment by RichieChoo** [comment]
它会把测试前的空格变为 nbsp;

**Comment by RichieChoo** [comment]
& 和 nbsp;

**Comment by RichieChoo** [comment]
一起打就变成空格了

**Comment by RichieChoo** [comment]
第八届北京国际电影节电影市场将于4月18日至4月20日在北京国际饭店举办。作为电影市场的重要版块之一，今年特约活动招募得到诸多业内机构的积极响应。本届电影市场特约活动最终敲定30场形式多样、内容丰富的活动，数量再创新高。今年的特约活动版块将会继续参照国际著名电影节标准，在满足国内外电影机构及公司对自身品牌、业务及项目宣传需求的同时，积极整合行业资源，提供涵盖项目路演、企业发布、沙龙活动在内的多元化解决方案，为各公司的深度市场开发及合作提供平台。从内容上看，本届电影市场特约活动紧贴产业热点，主题丰富多元，话题不仅涵盖IP研发及衍生、影视工业化、数据洞察等近年持续热门话题，也有网络影视发展、中国电影“走出去”、国际影视合作、影视金融、特效技术等议题，呈现出新的讨论方向。活动安排如下（最终安排以当天活动实际情况为准）： 这个之前的空格会改变

**Comment by RichieChoo** [comment]
会变成 & nbsp;

**Comment by RichieChoo** [comment]
请问能重现么

**Comment by RichieChoo** [comment]
问题已解决（采用别的逻辑判断），谢谢 @wangfupeng1988

**Comment by RichieChoo** [comment]
如果有要根据内容长度做限制编辑保存的操作的，请使用editor.txt.text().length获取长度，,editor.txt.html()删除换行会加入一些转义的字符使长度增加
