### ISSUE TITLE
对编辑器内容添加事件支不支持 ？

### ISSUE THREAD

**Issue by aiqin-bao** [wangfupeng1988/wangEditor#1477]
example： 上传图片之后对图片增加事件 ～～～

 -  jq是可以获取到dom节点的  但是添加事件是不可以的～～～  是不是编辑器对事件机制做了限制 ？？？

**Comment by wangfupeng1988** [comment]
编辑器应该没有做这种限制，不过你说的这种需求，暂时不会考虑支持

**Comment by aiqin-bao** [comment]
但是DOM的节点是可以获取到的 但是事件添加不上去 ？  难道不是编辑器做的限制吗 ？ 我这边不通过编辑器添加的内容是可以添加事件的。 但是通过编辑器添加的内容则添加不了事件？ 。这是什么原因 ？ 。能解释一下吗 ？
