### ISSUE TITLE
光标定位编辑器最后一行,回车无法生成新行,会回弹到上一行

### ISSUE THREAD

**Issue by wjqh** [wangfupeng1988/wangEditor#1479]
在 vue 中使用并通过 npm 安装初始化的,在开始编辑的时候出现问题,光标定位编辑器最后一行,回车无法生成新行,会回弹到上一行.

**Comment by wangfupeng1988** [comment]
这个问题很怪异，你要先确认一下是否和你的项目环境有关系。你可以运行文档中 vue 的示例，看下能否复现 https://www.kancloud.cn/wangfupeng/wangeditor3/335789

**Comment by wjqh** [comment]
在文本的最后一行拼接上<br>之后解决了
