### ISSUE TITLE
编辑器是兼容到ie10吗？可是这个demo在ie10中有问题，基本上选项都是有问题的。在safari中更严重

### ISSUE THREAD

**Issue by ccdida** [wangfupeng1988/wangEditor#1480]
这是safari浏览器的信息。ie是ie10
5.0 (Windows NT 6.1; WOW64) AppleWebKit/534.57.2 (KHTML, like Gecko) Version/5.1.7 Safari/534.57.2

ie中，选项都能出来，但是不生效，比如图片也能上传，但是并不会出现在编辑框中。safari中，子选项出不来。我是直接用的demo。谢谢~~

**Comment by ccdida** [comment]
document.execCommand('styleWithCSS',null,true); 这一句ie中报参数错误。

**Comment by wangfupeng1988** [comment]
> safari中，子选项出不来

不明白啥意思

> `document.execCommand('styleWithCSS',null,true);` 这一句ie中报参数错误。

你可以搜到这句话，暂时先删除掉

**Comment by wangfupeng1988** [comment]
无回复暂时关闭
