### ISSUE TITLE
添加图片

### ISSUE THREAD

**Issue by RunningOnMyWay** [wangfupeng1988/wangEditor#1483]
添加图片时是否可以给出一个与后台服务器交互的设置，将图片上传至指定的服务器(或者素材库等等)，而对应的服务器返回一个图片路径，然后在富文本中写入的src是一个图片路径呢？视频也同样的。

**Comment by wangfupeng1988** [comment]
没看明白

**Comment by RunningOnMyWay** [comment]
http://ueditor.baidu.com/website/onlinedemo.html  比如这个的编辑器，添加图片后，富文本中html代码src使用的是图片路径，我们这个能不能添加类似的功能，至于上传图片的http服务器url(使用该插件的个人服务器)之类的内容可以通过js中配置的方式。

**Comment by RunningOnMyWay** [comment]
现在的上传图片是上传之后代码是：
`<img src="data:image/png;base64sadsadsadasd" style="max-width:100%;">`
是否可以修改成为：
`<img src="/server/ueditor/upload/image/demo.jpg" style="max-width:100%;">` 
当然 网络图片应该是这个样子没错；
因为我在做项目的过程中发现，有的时候用户上传的图片指不定是多大的，有的十几M有的几百K都有可能，二十几M的在转为base64存在富文本中，太大了。

**Comment by KrisBiuBiu** [comment]
你存的是base64，用的时候肯定也是base64了。
可以不存base64，存图片文件也可以啊
或者用Buffer和writeFile将base64转为图片文件存起来
我也有上传图片过大的情况，图片太大的话都是用imageMagick进行裁剪、压缩。

**Comment by GeorgeCodesigner** [comment]
以<script type="text/javascript" src="wangEditor.js"></script>的方式引入，本地webstorm直接打开页面，复制粘贴word里面的图片不成功是什么情况？麻烦大神讲解下。

**Comment by wangfupeng1988** [comment]
@GeorgeCodesigner 重新起提交一个问题吧

**Comment by wangfupeng1988** [comment]
@RunningOnMyWay 你的疑问，你去看文档就好了，就是将图片上传到服务器，而不是用 base64 编码存储，文档中都有
