### ISSUE TITLE
希望能自己设置某些标签不可编辑

### ISSUE THREAD

**Issue by linzhaoyang** [wangfupeng1988/wangEditor#1486]
在公司项目中有需求需要插入的标签不能被编辑，如果要删除的时候，按删除键需要将新插入的标签删掉而不是一个个字删除。我用了contentEditable属性去设置false，让他不可编辑，在插入新标签后输入文字，第一次输入会无法输入中文，光标也会一直显示在最后面，最近因为这个搞得焦头烂额，这个是微博引用话题或者@某个人会用到的功能。

**Comment by linzhaoyang** [comment]
在公司项目中有需求需要插入的标签不能被编辑，如果要删除的时候，按删除键需要将新插入的标签删掉而不是一个个字删除。我用了contentEditable属性去设置false，让他不可编辑，在插入新标签后输入文字，第一次输入会无法输入中文，光标也会一直显示在最后面，最近因为这个搞得焦头烂额，这个是微博引用话题或者@某个人会用到的功能。

**Comment by wangfupeng1988** [comment]
> 需要插入的标签不能被编辑

不要禁用`contentEditable`，而是给这个标签设置一个特殊的属性，然后视图在光标遇到该标签时，对 keyup 等事件进行`event.preventDefault()`操作。

**Comment by wangfupeng1988** [comment]
无回复暂时关闭
