### ISSUE TITLE
清空富文本，在获取富文本，会获得<p><br></p>这样的一个字段

### ISSUE THREAD

**Issue by zl-qiuhuimin** [wangfupeng1988/wangEditor#1488]
如题， 在我清空了之后 再获取值，就会获得这样一个字符串， 请问应该如何去除这个？

**Comment by dandelion1000** [comment]
我也想问这个问题，不过手动给他置空应该可以，手动设置""

**Comment by wangfupeng1988** [comment]
编辑内容为空的时候，默认会有`<p><br></p>`。如果完全为空，那么再次输入就会有问题，因此必须有`<p><br></p>`才行。
