### ISSUE TITLE
如果只想用到图片缩放、文字混排功能，不需要任何其他文字样式修改、插入等功能，该如何实现？

### ISSUE THREAD

**Issue by lurenhtml5** [wangfupeng1988/wangEditor#1489]
也就是不需要咱们的编辑器工具栏，只需要图文混排的功能，上传图片的功能按钮，由第三方的div点击来触发，请问如何实现，希望得到帮助，谢谢。

**Comment by wangfupeng1988** [comment]
感觉你这个需求，和 wangEditor 满足的需求，不是很对应。

不过如果你想要这么做的话，看下 https://www.kancloud.cn/wangfupeng/wangeditor3/404586 提供的 API 是否能满足你吧
