### ISSUE TITLE
图片复制粘贴问题

### ISSUE THREAD

**Issue by GeorgeCodesigner** [wangfupeng1988/wangEditor#1491]
方式一：以`<script type="text/javascript" src="wangEditor.js"></script>`的方式引入，用 webstorm 直接打开页面，或者方式二：react方式npm start启动，将word里面的图片复制粘贴到文本框中，没有反应是什么情况？

**Comment by wangfupeng1988** [comment]
> 将word里面的图片复制粘贴到文本框中

本来就不支持从 word 中复制、粘贴图片

**Comment by GeorgeCodesigner** [comment]
为什么官网的demo里面可以？

**Comment by NineSwordsMonster** [comment]
I got the same problem, and I checked the official demo, it uses `base64` to store the image.

**Comment by NineSwordsMonster** [comment]
> > 将word里面的图片复制粘贴到文本框中
> 
> 本来就不支持从 word 中复制、粘贴图片

windows do not  support, but works  on mac

**Comment by JoMartinezZhu** [comment]
> 为什么官网的demo里面可以？

我也遇到了，你解决了嘛？

**Comment by NineSwordsMonster** [comment]
@JoMartinezZhu I convert `doc` to `docx`, and it works

**Comment by Terrency** [comment]
我看到官方demo里面有一行代码，可以解决这个问题，哈哈哈哈
`editor.config.uploadImgShowBase64 = true`

**Comment by Terrency** [comment]
word里面粘贴图片是不行的，单独的图片粘贴是可以的，亲测

**Comment by wangfupeng1988** [comment]
@Terrency 复制 word 内容（有图有文）粘贴，目前是不支持图片的，无论 v4 v5。
V4 不会再功能升级了。V5 后续会逐步支持，但需要一些时间。

**Comment by Terrency** [comment]
> 

多谢回复， 我看其他的编辑器好像有类似功能，我试试移植一下，我上次用了v5，感觉还是有一些问题，就退回到了v4.

**Comment by wangfupeng1988** [comment]
@Terrency 用 v5 如果感觉哪里不好用，可以提交issue ，高优问题我会紧急修复的。良心建议不要退回到 v4 ，这倒不是我自己为 v5 打广告，而是你要想一下：如果 v4 各方面都 OK ，我为啥要花费 1 年的精力去重构 v5？成本很高的

**Comment by Terrency** [comment]
> 为什么官网的demo里面可以？

v4版本提供了一个复制后处理的入口pasteTextHandle，开源项目 paste-from-word能够处理图文复制，我改造了一下结合两块功能实现了word的混合图文复制到编辑器中，目前采用的是base64格式图片嵌入，未结合上传图片，代码如下，仅供参考：
package.json
`
"paste-from-word": "^1.0.3",
`
editor EventListener 和后处理
`
import pasteFromWord from "paste-from-word";
const paster = new pasteFromWord();
let imgTags;
let hexImages;
let newSrcValues;
editor.config.pasteTextHandle = function(pasteStr){
      for (let i = 0; i < imgTags.length; i++) {
        // Replace only `file` urls of images ( shapes get newSrcValue with null ).
        if (imgTags[i].indexOf("file://") === 0) {
          if (!newSrcValues[i]) {
            console.error("处理后的图片中未找到第" + (i + 1) + "张图片", {
              type: hexImages[i].type,
              index: i,
            });
            continue;
          }
          const escapedPath = imgTags[i].replace(/\\/g, "\\\\");
          const imgRegex = new RegExp("(<img [^>]*src=[\"']?)" + escapedPath);

          pasteStr = pasteStr.replace(imgRegex, "$1" + newSrcValues[i]);
        }
      }
      return pasteStr;
};
//捕获模式，需要优先于wangeditor的的粘贴事件
editor.$textElem.elems[0].addEventListener(
      "paste",
      (pasteEvent) => {
        console.log("手动监听处理paste事件");
        const mswordHtml = paster.stripHtml(
          paster.getClipboardData(pasteEvent.clipboardData, "text/html")
        );
        const rtf = pasteEvent.clipboardData.getData("text/rtf");
        imgTags = paster.extractTagsFromHtml(mswordHtml);
        hexImages = paster.extractFromRtf(rtf);
        newSrcValues = hexImages.map((img) => paster.createSrcWithBase64(img));
      },
      true
    );
`
顺便说下，感谢作者。

**Comment by 200684632** [comment]
@Terrency 
你好我使用您提供的这个方法
`const rtf = pasteEvent.clipboardData.getData("text/rtf");`
获取的是空数据，在后续处理中报错了，能请教下是什么问题码

**Comment by Terrency** [comment]
@200684632 
pasteEvent是浏览器级别下发的事件，理论上不会有变化；
这里获取格式为rtf，要求从word中复制图文混排的内容粘贴才能工作，非图文混排都会获取不到数据。
