### ISSUE TITLE
通过editor.txt.html(data)设置内容时如果包含图片（即img标签），显示不出来

### ISSUE THREAD

**Issue by an-ya** [wangfupeng1988/wangEditor#1492]
如这个data数据是
```
<p>dsada</p>
<p><img src="/upload/article/springMVC/201805021831/img/dui.png" style="max-width:100%;" /></p>
```
这个图片显示不出来，我直接在地址栏输入http:localhost:8080/upload/article/springMVC/201805021831/img/dui.png可以看到图片

为什么显示不出来？

**Comment by wangfupeng1988** [comment]
第一，看下 DOM 结构中 `<img>` 是否已经在了？第二，看下网络请求是否发送了这个图片的请求，以及返回的是什么？

**Comment by an-ya** [comment]
那个实在不好意思，我找原因了，是因为我上传图片的时候，图片已经存在但是立即访问不到会报404，要等个5秒才访问得到，跟文本编辑器没关系。
