### ISSUE TITLE
如何去掉编辑器默认的聚焦事件，在火狐下面默认聚焦的时候，跳转页面的时候滚动条会自动到光标聚焦的地方，谷歌就不会

### ISSUE THREAD

**Issue by tjsome** [wangfupeng1988/wangEditor#1494]

**Comment by wangfupeng1988** [comment]
参考 https://github.com/wangfupeng1988/wangEditor/issues/1470#issuecomment-386202477 我最后的回复

**Comment by wangfupeng1988** [comment]
我看这个问题有好多人提过了，我记录下，下次升级时加一个配置项。

如果你着急用的话，就按照我上面说的方式改。

**Comment by butterfly771** [comment]
配置项加过了吗
