### ISSUE TITLE
建议增加一条粘贴时过滤inline的script

### ISSUE THREAD

**Issue by leafiy** [wangfupeng1988/wangEditor#1499]
比如
`pasteHtml = pasteHtml.replace(/\s?(onclick|onmouseover)=('|").*?('|")/igm, '')`

**Comment by wangfupeng1988** [comment]
感谢反馈。粘贴是的过滤，后期会有一个重构，将无用的属性全部删除掉。

如果你现在急用，可以在源码简单修改一下，加上你所说的这一句。
