### ISSUE TITLE
上传图片的返回值应该是什么格式？

### ISSUE THREAD

**Issue by starock** [wangfupeng1988/wangEditor#15]
话说，作者的用意很好还特意录了上传图片的视频。可是客观的说这段演示好啰嗦，而且关键的地方讲的让明白人也糊涂了。

其实就两点：
1、JS里配置好上传的API路径；
2、API给上传窗口返回值。

我现在图片上传是成功的，但是不论我怎么返回值，上传的这个窗口都没有反应。应该是上传成功后自动插入到富文本里就OK了，上传失败就提示一个错误信息。

现在就是不清楚后台API返回值该怎么写？

例子里为什么是一段HTML？这太麻烦了。一般情况下API不会这样返回的。API的返回值一般都很简练，比如成功返回1，失败-1或者0等等。

**Comment by starock** [comment]
搞定了，真费劲。

首先，后台上传图片的API，返回值一定要是这个形式：
return "<iframe src='http://127.0.0.1:8080/CMS/plugs/wangEditor/assist.html#ok|/cms/upload/partner/"+fileName+"'></iframe>";


有个很重要的文件是必须的，下载源码后找到DEMO这个文件夹，里面有个文件wangEditor_uploadImg_assist.html。这个文件是必须的，不然上传图片后无法关闭上传窗口也无法把上传好的图片插入到编辑器中。

还是想说声，OH SHIT！ :D

**Comment by wangfupeng1988** [comment]
第一， 我之所以讲的那么“啰嗦”，是为了应对大多数人的需求，因为我发现QQ群里的有部分人，基础知识不大好。如果你感觉这样讲很啰嗦，那么demo中有简洁的文字说明，重点就在那里写着。啰嗦的也有，简洁的也有，看哪个都行。
第二，不借助任何第三方插件而实现图片跨域上传，API只返回一个1或者0，是不能实现的。我作为软件的作者，当然最想简单的处理，让用户体验好，但是没办法。如果你有好的解决方案，不妨分享一下，我将非常感谢。
第三，当你搞定问题之后，所谓的“费劲”：返回iframe的html、wangEditor_uploadImg_assist.html页面……这两点，我不管是demo的简洁文档中，还是视频介绍中，都非常清晰而且非常重点的讲解到。我不知道你第一次没成功是因为你没看过文档，还是因为你没看懂文档。

有一些用户体验的建议是好的，例如API只返回1或0。但是，大家也都是技术人员，需要考虑这种场景是否容易实现。否则只能是退而求其次了。

**Comment by DyungWang** [comment]
非常感谢

**Comment by wangfupeng1988** [comment]
当前改版的编辑器，上传图片做了很多调整，情况好了很多。
http://www.wangeditor.com/wangEditor/docs/index.html#upload-img
