### ISSUE TITLE
使用最新版编辑器发现的几个问题

### ISSUE THREAD

**Issue by ArcRain** [wangfupeng1988/wangEditor#150]
1）复制或者剪切编辑器的内容，再次粘贴会有双份内容。重现步骤：打开编辑器官网，ctrl+a -> ctrl+x -> ctrl+v；
2）chrome浏览器无法粘贴类型为text/plain的纯文本内容。重现方法：chrome浏览器打开编辑器官网，复制地址栏的地址文本，无法粘贴到编辑器内；
3）调用clear方法之后，再次输入的内容在p标签外面。重现方法：输入一段文本，异步清空调用clear()方法，再次输入时，内容在p标签外面。
一个重构的建议：建议源代码里所有有关清空编辑器的地方，都使用统一的clear方法，这样避免硬编码带来的不一致问题。
感谢作者的辛勤付出~谢谢~

**Comment by wangfupeng1988** [comment]
这贴的问题我已经修复，可下载最新版本。

clear的问题，我继续跟踪

**Comment by wangfupeng1988** [comment]
clear的问题，下一个发布版本将这样修改。
