### ISSUE TITLE
上传图片弹出上传图片失败，查看后台已经上传了图片，原谅我文档看不明白，找不出原因。

### ISSUE THREAD

**Issue by 13820962382** [wangfupeng1988/wangEditor#1500]
弹出显示上传失败：
![_20180504183715](https://user-images.githubusercontent.com/25764845/39624126-b6dfaa56-4fca-11e8-86cf-241c84a90c02.png)
控制台警告说：主线程上的同步XMLHtRPRQuesty被禁止，
![_20180504183800](https://user-images.githubusercontent.com/25764845/39624153-cc1292da-4fca-11e8-8537-95ce9e2d8131.png)

js代码
![_20180504183420](https://user-images.githubusercontent.com/25764845/39624233-17128cae-4fcb-11e8-86cd-23aeb0f264de.png)
后台已经上传图片并打印出了json数据：
![_20180504183504](https://user-images.githubusercontent.com/25764845/39624304-65234cd0-4fcb-11e8-8ba7-be14b873afd2.png)

**Comment by 13820962382** [comment]
已经解决，犯了个小错误，使用监听函数查看了result返回的数据格式是html而不是json。

**Comment by Zeus-Iqd** [comment]
我也遇到了这个问题。

**Comment by SANEBEN** [comment]
我也遇到了这个问题，看来答主的描述瞬间懂了，哈哈哈哈，十分感谢 @13820962382
