### ISSUE TITLE
关于wangeditor与php连用,文本编辑器中上传文件出现403错误问题

### ISSUE THREAD

**Issue by xianglidiannao** [wangfupeng1988/wangEditor#1503]
在脚本中加入editor.customConfig.uploadImgServer = 'upload',点击上传图片,出现了403错误

wangEditor.js:4304 GET http://localhost/editor/upload/ 403 (Forbidden)
uploadImg @ wangEditor.js:4304
fn @ wangEditor.js:2784
(anonymous) @ wangEditor.js:1277

请问如何调试和解决

**Comment by xianglidiannao** [comment]
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="wangEditor.min.css" rel="stylesheet" type="text/css">
<title>创建第一个文本编辑器</title>
    <script type="text/javascript" src="jquery.min.js"></script>
<script type="text/javascript" src="wangEditor.js"></script>
</head>

<body>

<form id="form1" action="1.php" method="post">
<div id="editor">
<div id="div1">
<p>这是我的第一个文本编辑器</p>
</div>
</div>
<input type="hidden" name="text1" id="text1" value="" />

<img id="submit1" src="1.jpg" style="width:100px; height:17px;"/>
    </form>



<script type="text/javascript">
        var E = window.wangEditor
         var editor = new E('#editor')
       // 或者  var editor = new E( document.getElementById('editor') )
		 editor.customConfig.menus = [
      'head',  // 标题
      'bold',  // 粗体
      'fontSize',  // 字号
      'fontName',  // 字体
      'italic',  // 斜体
      'underline',  // 下划线
    'strikeThrough',  // 删除线
    'foreColor',  // 文字颜色
    'backColor',  // 背景颜色
    'link',  // 插入链接
    'list',  // 列表
    'justify',  // 对齐方式
    'quote',  // 引用
    'emoticon',  // 表情
    'image',  // 插入图片
    'code',  // 插入代码
    'undo',  // 撤销
    'redo'  // 重复
    ]
	
	
	editor.customConfig.uploadImgServer = 'upload'
	editor.customConfig.uploadImgMaxSize = 3 * 1024 * 1024
	editor.customConfig.uploadImgMaxLength = 5
	editor.customConfig.uploadFileName = 'myFileName'
	editor.customConfig.showLinkImg = false
	
        editor.create()
		
		
    $("#submit1").click(function () {
        $("#text1").val($("#div1").html()) ;
		$("#form1").submit();
    });


</script>
    
</body>
</html>

**Comment by wangfupeng1988** [comment]
403 是服务器端权限问题，跟编辑器没有关系。你抛开编辑器，自己做一个文件上传，也会有 403 错误。

**Comment by momokanni** [comment]
我是一个后台，我都能正常使用，问个问题过过脑子，基础不牢固，还写个屁呀，没办法看见傻d问题，就是容易暴脾气
