### ISSUE TITLE
大神 可不可以在下个版本 加个一个功能按钮 可以显示HTML代码

### ISSUE THREAD

**Issue by Winphred** [wangfupeng1988/wangEditor#1504]
大神 可不可以在下个版本 加个一个功能按钮 可以显示HTML代码

**Comment by nikolausliu** [comment]
好像2.x版本是有这个功能的，看3.x文档的默认菜单配置里貌似没有这个菜单了，不知道为什么要把这个功能移除

**Comment by wangfupeng1988** [comment]
因为绝大部分用户都不需要这个功能。

如果你真的需要，可以自己开发，知道了如何获取 html 、如何设置 html ，开发这个功能不麻烦。
