### ISSUE TITLE
移动端点击有链接图片时，会先显示一个打开链接的toolbar

### ISSUE THREAD

**Issue by nikolausliu** [wangfupeng1988/wangEditor#1505]
首先，为了避免误解，说明下：用的不是wangEditor-mobile,就是wangEditor。版本用的2.x，没有升级。

场景：在手机上用编辑器做展示文章用，禁用了编辑功能。但是在手机上点击带有链接的图片的时候，不是直接跳转，而是会先展示一个"打开链接"4个字的toolbar,点击这个toolbar后才会跳转。我觉得这增加了用户的操作成本。

有没有配置项，使得点击带有链接的图片时直接跳转？还是说我只能修改源码来做到这一点？

**Comment by wangfupeng1988** [comment]
wangEditor 目前不支持移动端
