### ISSUE TITLE
上传图片发生错误 500

### ISSUE THREAD

**Issue by peihuanhuan** [wangfupeng1988/wangEditor#1507]
在测试上传图片的时候，后台直接返回一个符合规范的json，没有问题（如图）
![image](https://user-images.githubusercontent.com/27762147/39736577-45e455fe-52b3-11e8-9251-d7566be05aef.png)

但是如果在参数里面添加一个MultipartFile参数，不管是否使用，都会报500错误
![image](https://user-images.githubusercontent.com/27762147/39736606-6d08fc3e-52b3-11e8-94cd-73b889d476ba.png)

![image](https://user-images.githubusercontent.com/27762147/39736637-8f2574fa-52b3-11e8-91f5-13624ac8545e.png)

![image](https://user-images.githubusercontent.com/27762147/39736652-9ea9e2b2-52b3-11e8-8ecd-493a937b804c.png)

请问是什么原因引起的

**Comment by wangfupeng1988** [comment]
500 是服务器错误，你得去 server 端找原因

**Comment by momokanni** [comment]
我是服了，问个问题都不过脑子，基本的都不知道，还写个屁呀

**Comment by peihuanhuan** [comment]
> 我是服了，问个问题都不过脑子，基本的都不知道，还写个屁呀

你咋那么暴躁呢?

**Comment by momokanni** [comment]
> > 我是服了，问个问题都不过脑子，基本的都不知道，还写个屁呀
> 
> 你咋那么暴躁呢?

这是基础，哥们
