### ISSUE TITLE
刷新页面，如何不是页面的默认焦点在文本编辑器内部？

### ISSUE THREAD

**Issue by Zhang-Yida** [wangfupeng1988/wangEditor#151]
每次刷新页面，页面的默认焦点都在 editor内部， 如何避免这个？

**Comment by wangfupeng1988** [comment]
用 `editor.$txt.blur()` 试试

**Comment by Zhang-Yida** [comment]
@wangfupeng1988 不好用。。  刷新页面后还是默认焦点。

**Comment by wangfupeng1988** [comment]
你想让焦点落在其他的输入框还是单纯的就想blur编辑器？
如果想要让焦点落在其他输入框，那直接 `$('#input1').focus()`就可以了。

**Comment by Zhang-Yida** [comment]
@wangfupeng1988  恩恩  就在刚刚解决了  谢谢  ～～
