### ISSUE TITLE
文档中插入表格，表格中输入汉字，有时候会第一个拼音的字母会单独字母显示，用的搜狗输入法

### ISSUE THREAD

**Issue by mmmmarcos** [wangfupeng1988/wangEditor#1511]
![_20180509153949](https://user-images.githubusercontent.com/26370284/39802336-5949a37c-53a0-11e8-928c-baa690df3a13.jpg)

**Comment by mmmmarcos** [comment]
好像是元音字母开头就会出现

**Comment by wangfupeng1988** [comment]
这个 bug 已经有人提过了，目前尚未找到解决方案。因为有些浏览器可以，有些就不可以，不知道哪里的问题。估计暂时解决不了。

**Comment by zibuyu1** [comment]
哎，版本回退到4.7.0就没有这个问题了
