### ISSUE TITLE
有没有完整的配置文档

### ISSUE THREAD

**Issue by faster-mo** [wangfupeng1988/wangEditor#1512]

**Comment by faster-mo** [comment]
https://www.kancloud.cn/wangfupeng/wangeditor3/356777
如，多语言这里的还可以添加更多，能添加那些？

**Comment by wangfupeng1988** [comment]
文档已经写的很详细了。

多语言哪里“还可以添加更多”意思是，你想让编辑器中的哪些汉语编程英语，自己写就是了，根据自己的需求自由添加，没有其他限制。
