### ISSUE TITLE
我想在富文本里面放入一段html代码

### ISSUE THREAD

**Issue by bsqmla** [wangfupeng1988/wangEditor#1515]
你好,作者,首先感谢你提供的工具,我现在想在富文本里面放一段代码,应该如何读取,我用editor.txt.html()读取出来的内容用浏览器只能读到他的文本,我应该怎样操作呢?

**Comment by jay816314** [comment]
你是想在富文本里面直接显示html代码？editor,txt.html()读取出来的是html代码，你再直接放进代码里，浏览器自然会把他当普通html代码解析，最终给到你浏览的结果

**Comment by wangfupeng1988** [comment]
无回复暂时关闭
