### ISSUE TITLE
如何设置wangEditor的宽度。使其能自适应

### ISSUE THREAD

**Issue by sean5120scan** [wangfupeng1988/wangEditor#1517]
请问如何设置wangEditor的宽度。使其能自适应。工具了总是顶在上面一行。如何实现当设置ediotr的宽度时 ，工具了自动下来。急急急

**Comment by wangfupeng1988** [comment]
https://www.kancloud.cn/wangfupeng/wangeditor3/335771 这个实现不了？

**Comment by wangfupeng1988** [comment]
无回复暂时关闭
