### ISSUE TITLE
编辑器中一行有多张图片时，将一张图片换行时，换行后的图片会消失

### ISSUE THREAD

**Issue by arieswxc** [wangfupeng1988/wangEditor#1518]
连续贴几张一样图片
![image](https://user-images.githubusercontent.com/9198262/39921250-cd557256-54df-11e8-9757-f3cbdf6e9142.png)

然后鼠标移动到其中一张图片前，点击回车，后面的图片消失
![image](https://user-images.githubusercontent.com/9198262/39921265-dd3dbcf0-54df-11e8-97a6-5a0534762900.png)

**Comment by arieswxc** [comment]
qq， chrome浏览器都会出现，都是最新版本。只是我设置了this.editor.customConfig.uploadImgShowBase64 = true;

**Comment by wangfupeng1988** [comment]
> 或者你去官网看下是否有这种问题

这个呢？

**Comment by wangfupeng1988** [comment]
无回复暂时关闭
