### ISSUE TITLE
插入代码后上传内容的问题

### ISSUE THREAD

**Issue by Dannil1** [wangfupeng1988/wangEditor#1519]
插入代码后，通过`editor.txt.html()`获取内容并上传到服务端时，服务端就报错了：`"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'lt;div'`，好像是因为转义符`&lt;div&gt;&lt;/div&gt;`的问题，应该怎么解决呢？

**Comment by wangfupeng1988** [comment]
后端的报错，我也不知道怎么解决。但是你说的转义字符`&lt;div&gt;&lt;/div&gt;`本身没有问题，就该这样转义。
