### ISSUE TITLE
能否支持下nodejs 安装和webpack中调用

### ISSUE THREAD

**Issue by jiangyoucai** [wangfupeng1988/wangEditor#152]
新版编辑器很不错，已经在项目中使用
能否支持下nodejs 安装和webpack中调用
谢谢

**Comment by wangfupeng1988** [comment]
暂时还不行啊，不过这个问题可以先open着，会将功能排到升级计划中。感谢反馈！

**Comment by jiangyoucai** [comment]
谢谢，想在vue.js项目中调用，暂时还没导入进去

**Comment by wangfupeng1988** [comment]
在 vue angular 和 react 中使用时，还需要再做一些调整，我今年春天一定会将编辑器都集成到目前常用的框架中

**Comment by wangfupeng1988** [comment]
目前编辑器已经支持使用`npm`和`bower`安装了，参见 https://github.com/wangfupeng1988/wangEditor 中的说明

**Comment by jiangyoucai** [comment]
非常感谢，明天会在项目中再次尝试集成

**Comment by wangfupeng1988** [comment]
webpack目前还不支持，不过我会在尽快完善上，webpack这个工具还是非常好的。

**Comment by jiangyoucai** [comment]
在vue+webpack中集成，无法传递jquery依赖进去
```
import $ from 'jquery'
import WangEditor from 'wangeditor/dist/js/wangEditor'
WangEditor($)
```
提示，在引用wangEditor.js之前，先引用jQuery，否则无法使用 wangEditor
怎么传递jquery进去，还没找到方法

安装imports-loader插件后
`import 'imports?$=jquery!wangeditor/dist/js/wangEditor'`
依旧提示同样的错误

另外
`import WangEditor from 'wangeditor'`
提示错误
`ERROR in ./~/babel-loader?presets[]=es2015&plugins[]=transform-runtime&comments=false!./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/news/NewsEdit.vue Module not found: Error: Cannot resolve module 'wangeditor' in /home/andy/workspace/lvmeme/src/com.lvmeme.app/public/templates/home/src/views/news resolve module wangeditor in /home/andy/workspace/lvmeme/src/com.lvmeme.app/public/templates/home/src/views/news looking for modules in /home/andy/workspace/lvmeme/src/com.lvmeme.app/public/templates/home/node_modules resolve 'file' wangeditor in /home/andy/workspace/lvmeme/src/com.lvmeme.app/public/templates/home/node_modules resolve file /home/andy/workspace/lvmeme/src/com.lvmeme.app/public/templates/home/node_modules/wangeditor is not a file /home/andy/workspace/lvmeme/src/com.lvmeme.app/public/templates/home/node_modules/wangeditor.js doesn't exist /home/andy/workspace/lvmeme/src/com.lvmeme.app/public/templates/home/node_modules/wangeditor.vue doesn't exist resolve 'file' or 'directory' /home/andy/workspace/lvmeme/src/com.lvmeme.app/public/templates/home/node_modules/wangeditor resolve file /home/andy/workspace/lvmeme/src/com.lvmeme.app/public/templates/home/node_modules/wangeditor is not a file /home/andy/workspace/lvmeme/src/com.lvmeme.app/public/templates/home/node_modules/wangeditor.js doesn't exist /home/andy/workspace/lvmeme/src/com.lvmeme.app/public/templates/home/node_modules/wangeditor.vue doesn't exist resolve directory`

**Comment by wangfupeng1988** [comment]
今晚开始支持`webpack`了，去看看 http://www.kancloud.cn/wangfupeng/wangeditor2/126637

**Comment by jiangyoucai** [comment]
非常感谢，已经测试完毕
编辑器可以加载，但是获取内容出错
错误信息：
wangEditor.js?bd94:6344 Uncaught TypeError: $ is not a function(anonymous function) 
NewsEdit.vue?7904:62 Uncaught TypeError: Cannot read property 'html' of undefined
估计还是和jquery相关的问题

代码如下：
wangEditor-jquery.js
```
var $ = require('./lib/jquery-2.2.1.js');
module.exports = $;
```
newsEdit
```
import WangEditor from 'wangeditor/dist/js/wangEditor'
import layout from '../../components/Layout'
export default {
    data: function() {
        return {
            news: {}
        }
    },
    methods: {
        publishNews: function() {
            var content = editor.$txt.html()
            var thumb = $(editor.$txt.find('img')[0]).attr('src')
            if (this.news.name === '' || content === '' || thumb === '') {
                console.log('提交空数据')
            }
            this.news.content = content
            this.news.thumb = thumb
            console.log('go', JSON.stringify(this.news))
        }
    },
    components: {
        'app-layout': layout
    },
    ready: function() {
        var editor = new WangEditor('editor')
        editor.config.uploadImgUrl = '/help/upload/wangEditorH5File'
        editor.create()
    }
}
```

**Comment by wangfupeng1988** [comment]
> 加载完毕后  $ is not a function(anonymous function) 

这个不正常啊，你是加载完wangEditor之后立马提示的这个错误吗？还是做什么操作的时候提示的这个错误？

另外，执行完 `import WangEditor from 'wangeditor/dist/js/wangEditor'` 之后，你打印一下`wangEditor`以及`wangEditor.fn`、`wangEditor.config`之类的属性，看看是不是有？

**Comment by wangfupeng1988** [comment]
另外，我怀疑是不是因为`React`的某些缘故，我晚上试试不用`React`时能不能加载。

咱俩一起弄弄这个，把支持`React`和`webpack`搞定~

**Comment by jiangyoucai** [comment]
日志如下：

console.log(1, WangEditor)
```
1 function(elemId) {
        // ---------------获取基本节点------------------
        var $elem = $('#' + elemId);
        if ($elem.length !== 1) {
            return;
        }
        var nodeName = $ele…
```
console.log(2, WangEditor.fn)

`2 Object {}`

console.log(3, WangEditor.config)

`3 Object {zindex: 10000, printLog: true, menuFixed: 0, jsFilter: true, legalTags: "p,h1,h2,h3,h4,h5,h6,blockquote,table,ul,ol,pre"…}`

var editor = new WangEditor('editor')
console.log(4, editor)

`4 E {valueNodeName: "div", $valueContainer: jQuery.fn.init[1], $prev: jQuery.fn.init[1], $parent: jQuery.fn.init[1], config: Object…}`

以上都不会报错

editor.create()

这句执行完，编辑器界面出现，同时报错信息也出现了

```
wangEditor提示: 建议在配置中自定义百度地图的mapAk，否则可能影响地图功能，文档：http://www.kancloud.cn/wangfupeng/wangeditor2/113961
wangEditor.js?bd94:6344 Uncaught TypeError: $ is not a function
```

**Comment by wangfupeng1988** [comment]
哦。。。好的，我了解问题了，我晚上回去完善。这个问题优先级最高，正好我个人也正想抓紧支持webpack

**Comment by jiangyoucai** [comment]
已经解决了，大神

**Comment by wangfupeng1988** [comment]
你以上说的这几个问题：`editor.create()`时报错，以及获取内容时报错，我都已经解决了。今晚发布，明天下载最新版本。

其他问题，我也没时间详细测试了，你如果发现了，及时给我反馈吧。幸好目前使用webpack的人不多。

感谢帮忙测试了！

**Comment by jiangyoucai** [comment]
哈，非常感谢大神，我克隆个最新的测试下哈

**Comment by wangfupeng1988** [comment]
你给我发一个QQ邮件，我给你回复一个附件，我昨晚测试的demo，获取html没问题的。

**Comment by jiangyoucai** [comment]
谢谢大神，问题已解决

var editor在vue的ready之前定义即可

错误写法
```
import WangEditor from 'wangeditor/dist/js/wangEditor'
import layout from '../../components/Layout'
export default {
    data: function() {
        return {
            news: {}
        }
    },
    methods: {
        publishNews: function() {
            var content = editor.$txt.html()
            var thumb = $(editor.$txt.find('img')[0]).attr('src')
            if (this.news.name === '' || content === '' || thumb === '') {
                console.log('提交空数据')
            }
            this.news.content = content
            this.news.thumb = thumb
            console.log('go', JSON.stringify(this.news))
        }
    },
    components: {
        'app-layout': layout
    },
    ready: function() {
        var editor = new WangEditor('editor')
        editor.config.uploadImgUrl = '/help/upload/wangEditorH5File'
        editor.create()
    }
}
```
正确写法
```
import WangEditor from 'wangeditor/dist/js/wangEditor'
import layout from '../../components/Layout'
**var editor**
export default {
    data: function() {
        return {
            news: {}
        }
    },
    methods: {
        publishNews: function() {
            var content = editor.$txt.html()
            var thumb = $(editor.$txt.find('img')[0]).attr('src')
            if (this.news.name === '' || content === '' || thumb === '') {
                console.log('提交空数据')
            }
            this.news.content = content
            this.news.thumb = thumb
            console.log('go', JSON.stringify(this.news))
        }
    },
    components: {
        'app-layout': layout
    },
    ready: function() {
        editor = new WangEditor('editor')
        editor.config.uploadImgUrl = '/help/upload/wangEditorH5File'
        editor.create()
    }
}
```

**Comment by wangfupeng1988** [comment]
hello 帅哥，能否写一个vue.js使用wangEditor的小demo，发给我？

**Comment by jiangyoucai** [comment]
我们封装成了组件，晚些再整理下，上传一份给分享给大家，另外我们正在开发基于wangEditor的插件，有疑问的时候，还望大神多多帮助

**Comment by wangfupeng1988** [comment]
好的，我最近自己看了看vue的文档，然后刚才自己写了一个小demo，有不完善的地方，还请指正  https://github.com/wangfupeng1988/wangEditor/blob/master/test/vue/test-vue.html

**Comment by jiangyoucai** [comment]
看了下代码，在网页上这样写是OK的，但是无法在多页面复用，一般是封装成组件，代码稍有不同
https://github.com/jiangyoucai/vueComponents

**Comment by wangfupeng1988** [comment]
好的，多谢了！

**Comment by tcstory** [comment]
@wangfupeng1988 看了一下,好像不支持下面这个引用的方法吧?
```
var wangEditor = require('wangeditor');
```

**Comment by jiangyoucai** [comment]
@tcstory 
vue中子写发是 
import WangEditor from 'wangeditor/dist/js/wangEditor'

**Comment by yayaqu** [comment]
大佬们我的vue和webpack集成环境为什么不可以呢，import WangEditor from 'wangeditor/dist/js/wangEditor'，import WangEditor from 'wangeditor'，还有var wangEditor = require('wangeditor');在本地使用的时候没问题的，但是run build的时候老是报这个错误can't resolve 'wangeditor' in 'src/src/components'

**Comment by wangfupeng1988** [comment]
@yayaqu 
看 https://www.kancloud.cn/wangfupeng/wangeditor3/335789 这里，就是用 npm 引入的 wangEditor
