### ISSUE TITLE
编辑器插入代码后显示行号

### ISSUE THREAD

**Issue by Expre** [wangfupeng1988/wangEditor#1520]
用有序列表应该很简单就可以实现， @wangfupeng1988 ，这样的细节功能像对我们这些程序员来说就很舒服了，自己用这个编辑器发表代码相关文章，别人提问找到具体代码位置真的不爽，建议加上这个行号，例如：这个效果是最棒的
![tim 20180512153811](https://user-images.githubusercontent.com/35752873/39954942-aff7a29e-55fa-11e8-98fd-207a4cb89d6c.jpg)

**Comment by wangfupeng1988** [comment]
https://www.kancloud.cn/wangfupeng/wangeditor3/335784 预览、修改源码的功能，都可以自己实现

**Comment by wangfupeng1988** [comment]
编辑器针对的主要目标用户肯定不是程序猿，如果你的编辑器针对的都是程序猿用户，建议使用 markdown 编辑器，像 github 一样
