### ISSUE TITLE
在不使用编辑器的页面怎么解析编辑器内容

### ISSUE THREAD

**Issue by Dannil1** [wangfupeng1988/wangEditor#1522]
我当前的方法是把编辑器内容提交到服务端，那在不使用编辑器的页面从服务端获取内容后，怎么解析？

**Comment by liuzeyafzy** [comment]
在你没有污染html标签类样式的情况下，直接将获取的内容放到div里面展示，就可以了吧？

我在使用in-vue的demo里面，将返回值直接放到“<div id="app"></div>”之前，展示效果就与编辑器中的很类似。

![image](https://user-images.githubusercontent.com/4161166/40092159-7563f6ae-58ee-11e8-97be-d7b78ed34fd7.png)

**Comment by liuzeyafzy** [comment]
ps, 瞟了一眼文档，可以支持上传图片，所以请忽略我上面截图中对于能否上传图片的评价

**Comment by Dannil1** [comment]
原来如此，是我想复杂了
