### ISSUE TITLE
当编辑区有选中内容粘贴内容时，选中内容不会被替换

### ISSUE THREAD

**Issue by jcplus** [wangfupeng1988/wangEditor#1526]
复原方法：
1、选中编辑区一部分内容
2、从别处复制一段不同内容
3、粘贴到编辑区
4、新内容会被自动附加到内容底部

**Comment by jcplus** [comment]
已经解决

**Comment by liuzeyafzy** [comment]
@jcplus 怎么解决的呢，能不能概括下？

**Comment by wangfupeng1988** [comment]
对，解决的问题，最好也能说一下解决方法，分享给大家

**Comment by jcplus** [comment]
因为我自己也无法重现问题了，所以只当是解决了。

**Comment by aruandme** [comment]
这个问题在作者提供的demo上尝试同样存在此问题！！时间2018-12-06 
如上所述：1.复制一段内容 2.在编辑区域内全选 3.粘贴之前复制的内容 4.出现直接追加到之前的内容后面或随机位置而不是直接替换
