### ISSUE TITLE
复制word文本到编辑器时，编辑区标签混乱

### ISSUE THREAD

**Issue by lurenhtml5** [wangfupeng1988/wangEditor#1528]
首先，谢谢您提供的编辑器工具，最近在使用上遇到一点问题，就是在从word文本中复制内容到编辑器时，获取到的editor.txt.text()中，存在很多多余的样式；editor.customConfig.pasteFilterStyle = true已设置，仍然无效。

如：
这个该如何解决呢，

**Comment by lurenhtml5** [comment]
[if gte mso 9]><xml>
 <o:DocumentProperties>
  <o:Revision>0</o:Revision>
  <o:TotalTime>0</o:TotalTime>
  <o:Pages>1</o:Pages>
  <o:Words>2</o:Words>
  <o:Characters>13</o:Characters>
  <o:Company>zyzl</o:Company>
  <o:Lines>1</o:Lines>
  <o:Paragraphs>1</o:Paragraphs>
  <o:CharactersWithSpaces>14</o:CharactersWithSpaces>
  <o:Version>14.0</o:Version>
 </o:DocumentProperties>
 <o:OfficeDocumentSettings>
  <o:AllowPNG/>
 </o:OfficeDocumentSettings>
</xml><![endif]

**Comment by wangfupeng1988** [comment]
复制 word excel 粘贴时有乱码的问题，后期会统一处理，目前还没有精力去做。

编辑器开放了一个函数`editor.customConfig.pasteTextHandle`允许用户自己来处理，文档 https://www.kancloud.cn/wangfupeng/wangeditor3/448202

**Comment by wo-xiaoxiao** [comment]
请问你解决了没

**Comment by CynthiaNC** [comment]
确实，从word中复制文字之后，就会带有一段 xml 代码，即使把内容全部删除然后再输入新的内容，xml 代码还是会存在。

我的解决方案是，从源头处禁止粘贴内容的样式。

1. 使用 shift + ctrl + v 进行粘贴（可去除样式）
2. 通过editor.customConfig.pasteTextHandle函数过滤粘贴方式内容。
如果是直接ctrl+v粘贴的，会带有<!--[if gte mso 9]><xml>.....</xml><!--[endif]> 这样的代码，就不允许粘贴；如果是用 shift + ctrl + v 方式进行粘贴的，就返回粘贴内容。（参考 [#1603](https://github.com/wangfupeng1988/wangEditor/issues/1603)）

```
      editor.customConfig.pasteTextHandle = function (content) {
            if (~content.indexOf('<!--[if gte mso 9]><xml>')) {
                return ''
            } else {
                return content
            }
        }
```

**Comment by onepow** [comment]
> 确实，从word中复制文字之后，就会带有一段 xml 代码，即使把内容全部删除然后再输入新的内容，xml 代码还是会存在。
> 
> 我的解决方案是，从源头处禁止粘贴内容的样式。
> 
> 1. 使用 shift + ctrl + v 进行粘贴（可去除样式）
> 2. 通过editor.customConfig.pasteTextHandle函数过滤粘贴方式内容。
>    如果是直接ctrl+v粘贴的，会带有<!--[if gte mso 9]>.....<!--[endif]> 这样的代码，就不允许粘贴；如果是用 shift + ctrl + v 方式进行粘贴的，就返回粘贴内容。（参考 [#1603](https://github.com/wangfupeng1988/wangEditor/issues/1603)）
> 
> ```
>       editor.customConfig.pasteTextHandle = function (content) {
>             if (~content.indexOf('<!--[if gte mso 9]><xml>')) {
>                 return ''
>             } else {
>                 return content
>             }
>         }
> ```

这个判定可能有问题， 不能强调用户的COPY行为， 如果是用鼠标操作的话 就是 CTRL +V ， 建议用正则去掉多余 生成的样式 可能更好。
