### ISSUE TITLE
vue  wacth监听编辑器内容时，再次输入会出错

### ISSUE THREAD

**Issue by lvzhengyu** [wangfupeng1988/wangEditor#1529]
vue2.0 引用编辑器的子组件需要通过props来动态赋值一些内容的时候，在此基础上，用户如果自行输入内容的时候，会导致编辑器录入输入法输入过程中的内容，比如我想打‘测试’两个字，拼音也会被输入到编辑器中，就会造成'ceshi测试'，通过watch去跟踪编辑器内容，控制台内容也会录入输入法输入过程。

**Comment by liuzeyafzy** [comment]
1、多描述些情况哈，输入法名称和版本，然后你的代码能够写成一个demo最好，不能最好也能够把部分代码贴出来——做一个与你的业务无关的demo也是提高咯～
2、我在看这个插件的文档的时候，尝试了我理解的你描述的场景。是基于作者的in-vue下的demo改写的。这段代码还有个小问题，就是props更新进来时，可能存在用户还在输入的情况，导致跳了鼠标位置。**这个问题也是可以通过判断焦点来开关props更新来处理的**，因时间关系且与这个问题无关，我直接注释掉了watch。

Editor.vue script主要改动：
`
<script>
    import E from 'wangeditor'
    var editor

    export default {
      name: 'editor',
      props: {
        propEditorContent: {
          type: String,
          default: ''
        }
      },
      computed: {
        editorContent: {
          get(){
            return this.propEditorContent
          },
          set(value){
            this.$emit('dochange', value)
          }
        }
      },
      watch: {
        // propEditorContent(newV){
        //   if (newV !== editor.txt.html()) {
        //     console.log(1)
        //     editor.txt.html(this.editorContent)
        //   }
        // }
      },
      methods: {
        getContent: function () {
            alert(this.editorContent)
        }
      },
      mounted() {
        editor = new E(this.$refs.editor)
        editor.customConfig.uploadImgShowBase64 = true
        editor.customConfig.onchange = (html) => {
          this.editorContent = html
        }
        editor.create()
        editor.txt.html(this.editorContent)
      }
    }
</script>
`

App.vue 的主要改动：
`
<template>
  <div id="app">
    <img src="./assets/logo.png">
    <hello></hello>
    <editor :propEditorContent="editorContent" @dochange="dochange"></editor>
  </div>
</template>

<script>
import Hello from './components/Hello'
import Editor from './components/Editor'

export default {
  name: 'app',
  components: {
    Hello,
    Editor
  },
  data(){
    return {
      editorContent: '<p>sdddd</p><p>sdfwedsf</p><p>ewfwdf</p>'
    }
  },
  methods: {
    dochange(event){
      console.log('dochange: ', event)
      this.editorContent = event
    }
  }
}
</script>
`

**Comment by wangfupeng1988** [comment]
无回复暂时关闭
