### ISSUE TITLE
工具栏换行后，悬浮框选不上，无法使用

### ISSUE THREAD

**Issue by zhump** [wangfupeng1988/wangEditor#1530]
![image](https://user-images.githubusercontent.com/7962067/40046281-2a450c1a-585f-11e8-8681-79ccdfe9de25.png)

**Comment by wangfupeng1988** [comment]
默认情况下不支持工具栏换行，因为换行会导致样式难看，如果宽度不够，建议重新配置菜单进行简化。

这是你自己改代码了吧？
