### ISSUE TITLE
编辑好的文章，下划线和删除线在手机端显示不出来

### ISSUE THREAD

**Issue by ChenSmall** [wangfupeng1988/wangEditor#1531]

**Comment by ChenSmall** [comment]
用电脑模拟的没问题，用手机访问会显示不出来

**Comment by wangfupeng1988** [comment]
先看下出来的 html ，style 是不是生效了？如果有了 style ，但是样式没显示，那就查一查 css 污染的问题。

**Comment by george0312** [comment]
> 先看下出来的 html ，style 是不是生效了？如果有了 style ，但是样式没显示，那就查一查 css 污染的问题。

在手机端text-decoration-line: underline是无效的， text-decoration: underline才能正常显示
