### ISSUE TITLE
上传图片到七牛云上传不了

### ISSUE THREAD

**Issue by CaoJ20132014** [wangfupeng1988/wangEditor#1533]
editor.customConfig.qiniu = true;
加上这个配置以后就没办法选择图片了

**Comment by wangfupeng1988** [comment]
按照文档的例子来吧 https://www.kancloud.cn/wangfupeng/wangeditor3/405041

**Comment by CaoJ20132014** [comment]
嗯嗯，谢谢

 iPhone 8 plus

**Comment by Eddie-Fannie** [comment]
解决了这个问题了吗
