### ISSUE TITLE
H标题引发的图片消失的问题

### ISSUE THREAD

**Issue by qiujie8092916** [wangfupeng1988/wangEditor#1534]
复现描述：
1.空的富文本框里打几个字，并选中将字设置为除正文外的任何标题大小（h1~h5）
2.紧接着上传一张图片
3.左移一格(光标位于字和图片中间)
4.敲回车
5.换行的同时伴随着图片的**消失**

**Comment by wangfupeng1988** [comment]
这个问题严格来说是一个 bug 。

不过，在 h 中添加图片的情况还是比较少的，案例说也是不允许的。在 p 中添加图片，回车换行不会有问题。

这个问题我记录下，再升级时看看如何解决吧，不过不会太高优。

**Comment by elvisWEB** [comment]
这个问题应该是比较高的优先级吧，很多运营人员都有这样的习惯。。希望能处理一下

**Comment by liujihaozhy** [comment]
这个问题解决不了，只能放弃使用了 @wangfupeng1988
