### ISSUE TITLE
为什么加粗要在行内添加style，而不是用b标签呢？？

### ISSUE THREAD

**Issue by tanxuewei** [wangfupeng1988/wangEditor#1535]
不用b标签，保留style会出现XSS攻击，用了filterCSS后，style又会被去掉？

**Comment by tanxuewei** [comment]
看了下代码是指执行了浏览器自己的bold，为什么不用标签替换么？我看以前的版本是用标签替换的啊？ 现在的版本能怎么解决呢

**Comment by wangfupeng1988** [comment]
> 保留style会出现XSS攻击

只加粗，还会有 xss 共计吗？你是不是为了防止 xss 共计，把所有的 style 都干掉了？

**Comment by tanxuewei** [comment]
是的，我之前只把所有的都去掉了，现在加了xss配置可以保留。只是我很好奇为什么不像2.x版本加上b，i标签，而是选择用行内style呢？请教下

**Comment by tanxuewei** [comment]
然后还有个问题想请教下，就是我在编辑的时候，选中全部然后删除，有的时候不会触发onchange事件

**Comment by cxcshuaige** [comment]
因为 _useStyleWithCSS 这个属性的缘故

**Comment by wangfupeng1988** [comment]
> 然后还有个问题想请教下，就是我在编辑的时候，选中全部然后删除，有的时候不会触发onchange事件

不同的问题，重新提交吧，别混在一起。
