### ISSUE TITLE
wangEditor3 菜单栏的部分操作按钮 限制editor宽度后会溢出不会换行显示

### ISSUE THREAD

**Issue by littlefish-qiu** [wangfupeng1988/wangEditor#1537]
![image](https://user-images.githubusercontent.com/20655940/40336675-ac86250e-5d9d-11e8-99f4-e8cb645be4bb.png)

**Comment by wangjun521** [comment]
作者文档说明的很清楚 换行后难看 所以直接不换行了 其实宽度也没有很宽

**Comment by wangfupeng1988** [comment]
楼上正解。
