### ISSUE TITLE
怎样做wangEditor内容与变量的双向绑定？

### ISSUE THREAD

**Issue by Rominez** [wangfupeng1988/wangEditor#1539]
我想实现一个可以编辑源代码同时编辑富文本的功能。原理是监听<textarea>的oninput，修改内容同时使用
editor.txt.html( textarea.value ) 去修改富文本编辑器里的样子，但调用了 html() 方法后输入的光标立即转到wangEditor 里。我又有点不想用 onchange，有没有办法做一个内容与某个数据变量的双向绑定呢？
![iss](https://user-images.githubusercontent.com/32057076/40357424-b91725b0-5dee-11e8-840e-a3bbcb7da066.png)

**Comment by wangjun521** [comment]
如果你是用vue的话你可以使用watch试试

**Comment by Rominez** [comment]
并没有用到vue😂。。其实我是个还不会用vue的后端程序员啦，这个是一个管理项目涉及到修改文章的需求，一边wangEditor给其他人用，一边textarea给技术人员用，相当于直接改库里的代码

**Comment by wangfupeng1988** [comment]
先从文档看起。https://www.kancloud.cn/wangfupeng/wangeditor3/335789

**Comment by run27017** [comment]
> 先从文档看起。https://www.kancloud.cn/wangfupeng/wangeditor3/335789

这并不是双向绑定，我试过如果做双向绑定的话，光标会飘导致无法正常输入（onchang方法）。如果换成onblur，必须要点击编辑器外面使其失焦，这时如果直接点击按钮如保存之类的，拿到的是失焦之前的编辑器数据。

**Comment by cherishPhoebe** [comment]
> > 先从文档看起。https://www.kancloud.cn/wangfupeng/wangeditor3/335789
> 
> 这并不是双向绑定，我试过如果做双向绑定的话，光标会飘导致无法正常输入（onchang方法）。如果换成onblur，必须要点击编辑器外面使其失焦，这时如果直接点击按钮如保存之类的，拿到的是失焦之前的编辑器数据。
这样的话是否可以在点击保存的事件中先手动触发一次onchange事件.使textarea中的内容是最新的

**Comment by yjshi2015** [comment]
> 先从文档看起。https://www.kancloud.cn/wangfupeng/wangeditor3/335789

里边并没有讲如何回显数据啊
