### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by hsun924** [wangfupeng1988/wangEditor#154]
移除元素的attr时，添加rowspan和colspan例外，至少保证表格的跨行和跨列

**Comment by wangfupeng1988** [comment]
好的，我忽略了，这个应该得加上。
我记下来，啥时候加上了，我在这里回复你。

**Comment by wangfupeng1988** [comment]
已经增加上了，将在今后的下一个版本中发布。可时刻关注QQ群邮件的通知。
