### ISSUE TITLE
富文本器编辑的字体图标和页面本身的字体图标冲突

### ISSUE THREAD

**Issue by hufenghuai** [wangfupeng1988/wangEditor#1541]
富文本器编辑的字体图标和页面本身的字体图标冲突

**Comment by wangfupeng1988** [comment]
编辑器字体相关的 css 源码在这里 https://github.com/wangfupeng1988/wangEditor/blob/master/release/wangEditor.css#L63 ，有冲突问题自己解决一下吧，这个编辑器不太好解决。
