### ISSUE TITLE
onchangeTimeout设置为0的问题

### ISSUE THREAD

**Issue by qiujie8092916** [wangfupeng1988/wangEditor#1542]
当onchangeTimeout设置为0时
在快速的输入字符和换行时
字符可能会被删掉

**Comment by wangfupeng1988** [comment]
你干嘛要设置为 0 呢？

**Comment by qiujie8092916** [comment]
改为1可以避免这个问题，当时为了尽可能缩短延迟触发时间

**Comment by wangfupeng1988** [comment]
onchangeTimeout 是为了函数节流用的，优化性能的，你改成 0 改成 1 ，那就对节流没意义了。我建议保持源代码中的值不变。
