### ISSUE TITLE
上传图片至阿里云，返回数据格式正确，但无法在编辑器中显示

### ISSUE THREAD

**Issue by zzke** [wangfupeng1988/wangEditor#1543]
上传图片成功，返回格式也正确，但在编辑中无法显示？

```html
<script src="${request.contextPath}/statics/common/js/wangEditor/wangEditor.min.js"></script>
    <script type="text/javascript">
        var E = window.wangEditor;
        var editor = new E('#editor');
        editor.customConfig.debug = location.href.indexOf('wangeditor_debug_mode=1') > 0;
        editor.customConfig.uploadImgServer = baseURL + 'shop/goods/upload';
        editor.customConfig.uploadFileName = 'file';
        editor.customConfig.uploadImgHooks = {
        		success: function(xhr,editor,result) {
        			alert("上传图片成功");
        		},
        		error: function(xhr,editor) {
        			alert("图片上传失败");
        		},
        		customInsert: function(insertImg,result,editor) {
        			var url = result.data;
        			insertImg(url);
        		}
        }
        editor.create()
    </script>
```
返回数据`{"errno":0,"data":["https://luxuryfox.oss-cn-shenzhen.aliyuncs.com/20180524/138826890282497f8f395d3e5286612a.png"]}`

**Comment by wangfupeng1988** [comment]
`var url = result.data;`获取的是一个数组啊，而`insetImg`要传入字符串的 —— 这低级错误。。。

**Comment by zzke** [comment]
customInsert: function(insertImg,result,editor) {
        			var url = result.data;
        			console.log(url[0]);
        			insertImg(url[0]);
        		}
没什么用？这个我之前也尝试过

**Comment by wangfupeng1988** [comment]
看下 chrome 控制台有没有 JS 报错？另外看下这个图片资源有没有被发起加载请求？

**Comment by zzke** [comment]
Accept: image/webp,image/apng,image/*,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9
Connection: keep-alive
Host: luxuryfox.oss-cn-shenzhen.aliyuncs.com
Referer: http://192.168.1.119:8080/welllan-admin/modules/shop/goods.html
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

**Comment by zzke** [comment]
@wangfupeng1988

**Comment by wangfupeng1988** [comment]
你发的这是请求时的 head ，返回的信息是啥呀？
