### ISSUE TITLE
内容保存过后，显示效果不对

### ISSUE THREAD

**Issue by LordRobert** [wangfupeng1988/wangEditor#1546]
主要是table，编辑过程中带 边框线，再显示的时候，边框线没有了。这种默认样式，是否增加上的为好？
![image](https://user-images.githubusercontent.com/8347212/40489053-d300787a-5f9a-11e8-8425-902f02a4db5c.png)
![image](https://user-images.githubusercontent.com/8347212/40489078-e22d9d6e-5f9a-11e8-98a3-d5583648bca8.png)

**Comment by wangfupeng1988** [comment]
看这里 https://www.kancloud.cn/wangfupeng/wangeditor3/335775
