### ISSUE TITLE
3.0版本没有像2.0版本那样的表情从后台获取的配置了吗？只能一个一个配置？

### ISSUE THREAD

**Issue by javed119** [wangfupeng1988/wangEditor#1547]
2.0版本表情配置可以直接通过访问后台请求获取表情的json，3.0版本没有吗？

**Comment by wangfupeng1988** [comment]
这个不是大问题，你可以自己写一个获取后台图片配置的 ajax ，然后在 callback 中再配置 editor 。就是说，这个表情从后台获取，并不是 editor 必须的功能，自己做也不麻烦。
