### ISSUE TITLE
wangEditor3.0版本颜色格式问题请教

### ISSUE THREAD

**Issue by xiaojinglyd** [wangfupeng1988/wangEditor#1548]
您好！我想知道wangEditor3.0版本颜色是被强制转化成了rgb吗？我怎样可以转回获取十六进制呢？我试着替换成十六进制，但是不生效，应该是3.0版本强制转化rgb了吧？麻烦帮忙解答下，谢谢！ @wangfupeng1988 

不好意思，我找到原因了，()正则不识别，要加转义符号，实在抱歉，误以为您强制转化了。

**Comment by wangfupeng1988** [comment]
OK 那我先关闭问题。

**Comment by adele-ty** [comment]
请问这个问题是如何解决的，我使用的是v5版本，麻烦解答一下，感谢！ @wangfupeng1988

**Comment by cycleccc** [comment]
@adele-ty wangeditor 底层做了颜色转换，设置了16进制也会被转成 rgb，如果你的需求一定要 16进制的话建议在 gethtml 时对 文本的 style 进行rgb转16进制处理

**Comment by adele-ty** [comment]
![image](https://github.com/user-attachments/assets/0e2d0cc5-c208-4c70-8cd9-deecb3d95841)

选择了失焦的时候转回16进制但并没有效果,newHtml正是我需要的，似乎是setHtml没有效果 @cycleccc

**Comment by cycleccc** [comment]
@adele-ty  wangeditor是不能随意 setHtml 的，setHtml 时会进行 normlize，你刚改的 html setHtml 又会改回去，能做的就是想要取出 html 的时候做过滤，没法注入回去。

**Comment by adele-ty** [comment]
感谢 @cycleccc
