### ISSUE TITLE
toolbar计算marginLeft未考虑计算为负数

### ISSUE THREAD

**Issue by hsun924** [wangfupeng1988/wangEditor#155]
toolbar计算marginLeft时未考虑计算结果小于0的情况，导致toolbar超出浏览器范围，部分功能使用不了，比如删除
浏览器：FireFox

**Comment by wangfupeng1988** [comment]
感谢反馈！
有复现场景（什么情况下能复现这个问题）和截图吧？可否在此描述、粘贴一下？

**Comment by hsun924** [comment]
![i1](https://cloud.githubusercontent.com/assets/3666506/13590926/fdb967fa-e51e-11e5-80ef-c5e10ebc5bb9.PNG)
![i2](https://cloud.githubusercontent.com/assets/3666506/13590928/02eacafc-e51f-11e5-83c7-cd9f1a992d36.PNG)

**Comment by wangfupeng1988** [comment]
该问题已经处理，请关注今后下一个版本的更新，会在QQ群中通知
