### ISSUE TITLE
是否可以添加设置行高和缩进的菜单？

### ISSUE THREAD

**Issue by TsingM** [wangfupeng1988/wangEditor#1552]
看V2.x版本的文档里有写，V3.X里取消了？

**Comment by wangfupeng1988** [comment]
该功能用的比例比较少，v3 取消了。

**Comment by huangqiang1363** [comment]
该功能用的比例比较少，v3 取消了吗？  哎，那自定义菜单的功能还有吗

**Comment by wangfupeng1988** [comment]
@huangqiang1363 自定义菜单也取消了

**Comment by huangqiang1363** [comment]
不是吧，老师；这玩意很有用呀！  如果自定义菜单取消了，那么我们如何实现一些 针对选取内容调整样式的 功能呢？ 调API的话，可以吗？ 事件监听应该放到哪里呢？

**Comment by wangfupeng1988** [comment]
@huangqiang1363 你的问题统一在 https://github.com/wangfupeng1988/wangEditor/issues/1556#issuecomment-392661165 回复

**Comment by kuangqijie** [comment]
我也很想知道如何添加行高功能、现在的项目急需这个、如果不能调行高的话、编辑文章的时候调间距只能通过换行、完全不能满足需求，知道的求告知

**Comment by fplun** [comment]
越用越回去了

**Comment by xieting123** [comment]
我也很想知道行高功能，请问有谁写出来啦，麻烦告知一下，万分感激

**Comment by gg22mm** [comment]
老大这个是最基本功能哦。行高这种应该会用到很多的。 怎么说用得少呢。实在不理解。这个是最基本功能呀。。 建议加上

**Comment by gg22mm** [comment]
灵魂功能不能丢啊。老大

**Comment by CoKoLe** [comment]
新版行间距和缩进能加上吗

**Comment by GalaxyChueng** [comment]
感觉新版功能还变少了
