### ISSUE TITLE
请问怎么增加从本地添加图片哦

### ISSUE THREAD

**Issue by liuwenn** [wangfupeng1988/wangEditor#1557]

**Comment by IVANLEE99** [comment]
https://www.kancloud.cn/wangfupeng/wangeditor3/335780
文档在此，请过目

**Comment by IVANLEE99** [comment]
![image](https://user-images.githubusercontent.com/18308725/40637259-5679f930-6336-11e8-8092-26c76cca0467.png)

**Comment by wangfupeng1988** [comment]
先看文档再来提问
