### ISSUE TITLE
是否可以将编辑器的右侧滚动改为auto？一切都是为了good looking

### ISSUE THREAD

**Issue by IVANLEE99** [wangfupeng1988/wangEditor#1558]
一切不美的编辑器，都是耍流氓。

![image](https://user-images.githubusercontent.com/18308725/40637299-983f4c62-6336-11e8-9dbe-5cfc1198a157.png)

![image](https://user-images.githubusercontent.com/18308725/40637392-3106f06c-6337-11e8-8366-ba00d2a9f551.png)

***

改成
`
.w-e-text{
    overflow-y: auto;
}
`

![image](https://user-images.githubusercontent.com/18308725/40637351-eb43cf1e-6336-11e8-9d52-e953a063a8c8.png)

**Comment by wangfupeng1988** [comment]
因为你将菜单栏放在右侧了，一次肯定得默认去掉滚动条，但是大部分用户还是没这个需求的。

因此，我建议你手动写一个 css 覆盖掉编辑器的默认样式，这样比较简单的达成目的。
