### ISSUE TITLE
建议将效果进行实时选择展示

### ISSUE THREAD

**Issue by rowthan** [wangfupeng1988/wangEditor#156]
目前要编辑效果  必须要先选中某一文字或对象再设置颜色等属性才能生效 希望能够先设置效果再编辑内容 如 这里github回复的内容的编辑器一样

**Comment by wangfupeng1988** [comment]
> 希望能够先设置效果再编辑内容 如 这里github回复的内容的编辑器一样

至于先编辑内容还是先设置效果，这不是使用编辑器过程中的关键问题，怎么着都能用。再者，这是一个仁者见仁的问题，有的人喜欢这样，有的人喜欢那样。最后，github的编辑器是markdown的，也wangEditor还是不大一样的。

目前编辑器还有一些优先级比较高的问题要解决，因此这个问题我觉得得放一放再讨论了。

感谢你的反馈！
