### ISSUE TITLE
v2.xx与v3.xx版本区别

### ISSUE THREAD

**Issue by shiruchao** [wangfupeng1988/wangEditor#1563]
v2与v3除了在兼容性方面有区别！还在什么地方有区别！比如API有没有变化！我看了一下v2的文档！好像已经没有介绍了！都是空白的页面！是不是说明只有兼容性的区别！在API等使用上没有大的改变呢！

**Comment by wangfupeng1988** [comment]
v3 算是 v2 的重构，各个方面都有区别，无论是兼容性还是功能上

**Comment by wangfupeng1988** [comment]
推荐直接使用 v3 ，放弃 v2 。v2 已经不再技术支持了，不再升级了，v3 还在维护中。

**Comment by shiruchao** [comment]
开始我也使用的V3最新版！后来因为要解决IE8兼容问题！不得不降级使用V2版本！现在问题已经解决！在此表示感谢！
________________________________
发件人: 王福朋 <notifications@github.com>
发送时间: 2018年6月2日 18:10:50
收件人: wangfupeng1988/wangEditor
抄送: shiruchao; State change
主题: Re: [wangfupeng1988/wangEditor] v2.xx与v3.xx版本区别 (#1563)


推荐直接使用 v3 ，放弃 v2 。v2 已经不再技术支持了，不再升级了，v3 还在维护中。

―
