### ISSUE TITLE
 编辑区域过小的话。。。工具条溢出

### ISSUE THREAD

**Issue by llsi4275** [wangfupeng1988/wangEditor#1564]
![qq 20180531192920](https://user-images.githubusercontent.com/5013417/40779828-f575f6b4-6508-11e8-861e-033d9f285caf.png)

 编辑区域过小的话。。。工具条溢出

**Comment by wangfupeng1988** [comment]
这个问题我回复过很多次了，可以去关闭的 issue 中查看。

v3 不支持菜单换行，菜单太多溢出的话，你应该精简菜单项。如果你非得要换行，自己找到`.w-e-toolbar`元素增加一个`flex-wrap: wrap`就行。

**Comment by pdd11997110103** [comment]
了解
