### ISSUE TITLE
只请求了一次OPTIONS通过后就不再请求上传图片了

### ISSUE THREAD

**Issue by 171563857** [wangfupeng1988/wangEditor#1565]
项目要跨域上传图片

**Comment by 171563857** [comment]
还有上传图片后有回调函数吗?
因为我的想法是先上传到一个临时文件夹,然后最后保存时把临时文件在复制到另一个文件夹
临时文件夹每天凌晨要清空

**Comment by 171563857** [comment]
谢谢

**Comment by wangfupeng1988** [comment]
第一，编辑器上传图片的配置问题参考 https://www.kancloud.cn/wangfupeng/wangeditor3/335782

第二，你 server 端如何操作上传后的文档，我给不了太多建议，毕竟每个人的语言、框架和环境都不一样
