### ISSUE TITLE
粘贴内容时，滚动条位置不变

### ISSUE THREAD

**Issue by KrisBiuBiu** [wangfupeng1988/wangEditor#1567]
粘贴内容，当一次性粘贴的内容稍微多一点的时候，编辑器的滚动条不会自动移动到光标处

**Comment by KrisBiuBiu** [comment]
![image](https://user-images.githubusercontent.com/25652089/40838056-1b529132-65cf-11e8-949e-0d274f9d106b.png)

**Comment by KrisBiuBiu** [comment]
![image](https://user-images.githubusercontent.com/25652089/40838163-8d2d7420-65cf-11e8-9894-5b843b8223f2.png)

**Comment by KrisBiuBiu** [comment]
就是像第二张图片那样，我又粘贴了一大段文字，这个时候滚动条位置没有变化，光标也没有出现在视野中

**Comment by wangfupeng1988** [comment]
考虑了一下，这个问题不太容易解决。我无法不管不顾直接将滚动条滚到最下方，这样对于其他的粘贴行为可能造成误伤。

因此，这个问题得根据粘贴之后光标的位置来计算，而且要最好要加一个动画（直接变过去会很突兀），因此成本还是比较高的。

近期我精力不是太多，因此就有限解决比较重要的问题，这个问题优先级先放低，我会记录下。

个人维护，还望体谅。

**Comment by leizhongli** [comment]
这个问题是什么情况？你是怎么解决的呢？

**Comment by KrisBiuBiu** [comment]
还没解决，体验问题而已，重要程度不高，暂时搁置了

**Comment by leizhongli** [comment]
嗯  我这边是必须做啦  得关于光标定位个盒子   只能想想别的招啦
