### ISSUE TITLE
html 初始化内容 js 设置内容 设置的内容会溢出编辑器

### ISSUE THREAD

**Issue by zhangvoice** [wangfupeng1988/wangEditor#1568]
![image](http://7shriek.cn/public/uploads/test.jpg)

**Comment by zhangvoice** [comment]
@wangfupeng1988

**Comment by wangfupeng1988** [comment]
我看下给你回复

**Comment by wangfupeng1988** [comment]
> 猜测你 JS 设计内容时，没有用`<p>....</p>`包裹。

你认真检查一下，你的内容中，有不被`<p>`包裹的。另外，编辑器内部的内容，也不能使用`<div>`包裹。

**Comment by zhangvoice** [comment]
我认为这不是我能控制的，有不被`<p>`包裹的和`<div>`包裹 的内容，均是编辑器产生的，在官网测试也是同样的问题
例如复制长度约868个无任何标签字符到编辑器中，查看代码发现 整体所有文字被一个 `<p>`包裹，里面小段内容就不会被‘<p>’包裹，就这样产生了不被`<p>`包裹

操作居中产生 `<div style="text-align: center;">假文字</div>`  。

@wangfupeng1988

**Comment by cdleaf** [comment]
这个问题目前有解决方案吗？

**Comment by cdleaf** [comment]
我也同样遇到这样的问题，如果楼主已经解决了，求分享。

**Comment by zhangvoice** [comment]
@cdleaf 暂时没有，复制的内容只能一段一段贴进去。等吧

**Comment by xxShawn** [comment]
粘贴表格之后， 在表格的前后不按回车键输入， 会产生没有用<p>标签包裹的内容 ，
导致溢出

**Comment by xxShawn** [comment]
插入自带的表格， 用鼠标选择到表格的前面（不要回车）会产生没有用 p 标签包裹的内容

**Comment by xxShawn** [comment]
<p>这里有个p被过滤掉了
