### ISSUE TITLE
对于代码特殊字符替换的问题

### ISSUE THREAD

**Issue by rowthan** [wangfupeng1988/wangEditor#157]
刚刚下载运行了 在贴入代码时（如http）发现 会将一些字符进行替换掉如‘<’等一些符号，结果在页面显示的时候，出来的效果就是被替换后的符号如‘&lt’ 导致很不友好，我想解决办法是在显示的时候再进行一次替换，但是觉得略麻烦。看了源代码，替换部分：
` val = val.replace(/&/gm, '&amp;')
                         .replace(/</gm, '&lt;')
                         .replace(/>/gm, '&gt;');`
不知道这样做的意义是什么？是为了代码压缩？
我现在自己用的时候将这替换部分删除了，但是结果是实时编辑的时候效果出不来。

**Comment by rowthan** [comment]
后来仔细看了下 觉得替换应该是转义吧 防止标签配对混乱的问题 但是怎么解决 输出的时候正确转换回来呢 再进行一次替换？

**Comment by wangfupeng1988** [comment]
> 结果在页面显示的时候，出来的效果就是被替换后的符号如‘&lt’ 导致很不友好，

你这个问题是什么环境下复现的？在官网demo也能复现吗？

---

我这里是这样的：我复制一段文字，例如`<script src="embedpano.js"></script>`，粘贴到编辑器中，得到的源码会是`<p>&lt;script&nbsp;src="embedpano.js"&gt;&lt;/script&gt;</p>`，但在编辑器区域显示的时候还是`<script src="embedpano.js"></script>`啊。即，源码中`&lt;`显示在编辑区域还是`<`。

**Comment by rowthan** [comment]
恩恩在编辑情况下 显示是没有问题的。我的意思是post 提交给数据库的时候是 提交的转义后的&lt。导致的结果是从数据库提取出来 渲染到前台的时候 也是&lt 这样一个结果。因为存入数据库提交的是源码 而不是编辑区域的样子。不知道我有没有说清楚

**Comment by ihongs** [comment]
这不很正常吗？难道 <p><script src="embedpano.js"></script></p> 那到最终的展示页就真成一段 js 引入了；如果真想插入一个 js ，在源码模式下编辑即可，其他编辑器也是如此办的。

**Comment by rowthan** [comment]
那在输出的时候怎么弄呢？显示的时候就要“<p><script src="embedpano.js"></script></p>”这个效果 但是又不能出现你说的这样真的引入一个js文件了。

**Comment by wangfupeng1988** [comment]
总之只要你给出的内容是`&lt;`那么显示出来的内容就是`<`，至于你是怎么获取的数据，怎么存储，之后又怎么展示，方式有很多种，我也不得而知。再怎么变化也逃不出html特殊字符转义的规则，这得靠你多实验研究一下。
