### ISSUE TITLE
wangEditor3想支持代码高亮，从源码入手，有什么建议吗？

### ISSUE THREAD

**Issue by Shmily-HJT** [wangfupeng1988/wangEditor#1571]
想结合hightlight让代码支持高亮，请教一下大大，有什么建议？

**Comment by wangfupeng1988** [comment]
第一，你要在输入代码的弹出框中，增加一个选择语言的`<select>`，源码可从 https://github.com/wangfupeng1988/wangEditor/blob/master/src/js/menus/code/index.js#L59 入手

第二，输入代码点击按钮插入时，其实会想编辑区域插入`<pre><code>....</code></pre>`，你要修改这里的插入格式以满足 highlight.js 的要求，源码看这里 https://github.com/wangfupeng1988/wangEditor/blob/master/src/js/menus/code/index.js#L86

第三，至于如何修改，看下 highlight.js 的文档，它其实也是基于`<pre><code>....</code></pre>`的，只不过加了些属性和样式

第四，插入源码之后，你要执行 highlight.js 生成高亮代码的初始化方法，还是刚才看到的从插入代码的地方，在插入之后执行初始化方法即可。

祝你成功！有问题再随时回复。

**Comment by Shmily-HJT** [comment]
谢谢大大指导，顺着大大的思路去弄，还是很快速就解决了。赞一个
