### ISSUE TITLE
可以增加上传PDF，zip等附件的功能吗

### ISSUE THREAD

**Issue by andyroyal520** [wangfupeng1988/wangEditor#1573]
可以增加上传PDF，zip等附件的功能吗

**Comment by wangfupeng1988** [comment]
你去参考邮箱的上传附件功能，单独开发，和编辑器保持独立，否则会出很多问题。

**Comment by wangfupeng1988** [comment]
v5 已经支持上传附件 https://github.com/wangeditor-team/wangEditor-plugin-upload-attachment

v4 不再升级新功能了
