### ISSUE TITLE
这个插件支持CDN方式引用么

### ISSUE THREAD

**Issue by fts11259375** [wangfupeng1988/wangEditor#159]
如果支持的话，可以放到BootCDN上去

**Comment by wangfupeng1988** [comment]
我已经提交到百度cdn，不过至今尚未回复我。你有比较好的免费cdn，也可以推荐给我，不过要知道如何提交进去。

**Comment by wangfupeng1988** [comment]
BootCDN我一直没找到如何添加

**Comment by fts11259375** [comment]
[bootstrap中文网提供的cdn](http://www.bootcdn.cn/)
这个很不错，一直在用，有问题发邮件给他们回复的也很及时

**Comment by wangfupeng1988** [comment]
但是我没找到入口，如何申请添加进去？

**Comment by fts11259375** [comment]
网页最下方有
cdn@bootcss.com 这是他们的email
他们收录的插件都是同步在 [cdnjs](https://github.com/cdnjs/cdnjs)这个仓库里的

**Comment by wangfupeng1988** [comment]
好，感谢提供。我在发布下一个版本时，就往`cdnjs`发送一个`pul request`

**Comment by iROCKBUNNY** [comment]
@wangfupeng1988 所以最后网cdnjs里面提交了么？提交的地方在这里：https://github.com/cdnjs/cdnjs/issues/new?title=%5BRequest%5D%20Add%20library_name&body=**Library%20name%3A**%20%0A**Git%20repository%20url%3A**%20%0A**npm%20package%20name%20or%20url**%20(if%20there%20is%20one)%3A%20%0A**License%20(List%20them%20all%20if%20it%27s%20multiple)%3A**%20%0A**Official%20homepage%3A**%20%0A**Wanna%20say%20something%3F%20Leave%20message%20here%3A**%20%0A%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%0ANotes%20from%20cdnjs%20maintainer%3A%0APlease%20read%20the%20%5BREADME.md%5D(https%3A%2F%2Fgithub.com%2Fcdnjs%2Fcdnjs%23cdnjs-library-repository)%20and%20%5BCONTRIBUTING.md%5D(https%3A%2F%2Fgithub.com%2Fcdnjs%2Fcdnjs%2Fblob%2Fmaster%2F.github%2FCONTRIBUTING.md)%20document%20first.%0A%0AWe%20encourage%20you%20to%20add%20a%20library%20via%20sending%20pull%20request%2C%0Ait%27ll%20be%20faster%20than%20just%20opening%20a%20request%20issue%2C%0Asince%20there%20are%20tons%20of%20issues%2C%20please%20wait%20with%20patience%2C%0Aand%20please%20don%27t%20forget%20to%20read%20the%20guidelines%20for%20contributing%2C%20thanks!!%0A

**Comment by iROCKBUNNY** [comment]
@wangfupeng1988 找到这样一个cdn：https://unpkg.com/wangeditor
