### ISSUE TITLE
是否支持markdown？

### ISSUE THREAD

**Issue by IVANLEE99** [wangfupeng1988/wangEditor#1598]
本人以为不支持md的编辑器都不是很好的编辑器

**Comment by IVANLEE99** [comment]
![image](https://user-images.githubusercontent.com/18308725/41841831-dd1192e4-789b-11e8-962e-919d55d4a5c2.png)

**Comment by wangfupeng1988** [comment]
markdown 插件已经开发完了 https://github.com/wangeditor-team/wangEditor-plugin-md

不过只能用于 [v5](https://www.wangeditor.com/v5/) 。v5 近期会正式发布，v4 不再做功能升级了。
