### ISSUE TITLE
wangEditor用于编辑页面时，编辑区域无法赋值

### ISSUE THREAD

**Issue by jking8866** [wangfupeng1988/wangEditor#16]
wangEditor绑定 textare 后，在编辑页面中，textare可以获取后台传过来的值 但是在wangEditor中无法显示，难道只能通过    $('.wangEditor-textarea').html(‘’后台的值“) ; 这种方式吗 来给编辑区域赋值吗，这样好麻烦

**Comment by wangfupeng1988** [comment]
我讲采纳你的建议，今晚修改。

**Comment by wangfupeng1988** [comment]
已经修改了，可参见 http://www.wangeditor.com/wangEditor/demo/demo-basic.html
