### ISSUE TITLE
大佬， 我知道我不该问，但是真的有需求，我想知道怎么在vue里面去加一个按钮，比如说源码编辑

### ISSUE THREAD

**Issue by Ecareyu** [wangfupeng1988/wangEditor#1600]
大佬， 我知道我不该问，但是真的有需求，我想知道怎么在vue里面去加一个按钮，比如说源码编辑。
这个功能的应用场景在文案需要丰富的移动端页面元素编辑，比如公众号的推文，文案们一直觉得我们的编辑器不好用，所以一直在用第三方的编辑器，比如365编辑器，但有时候我们又要用富文本，所以折中了一下就是开放源码编辑功能给他们，让他们直接拷贝365编辑器编辑好的源码。
但是我不知道怎么在wangEditor3里面去加这个按钮，您给出的案列是非侵入式的方式添加的，我尝试了使用E.xxx = {}类似的方法，但是就是没有反应，不知道能不能给一个基于vue的范例。

**Comment by Guotykaka** [comment]
也很需要这个

**Comment by zmyfrank** [comment]
> 大佬， 我知道我不该问，但是真的有需求，我想知道怎么在vue里面去加一个按钮，比如说源码编辑。
> 这个功能的应用场景在文案需要丰富的移动端页面元素编辑，比如公众号的推文，文案们一直觉得我们的编辑器不好用，所以一直在用第三方的编辑器，比如365编辑器，但有时候我们又要用富文本，所以折中了一下就是开放源码编辑功能给他们，让他们直接拷贝365编辑器编辑好的源码。
> 但是我不知道怎么在wangEditor3里面去加这个按钮，您给出的案列是非侵入式的方式添加的，我尝试了使用E.xxx = {}类似的方法，但是就是没有反应，不知道能不能给一个基于vue的范例。

请问你最后怎么实现的呢？用了其他的编辑器吗？

**Comment by Ecareyu** [comment]
放弃了这个编辑器了，后续专门定制了一个编辑器，还是内嵌百度编辑器
