### ISSUE TITLE
文件上传进度条bug

### ISSUE THREAD

**Issue by fts11259375** [wangfupeng1988/wangEditor#161]
6325行
`$progress.width(pregress * width);`
应改为
`$progress.width(pregress * width/100);`

**Comment by wangfupeng1988** [comment]
我去验证一下。

**Comment by wangfupeng1988** [comment]
相关代码如下：
```
// 这里调用进度条
var percentComplete = e.loaded / e.total;
editor.showUploadProgress(percentComplete);
```

```
// 这里显示进度条
var width = $editorContainer.width();
$progress.width(pregress * width);
```

你为何说要将 `$progress.width(pregress * width);`改为`$progress.width(pregress * width/100);`呢。

**Comment by wangfupeng1988** [comment]
哦。。。我了解你说的意思了。用七牛上传，返回的进度数据是从0到100变化的。
我已经统一将进度信息做成从0到100变化的了，下一个版本发布时，即可看到更新。

**Comment by fts11259375** [comment]
对，我只使用了七牛的，忘记说了哈
