### ISSUE TITLE
和requirejs并用出现问题。

### ISSUE THREAD

**Issue by breezern** [wangfupeng1988/wangEditor#162]
你好。
在引入wangEditor-2.0.14/dist/js/wangEditor.js文件之前，引入requirejs-2.1.20，会出现“Uncaught ReferenceError: wangEditor is not defined” 的问题。如果注释掉requirejs，或者在wangEditor.js之后引用，就完成正常。

**Comment by wangfupeng1988** [comment]
> 在引入wangEditor-2.0.14/dist/js/wangEditor.js文件之前，引入requirejs-2.1.20

如果用requirejs，就无需在引用其他的js了，直接用AMD的方式加载即可呀，不明白你的意思。
你是按照文档 http://www.kancloud.cn/wangfupeng/wangeditor2/113995 中写的吗？

**Comment by zzz999** [comment]
如果和requirejs并用的话必须用requirejs加载js，我用seajs也有这个问题

**Comment by wangfupeng1988** [comment]
> 我用seajs也有这个问题

啥问题？

**Comment by zzz999** [comment]
使用seajs和requirejs时不能直接用script标签引入wangEditor.js文件

**Comment by wangfupeng1988** [comment]
> 使用seajs和requirejs时不能直接用script标签引入wangEditor.js文件

使用seajs和requirejs的目的本来就是为了不手动引用script标签，要不然用它俩干嘛？先照着文档把功能做成功改了。
