### ISSUE TITLE
图片上传按钮能不能自定义按钮功能？不要显示弹窗输入链接等。。

### ISSUE THREAD

**Issue by Mr-SPM** [wangfupeng1988/wangEditor#1631]
如题。

**Comment by He-Polaris** [comment]
如题

**Comment by He-Polaris** [comment]
这位兄台，你的问题解决了吗？

**Comment by Mr-SPM** [comment]
解决是解决了，但是方法很蠢。。

**Comment by fengmangseo** [comment]
> 解决是解决了，但是方法很蠢。。

贴一下代码啊

**Comment by Mr-SPM** [comment]
几百年前的代码了，找不到了

**Comment by Mr-SPM** [comment]
> > 解决是解决了，但是方法很蠢。。
> 
> 贴一下代码啊

几百年前的代码了，找不到了

**Comment by fengmangseo** [comment]
> > > 解决是解决了，但是方法很蠢。。
> > 
> > 
> > 贴一下代码啊
> 
> 几百年前的代码了，找不到了

我搞定了 处理方法有点low 就是直接在注册一个菜单 直接去 .click() 那个上传按钮
