### ISSUE TITLE
报BUG:表格中粘贴文字 点击一次选中单元格不生效，会粘贴到之前光标所在单元格

### ISSUE THREAD

**Issue by Truke** [wangfupeng1988/wangEditor#165]

**Comment by Truke** [comment]
暂时解决办法
`editor.$txt.on('click','table',function(e){
                if($(this).hasClass('clicked')){
                    editor.$txt.blur();
                }
            })`

**Comment by wangfupeng1988** [comment]
恩，看到这个问题了，会跟进解决。解决完了在此回复。

**Comment by wangfupeng1988** [comment]
经查证，该问题是因为粘贴过滤之后用`execCommand`执行插入操作导致的。目前程序判断如果是`td`或者`th`中粘贴内容时，暂时不进行粘贴过滤，直接执行浏览器原生的粘贴操作，即可避免这个问题。
先这样解决吧。

粘贴过滤这块，挺麻烦，还有很多东西需要优化
