### ISSUE TITLE
编辑器产生的富文本出现奇怪的<divcourier>标签

### ISSUE THREAD

**Issue by hanx11** [wangfupeng1988/wangEditor#1659]
编辑器产生的富文本出现奇怪的<divcourier>标签，且标签内属性出现单引号，导致下次初始化富文本时出现html语法错误！
出现的完整标签如下：

<divcourier new',="" monospace;font-weight:="" normal;font-size:="" 20px;line-height:="" 30px;white-space:="" pre;"=""></divcourier>

**Comment by powerProgrammerMa** [comment]
我的也是   粘贴表格 还有很多其他的自定义标签 导致想通过邮件发出去就会说有特殊标签

**Comment by powerProgrammerMa** [comment]
请问解决了吗？

**Comment by peakandyuri** [comment]
为什么要把问题关了呢？
