### ISSUE TITLE
menu-tip 显示不全 ！

### ISSUE THREAD

**Issue by chenshuai2144** [wangfupeng1988/wangEditor#167]
menu-tip 显示不全 ！

  E.$body.append($tempDiv);

修改为 

 $('body').append($tempDiv);

问题就可以解决！

**Comment by wangfupeng1988** [comment]
`E.$body`和`$('body')`其实是一个东西，看看源码就知道了。

你这样做就可以了，我估计是你没有等待页面加载完成之后，就执行了`editor.create()`操作。

**Comment by chenshuai2144** [comment]
我是和react 结合用的！应该不是那方面问题！ 

发自我的 iPhone

**Comment by wangfupeng1988** [comment]
你测试一下，在代码中搜索到 `E.$body` 定义的代码，然后在定义之后立马`console.log`，看看输出的是啥？

**Comment by SoyMeng** [comment]
编辑器元素通过ajax加载就会出现这个问题,比如使用ajax load一个页面的时候。

**Comment by wangfupeng1988** [comment]
@SoyMeng 那你等着ajax success之后在创建编辑器呀

**Comment by SoyMeng** [comment]
@wangfupeng1988 肯定在ready之后才调用create的,1168行处outerWidth值为0,可能是jquery的计算问题,现在的情况来看我倾向于在在初始化编辑器的代码中初始化$body这个全局变量。

**Comment by wangfupeng1988** [comment]
@SoyMeng 

> 现在的情况来看我倾向于在在初始化编辑器的代码中初始化$body这个全局变量。

这个你可以自己控制，直接执行`window.wangEditor.$body = $('body')`即可
