### ISSUE TITLE
自定义菜单后，wangEditor-menu-container高度异常

### ISSUE THREAD

**Issue by mcc108** [wangfupeng1988/wangEditor#170]
在比较窄的地方使用，自定义前菜单有几排，自定义菜单后（只保留一排），.wangEditor-menu-container的高度异常，保持着没自定义之前的几排高度，太高了

**Comment by wangfupeng1988** [comment]
多给几个截图，详细描述一下。或者你直接给一个静态demo。
至少让我能复现问题，看到问题啥样子。

**Comment by mcc108** [comment]
http://zhihuo.coding.io/admin/diyapp.html  内容更改面板

**Comment by wangfupeng1988** [comment]
OK，我看到了，我回去验证这个问题。

**Comment by mcc108** [comment]
在外层加个overflow: hidden;解决了

**Comment by wangfupeng1988** [comment]
> 在外层加个overflow: hidden;解决了

哪个地方加了`overflow: hidden;`，分享一下，我也完善到产品中

**Comment by mcc108** [comment]
textarea的外层....   构成了bfc

**Comment by wangfupeng1988** [comment]
你这个menuContainer高度异常的问题，是怎么复现的，我这里怎么复现不了？给你粘贴一下我的html代码

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>wangEditor2 test</title>
    <link rel="stylesheet" type="text/css" href="../dist/css/wangEditor.min.css">
    <style type="text/css">
        .container {
            width: 300px;
        }
        #div1 {
            width: 100%;
            height: 300px;
        }
    </style>
</head>
<body style="padding:0 20px;">
    <p>wangEditor 多语言 - 自定义菜单</p>
    <div class="container">
        <div id="div1">
            <p>请输入内容222</p>
        </div>
    </div>
    
    
    <script type="text/javascript" src="../dist/js/lib/jquery-1.10.2.min.js"></script>
    <script type="text/javascript" src="../dist/js/wangEditor.js"></script>
    
    <script type="text/javascript">
        $(function () {
            
            var editor = new wangEditor('div1');

            // 自定义菜单
            editor.config.menus = [
                'source',
                'location',
                '|',
                'bold',
                'underline',
                'italic',
                'strikethrough',
                'eraser',
                'forecolor',
                'bgcolor'
            ];

            editor.create();

        });
    </script>
</body>
</html>
```

**Comment by mcc108** [comment]
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>教育信息化创新创业协会 - 重庆邮电大学</title>
    <link rel="stylesheet" href="static/css/style.css" />
    <link rel="stylesheet" href="static/css/bookblock.css">
    <script src="static/js/modernizr.custom.min.js?v2.6.2"></script>
</head>
<body>
<div class="nav">
    <div class="black-shadow"></div>
    
    <div class="top">
        <div class="logo"><a href="index.html"><img src="static/img/logo.png"><h1>教育信息化创新创业协会</h1></a></div>
        <div class="menu-btn"></div>
    </div>
    
    
    <div class="menu">
        <ul>
            <li><a class="active" href="#">主页</a></li>
            <li><a href="#">走进我们</a></li>
            <li><a href="#">作品展示</a></li>
            <li><a href="#">加入我们</a></li>
            <li><a href="#">关于我们</a></li>
        </ul>
        <div class="menu-footer">
            <p>Copyright © 2008-2016 蓝山工作室</p>
            <p>All Rights Reserved</p>
        </div>
    </div>
    
</div>
<div class="header">
    
    <ul class="header-list">
        <li class="active"></li><li></li><li></li>
    </ul>
    <div class="main-btns down-btn"><img src="static/img/down.png"></div>
    
    
    <div id="bb-bookblock" class="bb-bookblock main-box">
        <div class="bb-item">
            <div class="box-item box-1">
                <div class="particles willUp" id="particles-js"></div>
                <div class="box-center">
                    <h1 class="willUp">你好，我们是</h1>
                    <h1 class="willUp">教育信息化创新创业协会</h1>
                    <h1 class="willUp">蓝山工作室</h1>
                    <div class="willUp box-btns">
                        <a href="#" class="box-btn">走进我们</a>
                        <a href="#" class="box-btn">作品展示</a>
                    </div>
                </div>
                <div class="header-flip">
                    <div class="main-btns prev-btn"><img src="static/img/prev.png"></div>
                    <div class="main-btns next-btn"><img src="static/img/next.png"></div>
                </div>
            </div>
        </div>
        <div class="bb-item">
            <div class="box-item box-2">
                <div class="box-center">
                    <h1 class="willUp">介绍视频</h1>
                    <h2 class="willUp">教育信息化创新创业协会</h2>
                    <div class="box-btns">
                        <a href="#" class="willUp box-btn">观看视频</a>
                    </div>
                </div>
                <div class="header-flip">
                    <div class="main-btns prev-btn"><img src="static/img/prev.png"></div>
                    <div class="main-btns next-btn"><img src="static/img/next.png"></div>
                </div>
            </div>
        </div>
        <div class="bb-item">
            <div class="box-item box-3">
                <div class="box-center">
                    <h1 class="willUp">介绍视频</h1>
                    <h2 class="willUp">教育信息化创新创业协会</h2>
                    <div class="box-btns">
                        <a href="#" class="willUp box-btn">观看视频</a>
                    </div>
                </div>
                <div class="header-flip">
                    <div class="main-btns prev-btn"><img src="static/img/prev.png"></div>
                    <div class="main-btns next-btn"><img src="static/img/next.png"></div>
                </div>
            </div>
        </div>
    </div>
    
</div>

<div class="container">
    <h1 class="willUp">协会简介</h1>
</div>





<script src="static/js/jquery.min.js"></script>
<script src="static/js/jquery.bookblock.js"></script>
<script src="static/js/jquery.mousewheel.min.js"></script>
<script src="static/js/particles.min.js"></script>
<script src="static/js/app.js"></script>
</body>
</html>

**Comment by mcc108** [comment]
```
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>wangEditor2 test</title>
    <link rel="stylesheet" type="text/css" href="demo/wangEditor.min.css">
    <style type="text/css">
        #div0 {
            float: left;
            width: 200px;
            height: 100px;
        }
        .container {
            width: 500px;
            margin-left: 200px;
        }
        #div1 {
            width: 100%;
            height: 300px;
        }
    </style>
</head>
<body style="padding:0 20px;">
    <p>wangEditor 多语言 - 自定义菜单</p>
    <div id="div0"></div>
    <div class="container">
        <div id="div1">
            <p>请输入内容222</p>
        </div>
    </div>


    <script type="text/javascript" src="demo/jquery.min.js"></script>
    <script type="text/javascript" src="demo/wangEditor.min.js"></script>

    <script type="text/javascript">
        $(function () {

            var editor = new wangEditor('div1');

            // 自定义菜单
            editor.config.menus = [
                'source',
                'location',
                '|',
                'bold',
                'underline',
                'italic',
                'strikethrough',
                'eraser',
                'forecolor',
                'bgcolor'
            ];

            editor.create();

        });
    </script>
</body>
</html>
```

**Comment by wangfupeng1988** [comment]
知道了，晚上回去试试

**Comment by wangfupeng1988** [comment]
直接在`textarea`的外层增加`overflow:hidden`会导致其他问题的，其实你的这个`<div id="div0"></div>`有`float:left`就不该直接暴露出来，要经过`clearfix`的包裹。如下代码：

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>wangEditor2 test</title>
    <link rel="stylesheet" type="text/css" href="../dist/css/wangEditor.min.css">
    <style type="text/css">
        /* 定义 clearfix */
        .clearfix:after {
            content: '';
            display: table;
            clear: both;
        }
        #div0 {
            float: left;
            width: 200px;
            height: 100px;
        }
        .container {
            width: 300px;
        }
        #div1 {
            width: 100%;
            height: 300px;
        }
    </style>
</head>
<body style="padding:0 20px;">
    <p>wangEditor 多语言 - 自定义菜单</p>
    <!-- 使用clearfix包裹住float层 -->
    <div class="clearfix">
        <div id="div0"></div>
    </div>
    <div class="container">
        <div id="div1">
            <p>请输入内容222</p>
        </div>
    </div>
    
    
    <script type="text/javascript" src="../dist/js/lib/jquery-1.10.2.min.js"></script>
    <script type="text/javascript" src="../dist/js/wangEditor.js"></script>
    
    <script type="text/javascript">
        $(function () {
            
            var editor = new wangEditor('div1');

            // 自定义菜单
            editor.config.menus = [
                'source',
                'location',
                '|',
                'bold',
                'underline',
                'italic',
                'strikethrough',
                'eraser',
                'forecolor',
                'bgcolor'
            ];

            editor.create();

        });
    </script>
</body>
</html>
```
