### ISSUE TITLE
移动版本使用过程中遇到工具栏点击不能显示

### ISSUE THREAD

**Issue by winworm** [wangfupeng1988/wangEditor#172]
在使用过程中遇到一个问题，不知道是不是个bug，具体如下：
比如定义容器container的高度是固定的，开始都是正常的，但是如果输入足够内容后超出container的高度后富文本工具条 就不能显示了，总是一闪而过。

**Comment by wangfupeng1988** [comment]
移动端许久没有维护了，用的人也很少，毕竟在移动端没有那么多人编辑内容，都是在pc端做。

目前完全借助js的功能，还无法实现一个完善的移动端的编辑器，因此有些事儿一直搁置着。

待我把pc端2.0的一些其他基本需求都完成的差不多之后，我会将移动端整合到pc端来，做一个响应式的布局。

所以，移动端的问题还得再等等。精力有限，望谅解！
