### ISSUE TITLE
编辑图片，选择太小，可否做成输入框，让用户自定义输入百分比

### ISSUE THREAD

**Issue by soulCoke** [wangfupeng1988/wangEditor#1727]
![image](https://user-images.githubusercontent.com/30195403/45476330-49137700-b771-11e8-833e-6adf2c32f7d3.png)

**Comment by coolRoger** [comment]
请问怎么解决的?

**Comment by JhonYoung** [comment]
同问

**Comment by LoveEocding** [comment]
too
