### ISSUE TITLE
自定义图片宽度也是个不错的选择，实在没办法就自己手动改了

### ISSUE THREAD

**Issue by soulCoke** [wangfupeng1988/wangEditor#1728]
![383k0plxqf sx1jlou5ytsl](https://user-images.githubusercontent.com/30195403/45482149-d3fb6e00-b77f-11e8-9e15-cbb4977b3228.png)

**Comment by JhonYoung** [comment]
改的源码？

**Comment by soulCoke** [comment]
是的。改了一下源码、你可以根据汉字搜索一下，很容易的

**Comment by JhonYoung** [comment]
Thx

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: soulCoke <notifications@github.com>
发送时间: Friday, June 14, 2019 5:09:54 PM
收件人: wangfupeng1988/wangEditor
抄送: JhonYoung; Comment
主题: Re: [wangfupeng1988/wangEditor] 自定义图片宽度也是个不错的选择，实在没办法就自己手动改了 (#1728)


是的。改了一下源码、你可以根据汉字搜索一下，很容易的

―
