### ISSUE TITLE
ie8下seajs不兼容

### ISSUE THREAD

**Issue by 328080339** [wangfupeng1988/wangEditor#173]
seajs中的define函数是挂在window对象下的,即window.define=xxxxxxx
而您的插件首行重新定义了一遍define(var define)
在其它浏览器下这么做事没问题的,但ie8下，var关键字声明的变量优先于window。
请自测如下代码即可验证。
```
<script>
    window.x=10; 
</script>
<script>
    var x; 
</script>
<script>
   alert(x);
</script>
```
解决方法很简单。。。其实您干脆就直接删了var define得了。

**Comment by wangfupeng1988** [comment]
哦，知道了。感谢反馈，我会尽快修复的。

**Comment by wangfupeng1988** [comment]
已经将`var define`去掉了，今晚发布，明天下载最新版本即可。

**Comment by 328080339** [comment]
OK!非常感谢
