### ISSUE TITLE
拖拽图片，改变大小不生效

### ISSUE THREAD

**Issue by RyanPoy** [wangfupeng1988/wangEditor#174]
- 插入一个网络图片。
- 调整大小
  - 如果是用拖拽的方式调整图片大小，最后保存的时候，永远保存不了这个大小
  - 如果是用点击图片边框的 "+" (放大) 图标，最后保存的时候，就可以保存。

**Comment by wangfupeng1988** [comment]
不会吧，拖拽完了之后，源代码中的`<img>`标签会有高度和宽度的属性，例如`<img style="max-width: 100%; width: 504px; height: 155px;" src="http://news.baidu.com/resource/img/logo_news_276_88.png?date=20150104" class="">`

保存的时候，将这一串html代码保存到数据库中，再显示的时候，图片自然就有固定大小了。

其实点击"+" (放大) 图标和拖拽改变大小，都是通过修改`<img>`标签的`width`和`height`属性来修改图片大小的，一个道理。
