### ISSUE TITLE
一开始进入，用鼠标全选并删除，onchange不触发 （作者能不能加入oninput监听？）

### ISSUE THREAD

**Issue by herotony008** [wangfupeng1988/wangEditor#1749]
编辑器创建并赋值内容，当用鼠标全选，并且鼠标失去焦点（是在编辑器框架外失去焦点），此时按DEL键删除， 不会触发onchange事件，（目前编辑器里面显示的内容已经为空）。但是 如果失去焦点是在编辑器里面，则会触发

**Comment by herotony008** [comment]
一开始就用鼠标左键选中全部，并在编辑器外松开鼠标左键，点删除，才能复现这个问题。（不要在一开始，点击后再去操作，这时候不能复现这个问题）

**Comment by lqwzjay** [comment]
问题解决了吗，我也遇到了同样的问题，第一次进去鼠标选中后 键盘删除，没有触发onchnage事件

**Comment by eeeeeeeason** [comment]
我认为原因是点击事件由mousedown,mouseup都在元素内时触发，但若第一次鼠标抬起时在元素外，认为没有触发点击事件，点击事件会开始onchange，我们改第一次down为人为触发click即可
@lqwzjay 处理偏方如下

mousedown触发编辑框里面p标签click()函数、

**Comment by qilvnuanqingyou** [comment]
@eeeeeeeason 感谢大神，按你的思路解决了，太感谢了，贴上我的代码，有空请指教
`let trigger = function (element, event, data) {
            element.dispatchEvent(new CustomEvent(event, {detail: data, bubbles: true, cancelable: true}));
        }
        this.$refs.editor.addEventListener('mousedown', (e) => {
            trigger(e.target, 'click');
        });`

**Comment by duansj** [comment]
+1

**Comment by nanaismylove** [comment]
这个问题在react 怎么解决？

**Comment by pollux2015** [comment]
@eeeeeeeason 确实可以

**Comment by Johnbeir** [comment]
> 我认为原因是点击事件由mousedown,mouseup都在元素内时触发，但若第一次鼠标抬起时在元素外，认为没有触发点击事件，点击事件会开始onchange，我们改第一次down为人为触发click即可
> @lqwzjay 处理偏方如下
> 
> mousedown触发编辑框里面p标签click()函数、

大神，可以具体说说怎么实现吗？mousedown事件要绑定在p标签吗？可否展示个代码？

**Comment by Johnbeir** [comment]
> 触发编辑框里面p标签click()函数

如何触发p标签的click函数这个可以给个代码吗？不是很明白
