### ISSUE TITLE
实现单独调用 wangEditor 上传相关组件的需求

### ISSUE THREAD

**Issue by xingwen1987** [wangfupeng1988/wangEditor#175]
目前有一个需求：
       需要开发一套新闻发布系统，新闻内容里有【首页焦点图】、【列表展示图】、【专题大图】，以及新闻内容。
       考虑到现在市面上的上传控件对不同浏览器的兼容性不同，并且担心上传控件与其他JS冲突，使用编辑器自带的上传控件，既能减少页面体积，也不用担心页面的兼容性。
       目前，百度上针对 Ueditor 单独调用上传控件的帖子、文章很多，可以看到这个功能确实非常方便大家使用。
       我实现 Ueditor 单独调用上传组件的方式如下：
       1、在一个隐藏的div容器里初始化一个编辑器；
       2、`
uploader.ready(function () {
               uploader.addListener("contentChange", function () {
               setTimeout(function () {
                   // 实现上传成功后处理的方法
                 }, 10);
               });
            });
`
       3、通过以下两种方式：
                · `$("#元素ID .edui-for-simpleupload iframe").contents().find("input").click();`
                · `var myImage = uploader.getDialog("insertimage"); myImage.open();`
             的方式呼出上传界面，实现上传功能。

请问 wangEditor 可以实现这个功能吗？

**Comment by wangfupeng1988** [comment]
简单开放这么一个接口，用隐藏编辑器的方式只实现上传，监听上传事件并注入自定义函数——这些都没有问题，有不麻烦。

问题是——如果把这个开放，就相当于开放了一个上传功能的大入口。虽然你目前的需求比较简单，但是不难保证你日后的需求比较多，例如增加上传大小限制、上传事件的配置、甚至任何plupload里有的功能——即便你不会要，其他使用者也难免会要求比较多。

我曾经经历过类似的事情，对这方面还是深有感触的。

因此——上帝的归上帝，凯撒的归凯撒。你在页面中同时使用wangEditor和plupload，配置好了肯定没有问题。有问题你找我，我来完善编辑器。

当然，编辑器目前支持插件机制，你可以自己去试着实现一下编辑器的这种机制，有需要我会尽力支持。

**Comment by xingwen1987** [comment]
确实，这种需求也肯定是从简到复杂，老王想的很周到，赞！那我就用老王推荐的plupload试试。
