### ISSUE TITLE
WORDPRESS

### ISSUE THREAD

**Issue by bymichi** [wangfupeng1988/wangEditor#177]
請問這個編輯器可以在WORDPRESS上使用嗎？
第一次接觸這樣的編輯器不太敢亂動，個人相當喜歡這款，簡單而漂亮！

**Comment by wangfupeng1988** [comment]
我没用过wordpress，所以不知道是否可以很方便的用在wordpress中。但是如果wordpress支持插件机制，那肯定是可以用上的。前端很简单了，一看就明白，后台涉及到一个图片上传，提供一个接口就是了。

QQ群里面我记得貌似有个人弄过集成wordpress，最后结果如何，我忘记了。
