### ISSUE TITLE
复制文本或图片，在原焦点处单击，第一次粘贴不上

### ISSUE THREAD

**Issue by Truke** [wangfupeng1988/wangEditor#178]
**第一步：初始化**
![image](https://cloud.githubusercontent.com/assets/5698496/13844459/d63eeb5c-ec74-11e5-84e1-6cd8e5fdc419.png)
**第二步：选择文本**
![image](https://cloud.githubusercontent.com/assets/5698496/13844495/fd71fc82-ec74-11e5-9188-f807810f5c1f.png)
**第三步：原地点击，并粘贴，显示如下**
![image](https://cloud.githubusercontent.com/assets/5698496/13844563/57b972ec-ec75-11e5-968a-0915fb3254a0.png)
**继续ctrl+v粘贴，显示正常**
![image](https://cloud.githubusercontent.com/assets/5698496/13844586/7c7bd958-ec75-11e5-8368-e9b2affd530d.png)

**Comment by wangfupeng1988** [comment]
拒绝回答`一句话问题`

**Comment by wangfupeng1988** [comment]
OK  我看到问题了，记录下来，我查一查原因

**Comment by wangfupeng1988** [comment]
问题已经修复，可下载最新版本验证 https://github.com/wangfupeng1988/wangEditor/releases
也可以直接去官网demo http://wangeditor.github.io/ 验证一下
