### ISSUE TITLE
【bug】editor.showUploadProgress里的width不对

### ISSUE THREAD

**Issue by xcheese** [wangfupeng1988/wangEditor#179]
$progress.width(pregress * this.$editorContainer.width()); //暂时这么处理了，是上下文作用域不对吧？

**Comment by wangfupeng1988** [comment]
源码中是这么定义的`var width = $editorContainer.width();`，和你这里直接写成`this.$editorContainer.width())`是一样的。只不过，源码中获取width是在`editor.create()`之后立即获取的（因为所有的插件函数都会在`editor.create()`之后被执行），而你这里是随时计算随时获取的（性能差）。

你之所以遇到这个问题，肯定是在`editor.create()`之后执行`var width = $editorContainer.width();`时没有获取正确的width，怀疑你没有等待页面加载完成就创建编辑器了。

所以，你得先确定一下这个问题。
