### ISSUE TITLE
iPad上面 编辑时无法聚焦  要双击或者长按才可以

### ISSUE THREAD

**Issue by ajiaosong** [wangfupeng1988/wangEditor#1792]
iPad上面 编辑时无法聚焦  要双击或者长按才可以

**Comment by ajiaosong** [comment]
已经找到问题  其他插件影响到了

**Comment by Primers-cern** [comment]
> 已经找到问题 其他插件影响到了

你好，能说说具体影响的原因吗，我也遇到了这个问题，使用了截图插件之后，再聚焦到普通input文本框，之后富文本就不能聚焦了，感谢回复！
