### ISSUE TITLE
插入图片后获取的内容如何解析

### ISSUE THREAD

**Issue by alixh213** [wangfupeng1988/wangEditor#18]
<p>啊大师级的骄傲是</p><p><br></p><p>发生都 &nbsp;家覅是的覅几艘的 &nbsp; i偶的法搜地方到死&nbsp;</p><img id="88107137568295" src="/Admin/Public/uploadimg/article/1/1437117665.jpg" i2s_init="true" i2s_selected="true" i2s_guid="36fa32e5-31b5-027d-892a-71fb56a6715a" i2s_untagged="true"><p><br></p><p>教师的房间嗖地</p><p><img id="011354031739756465" src="/Admin/Public/uploadimg/article/1/1437117676.jpg" i2s_init="true" i2s_filters="{&quot;OR&quot;:[{&quot;property&quot;:&quot;width&quot;,&quot;operator&quot;:&quot;&lt;=&quot;,&quot;value&quot;:&quot;150&quot;,&quot;weight&quot;:-20},{&quot;property&quot;:&quot;offsetWidth&quot;,&quot;operator&quot;:&quot;&lt;=&quot;,&quot;value&quot;:&quot;50&quot;,&quot;weight&quot;:-20},{&quot;property&quot;:&quot;height&quot;,&quot;operator&quot;:&quot;&lt;=&quot;,&quot;value&quot;:&quot;150&quot;,&quot;weight&quot;:-20},{&quot;property&quot;:&quot;offsetHeight&quot;,&quot;operator&quot;:&quot;&lt;=&quot;,&quot;value&quot;:&quot;50&quot;,&quot;weight&quot;:-20}]}"></p><p>打算的撒打算打算打</p><p><img id="8541711906436831" src="/Admin/Public/uploadimg/article/1/1437117685.jpg" i2s_init="true" i2s_filters="{&quot;OR&quot;:[{&quot;property&quot;:&quot;width&quot;,&quot;operator&quot;:&quot;&lt;=&quot;,&quot;value&quot;:&quot;150&quot;,&quot;weight&quot;:-20},{&quot;property&quot;:&quot;offsetWidth&quot;,&quot;operator&quot;:&quot;&lt;=&quot;,&quot;value&quot;:&quot;50&quot;,&quot;weight&quot;:-20},{&quot;property&quot;:&quot;height&quot;,&quot;operator&quot;:&quot;&lt;=&quot;,&quot;value&quot;:&quot;150&quot;,&quot;weight&quot;:-20},{&quot;property&quot;:&quot;offsetHeight&quot;,&quot;operator&quot;:&quot;&lt;=&quot;,&quot;value&quot;:&quot;50&quot;,&quot;weight&quot;:-20}]}"></p><p><br></p><p><br></p>

除了第一张图以外后面的图片标签都出现了:&quot;150&quot;,&quot;weight&quot;:-20}这样的东西，请问要怎么解析

**Comment by alixh213** [comment]
上面对我的标签直接解析了，反正就是输出的东西多了很多:&quot;offsetWidth&quot;,&quot;operator&quot;:&quot;&lt;=&quot;,&quot;value&quot;
这些东西，求解

**Comment by alixh213** [comment]
“:&quot;offsetWidth&quot;,&quot;operator&quot;:&quot;&lt;=&quot;,&quot;value&quot;”

**Comment by alixh213** [comment]
自己解决了，用正则删除了多余的东西！！！

**Comment by wangfupeng1988** [comment]
我没看明白你的问题是什么

**Comment by zhougch5** [comment]
图片不能调节大小吗？

**Comment by wangfupeng1988** [comment]
@zhougch5 可以呀，点击图片，右下角又一个小三角，可以拖拽调节大小的

**Comment by zhougch5** [comment]
恩，我细看一下，为的editor界面点个赞！！！
