### ISSUE TITLE
浏览器复制粘贴的图片，在富文本中会先显示原图，再在原图后插入上传后的图片，版本2.0.16

### ISSUE THREAD

**Issue by Ttou** [wangfupeng1988/wangEditor#180]
![000-fs8](https://cloud.githubusercontent.com/assets/4298437/13869769/0ab65296-ed13-11e5-8c34-a7fc6fff76db.png)

**Comment by wangfupeng1988** [comment]
浏览器是哪一个？

**Comment by Ttou** [comment]
win7 64位
chrome 49.0.2623.75

**Comment by Ttou** [comment]
![001-fs8](https://cloud.githubusercontent.com/assets/4298437/13872814/0a271382-ed28-11e5-9566-9e9822648c1f.png)

**Comment by wangfupeng1988** [comment]
我试过两种方式复制图片，但是粘贴到编辑器都没有你说的问题。

使用 chrome 浏览器。

第一种，在一个其他网页上拖拽选择一张图片，复制，然后到编辑器中粘贴，结果编辑器中得到一张图片。查看源码是 `<h2><p><a href="http://yulezibenlun.baijia.baidu.com/article/366692" target="_blank"><img src="http://e.hiphotos.baidu.com/news/crop%3D0%2C0%2C640%2C384%3Bw%3D638/sign=a393c7688d82b90129e299734ebd8547/0d338744ebf81a4c3d600086d02a6059252da62b.jpg"></a></p><br></h2><p><br></p>`

第二种，在一个其他网页上右击一副图片，然后在右击菜单中点击『复制图片』，然后到编辑器中粘贴，页只得到一张图片。查看源码是`<p><img src="http://localhost:8011/uploadfiles/5274675777181983.png" style="max-width:100%;"><br></p><p><br></p>`

你的复现场景是啥，能详细描述一下吗？

**Comment by Ttou** [comment]
就是你说的第二种情况会出现问题

**Comment by wangfupeng1988** [comment]
我在windows电脑上的chrome复现了这个问题了，之前在mac上没有复现。今天我就查一下这个问题，fixed之后在此回复。

**Comment by Ttou** [comment]
好的

**Comment by wangfupeng1988** [comment]
已经修复，去下载最新版本即可 https://github.com/wangfupeng1988/wangEditor/releases

**Comment by Ttou** [comment]
试了下，问题已解决

**Comment by miaozikeji** [comment]
你好，这个版本也发现这个bug，也是复制后两张，vue3环境，
![image](https://user-images.githubusercontent.com/61998207/199208778-42a25a7a-df99-4645-8d96-c8706dfc1755.png)
![image](https://user-images.githubusercontent.com/61998207/199209071-5ec19855-58ab-4192-8f37-2c0b0f78bcbc.png)
