### ISSUE TITLE
当内容超出一页时，工具栏会显示阴影，这会把内容区域往下顶1px

### ISSUE THREAD

**Issue by Ttou** [wangfupeng1988/wangEditor#181]
![000-fs8](https://cloud.githubusercontent.com/assets/4298437/13874473/1d10c05a-ed33-11e5-9075-a0edfaea2fef.png)

可以把工具栏的属性设为absolute

**Comment by wangfupeng1988** [comment]
> 这会把内容区域往下顶1px

我还没有发现这样有啥问题，会导致什么样的结果，你可以在此描述一下带来的问题。

至于把工具栏设置为absolute，这个我还不能随便就设置了。因为position的改变可能会导致其他一些元素的position问题。最好能用其他方式解决。
