### ISSUE TITLE
关于列表的标题大小问题

### ISSUE THREAD

**Issue by chenmuen** [wangfupeng1988/wangEditor#182]
你好，最近在使用wangEditor写网页，我在使用过程中发现了这些问题：
1.在将文字列表化之后，如果连续的点标题1，字体都会持续的加大
![image](https://cloud.githubusercontent.com/assets/11451833/13897248/a5162f72-ede6-11e5-9b34-9b9d8b1286c9.png)
![image](https://cloud.githubusercontent.com/assets/11451833/13897277/45ab1aec-ede7-11e5-87fa-cee7320d5640.png)
2. 并且在点击标题之后，如果是数字列表，则所有的数字都会被置为1
![image](https://cloud.githubusercontent.com/assets/11451833/13897262/ffafc25e-ede6-11e5-9346-da85bc46c9b6.png)
3. 想知道如果设为了标题该如何还原成正文？

**Comment by wangfupeng1988** [comment]
想同时使用列表和标题（像word里面似的）我看是不行了，目前编辑器还不足以支持到这么复杂的程度，而且目前来看，页没有必要这样支持，因为这样使用的用户比较少。

一般设置了标题，就不会在设置列表。而使用列表的地方，也不会使用标题。

最后，设置了标题之后再还原为正文，可使用`清除格式`功能。
