### ISSUE TITLE
关于撤销输入会清空内容的问题ctrl + z

### ISSUE THREAD

**Issue by lgd5555** [wangfupeng1988/wangEditor#183]
ctrl + z 会把所有输入的内容去除掉，我看了下百度的编辑器，输入一段后只会撤销上一段编辑的内容

**Comment by wangfupeng1988** [comment]
OK 我会近期查询这个问题

**Comment by wangfupeng1988** [comment]
问题已经修复，现在使用`ctrl+z`和点击『撤销』菜单是一个效果了
可下载最新版本验证 https://github.com/wangfupeng1988/wangEditor/releases
