### ISSUE TITLE
上传图片到服务器跨域问题，报403

### ISSUE THREAD

**Issue by mahaMT** [wangfupeng1988/wangEditor#1831]
用谷歌浏览器报403
![image](https://user-images.githubusercontent.com/28173343/50465849-e7e87a00-09d4-11e9-9cce-68b0bafb316b.png)
用IE就可以上传不报错
withCredentials 设置 true or false 都没用

我本地调用接口不出现403 的问题

**Comment by issaTan** [comment]
你跨域了啊，跟编辑器没有关系

**Comment by mahaMT** [comment]
> 你跨域了啊，跟编辑器没有关系

可是我不用编辑器正常调接口没问题的。。

**Comment by mahaMT** [comment]
> 你跨域了啊，跟编辑器没有关系
是不是还有什么设置没设置呢，我文档都看了几遍了
