### ISSUE TITLE
IE下插入表格报错

### ISSUE THREAD

**Issue by gotanksgn** [wangfupeng1988/wangEditor#184]
chrome中没有问题，但是在IE11中插入表格报错。
初步怀疑是jquery的问题，版本为1.9
将4711行
editor.command(e, 'insertHtml', tableHtml);
改为
editor.command(e, 'insertHtml', $.parseHTML(tableHtml));
后，IE中使用正常，但是chrome中会插入
[object Text],[object HTMLTableElement],[object Text]

**Comment by wangfupeng1988** [comment]
我尽快查证，fixed之后在此回复你

**Comment by wangfupeng1988** [comment]
问题已经修复，可下载最新版本验证 https://github.com/wangfupeng1988/wangEditor/releases

---

说明一下：这个bug是IE的一个异常，其他浏览器不常见。我使用`try..catch..`屏蔽了这个异常，但是不影响正常功能的使用。
