### ISSUE TITLE
disable禁用编辑器后，图片仍可以删除

### ISSUE THREAD

**Issue by gotanksgn** [wangfupeng1988/wangEditor#185]
禁用编辑器后，点击图片自带的菜单仍可删除图片，不太合理。

**Comment by wangfupeng1988** [comment]
OK 我尽快调查这个问题，fixed之后在此回复你。

**Comment by wangfupeng1988** [comment]
问题已经修复，可下载最新版本验证 https://github.com/wangfupeng1988/wangEditor/releases
