### ISSUE TITLE
连续复制两个带样式的表格， 后面的样式会把前面表格的样式覆盖掉，样式错乱

### ISSUE THREAD

**Issue by xxShawn** [wangfupeng1988/wangEditor#1855]
![_15477779693731](https://user-images.githubusercontent.com/16178276/51361727-e4e03580-1b0b-11e9-96ce-9ac88ebb8cc6.png)
![_15477780963050](https://user-images.githubusercontent.com/16178276/51361733-ead61680-1b0b-11e9-9260-2a22a0b56c53.png)

1. 连续复制两个带样式的表格， 第二个表格的样式会把第一个表格的样式覆盖
2. 删除表格之后， 表格样式没有删除掉， 重新粘贴的新的表格，也会导致样式与之前的表格样式冲突， 导致表格样式错乱

**Comment by q378532364** [comment]
V4 即将发布，已解决该问题，感谢反馈
