### ISSUE TITLE
通过id选择器获取富文本对象

### ISSUE THREAD

**Issue by zly1988203** [wangfupeng1988/wangEditor#186]
是否能通过id选择器获取富文本选择器对象，或者提供一种方式获取这个对象；

**Comment by wangfupeng1988** [comment]
> 是否能通过id选择器获取富文本选择器对象，或者提供一种方式获取这个对象；

你说的这个『对象』是什么对象，编辑器对象还是编辑区域的dom对象，还是其他？需要它的什么属性和方法，你要用它来干嘛？
有问题一定要描述清楚。

**Comment by zly1988203** [comment]
我想获取编辑器对象，能用编辑器提供的方法属性；

主要是目前的一个问题，我在主页面弹出一个modal，modal里面使用到了富文本框，富文本框的对象的声明创建是在主页面监控到modal已经渲染完了之后，是在主页的。
我现在要在modal对应的js里面使用这个对象，所以想看能不能简单的拿到这个对象

**Comment by wangfupeng1988** [comment]
不能通过`id`获取到这个对象。

有很多种方式来拿到editor对象吧，再不济，你把editor赋值为window的一个属性，用window.editor取也行啊。

**Comment by zly1988203** [comment]
不知道有其他人反馈这个问题没有，提示我不能重复引用
 alert('一个页面不能重复引用 wangEditor.js 或 wangEditor.min.js ！！！');

**Comment by wangfupeng1988** [comment]
注意，不同的问题请单独提。这个 `alert('一个页面不能重复引用 wangEditor.js 或 wangEditor.min.js ！！！');` 不是已经清楚的告诉你了吗，你页面引用了两次js脚本。
