### ISSUE TITLE
IE9下图片上传不弹文件选择框

### ISSUE THREAD

**Issue by panchuang** [wangfupeng1988/wangEditor#187]
IE9下图片上传不弹文件选择框

**Comment by wangfupeng1988** [comment]
请把问题描述的再详细一些：你的机器环境？有没有错误提示？是否将编辑器集成到项目中了？单纯做一个demo是否会有这个问题？官网demo是否复现这个问题？从github上下载源码本地运行demo会不会有这个问题？

我晚上回去复现一下，不过记得之前IE9是可以正常访问的，不一定能复现。

**Comment by wangfupeng1988** [comment]
我用我电脑的IE9试了一下，没有发现不弹出的问题。而是发现弹出的modal定位有问题，可能会导致modal不在浏览器的显示范围之内。
我周末修复这个问题

**Comment by wangfupeng1988** [comment]
上面我说的定位问题，已经解决了，可去官网demo验证一下。

下载最新版本使用 https://github.com/wangfupeng1988/wangEditor/releases

有问题再继续反馈。
