### ISSUE TITLE
咨询两个使用上的问题

### ISSUE THREAD

**Issue by admail30** [wangfupeng1988/wangEditor#188]
你好，主要是对CSS方面不是很熟，想咨询两个使用上的问题
1. 每行文字过长的时候，开始出现了横向滚动条，稍许不太便利，是否可以自动换行到下一行？有这个选项配置吗？还是需要我单独设置 textarea 的 style ?  另外行间距感觉有一点高，貌似是 1.8, 在 css 里 p 上设置的，这个要想改动，依然是通过复用一个 css 来修改吗？参考了帮助文档中的『自定义表格、引用、代码的样式』

2. 插入金星表情后，后面在写文字对齐变成了在金星图片表情的中间位置。回车换行后，第二行的文字和金星的图片有稍微的重叠，这里可以调整吗？譬如，金星表情后面的文字与金星表情的底部对齐，新行不会与图片有重叠？

谢谢

**Comment by wangfupeng1988** [comment]
**1. 文字过长不会换行的问题。**在chrome中正常输入汉字，长了是会换行的。你如果一致输入英文或者数字，中间没有空格，浏览器就默认为一个长单纯，可能就不换行。如果我描述的和你的情况不符，请确定你的浏览器访问官网demo是否也有问题，如果也有问题，请给出浏览器信息和截图。

**2. 行间距问题。** 有两种方式，一种可以自己用css自行调整一个默认值，另一种可以引入『行间距』菜单，让用户调整，具体看文档。

**3. 插入金星表情的问题。** 金星表情其实就是一个比较大一点的gif动画图片而已，在后面输入文字，肯定会在图片的中间位置，这个是浏览器默认的，任何图片都会这样。另外，你说有重叠的问题，我没有看到，首先你需要确认看看官网demo是否也有重叠现象，如果也有，请给出浏览器信息和截图。

**Comment by admail30** [comment]
1. 文字过长不会换行的问题。
   - chrome/safari  : 汉字，英文，数字均无问题，可换行
   - firefox :  汉字没有问题，英文不换行

3. 插入金星表情的问题。此问题也只在 firefox  上
   - 确切说不是重叠问题，应该是没有上下间距了的问题。测试用例：插入后回车，在下一行敲 『天天向上』，就能看到 『天』字最上面的横与图片下边缘没有间距，导致阅读时误认为是『大』字。

所有测试均在 官网的demo 页面上测试

**Comment by wangfupeng1988** [comment]
我晚上查这个问题

**Comment by wangfupeng1988** [comment]
先回复一下我排查的结果。

**1. firefox : 汉字没有问题，英文不换行**

你如果输入一长串英文，不换行是因为浏览器以为是一个长单词。但是你如果输入一些正常的英文文章，单词之前有空格，那样换行就没有问题了。所以这不算是一个bug；

**2. 插入金星表情的问题。此问题也只在 firefox 上**

这个问题是firefox浏览器兼容性上的一个问题，我之前没有注意到。即，在chrome上插入金星表情然后换行，源码会是这样`<p><img src="../static/jinxing/1.gif"/></p><p>天天向上</p>`，而在firefox下，源码是这样`<p><img src="../static/jinxing/1.gif"/><br/>天天向上</p>`，看出区别了吧


我这周末将解决这个问题。

**Comment by wangfupeng1988** [comment]
上面说的插入金星表情导致的文字和图片间距太小的问题，已经解决了，可去官网demo验证一下。

下载最新版本使用 https://github.com/wangfupeng1988/wangEditor/releases

有问题再继续反馈。
