### ISSUE TITLE
还是关于撤销的问题，发现两个问题

### ISSUE THREAD

**Issue by lgd5555** [wangfupeng1988/wangEditor#190]
使用编辑自带的撤销有时候会出现下面两个图中的问题文字撤消后变成了拼音
![2](https://cloud.githubusercontent.com/assets/13177391/14057415/bb3eb7c6-f339-11e5-93ff-ee3a6393a45c.jpg)
![3](https://cloud.githubusercontent.com/assets/13177391/14057413/b5d88f50-f339-11e5-82a9-76ca4f9932fe.jpg)

使用ctrl+z的撤销方式会出现下图中问题，编辑器外边出现一个竖线，再次输入会消失
![qq 20160326095615](https://cloud.githubusercontent.com/assets/13177391/14057414/b771324a-f339-11e5-9a86-11b68fe54866.jpg)

**Comment by wangfupeng1988** [comment]
OK，我来排查。你浏览器和系统是什么，补充说明一下。

**Comment by lgd5555** [comment]
好的
浏览器：谷歌 版本 49.0.2623.87 m
系统：win10

**Comment by wangfupeng1988** [comment]
这个问题拖了三条没有查，这几天瞎忙活其他的了。你先别着急，一有时间我就先排插这个问题，这个的优先级还是比较高的。

**Comment by lgd5555** [comment]
OK

**Comment by wangfupeng1988** [comment]
实在抱歉，你说的这两个问题暂时都不好解决。

1. 撤销出现拼音这个问题，是因为拼音打字时，打了拼音，然后停顿了1秒钟以上，再生成汉字。此时撤销就会有问题。这个问题暂时还解决不了，因为js无法判断用户正在输入英文还是输入拼音。其实我们在sublime时，输入汉字，撤销也会遇到这个问题。

2. chrome浏览器右侧的竖线，我查了半天没找到什么原因造成的，这个问题firefox我没有发现。这个我接下来再跟踪吧，这种奇葩的东西，一时也急不得。

----

另外，我自己又发现了另外的两个于『撤销』有关的问题，我已经修改了，可去下载最新代码来更新：https://github.com/wangfupeng1988/wangEditor/releases

感谢你的反馈，有问题可继续反馈给我。
