### ISSUE TITLE
一个插入长图片出现编辑框的问题

### ISSUE THREAD

**Issue by lgd5555** [wangfupeng1988/wangEditor#191]
插入一般大小的图片，图片右下角有个圆点可以拖拽控制图片的大小
![4](https://cloud.githubusercontent.com/assets/13177391/14057565/c00b7cee-f33e-11e5-95e2-ff1a9180aed6.jpg)
插入一个长图片的话，右下角的可拖拽圆点没有,而且红色框内的编辑器随着图片向上拖的话会向上移动，图片很长的话就看不到了
![5](https://cloud.githubusercontent.com/assets/13177391/14057566/c017a96a-f33e-11e5-9884-09d6e523b9e0.jpg)

**Comment by wangfupeng1988** [comment]
OK 我复现了。先记录下，这两天看看这个问题

**Comment by wangfupeng1988** [comment]
已经解决了，可去官网demo验证一下。有问题再继续反馈。
