### ISSUE TITLE
百度地图有个问题，可以选中多个地点，是故意这样设置的吗？是的话就关掉吧

### ISSUE THREAD

**Issue by lgd5555** [wangfupeng1988/wangEditor#192]
![staticimage](https://cloud.githubusercontent.com/assets/13177391/14069972/3f4a4446-f4d3-11e5-8a6b-690fe865d23d.png)

**Comment by wangfupeng1988** [comment]
插入图片地图，可以设置多个位置。插入动态地图，只能设置一个位置。

为何要关掉？你能保证所有的用户，都只需要一个地点、不需要多个地点？

**Comment by lgd5555** [comment]
好的，没毛病！
