### ISSUE TITLE
复制粘贴问题

### ISSUE THREAD

**Issue by Ttou** [wangfupeng1988/wangEditor#193]
如果在火狐下复制带&lt;br&gt;&lt;/br&gt;标签的文字，不能粘贴到chrome的富文本框里
chrome下复制粘贴无此问题
文字内容如下：
![qq 20160328120729](https://cloud.githubusercontent.com/assets/4298437/14070797/9c05b2c4-f4dd-11e5-96e1-28958164b118.png)

**Comment by wangfupeng1988** [comment]
把需要复制的内容以文字的形式粘贴出来呗，我试试。上面只是图片。

**Comment by Ttou** [comment]
可以复制这个网址里的正文，最好是相连的俩个段落
http://xueqiu.com/1876614331/66595172

**Comment by wangfupeng1988** [comment]
问题已经修复了，可去官网demo验证一下
需下载最新版本更新js文件 https://github.com/wangfupeng1988/wangEditor/releases
