### ISSUE TITLE
IE9就上传图片还是不弹窗

### ISSUE THREAD

**Issue by panchuang** [wangfupeng1988/wangEditor#194]
IE9就上传图片还是不弹窗,我配合了BootStrap的模态框插件 地址http://v3.bootcss.com/javascript/#modals
这个模态框插件的z-index高于文件选择框的z-index?

**Comment by panchuang** [comment]
刚刚又测试了下 把BootStrap的模态框取消还是没弹

**Comment by wangfupeng1988** [comment]
去官网demo试试，看弹不弹

**Comment by wangfupeng1988** [comment]
提问者长时间不回复问题。

我用IE8、9都试过官网demo，弹出选择图片层是没有问题的。题目中提到的`z-index`是可以通过配置来自动设置的。
