### ISSUE TITLE
与angularjs混合使用

### ISSUE THREAD

**Issue by gitLuozixiao** [wangfupeng1988/wangEditor#195]
mobile在与angular Controller中初始化编辑器时报错
ionic.bundle.js:25642 TypeError: Cannot read property 'trim' of undefined

**Comment by wangfupeng1988** [comment]
mobile版的现在先不要用了，好久没维护了，而且目前的设计不是很科学，而且至今位置我也没找到很科学的设计方法。业界目前除了几款app之外，也没有可供参考的纯js写的mobile端的编辑器。

这几天我会写一个pc端2.0版本的用于ng和vue的demo，到时候会放在文档里，写完了在此回复你。

**Comment by wangfupeng1988** [comment]
pc端2.0集成到`angular`可参见：http://www.kancloud.cn/wangfupeng/wangeditor2/132884

有问题可继续反馈

**Comment by gitLuozixiao** [comment]
好的哟，谢谢老板
