### ISSUE TITLE
上传图片后,不能填alt文本

### ISSUE THREAD

**Issue by winq2008** [wangfupeng1988/wangEditor#196]
现在的编辑器上传图片后,不能填写alt文本
建议能不能在图片底下的一排按钮上添加一个填写alt文本的地方.

**Comment by wangfupeng1988** [comment]
目前你是第一个提出这个需求的人，之前的用户都没有提出过，因此小众的需求，我只能把优先级先放低了。先解决目前比较棘手的几个bug和问题，然后再解决这个问题。精力有限，只能这样，请谅解。
