### ISSUE TITLE
在 ie 浏览器中 复制粘贴文本，会自动换行

### ISSUE THREAD

**Issue by lsl233** [wangfupeng1988/wangEditor#197]

**Comment by wangfupeng1988** [comment]
拒绝`一句话问题`，请详细描述问题的复现场景。

**Comment by lsl233** [comment]
不好意思!

在 ie10、9、8浏览器中复制任意一段文字，粘贴进富文本编辑器中，会自动换行
![222](https://cloud.githubusercontent.com/assets/12219498/14136528/d48ee3a4-f695-11e5-8b3d-05d176707651.png)



在chrome，浏览器中不会出现这种情况
![11](https://cloud.githubusercontent.com/assets/12219498/14136549/e881ae14-f695-11e5-8bcf-6b03091fa4fd.png)

**Comment by wangfupeng1988** [comment]
哦，这个问题是因为`IE`8、9、10的`document.execCommand`不支持`insertHtml`命令，因此只能用手动插入`html`元素的方式来弥补，要实现粘贴过滤只能处理。

如果不管它，使用IE默认的粘贴功能，就可能把带有复杂样式的内容粘贴到编辑器中，更不合算。

其实不光是粘贴会这样，IE8、9、10中好多操作都会这样，涉及到插入内容的，都可能出现这个情况。

**Comment by lsl233** [comment]
原来是这样，
感谢你提供的插件，文档很详细，在项目中使用非常方便，
万分感谢！！

**Comment by wangfupeng1988** [comment]
欢迎向身边的人推广一下！
