### ISSUE TITLE
在编辑器里复制粘贴有问题

### ISSUE THREAD

**Issue by Ttou** [wangfupeng1988/wangEditor#199]
如果在编辑器里输入aaaaaa，然后对其进行复制粘贴，内容的后面会加上`<p> </p>""<p> </p>`
![qq 20160331095939](https://cloud.githubusercontent.com/assets/4298437/14163373/4f73c0e4-f727-11e5-8722-c7a9f8743094.png)

**Comment by wangfupeng1988** [comment]
请说明浏览器，并详细描述复现步骤，另外是不是在官网demo能复现？

我在官网demo简单复制粘贴，复现不了你说的情况。

**Comment by Ttou** [comment]
chrome 49，官网demo也存在同样问题
![qq 20160331155117](https://cloud.githubusercontent.com/assets/4298437/14169080/62672110-f758-11e5-8764-c193cbf24809.png)

**Comment by wangfupeng1988** [comment]
> 请说明浏览器，**并详细描述复现步骤**，另外是不是在官网demo能复现？

你是怎么操作才出来的这个问题？我简单的复制粘贴没出来这个问题

**Comment by Ttou** [comment]
先输入几个a，再选中它们按ctrl-c，按多次ctrl-v，最后查看源码

**Comment by wangfupeng1988** [comment]
我用官网demo，chrome浏览器。

先输入几个a，查看源码是这样子 `<p>aaaaaa</p><p><br></p>`，然后在选中，按ctrl-c，再多次 ctrl-v ，最后查看源码 `<p>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br></p><p><br></p>`

没有发现你说的问题呀

**Comment by Ttou** [comment]
![gif](https://cloud.githubusercontent.com/assets/4298437/14170493/ac7e1990-f760-11e5-96d7-cc5f996f664b.gif)

**Comment by wangfupeng1988** [comment]
我用mac的chrome没确实没发现这个问题，我回家用windows的chrome试试吧。有回复在这里交流

**Comment by Ttou** [comment]
粘贴过滤样式能不能保留<br>标签，因为复制有些带图片的文章时，它如果不是靠<p>分段，而是靠<br>来换行，这样就会导致图片和文字挤在一起

**Comment by wangfupeng1988** [comment]
我看了，windows7下的chrome确实有你说的这个问题，我尽快看看并解决这个问题

----

另外，粘贴过滤样式那个是否保留`<br>`也比较简单，你搜索以下代码，把其中的`br`删除即可。你删除之后试试，帮我简单测试一下，看看有没有什么其他的问题？没问题的话，我再验证一下，就去掉。

```
            } else {
                // 忽略的标签
                if (['meta', 'style', 'script', 'object', 'form', 'iframe', 'br', 'hr'].indexOf(nodeName) >= 0) {
                    return;
                }
                // 其他标签，移除属性，插入 p 标签
                $elem = $(removeAttrs(elem));
                resultHtml += $('<div>').append($elem).html();
            }
```

**Comment by Ttou** [comment]
好的，我试试，有问题再回复

**Comment by Ttou** [comment]
去掉`<br>`的话，在chrome里复制中间夹杂`<br>`的两个段落，后一个段落复制不过来，但是firefox里就没问题

**Comment by wangfupeng1988** [comment]
你说的第一个问题——复制粘贴出现空行的问题——已经解决了，去下载最新版本即可。

保留`<br>`这个，我已经记下了，再花点时间验证验证，fixed之后在此给你回复。

**Comment by wangfupeng1988** [comment]
我把`<br>`粘贴保留的功能加上了，你去官网demo看看还有没有你之前遇到的问题。有的话，再反馈

**Comment by Ttou** [comment]
复制粘贴的问题解决了，`<br>`的话会在粘贴时被删除一个，两个变一个，一个就没有。
**原段落：**
![qq 20160404143429](https://cloud.githubusercontent.com/assets/4298437/14239852/7e743d76-fa72-11e5-81ef-9c01fed072d7.png)
**粘贴后：**
![qq 20160404143517](https://cloud.githubusercontent.com/assets/4298437/14239855/85cdf01c-fa72-11e5-9184-ced3f50bd9bd.png)

**Comment by wangfupeng1988** [comment]
你把截图段落的网页地址发给我，然后在哪个浏览器复制、哪个浏览器粘贴会出现这个问题，也描述一下。我来验证修改

**Comment by Ttou** [comment]
原文：http://xueqiu.com/9193217464/66930181
![001-fs8](https://cloud.githubusercontent.com/assets/4298437/14268738/fd5f3854-fb10-11e5-96e0-76ee6658fa32.png)

**Comment by wangfupeng1988** [comment]
> 然后在哪个浏览器复制、哪个浏览器粘贴会出现这个问题，也描述一下。

都是哪个浏览器？

**Comment by Ttou** [comment]
win7下：firefox 45.0.1 没有问题；chrome 49.0.2623.110 出现问题

**Comment by wangfupeng1988** [comment]
好的，我晚上看看

**Comment by wangfupeng1988** [comment]
问题已经解决了，可去官网demo验证 http://wangeditor.github.io/ 
下载最新版本修复即可 https://github.com/wangfupeng1988/wangEditor/releases

**Comment by Ttou** [comment]
问题已修复
