### ISSUE TITLE
 希望将插件内对其他插件的CDN引用改为HTTPS方式

### ISSUE THREAD

**Issue by fts11259375** [wangfupeng1988/wangEditor#200]
在HTTPS网站上使用插件，会导致插件内部通过HTTP的CDN方式引用的highlight.js等插件加载不进来，希望将插件内对其他插件的CDN引用改为HTTPS方式

**Comment by wangfupeng1988** [comment]
有没有比较靠谱的https的cdn？

**Comment by fts11259375** [comment]
highlight.js我改成bootcss的了，不过貌似他们没有百度地图的

**Comment by wangfupeng1988** [comment]
我回头先把`highlight.js`换成bootcdn的源，他们支持协议的自适应。百度地图的，我看他们官网描述的，2.0版本支持`https`了，但是需要升级2.0然后还需要什么企业认证，我抽空看看吧，不行就把编辑器的地图代码升级了。

http://lbsyun.baidu.com/index.php?title=jspopular

>JavaScript API首家支持Https，如需要申请Https服务，请您认证企业信息，成为企业认证用户后，https将自动开通，同时获得更高的服务配额。
注意：仅JavaScript API V2.0 版本支持https，其他JavaScript API版本均不支持。使用https服务，请先检查您的版本以及配置注意事项。

**Comment by wangfupeng1988** [comment]
我将`highlight.js`改成`http`或者`https`自适应的方式了，使用的是`bootcdn`。
百度地图的，容我再看看他们那个`v2.0`的文档，做几次实验试试吧。

fixed之后在此通知你。

**Comment by fts11259375** [comment]
嗯嗯，还可以把这些插件的引用路径也放到config里让开发者可以自己配置，这样比较灵活，只要规定好兼容的插件版本就行了，其实七牛也可以提供https的cdn，只不过有流量限制，但是个人用足够了

**Comment by wangfupeng1988** [comment]
百度地图使用https，可下载今晚发布的`v2.1.16`版本，参考 https://github.com/wangfupeng1988/wangEditor/issues/346

**Comment by wangfupeng1988** [comment]
百度地图使用https，可下载今晚发布的`v2.1.16`版本，参考 https://github.com/wangfupeng1988/wangEditor/issues/346
