### ISSUE TITLE
可以添加优酷视频连接支持吗

### ISSUE THREAD

**Issue by wangzhipeng404** [wangfupeng1988/wangEditor#201]
您好，我需要在文本中插入优酷的视频，但是修改url正则匹配之后，来了插入但是视频不能播放，可以添加一下对优酷视频的支持吗

**Comment by wangfupeng1988** [comment]
优酷视频支持啊，复制优酷.swf格式的视频链接，插入视频到编辑器，就可以了，官网demo就可以。

不过我近期要改一下，那样就能自动支持移动端了

**Comment by wangfupeng1988** [comment]
视频这块已经改好了，你可以去官网demo中试试。

**Comment by wangzhipeng404** [comment]
放假了还这么努力，谢谢～～
