### ISSUE TITLE
wangEditor.js与Vue.js冲突

### ISSUE THREAD

**Issue by qingzi-king** [wangfupeng1988/wangEditor#202]
如题，当同时使用这两个的时候，页面触底时会出现页面跳动，无法将页面滚到最后。

**Comment by wangfupeng1988** [comment]
> 页面触底时会出现页面跳动，无法将页面滚到最后。

不是太明白你说的错误是什么，最好截图来详细描述一下，另外把你的关键代码也粘贴一下。

文档中给出了一个集成`vue.js`的示例 http://www.kancloud.cn/wangfupeng/wangeditor2/133135 ，你试试用这个示例会否有你所说的问题？

**Comment by wangfupeng1988** [comment]
提问者长时间没有回复，先关闭问题。有疑问继续在此交流

**Comment by hansnow** [comment]
试试 `editor.config.menuFixed = false`
`menuFixed === true` 会导致body的css属性在滑动过程中变化
