### ISSUE TITLE
想问一下有支持音频的计划吗，mp3格式就可以

### ISSUE THREAD

**Issue by tian4010292** [wangfupeng1988/wangEditor#203]

**Comment by wangfupeng1988** [comment]
这个比较积累吧，我几遍是支持了`mp3`音频的功能，那能直接像视频一样，插入一个链接吗？现在主流视频网站，都有视频向第三方网站分享链接的功能，而语音没有吧。

如果是做成上传语音，那不就是和上传附件差不多了吗。文档中有关于上传附件功能的建议。

再者，现在互联网的语音输入，都是像微信那种直接录音的，而编辑器做不了这一步。

因此总体感觉这个功能做了，也做不好。而且你是第一个提出来的这个需求的人。

---

另外，如果你有好的建议，我没想到的地方，也可以多多交流。

**Comment by wangfupeng1988** [comment]
这个比较积累吧，我几遍是支持了`mp3`音频的功能，那能直接像视频一样，插入一个链接吗？现在主流视频网站，都有视频向第三方网站分享链接的功能，而语音没有吧。

如果是做成上传语音，那不就是和上传附件差不多了吗。文档中有关于上传附件功能的建议。

再者，现在互联网的语音输入，都是像微信那种直接录音的，而编辑器做不了这一步。

因此总体感觉这个功能做了，也做不好。而且你是第一个提出来的这个需求的人。

---

另外，如果你有好的建议，我没想到的地方，也可以多多交流。

**Comment by tian4010292** [comment]
我有一些mp3的音频在七牛云上，其实只要有个播放器就好了，我现在是通过源码自己添加的，不知道你用过微信上那种语音吗，就是能发一段话那种，一般富文本都是支持语音和视频的，不知道是不是只有我有这个需求

**Comment by wangfupeng1988** [comment]
> 一般富文本都是支持语音和视频的

富文本支持视频我知道，支持语音的我还没见过。你可以拿出一个来参考一下。

另外，微信、QQ等发送消息的地方，那不是富文本，那是个定制的输入框。不要拿这个来和富文本相比

**Comment by tian4010292** [comment]
不好意思，可能我表述有问题，不是按着发的那种语音，就是如果能想视频一样，输入.mp3后缀的url，生成一个播放器就好了，如果需求很少的话我自己写一写试试吧，感谢你的帮助

**Comment by wangfupeng1988** [comment]
http://www.kancloud.cn/wangfupeng/wangeditor2/115836  参看这个文档写一个自定义菜单吧，写完可以分享出来，
