### ISSUE TITLE
上传图片绑定链接，我的实现方式（亲测，有效）

### ISSUE THREAD

**Issue by momokanni** [wangfupeng1988/wangEditor#2031]
[先看实现效果](https://github.com/momokanni/doc/blob/master/wangEditor/wangEditor-imgBindUrl.png)   
1.  _createInsertPanel() 新增 var inputLinkId = getRandom('up-link'); 链接输入框ID  
2.  修改var tabsConfig的tpl属性，添加`<input id="'+ inputLinkId +'" type="text" class="block" value="" placeholder="http://..." />\n`  【链接输入框】    
3.  修改_createInsertPanel() 里的 返回数据xhr.onreadystatechange()函数中的insertLinkImg(link)的调用 -- > insertLinkImg(link,target)    
4.  最后修改insertLinkImg(..)的editor.cmd.do  
`editor.cmd.do('insertHTML', '<a href="'+ link +'"><img src="' + target + '" style="max-width:100%;"/></a>');`  添加a标签  
要先输入链接再上传图片，这是我的改法，比较着急，没法去重写customInsert

**Comment by momokanni** [comment]
我是后端不是前端，伪全栈

**Comment by 44886** [comment]
截图粘贴的图片不好弄

**Comment by momokanni** [comment]
> 截图粘贴的图片不好弄

粘贴那就不是一套逻辑了，你可以试着改下，成了分享，我也借用下
