### ISSUE TITLE
格式操作按钮设计的操作模式不符合使用习惯

### ISSUE THREAD

**Issue by Honghe** [wangfupeng1988/wangEditor#204]
环境：
- windows 10
- Chrome 49.0.2623.87 m

比如点击加粗，这时输入的文字应该是要加粗的，但实际上没有生效。
最新IE上没此问题。

**Comment by wangfupeng1988** [comment]
加粗的操作步骤是这样的：
第一，在编辑器中输入一段文字 `北京市海淀区`，此时看编辑器的源码是这样的 `<p>北京市海淀区</p>`
第二，选中几个字，例如选中`北京市`，点击『加粗』按钮，再查看源码，此时源码是这样的`<p><b>北京市</b>海淀区</p><p><br></p>`
其中的`<b>北京市</b>`就证明选中的文字已经加粗了。

你按照我说的步骤，将你那里的情况详细描述一遍吧。要不然你光说『没生效』我也不知道为何呀

**Comment by Honghe** [comment]
@wangfupeng1988 是的，其中一种情况就是按你这样操作，但仍没有加粗，源码也没变化。
另一种使用是，先点`加粗`，然后再输入文字，这时输入的文字应该是会加粗的，直至再点击`加粗`以取消加粗状态，这种使用方式也失效。

**Comment by Honghe** [comment]
@wangfupeng1988 不好意思，上个回复的第一种情况实际另有原因：是编辑器跟Chrome In-page HighLighter插件冲突，导致操作失效。

上面说的第二种情况：

> 另一种使用是，先点加粗，然后再输入文字，这时输入的文字应该是会加粗的，直至再点击加粗以取消加粗状态，这种使用方式也失效。

这个应该是WangEditor设计上的问题，跟百度的UMeditor等通用习惯不一致，通用的习惯是这样的：当光标停留在加粗的一些文字末尾，这时点击`加粗`按钮应该是把加粗的状态取消。但WangEdior设计为将光标前连续的加粗文字的加粗效果取消，有点突兀。不知作者为何这样设计，至少我是不习惯？

**Comment by wangfupeng1988** [comment]
> 另一种使用是，先点加粗，然后再输入文字，这时输入的文字应该是会加粗的，直至再点击加粗以取消加粗状态，这种使用方式也失效。

这种情况，目前不支持，并且`v2.x`的版本也不打算支持。因为`v2.x`是要支持IE8浏览器的，在IE8浏览器上这样操作，不大方便。

**Comment by Honghe** [comment]
@wangfupeng1988 请问，百度的`UMeditor`是如何在兼容IE8的同时支持这种`加粗`有状态的使用方式，你说的`在IE8浏览器上这样操作，不大方便`具体是什么能否科普下 :)

**Comment by wangfupeng1988** [comment]
IE8中没有遵循W3C标准的`selection`和`range`的API，而是用的微软自己的API标准，在使用上比较费劲，做出你说的这种效果就更加费劲了。

而且，你提出的这个需求，虽然在你个人感觉不是很习惯，并且我也知道这样操作更加好一些。但是整个QQ群几百个人，也就不到5个人提出过这个问题，其他人都没说使用不方便。

因此，大众需求不是很着急，我也就没有把优先级提高。

我不知道你是否对编辑器的使用和关注上多一些，你可以想想，对于大众用户来说，你说的这个需求，是否真的就是体验性非常糟糕、没有就不能用的级别？我觉得绝大部分人可能只知道选中加粗，根本就不知道你说的这个操作。

**Comment by wangfupeng1988** [comment]
你说的这种易用性改进，我会在下个大版本中加入。不过大版本`3.X`估计得等半年之后甚至明年（计划是这个时间点）
