### ISSUE TITLE
表格功能的建议

### ISSUE THREAD

**Issue by huangnie** [wangfupeng1988/wangEditor#205]
这个表格很棒了, 但是没有 在已插入的表格, 继续增加行或列的 功能,  不能没有呀

**Comment by wangfupeng1988** [comment]
抱歉，你说的这个功能，到目前为止，我印象中提出来的不超过5个人。说明用户需求量还是比较小的。因此，**我不会因为少数用户提出，就花费很大精力去做这件事儿**——表格操作真的很麻烦，就像word里面的表格操作，你光学就得学半天，更别说开发出来了。

你可能会说，你不会要word那么复杂的操作表格的功能，只要插入行和插入列。但是我一旦满足了你的需求，做了插入行和插入列。赶明天又来一位说要做合并单元格，你说我到时候是做还是不做？我即便是费好大劲做了，也只是满足一小部分人的需求。违背了 `2/8` 原则。

以上是说的我个一个宗旨和目前的情况，希望你能谅解这件事儿。

----

我在QQ群也说过，操作表格的功能，可以自定义插件开发。目前编辑器中操作表格的『删除』『增大』『缩小』这几个功能，都是插件化开发的。
如果你想开发一个，遇到问题我一定帮助。

**Comment by IVANLEE99** [comment]
插件？如何开发编辑器插件？
