### ISSUE TITLE
本地和服务器的样式不同步问题

### ISSUE THREAD

**Issue by bing2313** [wangfupeng1988/wangEditor#2055]
![image](https://user-images.githubusercontent.com/45384074/64101605-cb40e500-cda0-11e9-859b-00f64d64fe26.png)
![image](https://user-images.githubusercontent.com/45384074/64101617-d267f300-cda0-11e9-877a-b3253861e7a3.png)
第一张的样式是本地的，第二张的是上传到服务器的，是用vue写的项目，这是怎么回事啊？我想用第一张图片的样式

**Comment by Hench10** [comment]
理论上来说，一样的代码，一样的浏览器，效果应该是一样的，建议检查发布后的代码是否在编译过程中被改动（如：多浏览器支持）。或者上线后部分文件请求失败。
