### ISSUE TITLE
如何限制wangEditor编辑器文本内容长度

### ISSUE THREAD

**Issue by zhang14725804** [wangfupeng1988/wangEditor#208]
类似于input标签可以通过设置maxlength来限制输入长度

**Comment by wangfupeng1988** [comment]
目前无法设置，编辑器是富文本，不是textarea那样的纯文本，因此无法确定文本的实际长度，做不到类似 textarea那种maxlength的功能。

不过可以根据实际情况做一个提示，例如在你的『保存』按钮中，检查`editor.$txt.text()`或者`editor.$txt.html()`然后判断长度，给出提示。
