### ISSUE TITLE
如何保存wangEditor样式

### ISSUE THREAD

**Issue by zhang14725804** [wangfupeng1988/wangEditor#209]
用wangEditor编辑字体样式后，不能保存显示样式，莫名其妙的多出来<p><br></p>

**Comment by wangfupeng1988** [comment]
编辑器只提供纯html文件，至于样式，你需要自己去写。其实需要写的也不多，参考：http://www.kancloud.cn/wangfupeng/wangeditor2/113988

**Comment by zhang14725804** [comment]
谢谢作者
