### ISSUE TITLE
编辑器按钮乱码

### ISSUE THREAD

**Issue by nobodyhi** [wangfupeng1988/wangEditor#21]
![image](https://cloud.githubusercontent.com/assets/3972411/8951958/425e8242-3605-11e5-9f5a-3b5892abf41f.png)
如上图：编辑器外部按钮全部乱码，字体不生效。
公司全部使用内部专网，不能连接公网，可否提供：{path:"http://www.wangeditor.com/expressions/"}路径下文件的下载。

**Comment by wangfupeng1988** [comment]
看样子是IE低版本浏览器。
1. 建议你可以选择其他浏览器试试，看看其他浏览器行不行；
2. 检查网页编码，看看是不是utf-8；
3. 实在不行，做一个静态的demo，qq群发给我。

（如果问题解决了，别忘了再这里分享一下解决方案）

你说的下载方式我接收，今晚就弄上。

**Comment by wangfupeng1988** [comment]
表情文件打包上传到了qq群空间中
