### ISSUE TITLE
IE8下点击下划线，内容会多出<p><br></p>

### ISSUE THREAD

**Issue by bjcangyue** [wangfupeng1988/wangEditor#210]
IE8下点击工具按钮，内容会多出`<p><br></p>`，重复点击就会重复出现。

**Comment by wangfupeng1988** [comment]
哦，多谢你的反馈，刚才我在IE8试了一下，确实是这样，不过原因我已经看出来了。

其他浏览器无论怎么点击，最后都只有一个`<p><br></p>`，这是正常的。IE8下，浏览器自动生成的是大写的`<P><BR></P>`，可能代码中没有做大写判断。

我已经记录下这个问题了，修改之后在此回复你。

**Comment by wangfupeng1988** [comment]
https://github.com/wangfupeng1988/wangEditor/releases/tag/v2.1.4 下载`v2.1.4`版本，已经修复了IE8的这个问题

**Comment by JunedanVan** [comment]
@bjcangyue 你好！可以解答一下IE8的问题吗？
