### ISSUE TITLE
上传图片格式

### ISSUE THREAD

**Issue by starlitlight** [wangfupeng1988/wangEditor#211]
我测试了一下，上传的原图片是jpg格式，上传后得到的图片是jpeg格式，最主要的是图片名字改了。请教如何让上传图片保持原来的图片名？

**Comment by wangfupeng1988** [comment]
可能是后台判断图片文件类型的时候输出了`img/jpeg`类型了，不过图片名字改了没关系呀，上传图片就是存储一个url，只要能通过url获取正确的图片不就行了吗？

可以把你因为图片名字修改了而导致的问题，详细描述一下

**Comment by starlitlight** [comment]
因为我用富文本框添加图片，保存图片路径在数据库，但是如果想要修改的话，就需要update图片路径，我一开始通过名字去匹配，发现名字变了。我现在的做法是如果要修改图片的话，通过对应的id找到相关图片路径，然后全部删掉，再添加新图片路径就解决了。

**Comment by wangfupeng1988** [comment]
恩，好。你先这么用，我记录下问题之后，再看看。最好还是保证名字一样的好，对吧

**Comment by starlitlight** [comment]
嗯，是的，非常感谢

**Comment by wangfupeng1988** [comment]
https://github.com/wangfupeng1988/wangEditor/releases/tag/v2.1.4 下载`v2.1.4`版本，已经修复了`.jpg`格式自动转成`.jpeg`格式的问题
