### ISSUE TITLE
每次编辑保存后，内容最前面都会多出1个空的p标签。

### ISSUE THREAD

**Issue by wuyinman** [wangfupeng1988/wangEditor#2127]
第一次创建文章，我的内容就写了个 1。但是通过 onchange 获取到的内容前面会多个空的 p 标签。
![image](https://user-images.githubusercontent.com/28140607/70846358-89d9ce80-1e93-11ea-808f-debe7ce6e672.png)

保存第一次创建内容后，我点击编辑按钮再次编辑时，我输入了回车然后写了个2。这时获取内容时，前面又多了个空的p标签。如此循环每次都会有多的空p标签出现。
![image](https://user-images.githubusercontent.com/28140607/70846398-d02f2d80-1e93-11ea-9ae9-d999f0ab0d14.png)

请问大家有没有遇到同样的问题，是怎么解决的呢？

**Comment by wuyinman** [comment]
错别字更改

**Comment by wuyinman** [comment]
我目前的解决方式：

`editor.customConfig.onchange = function (html) {
    const contentHtml = html.replace(/<p\><\/p>/g, '');
    $('input[name=\'$name\']').val(contentHtml);
}`

**Comment by yourkevin** [comment]
我项目也遇到这个问题，我在后端处理的时候，存数据库之前去掉的p标签

**Comment by mywzxc** [comment]
因为自带一对p
初始化新增时使用html('')
初始化赋值时也需要使用html(val)，不能用append(val)
