### ISSUE TITLE
上传图片

### ISSUE THREAD

**Issue by zhang14725804** [wangfupeng1988/wangEditor#213]
如果用自己写的ajax上传文件，发送请求之后会返回一个json，然后从json中获取相应的内容进行之后的操作，，，
editor.config.uploadImgUrl = '/upload';
请求发送成功后，怎么得到返回值呢

**Comment by zhang14725804** [comment]
这个问题我知道怎么办了，，尴尬

**Comment by wangfupeng1988** [comment]
提问者已经自己答复了 😄
