### ISSUE TITLE
上传图片大小限制这么修改？

### ISSUE THREAD

**Issue by CXLDILEI** [wangfupeng1988/wangEditor#2134]
现在不能上传超过5m的图片

**Comment by xiuqiang1995** [comment]
// 将图片大小限制为 3M
editor.customConfig.uploadImgMaxSize = 3 * 1024 * 1024
---
文档里有

**Comment by CXLDILEI** [comment]
已经看到了，谢谢回复



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xiuqiang1995"<notifications@github.com&gt;; 
发送时间: 2020年3月30日(星期一) 下午4:42
收件人: "wangfupeng1988/wangEditor"<wangEditor@noreply.github.com&gt;; 
抄送: "唐云飞"<451202165@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [wangfupeng1988/wangEditor] 上传图片大小限制这么修改？ (#2134)





 
// 将图片大小限制为 3M
 editor.customConfig.uploadImgMaxSize = 3 * 1024 * 1024
 
文档里有
