### ISSUE TITLE
chrome或者firefox复制问题

### ISSUE THREAD

**Issue by zhang14725804** [wangfupeng1988/wangEditor#215]
在chrome或者firefox复制中，随便敲一些字然后ctrl+A  Ctrl+C  ctrl+V，他就会自动换行，，有什么办法解决么

**Comment by wangfupeng1988** [comment]
因为`ctrl+a`会选中整行，一行下面再粘贴一行，当然会换行了。

例如，你输入了`abcd`，查看源代码应该是`<p>abcs</p>`，然后全选、复制、粘贴，出来的其实是`<p>abcs</p><p>abcs</p>`。

另外，富文本编辑器的操作API，虽然目前除去IE8以外，都已经使用了`W3C`的API名称，但是具体的操作结果，还都没有完全统一，特别是像你说的这种细节问题。

因此，出现这种问题也是没有办法的事儿，只能慢慢优化了。
