### ISSUE TITLE
右键实现剪切的时候  无法undo回去

### ISSUE THREAD

**Issue by ray-toby** [wangfupeng1988/wangEditor#2159]
![image](https://user-images.githubusercontent.com/19220426/75639075-fc27a700-5c69-11ea-91cb-2c61d46f7de7.png)   调用的range.extractContents()；  或range.deleteContents();删除后  无法撤销回去，请问有人实现过吗

**Comment by ray-toby** [comment]
最后调用了document.execCommand('cut')方法解决了

**Comment by huacha106** [comment]
请问右键调用粘贴事件是怎么实现的，，我直接调用document.execCommand('parse')没有反应，键盘事件ctrl+v是可以的
