### ISSUE TITLE
是否可以对编辑器中的图片做剪切操作?

### ISSUE THREAD

**Issue by niget** [wangfupeng1988/wangEditor#216]
当前,点击编辑器中的图片,可以ctrl+c,进行复制,然后ctrl+v做粘贴。
但是呢，不能使用ctrl+x做剪切操作，请问群主，是否可以开发这个功能呢？

**Comment by wangfupeng1988** [comment]
这个不好弄吧，`ctrl+x`剪切是要用javascript操作剪切板的，这块我没详细看过相关文档，不过感觉各个浏览器的兼容程度都不一样，而且IE低版本肯定不支持。所以，耗费的开发精力会比较多一些。

另外，这功能不算是一个明显提高易用性的功能，即有了更好、没有对大多数用户来说也没事儿。

因此，我目前的立场是——如果用户提出了一个需求，不是明显提高易用性的，而且花费成本会比较高的，我就先持观望态度，因为现在还需要花费精力去做一些优先级比这个要高的功能。

希望能理解

**Comment by niget** [comment]
恩，好的，明白了。是我考虑的不全面，把这个事情想的太简单了.
