### ISSUE TITLE
编辑器中 链接 能否修改为可以单击打开？

### ISSUE THREAD

**Issue by niget** [wangfupeng1988/wangEditor#217]
现在编辑器中，浏览器是不可以点开的，但是又可以右键-->在新标签页打开.

请问,是否可以做到直接单击打开,如果不可以,请问能否告知不能打开的原因?

**Comment by wangfupeng1988** [comment]
你说的是编辑器中的链接吧。。

如果对编辑器的链接功能，不做任何处理的话，就是目前官网demo的那种效果，即链接是不能通过点击鼠标来跳转的，因为这是个编辑器，点击鼠标要光标定位、编辑内容的，跳转了还怎么编辑了？

---

如果想实现你的需求，比较好用的方式也有，就像QQ邮箱中的编辑器，链接既可以点击跳转、又可以编辑，不过所有的这种处理方式，都得自己去额外写程序和界面来处理。

我先记录下这个问题吧，按照优先级，后面加上，不过这几天工作相当忙，晚上周末的都得加班，精力不太够，可能进度上不会很快。

你如果着急，可以参考编辑器的自定义插件文档 http://www.kancloud.cn/wangfupeng/wangeditor2/115837 试着自己来写一个

**Comment by niget** [comment]
好吧,了解了.我看了腾讯的,确实好像太繁琐。我并不是着急，只是觉得链接能直接点的话，用户体验更好一些。
恩，不知道群主你用过apple的icloud没，在里面的备忘录里面，链接的表现文字可以直接编辑，然后同时，链接也能直接点开，当然icloud的并不能编辑链接。
我尝试分析代码，可惜功底太差，没能耐。希望这个能给群主你以一点参考。

**Comment by wangfupeng1988** [comment]
> 我觉得编辑链接可以在toolbar里面，链接的作用更应该点开来的

你说的这个，和QQ邮箱那个一个逻辑，只是位置不一样而已，都需要额外增加一些自定义的功能。

**Comment by niget** [comment]
恩,我刚才细细想了想,是我把自己绕住了,没有考虑的太深。群主你觉得可以处理，是否合理？

单击事件编辑器占用了，那么双击事件呢？我自己绑定一个双击事件在<a>上，是否合理呢？

**Comment by wangfupeng1988** [comment]
双击也是不合理的，因为单击、双击、三击都会触发页面选择区域的变化，所以这三个都不能用。
这个问题我已经记录下了，有时间我就去加上这个预览链接的功能，但是近期（这个周末要发布的版本）没有精力加，你要着急就去自己做插件。

问题先open着，我加上之后，在此回复你。

**Comment by wangfupeng1988** [comment]
问题已经修复，查看链接的功能，已经加上了，可关注今晚的`v2.1.6`的更新

**Comment by niget** [comment]
好的,多谢群主
