### ISSUE TITLE
插入表格能否恢复成以前的手动输入宽高的设置？

### ISSUE THREAD

**Issue by fudiwei** [wangfupeng1988/wangEditor#218]
在 1.3  版本中插入表格是手动设置行、列数的，但在 2.0 以后的版本里变成了一个 10*10 的矩阵选择，这个矩阵选择更人性化也更友好。但数量上 10 列还好说，而 10 行往是远远不够的。

能否像插入图片分为“上传图片”、“网络图片”两个面板一样，把插入表格也分为“手动插入”、“快速插入”两个面板？

**Comment by wangfupeng1988** [comment]
现在的编辑器用到互联网产品中，使用10*10以上的表格已经不多了，因为10*10以上的表格，放在页面上的表现效果已经不好了、阅读体验很差，往往会用其他形式（例如拆分表格）来增加易读性。

不清楚你的产品中，会用到的最大的表格，是几行几列？这么多不会产生易用性问题吗

**Comment by fudiwei** [comment]
10 列以上的情况确实很少，尤其要面向多终端展示时，一般也就三五列，但 10 行基本是不够用的。

**Comment by fudiwei** [comment]
另外有没有考虑将构造函数扩展一下？因为现在MV*的框架已经很常见了，无论是React也好Angular也罢，都提出了组件复用的解决方案。以ng为例，虽然您提供了一个ng的例子，但在自定义指令里还以id选择器作为构造函数参数，这也就达不到复用的目的了。因为往往组件是ng-repeat或者使用模板渲染出来的，本身不具有id属性。

构造函数里的：
`var $elem = $('#' + elemId);`
个人感觉可以修改为：
`function isElement(node) {
    return !!(node &&
        (node.nodeName
        || (node.prop && node.attr && node.find)));
}
var $elem = isElement(elemId) ? $(elemId) : $('#' + elemId);`

这样就既可以传递一个id选择器，又可以传递一个HTMLElement对象进去了。对应到ng的directive里就是element[0]。

**Comment by wangfupeng1988** [comment]
> 这样就既可以传递一个id选择器，又可以传递一个HTMLElement对象进去了。

恩，这样应该是没问题的，我记录下来，然后改一下。fixed之后在此回复你

**Comment by wangfupeng1988** [comment]
https://github.com/wangfupeng1988/wangEditor/releases/tag/v2.1.4  下载2.1.4版本

可以使用`element`创建编辑器，也增加了创建table的数量（15*20）
