### ISSUE TITLE
IE10下字体、字号，前景色、背景色、表情按钮点下去弹出来一下就没了，再点击也是如此

### ISSUE THREAD

**Issue by misder** [wangfupeng1988/wangEditor#22]
IE10下字体、字号，前景色、背景色、表情按钮点下去弹出来一下就没了，再点击也是如此

**Comment by wangfupeng1988** [comment]
首先，我记得之前因为某个一错误发生过你说的这种严重的错误，但是接着就改过来了。不知道你遇到这个问题时，是不是还用的以前的版本，可以通过 http://www.wangeditor.com/wangEditor/demo/demo.html 这个链接来测试一下，看看是不是仍然有你说的问题。

另外，我用IETester对你描述的问题进行了测试，结果是正常的，用IE8、9都测试过，如下图：
![qq 1](https://cloud.githubusercontent.com/assets/9583120/9268772/d533314e-4294-11e5-8926-77461f2bdd53.png)
![qq](https://cloud.githubusercontent.com/assets/9583120/9268774/d696cc1c-4294-11e5-9a68-e3f7e16eb728.png)

**Comment by misder** [comment]
IE11也有这种问题

**Comment by misder** [comment]
谷歌没问题，那个demo也没问题，不知是何缘故

**Comment by wangfupeng1988** [comment]
如果你确定 http://www.wangeditor.com/wangEditor/demo/demo.html 这个demo没有问题，那你就重新下载js、css，覆盖你当前的文件，就可以了。

**Comment by wangfupeng1988** [comment]
最新版本的编辑器没有问题，关闭此问题。
