### ISSUE TITLE
上传图片问题

### ISSUE THREAD

**Issue by starlitlight** [wangfupeng1988/wangEditor#220]
我本地运行没问题，上传阿里服务器后，上传大图片会报错，但是小图片可以运行，请问该怎么解决

**Comment by wangfupeng1988** [comment]
这种特殊情况，还是建议用`plupload`重写一下上传功能http://www.kancloud.cn/wangfupeng/wangeditor2/123690 这样遇到什么问题，你可以去查找`plupload`的解决方案。毕竟`uppload`算是比较成熟的产品（七牛推荐用），绝大部分问题应该都会有相应的解决方案。

**Comment by starlitlight** [comment]
好的，谢谢
