### ISSUE TITLE
是否支持复杂的数学公式呢

### ISSUE THREAD

**Issue by ymma** [wangfupeng1988/wangEditor#221]

**Comment by wangfupeng1988** [comment]
暂时没有这个功能，因为用户需要这个需求的不是太多，就没有着急加上。你可以参考文档中自定义菜单，自定义开发这个功能。

**Comment by ymma** [comment]
好的，谢谢您

**Comment by wangfupeng1988** [comment]
v5 已经支持 公式 https://github.com/wangeditor-team/wangEditor-plugin-formula

v5 发布在即，v4 中不会再增加新功能了
