### ISSUE TITLE
编辑器默认高度被行内样式写死搞不懂这是什么骚操作

### ISSUE THREAD

**Issue by dcdlove** [wangfupeng1988/wangEditor#2224]
![image](https://user-images.githubusercontent.com/10043691/86504147-c517fc80-bde7-11ea-9a12-6c7f0ff49abd.png)

**Comment by htlshu** [comment]
怎样去配置富文本的高度呢？

**Comment by abduhelel** [comment]
可以自定义设置富文本编辑器的高宽的
| |
timehelel
|
|
timehelel@163.com
|
签名由网易邮箱大师定制


在2020年07月14日 17:54，沈先生<notifications@github.com> 写道：

怎样去配置富文本的高度呢？
