### ISSUE TITLE
设置字号后再设置标题

### ISSUE THREAD

**Issue by tian4010292** [wangfupeng1988/wangEditor#223]
设置字号后再设置标题，选区字体大小久不会改变了，这算一个bug吗

**Comment by wangfupeng1988** [comment]
去了解一下css层叠样式就知道了，这不是一个bug。

标题例如`<h1>`之所以会加粗加大，是浏览器内置了一个默认样式（跟你自己写的样式一样，只不过是内置的）而导致的结果。这个这个内置样式的优先级是最低的，只要有其他样式，就会覆盖掉这个内置样式。

因此，你都设置了字号了，当然内置样式就失效了
