### ISSUE TITLE
上传图片在IE8,9,10，11下不兼容的问题

### ISSUE THREAD

**Issue by 18189529845** [wangfupeng1988/wangEditor#224]
在IE10,11上运行正常。但是当用ie9的时候多了PRE标签。在 wangEditor.js文件的6401行跟6479行我用replace函数去掉<pre>后可以在IE9下正常上传显示，但是IE8还是有问题，修改代码如下：
 img.onerror = function () {
                    if (resultText.indexOf("<pre>") >= -1) {
                        resultText = resultText.replace("<pre>", "");
                        resultText = resultText.replace("</pre>", "");
                        var html = '<img src="' + resultText + '" style="max-width:100%;"/>';
                        editor.command(null, 'insertHtml', html);

                        E.log('已插入图片，地址 ' + resultText);
                        img = null;
                    } else {
                        E.error('使用返回的结果获取图片，发生错误。请确认以下结果是否正确：' + resultText);
                        img = null;
                    }
                    
                };

**Comment by wangfupeng1988** [comment]
你说的这段代码是`img.onerror`函数里面的，这个函数只当返回的数据不正确、加载不了图片时才会触发的，说明你返回的数据不正确。

你先不要管源码哪里不正确，你先看看在IE9时候，服务器端`response`的是什么？如果服务器端`response`的是一个正确的图片url，还显示不出图片来，那就是编辑器的问题了。如果你服务器端`response`出来的本身就不是一个正确的图片url，那就先处理这个问题。

你可能会问：IE10可以、IE9就不行了，证明服务器端没问题——我的回答：先不要管IE10和IE11，就看IE9时候，服务器端`reponse`了什么，这个是核心问题。

**Comment by 18189529845** [comment]
已找到原因。设置
context.Response.ContentType = "text/html";
            context.Response.Charset = "utf-8";
即可，之前为context.Response.ContentType = "text/plain";
