### ISSUE TITLE
增加上下标格式

### ISSUE THREAD

**Issue by iwege** [wangfupeng1988/wangEditor#226]
建议增加上下标格式，这个在command里面应该是有的，难度应该不大。

**Comment by wangfupeng1988** [comment]
> 上下标格式

啥意思？

**Comment by iwege** [comment]
`<sup>`,`<sub>`

**Comment by wangfupeng1988** [comment]
这个自己扩展一个菜单吧 http://www.kancloud.cn/wangfupeng/wangeditor2/115833 ，因为目前你是第一个提出这种需求的，需求量太少。如果`document.execCommand`支持的话，扩展一个菜单会很简单的。看看文档，然后还可以参考一下编辑器源码中`bold`菜单或其他菜单的配置源码：https://github.com/wangfupeng1988/wangEditor/blob/master/dist/js/wangEditor.js#L3505
