### ISSUE TITLE
内容为空时，再继续删除会出现跳动，问题依旧存在

### ISSUE THREAD

**Issue by thinktkj** [wangfupeng1988/wangEditor#227]
我看到源码中，您是通过在2207行加入如下代码：
`if (txtHtml === '<p><br></p>') {
       // 如果最后还剩余一个空行，就不再继续删除了
       return;
}
`
而我是通过在4205行左右加入如下代码：
`if($txt.html() === '<p><br></p>'){
        e.preventDefault();
        e.stopPropagation();
        return;
}`

此时可以解决“内容为空时，再继续删除会出现跳动”的问题，

`但是有一个更根本的问题是，编辑器初始化不一定是<p><br></p>开头，如拷贝粘贴等其他操作，都有不确定的因素，所以更根本的问题是如何解决初始化必须是<p><br></p>开头，编辑器内容为空的时候样式才正常的问题`

`是否可以考虑编辑器源码就算为空，而不是“<p><br></p>”的时候，样式跟"<p><br></p>"保持一样，让用户感觉不到明显的跳动。`

或者

`强制让编辑器以“<p><br></p>”开头，不论内容来源（如编辑拷贝粘贴等），然后删除的时候，直接控制最后不会删除“<p><br></p>”。`

感谢您的开源奉献。

**Comment by songxuangh** [comment]
是的，目前还存在，希望尽快修复，感谢作者！

**Comment by wangfupeng1988** [comment]
我看到了，我修改的地方是在 `$txt.on('keyup')`中，而你修改的是在`$txt.on('keydown')`里面，而我忽略了后者。我下次维护将加上，一定会搞定这个问题的。

----

另外，如果编辑器的内容看起来为空（用户看不到任何文字、图片等），那么编辑器的源码中必须还有一个`<p><br></p>`，否则就会有问题，这是肯定的。

**Comment by wangfupeng1988** [comment]
问题已经修复，关注`v2.1.6`版本更新即可。
