### ISSUE TITLE
图片插件在全屏时，无法使用

### ISSUE THREAD

**Issue by thinktkj** [wangfupeng1988/wangEditor#228]
图片插件在全屏时，无法使用

如果在未全屏时，先点出图片插件，然后全屏，图片插件的定位位置会出现异常。

**Comment by wangfupeng1988** [comment]
这个问题我这两天发现了，是设置了`max-height`导致的冲突，你先不要使用`max-height`。待我修复之后，在此回复你。

**Comment by thinktkj** [comment]
恩  刚才才发现

**Comment by wangfupeng1988** [comment]
这个问题我详细看了一下，发现此前设计`max-height`功能时候，没有详细考虑到『全屏』时候的各种场景，因此不是很好调整。为了不误导用户，我已经在文档中做了说明 http://www.kancloud.cn/wangfupeng/wangeditor2/113966 建议`max-height`和『全屏』不要同时使用。

我这次发布先更新一些比较好紧急的问题，这个问题，我再想想，说不定要把`max-height`这块再重新设计一下。

issue先保持open状态，啥是否修复了，在此回复。

**Comment by wangfupeng1988** [comment]
这个问题比较复杂，原因就是我在设计全屏功能的时候，没有对`max-height`的影响考虑那么周全。这一版本先不解决了，年底重构下一次大版本时候，这个问题一定解决。
