### ISSUE TITLE
firefox居中问题

### ISSUE THREAD

**Issue by zhang14725804** [wangfupeng1988/wangEditor#229]
用本编辑器编辑一段文字，设置居中，然后向后端发送请求
chrome：<p style="text-align: center; ">GGGGGGGGGGG</p><p><br></p>
firefox：	<p align="center">HHHHHHHHHHHH<br></p><p><br></p>

结果就是chrome正常显示，，firefox没有作用

**Comment by zhang14725804** [comment]
firefox：`<p align="center">HHHHHHHHHHHH<br></p><p><br></p>`
chrome：`<p style="text-align: center; ">GGGGGGGGGGG</p><p><br></p>`

**Comment by wangfupeng1988** [comment]
好的，知道了。感谢反馈，我修复完成之后，在此回复你。

**Comment by wangfupeng1988** [comment]
我今天详细看了这个问题，确实如你所说：

firefox：`<p align="center">HHHHHHHHHHHH<br></p><p><br></p>`
chrome：`<p style="text-align: center; ">GGGGGGGGGGG</p><p><br></p>`

但是这个问题，只在编辑器层面没有找到合适的解决方法。显然，chrome这种方式是正确的，firefox这样做确实不够标准。但是如果我在用设置之后强行在firefox中将`align="center"`修改为`style="text-align:center"`，然后在firefox中再设置『居左』或者『居右』就不起作用了。看来firefox在这部分是要将不标准走到底。

我建议你可以在保存数据之前，自己做一个判断，就是碰到`align="center"`的元素就修改为`style="text-align:center"`的。这样一步操作完了反而省事儿。这种简单的查询、替换函数也很简单。

**Comment by zhang14725804** [comment]
恩恩，我试试，谢谢啊
