### ISSUE TITLE
支持require.js动态引入吗，因为老报错“wangEditor is not a function”

### ISSUE THREAD

**Issue by pigerla** [wangfupeng1988/wangEditor#23]
我是requirejs引入wangEditor的，jq版本1.11.0，然后textarea那块dom也是动态生成的，在生成之后，我才做初始化，如：

     var editor = $smsTextArea.wangEditor();

然后老报错：

     $smsTextArea.wangEditor is not a function

请问如何解决？谢谢~

**Comment by wangfupeng1988** [comment]
这个问题你得具体分析，你把主要代码在这里粘贴一下。包括：页面代码、require主文件代码。
根据代码分析一下

**Comment by wangfupeng1988** [comment]
请继续提交描述或者代码，要不然没法帮你解决问题，时间久了我会关闭该问题。

**Comment by wangfupeng1988** [comment]
提问者长时间不回复，暂时关闭问题，有疑问在qq群 164999061 联系我。

将 wangEditor 用在 requirejs 环境下：http://www.wangeditor.com/wangEditor/docs/index.html#requirejs

**Comment by pigerla** [comment]
不好意思，回复晚了。
好的，有需要再QQ群联系你
