### ISSUE TITLE
编辑器能不能模块化

### ISSUE THREAD

**Issue by zhang14725804** [wangfupeng1988/wangEditor#230]
按需加载是不是更好一些

**Comment by wangfupeng1988** [comment]
群公共高明确写了不回复`一句话问题`，请详细描述一下，方便你我交流，也方便给其他用户分享。否则，我只能去猜你的意思了

**Comment by wangfupeng1988** [comment]
提问者长时间不回复，暂时关闭问题，有疑问可以再继续下面回复。
