### ISSUE TITLE
无法插入表格（IE+jquery1.9.1）

### ISSUE THREAD

**Issue by gotanksgn** [wangfupeng1988/wangEditor#232]
经排查，wangEditor2.1.5.js中4916行生成表格html时，如果以\n开头，则在554行转为jquery元素时报错，麻烦修改一下。
IE+jquery1.9.1 ，报错
IE+jquery1.10.2 ，正常
chrome+jquery1.9.1，不走commandHooks，所以也没问题

**Comment by wangfupeng1988** [comment]
demo中都是用的 jquery1.10  没注意1.9版本的错误，我记录下来，试一下。如果有问题，修复之后在此回复。

**Comment by wangfupeng1988** [comment]
已经修复，可关注`v2.1.6`版本的更新
