### ISSUE TITLE
config.printLog配置不生效

### ISSUE THREAD

**Issue by gotanksgn** [wangfupeng1988/wangEditor#233]
如题，配置后在源码中没有赋值。

**Comment by wangfupeng1988** [comment]
把你配置的代码贴出来，我给看看

**Comment by wangfupeng1988** [comment]
提问者长时间不回复，先关闭问题，有疑问可继续在下面留言

**Comment by fengbjhqs** [comment]
`$(document).ready(function() {
	wangEditor.config.printLog = false;
	var editor = new wangEditor('textarea1');
	
	editor.config.menus = [
		'source',
		'bold',
		'underline',
		'italic',
		'strikethrough',
		'eraser',
		'forecolor',
		'bgcolor',
		'quote',
		'fontfamily',
		'fontsize',
		'head',
		'unorderlist',
		'orderlist',
		'alignleft',
		'aligncenter',
		'alignright',
		'link',
		'unlink',
		'table',
		'img',
		'undo',
		'redo',
		'fullscreen'
	];
	editor.create();

});`

还是会提示 wangEditor提示: 本页面富文本编辑器由 wangEditor 提供 http://wangeditor.github.io/

**Comment by paranoidjk** [comment]
This PR fix this problem:  https://github.com/wangfupeng1988/wangEditor/pull/542
