### ISSUE TITLE
能否在视频那块增加上传本地视频呢？

### ISSUE THREAD

**Issue by 18189529845** [wangfupeng1988/wangEditor#234]
现在的这种是方便的不少，用户也容易操作，但是没有本地视频的上传的功能呢？

**Comment by wangfupeng1988** [comment]
上传本地视频之后是需要后台做解析的，不知道你有没有在优酷上传过视频，那是一个相当复杂的过程，比上传图片可麻烦多了。

现在上传图片这么点功能，我都写了很大篇幅的文档，就这样详细还这么多人看不懂。如果做上传视频，你让我怎么写文档？使用成本会非常高的。

**Comment by 18189529845** [comment]
之前使用ffmpeg 做过视频转换，但是如果没这个功能的话视频只能全是外链，无法真正满足客户需求的呀，

**Comment by wangfupeng1988** [comment]
你可以看看其他成熟互联网产品中的编辑器，有几个有上传视频功能的，可以列举出来。我至今反正没发现主流互联网产品中支持这个功能

**Comment by wangfupeng1988** [comment]
提问者长时间不回复，暂时关闭问题，有疑问可继续在下面留言

**Comment by lizy0329** [comment]
> 上传本地视频之后是需要后台做解析的，不知道你有没有在优酷上传过视频，那是一个相当复杂的过程，比上传图片可麻烦多了。
> 
> 现在上传图片这么点功能，我都写了很大篇幅的文档，就这样详细还这么多人看不懂。如果做上传视频，你让我怎么写文档？使用成本会非常高的。

其实用户说那么多，无非只是想要一个自定义按钮的功能。上传视频编辑器自己做？别傻了，外部需求千变万化，怎么能够满足。

**Comment by ackemaneva** [comment]
> > 上传本地视频之后是需要后台做解析的，不知道你有没有在优酷上传过视频，那是一个相当复杂的过程，比上传图片可麻烦多了。
> > 现在上传图片这么点功能，我都写了很大篇幅的文档，就这样详细还这么多人看不懂。如果做上传视频，你让我怎么写文档？使用成本会非常高的。
> 
> 其实用户说那么多，无非只是想要一个自定义按钮的功能。上传视频编辑器自己做？别傻了，外部需求千变万化，怎么能够满足。看问题抓不到要点是很致命的

可以，说的很到位，思路打开了，多谢
