### ISSUE TITLE
关于上传的问题

### ISSUE THREAD

**Issue by 349865361** [wangfupeng1988/wangEditor#235]
能否将图片上传的UploadFile方法单独剥离出来？因为如果自己做其他的上传组件调用UploadFile方法的话会触发uploadImgFns事件，因为不是图片就得重写一大堆，是否考虑过这种情况呢，把UploadFile事件做剥离，uploadImgFns参数改为自定义的，让其他插件可以调用UploadFile方法作为上传其他类型的工具

**Comment by wangfupeng1988** [comment]
其实我没有太明白你的意思，可以用一个示例更加清楚的描述一下。

但是有一点可以明确的，就是编辑器里面的上传服务仅仅是供编辑器用的，这个模块会随着编辑器的需求而变化，不会单独剥离出来给其他的地方做上传用。

如果你想让自己的系统中上传的组件更加统一，那么我建议你统一使用`plupload`，编辑器也使用（文档中说明），其他地方也使用。

如果你想着在其他地方上传了图片之后接着插入到编辑器当中，可以在上传的callback中使用`editor.command(event, 'insertImage', 'http://........jpg')`这种方式插入。

以上是我想到的场景，如果不是你想表达的，可以继续补充、继续讨论

**Comment by wangfupeng1988** [comment]
提问者长时间不回复，暂时关闭问题，有疑问可继续在下面留言
