### ISSUE TITLE
给文字加粗 下划线 添加链接 自动换行问题

### ISSUE THREAD

**Issue by langzu292** [wangfupeng1988/wangEditor#236]
编辑器文本内容在没有任何p标签包裹下，给这段文字加粗或者 添加下划线 添加链接等 会将选中的这段文本自动生成一个独立的行。这是个bug。
楼主这个编辑器空的时候需要p标签包裹，不过在实际使用中 给编辑器赋值的内容确实是纯文本 没有任何p包裹的，这种情况下设置加粗等就出现问题了。

**Comment by wangfupeng1988** [comment]
赋值要统一使用`<p>`包裹，否则出的问题就不仅仅是你说的这些了。
