### ISSUE TITLE
上传图片大小、位置可以调整吗？

### ISSUE THREAD

**Issue by zhxiaobin** [wangfupeng1988/wangEditor#238]
上传以后的图片，能否拖拽大小调整，或者进行位置调整呀

**Comment by wangfupeng1988** [comment]
可拖拽大小调整，但不能进行位置调整

**Comment by zhxiaobin** [comment]
上传的图片也不能悬浮在文字中间，我觉得这个在编辑排版的时候倒是一个挺重要的功能

**Comment by wangfupeng1988** [comment]
你说的是文字环绕图片这种效果吧，目前还不支持左右浮动。而且你可以看看现在互联网上面的文章，特特别是手机上看的，哪儿还有文字环绕图片的？

**Comment by wangfupeng1988** [comment]
提问者不及时回复，先关闭问题。有疑问继续在下面留言
