### ISSUE TITLE
上传图片验证问题？

### ISSUE THREAD

**Issue by celleychen** [wangfupeng1988/wangEditor#239]
您好，我想在上传图片到后端前做验证，验证图片文件大小或者图片长宽大小怎么做？onload好像是已经在后台处理完后的事件？有选择完文件触发上传前的事件吗？

**Comment by wangfupeng1988** [comment]
这种情况，你可以选择使用`plupload`插件来做 http://www.kancloud.cn/wangfupeng/wangeditor2/123690

**Comment by wangfupeng1988** [comment]
提问者没及时回复，先关闭问题。有疑问继续在下面留言
