### ISSUE TITLE
关于editor.$txt.html()赋值和onchange事件的冲突

### ISSUE THREAD

**Issue by niget** [wangfupeng1988/wangEditor#240]
通过使用 editor.$txt.html() 给编辑器赋值以后, 只是单击编辑器,就会触发onchange事件。

我跟了源代码，冲突是editor.$txt.html() 赋值以后，oldvalue 还是以前的值，大概是 editor.$txt.html()  赋值 并不触发那些事件（txtChangeEventNames里面的），进而给oldvalue更新内容 而造成的。

我想了下，没有好的思路。。。只能来找群主你了。。。

**Comment by niget** [comment]
恩,我刚刚才发现一个直接的方法...就是把click监听去掉,  因为我用的功能比较少,单击不会引发内容变化,所以就暂时去掉了.

当然,这个只是勉强的解决方法,看看群主你有什么好的方法了

**Comment by wangfupeng1988** [comment]
我今晚查查这个问题。

**Comment by wangfupeng1988** [comment]
发现了你说的问题。我现在的解决方法是——通过使用 `editor.$txt.html()` 给编辑器赋值，只要是新值和旧值不同，就立刻触发`onchange`事件。关注今晚的`v2.1.7`版本更新
