### ISSUE TITLE
求指教模拟上传。

### ISSUE THREAD

**Issue by smarttang** [wangfupeng1988/wangEditor#243]
FYI 群里说了，这个该如何实现。。。
障眼法。。求解释。。。

![image](https://cloud.githubusercontent.com/assets/4961402/15006275/9101c43a-1201-11e6-9aea-341230685d7a.png)

**Comment by wangfupeng1988** [comment]
我本地demo试了，demo中做如下配置：
```
        editor.config.uploadParams = {
            token1: 'abcde',
            token2: '12345'
        };
```
上传图片，抓包http看到：

```
------WebKitFormBoundaryrn5YtQdj4NxUDnd0
Content-Disposition: form-data; name="wangEditorH5File"; filename="17833422553248024.jpg"
Content-Type: image/jpeg


------WebKitFormBoundaryrn5YtQdj4NxUDnd0
Content-Disposition: form-data; name="token1"

abcde
------WebKitFormBoundaryrn5YtQdj4NxUDnd0
Content-Disposition: form-data; name="token2"

12345
------WebKitFormBoundaryrn5YtQdj4NxUDnd0--
```

后台nodejs接收到了结果：

```
{ token1: 'abcde', token2: '12345' }
```

-----

你可以去github下载并运行demo，参见 https://github.com/wangfupeng1988/wangEditor#4-本地运行demo

然后配置`editor.config.uploadParams`，上传图片之后看看控制台是否会有如下的提示：

```
显示上传时的参数 begin
{ token1: 'abcde', token2: '12345' }
显示上传时的参数 end
```

**Comment by smarttang** [comment]
good 这个好东西。。。
主要这个功能在于一些比较特殊的系统，例如说保密级别比较高的系统，
上传图片可能存在各种风险，毕竟用户可以操作输入的地方都是不可信任的。
但是如果变成base64就不一样了。。攻击者也搞不出啥来。。。
不管咋说，谢谢。。。

**Comment by wangfupeng1988** [comment]
不过当心你编辑内容时，上传了很多大图片，都以base64存储，将服务器撑爆了
