### ISSUE TITLE
360浏览器8.2 无法上传图片

### ISSUE THREAD

**Issue by z1003031335** [wangfupeng1988/wangEditor#245]
点击上传图片的时候，没有反应

**Comment by wangfupeng1988** [comment]
我尽早试试哈，是那个『360安全浏览器』？http://se.360.cn/ 这个网站的
另外，你操作系统是哪个？

**Comment by z1003031335** [comment]
@wangfupeng1988 是啊，我是win7

**Comment by wangfupeng1988** [comment]
我在虚拟机里面运行win7，安装了360安全浏览器（http://se.360.cn/），然后访问本地的demo，上传图片是没有问题的，不知道你的啥错误。

你能跟踪到服务器的代码吗？看看是不是服务器出什么异常了？

----

另外，我的win7中是默认的IE8浏览器，安装了360浏览器之后，我看它直接就用了IE8的内核。我不清楚你的电脑上360浏览器用的什么内核。

**Comment by z1003031335** [comment]
@wangfupeng1988 看来是我自已的问题，刚才重装浏览器好像就好了
