### ISSUE TITLE
点击图片后,出现图片工具bar,然后把图片删除,bar却还留在页面,需要再点击下其他地方才会去掉

### ISSUE THREAD

**Issue by niget** [wangfupeng1988/wangEditor#246]
这个问题,虽然不大,但是有那么一丢丢会影响到体验。群主如果有时间，就看看，如果没时间，或者觉得无关紧要，直接关了这个问题也行。

**Comment by wangfupeng1988** [comment]
OK 感谢反馈，我尽早修复这个问题。修复之后，在此回复你。

**Comment by wangfupeng1988** [comment]
> 然后把图片删除

你用的什么浏览器？何种场景把图片删除的？我在chrome上试了，删除图片时候，toolbar会跟着消失的，代码里面也是这么写的。不知道如何复现出来

**Comment by niget** [comment]
也是谷歌,恩,估计删除的方式不一样,我是直接 回退键 删除的,如果图片的删除,就没事

**Comment by wangfupeng1988** [comment]
这个问题我已经处理了，去下载`v2.1.8`版本 https://github.com/wangfupeng1988/wangEditor/releases 也可去官网demo上验证一下。
