### ISSUE TITLE
引用jq1.7.1在IE8/9下报[无法获取属性“commonAncestorContainer”的值]

### ISSUE THREAD

**Issue by blankoff** [wangfupeng1988/wangEditor#247]
页面引用jquery-1.10.2.min 正常不报错 289行range有值
页面引用jquery-1.7.1.min 289行range undefined 报错

**Comment by wangfupeng1988** [comment]
我回头看看吧，报`range undefined`应该不是jquery的问题，可能是jquery导致的其他问题。有结果了在此回复你。

**Comment by blankoff** [comment]
好的多谢，后来又在别人的机器上试了一下，别人的是好用的。也有可能是我系统的原因，因为IE用的是虚拟机里装的。
