### ISSUE TITLE
希望增加一个表格的单元格合并

### ISSUE THREAD

**Issue by yilinyouhun** [wangfupeng1988/wangEditor#248]
希望增加一个表格的单元格合并，类似于 tinymce 这个编辑器或者其他编辑器的单元格合并……

**Comment by wangfupeng1988** [comment]
对于表格操作的功能，已经有几个人跟我反馈了，目前我的意见还是不想在基本产品中加。原因很简单——第一，这个功能目前需求量不是很大；第二，我目前业余做，精力有限，做好表格操作是需要花费时间的。所以还请你理解。

如果有兴趣可参考一下自定义插件的文档 http://www.kancloud.cn/wangfupeng/wangeditor2/115837 ，自己做一个这样的功能。其实，现在编辑器中表格的toolbar就是机遇插件机制实现的，源码可参见：https://github.com/wangfupeng1988/wangEditor/blob/master/dist/js/wangEditor.js#L7246
