### ISSUE TITLE
“插入代码”功能的问题

### ISSUE THREAD

**Issue by dongfenglong** [wangfupeng1988/wangEditor#251]
在编辑器中插入代码后，代码块是有边框的。当然是因为编辑器中有该样式。但是将编辑器中的内容提交后，在显示页面中代码块就没有边框了。因为在显示页面中没有提供该样式。该样式是依赖于编辑器的：.wangEditor-container .wangEditor-txt pre{……}

编辑器页面图示：

![qq 20160511110447](https://cloud.githubusercontent.com/assets/6386364/15168913/6b064424-1768-11e6-8c46-d89a4e512a17.png)

=========================显示页面图示==================================
![2](https://cloud.githubusercontent.com/assets/6386364/15168922/7da4cd4e-1768-11e6-89ad-f06fdfa00690.png)

**Comment by wangfupeng1988** [comment]
是的，获取编辑器的内容时，编辑器尽量提供纯粹的html代码，尽量不加入css样式代码（除了像`max-width:100%`这种必须加的），显示页面中如何显示，需要自己来写css，可参见 http://www.kancloud.cn/wangfupeng/wangeditor2/113988

这样做有如下好处：

- 可减少服务器端数据存储的内容；
- 可方便自己定义不同的样式或者皮肤；

**Comment by dongfenglong** [comment]
原来如此，谢谢。
