### ISSUE TITLE
pc 版，不能连续每次上传相同的图片

### ISSUE THREAD

**Issue by arnotong** [wangfupeng1988/wangEditor#252]
点击图片上传一张图片，成功后再次选择同一张图片上传，无效。

**Comment by wangfupeng1988** [comment]
提交问题之前建议现阅读 http://www.kancloud.cn/wangfupeng/wangeditor2/137878 (即QQ群公告的内容)  会提高你提问的效率。

遇到这个问题你应该去下载github的源码，在本地运行demo测试一下。另外，提问之前要说明是哪个浏览器。

**Comment by wangfupeng1988** [comment]
提问题长时间不回复，先关闭问题。有疑问再继续在下面留言
