### ISSUE TITLE
添加代码块总是在代码块上方多出数量不等的空行

### ISSUE THREAD

**Issue by dongfenglong** [wangfupeng1988/wangEditor#253]
在空行上添加代码块，添加完成后会发现代码块前面多出了几条空行

![qq 20160512134916](https://cloud.githubusercontent.com/assets/6386364/15205304/9ccf8e44-1848-11e6-82f0-01579034f87b.png)

**Comment by wangfupeng1988** [comment]
如果你是IE浏览器，那么出现这个问题是正常的，因为IE的 `document.execCommand` 方法不支持 `insertHtml`，只能使用在<p>元素后面append代码块的方式解决，而且要保证插入代码块之后前面可以继续输入内容。

如果是其他浏览器，请说明版本，我来查证。

**Comment by dongfenglong** [comment]
我用的是Google Chrome，版本 51.0.2704.19 (64-bit)。

**Comment by wangfupeng1988** [comment]
我用 mac os 的 chrome测试，未复现你的问题，用windows7的chrome测试，也未复现你的问题。

你在你电脑上，直接访问官网demo，也有这个问题嘛？

**Comment by wangfupeng1988** [comment]
提问者长时间不回复，先关闭问题。有疑问可继续在下面留言
