### ISSUE TITLE
如何扩展视频上传菜单，并且传递不同的参数

### ISSUE THREAD

**Issue by langzu292** [wangfupeng1988/wangEditor#254]
请问下如何扩展视频上传菜单，并且传递一个与上传图片不同的参数
另外上传提交的文件类型不仅仅局限于base64，也有file形式的
那么我该如何在不改动源码基础上扩展一个独立上传视频的菜单呢？

**Comment by wangfupeng1988** [comment]
照着 http://www.kancloud.cn/wangfupeng/wangeditor2/115836 这个页面，扩展一个菜单，这个demo中扩展的菜单是插入特殊符号。而你需要做的是在菜单的dropPanel中写一个`<input file>`标签以选择视频文件。

可以选择视频文件了之后，如何上传视频你自己来写，和编辑器无关。在视频上传完成的callback函数中，你需要使用`editor.command(e, 'insertHtml', '<video src="xxxx.mp4" controls="controls"></video>');`来将视频的html代码插入到编辑区域。其中的`<video>`标签如何写，你自己定义即可。

过程大体就是上面的描述，无需修改编辑器代码。

----

另外，一般上传视频（如优酷）之后，系统后台都会有一个解码的过程，不知道你是否也有此过程，如果有，你就自己考虑一下该如何实现吧。

**Comment by wangfupeng1988** [comment]
提问题长时间不回复，先关闭问题。有疑问再继续在下面留言
