### ISSUE TITLE
上传图片时能否增加设置ALT属性功能？

### ISSUE THREAD

**Issue by jbksir** [wangfupeng1988/wangEditor#255]
上传图片时能否增加设置ALT属性功能？
图片的ALT属性对**# 优化**来说非常重要，希望作者能够增加此项功能。
最好是在选择图片之前设置ALT属性

**Comment by wangfupeng1988** [comment]
给图片加 `alt` 属性不是很难，只不过界面上不好设计。
目前上传图片panel中，就只有选择图片一个按钮，再加一个`input`输入框不好设计。

我先想想这个问题，你也帮忙想一下吧，如何好看的加上这个输入框。

**Comment by jbksir** [comment]
`// 上传图片事件
_e(function (E, $) {

    E.plugin(function () {
        var editor = this;
        var fns = editor.config.uploadImgFns; // editor.config.uploadImgFns = {} 在config文件中定义了
        
        // -------- 定义load函数 --------
        fns.onload || (fns.onload = function (resultText, xhr) {
            E.log('上传结束，返回结果为 ' + resultText);

            var editor = this;
            var img;
            if (resultText.indexOf('error|') === 0) {
                // 提示错误
                E.warn('上传失败：' + resultText.split('|')[1]);
                alert(resultText.split('|')[1]);
            } else {
                E.log('上传成功，即将插入编辑区域，结果为：' + resultText.split(',')[0]);

                // 将结果插入编辑器
                img = document.createElement('img');
                img.onload = function () {
                    var html = '<img src="' + resultText.split(',')[0] + '" alt="' + resultText.split(',')[1] + '" />';
                    editor.command(null, 'insertHtml', html);

                    E.log('已插入图片，地址 ' + resultText.split(',')[0]);
                    img = null;
                };
                img.onerror = function () {
                    E.error('使用返回的结果获取图片，发生错误。请确认以下结果是否正确：' + resultText.split(',')[0]);
                    img = null;
                };
                img.src = resultText.split(',')[0];
            }

        });

        // -------- 定义tiemout函数 --------
        fns.ontimeout || (fns.ontimeout = function (xhr) {
            E.error('上传上图片发生错误');
            alert('上传上图片发生错误');
        });

        // -------- 定义error函数 --------
        fns.onerror || (fns.onerror = function (xhr) {
            E.error('上传图片超时');
            alert('上传图片超时');
        });

    });
});`

我怎么在这里获取到图片的原始名字？
我现在改的这里获取的是图片经过 处理后的图片名字
我想在上传图片的时候直接将图片的原始名字作为图片的ALT属性

**Comment by wangfupeng1988** [comment]
不明白为何你们好多人一遇到问题就喜欢去直接改代码？那样效率真的高吗？

你从这里是获取不到名字的，因为这里是处理服务器返回之后的操作，没要求服务器返回名字，怎么能处理呀？

如果你想要以图片名字作为 `alt` ，我可以升级来加上这个功能。修改源码之后，以后还怎么升级了？

**Comment by wangfupeng1988** [comment]
你说的功能我已经加上了，默认情况下会把图片名字当做 alt 属性，下载 v2.1.11 版本更新 https://github.com/wangfupeng1988/wangEditor/releases/tag/v2.1.11

如果想自定义上传事件，可参考 http://www.kancloud.cn/wangfupeng/wangeditor2/123689
