### ISSUE TITLE
关于编辑器中tab键的使用问题

### ISSUE THREAD

**Issue by niget** [wangfupeng1988/wangEditor#256]
进入编辑器，点第一行，tab键可用。然后点击第二行，光标也移动到第二行，点按tab键，光标会自动返回第一行位置，并把第一行文字向后推几个空格位置。
  除非，在鼠标单击第二行后，输入一个空格，或其他内容，这样tab键才能正常。

**Comment by wangfupeng1988** [comment]
说明浏览器，我在mac os 的chrome和firefox上没发现你说的问题，在官网demo测试的

**Comment by niget** [comment]
更新最新版本后,没有问题了. 前面使用的是360急速浏览器

**Comment by wangfupeng1988** [comment]
最新版本也没有修改这个问题呀。你是哪个系统的360极速浏览器，我来验证一下

**Comment by niget** [comment]
最新版的，我中午刚刚更新，并测试了一下，问题还在。然后升级了最新的编辑器，没有问题了

**Comment by wangfupeng1988** [comment]
你是哪个系统的360极速浏览器

**Comment by niget** [comment]
我刚刚试了下。。。。多试几次后，又出现这个问题了，我用最新的360极速，最新的chrome，都是中午刚更新的。
是我的系统的问题，不是编辑器的事，很抱歉提bug之前没有在官网demo上测试。
我对编辑做了小小改动，是在编辑器生成后，对编辑器高度做的改动，因为我怎么设置，编辑器的高度都不能占满我的div，不知道是不是这个原因。
系统是windows 7 旗舰版

**Comment by wangfupeng1988** [comment]
> 因为我怎么设置，编辑器的高度都不能占满我的div，不知道是不是这个原因。

编辑器的高度如何设置，文档中是有规定的，不能随便用javascript修改DOM元素的高度。至于让编辑器在高度上填充满整个容器，目前还不支持这个功能。

**Comment by niget** [comment]
`  editor.create();
       	
        
        //对编辑器进行自定义
        $(".wangEditor-container").height("593px"); //设置编辑器高度-----------------------1080P-866px   1366-579
        $(".wangEditor-container").css("border-right-width","0px"); //边框
        $(".wangEditor-container").css("border-left-width","0px"); //边框
        $(".wangEditor-container").css("border-top-width","0px"); //边框
        $(".wangEditor-container").css("border-bottom-width","0px"); //边框
        $("#editor-trigger").parent().attr('id','edit_textarea');//给编辑器文本去增加id,方便修改滚动条样式
        $("#editor-trigger").css("min-height","540px");//修改编辑区域高度  --------------1080-805px 1366-530px`

修改代码，大概是这样。
