### ISSUE TITLE
给图片添加了一个跳转链接之后，左对齐/居中/右对齐就不能用了，点击没反应

### ISSUE THREAD

**Issue by JerryGao-RD** [wangfupeng1988/wangEditor#257]
我在使用中出现了这样的bug,

**Comment by wangfupeng1988** [comment]
好的，我看到这个问题了，感谢返回。

修复完之后，我会在这里回复你。

**Comment by JerryGao-RD** [comment]
我是这么改的，还请多多指教。
``$alignCenter.click(function (e) {
                commandFn = function () {
                    if (e.currentTarget.tagName === 'A') {
                        $currentImg.parent().parent().css({
                            'text-align': 'center'
                        }).attr('align', 'center');
                    } else {
                        $currentImg.parent().css({
                            'text-align': 'center'
                        }).attr('align', 'center');
                    }
                };
                customCommand(e, function () {
                    setTimeout(hide, 100);
                });
            });

**Comment by wangfupeng1988** [comment]
感谢反馈，感谢修改。因为要在本周末和其他问题一起修改，一起测试，我就现不合并你的PR了，我先自己修改了，然后一起测试一起提交、发布。

提交之后，我会在此回复你。

**Comment by wangfupeng1988** [comment]
而且，我感觉你这样简单粗暴的使用`$currentImg.parent().parent()`，强硬的获取第二级父节点，有些不妥，不利于后期扩展。我是这么做的

```
$alignRight.click(function (e) {
    commandFn = function () {
        // 如果 img 增加了链接，那么 img.parent() 就是 a 标签，设置 align 没用的，因此必须找到 P 父节点来设置 align
        $currentImg.parents('p').css({
            'text-align': 'right'
        }).attr('align', 'right');
    };
    customCommand(e, function () {
        setTimeout(hide, 100);
    });
});
```

使用 `$currentImg.parents('p')` 来获取 `p`上级节点，无论中间有几层，都不妨碍。因此这样修改更好一些，你说呢？

**Comment by JerryGao-RD** [comment]
是的，后来想用closest('p')，只是不知道以后会不会对<p>标签进行改变，所以就没提交，只是在自己用的标签里面改成了closest('p')

**Comment by wangfupeng1988** [comment]
已经修复了，下载 v2.1.11 版本 https://github.com/wangfupeng1988/wangEditor/releases/tag/v2.1.11 或者直接去官网demo验证

**Comment by JerryGao-RD** [comment]
好的
