### ISSUE TITLE
请添加一个过滤HTML代码的Filter

### ISSUE THREAD

**Issue by zhoubaicheng** [wangfupeng1988/wangEditor#258]
当直接在HTML页面上复制页面上的html的时候，粘贴进去wangEditor ，会呈现html代码，我希望只有文本。

谢谢！

**Comment by wangfupeng1988** [comment]
> 当直接在HTML页面上复制页面上的html的时候，粘贴进去wangEditor ，会呈现html代码

虽然我已经在聊天过程中明白了你的问题，但是我觉得你还是应该详细描述一下这个问题。我让你提交issue，不是给我看的，而是要给后来看的人分享问题的。如果你写的描述只有我能看懂，那么你提交这个issue就没有意义了。

我周末会加一个只粘贴文本的参数，但是你的问题内容也详细描述一下，让其他人也能轻易看懂。

**Comment by wangfupeng1988** [comment]
已经加上了，可去下载最新版 https://github.com/wangfupeng1988/wangEditor/releases/tag/v2.1.11
文档看这里 http://www.kancloud.cn/wangfupeng/wangeditor2/156691
