### ISSUE TITLE
光标自动换行问题

### ISSUE THREAD

**Issue by Frankseek** [wangfupeng1988/wangEditor#260]
我在项目中使用wangeditor添加表格调样式的时候，发现在每个在开头和结尾偶尔会多一个`<p></p>`标签，后来后台告诉我，编辑器在编辑完毕的时候，光标会自动换行，会自动多出一个`<p></p>`或者`</br>`标签。

**Comment by wangfupeng1988** [comment]
是的，执行完每一步操作，编辑器都必须保证结尾有一个`<p><br></p>`，否则会出其他问题。

关键是我没看到你的问题呀？末尾自动多一个`<p><br></p>`到底给你带来了什么问题，没看到

**Comment by Frankseek** [comment]
第一次打开时候生产的代码

<p>请输入问题...</p><p><br></p>

第二次打开修改第一次编辑的的代码

<p></p><p>请输入问题...</p><p><br></p><p></p><p><br></p>

每次都会生成 <p></p><p><br></p>
这是我回写的内容 <p>回写内容</p><p><br></p>

在 2016-05-19 09:44:41，"王福朋" <notifications@github.com> 写道：


是的，执行完每一步操作，编辑器都必须保证结尾有一个<p><br></p>，否则会出其他问题。

关键是我没看到你的问题呀？末尾自动多一个<p><br></p>到底给你带来了什么问题，没看到

**Comment by wangfupeng1988** [comment]
参考 https://github.com/wangfupeng1988/wangEditor/issues/274

**Comment by dizhenhao** [comment]
"造型时尚 设计新颖 方便携带 logo位置大‘"这是我文本框的内容，     
点击源码后会变成这个样子   “造型时尚 设计新颖 方便携带  logo位置大<p><br></p>” 明显的多了个<p><br></p>标签，添加下划线，加粗等都有这个问题，请问怎么去掉这个<p><br></p>标签

**Comment by dizhenhao** [comment]
"造型时尚 设计新颖 方便携带 logo位置大‘"这是我文本框的内容，
点击源码后会变成这个样子 “造型时尚 设计新颖 方便携带 logo位置
大<p><br></p>” 明显的多了个<p><br></p>标签，
添加下划线，加粗等都有这个问题，请问怎么去掉这个
标签

**Comment by dizhenhao** [comment]
"造型时尚 设计新颖 方便携带 logo位置大‘"这是我文本框的内容，
点击源码后会变成这个样子 “造型时尚 设计新颖 方便携带 logo位置
大” 明显的多了个p
标签，
添加下划线，加粗等都有这个问题，请问怎么去掉这个
标签

**Comment by pfei-yu** [comment]
2886行 修改成这个就行了
 if ($.trim($children.last().html()).toLowerCase() !== '<br/>'&&$.trim($children.last().html()).toLowerCase() !== '<br>') {
            $txt.append($('<p><br/></p>'));
        }
