### ISSUE TITLE
wangEditor-jquery.js ?

### ISSUE THREAD

**Issue by zanemarkson** [wangfupeng1988/wangEditor#261]
我正在尝试把这个editor用Github Electron搞成desktop application，然后在源码里见到了
> ```js
   else if (typeof module === "object" && typeof module.exports === "object") {
        // commonjs
        module.exports = factory(
            require('./wangEditor-jquery.js')
        );
 ```

可是貌似。。。找不到wangEditor-jquery.js呃。。。

**Comment by wangfupeng1988** [comment]
这是为了配合webpack使用的，看看这里 http://www.kancloud.cn/wangfupeng/wangeditor2/126637
