### ISSUE TITLE
上传图片成功返回图片路径后不能显示图片

### ISSUE THREAD

**Issue by mini-coder** [wangfupeng1988/wangEditor#262]
上传后的图片能正常访问，看上传结果--> ![2016-05-20_222041](https://cloud.githubusercontent.com/assets/12810809/15430722/22439d72-1ed9-11e6-97a8-36ff3dbc3307.png)--http://www.bearingstudy.com/upload/article/54dcbceb4cb24beca9439001f0d9cbb1.jpg

**Comment by wangfupeng1988** [comment]
除了前面添加的一个当前页路径前缀之外，你有没有看到其他异常？

你截图中，那个添加了前缀的url中有两个`%22`，有没有想过这是什么？

`%22`进行url解码是双引号`"`，也就是说，你返回的图片url两边都带了双引号，而你直接就把这个带双引号的字符串给当做url了，浏览器以为这不是一个url，因此就加了页面前缀了。问题就是这么个问题。

**Comment by mini-coder** [comment]
可以了，谢谢了，
.net平台只能通过这种方式输出
`HttpContext.Current.Response.Write(fileName);
 HttpContext.Current.Response.End();`
aps.net mvc 和 wei api 这些常用的输出方式就不行了,会输出带双引号的字符串
（吐槽一下，字符串不都是带双引号的吗,[哭笑不得]）

**Comment by wangfupeng1988** [comment]
> （吐槽一下，字符串不都是带双引号的吗,[哭笑不得]）

`var s = 'abc'` 和`var s = '"abc"'`能一样吗？
