### ISSUE TITLE
IE11下，文本框清空后复制黏贴第二次才会有效果

### ISSUE THREAD

**Issue by sql370** [wangfupeng1988/wangEditor#263]
@wangfupeng1988 
重现步骤：
1.点击源码按钮，出现html
2.将源码html清空
3.再次点击源码按钮回到富文本编辑器
4.将复制的文本ctrl+v黏贴
5.出现回车，但是并没有将文本复制上去
5.再按一次ctrl+v黏贴
6.文本黏贴成功
注意：清空文本框是在源码下清空的，不然的话源码是有`<p></p>`的，并能没有真正的清空。

**Comment by wangfupeng1988** [comment]
> 注意：清空文本框是在源码下清空的，不然的话源码是有<p></p>的，并能没有真正的清空。

你说的这个问题确实存在，我本次优化就把`清空文本框是在源码下清空`之后立即加上`<p></p>`。其实这是一个疏漏，应该在任何清空的情况下都保留`<p></p>`，否则就会出现各种问题。

问题修复之后，我在此回复你。

**Comment by wangfupeng1988** [comment]
已经修复，可去下载最新版 https://github.com/wangfupeng1988/wangEditor/releases/tag/v2.1.11 或者去官网demo上验证

**Comment by sql370** [comment]
ok，已验证
