### ISSUE TITLE
建议在npm包的package.json加main字段索引

### ISSUE THREAD

**Issue by alankell** [wangfupeng1988/wangEditor#265]
建议在npm包的package.json加main字段索引资源,并加入jquery的依赖(webpack中用要自己在npm包里新建个jquery的js是不是有点...),这样方便import,也方便日后在项目中更新版本了

**Comment by wangfupeng1988** [comment]
恩，我也很早意识到这个问题了，是挺费劲。之前没人提出来，我就一直懒懒的拖着没改。既然你提出来了，我周末就搞定这个问题。

fixed之后在此回复你

**Comment by wangfupeng1988** [comment]
该功能已经增加，下载最新版 https://github.com/wangfupeng1988/wangEditor/releases ，文档在此 http://www.kancloud.cn/wangfupeng/wangeditor2/126637

**Comment by alankell** [comment]
可行

**Comment by alankell** [comment]
dev的时候代码可跑起来,但是wepack build的时候突然报警告:
```
WARNING in ./~/wangeditor/dist/js/wangEditor.js
    Critical dependencies:
    19:35-68 the request of a dependency is an expression
    22:42-78 the request of a dependency is an expression
     @ ./~/wangeditor/dist/js/wangEditor.js 19:35-68 22:42-78
```
赶紧去翻源码,...吓坏宝宝了,为什么写个表达式去动态引入...ES2015是不支持动态引入的,虽然一些工具支持但是不符合规范的话很容易出问题的,建议直接引wangEditor-min.js吧,也不要放出什么选项让用户配了,js包用户既然已经用npm安装了,也不会再改成其他路径了,css其实没必要引的,因为大部分用户多多少少会改些样式,就让他们自己引就好了,that's all depend on you! 麻烦来个hotfix吧 @wangfupeng1988

**Comment by wangfupeng1988** [comment]
直接引用`min.js`不大好，你的工具自己有压缩功能，而且出错的时候，也至少知道哪一行出错，好反馈。

至于动态引入，你可以先去修改一下源码
```
    } else if (typeof module === "object" && typeof module.exports === "object") {
        // commonjs

        // 引用 css —— webapck
        window.wangEditorCssPath ? require(window.wangEditorCssPath) : require('../css/wangEditor.css');
        module.exports = factory(
            // 传入 jquery ，支持使用 npm 方式或者自己定义jquery的路径
            window.wangEditorJQueryPath ? require(window.wangEditorJQueryPath) : require('jquery')
        );
    } else {
```

吧修改结果发给我，我下次升级的时候一起改了。到时候你直接升级版本就行了

**Comment by alankell** [comment]
去掉引入的表达式就OK了,修改下面这个我这边就不报警告了
```javascript
} else if (typeof module === "object" && typeof module.exports === "object") {
        // commonjs
        // css在这里引我觉的没必要,可以让用户在项目模块里引修改后的样式
        module.exports = factory(require("jquery"), require('../css/wangEditor.css'));
 } else {
```

**Comment by wangfupeng1988** [comment]
OK

> css其实没必要引的,因为大部分用户多多少少会改些样式

你说的这个问题，其实应该从另外一个角度考虑。你的意思是让用户自己修改了源码，然后自己再引用，这不符合开放封闭的设计原则。我觉得应该去考虑一种扩展机制——即，编辑器基本的样式还是在自动引用，不修改也OK，但是自己想修改了，再让用户另外扩展一个文件自己引用，而不是修改源码。

**Comment by alankell** [comment]
嗯,如果是js修改源码再引的确不合理,但是css对于开发者来说其实就是一套皮肤,在包外引也没什么问题,当然你做一个默认皮肤也OK啦,depend on you ,哈哈
