### ISSUE TITLE
希望增加编辑器输入框自定义placeholder功能,感觉这个还是必须的

### ISSUE THREAD

**Issue by alankell** [wangfupeng1988/wangEditor#266]
可以模拟一个div飘上去

**Comment by wangfupeng1988** [comment]
富文本增加placeholder不好整啊，给IE8中的`<input>`做一个模拟的placeholder实现的不会太理想，何况是富文本编辑器？

像你说的模拟一个div飘上去，到时可以简单实现这个功能，但是肯定只能满足小部分用户的需求，而且模拟的div实现不了现在placeholder的功能。因此，我暂时先不做placeholder

编辑器支持自定义插件了，你可以试着自己做一个，应该不会太麻烦。有困难可以继续给我留言。

**Comment by alankell** [comment]
个人觉得placeholder这种简单功能不应该做为一个插件,而是应该作为一个选项集成到编辑器当中去,可以根据配置使用,也可配置成不显示,对视觉稍有要求的应该都是需要这个功能的,像simditor和summernote等富文本编辑器其实都是有这个功能的

**Comment by wangfupeng1988** [comment]
不好意思，这个暂时不做，有需要可以通过插件的形式自己实现一个。
