### ISSUE TITLE
火狐下无序列表和有序列表取消后自动增加空行

### ISSUE THREAD

**Issue by yuaptx4869** [wangfupeng1988/wangEditor#267]
![image](https://cloud.githubusercontent.com/assets/7532928/15458874/bede5592-20d1-11e6-9328-70e2c58cb92f.png)
![image](https://cloud.githubusercontent.com/assets/7532928/15458860/aafc2144-20d1-11e6-9ff7-3c808e43d067.png)
![image](https://cloud.githubusercontent.com/assets/7532928/15458881/cdc3a328-20d1-11e6-8ae1-9c76f2a4f5f7.png)
![image](https://cloud.githubusercontent.com/assets/7532928/15458927/40e16bb0-20d2-11e6-8760-88a0276d1914.png)

**Comment by wangfupeng1988** [comment]
OK 我看到你说的问题了，讨厌的浏览器兼容性。。。怪不得火狐现在市场占有率越来越低了

我来查查这个问题吧，有结果了在此回复你。

**Comment by wangfupeng1988** [comment]
今天下午查了，这应该是火狐浏览器对`document.execCommand`的一个兼容性的问题，在 chrome 和 safari 都没有出现过此问题。

目前编辑器对于这些基本的操作（加粗、变色、列表等）使用的都是浏览器自带的`document.execCommand`命令，因此这个情况目前不太好调整。

问题先open着吧，等我有了比较好的解决方案，再去fixed

**Comment by yuaptx4869** [comment]
嗯，会继续关注大大的编辑器，祝越来越好！

**Comment by wangfupeng1988** [comment]
这个怪异问题这一版本先不解决了，下一个大版本争取看看解决掉。
