### ISSUE TITLE
插入视频iframe后显示空白尺寸

### ISSUE THREAD

**Issue by jeeinn** [wangfupeng1988/wangEditor#268]
http://wangeditor.github.io/
插入视频iframe后显示空白块，没有预览图，但是前端能正常显示播放。
插入的embed后台能正常预览。

**Comment by wangfupeng1988** [comment]
> 插入视频iframe后显示空白块，没有预览图，但是前端能正常显示播放

前端能正常显示播放，哪里显示空白块，没有预览图？不明白。

另外，把你想要插入的视频，发给我

**Comment by jeeinn** [comment]
已经正常了，有可能是浏览器缓存或者网络慢问题。
感谢回复！
