### ISSUE TITLE
destory方法只是把编辑器单纯的隐藏了而不是销毁实例

### ISSUE THREAD

**Issue by alankell** [wangfupeng1988/wangEditor#269]
这在单页面里容易创建多个实例,占用内存
![2121](http://gtms03.alicdn.com/tps/i3/TB15OkzJVXXXXcKXpXXza7xTFXX-1406-268.png)

**Comment by wangfupeng1988** [comment]
http://www.kancloud.cn/wangfupeng/wangeditor2/120001 `destroy`设置的本意是暂时不用，对应的方法是`undestroy`，这两个配合一起用。如果真的直接就不用了，把编辑器的DOM元素`remove`，然后将`editor = null`就行了。

另外，你截图中加载了很多`highlight.min.js`，这应该是一个问题，下次升级，我优化一下这个地方。

**Comment by alankell** [comment]
如果不把实例销毁的话,单页面里来回切的时候会报下面一个错,提示之前已经存在了一个编辑器不让用地图菜单了,react里边在`componentWillUnmount`里设置把editor设为null了之后依旧提示这个
```wangEditor.js:535 wangEditor提示: 目前不支持在一个页面多个编辑器上同时使用地图，可通过自定义菜单配置去掉地图菜单```

**Comment by alankell** [comment]
不把实例销毁的话,在单页面里来回切换的时候会爆下面一个错,我在react里当`componentWillUnmount`把editor设为null了,依旧爆这个错不让用地图了,麻烦看一下了
```
wangEditor.js:535 wangEditor提示: 目前不支持在一个页面多个编辑器上同时使用地图，可通过自定义菜单配置去掉地图菜单
```

**Comment by wangfupeng1988** [comment]
我周末去跟踪一下这个问题，有结果了在此回复你。

**Comment by wangfupeng1988** [comment]
关注 https://github.com/wangfupeng1988/wangEditor/releases 中的 `v2.1.12`版本，计划今晚更新。该版本将修复你提到的问题：

第一，判断、避免了`highlight.js`的重复加载；

第二，针对针对第二次`create`时候的地图的错误提示，你可以通过在`editor=null`的同时，执行`wangEditor.numberOfLocation--`操作。`wangEditor.numberOfLocation`就代表了该页面中有几个编辑器正在同时使用地图。先手动`--`一下吧。

----

当初`v2.0`升级的时候，确实没有充分考虑单页面的应用场景、以及augnlar react的这些框架，因为目前有些地方确实非常蹩脚，我也深表惭愧。

下次大版本升级的时候，一定是以当前最主流的单页面、angular vue react 框架、npm等这些基础为准，做一个真正符合用户开发习惯的编辑器！

**Comment by alankell** [comment]
敢问下次大版本升级计划大概是什么时候?

**Comment by wangfupeng1988** [comment]
估计得冬天过年那会儿吧，下半年的计划排满了。

**Comment by harrydengchao** [comment]
我是在vue单页面重使用，遇到了“目前不支持在一个页面多个编辑器上同时使用地图”报错。按作者提供的思路，还是不能解决，是我哪里操作不对吗。
![image](https://cloud.githubusercontent.com/assets/13941171/18776587/ce344f2a-819c-11e6-9316-6694a851ce37.png)

**Comment by vylan** [comment]
同@harrydengchao遇到的问题一样，在angular中对于两个不同的路由中使用地图报同样的错。

**Comment by harrydengchao** [comment]
@vylan 我那里是我自己代码写漏了
```javascript
this.editor = null;
WangEditor.numberOfLocation--;  // 手动清除地图的重复引用，作者的临时解决方案。否则单页面来回切换时，地图报错重复引用
```
这样写就好了
