### ISSUE TITLE
上传图片集成第三方插件问题

### ISSUE THREAD

**Issue by vioao** [wangfupeng1988/wangEditor#270]
在集成文件上传插件插件的时候发现,
初始化后生成的上传图片的按钮的a标间包含href属性，但是没有阻止其默认的跳转行为。导致点击上传图片的按钮后直接页面跳转了。
集成的是 [webuploader](http://fex.baidu.com/webuploader/doc/index.html) 插件

初始化webuploader时获取到的customUploadBtnId为upload7976869253907353
生成的上传按钮html:
`<a href="#" class="upload-icon-container webuploader-container" id="upload7976869253907353"><div class="webuploader-pick webuploader-pick-hover"><i class="wangeditor-menu-img-upload"></i></div><div id="rt_rt_1ajegmq11uq01mvj5iiftv191l6" style="position: absolute; top: 5px; left: 135.5px; width: 65px; height: 71px; overflow: hidden; bottom: auto; right: auto;"><input type="file" capture="camera" name="file" class="webuploader-element-invisible" multiple="multiple"><label style="opacity: 0; width: 100%; height: 100%; display: block; cursor: pointer; background: rgb(255, 255, 255);"></label></div></a>`

**Comment by wangfupeng1988** [comment]
你先在`<div class="webuploader-pick webuploader-pick-hover">`这个元素上阻止`click`事件的冒泡试试。
我下次升级阻止了`<a>`的默认行为。


另外我怎么没在文档中看到这块的说明呢？难道当时我忘记写了？

**Comment by vioao** [comment]
文档中有关于[集成plupload的说明](http://www.kancloud.cn/wangfupeng/wangeditor2/123690)
我是参考这个来写的、暂时直接把a标签的href属性去掉就行了。

**Comment by wangfupeng1988** [comment]
OK 我修复了之后，在此回复你。

**Comment by wangfupeng1988** [comment]
该问题已经修复，下载最新版 https://github.com/wangfupeng1988/wangEditor/releases

这次直接把`<a>`标签换成了`<div>`标签，就不会有点击跳转链接的问题了
