### ISSUE TITLE
自带图片上传不支持设置headers

### ISSUE THREAD

**Issue by vioao** [wangfupeng1988/wangEditor#271]
使用时有需要设置请求的headers的情况,查看源码发现上传图片的时候不支持这个参数。
建议扩展下,类似设置上传的params一样可以设置请求的headers。

**Comment by wangfupeng1988** [comment]
可以加上。不过请说明一下你使用headers参数的场景，因为我写文档时候要有一个场景举例，否则用户看了不知道这是干嘛的。

**Comment by vioao** [comment]
比如说指定接收的Accept的类型。需要指定接收json。这样服务器会返回json格式的结果。
比如说后台需要从请求头中获取特定字段做些特殊校验之类的。
还是有不少情况用得上的。

**Comment by wangfupeng1988** [comment]
我已经merge了你的PR，并且完善了文档 http://www.kancloud.cn/wangfupeng/wangeditor2/113992
