### ISSUE TITLE
可不可以点击按钮直接弹出选择文件窗口，不显示下拉框？

### ISSUE THREAD

**Issue by a12345rwaj** [wangfupeng1988/wangEditor#272]
求解代码或者方法

就是这样
不显示这个下拉框
![2016-05-24 10 11 53](https://cloud.githubusercontent.com/assets/17734732/15507094/b97aff34-21fc-11e6-8e9b-0dd2bff94347.png)
直接跳出这个窗口
![2016-05-24 10 12 02](https://cloud.githubusercontent.com/assets/17734732/15507131/e06ec8fa-21fc-11e6-96ee-0c1bdce158cd.png)

**Comment by wangfupeng1988** [comment]
这个目前还不支持，至少不能通过参数配置来支持。

你这样做的原因，可能是你不需要『插入网络图片』，只需要上传本地图片。但是对于大部分编辑器的用户来说，他们可能都会需要插入网络图片。因此，目前编辑器的配置中，没有你说的这种情况。

有个退一步的建议，就是你把dropPanel中的『网络图片』tab给隐藏掉，这样虽然实现不了你说的效果，但是也能上传本地图片，就是多一步点击而已

**Comment by a12345rwaj** [comment]
我是在手机端用的这个编辑器，所以希望点击就能直接弹出上传图片，可不可以把编辑器的id指向之类的直接改成点击按钮上传

**Comment by wangfupeng1988** [comment]
> 可不可以把编辑器的id指向之类的直接改成点击按钮上传

你自己去修改源码当然可以了，但是我不能直接在产品中改了。
不过你自己修改源码之后，以后更新升级会很麻烦，现在基本一周升一个小版本，修复一周积累的bug

**Comment by a12345rwaj** [comment]
> 你自己去修改源码当然可以了
可不可以提供一些思路呢

**Comment by wangfupeng1988** [comment]
建议：修改源码比较麻烦，你可以考虑自定义扩展一个菜单，群里已经有人自定通过扩展做了上传附件的菜单了。

**简单给你提供一点思路：**
参考 http://www.kancloud.cn/wangfupeng/wangeditor2/115834 其中的代码，其中的`menu.clickEventSelected`和`menu.updateSelectedEvent`两个函数你都不需要，可忽略。你重点需要编写`menu.clickEvent`函数的内容——这个函数就是菜单点击的时候触发——你可以在里面定义，菜单点击的时候弹出文件选择窗口。

然后，选中文件之后，再去将图片文件上传，上传之后，将图片的url地址插入到编辑器中。如果插入到编辑器中，可参考 http://www.kancloud.cn/wangfupeng/wangeditor2/123689 其中的`editor.command(null, 'insertHtml', '<img src="' + resultText + '" alt="' + originalName + '" style="max-width:100%;"/>');`

大体上这么个思路，如果你仔细看看文档，相信不难。有问题再反馈

**Comment by wangfupeng1988** [comment]
暂时关闭，有问题可继续在下面留言

**Comment by a12345rwaj** [comment]
这样做之后报错了，提示uploadimg.js:35 Uncaught TypeError: Cannot read property 'uploadImgFns' of undefined
![2016-06-04 9 27 32](https://cloud.githubusercontent.com/assets/17734732/15799796/3c8d7086-2a9b-11e6-866d-73e16d6205bb.png)

**Comment by a12345rwaj** [comment]
或者 可不可以这样，我看源文件里有一个这个按钮
 // 上传图片 content
var $uploadContent = $('<div class="content"></div>');

能不能自定义一个按钮，直接调用这个的click方法呢？

**Comment by a12345rwaj** [comment]
var upfile = new E.UploadFile({
            editor: editor,
            uploadUrl: uploadImgUrl,
            timeout: uploadTimeout,
            fileAccept: 'image/*'    // 只允许选择图片 
       });
		// 菜单正常状态下，点击将触发该事件
		menu.clickEvent = function(e) {
           	event = e;
            upfile.selectFiles();
            upfile.selected();
            upfile.upload();
//          var imgHtml = '<img style="max-width:100%;" src="' + url + '"/>';
//          editor.command(e, 'insertHtml', imgHtml);

		
		};
我现在的代码卡在这里了，不知道该怎么做了

在pc端还能弹出选择文件页面，到了手机端就不好用了，求解 谢谢了

**Comment by wangfupeng1988** [comment]
我强烈不建议你修改源码，因为我后期还会做很多优化和升级。你修改了源码之后，以后如何升级了？

扩展插件出错，可以寻找原因

> 这样做之后报错了，提示uploadimg.js:35 Uncaught TypeError: Cannot read property 'uploadImgFns' of undefined

在你这个回复中，我看到了两个错误（截图中），第一个是你说的`uploadImgFns`未定义，第二个还有一个跨域的bug，你自己去看看吧。

`uploadImgFns`未定义，你也得去找找原因吧，你这个变量是从哪里来的，为何提示未定义，把关键代码贴出来看看。

**Comment by a12345rwaj** [comment]
var upfile = new E.UploadFile({
            editor: editor,
            uploadUrl: uploadImgUrl,
            timeout: uploadTimeout,
            fileAccept: 'image/*'    // 只允许选择图片 
       });
		// 菜单正常状态下，点击将触发该事件
		menu.clickEvent = function(e) {
           	upfile.selectFiles();
		};

我就直接加的这一行代码

**Comment by 976500133** [comment]
看了木木的自定义组件的方式， 然而在自定义上传的时候是不行的。 会报如下错误

**Comment by 976500133** [comment]
我用最简单的方式解决了这个问题。

     ```
   Menu.fn.activeStyle = function (active) {
            var selected = this.selected
            var $dom = this.$domNormal
            var $domSelected = this.$domSelected

            if (active) {
                $dom.addClass('active')
                $domSelected.addClass('active')

                if(this.id === 'img'){
                    $('.wangEditor-drop-panel').css('display','none')
                    setTimeout(function () {
                        $('.upload-icon-container').click()
                    }, 0)
                }

            } else {

                $dom.removeClass('active')
                $domSelected.removeClass('active')
            }

            // 记录状态 （ menu hover 时会取状态用 ）
            this.active(active)
        }
```
