### ISSUE TITLE
保存修改第二次会多一个P生成

### ISSUE THREAD

**Issue by Frankseek** [wangfupeng1988/wangEditor#274]
​
不知道这个BUG能不能解决
![image](https://cloud.githubusercontent.com/assets/17483480/15535594/9ad06ab6-22a0-11e6-9d4b-0f62bffc9233.png)

**Comment by wangfupeng1988** [comment]
> 第二次打开修改第一次编辑的代码

这块的逻辑请你详细描述清楚。这里的第二次打开时候，第一次的代码是如何加载进去的？像这些细节你都得给我，还要告诉我什么浏览器什么系统，我才能准确定位问题。

看到之后及时反馈给我，我周末验证，有结果了在此回复你。

**Comment by wangfupeng1988** [comment]
暂时关闭，有疑问再继续留言
