### ISSUE TITLE
angularjs下上传不了本地图片

### ISSUE THREAD

**Issue by windluo** [wangfupeng1988/wangEditor#275]
如题。我的项目还用到了webuploader，上传图片是OK的。（不知道这个怎么上传图片，就纯文字了）
webuploader上传本地图片时，后台监控：
      _上传文件名称 20160525-b7fe85ad-b5ac-4fb1-bdc8-54e7a131ff9f.jpg, 
       复制文件内容到 /usr/local/apache-tomcat-8.0.32/public/20160525-b7fe85ad-b5ac-4fb1-bdc8-54e7a131ff9f.jpg_

wangEditor上传本地图片时，后台监控：（）什么也拿不到。

**Comment by wangfupeng1988** [comment]
你看看http抓包啊，http的请求中有没有图片数据。

或者看看这篇文章 http://www.kancloud.cn/wangfupeng/wangeditor2/131049

**Comment by windluo** [comment]
没有哦。

因为我们这边是前后端分离的，所以····哈哈。
我引入了webuploader上传图片，这个没有问题。

还是很感谢你的帮助，谢谢。

在 2016-05-27 09:50:13，"王福朋" <notifications@github.com> 写道：


你看看http抓包啊，http的请求中有没有图片数据。

或者看看这篇文章 http://www.kancloud.cn/wangfupeng/wangeditor2/131049

**Comment by wangfupeng1988** [comment]
前后端分离和http转包没关系的，你去看看 http://www.kancloud.cn/wangfupeng/wangeditor2/131049 
有问题再回复

**Comment by windluo** [comment]
我的意思是不想麻烦后台了。
因为wangEditor不能粘贴结构样式，我又换回了原来的富文本编辑器。上传图片用了webuploder。
现在没问题了，谢谢你的帮助！

在 2016-05-27 15:18:19，"王福朋" <notifications@github.com> 写道：


前后端分离和http转包没关系的，你去看看 http://www.kancloud.cn/wangfupeng/wangeditor2/131049
有问题再回复
