### ISSUE TITLE
当在同一个界面上有多个编辑器，上传图片总是显示在最后一个编辑器上。

### ISSUE THREAD

**Issue by honpery** [wangfupeng1988/wangEditor#277]
是搭配angular使用的。

**Comment by honpery** [comment]
```
// 自定义load事件
$scope.editor.config.uploadImgFns.onload = function(resultText, xhr) {
     var result = JSON.parse(resultText).result.url.substr(1);
     $scope.editor.command(null, 'insertHtml', '<img src="' + result + '" style="max-width:100%;"/>');
};
```
这个是上传部分的代码。

**Comment by honpery** [comment]
https://github.com/tengwanll/project/blob/master/Public/Admin/scripts/directives/editor/editor.js

**Comment by wangfupeng1988** [comment]
>  当在同一个界面上有多个编辑器，上传图片总是显示在最后一个编辑器上，是搭配angular使用的

你先不要使用angular，就做一个简单的单页面多编辑器的demo，看看上传的位置是不是正常？

我周末也会去验证一下，如果demo正常，那应该不是编辑器的问题。有结果在此回复你

**Comment by wangfupeng1988** [comment]
暂时关闭，有疑问再继续留言

**Comment by honpery** [comment]
不好意思，最近比较忙。
https://github.com/tengwanll/project/blob/master/Public/Admin/scripts/directives/editor/editor.js
还是这部分代码，第77行和第96行，我分别打印了内容，这个时候是不一样的，我想是不是您的文件里作用域的问题？还是我的代码有些问题呢？
