### ISSUE TITLE
常见css样式冲突，一般ul，ol 默认样式都设置没了。

### ISSUE THREAD

**Issue by xxShawn** [wangfupeng1988/wangEditor#278]
ul，ol 的默认样式设置没了之后，
再使用派讯命令时候，列表前面的标志没有了啊，一般默认样式都会把他们设置掉的。。

**Comment by wangfupeng1988** [comment]
> 派讯命令

啥意思？

**Comment by xxShawn** [comment]
ol,ul的默认样式，类似于这种排序的   一般都会清除浏览器的默认样式，然后这些
1.
2.
3.

·
·
·
然后这样的样式都没了啊  editor里面好像是使用的都是默认的样式吧。

**Comment by wangfupeng1988** [comment]
> 然后这些  然后这样的样式都没了啊

你描述的太模糊了，我还是没看明白你的问题。描述问题应该说明操作之前的状态，如何操作（详细场景），操作之后的错误状态，以及期望的成功状态。

**Comment by yeyunzhixian** [comment]
他的意思是ul和ol样式重置了，没有list-style

**Comment by wangfupeng1988** [comment]
> 他的意思是ul和ol样式重置了，没有list-style，这个其实前台样式控制就好了

@xxShawn 不知道这个回复是否你的意思？

**Comment by wangfupeng1988** [comment]
> 他的意思是ul和ol样式重置了，没有list-style

这个问题在demo中无法复现，自己看看样式冲突吧。
