### ISSUE TITLE
可以动态添加及替换内容吗？

### ISSUE THREAD

**Issue by pshaoyi** [wangfupeng1988/wangEditor#279]
比如我插一段签名信息，然后想换个签名内容，以目前的功能只能手动删除然后在append进去，这样操作就比较麻烦，不够灵活。

**Comment by wangfupeng1988** [comment]
是的，目前是将编辑器区域的 `<div>`标签暴露给用户，让用户自己来做任何操作。

> 比如我插一段签名信息，然后想换个签名内容

我没看明白你的问题，替换签名内容是什么意思？具体操作场景是什么？如果不用append等方法，你希望有什么样更加方便的API来支持你。

这些最好都写写，让我更加清楚的了解问题

**Comment by pshaoyi** [comment]
谢谢你能回答我的问题，我意思就是可以通过某个按钮给编辑器插一段签名，再次点击按钮的时候可以直接替换文本框内的签名内容。
在内容插入一个固定标示的<div>标签或者别的标签，然后我通过编辑对象去找到这个<div>元素，然后替换元素里面的文本内容。

**Comment by wangfupeng1988** [comment]
大体明白你的意思了，你这个功能如果写一个插件，其实很好实现，插件文档 http://www.kancloud.cn/wangfupeng/wangeditor2/115837

代码大体内容如下：

```javascript
(function () {

    // 获取 wangEditor 构造函数和 jquery
    var E = window.wangEditor;
    var $ = window.jQuery;

    // 通过 E.plugin 注入插件代码
    E.plugin(function () {

        // 此处的 this 指向 editor 对象本身
        var editor = this;
        var $txt = editor.$txt;

        var id = 'xxxxxxxxx';

        editor.insertElem = function () {
            // 在此插入一个 <div id="' + id + '"> 标签
        }

        editor.editElem = function () {
            // 去修改 <div id="' + id + '"> 标签的内容
        }
    });

})();
```

以上插件写完之后，`insertElem`和`editElem`就会暴露给用户，就可以实现你的需求了

**Comment by pshaoyi** [comment]
好的，谢谢你的回复
