### ISSUE TITLE
editor 上传错误

### ISSUE THREAD

**Issue by mrtang123** [wangfupeng1988/wangEditor#280]
wangEditor.js:3013 wangEditor提示: 本页面富文本编辑器由 wangEditor 提供 http://wangeditor.github.io/ 
wangEditor.js:3013 wangEditor提示: 正在处理 微博表情 表情的数据...
wangEditor.js:3013 wangEditor提示: 建议在配置中自定义百度地图的mapAk，否则可能影响地图功能，文档：http://www.kancloud.cn/wangfupeng/wangeditor2/113961
wangEditor.js:3013 wangEditor提示: 本页面富文本编辑器由 wangEditor 提供 http://wangeditor.github.io/ 
wangEditor.js:3013 wangEditor提示: 正在处理 微博表情 表情的数据...
wangEditor.js:3013 wangEditor提示: 建议在配置中自定义百度地图的mapAk，否则可能影响地图功能，文档：http://www.kancloud.cn/wangfupeng/wangeditor2/113961
wangEditor.js:3013 wangEditor提示: 使用 html5 方式上传
wangEditor.js:3013 wangEditor提示: 渲染dom
wangEditor.js:3013 wangEditor提示: 选择文件
wangEditor.js:3013 wangEditor提示: 选中 1 个文件
wangEditor.js:3013 wangEditor提示: 开始执行 111.gif 文件的上传
wangEditor.js:3013 wangEditor提示: 已读取111.gif文件
wangEditor.js:3013 wangEditor提示: 开始上传...并开始超时计算
wangEditor.js:3013 wangEditor提示: input value 已清空
wangEditor.js:3013 wangEditor提示: 上传上图片发生错误E.(anonymous function) @ wangEditor.js:3013fns.ontimeout.fns.ontimeout @ wangEditor.js:6455editor.xhrUploadImg.timeoutfn @ wangEditor.js:6875timeoutCallback @ wangEditor.js:6585
在网速慢的时候使用该上传图片功能超时导致无法上传。

**Comment by wangfupeng1988** [comment]
> wangEditor.js:3013 wangEditor提示: 上传上图片发生错误E.(anonymous function) @ 

你使用的哪个版本，我现在用最新版本看 3013 行貌似不会报什么错误。我需要定位到报错的那一行，然后分析你的问题。

**Comment by wangfupeng1988** [comment]
我今天在修复其他bug时候遇到一个和你类似的错误，发现是这段代码提示的

```javascript
        // -------- 定义tiemout函数 --------
        fns.ontimeout || (fns.ontimeout = function (xhr) {
            E.error('上传上图片发生错误');
            alert('上传上图片发生错误');
        });

        // -------- 定义error函数 --------
        fns.onerror || (fns.onerror = function (xhr) {
            E.error('上传图片超时');
            alert('上传图片超时');
        });
```

首先，我这里的提示写错了，`error`和`timeout`的提示写颠倒了，我会在这次升级修改过来。

我今天遇到的换个问题，是因为我没有把图片文件上传到后台，后台接收不到图片、报错了，因此前台提示了这个错误。我怀疑你这个问题，后台肯定没有正确保存或者处理好图片，你可以跟踪一下后台的代码看看。

**Comment by wangfupeng1988** [comment]
暂时关闭，有疑问可继续在下面留言

**Comment by AAAYINGCHAO** [comment]
wangEditor提示: 使用返回的结果获取图片，发生错误。请确认以下结果是否正确：<script> Sfdump = window.Sfdump || (function (doc) { var refStyle = doc.createElement('style'), rxEsc = /([.*+?^${}()|\[\]\/\\])/g, idRx = /\bsf-dump-\d+-ref[012]\w+\b/, keyHint = 0 <= navigator.platform.toUpperCase().indexOf('MAC') ? 'Cmd' : 'Ctrl', addEventListener = function (e, n, cb) { e.addEventListener(n, cb, false); }; (doc.documentElement.firstElementChild || doc.documentElement.children[0]).appendChild(refStyle); if (!doc.addEventListener) { addEventListener = function (element, eventName, callback) { element.attachEvent('on' + eventName, function (e) { e.preventDefault = function () {e.returnValue = false;}; e.target = e.srcElement; callback(e); }); }; } function toggle(a, recursive) { var s = a.nextSibling || {}, oldClass = s.className, arrow, newClass; if ('sf-dump-compact' == oldClass) { arrow = '&#9660;'; newClass = 'sf-dump-expanded'; } else if ('sf-dump-expanded' == oldClass) { arrow = '&#9654;'; newClass = 'sf-dump-compact'; } else { return false; } a.lastChild.innerHTML = arrow; s.className = newClass; if (recursive) { try { a = s.querySelectorAll('.'+oldClass); for (s = 0; s < a.length; ++s) { if (a[s].className !== newClass) { a[s].className = newClass; a[s].previousSibling.lastChild.innerHTML = arrow; } } } catch (e) { } } return true; }; return function (root, x) { root = doc.getElementById(root); var indentRx = new RegExp('^('+(root.getAttribute('data-indent-pad') || ' ').replace(rxEsc, '\\$1')+')+', 'm'), options = {"maxDepth":1,"maxStringLength":160,"fileLinkFormat":false}, elt = root.getElementsByTagName('A'), len = elt.length, i = 0, s, h, t = []; while (i < len) t.push(elt[i++]); for (i in x) { options[i] = x[i]; } function a(e, f) { addEventListener(root, e, function (e) { if ('A' == e.target.tagName) { f(e.target, e); } else if ('A' == e.target.parentNode.tagName) { f(e.target.parentNode, e); } else if (e.target.nextElementSibling && 'A' == e.target.nextElementSibling.tagName) { f(e.target.nextElementSibling, e, true); } }); }; function isCtrlKey(e) { return e.ctrlKey || e.metaKey; } addEventListener(root, 'mouseover', function (e) { if ('' != refStyle.innerHTML) { refStyle.innerHTML = ''; } }); a('mouseover', function (a, e, c) { if (c) { e.target.style.cursor = "pointer"; } else if (a = idRx.exec(a.className)) { try { refStyle.innerHTML = 'pre.sf-dump .'+a[0]+'{background-color: #B729D9; color: #FFF !important; border-radius: 2px}'; } catch (e) { } } }); a('click', function (a, e, c) { if (/\bsf-dump-toggle\b/.test(a.className)) { e.preventDefault(); if (!toggle(a, isCtrlKey(e))) { var r = doc.getElementById(a.getAttribute('href').substr(1)), s = r.previousSibling, f = r.parentNode, t = a.parentNode; t.replaceChild(r, a); f.replaceChild(a, s); t.insertBefore(s, r); f = f.firstChild.nodeValue.match(indentRx); t = t.firstChild.nodeValue.match(indentRx); if (f && t && f[0] !== t[0]) { r.innerHTML = r.innerHTML.replace(new RegExp('^'+f[0].replace(rxEsc, '\\$1'), 'mg'), t[0]); } if ('sf-dump-compact' == r.className) { toggle(s, isCtrlKey(e)); } } if (c) { } else if (doc.getSelection) { try { doc.getSelection().removeAllRanges(); } catch (e) { doc.getSelection().empty(); } } else { doc.selection.empty(); } } else if (/\bsf-dump-str-toggle\b/.test(a.className)) { e.preventDefault(); e = a.parentNode.parentNode; e.className = e.className.replace(/sf-dump-str-(expand|collapse)/, a.parentNode.className); } }); elt = root.getElementsByTagName('SAMP'); len = elt.length; i = 0; while (i < len) t.push(elt[i++]); len = t.length; for (i = 0; i < len; ++i) { elt = t[i]; if ('SAMP' == elt.tagName) { elt.className = 'sf-dump-expanded'; a = elt.previousSibling || {}; if ('A' != a.tagName) { a = doc.createElement('A'); a.className = 'sf-dump-ref'; elt.parentNode.insertBefore(a, elt); } else { a.innerHTML += ' '; } a.title = (a.title ? a.title+'\n[' : '[')+keyHint+'+click] Expand all children'; a.innerHTML += '<span>&#9660;</span>'; a.className += ' sf-dump-toggle'; x = 1; if ('sf-dump' != elt.parentNode.className) { x += elt.parentNode.getAttribute('data-depth')/1; } elt.setAttribute('data-depth', x); if (x > options.maxDepth) { toggle(a); } } else if ('sf-dump-ref' == elt.className && (a = elt.getAttribute('href'))) { a = a.substr(1); elt.className += ' '+a; if (/[\[{]$/.test(elt.previousSibling.nodeValue)) { a = a != elt.nextSibling.id && doc.getElementById(a); try { s = a.nextSibling; elt.appendChild(a); s.parentNode.insertBefore(a, s); if (/^[@#]/.test(elt.innerHTML)) { elt.innerHTML += ' <span>&#9654;</span>'; } else { elt.innerHTML = '<span>&#9654;</span>'; elt.className = 'sf-dump-ref'; } elt.className += ' sf-dump-toggle'; } catch (e) { if ('&' == elt.innerHTML.charAt(0)) { elt.innerHTML = '&hellip;'; elt.className = 'sf-dump-ref'; } } } } } if (0 >= options.maxStringLength) { return; } try { elt = root.querySelectorAll('.sf-dump-str'); len = elt.length; i = 0; t = []; while (i < len) t.push(elt[i++]); len = t.length; for (i = 0; i < len; ++i) { elt = t[i]; s = elt.innerText || elt.textContent; x = s.length - options.maxStringLength; if (0 < x) { h = elt.innerHTML; elt[elt.innerText ? 'innerText' : 'textContent'] = s.substring(0, options.maxStringLength); elt.className += ' sf-dump-str-collapse'; elt.innerHTML = '<span class=sf-dump-str-collapse>'+h+'<a class="sf-dump-ref sf-dump-str-toggle" title="Collapse"> &#9664;</a></span>'+ '<span class=sf-dump-str-expand>'+elt.innerHTML+'<a class="sf-dump-ref sf-dump-str-toggle" title="'+x+' remaining characters"> &#9654;</a></span>'; } } } catch (e) { } }; })(document); </script><style> pre.sf-dump { display: block; white-space: pre; padding: 5px; } pre.sf-dump span { display: inline; } pre.sf-dump .sf-dump-compact { display: none; } pre.sf-dump abbr { text-decoration: none; border: none; cursor: help; } pre.sf-dump a { text-decoration: none; cursor: pointer; border: 0; outline: none; color: inherit; } pre.sf-dump .sf-dump-ellipsis { display: inline-block; overflow: visible; text-overflow: ellipsis; max-width: 5em; white-space: nowrap; overflow: hidden; vertical-align: top; } pre.sf-dump code { display:inline; padding:0; background:none; } .sf-dump-str-collapse .sf-dump-str-collapse { display: none; } .sf-dump-str-expand .sf-dump-str-expand { display: none; }pre.sf-dump, pre.sf-dump .sf-dump-default{background-color:#fff; color:#222; line-height:1.2em; font-weight:normal; font:12px Monaco, Consolas, monospace; word-wrap: break-word; white-space: pre-wrap; position:relative; z-index:100000}pre.sf-dump .sf-dump-num{color:#a71d5d}pre.sf-dump .sf-dump-const{color:#795da3}pre.sf-dump .sf-dump-str{color:#df5000}pre.sf-dump .sf-dump-cchr{color:#222}pre.sf-dump .sf-dump-note{color:#a71d5d}pre.sf-dump .sf-dump-ref{color:#a0a0a0}pre.sf-dump .sf-dump-public{color:#795da3}pre.sf-dump .sf-dump-protected{color:#795da3}pre.sf-dump .sf-dump-private{color:#795da3}pre.sf-dump .sf-dump-meta{color:#b729d9}pre.sf-dump .sf-dump-key{color:#df5000}pre.sf-dump .sf-dump-index{color:#a71d5d}</style><pre class=sf-dump id=sf-dump-2015968329 data-indent-pad="  "><span class=sf-dump-note>array:1</span> [<samp>
  "<span class=sf-dump-key>wangEditorH5File</span>" => <abbr title="Illuminate\Http\UploadedFile" class=sf-dump-note>UploadedFile</abbr> {<a class=sf-dump-ref>#171</a><samp>
    -<span class=sf-dump-private title="Private property defined in class:&#10;`Symfony\Component\HttpFoundation\File\UploadedFile`">test</span>: <span class=sf-dump-const>false</span>
    -<span class=sf-dump-private title="Private property defined in class:&#10;`Symfony\Component\HttpFoundation\File\UploadedFile`">originalName</span>: "<span class=sf-dump-str title="20 characters">9579146345176821.png</span>"
    -<span class=sf-dump-private title="Private property defined in class:&#10;`Symfony\Component\HttpFoundation\File\UploadedFile`">mimeType</span>: "<span class=sf-dump-str title="9 characters">image/png</span>"
    -<span class=sf-dump-private title="Private property defined in class:&#10;`Symfony\Component\HttpFoundation\File\UploadedFile`">size</span>: <span class=sf-dump-num>320709</span>
    -<span class=sf-dump-private title="Private property defined in class:&#10;`Symfony\Component\HttpFoundation\File\UploadedFile`">error</span>: <span class=sf-dump-num>0</span>
    <span class=sf-dump-meta>path</span>: "<span class=sf-dump-str title="13 characters">G:\wamp64\tmp</span>"
    <span class=sf-dump-meta>filename</span>: "<span class=sf-dump-str title="11 characters">php8E72.tmp</span>"
    <span class=sf-dump-meta>basename</span>: "<span class=sf-dump-str title="11 characters">php8E72.tmp</span>"
    <span class=sf-dump-meta>pathname</span>: "<span class=sf-dump-str title="25 characters">G:\wamp64\tmp\php8E72.tmp</span>"
    <span class=sf-dump-meta>extension</span>: "<span class=sf-dump-str title="3 characters">tmp</span>"
    <span class=sf-dump-meta>realPath</span>: "<span class=sf-dump-str title="G:\wamp64\tmp\php8E72.tmp
25 characters"><span class=sf-dump-ellipsis>G:\wamp64</span>\tmp\php8E72.tmp</span>"
    <span class=sf-dump-meta>aTime</span>: <span class=sf-dump-const title="1556975265">2019-05-04 21:07:45</span>
    <span class=sf-dump-meta>mTime</span>: <span class=sf-dump-const title="1556975265">2019-05-04 21:07:45</span>
    <span class=sf-dump-meta>cTime</span>: <span class=sf-dump-const title="1556975265">2019-05-04 21:07:45</span>
    <span class=sf-dump-meta>inode</span>: <span class=sf-dump-num>0</span>
    <span class=sf-dump-meta>size</span>: <span class=sf-dump-num>320709</span>
    <span class=sf-dump-meta>perms</span>: <span class=sf-dump-const title="33206">0100666</span>
    <span class=sf-dump-meta>owner</span>: <span class=sf-dump-num>0</span>
    <span class=sf-dump-meta>group</span>: <span class=sf-dump-num>0</span>
    <span class=sf-dump-meta>type</span>: "<span class=sf-dump-str title="4 characters">file</span>"
    <span class=sf-dump-meta>writable</span>: <span class=sf-dump-const>true</span>
    <span class=sf-dump-meta>readable</span>: <span class=sf-dump-const>true</span>
    <span class=sf-dump-meta>executable</span>: <span class=sf-dump-const>false</span>
    <span class=sf-dump-meta>file</span>: <span class=sf-dump-const>true</span>
    <span class=sf-dump-meta>dir</span>: <span class=sf-dump-const>false</span>
    <span class=sf-dump-meta>link</span>: <span class=sf-dump-const>false</span>
    <span class=sf-dump-meta>linkTarget</span>: "<span class=sf-dump-str title="25 characters">G:\wamp64\tmp\php8E72.tmp</span>"
  </samp>}
</samp>]
</pre><script>Sfdump("sf-dump-2015968329")</script>

**Comment by AAAYINGCHAO** [comment]
这怎么解决
