### ISSUE TITLE
多个富文本框的时候代码框会背遮住

### ISSUE THREAD

**Issue by liuww111** [wangfupeng1988/wangEditor#281]
多个富文本框的时候代码框会背遮住（版本：wangeditor.js 2016-03-13 ）

**Comment by wangfupeng1988** [comment]
OK，我get到这个问题了，下次升级版本的时候修复这个问题。fixed之后在此回复你

感谢反馈

**Comment by wangfupeng1988** [comment]
这个问题，我写了一个解决方案 http://www.kancloud.cn/wangfupeng/wangeditor2/167548 可现参考。有建议和疑问继续回复
