### ISSUE TITLE
图片上传问题

### ISSUE THREAD

**Issue by lishichao** [wangfupeng1988/wangEditor#282]
集成成功后，点击图片标签没有本地上传图片功能，只有让输入网址上传图片功能

**Comment by wangfupeng1988** [comment]
没看文档就提问的，不予回复。

**Comment by lishichao** [comment]
不是不看文档，是你们的文档打不开啊，提示页面错误

**Comment by wangfupeng1988** [comment]
http://www.kancloud.cn/wangfupeng/wangeditor2/   大家都在看这个文档，你那里打不开，可以去同事或者其他电脑看看能不能打开。这个 `www.kancloud.cn` 提供的服务，还是比较好的。

如果你那儿就是打不开，谁的电脑也打不开，我就没办法了。。。
