### ISSUE TITLE
初始化后,editor.$txt.append() 追加内容时。追加的内容不在第一行。

### ISSUE THREAD

**Issue by vioao** [wangfupeng1988/wangEditor#286]
问题如上。
还有一个问题，缺少在在光标位置追加内容的api。使用append只能在最末尾添加内容。很多情况下都不够用的。

**Comment by wangfupeng1988** [comment]
那当然啊，这个`append()`就是jquery的`append()`，当然是追加到末尾了。

光标位置添加内容使用 `editor.command(event, 'insertHtml', '<p>要添加的内容</p>')`，这里的`event`是事件对象，没有可用`null`代替

**Comment by vioao** [comment]
thx。之前文档没看这么细
