### ISSUE TITLE
多富文本框上传图片问题

### ISSUE THREAD

**Issue by atomperson** [wangfupeng1988/wangEditor#287]
我在同一个页面实例化两个富文本框，在第一个里面上传图，获取到地址插入图片却是插在第二个富文本框里。

**Comment by wangfupeng1988** [comment]
我回头验证一下，再回复你吧（这个问题我记得之前修复过）

**Comment by wangfupeng1988** [comment]
我测试没有复现这个问题。

我记得之前有过这个问题，后来解决掉了，不过是很早之前的事儿了。你的代码是不是最新的？

**Comment by wangfupeng1988** [comment]
暂时不关闭，有问题再继续留言即可
