### ISSUE TITLE
帮忙看一下我自定义的添加分割线的插件？哪里出问题了？谢谢

### ISSUE THREAD

**Issue by a12345rwaj** [wangfupeng1988/wangEditor#288]
// 获取 wangEditor 构造函数和 jquery
	var E = window.wangEditor;
	var $ = window.jQuery;

	// 用 createMenu 方法创建菜单
	E.createMenu(function(check) {

		// 定义菜单id，不要和其他菜单id重复。编辑器自带的所有菜单id，可通过『参数配置-自定义菜单』一节查看
		var menuId = 'hrapp';

		// check将检查菜单配置（『参数配置-自定义菜单』一节描述）中是否该菜单id，如果没有，则忽略下面的代码。
		if (!check(menuId)) {
			return;
		}

		// this 指向 editor 对象自身
		var editor = this;

		// 创建 menu 对象
		var menu = new E.Menu({
			editor: editor, // 编辑器对象
			id: menuId, // 菜单id

			title: '分割线', // 菜单标题

			// 正常状态和选中状态下的dom对象，样式需要自定义
			$domNormal: $('<a href="#" tabindex="-1"><i class="fa fa-minus"></i></a>'),
			$domSelected: $('<a href="#" tabindex="-1" class="selected"><i class="fa fa-minus"></i></a>')
		});

		// 菜单正常状态下，点击将触发该事件
		menu.clickEvent = function(e) {
			// 找到当前选区所在的 p 元素
			var elem = editor.getRangeElem();
			var p = editor.getSelfOrParentByName(elem, 'p');
			var $p;

			if (!p) {
				// 未找到 p 元素，则忽略
				return e.preventDefault();

			}

			// 使用自定义命令
			function commandFn() {
				var hrLine = document.createElement('hr');
				elem.appendChild(hrLine);
			}

			editor.customCommand(e, commandFn);
		};

		// 菜单选中状态下，点击将触发该事件
		menu.clickEventSelected = function(e) {
			// 找到当前选区所在的 p 元素
			var elem = editor.getRangeElem();
			var p = editor.getSelfOrParentByName(elem, 'p');
			var $p;
			var range = editor.currentRange();

			if (!p) {
				// 未找到 p 元素，则忽略
				return e.preventDefault();
			}
			$p = $(p);

			// 使用自定义命令
			function commandFn() {
				var hrLine = document.createElement('hr');
				elem.appendChild(hrLine);
			}
			editor.customCommand(e, commandFn);
		};

		// 根据当前选区，自定义更新菜单的选中状态或者正常状态
		menu.updateSelectedEvent = function() {
			// 获取当前选区所在的父元素
			var elem = editor.getRangeElem();
			var p = editor.getSelfOrParentByName(elem, 'p');
			var $p;
			var indent;

			if (!p) {
				// 未找到 p 元素，则标记为未处于选中状态
				return false;

			}
			return true;
		};

		// 增加到editor对象中
		editor.menus[menuId] = menu;
	});

这么写有几个问题，

1. 点击插入分割线有的时候会不好使， 比如插入图片，引用之后就插入不好用了

2.我想插入hr的同时获取鼠标焦点，转到下一行，光标直接移到下一行编辑，这个也不可以

3.点击一次之后样式不会更改，图标一直是红色的

希望大神有时间帮忙指导下，谢谢

图传不上去。。。

可以加到文件里试一下

**Comment by wangfupeng1988** [comment]
你不是就想插入一个`<hr>`？

如果那样的话，`menu.clickEventSelected`和`menu.updateSelectedEvent`这两个函数完全可以不用定义，就插入一个横线还要什么『选中状态』呀？想删除的时候，通过键盘删除就是了。

另外，`menu.clickEvent`这个函数没必要定义的这么负责，这样写即可
```js
menu.clickEvent = function(e) {
    editor.command(e, 'insertHtml', '<hr>');
};
```

你去试试吧

**Comment by wangfupeng1988** [comment]
暂时关闭，有疑问再继续留言
