### ISSUE TITLE
不知道可以获取光标所在行数

### ISSUE THREAD

**Issue by masonwu311** [wangfupeng1988/wangEditor#289]
大家好！需求是这样的，我需要跟踪onchange事件，然后判断是哪一行发生了变化，哪一行增加或者减少了，不知道怎样满足这样的需求呢？
比如下面的内容
```
<p>测试1</p>
<p>测试2</p>
<p>测试3</p>
```
如果当前改变的是把“测试2”改成了“测试4”，我怎么知道是第二行发生了变化。

**Comment by wangfupeng1988** [comment]
你这个需求和编辑无关的，得靠你自己计算。

你修改之前的数据是
```html
<p>测试1</p>
<p>测试2</p>
<p>测试3</p>
```
修改之后的数据是
```html
<p>测试1</p>
<p>测试4</p>
<p>测试3</p>
```
然后『我怎么知道是第二行发生了变化』得靠你自己计算，编辑器不会管这个。

---

目前编辑器可见的问题就是，你在`onchange`事件中，只能得到修改之后的内容，而得不到修改之前的内容。其实获取修改之前的内容，方法是有的。例如你刚刚给编辑器赋值的时候，将内容存储到`prevValue`变量中，作为第一次`onchange`事件的『修改之前的内容』，而每次`onchange`事件中，你都将内容存储到`prevValue`变量中，作为下一次`onchange`事件的『修改之前的内容』。问题就解决了。

---

另外，你要想做这个功能，估计会挺费劲，因为它已经接近一个`svn`或者`git`的`diff`功能了，这块我没做过，但是感觉还是蛮复杂的。

**Comment by masonwu311** [comment]
好的谢谢 ，已经用这个api：http://www.kancloud.cn/wangfupeng/wangeditor2/115831 解决了这个需求
