### ISSUE TITLE
编辑器的menu栏下面多余一个空行

### ISSUE THREAD

**Issue by beijishiqidu** [wangfupeng1988/wangEditor#29]
![well](https://cloud.githubusercontent.com/assets/14070935/9600556/45a90d62-50ce-11e5-9c14-cd18e42385fa.jpg)
![bad](https://cloud.githubusercontent.com/assets/14070935/9600557/45dc902e-50ce-11e5-9389-7ffd0d663551.jpg)

上图中一个正常的，一个是多余一个空行，对css文件只做了稍微的定制，
1.增加了每个menu之前的距离和每个图标的左右间距；
2.去掉了菜单的分割线(好像是一个border)。
其余的并没有做什么操作了，图中好的那个跟有问题的这个调用方式是一模一样的，唯独两个地方的宽度不一样，不知道是什么问题。

debug看到如下截图：
![debug](https://cloud.githubusercontent.com/assets/14070935/9600658/d3b6e85e-50ce-11e5-8713-a8dc1943ba87.png)

**Comment by beijishiqidu** [comment]
复制了你的上传图片视频中的例子，做了菜单的自定义，就这些操作。

**Comment by wangfupeng1988** [comment]
这样，你做成一个静态的demo，这个demo要能复现你所描述的问题，然后发给我： 642009075#qq.com

我通过跟踪源码，帮你查查这个问题。

发邮件时候别忘了问题的截图和描述。

**Comment by beijishiqidu** [comment]
嗯，问题已经找到原因了，好的那个页面没有用浮动，坏的那个页面用的左右布局，左边给了一个浮动，就会影响了这个editor的菜单布局展示。多谢福朋兄。
