### ISSUE TITLE
给文字加上背景之后再放大字体，文字背景颜色大小没变

### ISSUE THREAD

**Issue by RitterHou** [wangfupeng1988/wangEditor#291]

**Comment by wangfupeng1988** [comment]
我看到了，感谢反馈。

从复现问题之后的富文本的html代码中看来，导致这一问题的原因可能是设置字号时，使用`<font size="7">`这种形式的原因。但是目前编辑器仍然采用了浏览器自带的`document.execCommand`才导致的这一问题，因此近期不好修复。

这个问题先open吧，我回头再仔细调研一下，fixed之后给你回复。

**Comment by wangfupeng1988** [comment]
这一怪异问题，这一版本先不考虑解决了，等待下一次大版本升级，我再考虑解决这一问题吧。请谅解
