### ISSUE TITLE
字号设置问题

### ISSUE THREAD

**Issue by yeyunzhixian** [wangfupeng1988/wangEditor#292]
没有输入之前，设置字体大小不起作用，必须通过选中文字才能设置字号，而且没有显示当前选择的字号大小，有点不太方便

**Comment by wangfupeng1988** [comment]
> 必须通过选中文字才能设置字号，而且没有显示当前选择的字号大小 

你说的问题我清楚，不过2.x版本的编辑器不会修复这个问题。我计划下一次大版本升级的时候，再去完善这些易用性问题。

**Comment by wangfupeng1988** [comment]
暂时关闭，有疑问再继续留言
