### ISSUE TITLE
angularjs 指令绑定Tip宽度的问题

### ISSUE THREAD

**Issue by kent124454731** [wangfupeng1988/wangEditor#293]
![image](https://cloud.githubusercontent.com/assets/8786136/15852150/ba912d68-2cd2-11e6-93a5-930ba400ed0b.png)

js直接放在body下面没有Tip的问题，但会有重复加载js的问题

将js提出到外面就不会有重复加载的问题，但Tip的宽度计算会有问题，初始宽度为0+5px

所以我在指令中只能先删除菜单，再重新渲染一遍菜单，这样Tip的宽度会重新计算。

希望大神能提供更优雅的解决办法 *^ο^*

**Comment by wangfupeng1988** [comment]
第一，你应该去找找为何『js放在body下面就会出现重复加载』的问题，重复加载和js放在哪里没有任何关系的。

第二，tip宽度为`0+5px`最根本的原因就在于body还未被渲染呢，就开始渲染编辑器菜单了，才会这样的。你去看看你的代码中，是否是等待body渲染完了之后又渲染的编辑器。

**Comment by wangfupeng1988** [comment]
暂时关闭，有疑问再继续留言
