### ISSUE TITLE
将富文本回写页面进行二次编辑

### ISSUE THREAD

**Issue by mobilesite** [wangfupeng1988/wangEditor#294]
有一个需求，需要在把富文本编辑器的内容提交数据库之后，把数据库中刚刚提交的富文本回写到页面中，以便于在此基础上进行再次的修改和编辑，请问该如下解决？另外，在使用过程中发现编辑富文本时会自动插入一些`<p>`和`<br>`标签，具体不太清楚什么情况下会插入，如何去除掉它们？

**Comment by wangfupeng1988** [comment]
>  把数据库中刚刚提交的富文本回写到页面中，以便于在此基础上进行再次的修改和编辑，请问该如下解决？

这个问题不就是对编辑器进行赋值吗，看看这里 http://www.kancloud.cn/wangfupeng/wangeditor2/113968

> 另外，在使用过程中发现编辑富文本时会自动插入一些<p>和<br>标签，具体不太清楚什么情况下会插入，如何去除掉它们？

首先，这些标签存在即有用；其次，我想知道你为何要删掉它们，带着这些标签有啥问题？

**Comment by mobilesite** [comment]
非常感谢回复！问题1是因为我在同一页面中有多个编辑器实例，不好用JS的方式初始化赋值，而想在VM模板中赋值。如果用<div id="div1"><p>要初始化的html内容...</p></div>这种方式赋值，则得到的结果是把富文本片段当作纯文本显示到了编辑器窗口（类似于被<pre>标签包裹的效果），而非所需要的作为p标签下的HTML节点。问题2是因为不想输出多余的标签到使用富文本数据的界面中，因为这些用富文本数据所用在的界面不在我们的掌控之下，输出多余的标签有可能会导致这些界面样式上的问题。

**Comment by wangfupeng1988** [comment]
> 同一页面中有多个编辑器实例，不好用JS的方式初始化赋值

多个编辑器实例为何就不能用js赋值？

> 如果用帮助文档中的HTML初始化方式赋值，则得到的结果是把富文本片段当作纯文本显示到了编辑器窗口（类似于被<pre>标签包裹的效果）

这个问题我没有发现，例如 https://github.com/wangfupeng1988/wangEditor/blob/master/test/index.html#L22 这里这么写。你说的这个问题如果你那里确实存在，把复现方法告诉我，最好做一个demo（直接复现问题）发给我

> 问题2是因为不想输出多余的标签到使用富文本数据的界面中

编辑器中所谓的『多余的标签』就是最后可能会有一个`<p><br></p>`，这个你用正则匹配去掉就是了，其他的再有，你可以继续反馈给我。

**Comment by wangfupeng1988** [comment]
暂时关闭，有疑问再继续留言
