### ISSUE TITLE
编辑器大小的问题

### ISSUE THREAD

**Issue by niget** [wangfupeng1988/wangEditor#295]
请问,编辑器可以实现占满父级div的功能吗?
因为在使用的过程中,可能面对不同的分辨率,而使用百分比设置编辑器的高度总是失败,如果不占满的话,页面会不美观,所以希望编辑器可以实现这个功能

**Comment by wangfupeng1988** [comment]
高度自动适应父元素，暂时不行。

这个需求目前提出来的用户不多，目前是需求稳定期，不会做一些非紧急的功能。像这些增加易用性的功能，很多我都计划在下一次大版本更新（至少半年之后）

**Comment by wangfupeng1988** [comment]
暂时关闭，有疑问再继续留言
