### ISSUE TITLE
实时追踪光标问题

### ISSUE THREAD

**Issue by wsmeichao** [wangfupeng1988/wangEditor#296]
在这遇到这样的一个问题：就是类似的富文本编辑器，当我聚焦在可编辑范围内时，焦点实时变更，插入图片位置没问题，但是当我失去焦点时(移动端还有在软键盘上点击完成同样)，选择插入图片，不会插入到上次光标停留的位置，我看来下大神你的代码，好像是要各种保存选区，然后恢复选区这样的，具体操作有点乱，还望大神有空帮忙解答下

**Comment by wangfupeng1988** [comment]
> 好像是要各种保存选区，然后恢复选区这样的，具体操作有点乱 

这块确实是这样的，大体的意思是：第一步，你鼠标或者手指focus了编辑器，此时要将`选区`保存起来；第二步，你blur了编辑器；第三步，你执行命令（如插入一个图片），首先要将之前保存的`选区`恢复过来，然后在执行插入。

如果你要对编辑器做一些开发，参加这里 http://www.kancloud.cn/wangfupeng/wangeditor2/115831  
如果你要自己做一些代码，就需要你去查js的`selection`和`range`相关的API了

**Comment by wangfupeng1988** [comment]
暂时关闭，有疑问再继续留言
