### ISSUE TITLE
与编辑器同一页面的其他图片上传功能是否可以直接调用编辑器的上传图片功能?

### ISSUE THREAD

**Issue by bidibao** [wangfupeng1988/wangEditor#297]
与编辑器同一页面的其他图片上传功能是否可以直接调用编辑器的上传图片功能?现在是另外写一个上传，感觉不如编辑器这个xhr好用。是否可以直接在其他地方调用这个上传。我已经处理好编辑器图片上传对应的后端，并使用正常

**Comment by wangfupeng1988** [comment]
记得之前回答过这个问题，在issues中找了半天没找到，就再说一遍吧。

**编辑器的上传功能仅供编辑器用，不对外开放**，原因如下：

编辑器的核心功能就是富文本编辑，上传图片是富文本编辑器这个整体功能的一个分支功能，因此上传图片不是编辑器的核心功能——说白了，你会因为一个编辑器上传图片功能做的好（其他功能不怎么样），而去用吗？

另外，如果要将上传功能开放出去，你觉得当前这些配置够用吗？你看看plupload这些插件功能多强大。一旦开放出去带来的结果是什么？——用户各种需求、对编辑器有用的没用的、纷纷提出来，你改还是不改？

**Comment by wangfupeng1988** [comment]
暂时关闭，有疑问再继续留言
