### ISSUE TITLE
超链接里不输入http:// 的话 会自动在连接上加当前的域名

### ISSUE THREAD

**Issue by dongtc** [wangfupeng1988/wangEditor#298]
demo里点击链接，链接地址里输入www.baidu.com，确定后，点这个链接，跳的是http://wangeditor.github.io/www.baidu.com/
这个地址，
输入http://的话 就不会添加当前域名

**Comment by wangfupeng1988** [comment]
插入链接肯定是要插入一个完整的链接地址啊，很显然 `www.baidu.com` 不算是一个完整的地址，因此就当做一个相对路径来判断了。

**Comment by dongtc** [comment]
这里是不是可以优化下呢，用户一般不会知道输入http://啊

**Comment by wangfupeng1988** [comment]
上次回复你的时候，我也考虑过这个优化的问题。但是没有一个很合理的解决方案。

直接在用户输入的网址前面加上`http://` ？貌似不合适吧？

**Comment by dongtc** [comment]
默认链接的input的value为‘http://’ 不挺好吗

**Comment by wangfupeng1988** [comment]
> 默认链接的input的value为‘http://’ 

恩，现在暂时这么处理吧，修复之后我给你回复

**Comment by wangfupeng1988** [comment]
已修复，可去官网demo验证，下载最新版本 https://github.com/wangfupeng1988/wangEditor/releases 更新js即可
