### ISSUE TITLE
字体样式不起作用

### ISSUE THREAD

**Issue by xubowenjx** [wangfupeng1988/wangEditor#3]
下载了源码中的demo,所有的字体大小、颜色等等都没用。
应该不是我的原因吧，因为我去项目给的demo地址看也是无法改变字体样式的。

**Comment by wangfupeng1988** [comment]
你是用的哪个浏览器？我检查着没啥问题。最好有个截图什么的

**Comment by xubowenjx** [comment]
很奇怪。我叫其他同事去demo地址测试，只有我和另外两人的360、chrome都不行。其他人所有都行的。
似乎还是电脑的问题。

**Comment by wangfupeng1988** [comment]
你可以在github上把源码下载下来，然后在自己机器上发布一个测试环境运行一下。看看是不是也这样。或者你如果方便的话，我可以远程帮你看看。在qq群里（164999061）找我就行。

**Comment by xubowenjx** [comment]
谢谢了。我自己电脑上不行，换在服务器上就没什么问题。只能说是个人环境exception吧。

**Comment by wangfupeng1988** [comment]
不客气，感谢对wangEditor的关注，有问题可以到qq群（164999061）里讨论

**Comment by keven9** [comment]
chrome某些版本中font-family对中文字体的识别有问题:
font-family: '微软雅黑'  //不生效，
font-family: 'Microsoft Yahei'  //没问题

建议editor里的中文字体名称都换成相应的英文名称
