### ISSUE TITLE
本地上传图片(不跨域) 路径插入错误

### ISSUE THREAD

**Issue by ChenQiWen** [wangfupeng1988/wangEditor#30]
本地上传图片图片是插入进去了 但是插入的路径不对，把upload.ashx 文件里的代码插了进去。
![1](https://cloud.githubusercontent.com/assets/5643252/9625617/000fdce2-518a-11e5-8236-1d40758fbbf2.png)
![2](https://cloud.githubusercontent.com/assets/5643252/9625620/09d3da76-518a-11e5-9ce2-c57296fead98.png)
![3](https://cloud.githubusercontent.com/assets/5643252/9625623/0e3eb73e-518a-11e5-9ad9-7fced6ef4ef8.png)

**Comment by wangfupeng1988** [comment]
你的最后一张截图中，img的src的值，就是要插入的值，也就是服务器返回的值，对吧？
本来服务器应该返回上传图片的url，我不知道你为何返回了整个代码文件。

我不知道你运行的时候，有没有设置断点跟踪后台程序，你可以去试试，我觉得你的后台程序（或者环境）有问题。

**Comment by wangfupeng1988** [comment]
1. 无论如何你要会使用plupload上传文件，这个只能靠自己，文档中也给出了学习链接；
2. 在此基础上，根据文档的配置，一步一步操作，肯定没有问题；

**Comment by wangfupeng1988** [comment]
配置文件上传：http://www.wangeditor.com/wangEditor/docs/index.html#upload-img-no-cross-domain
配置跨域文件上传：http://www.wangeditor.com/wangEditor/docs/index.html#upload-img-cross-domain
