### ISSUE TITLE
请问如何把编辑器中的换行符由<p>切换为<br>？

### ISSUE THREAD

**Issue by RitterHou** [wangfupeng1988/wangEditor#300]
希望可以自定义换行符，但是不知道在哪里修改才可以，请问需要怎么操作呢？

**Comment by wangfupeng1988** [comment]
这个不好改，而且我也不建议你改。

因为`<p>`本来就是段落的意思，换行了就是重起一个段落，段落内的换行，根据容器的宽度自动换行。

有人也提过同样的问题，也没有解决。他的原因是由于`<p>`之间的间距太大，想通过`<br>`换行来缩小行间距，但是间距的问题应该是css来处理的，而不是html处理的。

**Comment by yaoxiaoqi** [comment]
可以把所有的p标签都换成div吗

**Comment by yuandalu** [comment]
> 这个不好改，而且我也不建议你改。
> 
> 因为`<p>`本来就是段落的意思，换行了就是重起一个段落，段落内的换行，根据容器的宽度自动换行。
> 
> 有人也提过同样的问题，也没有解决。他的原因是由于`<p>`之间的间距太大，想通过`<br>`换行来缩小行间距，但是间距的问题应该是css来处理的，而不是html处理的。

现在的 行间距没问题，但是p段落间距 比行间距大，看了下 css写死了panding 15 这个能在设置中开放一下 允许设置么
