### ISSUE TITLE
内容初始化时如果内容含有<>的转义字符依然会被当成标签处理

### ISSUE THREAD

**Issue by haha214** [wangfupeng1988/wangEditor#301]
如题，初始化的时候如果内容中有标签即使使用了转义字符，仍然会被处理成标签
![](http://chuantu.biz/t5/10/1466077017x3738746535.png)
![](http://chuantu.biz/t5/10/1466077291x3738746535.jpg)
![](http://chuantu.biz/t5/10/1466077374x3738746535.jpg)
如果只想让他安安静静的显示为纯文字<script>alert("hello");</script>该如何处理

**Comment by wangfupeng1988** [comment]
图片咋显示不出来了。。。

**Comment by haha214** [comment]
额，能显示呀。。。我再回一次图片

**Comment by haha214** [comment]
![](http://img.hoop8.com/1606/153992920853.png)
![](http://img.hoop8.com/1606/031992920853.jpg)
![](http://img.hoop8.com/1606/205992920853.jpg)

**Comment by wangfupeng1988** [comment]
我周末一起看一下吧，这几天比较忙，有点私人的事儿。

**Comment by haha214** [comment]
麻烦您了

**Comment by wangfupeng1988** [comment]
> 初始化的时候如果内容中有标签即使使用了转义字符，仍然会被处理成标签

这个问题我验证了，我这里没有复现。下面说说我的步骤：
第一，html的代码是（即创建编辑器所使用的`<div>`）`<div id="editor-trigger"><p>请输入内容</p><p>&lt;script&gt;&lt;/script&gt;</p></div>`，然后创建编辑器。
第二，编辑器运行之后，显示的默认内容是
```
请输入内容
<script></script>
```
第三，使用编辑器的『查看源代码』菜单，查看源代码是：
```
<p>请输入内容</p><p>&lt;script&gt;&lt;/script&gt;</p><p><br></p>
```
第四，使用js打印编辑器的html内容，即`editor.$txt.html()`，得到的结果是`"<p>请输入内容</p><p>&lt;script&gt;&lt;/script&gt;</p><p><br></p>"`

完全没有问题。

-----

我很好奇，你截图中alert出来的『hello』，是用编辑器的什么API获取的？

**Comment by haha214** [comment]
<body>
        <div class="wangEditor-pc-container" >
            <textarea id="textareaPC">
                <p>请输入内容&lt;script&gt;alert("hello");&lt;/script&gt;</p>
            </textarea>
        </div>
  </body>
 <script>
                var editor;
                wangEditor.config.printLog = false;
                editor = new wangEditor("textareaPC");
                editor.config.menus = [
                'fontfamily',
                'fontsize',
                'bold',
                'underline',
                'italic',
                'strikethrough',
                'eraser',
                'forecolor',
                'bgcolor',
                '|',
                'orderlist',
                'alignleft',
                'aligncenter',
                'alignright',
                '|',
                'link',
                'emotion',
                'undo',
                'redo',
                ];
                editor.create();
        </script>
只用了create，我是用的textarea标签，难道可能因为它？

**Comment by haha214** [comment]
`<body>
        <div class="wangEditor-pc-container" >
            <textarea id="textareaPC">
                <p>请输入内容&lt;script&gt;alert("hello");&lt;/script&gt;</p>
            </textarea>
        </div>
    </body>`
` <script>
                var editor;
                wangEditor.config.printLog = false;
                editor = new wangEditor("textareaPC");
                editor.create();
        </script>`
只用了create创建一下，不过我用的是textarea标签，难道会是这个原因吗...

**Comment by wangfupeng1988** [comment]
使用`textarea`的情况我倒是上次没试过，我回头再试试哈

**Comment by wangfupeng1988** [comment]
你能通过js对编辑器赋值吗？例如
```
editor.create();
editor.$txt.html('<p>&lt;script&gt;&lt;/script&gt;123123</p>');
```

**Comment by yChainsan** [comment]
![11111](https://cloud.githubusercontent.com/assets/13290888/16381085/5e2bbdfa-3cad-11e6-88c5-a78888eeba63.png)
图片上传失败，使用textarea方式可以赋值

**Comment by yChainsan** [comment]
还有PHP代码的开始符<?php在初始化时直接被注释掉了，
原内容
<p>测试wangEditor</p><pre style="max-width:100%;overflow-x:auto;"><code class="php hljs" codemark="1"><span class="hljs-meta">&lt;?php</span>
    $a = <span class="hljs-string">'abc'</span>;
    tryTest($a);
<span class="hljs-meta">?&gt;</span></code></pre><p>test a content with code.</p>

初始化后：
<p></p><p>测试wangEditor</p><pre style="max-width:100%;overflow-x:auto;"><code class="php hljs" codemark="1"><span class="hljs-meta">
    $a = <span class="hljs-string">'abc'</span>;
    tryTest($a);
<span class="hljs-meta">?&gt;</span></span></code></pre><p>test a content with code.</p>

**Comment by haha214** [comment]
用js赋值的方式`editor.$txt.html('<p>&lt;script&gt;&lt;/script&gt;123123</p>');`可以解决这个问题~

**Comment by yChainsan** [comment]
关于包含代码的内容初始化问题我写了个demo，麻烦老师看下。[https://github.com/yChainsan/oew/blob/master/wangEditor-2.1.13_%E7%BC%96%E8%BE%91%E5%90%AB%E4%BB%A3%E7%A0%81%E5%86%85%E5%AE%B9%E7%9A%84%E6%A0%87%E7%AD%BE%E9%97%AE%E9%A2%98.rar](url)

**Comment by wangfupeng1988** [comment]
@yChainsan 你给出的链接打不开。上面都说了

> 用js赋值的方式editor.$txt.html('<p>&lt;script&gt;&lt;/script&gt;123123</p>');可以解决这个问题~

你还有什么疑问，最好直接详细的描述出来，比扒代码效率要高

**Comment by yChainsan** [comment]
editor.$txt.html();这种方式我试过，也不行。使用textarea问题比较多。上面的链接直接点击打不开，不知道什么问题，麻烦复制一下，demo可以下载的，自己测试过。希望能解决掉问题，谢谢
https://github.com/yChainsan/oew/blob/master/wangEditor-2.1.13_issue_301.rar

**Comment by wangfupeng1988** [comment]
有问题一个一个来，或者把每个问题都提交成一个issue。先说第一个：

> editor.$txt.html();这种方式我试过，也不行

使用这种方式不行，到底怎么不行？在什么情况下，有啥报错？我看你给我的附件中，代码中，没找到这种用法呀？

**Comment by wangfupeng1988** [comment]
暂时关闭，有问题继续在下面留言
