### ISSUE TITLE
如何获取富文本里的每个字符相关属性

### ISSUE THREAD

**Issue by szcountryboy** [wangfupeng1988/wangEditor#303]
在富文本框输入的文字,如何获取每个字的属性(字体名称,字体大小,字体颜色,加粗)

目前手工使用压栈的方式,感觉性能不是很好,是否有提供更好的办法?

谢谢

**Comment by wangfupeng1988** [comment]
> 如何获取每个字的属性(字体名称,字体大小,字体颜色,加粗)

不明白为何要获取**每一个字**的这些属性，从没见过这样的需求，能否举个例子来说明。我明白了，也好给你出最佳的主义。

-------

另外，关于获取你说的『属性』（其实我理解的就是css样式），例如要获取编辑器编辑区域第一个`<p>`元素的样式，可以使用`window.getComputedStyle(editor.$txt.find('p')[0])`来获取，具体你可以试试。

至于你说的**每一个字**，我就不明白了，最好举例说明

**Comment by szcountryboy** [comment]
非常感谢解答,需求是这样的
一个富文本框,用户输入,可以设置单个字的各种样式(颜色\大小\字体),然后web界面要在canvas上根据富文本的显示效果,在canvas上显示出来(颜色\大小\字体),
比如:富文本里面  欢迎来到这
欢   红色  宋体,10
迎   绿色  楷体,12
来   蓝色  黑体,8
到   绿色  宋体,20
这   红色  黑体,10

如果不使用富文本,单独的textarea可以实现分字,但界面上无法显示效果(颜色等),使用此富文本编辑器,目前是通过正则匹配<span>标记来获取每个字的属性,所以咨询下看是否有更加高效的方法

**Comment by wangfupeng1988** [comment]
第一，定义一个数组 `var data = []`

第二，获取编辑器区域的DOM `var $content = editor.$txt` ，然后针对 `$txt.chidlren()`子节点、以及子节点的子节点，这棵树，进行遍历。

第三，接第二步说，每每遍历到最`TextNode`，通过`window.getComputedStyle`获取它的属性，然后将每个字、属性，都添加到一开始的数组中，例如`data.push({val: '欢', family: '宋体', size: 10})`等（如果这个`TextNode`包含多个字，就循环挨个push进去）

第四，将以上所说的过程，封装成一个函数，然后做一个编辑器的插件，参见 http://www.kancloud.cn/wangfupeng/wangeditor2/115837
