### ISSUE TITLE
editor在iframe里的时候，回车失效了

### ISSUE THREAD

**Issue by anguskwan** [wangfupeng1988/wangEditor#305]
但是，在bindEnterForDiv的

$txt.on('keydown keyup', function (e) {
            if (e.keyCode !== 13) {
                return;
            }

下面加个alert（）；之后回车的内容加进去了，有点费解。求助。

**Comment by wangfupeng1988** [comment]
我周末一起看看这个问题

**Comment by anguskwan** [comment]
多谢 @wangfupeng1988

**Comment by wangfupeng1988** [comment]
首先，这种情况下，回车是没有问题的

```html
<!--./index.html中创建了编辑器，这里仅仅用 iframe 引用一下-->
<iframe src="./index.html" width="100%" height="500"></iframe>
```

**Comment by anguskwan** [comment]
我是放在discuz的插件里的，看来是和其他事件冲突了。。我再定位一下，多谢！

**Comment by wangfupeng1988** [comment]
遇到问题的时候，现自己做一个简单的demo验证一下。在项目环境中，影响因素那么多，不把问题分离解决，不容易找到原因。

**Comment by anguskwan** [comment]
嗯嗯，认同！ 我仔细看过demo，给editor增加了个上传视频、音频的功能，后来才发现有回车这个问题，通过chrome的开发工具跟了下event listner没找到问题，，只好来麻烦大神了，哈哈
