### ISSUE TITLE
项目中使用jquery step插件后，无法使用编辑器

### ISSUE THREAD

**Issue by geekpi** [wangfupeng1988/wangEditor#309]
浏览器: Chrome 51
jquery step插件地址：http://www.jquery-steps.com/GettingStarted
wangEditor版本: 2.1.13

默认情况下直接使用wangEditor没有问题，但是用上述jQuery插件之后，可以正常初始化，但是点击任何编辑选项都没有反应，作者能否修复这个兼容性？谢谢

**Comment by wangfupeng1988** [comment]
你按照这两个demo再做一下试试，有问题再回复。
https://github.com/wangfupeng1988/wangEditor/blob/master/test/step-test/test1.html
https://github.com/wangfupeng1988/wangEditor/blob/master/test/step-test/test2.html

**Comment by geekpi** [comment]
目前已经可以，需要在最新版的jquery step加入了onInit事件，在这里面初始化editor就行

**Comment by wangfupeng1988** [comment]
你说的`onInit `应该是个每一步加载之后的回调函数吧？我当时也想找这个函数，但是文档中没找到。因此不得已才在`test2.html`中做了如下处理：

```

        var content = '';
        content += '<div id="editor-container" class="container"><div id="editor-trigger"><p>请输入内容</p></div></div>';
        // 下一行的 create() 其实应该在回调函数中做
        content += '<script>var editor = new wangEditor("editor-trigger");editor.create();<\/script>';
        wizard.steps("add", {
            title: "wangEditor", 
            content: content
        });
```

**Comment by geekpi** [comment]
在此：https://github.com/rstaib/jquery-steps/wiki/Settings#events
，wizard初始化完成之后会调用

在 2016年6月27日 下午1:11，王福朋 <notifications@github.com>写道：

**Comment by wangfupeng1988** [comment]
好，解决了就OK

**Comment by KeKe-Li** [comment]
有个问题请教下啊，最近载用这个jquery-steps插件做一个登录注册的这样类似的例子，但是做好了无法触发！
