### ISSUE TITLE
保存数据后的表格样式问题！

### ISSUE THREAD

**Issue by linjiaju8** [wangfupeng1988/wangEditor#310]
我编辑一个表格保存后边框会消失，原因是表格样式依赖于编辑器的样式，我通过editor.$txt.html()拿到的编辑器内容表格是没有任何样式的。所以出现在有编辑器编辑内容时能看到表格的样式，发布编辑内容后表格边框看不到了。

**Comment by wangfupeng1988** [comment]
是的，编辑器给出的html代码是没有任何样式的，纯html代码。这样做，就是为了让用户来自定义样式。因此，你需要在显示页面自己去定义table的样式，参见 http://www.kancloud.cn/wangfupeng/wangeditor2/113988

**Comment by wangfupeng1988** [comment]
暂时不关闭，有问题可继续在下面留言

**Comment by linjiaju8** [comment]
好的清楚了，谢谢
