### ISSUE TITLE
从word复制文本有问题

### ISSUE THREAD

**Issue by Ttou** [wangfupeng1988/wangEditor#311]
在win7上从word2013中复制文本粘贴到编辑器中，编辑器的中内容头部会被插入三条html字段：
`<link href="file:///C:\Users\hizaki\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<link href="file:///C:\Users\hizaki\AppData\Local\Temp\msohtmlclip1\01\clip_themedata.thmx">
<link href="file:///C:\Users\hizaki\AppData\Local\Temp\msohtmlclip1\01\clip_colorschememapping.xml">`

**Comment by wangfupeng1988** [comment]
我告诉你个方法，你帮我试一下吧（我这里没有word2003），看是否可行。

这里 https://github.com/wangfupeng1988/wangEditor/blob/master/dist/js/wangEditor.js#L2466 的数组中，将`link`加上。即
```
                // 忽略的标签
                if (['meta', 'style', 'script', 'object', 'form', 'iframe', 'hr'].indexOf(nodeName) >= 0) {
                    return;
                }
```
改成
```
                // 忽略的标签
                if (['meta', 'style', 'script', 'object', 'form', 'iframe', 'hr', 'link'].indexOf(nodeName) >= 0) {
                    return;
                }
```

试一下然后在此回复我吧，多谢啦

**Comment by Ttou** [comment]
改了之后的确可以了

**Comment by wangfupeng1988** [comment]
好，你现这么用着。我下次小版本更新的时候，修复过来，到时候你直接覆盖新版本即可。
