### ISSUE TITLE
源码情况下无法获取编辑器内容

### ISSUE THREAD

**Issue by vioao** [wangfupeng1988/wangEditor#312]
如题,在源码模式下使用 editor.$txt.html() 和 editor.$txt.text() 都无法获取当前的编辑器内容。

**Comment by wangfupeng1988** [comment]
好，我周末一起看看这个问题吧。到时候在此回复你

**Comment by wangfupeng1988** [comment]
我在自己的demo中没有复现。如果你这个问题是在项目环境下出现的，请先忽略项目环境，做一个基本的demo来复现问题，然后将复现步骤反馈给我。

注意，复现步骤尽量详细详细再详细。

**Comment by vioao** [comment]
有一个情况要确认，就是原本编辑器中有内容，然后切换到源码模式编辑。之后使用 editor.$txt.html() 和 editor.$txt.text() 的确是能获取到内容，但是获取到的内容是编辑前的内容。

**Comment by vioao** [comment]
在demo(http://wangeditor.github.io/) 页面就可以重现问题
重现步骤如下:
1、切换到源码编辑模式,输入 ‘123’ 
在控制台输入 
`jQuery('#divDemo').html()`
得到
`<p>欢迎使用<b>wangEditor 富文本编辑器</b>，请输入内容...</p><p><br></p>`

此时获取不到刚输入的内容 123

2、切换只普通编辑模式
在控制台输入 
`jQuery('#divDemo').html()`
得到
`<p>欢迎使用<b>wangEditor 富文本编辑器</b>，请输入内容...</p><p><br></p>`
`123`

此时才能获取到刚输入的内容

**Comment by wangfupeng1988** [comment]
那当然，富文本编辑器是用来编辑内容的，不是编辑源码的，当然是编辑完了源码之后，回到内容区域再去替换内容。

再者，要是按你说的每输入一个源码的字符，就要生效，这是有问题的。例如当前源码是`<p>123</p>`，你想要在源码状态下修改成`<p>123<b>45</b></p>`。如果等你修改完了，进入普通模式才生效，这样没问题。但是当你修改的内容刚刚是`<p>123<b</p>`的时候，这时候将这段html代码生效，不就有错误了吗？

**Comment by vioao** [comment]
那看来只能做个限制了。有办法获取当前选择的菜单项不？看文档没找到对应的说明。

**Comment by wangfupeng1988** [comment]
> 有办法获取当前选择的菜单项不

啥意思，没明白？

**Comment by wangfupeng1988** [comment]
暂时关闭，有疑问继续在下面留言即可
