### ISSUE TITLE
按照文档集成到angular项目中的时候报错

### ISSUE THREAD

**Issue by nouh** [wangfupeng1988/wangEditor#314]
一直会报: `Cannot read property 'menus' of undefined wangEditor` 错误

**Comment by wangfupeng1988** [comment]
> 一直会报: Cannot read property 'menus' of undefined wangEditor 错误

这个错误，一般就是在DOM未加载完成之前，就支行了`editor.create()`

**Comment by nouh** [comment]
谢谢, 另外问下wangEditor-mobile 可以和angular比较好的集成么

**Comment by wangfupeng1988** [comment]
mobile版目前还是没有维护，原因可以看看这里 http://www.kancloud.cn/wangfupeng/wangeditor2/139064
