### ISSUE TITLE
图片上传怎么去掉网络图片选项

### ISSUE THREAD

**Issue by 799535610** [wangfupeng1988/wangEditor#317]
图片上传怎么去掉网络图片选项， 只能上传本地图片

**Comment by wangfupeng1988** [comment]
目前还不支持这个配置，我下次升级增加上这个配置吧。加上之后在此回复你。

**Comment by wangfupeng1988** [comment]
下载`v2.1.14`版本，https://github.com/wangfupeng1988/wangEditor/releases/tag/v2.1.14 

然后在`editor.create()`之前加上`editor.config.hideLinkImg = true;`即可
