### ISSUE TITLE
[bug]行距只能选择一段一段设置，如果同时选择多段，无法设置行距

### ISSUE THREAD

**Issue by jacobcyl** [wangfupeng1988/wangEditor#318]
行距只能选择一段一段设置，如果同时选择多段，无法设置行距。

**Comment by wangfupeng1988** [comment]
好的，我周末看看这个问题

**Comment by wangfupeng1988** [comment]
看了一下，是有这个问题，而且在目前的代码框架中，不太好解决。因为浏览器本身的`document.execCommand`不支持设置lineheight，因此无法根据选区自动设置行高，只能设置段落的css样式，才导致了目前这种情况。

这个问题计划会在下次大版本升级的时候解决。
