### ISSUE TITLE
图片之后粘贴文字问题，导致图片删不掉

### ISSUE THREAD

**Issue by xcheese** [wangfupeng1988/wangEditor#319]
![image](https://cloud.githubusercontent.com/assets/9137396/16608012/f589e37a-4379-11e6-9020-cec4edfea7c1.png)

如图，操作图片上传之后，粘贴了一段文字，进入到了图片所在的p标签中，导致在文字之前按退格键无法删除图片（windows10 chrome）

**Comment by wangfupeng1988** [comment]
我在mac下的chrome中，复现你这个场景，源代码如下
```
<p><img style="max-width:100%;" src="http://www.cnblogs.com/images/logo_small.gif" class="">欢迎使用wangEditor 富文本编辑器，请输入内容...</p><p><br></p>
```
这样是可以通过退格键删除图片的。

另外，删除图片还可以在点击图片时，图片下方弹出的toolbar中删除。

最后，你说的这个bug，在官网demo能复现吗？
