### ISSUE TITLE
head插件弹出窗定位bug

### ISSUE THREAD

**Issue by xingkongs** [wangfupeng1988/wangEditor#320]
head插件弹出窗**定位**bug
设置吸顶50、 max-height值比较大 如20000px ，当文字超出一定高度的时候 ，head弹窗定位出现变化top 变为100px；其他弹窗如视频、链接定位良好，感觉应全改成视频弹窗这种定位

**Comment by wangfupeng1988** [comment]
这个`head插件`是个什么插件，我没用过，能否提供个地址。

另外，最好做一个简单的demo页，能让我一眼就看到这个bug是什么样子的。

**Comment by xingkongs** [comment]
就是默认的 可以改h2、h3标签的功能

**Comment by wangfupeng1988** [comment]
能否提供个最简单的demo页的代码给我（最最简单、且能复现问题的demo页）？

另外注意，不要拿那些特别极端的情况举例子（max-height值比较大 如20000px），就拿实际常用的。

**Comment by wangfupeng1988** [comment]
暂时关闭，有疑问继续在下面留言即可

**Comment by wangfupeng1988** [comment]
暂时关闭，有疑问继续在下面留言即可
