### ISSUE TITLE
有个疑问，为什么默认的空值是<p><br></p>呢？

### ISSUE THREAD

**Issue by linjiaju8** [wangfupeng1988/wangEditor#322]
这不是什么大问题，只是我们测试还专门提了个bug给我说退格不能把空格换行清除，退格后又出来空格换行了，我试了不管怎么退格，$txt中的内容始终是`<p><br></p>`，这样做是处于什么原因？

**Comment by MiYogurt** [comment]
这样的默认空值感觉好尴尬呀，假如用户只是想提交一个高亮代码，不写内容，自动加上这个，留白太多，好难看呀。

通常用户习惯会是写完之后再按一个回车，求解，如何删除最后的几行空白行。

![image](https://cloud.githubusercontent.com/assets/10082395/16679956/2eaa372c-451e-11e6-912a-f2a4956d4d58.png)

**Comment by wangfupeng1988** [comment]
@linjiaju8 首先，`<p><br></p>`不是空格，是空行。编辑器是用于输入内容的，它无论怎么空，也得留个空行让用户输入吧。如果一个空行都没有了，用户怎么输入内容？

**Comment by wangfupeng1988** [comment]
@MiYogurt 

> 通常用户习惯会是写完之后再按一个回车

在高亮代码块中按回车，它永远都在代码快中回车，因此在插入代码块之后，紧接着在代码块下面插入空行。但高级浏览器下，只有一个空行，你说的『几个空行』，是否在IE低版本出现的？

想要删除，自己在提交的时候用正则替换一下就行了。再说了，不删除也没啥影响。

**Comment by MiYogurt** [comment]
几个空行，是因为习惯使然，通常写东西会在最后多留几行的空白，也就是多敲几下回车。

```
let reg=/\<p\>\<br\>\<p\>/g;

content.replace(reg,'');
```

是这样么？很少用正则，都快忘了。

**Comment by wangfupeng1988** [comment]
@MiYogurt 是不是你验证一下不就知道了？

**Comment by MiYogurt** [comment]
好吧，我承认我懒了。
应该是这个样子才对，replace 是纯函数。
```
let reg=/\<p\>\<br\>\<\/p\>/g;

content = content.replace(reg,'');
```

**Comment by 11003** [comment]
editor_description = editor_description  === `<p><br></p>` ? '' : editor_description
