### ISSUE TITLE
编辑器中加了表格之后，table的宽度和class都为空。如果用这个编辑器保存的内容，邮件发送出去之后，表格就无边框了

### ISSUE THREAD

**Issue by gs2009** [wangfupeng1988/wangEditor#323]
编辑器中加了表格之后，table的宽度和class都为空。如果用这个编辑器保存的内容，邮件发送出去之后，表格就无边框了
以下是表格源码：
```
<p>欢迎使用<b>wangEditor 富文本编辑器</b>，请输入内容.**..</p><table class=""><tbody>**<tr><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td></tr></tbody></table><p><br></p>
```

**Comment by wangfupeng1988** [comment]
以前有人提问过类似的问题，可以去关闭的issues中查找。

这里简单说一下吧。
编辑器输出的是最简单最纯净的html代码，不带任何样式。样式交给外面来控制，才能实现那种多主题、多皮肤的效果，而且不同风格的网站，需要的样式也是不一样的，因此编辑器不会去控制任何样式。

像你这种要把内容发布出来到邮件，你就需要自己写一些样式，其实也很简单。参见 http://www.kancloud.cn/wangfupeng/wangeditor2/113988
