### ISSUE TITLE
android webview空间里点击编辑器上传图片按钮没有反应

### ISSUE THREAD

**Issue by ItBeatles** [wangfupeng1988/wangEditor#324]
编辑器上的图片上传按钮在浏览器上能正常上传图片；可是在android 系统的webview控件里打开，点击图片上传图片没有任何反应

**Comment by wangfupeng1988** [comment]
目前编辑器还未完全支持移动端（移动端用户体验也较差），更别说hybrid里了，问题应该会更多一些。不过目前上不支持。
