### ISSUE TITLE
点击图片,出现图片bar,然后在对编辑器赋值以后,图片消失,bar却还在

### ISSUE THREAD

**Issue by niget** [wangfupeng1988/wangEditor#326]
在使用editor.$txt.html()对编辑器赋值以后,bar并不会自动消失,还需要在另单击下编辑器,bar才会消失,

希望赋值以后,编辑器的所有内容都能初始化,包括各种bar

**Comment by wangfupeng1988** [comment]
好，我周末看看这个问题，这个问题还是要修复一下的

**Comment by wangfupeng1988** [comment]
我具体看了一下，发现问题不大。

第一，使用`editor.$txt.html()`来操作内容的情况还是比较少的，你是第一个提出这个问题的用户。

第二，即便使用`editor.$txt.html()`操作内容，只要不是删除图片，toolbar不消失也无大碍。而删除图片都会一般再编辑器中删除。

第三，toolbar是插件机制实现的，插件调用外面简单，而外面想调用插件，就违反了一些设计原则，会导致代码很乱。

因此，这个暂时先不解决。

**Comment by wangfupeng1988** [comment]
暂时关闭，有疑问继续在下面留言即可
