### ISSUE TITLE
撤销问题，多个编辑器的时候，撤销会互相干扰

### ISSUE THREAD

**Issue by rajna** [wangfupeng1988/wangEditor#327]

**Comment by wangfupeng1988** [comment]
请给出详细描述，例如一共几个编辑器，销毁哪个，会影响哪个。
销毁操作是怎么执行的，关键代码是啥。

一再强调，拒绝『一句话问题』

**Comment by wangfupeng1988** [comment]
暂时关闭，有疑问继续在下面留言即可

**Comment by wangfupeng1988** [comment]
我在今天的测试过程中突然发现了你说的这个问题，已经修复。可明天下载`v2.1.16`版本验证
