### ISSUE TITLE
在webpack的使用中，字体文件会无法加载

### ISSUE THREAD

**Issue by zzbkszd** [wangfupeng1988/wangEditor#328]
使用npm 安装，并使用webpack进行打包，解析器为file-loader，结果报错如下：

ERROR in ./~/wangeditor/dist/css/fonts/icomoon.eot?-qdfu1s
Module parse failed: /Users/shizhida/Desktop/woodmarket/admin/woodmarket/src/main/resources/webroot/jsx/comp/node_modules/wangeditor/dist/css/fonts/icomoon.eot?-qdfu1s Unexpected token (1:1)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:1)

这个文件有问题？还是我用错了解析器？在官网文档中是不是可以添加一下对webpack使用的config文件相关配置？

**Comment by wangfupeng1988** [comment]
OK 我周末看一下这个问题

**Comment by wangfupeng1988** [comment]
上个周末有事儿忙去了，这周我一定抽时间看看，并将如何用webpack做写到文档中。

**Comment by wangfupeng1988** [comment]
问题已经解决，可先看这里 https://github.com/wangfupeng1988/wangEditor2-width-webpack

**Comment by loanniss** [comment]
怎么使用啊，下载下来的东西，都没有这个js啊！

**Comment by wangfupeng1988** [comment]
没有哪个js？
