### ISSUE TITLE
es6下引用报warning

### ISSUE THREAD

**Issue by cyuxlif** [wangfupeng1988/wangEditor#329]
![image](https://cloud.githubusercontent.com/assets/5780053/16790589/cb3d2756-48e9-11e6-9e60-779db9cfcf76.png)
![image](https://cloud.githubusercontent.com/assets/5780053/16790595/d698bcbe-48e9-11e6-9cf6-c7f68c1b6b94.png)

this.editor 可以打印出来

**Comment by wangfupeng1988** [comment]
我周末看一下，到时候在这里回复你

**Comment by cyuxlif** [comment]
搜了下资料 好像 es6不支持 动态加载

**Comment by zzbkszd** [comment]
同遇到此问题的路过，并没有影响使用所以没有在意……

**Comment by wangfupeng1988** [comment]
这个问题先不用纠结了，先这么用着吧。下次大版本升级我会直接使用es6和npm的方式来开发。
