### ISSUE TITLE
非常感谢作者。

### ISSUE THREAD

**Issue by imwangji** [wangfupeng1988/wangEditor#33]
本来我也打算自己写一个编辑器的。但是作者现在写出来的编辑器和我想象中的风格一样。代码也蛮工整。
我就拿走直接改了哈，不重复造轮子了。
哈哈。
表示感谢。
ps. 同年生人啊。 ：）

**Comment by wangfupeng1988** [comment]
可以。
不过建议你作为这个插件的用户，而不是改源码。如果改了源码，以后的更新你都没法用。
如果编辑器不能满足你的需求，你可以提出来给我。

改源码是一种最坏的选择

**Comment by beijishiqidu** [comment]
我也是在你的基础上做了一些样式的定制。不过后期你要是有新的版本升级的话，替换起来也不是难事。赞一个。

**Comment by wangfupeng1988** [comment]
ok
