### ISSUE TITLE
图片上传在有多个编辑器中的问题

### ISSUE THREAD

**Issue by jiangquanyi** [wangfupeng1988/wangEditor#330]
图片上传在有多个编辑器时，图片都添加到最后一个编辑器上，版本是wangEditor-2.1.14，

**Comment by wangfupeng1988** [comment]
我在本地demo中没发现这个问题，demo的源码 https://github.com/wangfupeng1988/wangEditor/blob/master/test/test-muti.html

不知道你是否看过文档中的这段话（http://www.kancloud.cn/wangfupeng/wangeditor2/137878）

> 下载源码并在本地运行demo，看看有没有问题（一般针对图片上传，需要服务端支持）
先别管项目环境，先自己做一个编辑器的demo，看是否正常。如果正常，将项目中的功能一步一步加到编辑器页面。边加边验证，看看哪一步导致的冲突。

如果你真的是再最最简单的demo也出现的这个问题，把代码直接发给我。如果是在复杂项目中出现了这个问题，请先确认问题范围。

**Comment by wangfupeng1988** [comment]
暂时关闭，有疑问继续在下面留言即可

**Comment by 876968680** [comment]
我也发现了同一个问题，就是在两个编辑器上传图片无论怎么上传都跑到第一个里面呢？不知道为什么，哭死了快
代码如下：ditor1.config.uploadImgFns.onload = function (resultText, xhr) {
                console.log("11111111111editer1");
                var resultText = JSON.parse(resultText);
       
                var originalName = editor1.uploadImgOriginalName || '';
                var html = '<img src="' + resultText.result + '" alt="' + originalName + '" style="max-width:100%;"/>';
                editor1.command(null, 'insertHtml', html);
            };

            editor1.config.hideLinkImg = true;
            editor1.$editorContainer.css('z-index', 20);
            editor1.create();

            var editor2 = new wangEditor('config_div2');
            editor2.config.uploadImgUrl = '/api/tembin/haishen/upload_img/';
            editor2.config.uploadImgFns.onload = function (resultText, xhr) {
                console.log("2222222222222editer2");
                var resultText = JSON.parse(resultText);
               
                var originalName = editor2.uploadImgOriginalName || '';
                var html = '<img src="' + resultText.result + '" alt="' + originalName + '" style="max-width:100%;"/>';
                editor2.command(null, 'insertHtml', html);
            };


            editor2.config.hideLinkImg = true;
            editor2.create();
            editor2.$editorContainer.css('z-index', 10);

**Comment by 876968680** [comment]
补充下  刚刚那个描述错了，是一个页面两个编辑器，上传第一个编辑器图片的时候，上传后图片跑到第二个编辑器里面。

**Comment by gxlfc** [comment]
我也出现了同样的问题，怀疑是editor.command中null参数的问题，改为element后仍不起作用
