### ISSUE TITLE
单页面应用已存在地图对象时，点击富文本地图报错

### ISSUE THREAD

**Issue by sungf** [wangfupeng1988/wangEditor#332]
单页面应用已存在地图对象时，点击富文本地图报错：Uncaught TypeError: Cannot read property 'fc' of undefined
再次点击一直显示加载中...
原因是加载先后顺序错误，加载地图对象即创建实例，此时地图页面标签还未显示
mapData.initMap();
dropPanel.show();
两行代码对调位置,即解决
dropPanel.show();
mapData.initMap();

不知道是不是这个原因，导致多个编辑器加载地图会出错...

**Comment by wangfupeng1988** [comment]
> 不知道是不是这个原因，导致多个编辑器加载地图会出错...

多编辑器同时使用地图，本身就有问题，这个一直未找打原因，所以我会在多编辑器使用地图的时候给出`console.error`提示，不知道你看到了没有。

另外，在SPA中，多次`create()`时，之前有人提出来过，会出现地图不能使用的bug，之前就解决了，不知道你是否用的最新版本。

----

你说的这两行代码顺序的问题，我先调整过来测试一下，如果没问题，就改过来。
```
dropPanel.show();
mapData.initMap();
```

事后会在此回复你。

**Comment by wangfupeng1988** [comment]
我刚才发现了你说的这个错误了 `Uncaught TypeError: Cannot read property 'fc' of undefined`

你反馈的代码顺序问题已经调整，并测试了没问题。你可以先这么自己手动改了用着，等待今晚或者明天的`v2.1.15`版本的更新即可。
