### ISSUE TITLE
要求从其他地方复制到编辑器的内容以10号字显示

### ISSUE THREAD

**Issue by 799535610** [wangfupeng1988/wangEditor#334]
我在`Txt.fn.bindPasteFilter`里`editor.command(e, 'insertHtml', resultHtml); ` 里直接加的  `editor.command(e, 'insertHtml', '<font size="1">'+resultHtml+'</font>');    `发现复制的内容有时并未被font包含,   大神还有其他好的处理方式吗

**Comment by 799535610** [comment]
加的font size="1"  上面没显示

**Comment by wangfupeng1988** [comment]
你这个需求太奇葩了吧，只有粘贴过来的显示10号字？还是所有的问题（包括打字的）都显示10号字？

对于这个需求，首先你要开启粘贴样式的过滤（http://www.kancloud.cn/wangfupeng/wangeditor2/113984）然后再对粘贴过来的内容进行处理。

注意，是对粘贴的内容进行处理，你光在外面包裹一层`<font size="1">`是没用的，你得对里面的内容进行处理。去试试吧

**Comment by 799535610** [comment]
只对粘贴过来的进行处理.  现在的处理方式是对粘贴的内容进行处理,  查找p, span等标签,  对设置了字体的进行处理

**Comment by wangfupeng1988** [comment]
对，目前只能是这么处理了。你这个需求比较个性，应该没有通用的配置支持
