### ISSUE TITLE
如何禁用同时上传多张图片

### ISSUE THREAD

**Issue by ZhuGongpu** [wangfupeng1988/wangEditor#335]
如题。

**Comment by ZhuGongpu** [comment]
源码中所有的`UploadFile`中都设置了`this.multiple = true;`，建议加入相关的API进行自定义。

**Comment by wangfupeng1988** [comment]
但是绝大部分情况应该是允许多张图片上传才对呀？你为何非得每次只上传一个图片？有啥特殊的场景？

**Comment by wangfupeng1988** [comment]
暂时关闭，有疑问继续在下面留言即可
