### ISSUE TITLE
代码高亮的时候想添加 C 语言应该在哪里修改？

### ISSUE THREAD

**Issue by RitterHou** [wangfupeng1988/wangEditor#336]

**Comment by wangfupeng1988** [comment]
编辑器借用的 https://highlightjs.org/ 的代码高亮功能，可以去看看如何扩展C语言，我觉得应该是可以扩展的。

**Comment by RitterHou** [comment]
那里只需要直接把class设置为 C 就可以了，我也可以直接修改源代码进行改正

我现在比较好奇的是那个下拉框中的参数需要怎么样才可以添加进我所需要的值？

**Comment by wangfupeng1988** [comment]
下拉框中的代码列表，是我通过`window.hljs.listLanguages`这个API获取的，你得查查如何扩展到这个API中。

**Comment by wangfupeng1988** [comment]
暂时关闭，有疑问继续在下面留言即可
