### ISSUE TITLE
当退格键 怎么获取当前光标所在的dom

### ISSUE THREAD

**Issue by weijer** [wangfupeng1988/wangEditor#338]
如题：当退格键 怎么获取当前光标所在的dom

**Comment by wangfupeng1988** [comment]
没自习看文档。

js监控退格键，然后使用 `var elem = editor.getRangeElem();` 即可获取， 参见  http://www.kancloud.cn/wangfupeng/wangeditor2/115831

**Comment by wangfupeng1988** [comment]
暂时关闭，有疑问继续在下面留言即可
