### ISSUE TITLE
Word中复制一段文本到编辑器中，后面会带上特殊字符

### ISSUE THREAD

**Issue by chen8ih** [wangfupeng1988/wangEditor#339]
您好，在使用wangEditor的过程中，觉得这款编辑器非常的清爽，所以我们在项目中都替换成这款编辑器了，目前遇到一个问题，就是每次从word中复制文本都会在编辑器后面带上几个特殊字符，感觉应该是word中的回车符或换行符导致的，请问有没有什么方法在粘贴的时候过滤掉这些特殊字符？

使用的时win7系统 chrome浏览器，版本 51.0.2704.103 m
word使用的是2013版的
wangEditor版本为2.1.11

在官网的编辑器中也会出现类似情况

**Comment by wangfupeng1988** [comment]
能否把word文档发给我（QQ邮箱即可），然后截图告诉我粘贴哪一段会出问题，我来试试

**Comment by chen8ih** [comment]
谢谢您的回复，已通过QQ邮箱发送给您了

**Comment by wangfupeng1988** [comment]
我收到了，但是再mac os下，打开word复制，粘贴到编辑器中（chrome浏览器）没问题。windows下，我回去再看看吧

**Comment by chen8ih** [comment]
好的，我是在window环境下操作的，mac环境下没有测试。

**Comment by WuWeiSen** [comment]
我也遇到了这个问题，是编码问题吗？

**Comment by wangfupeng1988** [comment]
很抱歉，平时使用mac，近期没找到windows下的测试环境，问题一直耽搁了。我怀疑可能是编码的问题。。。
