### ISSUE TITLE
编辑器的查看源码的弹出页面拖动超出弹出框口的范围

### ISSUE THREAD

**Issue by beijishiqidu** [wangfupeng1988/wangEditor#34]
![qq 20150907174117](https://cloud.githubusercontent.com/assets/14070935/9714000/ae065f46-5587-11e5-8449-a46af915359c.jpg)

如上图所示。

浏览器是google 44.0.2403.107 m
代码：图片上传的demo就可以重现这个问题。

**Comment by wangfupeng1988** [comment]
官网首页的demo是没有问题的。
你说的『图片上传的demo』是哪里？如何复现一下？

**Comment by beijishiqidu** [comment]
来源：http://pan.baidu.com/s/1mgiXxOW我在你百度云盘的共享中下载下来的。
复现步骤：
![qq 20150909100132](https://cloud.githubusercontent.com/assets/14070935/9751645/cb92d3c0-56d9-11e5-916e-c0db02f71115.jpg)
浏览器大家wangEditor-upload-img.html文件就能复现了。

**Comment by wangfupeng1988** [comment]
我下载了百度云盘里的代码，运行，但是没有复现这个问题。
你可以做一个静态demo，复现这个问题，然后发给我qq邮箱。
<img width="1058" alt="qq20150910-1 2x" src="https://cloud.githubusercontent.com/assets/9583120/9767262/ee8e447e-574f-11e5-9daa-a469670e5af9.png">

**Comment by wangfupeng1988** [comment]
提问者长时间不反馈，先把问题关闭，如有需要，再重新向我反馈。
