### ISSUE TITLE
火狐浏览器中，文本输入换行不了？

### ISSUE THREAD

**Issue by linvic** [wangfupeng1988/wangEditor#341]
您好，请问为什么火狐浏览器中，编辑器换行不了呢？

**Comment by wangfupeng1988** [comment]
什么系统（多少位），火狐哪个版本？官网demo就有这个问题吗？——这些都要描述一下，提问问题远不止问一句话这么简单。

我这里mac os下没发现问题。

**Comment by linvic** [comment]
抱歉，问题提的不够详细。
win8 64位系统。火狐46.0.1。
官方demo没有这个问题。不知道是不是引用ng导致的。
测试页面http://mt.tsta.com.cn/Admin/Meeting/Add
账号，cyl，密码123456

**Comment by linvic** [comment]
sorry，已解决，太慌张了，另外一个前端样式影响的
