### ISSUE TITLE
Cannot set property 'menus' of undefined

### ISSUE THREAD

**Issue by wupantong** [wangfupeng1988/wangEditor#342]
div为动态追加多个相同的 在初始化编辑器的时候报错：Cannot set property 'menus' of undefined  这问题是为什么

**Comment by wangfupeng1988** [comment]
这个错误的原因就是DOM未加载就执行了`create()`，具体如何解决自己思考一下吧

**Comment by wupantong** [comment]
window.onload = function() {
                var
                    textarea = $(".wrapper"),
                    editor = new wangEditor(textarea);
                editor.config.menus = $.map(wangEditor.config.menus, function(item, key) {
                    if (item === 'location') {
                        return null;
                    }
                    return item;
                });
                editor.create();
            };

如果我这样写的话 在新追加的div上面是没有编辑器生成的
