### ISSUE TITLE
手机版的上传图片提示错误

### ISSUE THREAD

**Issue by laowen123** [wangfupeng1988/wangEditor#343]
手机版上传图片提示”图片加载失败“，同时点击表情那个按钮，显示为空白（表情图片没有正常加载出来），请帮忙解答一下，谢谢

**Comment by laowen123** [comment]
我是安卓5.1.1，UC浏览器上传图片一直处于“上传中”，然后提示上传超时，失败

**Comment by wangfupeng1988** [comment]
看文档。

mobile版暂时不维护 http://www.kancloud.cn/wangfupeng/wangeditor2/139064
