### ISSUE TITLE
同一页面，按钮出发弹层，弹层里面用到编辑框问题。

### ISSUE THREAD

**Issue by fashman** [wangfupeng1988/wangEditor#345]
如题：弹层第一次初始化的时候没有问题；关闭删除弹层后，第二次弹出的弹层编辑框无法初始化；

**Comment by wangfupeng1988** [comment]
关键在于你是如何弹层的，以及第二次弹层之后做了什么。请给出静态demo页面来复现这个问题。看到具体的实现方式，我才能判断问题所在。

注意，给出的demo页面只要能复现问题，剩下的越简单越好，不要夹杂任何无关代码。

**Comment by wangfupeng1988** [comment]
先关闭，有问题继续在下面回复即可
