### ISSUE TITLE
能不能改进一下颜色的显示，添加颜色调色板的功能

### ISSUE THREAD

**Issue by nmdigboy** [wangfupeng1988/wangEditor#347]
现在的颜色样式是一个笔，下面一条颜色的色线，在一些浏览器中显示很不好，能不能换成小方格形式的？并且可以调色的？

**Comment by wangfupeng1988** [comment]
> 在一些浏览器中显示很不好

那些浏览器显示有问题，可以报给我，我来修复。

至于用什么样子显示（是否用小方块显示），这就是仁者见仁了，你提该问题之前还没有人说现在的样式不好看，因此先不改。

另外，调色板其实并无意义，提供的默认几个颜色已经够用了，而且还可以手动配置更多颜色。所以我好奇你说要加调色板，是为了加而加，还是你的需求非加不可？
