### ISSUE TITLE
二次编辑 获得的是源码 html标签在编辑器中不解析

### ISSUE THREAD

**Issue by sumengliang** [wangfupeng1988/wangEditor#348]
我的情况不是查看源码为空 获得了内容 但是到编辑器中 内容中的html标签没有解析出来 很混乱 和post提交前点击源码的内容一样 但是在此编辑是把内容当普通文本 而不解析 点击源码 只会更混乱 ？？？
是和angular集成的BTW

**Comment by wangfupeng1988** [comment]
没看明白你说的问题，最好举一个例子说明。
