### ISSUE TITLE
回车后，用输入法输入的文本跑到了<p>标签外面

### ISSUE THREAD

**Issue by wooilung** [wangfupeng1988/wangEditor#349]
修改了回车事件，在`<p>`标签内增加了自定义属性
直接英语输入没有问题
![image](https://cloud.githubusercontent.com/assets/2063253/17124772/1f434f84-5320-11e6-90c2-877fda68d084.png)
用输入法输入，光标跳了一下，输入的文本跑到了`<p>`标签外面
![image](https://cloud.githubusercontent.com/assets/2063253/17124850/a56ed718-5320-11e6-9979-2927af3e4fcb.png)

**Comment by wangfupeng1988** [comment]
> 修改了回车事件，在<p>标签内增加了自定义属性

这块你修改的哪里？怎么改的？

> 用输入法输入，光标跳了一下

这个『跳一下』是如何触发的，哪个键盘的健触发的？
