### ISSUE TITLE
关于placeholder的问题

### ISSUE THREAD

**Issue by jerry-he** [wangfupeng1988/wangEditor#35]
项目中引入多使用在评论中，因为比较轻量。所以需要placeholder支持，如果项目能原生支持就比较好了

**Comment by wangfupeng1988** [comment]
编辑器目前不支持 placeholder ，因为编辑器实际上是一个 div，而不是一个textarea。
我可以告诉你一个方法：
你让页面默认显示一个input，其中加上placeholder属性。当用户focus这个input时候，再显示编辑器。

我还专门为你做了了一个demo：http://www.wangeditor.com/wangEditor/test/test-placeholder.html
源代码：https://github.com/wangfupeng1988/wangEditor/blob/master/test/test-placeholder.html

**Comment by wangfupeng1988** [comment]
该问题同 https://github.com/wangfupeng1988/wangEditor/issues/37 是一个问题，先关闭该问题。
更多信息可参见：https://github.com/wangfupeng1988/wangEditor/issues/37
