### ISSUE TITLE
给内容赋值‘<p><br></p>’ 会使倾斜标签变蓝

### ISSUE THREAD

**Issue by dongtc** [wangfupeng1988/wangEditor#350]
初始化后 `editor.$txt.html()` 得到的内容为 `‘    <p><br></p>’` 前面有空格，
后续给它赋值 `‘<p><br></p>’` 倾斜标签竟然变蓝了==

初始化后 执行 `editor.$txt.html(‘<p><br></p>’);` 或`editor.clear();` 均可解决问题

![qq 20160726182825](https://cloud.githubusercontent.com/assets/13464443/17134808/cfd5ef58-535e-11e6-925f-19742fc5ef5d.png)

**Comment by wangfupeng1988** [comment]
> 后续给它赋值 ‘<p><br></p>’ 倾斜标签竟然变蓝了==

>  初始化后 执行 editor.$txt.html(‘<p><br></p>’); 

这两句话说的不是一个意思吗？为何会有不一样的结果。

描述问题有点混乱，按照步骤讲讲，如何一步一步，最后复现问题，就好了。
另外，哪个浏览器要说明白。

**Comment by dongtc** [comment]
额，终于查到了
当点击一个`<i>`标签并触发事件更改内容时，会触发斜体图标变蓝
```html
<i ng-click="$ctrl.click()">点点点</i>
```
```js
function click() {
  editor.$txt.html('<p></p>');
}
```

**Comment by wangfupeng1988** [comment]
哦，原来如此。我估计，在你点击`<i>`标签的时候，肯定也触发了这个标签的`focus`事件了。

我会再编辑器中做一个判断，只有焦点在编辑器内部才改变菜单状态，在外面时不改变。我回头先验证一下，完事儿在此回复你

**Comment by wangfupeng1988** [comment]
我看到了，目前确实有这个问题，原因比较怪异。你先用`<span>`标签替换一下`<i>`标签吧，这样改能解决问题。
