### ISSUE TITLE
IE浏览器下，复制的内容不能插入指定位置，而是直接插入到末尾。

### ISSUE THREAD

**Issue by liunianmou** [wangfupeng1988/wangEditor#352]
IE浏览器下，复制的内容不能插入指定位置，而是直接插入到末尾。

**Comment by wangfupeng1988** [comment]
是的，IE的`document.execCommand`不支持`insertHTML`，因此插入到后面了。

也许会有其他解决方案，例如对DOM的TEXT节点直接进行操作，不过那应该是下一个大版本应该做的事儿。
