### ISSUE TITLE
用webpack打包代码后,报这个错TypeError: wangEditor is not a constructor

### ISSUE THREAD

**Issue by cbbaaa1989** [wangfupeng1988/wangEditor#353]
var wangEditor = require('wangeditor');
var editor = new wangEditor('editor-trigger');

控制台打印wangEditor：Object {}

**Comment by cbbaaa1989** [comment]
找到原因了，和echarts的require加载方式冲突了

**Comment by cbbaaa1989** [comment]
这个有办法解决吗

**Comment by cbbaaa1989** [comment]
echarts升级到3.2.2搞定了

**Comment by wangfupeng1988** [comment]
http://www.kancloud.cn/wangfupeng/wangeditor2/137878

第四步，缩小问题范围

如果将编辑器集成到项目环境中出的问题，此时你要确定到底是编辑器的问题还是因为集成到项目中的冲突问题。你可以：

试试官网demo有没有问题；
下载源码并在本地运行demo，看看有没有问题（一般针对图片上传，需要服务端支持）
先别管项目环境，先自己做一个编辑器的demo，看是否正常。如果正常，将项目中的功能一步一步加到编辑器页面。边加边验证，看看哪一步导致的冲突。

**Comment by cbbaaa1989** [comment]
已经找到原因了，echart2.0自动引入了一个amd环境，引发的冲突

**Comment by wangfupeng1988** [comment]
OK
