### ISSUE TITLE
在代码去复制粘贴 敲回车键无法换行

### ISSUE THREAD

**Issue by zsw12013** [wangfupeng1988/wangEditor#354]
在插入的代码去编写内容，加入在外面复制一些内容，然后粘贴到 代码区中‘
然后敲回车键无法切换到下一行，
然后源码会发现，自动插入了一些标签
`<span style="line-height: 1.8; font-size: inherit;"></span>`

**Comment by wangfupeng1988** [comment]
和粘贴没关系。

你输入一段代码，然后在已经输入的代码内容中，点击回车键，也会有这种情况。但是只有第一次回车的时候才有，第二次、第三次就OK了，具体原因我也不太清楚。

但是你说的这个`<span style="line-height: 1.8; font-size: inherit;"></span>`我没有发现。
