### ISSUE TITLE
我这里并没有说明上默认的代码高亮功能，想请教一下是什么原因呢？

### ISSUE THREAD

**Issue by vvhl** [wangfupeng1988/wangEditor#356]
我按照说明，正确的使用了wangEditor，页面上也成功的加载了编辑器，功能也一切正常，除了这个高亮功能，我插入代码的时候并没有高亮显示，是什么原因呢？

**Comment by wangfupeng1988** [comment]
过程描述详细。用什么版本的编辑器代码？啥浏览器？插入什么语言没有高亮？如何操作的？有没有在线能复现问题的demo？

**Comment by vvhl** [comment]
嘿嘿我搞定了，原来是没有引用高亮的文件，谢谢
