### ISSUE TITLE
发现了一个不知道是不是bug的东西

### ISSUE THREAD

**Issue by vvhl** [wangfupeng1988/wangEditor#357]
给div设置了高度，然后点击全屏，再点击缩小，高度就变低了，再点击全屏，再缩小，又变更低了，一直重复多次点击，变到65px时就停止了不再变小了

**Comment by wangfupeng1988** [comment]
好，我周末去查证一下，很有可能有这个问题。

这应该怪之前设计的时候没有考虑全面，导致目前全屏功能、自动高度功能会和很多功能有冲突，而且不好改动。我看看尽量给改过来。

**Comment by wangfupeng1988** [comment]
你确定在官网demo中能复现这个问题吗？ http://www.wangeditor.com/  

如果你是其他情况复现的，请说明如何配置才能复现这个问题

**Comment by vvhl** [comment]
我自己使用时候也会这样，在官网demo看也会这样，我用的谷歌浏览器和火狐浏览器都会……

**Comment by wangfupeng1988** [comment]
我用chrome、safari和火狐，在官网demo确实没有复现你的问题，不知道你的情况是咋出现的

**Comment by wangfupeng1988** [comment]
先关闭这个问题，可继续在下面留言
