### ISSUE TITLE
关于多语言包的支持

### ISSUE THREAD

**Issue by jerry-he** [wangfupeng1988/wangEditor#36]
因为项目使用在国际项目中，需要项目本身支持多语言的封装，我们现在的方案是自定义数组，去把几个ui上的文字遍历掉，希望项目本身能支持，这样有利于这个开源项目国际化的发展

**Comment by wangfupeng1988** [comment]
多语言支持可以增加，其实就是需要开发者传入一个语言包。我已经记录下来了这个功能，近期将会增加上去。
注意群里的动态，增加完了，会再群里说。

**Comment by wangfupeng1988** [comment]
多语言配置已经支持：http://www.wangeditor.com/wangEditor/docs/index.html#langs
