### ISSUE TITLE
服务端获取不到图片后缀名

### ISSUE THREAD

**Issue by xulang** [wangfupeng1988/wangEditor#360]
如题，这是什么原因呢

**Comment by wangfupeng1988** [comment]
> 第四步，缩小问题范围
如果将编辑器集成到项目环境中出的问题，此时你要确定到底是编辑器的问题还是因为集成到项目中的冲突问题。你可以：
试试官网demo有没有问题；
下载源码并在本地运行demo，看看有没有问题（一般针对图片上传，需要服务端支持）
先别管项目环境，先自己做一个编辑器的demo，看是否正常。如果正常，将项目中的功能一步一步加到编辑器页面。边加边验证，看看哪一步导致的冲突。

http://www.kancloud.cn/wangfupeng/wangeditor2/137878

**Comment by wangfupeng1988** [comment]
有问题先去排查一下原因，看看文档，找找思路。

你光说一句`服务端获取不到图片后缀名`我也不知道啥原因，但是我的demo中是没有问题的

**Comment by straightdave** [comment]
先用浏览器开发者工具查看请求（上传图片，选好图片之后确定）的payload；不同的后端语言获取这个payload的方式不一（补充下ruby相关的：基于rack的框架，一般可使用:
`payload = request.POST`等方式获取，之后可以使用`inspect`查看获取之物内部字段内容）。可自行搜索诸如“java get request payload”之类的关键词（现在用必应比较靠谱）。
我觉得作者可以close这个issue了。

**Comment by wangfupeng1988** [comment]
@straightdave 我不知道提问者后台是否是java的
