### ISSUE TITLE
查看源码的时候可否不清除\n换行

### ISSUE THREAD

**Issue by aov2005** [wangfupeng1988/wangEditor#361]
或者添加格式化功能，不然这个查看源码可视化程度不是很高，要是编辑的页面复杂的话还要复制一遍回到IDE格式化编辑之后再粘贴回来

比如
```
<p>test</p>
<p>test</p>
<p>test</p>
```
而不是
`<p>test</p><p>test</p><p>test</p>`

**Comment by wangfupeng1988** [comment]
这个问题我之前试过，但是遇到了一些其他的影响（具体什么问题忘记了，反正挺麻烦），于是后来又改回来了。总之不是自己当初想的那么简单。

我记下这个问题，下次大版本升级一定加上高亮和格式化。这一版本就不做大改动了，我正在为下一次升级规划功能和改进的地方。

**Comment by aov2005** [comment]
好的，期待中
