### ISSUE TITLE
 图片上传成功，返回值也正确，但图片加载的时候使用的是相对路径，而不是绝对路径

### ISSUE THREAD

**Issue by moxiaozhou** [wangfupeng1988/wangEditor#362]
![image](https://cloud.githubusercontent.com/assets/10559002/17456329/bb45a35c-5c06-11e6-94a5-fa30936daecd.png)

**Comment by wangfupeng1988** [comment]
最后一行红色提示，你返回的是一个json串，文档中不是这么规定的。

**Comment by moxiaozhou** [comment]
谢谢，一语点破，我一直以为这返回的是json数据，原来只是string的json串。
