### ISSUE TITLE
关于图片的两个问题

### ISSUE THREAD

**Issue by iccfzn** [wangfupeng1988/wangEditor#364]
1.在图片上传的配置里面需要加配置才会出现图片上传
 editor.config.uploadImgUrl = '/www';
我加了一直 他会直接执行上传图片的事件 ，导致错误 ，可我不需要上传图片 我只需要让他转成base64 我获取到整个的html存在数据库里即可，请指导一下 谢谢
2.获取html作者写的很清楚，但是 我是要在后台 获取 我用的是.net 
我是这样取得 可是取不到Request.Form["editor1"].ToString();
别的都可以取到就是这个取不到 求解 已经一下午了  谢谢

**Comment by iccfzn** [comment]
不好意思 作者 第二个问题多余问了 已经解决 只剩第一个了 希望不吝赐教

**Comment by wangfupeng1988** [comment]
>  我只需要让他转成base64 我获取到整个的html存在数据库里即可，请指导一下 谢谢

目前不支持通过配置直接让图片使用base64的格式保存，而且直接这样用会有很多问题。如果你非要使用，可参见这里 https://github.com/wangfupeng1988/wangEditor/blob/master/dist/js/wangEditor.js#L90 

将这行改成`E.isOnWebsite = true;`试试

**Comment by wangfupeng1988** [comment]
先关闭，有问题继续留言

**Comment by hypwxm** [comment]
@wangfupeng1988 你官网的图片选着直接转base64不是你的变奇迹本身转的吗？

**Comment by hypwxm** [comment]
@wangfupeng1988 你官网的图片选着直接转base64不是你的编辑器本身转的吗？

**Comment by wangfupeng1988** [comment]
> 你官网的图片选着直接转base64不是你的编辑器本身转的吗？

一切以文档为主，文档没说的你就当没有
