### ISSUE TITLE
插入代码中的注释显示成一行了

### ISSUE THREAD

**Issue by zsw12013** [wangfupeng1988/wangEditor#368]
没发上传图片，，，还是看地址吧
http://zhousw.top/posts/90
插入的java代码，里面的注释显示成一行了
对比一下
http://blog.csdn.net/zsw12013/article/details/52157319

**Comment by wangfupeng1988** [comment]
`http://blog.csdn.net/zsw12013/article/details/52157319`这里面，我发现了这样一个样式：

```
.markdown_views pre code {
    word-wrap: normal;
}
```

你加一下这个样式，看看能否换行了？

**Comment by zsw12013** [comment]
不行。。。。。。。。。。。。。。。。

**Comment by wangfupeng1988** [comment]
> 就是最终页面显示 的时候就有问题了

就是让你在最终显示的页面加`word-wrap: normal;`样式
