### ISSUE TITLE
编辑中是否可以加一个placeholder

### ISSUE THREAD

**Issue by beijishiqidu** [wangfupeng1988/wangEditor#37]
![qq 20150909100341](https://cloud.githubusercontent.com/assets/14070935/9751666/165e0320-56da-11e5-8c6f-4a004cf6bc51.jpg)
类似于截图中的效果。

我之前也做过一个div的编辑器，简单的代码如下：
<div contenteditable="true" class="your-comment" placeholder="写下你的评论">&nbsp;</div>
借助了Jquery的placeholder的插件才兼容了IE浏览器。

就想着如果你的实现也是在div的基础上弄的，那应该也容易吧？

**Comment by wangfupeng1988** [comment]
编辑器目前不支持 placeholder ，因为编辑器实际上是一个 div，而不是一个textarea。
我可以告诉你一个方法：
你让页面默认显示一个input，其中加上placeholder属性。当用户focus这个input时候，再显示编辑器。

我还专门为你做了了一个demo：http://www.wangeditor.com/wangEditor/test/test-placeholder.html
源代码：https://github.com/wangfupeng1988/wangEditor/blob/master/test/test-placeholder.html

**Comment by wangfupeng1988** [comment]
提问者长时间不反馈，先把问题关闭，如有需要，再重新向我反馈。

**Comment by lgd5555** [comment]
我在使用移动版的时候遇到这个问题是这样解决的，给textarea添加onclick时间，点击编辑器初始化
`<textarea class="text"  id="textarea1" onclick="editinit()"   placeholder="快记录下你的话"><textarea>`
`
function editinit(){
	editor.init();
}
`

**Comment by wangfupeng1988** [comment]
@lgd5555 新问题重新提交一个issue，并且去移动版的项目下面去提交。放在这儿就乱了

**Comment by lgd5555** [comment]
哦，这不是新的问题，只是一个可适用于移动编辑器的解决方案，我想也许可以用在PC端

**Comment by wangfupeng1988** [comment]
@lgd5555 哦。。。抱歉哈，我一时大意看错了。。。感谢你的答复
