### ISSUE TITLE
关于图片上传的一点建议

### ISSUE THREAD

**Issue by infeng** [wangfupeng1988/wangEditor#370]
因为公司上传图片用的是同一个接口，能不能提供自定义上传事件的功能（自己写请求的逻辑），谢谢。

**Comment by wangfupeng1988** [comment]
看看这个能满足要求吗？ http://www.kancloud.cn/wangfupeng/wangeditor2/123689

**Comment by infeng** [comment]
接口请求参数的类型是base64字符串，所以只能改xhr上传图片的方法

**Comment by wangfupeng1988** [comment]
你这种情况不多见啊，图片使用base64的情况比较有限，图片文件过大、数量过多，再使用base64时有很多问题的。

**Comment by infeng** [comment]
我跟后台那边协商一下，不行的话只能改xhr上传图片的方法，wangEditor其他方面都能满足需求，也不想换其他的

**Comment by wangfupeng1988** [comment]
好，和其他角色合作要提出自己的建议，不能人家说啥你就用啥。
