### ISSUE TITLE
关于编辑器表格的bug

### ISSUE THREAD

**Issue by Idiot-Alex** [wangfupeng1988/wangEditor#371]
在编辑器中编辑表格之后，编辑器中能看到表格有边框，但是获取完整的html文本之后，再显示在网页中就发现表格没有了边框，需要自己修改或者设置样式

**Comment by wangfupeng1988** [comment]
以前的issue有人问过，记得不止一次了。
编辑器只输出无任何样式的纯html，你如果要展示的时候自己加一些标签的样式，这样做的好处就是——编辑器不会强行“绑架”样式，想显示什么样，你自己来控制。可参考 http://www.kancloud.cn/wangfupeng/wangeditor2/113988
