### ISSUE TITLE
webpack打包提示警告

### ISSUE THREAD

**Issue by broadliyn** [wangfupeng1988/wangEditor#373]
wangeditor使用版本是2.1.16，webpack打包运行的时候会提示警告：

> WARNING in ./~/wangeditor/dist/js/wangEditor.js
> Critical dependencies:
> 19:35-68 the request of a dependency is an expression
> 22:42-78 the request of a dependency is an expression
>  @ ./~/wangeditor/dist/js/wangEditor.js 19:35-68 22:42-78

> WARNING in ./~/wangeditor/dist/js/wangEditor.min.js
> Critical dependencies:
> 2:264-297 the request of a dependency is an expression
> 2:376-412 the request of a dependency is an expression
>  @ ./~/wangeditor/dist/js/wangEditor.min.js 2:264-297 2:376-412

查看源码发现：
> window.wangEditorCssPath ? require(window.wangEditorCssPath) : require('../css/wangEditor.css');

这里用到了动态require，好像报错了。

**Comment by wangfupeng1988** [comment]
你先手动将动态引用改一下，这一版本webpack打包的问题先放一放，下一次大版本升级，直接用webpack来做。
