### ISSUE TITLE
IE8下不能连续的粘贴

### ISSUE THREAD

**Issue by osoctz** [wangfupeng1988/wangEditor#375]
在ie8下先粘贴一段文本,然后CTRL+A全选后backspace删除掉文本

在粘贴失效,其他浏览器下没发现这种情况

而且在ie8下会出现删除后出现空行两行的情况,光标在第二行。

**Comment by osoctz** [comment]
resultHtml = resultHtml.replace((new RegExp('\n', 'g'), '</p><p>'));
2414行 多了括号吧

**Comment by wangfupeng1988** [comment]
> 2414行 多了括号吧

哪里多了个括号？

**Comment by wangfupeng1988** [comment]
IE8的问题，我周末会一起验证一下看看

**Comment by osoctz** [comment]
只是疑问  resultHtml = resultHtml.replace(new RegExp('\n', 'g'), '</p><p>');  是不是这么写 没有歧义点

**Comment by osoctz** [comment]
\'</p><p>\'  没有显示出来

**Comment by wangfupeng1988** [comment]
哦 貌似是，不好意思我刚才没看出来 `resultHtml = resultHtml.replace((new RegExp('\n', 'g'), '</p><p>'));`在`replace`多了一层括号

**Comment by wangfupeng1988** [comment]
> resultHtml = resultHtml.replace((new RegExp('\n', 'g'), '</p><p>'));在replace多了一层括号

已经改过来了，下载`v2.1.17`版本

**Comment by osoctz** [comment]
ie8下的连续粘贴问题可以修复吗

**Comment by osoctz** [comment]
目前貌似全选删除后在IE8下光标在第二行,如果不移动光标到第一行，直接粘贴的话无效

**Comment by wangfupeng1988** [comment]
非常抱歉，v2 此后不维护了，已经升级到 v3 版本了，个人业余精力有限，还请体谅。
