### ISSUE TITLE
自定义编辑器颜色添加BUG

### ISSUE THREAD

**Issue by ljeonhack** [wangfupeng1988/wangEditor#376]
颜色配置中`E.config.colors `添加了70条颜色，但只显示了69条，
其中有一条   ` '#7f7f7f': '浅绿色', `  没有显示出来，其他的都显示出来了，
再次经过测试，`#7f7f7f` 换成其他颜色也显示不出来，多添加了10条，也就是说一共是70条颜色，但还是只显示了69条！
不知道是怎么回事，是不是bug呢？

**Comment by wangfupeng1988** [comment]
> 颜色配置中`E.config.colors`添加了70条颜色

注意，在`E.config.colors`中配置是全局配置，不是单个编辑器的配置。另外，即便是对`E.config.colors`配置，也不要去修改源码。

> 其中有一条 '#7f7f7f': '浅绿色', 没有显示出来，其他的都显示出来了

是在70条的情况下不显示，还是小于70条等所有其他情况都不显示？这个自己可以确定。

> 添加了70条颜色，但只显示了69条

你把你这70条颜色的json发给我，我临时写不出那么多颜色值，我直接拿你的试试吧。

**Comment by ljeonhack** [comment]
@wangfupeng1988 第一个关于全局配置问题，颜色配置我是直接写在了wangEditor.js 文件的 E.config.colors中，因为我的项目中多个页面要用到编辑器，每次调用的时候还要填写那么多的颜色配置，代码量会很多，也影响项目中的代码文件阅读，所以我直接修改的全局配置，这样其他页面直接调用这个编辑器即可。

第二个关于显示数量问题，我无论添加80条还是100条，最终显示出来只有69条，意思就是大于69条之后，后面的颜色都显示不出来。

第三个关于颜色的json问题，我直接复制过来，如下：
'#ffffff': '#ffffff',
'#000000': '#000000',
'#eeece1': '#eeece1',
'#1f497d': '#1f497d',
'#4f81bd': '#4f81bd',
'#c0504d': '#c0504d',
'#9bbb59': '#9bbb59',
'#8064a2': '#8064a2',
'#4bacc6': '#4bacc6',
'#f79646': '#f79646',
'#f2f2f2': '#f2f2f2',
'#7f7f7f': '#7f7f7f',
'#ddd9c3': '#ddd9c3',
'#c6d9f0': '#c6d9f0',
'#dbe5f1': '#dbe5f1',
'#f2dcdb': '#f2dcdb',
'#ebf1dd': '#ebf1dd',
'#e5e0ec': '#e5e0ec',
'#dbeef3': '#dbeef3',
'#fdeada': '#fdeada',
'#d8d8d8': '#d8d8d8',
'#595959': '#595959',
'#c4bd97': '#c4bd97',
'#8db3e2': '#8db3e2',
'#b8cce4': '#b8cce4',
'#e5b9b7': '#e5b9b7',
'#d7e3bc': '#d7e3bc',
'#ccc1d9': '#ccc1d9',
'#b7dde8': '#b7dde8',
'#fbd5b5': '#fbd5b5',
'#bfbfbf': '#bfbfbf',
'#3f3f3f': '#3f3f3f',
'#938953': '#938953',
'#548dd4': '#548dd4',
'#95b3d7': '#95b3d7',
'#d99694': '#d99694',
'#c3d69b': '#c3d69b',
'#b2a2c7': '#b2a2c7',
'#92cddc': '#92cddc',
'#fac08f': '#fac08f',
'#a5a5a5': '#a5a5a5',
'#262626': '#262626',
'#494429': '#494429',
'#17365d': '#17365d',
'#366092': '#366092',
'#953734': '#953734',
'#76923c': '#76923c',
'#5f497a': '#5f497a',
'#31859b': '#31859b',
'#e36c09': '#e36c09',
'#7f7f7f': '#7f7f7f',
'#0c0c0c': '#0c0c0c',
'#1d1b10': '#1d1b10',
'#0f243e': '#0f243e',
'#244061': '#244061',
'#632423': '#632423',
'#4f6128': '#4f6128',
'#3f3151': '#3f3151',
'#205867': '#205867',
'#974806': '#974806',
'#c00000': '#c00000',
'#ff0000': '#ff0000',
'#ffc000': '#ffc000',
'#ffff00': '#ffff00',
'#92d050': '#92d050',
'#00b050': '#00b050',
'#00b0f0': '#00b0f0',
'#0070c0': '#0070c0',
'#002060': '#002060',
'#7030a0': '#7030a0',

**Comment by wangfupeng1988** [comment]
太坑了。。。`'#7f7f7f': '#7f7f7f',`重复了两次，当然就油70个变成69个了，属性名重复是会被覆盖的。

**Comment by ljeonhack** [comment]
@wangfupeng1988 我擦，你不说我都没发现，汗，毕竟颜色值挺多了，这个。。。一时没发现
