### ISSUE TITLE
360浏览器，chrome兼容性问题

### ISSUE THREAD

**Issue by lidanxie** [wangfupeng1988/wangEditor#377]
你好，我刚下了编辑器wangEditor-2.1.16的demo，初步测试的时候发现在360浏览器并不能正常运行，这让我有点尴尬，请问有什么办法可以解决360浏览器的版本问题吗？

**Comment by wangfupeng1988** [comment]
> 标题：360浏览器，chrome兼容性问题

chrome有和兼容性问题？没说明白

> 初步测试的时候发现在360浏览器并不能正常运行

具体是哪里不能正常运行？有问题最好一次描述清楚，要不然我再追问一次（甚至好几次）浪费时间

**Comment by lidanxie** [comment]
是这样的，我是打开你的test文件夹中的index.html文件的，在主流浏览器上看了一下，ie基本都可以，但是谷歌中默认表情那部分的就出不来，在360浏览器中工具条都加载不出来，我怀疑这是因为文件的路径搞错了吗？自己试了一下，可能我也还不知道改怎么使用您已经实现好的功能，请问您有最新版本的使用说明教程吗？

**Comment by wangfupeng1988** [comment]
1. 去用着俩浏览器验证官网的demo是否正常 www.wangeditor.com
2. 有问题先去看文档，官网上有链接
