### ISSUE TITLE
百度地图接口部分，是否考虑支持自定义地图显示的大小？

### ISSUE THREAD

**Issue by faydanube** [wangfupeng1988/wangEditor#378]
已决定出坑……

**Comment by wangfupeng1988** [comment]
这个问题，目前返回的图片尺寸还是固定的，不过可以通过配置来规定尺寸大小，我周末试一下，到时候回复在此回复你。

**Comment by wangfupeng1988** [comment]
如果急用，可以先修改这里的源码 https://github.com/wangfupeng1988/wangEditor/blob/master/dist/js/wangEditor.js#L5777
