### ISSUE TITLE
textarea内容没有更新

### ISSUE THREAD

**Issue by nsecgo** [wangfupeng1988/wangEditor#379]
官网上说编辑区域的内容的修改，会实时更新到textarea当中。但我在用test目录下的index.html测试时，textarea内容并没有改变啊？
![2016-08-15 15-09-32](https://cloud.githubusercontent.com/assets/7569177/17658010/a29139b6-62fa-11e6-9b5d-2333126c0498.png)

**Comment by wangfupeng1988** [comment]
不要看DOM，用js获取textarea内容来验证一下试试改了没？

**Comment by nsecgo** [comment]
找到原因了。。。

**Comment by wangfupeng1988** [comment]
> 找到原因了。。。

找到原因最好能写出来分享一下，issue提出来放在这里不是和作者私聊用，而是分享用

**Comment by nsecgo** [comment]
因为我是用后端接收数据测试的，结果我后端程序出了问题，
