### ISSUE TITLE
关于顶部工具栏的位置修改

### ISSUE THREAD

**Issue by jerry-he** [wangfupeng1988/wangEditor#38]
我们项目中（类似微博的发布框），需要将工具栏放在底部，因为目前样式都是js控制的，如果我们直接修改源码，可能以后就不好用了，看有什么办法可以修改？

**Comment by jerry-he** [comment]
不是说有问题都响应的么？

**Comment by wangfupeng1988** [comment]
我这个周末外出，所以没有及时回复邮件。

首先，你说的需求我很感兴趣，因为现在很多传统的方式都被一一打破，慢慢趋向于简洁化，所以有人能提出一些不同的想法给我，我是很高兴的，我也会尽力去满足大家的需求。

你说的“将工具栏放在底部”功能，目前虽然没有配置能支持，但是我会做一个简单的调整，然后告诉你如何去简单的二次开发支持。后面升级，我会把这个配置加上，到时候你升级时候再改过来，就OK啦。

这周末没时间了，我会下周一或者周二，在这里给你回复。

**Comment by wangfupeng1988** [comment]
先给你说一个暂时的解决方案，比较简单，也不会影响后续升级。在 http://www.wangeditor.com/wangEditor/docs/index.html#start 的基础上，做如下修改：

```
$(function(){
	var editor = $('#textarea1').wangEditor();

	//获取按钮容器、输入框容器
	var $btnContainer = editor.$btnContainer,
		$txtContainer = editor.$txtContainer;

	//修改按钮容器的样式
	$btnContainer.css('border-bottom', '0');
	$btnContainer.css('border-top', '1px solid #eeeeee');

	//移动按钮容器的位置，把按钮放在下面
	$txtContainer.after($btnContainer);
});
```

这样就可以把菜单栏放在编辑器的底部。
其他的配置（如自定义配置菜单）完全可以参考文档说明来修改。

不过，这样修改只能将菜单栏放在底部，其他的改变没有。如果不能满足你的需求，你再另外单独提出来给我。

**Comment by wangfupeng1988** [comment]
提问者不予回复，暂时关闭问题。再有问题，再反馈给我。
