### ISSUE TITLE
插入大图片无法正常拖拽

### ISSUE THREAD

**Issue by 18060006730** [wangfupeng1988/wangEditor#380]
如果插入的图片高度大于编辑框后，拖拽的小黑点在拖拽的时候就会错位,看到之前好像有人问过，试了官网的demo，发现还是有这个问题

**Comment by wangfupeng1988** [comment]
插入图片时，编辑器会将图片的宽度设置为`max-width:100%`，想拖拽的话，将滚动条滑动到最底部应该可以看到拖拽按钮的。这是我刚才试过的。

至于你说的错位的问题，我不清楚如何复现的，你的“大图”是多大，什么尺寸的，可以描述一下，或者直接把图发给我，我来验证
