### ISSUE TITLE
保存后，有多余的后缀代码

### ISSUE THREAD

**Issue by swmwlm** [wangfupeng1988/wangEditor#381]
保存文本后，会多余出来一段代码，
`<p><br/><p>`
这个能控制去掉吗？前台展示的时候由于多了这个代码，导致页面排版问题

**Comment by wangfupeng1988** [comment]
编辑器编辑内容是，下面多一行`<p><br></p>`是编辑器本身特点的需要，如果保存时不需要这个，可以在保存之前过来掉最后的`<p><br></p>`。过滤方法有很多，例如正则过滤

**Comment by ejseen** [comment]
那請問有人可以幫忙把這個方法寫好嗎

**Comment by wangfupeng1988** [comment]
> 那請問有人可以幫忙把這個方法寫好嗎

这么简单的事儿，还在这里寻求别人帮助？以后还怎么愉快的干程序猿？

**Comment by swmwlm** [comment]
我们可以自己过滤掉。但是作为一款编辑器，还请考虑这个东东是否必须加？人为的给别人加上这个代码是否不妥？如何去掉？

**Comment by wangfupeng1988** [comment]
> 但是作为一款编辑器产品，唯独从源头上解决乃是正统，还请考虑这个东东是否必须加？

这样考虑没有问题，也应该这么做。不过这里`<p><br></p>`是一个例外。按你说的，后面多了`<p><br></p>`就自动过滤掉，万一用户需要最后那个空行呢？如果用户自己主动在最后加了很多个空行，是删除掉、不删除还是删除部分？

每个简单的问题一到用户真正的使用场景中，机会将复杂度提高。

**Comment by swmwlm** [comment]
我只想说，很多编辑器是这样的：初始化的时候会加上`<p><br></p>`，wangEditor也是如此。当用户输入了内容，此时不敲击回车，是不会添加上面的代码； 如果用户敲了回车，则会加上`<p><br></p>`。这样才符合大多数人的习惯吧。希望可以考虑这么实现。当然，保持现状也没关系，只是我们开发者在每次进行数据保存的时候都需要麻烦一点。
