### ISSUE TITLE
[交流]我用react重写了umeditor，有些问题需要和你交流

### ISSUE THREAD

**Issue by liuhong1happy** [wangfupeng1988/wangEditor#382]
最近几个月折腾了富文本编辑器的实现，当然也是结合自己公司的实际情况，采用的react来实现的，ui采用的umeditor的ui，关键是有些问题需要请教大牛，或者说能否讨论一些问题呐。
我的扣扣 `284362096`。

**Comment by wangfupeng1988** [comment]
😃 OK
