### ISSUE TITLE
删除图片事件怎么写呢？

### ISSUE THREAD

**Issue by cssiso** [wangfupeng1988/wangEditor#385]
上传图片后，在回显得图片的toolbar的有个删除图片按钮，这个按钮的点击事件怎么写呢？ 要获取对应图片的src属性值。
由于没有在文档中找到说明，以往的问题里好像没有。

**Comment by wangfupeng1988** [comment]
你是想前端点击了“删除”按钮，同步到后端也删除图片文件吧？

这个还暂时不支持，因为删除图片的方式有很多种，不仅仅是toolbar的删除按钮，因此这里很难通过回调事件来监控。

下次大版本升级考虑支持这一块，但是肯定不是以监听删除按钮的回调事件的方式

**Comment by cssiso** [comment]
哦，我有个想法不知道可行不嘛，在插入本地图片时给<img class="localImg">加个样式用做选择器，并把该img的src属性值保存到一个数组里面，当编辑器的内容发生变化时（当前版本已有的事件）从编辑器中查找所有的<img class="localImg">和数组的长度对比，如果长度不相等应该是可以找出删除的的图片的src属性值的。

**Comment by wangfupeng1988** [comment]
恩，如果要实现的话，差不多就是你这个思路——临时存储、有变化即对比。

**Comment by 613660067** [comment]
同在关注这一块!
