### ISSUE TITLE
设置字号后，line-height出现不相应匹配问题

### ISSUE THREAD

**Issue by noinflation** [wangfupeng1988/wangEditor#386]
应该算个bug：复现情景 ——  在第一行设置字号为24px之后，第二行改字号为12px后仍然保留了line-height为24px，之后在换行每行的line-height都为24px。甚至全部删除之后，line-height也会保留24px的值

**Comment by wangfupeng1988** [comment]
我了解这个问题了，不过这个问题比较棘手，目前修改的方案只能满足你一部分需求。即——默认文字情况下，你如果将文字字号放大，line-height会变大；但是你如果将文字字号缩小，那就无效了。

如果也想满足第二个，那将会导致默认文字的line-height太小，导致效果很难看。这次修改将在`v2.1.18`发布

-----

以上是编辑器中的样式修改，你保存内容然后到了展示页之后，样式你就可以自己去定义了，那里你可以做详细的优化。

**Comment by noinflation** [comment]
十分感谢您给我做出了解答，我也发现您提交了一个完善line-height的commit，将每个包含块里的line-height保持了一致，确实在编辑器里后line-height得到了完善。
发现如果将每行的字号设置为不同，比如第一行字号24px，第二行字号12px，然后全选删除，重新输入内容后，发现输入的内容会被包含在一个span标签里，比如<span style="line-height: 24px;">发生地方</span>，这里强行设置了line-height（因此导致如果字号为12px，line-height也为24px，觉得不太好吧），为啥要包含在span里，强行设置line-height，这里设置line-height的相关代码在哪，我调试了很久没定位到？

**Comment by wangfupeng1988** [comment]
> 为啥要包含在span里，强行设置line-height，这里设置line-height的相关代码在哪，我调试了很久没定位到？

你提出的这个问题，应该是浏览器内部的处理逻辑，我没记得自己有过这种干预。可以这样验证：

> 比如第一行字号24px，第二行字号12px，然后全选删除，重新输入内容后，发现输入的内容会被包含在一个span标签里，

这里的`然后全选删除，重新输入内容后`在刚刚删除之后，重新输入内容之前，你先鼠标点击页面空白处，让编辑器发生blur，然后再执行重新输入，你就能看不到`<span>`标签了。

**总结一下：目前`v2.x.x`的编辑器还是过于依赖浏览器内部API来实现富文本编辑功能，大部分场景下使用是没有问题的，但是至于你说的这种复杂场景下，可能就会有一些很别扭的问题，这也是整个版本无法解决的。下次升级大版本，我会考虑这种易用性的问题。**

感谢反馈！
