### ISSUE TITLE
react中接入，使用无序列表没有小圆点标记，有序列表没有数字

### ISSUE THREAD

**Issue by yuweilan** [wangfupeng1988/wangEditor#387]
开发环境是基于ant.design的react脚手架，使用webpack打包
按照你们的文档接入以后，在编辑器中使用无序列表没有小圆点标记，有序列表没有数字
但是保存的html却是正常的

**Comment by wangfupeng1988** [comment]
> 在编辑器中使用无序列表没有小圆点标记，有序列表没有数字

chrome监控list的样式，看看是否有其他css设置了没有小圆点、数字？编辑器的css和外面框架的冲突，是经常发生的事儿。

> 但是保存的html却是正常的

保存成了html然后再显示的时候，就不收编辑器的样式影响了，这个当然没有问题。

**Comment by yuweilan** [comment]
刚才检查了下，样式被覆盖掉了，麻烦了，谢谢

问下有计划做一版抛弃jq的react版本的编辑器么？
react本身是数据驱动的，jq本身对于react就是鸡肋
谢谢

**Comment by wangfupeng1988** [comment]
> 问下我们的编辑器编辑项可以可选么？有时候部分编辑项，比如插入视频不需要，就不必要出现

可以配置，看文档（官网有链接）

> 问下有计划做一版抛弃jq的react版本的编辑器么？

计划年底开始升级大版本，到时候肯定要放弃jq。v3.x 关注的是互联网的开发方式和应用方式，更多关注和React、Vue auglar的集成，在SPA中的应用，html5技术的应用，以及尽量照顾一下移动端的使用体验（至少保证移动端能用）

**Comment by yuweilan** [comment]
谢谢，另外再问下，怎么判断我们的编辑器是否有实际输入？事实上空格也是会产生代码的

**Comment by wangfupeng1988** [comment]
> 怎么判断我们的编辑器是否有实际输入？

看文档，有 `editor.$txt.text()` 可判断

**Comment by yuweilan** [comment]
单独的这个条件判断不行，我这样判断了
`const texts = this.editor.$txt.text().replace(/\s+/g,"");

const imgs = this.editor.$txt.find('img');
    	if (!texts&&!imgs.length) {//}`

**Comment by wangfupeng1988** [comment]
哦 你还考虑了img的情况，这样做是可以的

**Comment by yuxuan1125** [comment]
@yuweilan 帅哥 我最近在react中 用到wangEditor了  但是引用失败    能请教一下么 下面是代码

import React from 'react';
import WangEditor from 'wangeditor';
export default class TestPage extends React.Component {

 constructor(props) {
  super(props);
 }

 componentDidMount(){
  this.editor = new window.wangEditor('div1');
  this.editor.create();
 }
 render(){
  return (
    <div id="div1" style={{width:500,height:300}} contentEditable={true}></div>
  )
 }
};

这是build时候报的错

ERROR in ./~/.npminstall/wangeditor/2.1.23/wangeditor/dist/css/wangEditor.css
Module build failed: ModuleParseError: Module parse failed: F:\Yangtze\node_modules\.npminstall\wangeditor\2.1.23\wangeditor\dist\fonts\icomoon.ttf?-qdfu1s Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
    at DependenciesBlock.<anonymous> (F:\Yangtze\node_modules\.npminstall\webpack\1.12.15\webpack\lib\NormalModule.js:113:20)
    at DependenciesBlock.onModuleBuild (F:\Yangtze\node_modules\.npminstall\webpack-core\0.6.9\webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (F:\Yangtze\node_modules\.npminstall\webpack-core\0.6.9\webpack-core\lib\NormalModuleMixin.js:275:25)
    at F:\Yangtze\node_modules\.npminstall\webpack-core\0.6.9\webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.finished (F:\Yangtze\node_modules\.npminstall\enhanced-resolve\0.9.1\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
    at F:\Yangtze\node_modules\.npminstall\graceful-fs\4.1.11\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
 @ ./~/.npminstall/wangeditor/2.1.23/wangeditor/dist/js/wangEditor.js 19:8-40

跟webpack  配置文件有关系吗？

**Comment by yuxuan1125** [comment]
![Uploading 111.png…]()
