### ISSUE TITLE
wangEditor能够通过JS对光标进行移动操作吗

### ISSUE THREAD

**Issue by MrOhyang** [wangfupeng1988/wangEditor#389]
如题，能否像textarea一样，通过JS对光标进行操作呢？

**Comment by wangfupeng1988** [comment]
肯定可以的，不过得需要你了解js的Range和Selection部分的API，文档中也开放了wangEditor内部用到了这部分的API，可去参考一下。

**Comment by MrOhyang** [comment]
好的，我在去多了解一下API和文档~Thanks~
