### ISSUE TITLE
关于表情分组的支持

### ISSUE THREAD

**Issue by jerry-he** [wangfupeng1988/wangEditor#39]
同需求，我们项目是sns项目，聊天中需要发送表情，现在的表情是单分组的，增加一个数组不难，但是样式控制不好，表情弹出的时候需要有个tab做分类管理，同样，你说的支持移动端，我们期望中！

**Comment by wangfupeng1988** [comment]
表情分组，之前已经有人提过，我近期将支持这个功能，也不是很麻烦。
当时他说的另一个问题，就是多语言的问题，而且他更加看重多语言，因此我目前正在开发多语言支持。
表情分组接下来就会支持。我觉得一周时间肯定能搞定这个问题。

功能要一个一个做，用的人多了，提出的需求就比较多，我现在已经很努力了，一般每天都会开发到半夜。

这周末外出，因此没有及时回复邮件。

------------------------

至于移动端，我现在有思路，但是却没有一个很确定的思路，毕竟目前市面上还没有很成熟的开源产品。
不过我会试着去做一个，只有做出来，大家用上了，才会提出不同的意见和建议，慢慢修复。

目前最主要的原因就是我精力不够。待我再花一些时间把手头大家提出的紧急问题都处理了，我就会搞移动端。

移动端我一定会搞的，而且就在近期。

**Comment by wangfupeng1988** [comment]
表情分组已经支持，移动端计划在10.1之后开始设计
