### ISSUE TITLE
一个页面不能重复引用 wangEditor.js 或 wangEditor.min.js ！！！

### ISSUE THREAD

**Issue by RogerFang** [wangfupeng1988/wangEditor#390]
页面中只引用了一次wangEditor.min.js ,但是偶尔会跳出这个提示，不知道是什么原因？

**Comment by yuweilan** [comment]
我也有这个问题，同问

**Comment by wangfupeng1988** [comment]
你们抓包看看吧，肯定是哪个地方重复引用了，或者只引用改了一次，但是某个地方又重新加载这个js文件了。抓包看一下。

**Comment by kellybs** [comment]
我也碰到同样问题，是和网页中一个滚动条插件冲突了
