### ISSUE TITLE
选择字号后  打出的文字字号不匹配

### ISSUE THREAD

**Issue by sunylt** [wangfupeng1988/wangEditor#393]
就是我选完字号后  敲出的文字的字号并不是刚才选择的   然后试了选中部分文字应用字号是可以的  就是这么设计的么？

**Comment by wangfupeng1988** [comment]
是的，目前是这么设计的。这种设计方式v2.x版本不会修改，会在年底的大版本升级中修复。静静等待吧，哈哈

**Comment by DanielWLam** [comment]
额。。擦。。
