### ISSUE TITLE
wangeEditor-react

### ISSUE THREAD

**Issue by zodana** [wangfupeng1988/wangEditor#394]
react重构中。
添加表情时 ，表情文字插入在了  textEditor的最前端 。不知所云。
切入点 ：currentRange() 方法。 全文中极少找到  设置值的地方 。 有可能是 saveSelection()传进去的吧。
之前已测试 wysiwyg 的代码 。表情依然插入在文本框的最前面 。奇怪的是 firefox 是好的。 我自然的以为是兼容性问题造成的。
开始大量移植wangEditor的代码 。经过万难 ，代码终于跑通后 。发现问题依旧 。
更崩溃的是 即即使是firefox  表情字符依然插入在了文本框的最前面 。 遗憾。
我仔细观察了DEMO ，发现 在点击菜单时 ，textEditor 依然是保持焦点的， 恐怕这就是问题的关键吧。
希望作者 能告知 如何在点击菜单时  依然保持 textEditor不失去焦点的方法 。

**Comment by zodana** [comment]
经过层层跟踪源代码之后
终于找到问题所在了。 
少移植了 这个函数 saveSelectionEvent  
起先理所当然的以为 。这个函数 会写进 text 的 init逻辑中 。
问题全部解决了。
为感谢作者的无私奉献。  将react 的版本 发至QQ群。

**Comment by infeng** [comment]
@zodana 能提供react的版本学习一下吗？
