### ISSUE TITLE
插入视频之后 后面的文字都自动居中了...

### ISSUE THREAD

**Issue by Geew** [wangfupeng1988/wangEditor#396]
bug

**Comment by wangfupeng1988** [comment]
是这样的。
插入视频之后，为了排版好看，视频本身是居中的。此时你如果从视频再另起一行，那自然也是居中的。但是你如果不是从视频另起一行，而是在视频的下一行重新输入，就不会居中了。

**Comment by Geew** [comment]
但是正常的操作应该是这样的吧 插入视频 然后回车下一行 但是这个回车下一行都是默认居中的 除非用鼠标点下一行才行

**Comment by wangfupeng1988** [comment]
恩，说的也有道理。我下次升版时候改过来吧。着急的话可以自行修改一下源码，这里 https://github.com/wangfupeng1988/wangEditor/blob/master/dist/js/wangEditor.js#L5420

**Comment by wangfupeng1988** [comment]
已经修改，注意明天或者后天查看`v2.1.19`版本
