### ISSUE TITLE
存储进数据库以后是html代码，怎么正常调用显示

### ISSUE THREAD

**Issue by Yolenna** [wangfupeng1988/wangEditor#399]
编辑器的内容存储进数据库以后是html代码，怎么在前端调用这个数据是能够显示编辑器里面的样式
，目前在前端调用出来的还是一串的html代码，用的Nodejs，怎么解决呢，可能这个问题有点白痴

**Comment by Yolenna** [comment]
这个问题我解决了，感谢朋友的帮助，首先说明一下问题所在:
nodejs里面ejs引擎模板不要使用<%=%>来引用数据库的值，要当成代码写成<%-%>就解决了

**Comment by wangfupeng1988** [comment]
解决了要记得关闭问题
