### ISSUE TITLE
怎么添加颜文字支持呢?

### ISSUE THREAD

**Issue by Geew** [wangfupeng1988/wangEditor#400]

**Comment by Geew** [comment]
我的想法是 每组表情可以自定义其在tab里面的展示方式(图片,还是值) 以及 在输入之后内容的展示. 所以我在每组表情的配置里面加了两个参数
tabShow和inputShow然后自己改了下源码 
只是个建议, 望采纳

**Comment by wangfupeng1988** [comment]
没明白你啥意思

**Comment by Geew** [comment]
就题目的需求吧 怎么添加颜文字呢

**Comment by wangfupeng1988** [comment]
> 怎么添加颜文字呢

啥叫“颜文字”？

请看一下提交问题或者建议的要求： http://www.kancloud.cn/wangfupeng/wangeditor2/137878

**Comment by wangfupeng1988** [comment]
暂时关闭问题，可继续在下面留言

**Comment by 1043328710** [comment]
颜文字： ~~~///(^v^)\\\~~~？？ 是这样的吗
