### ISSUE TITLE
文字+图片混合粘贴

### ISSUE THREAD

**Issue by helibin** [wangfupeng1988/wangEditor#402]
复制单张图片是可以上传的，但图片加文字一起粘贴的话，那图片就不会上传啦，图片地址还是的原地址，不知道这个是不是可以优化下。

**Comment by wangfupeng1988** [comment]
复制单张图片你复制的是文件，而图文混排你复制出来的就是html代码（所以`图片地址还是原地址`），这两种复制形式，复制之后剪切板中内容不一样，当然就粘贴的不一样。这个没法优化。

**Comment by helibin** [comment]
哦哦，好吧，谢谢哈                             原始邮件                             发件人: 王福朋<notifications@github.com>收件人: wangfupeng1988/wangEditor<wangEditor@noreply.github.com>抄送: helibin<helibin@139.com>; Author<author@noreply.github.com>发送时间: 2016年8月30日(周二) 21:10主题: Re: [wangfupeng1988/wangEditor] 文字+图片混合粘贴 (#402)复制单张图片你复制的是文件，而图文混排你复制出来的就是html代码（所以图片地址还是原地址），这两种复制形式，复制之后剪切板中内容不一样，当然就粘贴的不一样。这个没法优化。

**Comment by cody1991** [comment]
图文混排你复制出来的就是html代码（所以图片地址还是原地址）

这个有解决的思路吗，确实需要如果图文复制，里面的图片要上传到自己的服务器，替换链接。。

**Comment by wasd345** [comment]
作者你再胡说吧 为什么没法优化 可以优化，看我的代码
   function getImgToBase64(url,callback){//将图片转换为Base64
            debugger;
            var image = new Image(editor);
            image.addEventListener('load', function() {
                debugger;
                var canvas = document.createElement("canvas");
                canvas.width = image.width;
                canvas.height = image.height;
                var ctx = canvas.getContext("2d");
                ctx.drawImage(image, 0, 0, image.width, image.height);
                var ext = image.src.substring(image.src.lastIndexOf(".")+1).toLowerCase();
                var dataURL = canvas.toDataURL("image/"+ext);
                callback(dataURL);
            }, false);
            image.src = url;
        }

        function dataURLtoFile(dataurl, filename) {//将base64转换为文件
            debugger;
            var arr = dataurl.split(','), mime = arr[0].match(/:(.*?);/)[1],
                bstr = atob(arr[1]), n = bstr.length, u8arr = new Uint8Array(n);
            while(n--){
                u8arr[n] = bstr.charCodeAt(n);
            }
            return new File([u8arr], filename, {type:mime});
        }

        //获取匹配中的img
        function pipei(html) {
            debugger;
            var result = [];
            var files=[];
            //匹配img标签
            var imgReg = /<img.*?(?:>|\/>)/gi;
           //匹配src属性
            var srcReg = /src=[\'\"]?([^\'\"]*)[\'\"]?/i;
            var arr = html.match(imgReg);
            for (var i = 0; i < arr.length; i++) {
                var src = arr[i].match(srcReg);
                //获取图片地址
                result.push(src[1]);
               //上传图片
                getImgToBase64(src[1],function(data) {
                    var myFile = dataURLtoFile(data,'test');
                    files.push(myFile);
                });
            }
            var uploadImg = editor.uploadImg;
            uploadImg.uploadImg(files);
        }


调用示例：
 pipei(pasteHtml);
![image](https://user-images.githubusercontent.com/5779660/48602308-af08be80-e9ad-11e8-9652-5c7e0f20cb58.png)
