### ISSUE TITLE
关于上传图片之前文件名被转换为数字串的问题

### ISSUE THREAD

**Issue by linyif2** [wangfupeng1988/wangEditor#403]
问题：主要是后台附件处理wangeditor上传的图片的时候，文件名这个出于业务的一些需要，需要保持原文件名，但是从示例中看到在f12的文件信息，文件名已经是数字串了。

一个是想跟作者请教一下这么做是出于什么考虑？
一个是如果想保持原名传递给后台，是否有折衷的处理方式，或者插件有可以利用的配置点？

**Comment by wangfupeng1988** [comment]
有以下原因：
1. 在富文本编辑器的基本使用场景中，使用随机数作为图片名称完全能满足项目要求；
2. 使用文件原名会发生重复上传覆盖的情况；
3. 使用文件原名很可能出现汉字，会有其他意外问题。

目前没有很好的解决方案能在上传时候把文件原名提交上去，你也是第一个提到过这个问题的用户。

能否说明一下为何需要文件原名？绝大多数用户使用富文本上传图片，都不需要原名的。

**Comment by wangfupeng1988** [comment]
其实，有一个简单的解决方案（修改的代码不多）。
第一，我需要在这里加 http://www.kancloud.cn/wangfupeng/wangeditor2/123689 一个`beforeUpload`的hock函数，即可自定义上传之前的一些业务操作。
第二，你再`beforeUpload`函数中，讲图片文件原名设置这里的参数 http://www.kancloud.cn/wangfupeng/wangeditor2/113992

```
    // 配置自定义参数（举例）
    editor.config.uploadParams = {
        token: 'abcdefg',
        user: 'wangfupeng1988'
    };
```

不过这个方法好绕！
