### ISSUE TITLE
关于插入代码<code></code>问题

### ISSUE THREAD

**Issue by zpreed** [wangfupeng1988/wangEditor#405]
我找了一下，好像没发现单纯插入【code】标签的功能。
编辑器中插入代码插入的是【pre】和【code】，这是插入代码段用的，而我只想要一个单词或变量被【code】【/code】标签包裹，例如:
 <code>CSS</code>
而不是<pre><code>CSS</code></pre>
现在好像只能源码模式手动添加。

**Comment by wangfupeng1988** [comment]
明白你的意思了，不过目前编辑器没有这个功能，这个功能是markdown的基本功能，给程序猿用的。普通的富文本编辑器，这个功能用的几乎很少。

**Comment by zpreed** [comment]
考虑加上去吗

**Comment by wangfupeng1988** [comment]
v2.x 版本就先不考虑了，下次升级大版本会加上这个功能，计划年底升级大版本
