### ISSUE TITLE
请教个问题，这个怎么让它优雅得默认选中javascript

### ISSUE THREAD

**Issue by livisky** [wangfupeng1988/wangEditor#406]
![11](https://cloud.githubusercontent.com/assets/11676709/18199954/3120f048-7135-11e6-987e-18275c417528.png)
是否能有一个配置，感谢！

**Comment by wangfupeng1988** [comment]
你先临时修改一下，这里 https://github.com/wangfupeng1988/wangEditor/blob/master/dist/js/wangEditor.js#L5921 ，判断当 `lang`是`'javascript'`时就选中。

我在接下来的升级中，坐上这个配置。到时候在这里回复你。

**Comment by wangfupeng1988** [comment]
下载`v2.1.19`版本，配置文档看这里 http://www.kancloud.cn/wangfupeng/wangeditor2/206179
