### ISSUE TITLE
是否支持jquery3.1.0.min.js

### ISSUE THREAD

**Issue by Loseheartcrazy** [wangfupeng1988/wangEditor#407]
我在使用时被alert 了一个 说我没有jquery 我在用bootstrap所以需要高版本jquery

**Comment by wangfupeng1988** [comment]
目前代码中判断jq是这样判断的 https://github.com/wangfupeng1988/wangEditor/blob/master/dist/js/wangEditor.js#L31

```
    // 验证是否引用jquery
    if (!$ || !$.fn || !$.fn.jquery) {
        alert('在引用wangEditor.js之前，先引用jQuery，否则无法使用 wangEditor');
        return;
    }
```

你可以看一下高版本jq是否符合这个判断？如果不符合、它有什么特点？

这样我可以做一个兼容处理。

**Comment by wangfupeng1988** [comment]
暂时关闭，有问题继续留言
