### ISSUE TITLE
自动在行尾添加<p><br></p>问题

### ISSUE THREAD

**Issue by ycrao** [wangfupeng1988/wangEditor#408]
发现，这个编辑器在编辑时会自动在行尾添加上 `<p><br></p>` 代码，这个可能会造成困扰，因为有些时候，我需要保持碎片代码不变化，如果自动添加会在修改时追加上这一段。希望，作者给予解决，或者新增个配置项。
![image](https://cloud.githubusercontent.com/assets/3280204/18229568/9d7bda9c-72b0-11e6-8576-2015ede14ee6.png)

@wangfupeng1988

**Comment by wangfupeng1988** [comment]
任何操作都要保证内容最后又一个`<p><br></p>`，否则想要再鼠标输入内容时，需要在末尾回车才能输入，这一回车操作可能会导致很多问题，很多人提过`<p><br></p>`的不方便，却不知道去掉`<p><br></p>`之后会带来什么问题。

我不建议在编辑器中去掉`<p><br></p>`，而是你再业务代码中做判断，手动删除掉`<p><br></p>`

**Comment by kzwr** [comment]
我的是直接在后台判断处理文字最后多出来的<p><br></p>

**Comment by ycrao** [comment]
解决办法是有的，但编辑器理应做到内容足够保真，不能随意如此追加字符。
我在首次创建提交，并未带上，后续编辑时也未动过编辑器内容区域，结果更新提交却带上。
