### ISSUE TITLE
txtContainerHeight的作用？

### ISSUE THREAD

**Issue by Trult** [wangfupeng1988/wangEditor#41]
在设置wangEditor-btn-container样式时将width设置为40的时候出现输入框高度只有3px
结果发现是txtContainerHeight的原因...

**Comment by wangfupeng1988** [comment]
你为何要设置 wangEditor-btn-container 的样式？你要先告诉我你的需求，你想要通过自己修改设置什么东西？目前编辑器哪些功能不能满足你？

**Comment by Trult** [comment]
嗯...我的想法是将工具栏竖直排列在一侧

**Comment by wangfupeng1988** [comment]
工具栏竖向排列暂时不支持，而且也不是设置一下高度就可以实现的。
目前我还没有发现哪个地方需要竖向排列，我见过的编辑器区域都是工具栏横向排列。

如果你项目中真的需要竖向排列，可以把需求以及界面的效果图发给我，如果真的很有创意并且易用性非常好，我一定会在升级的时候加上。

**Comment by wangfupeng1988** [comment]
提问者长时间不回复，暂时关闭问题。
有需要在重新提问
