### ISSUE TITLE
关于添加代码阶梯式追加空行的问题

### ISSUE THREAD

**Issue by zhangyd-c** [wangfupeng1988/wangEditor#410]
![aaa](https://cloud.githubusercontent.com/assets/12689082/18301633/97e8e96a-7505-11e6-9de0-30ec74faebc7.gif)
插入代码时如果是单独另起一行进行添加操作是没有问题的，
如果实在某一行的某个地方插入代码，则会自动分行且代码上部追加空行，且插入的代码次数越多，追加的空行就越多。望处理！
操作系统	Windows 7 x64
Google Chrome	52.0.2743.116 (正式版本) m （32 位）

**Comment by wangfupeng1988** [comment]
好，我周末看一下这个问题。

**Comment by wangfupeng1988** [comment]
> 如果实在某一行的某个地方插入代码，则会自动分行且代码上部追加空行

在代码上面插入空行，我记得当时应该是兼容某一款浏览器而做的一个折中处理的兼容方案。虽然上面插入空行稍微麻烦一点，但是也不至于有浏览器兼容性问题。

> 且插入的代码次数越多，追加的空行就越多。

这个问题已经解决，可于明天下载 `v2.1.19`版本
