### ISSUE TITLE
开启只粘贴纯文本时 的一个小bug

### ISSUE THREAD

**Issue by qtnote** [wangfupeng1988/wangEditor#411]
如图：粘贴多个图片会过滤，但一个的时候就没过滤了
![adasdasdas](https://cloud.githubusercontent.com/assets/16409314/18302693/c7fae3e6-750b-11e6-8eb8-dfd1d5dba33b.gif)

**Comment by wangfupeng1988** [comment]
OK 我周末关注一下这个bug，感谢反馈

**Comment by wangfupeng1988** [comment]
看了一下，原因是这样的。当你仅仅选择两个表情图标（没有选择任何文字）再粘贴的时候，其实此时`粘贴纯文本`这个过滤是生效了，而它生效时粘贴的数据是空（因为你复制的仅仅是图片，而没有文字）。

但是，此时又不能阻止浏览器默认行为（这是关键），因为如果阻止了默认行为，那么粘贴上传图片就失效了。因此浏览器自己的默认行为，将两个表情粘贴上了。

这就是原因。

**Comment by qtnote** [comment]
好的👌，感谢



发自我的小米手机在 王福朋 <notifications@github.com>，2016年9月9日 22:37写道：看了一下，原因是这样的。当你仅仅选择两个表情图标（没有选择任何文字）再粘贴的时候，其实此时粘贴纯文本这个过滤是生效了，而它生效时粘贴的数据是空（因为你复制的仅仅是图片，而没有文字）。

但是，此时又不能阻止浏览器默认行为（这是关键），因为如果阻止了默认行为，那么粘贴上传图片就失效了。因此浏览器自己的默认行为，将两个表情粘贴上了。

这就是原因。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/wangfupeng1988/wangEditor","title":"wangfupeng1988/wangEditor","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/wangfupeng1988/wangEditor"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wangfupeng1988 in #411: 看了一下，原因是这样的。当你仅仅选择两个表情图标（没有选择任何文字）再粘贴的时候，其实此时`粘贴纯文本`这个过滤是生效了，而它生效时粘贴的数据是空（因为你复制的仅仅是图片，而没有文字）。\r\n\r\n但是，此时又不能阻止浏览器默认行为（这是关键），因为如果阻止了默认行为，那么粘贴上传图片就失效了。因此浏览器自己的默认行为，将两个表情粘贴上了。\r\n\r\n这就是原因。"}],"action":{"name":"View Issue","url":"https://github.com/wangfupeng1988/wangEditor/issues/411#issuecomment-245932230"}}}
