### ISSUE TITLE
关于上传图片的压缩

### ISSUE THREAD

**Issue by woshihuzios123** [wangfupeng1988/wangEditor#412]
我现在有一个需求就是用户上传的图片，压缩后返回路径，然后我看了一下编辑器是post 文件 到服务器，
而图片压缩插件是 把file 转换后压缩成 base64 字符串，如果我想改成  （ajax或post）提交 base64 字符串，有解决办法吗？
（图片压缩插件是 https://github.com/think2011/localResizeIMG  ）
目前我解决办法是后端压缩，不过挺占用服务器资源的

**Comment by wangfupeng1988** [comment]
感谢提供这么优秀的压缩插件，我平时也一直关注图片压缩的解决方案。不过目前`v2.x`版本还不支持压缩，如果要按照你说的方式，得需要二次开发了。

我计划在下一次大版本升级的时候加上图片压缩，到时候会详细考察验证这个组件。计划年底执行

**Comment by woshihuzios123** [comment]
我主要是是弄后端的， 如果短时间内没有解决办法那我只能先后端压缩了

**Comment by wangfupeng1988** [comment]
先弄个后端解决方案吧，毕竟编辑器这款产品的更新也不会那么快就做这么大一个功能改进

**Comment by orchie** [comment]
@wangfupeng1988 老大快两年了 还搞图片压缩吗
