### ISSUE TITLE
粘贴word内容到wangEditor出现乱码

### ISSUE THREAD

**Issue by agoodfeeling** [wangfupeng1988/wangEditor#413]
从word文档里复制内容（带有回车符）到wangEditor里，会出现乱码.系统：win7，浏览器：搜狗6.2，chrome 50，word：2013

**Comment by wangfupeng1988** [comment]
> 记得说明系统和浏览器的信息，以及word的版本

以上信息也很重要（qq交流时已经强调过）

**Comment by ArcRain** [comment]
我来补充下我出现问题的虚拟机环境吧：
系统：Windows 8.1
浏览器：Chrome
Office版本：2007
Word内容：任意，最后一行保持一个回车符

![image](https://cloud.githubusercontent.com/assets/5145020/18378286/ac39f176-769e-11e6-9a47-9bfba514d978.png)

由最后到最前框选后，右键选复制（不用快捷键），然后左键粘贴到WangEditor的官网，结果如下：
![image](https://cloud.githubusercontent.com/assets/5145020/18378339/018df1b8-769f-11e6-9fb9-5678f24b2e93.png)

**Comment by EdgarDegas** [comment]
同样有这个问题：
Windows 10
Office 2016

**Comment by yuweilan** [comment]
同word文档样式不能保持

**Comment by wangfupeng1988** [comment]
抱歉各位，我的windows环境一直有问题，因此这个bug就落下了。问题我一定会修改！

**Comment by helibin** [comment]
![image](https://cloud.githubusercontent.com/assets/14595752/19424010/4fb0b5c0-9458-11e6-9432-b1b3f71fe790.png)
偶尔会出现这种

**Comment by wangfupeng1988** [comment]
非常抱歉，v2 此后不维护了，已经升级到 v3 版本了，个人业余精力有限，还请体谅。

**Comment by 569061150** [comment]
请问这个乱码的问题 解决了吗？ 正好遇到这个 问题了
