### ISSUE TITLE
回车换行生成p标签的同时生成唯一标识

### ISSUE THREAD

**Issue by HLTwilight** [wangfupeng1988/wangEditor#414]
想获取编辑文档的足迹，为每一个p和p的同级标签加上唯一标识，用时间戳作为id，但每次回车换行都只能复制上一条标签的id而不是重新生成，可以在回车换行生成p标签的同时生成id吗？

**Comment by wangfupeng1988** [comment]
又是一个奇葩需求。这个估计不好配置，因为回车产生<p>标签，不是JavaScript语言控制的，而是浏览器自带的行为。如果按照你的需求，那得阻止浏览器默认行为，自己来写回车方法，那时会遇到很多问题。

不知道你这个需求，到底要满足什么场景？其他使用者没有提到过这个需求

**Comment by HLTwilight** [comment]
一边编辑文档，另一边同步看文档并对文档做相应批注。所以想根据id插入批注，保证无论怎样改动文档，批注与内容始终对应

**Comment by wangfupeng1988** [comment]
你需要的就是每个<p>标签都有一个单独的标记，是吧？

你可以这样：监听回车事件，在事件中遍历所有的<p>，为每个<p>标签增加`data-id`属性。如果下次遍历，有`data-id`的就不要再加了。这样也可以实现你的需求，只不过实现方式上换了一种稍微简单但是性能稍微差一些的做法。但是性能即便是差，我觉得也应该保证用户体验，你可以试一下。

**Comment by HLTwilight** [comment]
那我试试这个办法，非常感谢您的回答

**Comment by wangfupeng1988** [comment]
好。注意考虑一下性能，例如在js的for循环中，这种方式比较耗费性能：

```javascript
var i;
for (i = 0; i < document.getElementsByTagName('p').length; i++) {
    // ....
}
```

而以下方式就会好很多：

```javascript
var i;
var els = document.getElementsByTagName('p');
var length = els.length;
for (i = 0; i < length; i++) {
    // ....
}
```
