### ISSUE TITLE
高度支持自动变化吗

### ISSUE THREAD

**Issue by Geew** [wangfupeng1988/wangEditor#415]
超过高度自动调整高度而不出现滚动条 该设置哪个参数呢

**Comment by wangfupeng1988** [comment]
http://www.kancloud.cn/wangfupeng/wangeditor2/113966

**Comment by kyo-chou** [comment]
自动高度不支持 textarea?

**Comment by zuibunan** [comment]
我试了试还是不支持
http://jsbin.com/fazicazixu/edit?html,output
@wangfupeng1988
