### ISSUE TITLE
建议增加上下标的功能

### ISSUE THREAD

**Issue by zhuxinghan** [wangfupeng1988/wangEditor#417]
可否增加上标/下标的功能？这在输入数学和化学之类的内容时十分重要。

**Comment by wangfupeng1988** [comment]
和数学公式相关的，v2.x的版本不考虑原生添加了，可以通过扩展菜单添加。v3.x升级版本的会加上，v3.x会在年底着手开始做。

**Comment by zhuxinghan** [comment]
其实上下标也不是为了复杂的数学公式，而是一些类似于下划线、删除线之类的常用功能，比如要输入二氧化碳CO2，如果2可以设为下标就很完美了。使用document.execCommand(‘superscript', false, null)和document.execCommand(‘subscript', false, null)即可将选中文字设为上标或下标。

**Comment by wangfupeng1988** [comment]
> 使用document.execCommand(‘superscript', false, null)和document.execCommand(‘subscript', false, null)即可将选中文字设为上标或下标

自己扩展个菜单吧，目前有这种需求的用户还是比较少的。参见 http://www.kancloud.cn/wangfupeng/wangeditor2/115833

**Comment by zhuxinghan** [comment]
多谢，已改好。
