### ISSUE TITLE
微信文章文字图片一起复制粘贴问题

### ISSUE THREAD

**Issue by sweetyluo** [wangfupeng1988/wangEditor#419]
我看到别人提交的issue,说不能实现图片文字一起复制粘贴问题，但是我在http://www.wangeditor.com/ 把文字图片一起复制又可以实现，能看到文字图片，具体真的是不能优化是么？微信文章来源http://mp.weixin.qq.com/s?__biz=MzI0MTAzMTAzMQ==&mid=2650004036&idx=1&sn=b0db13d18c732d985161495ebc91c93b&chksm=f116b85cc661314a102f2905e4905ffd297d8d8063278bf248a521697810e738b44583c1c4e8&scene=1&srcid=09175jWSmT41YSls4vpOJmfH#rd

**Comment by wangfupeng1988** [comment]
> 我看到别人提交的issue,说不能实现图片文字一起复制粘贴问题

那个issue这么说的？编辑器支持文字和图片一起复制粘贴的。官网只要能实现，即表示编辑器就可以实现。

你只要没有关闭粘贴样式的过滤（[文档](http://www.kancloud.cn/wangfupeng/wangeditor2/113984)）、没有开启只粘贴纯文本（[文档](http://www.kancloud.cn/wangfupeng/wangeditor2/156691)）就可以实现文字图片一起粘贴呀？

遇到啥问题了？

**Comment by sweetyluo** [comment]
https://github.com/wangfupeng1988/wangEditor/issues/402

**Comment by sweetyluo** [comment]
https://github.com/wangfupeng1988/wangEditor/issues/402

**Comment by sweetyluo** [comment]
默认的编辑器是没有开启只粘贴纯文本和没有关闭粘贴样式的过滤对吗？我那边复制粘贴后，图片统一变成一个图片，图片写着：此图片来自微信公众平台，未经允许不可引用

**Comment by wangfupeng1988** [comment]
第一，#402 提问的是粘贴上传的问题，它属于图片上传的范畴，如题所说，复制单个图片可以支持上传（某些浏览器不支持），复制多个就不支持上传了，这是确定的

第二，你说的`图片写着：此图片来自微信公众平台，未经允许不可引用`那是因为人家图片防盗链了

**Comment by sweetyluo** [comment]
一篇文章就是多段文字+多个图片的，这样是不支持的对吗？

**Comment by sweetyluo** [comment]
可是同一篇文章却可以在http://www.wangeditor.com/这个网址的编辑器复制粘贴。

**Comment by wangfupeng1988** [comment]
粘贴外链图片和粘贴图片上传，是两个概念，你先弄明白吧。

**Comment by wangfupeng1988** [comment]
暂时关闭，有问题可继续留言

**Comment by comeonbob** [comment]
请问有没有解决防盗链图片的办法？

**Comment by wangfupeng1988** [comment]
> 请问有没有解决防盗链图片的办法？

防盗链是服务器端考虑的事儿，前端解决不了也干预不了，否则人家就防不了了

**Comment by comeonbob** [comment]
@wangfupeng1988 
恩，明白了。
另外补充下， 取巧的实现了图片防盗链问题。
在editor.onchange事件中，
1. 找到所有img
2. 判断img.src来源于微信公众号，src增加前缀http://read.html5.qq.com/image?src=forum&q=5&r=0&imgflag=7&imageUrl=
3. 只增加一次前缀，确实可以显示图片了。
        editor.onchange = function () {
          // 获取编辑区域的所有图片
          var imgs = editor.$txt.find('img')
          // 防盗链方法
          var imgSrcHead = 'http://read.html5.qq.com/image?src=forum&q=5&r=0&imgflag=7&imageUrl='
          // 来自微信
          var imgSrcHeadWC = '://mmbiz.qpic.cn'

          for(let i = 0; i < imgs.length; i++) {
            var imgSrc = imgs[i].src
            console.log('imgSrc', imgSrc)
            console.log('imgSrc.indexOf(imgSrcHeadWC)', imgSrc.indexOf(imgSrcHeadWC))
            // 只增加一次
            if (imgSrc.indexOf(imgSrcHead) === -1 && imgSrc.indexOf(imgSrcHeadWC) !== -1){
              imgs[i].src = imgSrcHead + imgSrc
            }
          }
        }

**Comment by kingbill** [comment]
` //微信图片防盗链
        editor.customConfig.onchange = function () {

// 防盗链方法
var imgSrcHead = http://域名/文件?url=图片地址（含http）'
// 获取编辑区域的所有图片
 var imgs = document.getElementById("editor").getElementsByTagName("img");
            for (var i = 0, l = imgs.length; i < l; i++) {
                imgs[i].src = imgs[i].src.replace("https",imgSrcHead); //img[i].src is the reference to the image. 
            }
  
 }
`
微信图片转换，参考 [https://github.com/44886/imgBridge](url)
