### ISSUE TITLE
支持grunt吗

### ISSUE THREAD

**Issue by chenhuixfyy** [wangfupeng1988/wangEditor#421]
在grunt项目中使用，发现bower.json的main里面只写了js的依赖，css依赖没有写入，导致在构建的时候没有加载css，需要自己额外的去添加css路径

**Comment by wangfupeng1988** [comment]
grunt和bower没有很直接的联系吧？如果你用bower安装的话，css和js都需要你自己去引用啊，它和npm本来就不一样
