### ISSUE TITLE
PC版-上传后的图片底部存在空白间隙

### ISSUE THREAD

**Issue by king-of-the-world** [wangfupeng1988/wangEditor#422]
图片上传后，p标签进行包裹，因为line-height和font-size的影响，图片底部会多余出一条空白的线。想针对图片外层使用div来包裹。还是另有其它好的解决方案

**Comment by king-of-the-world** [comment]
问题终于解决了，这是img标签的3像素问题，参考http://www.jianshu.com/p/1ccaf78bf508
，我在作者源码的6530行`var html = '<img src="' + resultText + '" alt="' + originalName + '" style="max-width:100%"/>';`调整为`var html = '<img src="' + resultText + '" alt="' + originalName + '" style="max-width:100%;vertical-align:top;"/>';`
6604行也做同样的处理：
`var html = '<img src="' + src + '" style="max-width:100%;vertical-align:top;"/>';`
望作者修复这个问题

**Comment by wangfupeng1988** [comment]
OK
