### ISSUE TITLE
angular2使用wangEditor参考

### ISSUE THREAD

**Issue by ghost** [wangfupeng1988/wangEditor#424]
参见：
https://github.com/kaaann/Angular2-directive-wangEditor

**Comment by wangfupeng1988** [comment]
感谢反馈！

**Comment by kaaann** [comment]
更新了使用方式。可以使用npm 安装，再使用。

**Comment by xifengxx** [comment]
上面的链接已无法打开，有其他链接地址吗？

**Comment by wangfupeng1988** [comment]
非常抱歉，v2 此后不维护了，已经升级到 v3 版本了，个人业余精力有限，还请体谅。
