### ISSUE TITLE
是否考虑移除对JQ的依赖？

### ISSUE THREAD

**Issue by erguotou520** [wangfupeng1988/wangEditor#426]
现在很多的MV*框架在开发时都不依赖于JQuery了，所以在引入wangEditor时还依赖于JQuery是有些累赘，所以想问下，是否有不依赖JQ的版本。另外建议模块化开发，不要只在一个js文件中进行开发。

**Comment by wangfupeng1988** [comment]
年底将升级大版本，你说的这些肯定会做，我早就想好了
