### ISSUE TITLE
查看源代码和上传结果

### ISSUE THREAD

**Issue by newday-me** [wangfupeng1988/wangEditor#427]
现在查看源代码的话，没有格式化，也没有行号。
可以考虑以插件的形式，使用codemirror美化一下。

上传文件的话，感觉返回结果是json格式的会好一点吧。

**Comment by wangfupeng1988** [comment]
这些在 v2.x 不会改了，年底升级大版本肯定会做

**Comment by nd888915** [comment]
静候佳音

**Comment by nd888915** [comment]
已经年底了  啥时候有大版本

**Comment by wangfupeng1988** [comment]
@nd888915 哈哈，这段时间忙着照顾孕妇和生孩子，没顾得上，近期即将启动哈。
