### ISSUE TITLE
我在网站引用后，mac端的兼容性问题

### ISSUE THREAD

**Issue by Mingmingmew** [wangfupeng1988/wangEditor#429]
我引用这富文本编辑器后，在Windows上的浏览器都可以正常浏览，但是在mac电脑上的浏览器编辑器会消失，只会留下一个输入文本框。这个是我引用问题，还是这个框架的兼容性问题?

**Comment by wangfupeng1988** [comment]
mac肯定没问题，我日常就是用mac，你再对照文档重新做一遍试试。
