### ISSUE TITLE
全屏时的一个Bug

### ISSUE THREAD

**Issue by liamwang** [wangfupeng1988/wangEditor#43]
![2015-09-19_165015](https://cloud.githubusercontent.com/assets/5000396/9975427/bbe449f0-5eee-11e5-8554-ea5ac6c95124.png)

如图（Chrome浏览器）所示，全屏时滚动条没有达到底部。另外， 为什么不100%全屏呢？当滚动滚轮时，编辑器的滚动条和浏览器的滚动条会同时滚动。

**Comment by wangfupeng1988** [comment]
你好，这的确是一个bug，经查证，这是在增加默认高度和最大高度这个功能时候，忽略了全屏的情况。
我已经改好了，今天晚上会同步到github中。

**Comment by wangfupeng1988** [comment]
全屏滚动条的问题，已经解决。
