### ISSUE TITLE
建议增加的功能

### ISSUE THREAD

**Issue by rowthan** [wangfupeng1988/wangEditor#430]
距离上一次来看已经是半年了 感觉这一次又了质的飞越呀哈哈。我还没有下载看源码 但是体验了下 感觉不错 主要是在图片处理上有了很大的提升：主要是图片尺寸拉升和截图可以直接粘贴在上面，着实方便了很多，以前总是要通过上传图片的方式 还是有点不方便的。

建议增加的功能：
功能一：
 目前截图粘贴图片到编辑器中应该是将图片进行了BLOB二进制处理，能不能增加接口--上传到服务器中，比如七牛云。其中还有一个问题，我在使用上一版本的时候 自己增加了一个上传到七牛云的方法，但是有些问题我还没有解决，
一个是：希望图片放到编辑器中后，图片能够**立即**采用本地的方式马上将图片显示在上面，但是后台还是默默的在上传服务器，当上传服务器结束后 返回一个地址写入编辑器中，然后再提交再随着编辑结束一并post到后台。并且在图片上传服务器的过程中，能够有一个进度条提示，比如通过改变现实在编辑器中的本地图片的不透明度来表现等。感觉这个功能有点麻烦 有听过异步处理 我之前一直都没有做好。

功能二：
在菜单栏上方或者左右两侧 增加一些按钮块 点击可以直接在编辑器中 增加一些样式 如标题样式框 图片样式框 段落样式框等一些内置好的样式供用户选择。
这部分功能可以作为一个独立功能块引入到wangEditor.js ，即开发者需要就引入该js 不需要就不用引入，这样就可以 供用户自行选择。

功能三：
我记得在以前的版本中，选中编辑器中的文字，即会在下方出现加粗、颜色、斜体等功能按钮，貌似在最新版本中没有了该功能？感觉比较遗憾。

功能四：
编辑框的区域能够设置为可拉伸？目前编辑区的大小是不可改变的（除了全屏），在编辑的时候有点不方便，希望能够在垂直方向上可以拉升，这样看效果也比较好一点。

**Comment by wangfupeng1988** [comment]
> 功能一

现在编辑器支持上传到七牛云 http://www.kancloud.cn/wangfupeng/wangeditor2/123691
你提到的这个先显示本地再上传的这种方式，我觉得非常好，年底就要计划升级大版本了，我会加上这个易用性的体验。

> 功能二

是不是类似[135编辑器](http://www.135editor.com/)左侧的样式区域这种的功能？之前没有关注，现在发现这个东西简直非常好用，特别符合当前的互联网思维。这个一定要集成，而且是像你说的插件式集成

> 功能三

这个也可以作为插件或者可配置的功能加上

> 功能四

上下拉伸，这个可以有

**Comment by rowthan** [comment]
希望行高能够调整 默认行高感觉有点过高。
在保证编辑器区域纵向可调节的前提下 注意要限制不允许横向调节哦，很多编辑器有时候会忽略这一点。

> 有一点使用上的改进建议

对于文字加粗加斜体等等一系列的文本操作，都存在一些诟病：我这个文字需要**加粗**，而后面的文字并不需要加粗。而目前你编辑器的做法是 一旦我点击了加粗 那么就意味着
&lt;b&gt;文字 光标&lt;b&gt;都在B标签内部，这就导致我后面的输入必须要手动的去清除加粗。其实这个问题也不算什么问题，只是个人习惯不同吧 有人习惯先定义再输入，有人习惯先输入在修改样式。主要到这个问题，主要是在这里用github编辑器的时候 发现它做得不同，大致分析了下 它是通过空格来分析是否为一个部分的--文字间存在空格则样式不会相互影响 **我加粗了不影响前后**。 我就发现了这个问题想跟你说下，其实改不改够无所谓的。

顺便再说一个小功能 这个不涉及到编辑器本身 算是一个额外的需求了：其实就是自己使用时候的私心了
demo演示中 增加一个异步加载wangEditor.js、wangEditor.css、font文件的按钮： 如果用户并不想留言 那么加载这些js\css font无疑是浪费资源 特别是在手机端中更能体现。
现在有些网站的做法就是 当用户click textare后才会加载这些js css来绘制出富文本的效果。

最后，期待新版本出来，我继续给你提建议哈~~~orz~

**Comment by wangfupeng1988** [comment]
> 当用户click textare后才会加载这些js css来绘制出富文本的效果

这个值得考虑加上

**Comment by wangfupeng1988** [comment]
这些建议我已经记录下，问题暂时关闭，不影响继续留言。

**Comment by chengma** [comment]
图片上传，文档里，我没有看到有对图片大小的限制，强烈建议加上！太大的图片影响速度。

**Comment by wangfupeng1988** [comment]
@chengma 

> 图片上传，文档里，我没有看到有对图片大小的限制，强烈建议加上！太大的图片影响速度。

即将规划的升级，会加上这个限制，感谢反馈
