### ISSUE TITLE
上传图片到后端提示跨域的问题

### ISSUE THREAD

**Issue by yinxueUser** [wangfupeng1988/wangEditor#431]
按照前端配置的说明，除了header以外都配置了， 可是在发给服务器的时候还是提示跨域的问题，服务器的设置也都进行了设置

**Comment by lihsai0** [comment]
昨晚，也遇到类似问题
你仔细看看错误提示
我这边是后端跨域许可写了 * 通配符

但是在wangEditor中的`editor.xhrUploadImg`写了这么一句：
``` javascript
// 跨域上传时，传cookie
            xhr.withCredentials = true;
```
跨域错误提示写的很清楚当`Credentials = true;`时 不能使用 * 统配符

**Comment by wangfupeng1988** [comment]
@yinxueUser 你去试试 @lihsai0 的方法，如果有问题再继续留言

**Comment by wangfupeng1988** [comment]
问题暂时关闭，不影响继续留言

**Comment by nomran** [comment]
？？？这不是解决方法啊 我也遇到了 还是不行，cors都设成*了还是不可以
