### ISSUE TITLE
作者威武，很好用，但最关注的表格不能拖拽，忍痛割爱，请升级。

### ISSUE THREAD

**Issue by yuyuntec** [wangfupeng1988/wangEditor#433]
许多内容是从word中粘贴来，用到table

**Comment by yuyuntec** [comment]
希望能加强table的功能。

**Comment by wangfupeng1988** [comment]
计划年底的大版本升级时再对table的处理。不过，编辑器本身还是以基本功能为主，像处理table的这些复杂功能，会通过扩展插件的形式来实现。

**Comment by IVANLEE99** [comment]
2017年底已过，table插件进展如何？
