### ISSUE TITLE
关于菜单栏增加分割线，图片加阴影等功能，另外清除格式功能

### ISSUE THREAD

**Issue by sweetyluo** [wangfupeng1988/wangEditor#434]
菜单框那里如果要加上分割线或者图片加阴影的图标按钮的话，我可以自定义菜单吗？如135编辑器一样，清除格式能不能全部文本一起清除格式，但段落还是在那里

**Comment by wangfupeng1988** [comment]
> 菜单框那里如果要加上分割线或者图片加阴影的图标按钮的话，我可以自定义菜单吗？

菜单框中本来就有分割线，而且分割线的位置也可以自定义，去看文档。“图片加阴影的图标按钮”这个得需要自定义菜单了，文档中也有。

> 清除格式能不能全部文本一起清除格式，但段落还是在那里

目前编辑器中，你选中多段文字，点击“清除格式”按钮，就是“全部文本一起清除格式，但段落还是在那里”啊？有什么问题吗？

----

提问的时候最好举个例子，你第二个问题我就没看明白。

**Comment by sweetyluo** [comment]
1.同时复制很多段的时候，清除格式时，并不能全选所有文本清格式，必须一段一段清格式。
2.我说的分隔线是指段与段之间用一条横线分开来的分隔线功能键，如http://www.135editor.com/
![u zp9h6 jrynj6yx3m_ 4 2](https://cloud.githubusercontent.com/assets/22252654/19217003/0ffbd516-8e06-11e6-87cc-3c97eb9b7c1e.png)
3.图片加阴影，我把文档看了都没有看到才过来问你的，具体在哪里可以给对应链接吗？

**Comment by wangfupeng1988** [comment]
了解了。

第一，清除样式的问题，到v3版本再升级，年底就开始做了。v2版本尽量保证当前功能的稳定
第二，分割线和图片阴影，都需要你自己扩展菜单，参见 http://www.kancloud.cn/wangfupeng/wangeditor2/113997

**Comment by sweetyluo** [comment]
好的，谢谢。请问编辑器里存在13.5的字号码？发布出去没有对应的样式

**Comment by wangfupeng1988** [comment]
13.5字号自己去配置，看文档
