### ISSUE TITLE
编辑完内容保存以后再编辑 光标为什么会自动跑前面？

### ISSUE THREAD

**Issue by conquer123** [wangfupeng1988/wangEditor#436]
编辑完内容保存以后在编辑 光标为什么会自动跑前面？ 如何实现光标始终在最后面？求方案。感谢

**Comment by ztkIsAlreadyTaken** [comment]
找到最后一个p元素，设置可编辑属性，然后p.focus(),,,,,,,,,,,应该可以吧，，

**Comment by wangfupeng1988** [comment]
> 找到最后一个p元素，设置可编辑属性，然后p.focus(),,,,,,,,,,,应该可以吧，，

@ztkIsAlreadyTaken 我觉得这样是不行的，对`<p>`进行 focus 没用的


@conquer123 能具体说一下`编辑完内容保存以后在编辑`这个的过程吗？即接下来的光标是和操作触发而出现的？

**Comment by conquer123** [comment]
p.focus(),那个不行；  就是我编辑一篇内容 然后保存再重新编辑，一进页面的时候的光标想让在最后，但是现在是一进页面在最前面。

**Comment by wangfupeng1988** [comment]
> 一进页面的时候的光标想让在最后，但是现在是一进页面在最前面

官网demo一进页面就是光标在后面啊。

你得告诉我怎么让我复现问题，你说的“保存在重新编辑”我这里没有保存功能，我也不知道你的“保存再重新编辑”是一个什么场景。

抛开一切相关因素，以最直接有效的方式复现问题，该怎么复现？

**Comment by conquer123** [comment]
官网的demo是因为编辑器里面没有内容 ；就是一个简单添加一篇文章的功能。保存到数据库里面；然后在编辑这篇文章的时候光标自动跑到了最前面；

**Comment by wangfupeng1988** [comment]
> 官网的demo是因为编辑器里面没有内容

官网demo编辑器是有内容的，虽然只有一句话。

> 然后在编辑这篇文章的时候光标自动跑到了最前面；

编辑这篇文章的时候，你是如何让文章内容显示到编辑器中的？是js方式还是html方式？你用一个静态的html，将一些静态文字放到编辑器中，模拟一下这个编辑页面，看能否复现问题？如果能复现告诉我就好了。

将复现问题缩小到一个静态页面中，而不是给我说一个系统还有数据库这么大的一个环境中。

**Comment by conquer123** [comment]
就是js方式，请求接口 然后让div的内容等于接口返回的某个字段的内容

**Comment by wangfupeng1988** [comment]
试试 http://www.kancloud.cn/wangfupeng/wangeditor2/115831 里面的**`editor.restoreSelectionByElem`**（其中第二个参数的说明：`'start'-折叠到开始，'end'-折叠到结束，'all'-全部选中`）

你用异步的方式来赋值，页面加载完了之后，编辑器先执行 focus，然后js再去请求接口数据，请求数据回来之后再赋值，当然光标还是在前面。你在请求的callback中，赋值了内容之后再上面说的方法手动设置选取，试试。

**Comment by conquer123** [comment]
方法并不行
...

**Comment by wangfupeng1988** [comment]
你可以试试在 ajax 的 callback 中获取了内容之后，再去执行`editor.create()`创建编辑器。而不是创建完了编辑器之后，再用 ajax 异步获取数据。这个你试一下吧。其他方法我暂时想不到了。

**Comment by sfq1110660201** [comment]
我是在vue环境下遇到了这个问题，页面返回图文数据通过v-html绑定后也出现了光标跑前的bug，最后用jq html()方法解决了editor.$txt.html(res)

**Comment by wangfupeng1988** [comment]
建议升级 v3 版本，v2版本由于个人业余精力有限不再升级。
