### ISSUE TITLE
关于编辑器点击一下html模式 然后输入内容如果不恢复为普通模式的bug

### ISSUE THREAD

**Issue by Geniusssssss** [wangfupeng1988/wangEditor#437]
大致讲下 老王你自己试下就知道了 我在群里说了的 艾特你了 
在正常模式下输入一句话 使用editor.$txt.html()可以得到全部的html代码
但是在html下键入之后不恢复到正常模式 editor.$txt.html()获取不到在html模式下输入的内容 除非再次恢复正常模式才可以获得
附几张截图
顺便 能某考虑下html模式下的代码格式化呢。。现在的html下代码挤在一起 完全看不了- -
![qq 20161009175508](https://cloud.githubusercontent.com/assets/16536678/19219593/d5ad77cc-8e49-11e6-8f88-7a1a2661b9a7.png)
![vj7d2 ep 1axui9g w0xub](https://cloud.githubusercontent.com/assets/16536678/19219590/c3402544-8e49-11e6-9957-dfa76f5ef037.png)
![_ 3q o p3r n0 fe6nc 7](https://cloud.githubusercontent.com/assets/16536678/19219596/e24353da-8e49-11e6-9186-bbd41ec861e3.png)

**Comment by wangfupeng1988** [comment]
看到这个bug了，我会尽快处理一下

**Comment by wangfupeng1988** [comment]
已修复，今晚更新。
