### ISSUE TITLE
上传图片后，返回的地址为线上图片服务器的地址，js调试显示错误，目测是把返回地址认为相对路径

### ISSUE THREAD

**Issue by xu509** [wangfupeng1988/wangEditor#438]
您好，我上传图片后，返回一个图片的线上地址，如图：
![bug](https://cloud.githubusercontent.com/assets/7601340/19219904/ec540b40-8e52-11e6-9adb-e543bde045e1.png)
请问如何只使用返回的路径？

**Comment by wangfupeng1988** [comment]
> 返回的地址为线上图片服务器的地址

问题在于返回的地址外面有两个引号，你去掉引号试试行吗
