### ISSUE TITLE
Firefox 浏览器 下加粗粘贴过来的文本 会从加粗文字的头个字断开自动换行

### ISSUE THREAD

**Issue by kzwr** [wangfupeng1988/wangEditor#439]
个别会出现这个情况

**Comment by wangfupeng1988** [comment]
firefox 意外情况遇到的比较多，算是有点小奇葩吧。你把详细复现场景告诉我，我去试试吧，看好解决的话，就搞定它。不好解决就慢慢啃吧。

**Comment by helibin** [comment]
firefox下有点兼容性问题，文字居中后p标签加的是align="center"，这属性已经弃用了，，chrome下就会加style="text-align:center"

**Comment by wangfupeng1988** [comment]
我记录下了，大版本升级时注意多测试这里，v2.x新这样吧，目前以维护着稳定为主
