### ISSUE TITLE
关于位置的功能

### ISSUE THREAD

**Issue by IceMapleDancer** [wangfupeng1988/wangEditor#44]
当页面有一个富文本框的时候，功能是可以的。当页面有两个富文本框的时候，第一个的位置功能不好用，地图一直加载中，第二个是可以的。
当页面采用https协议的时候，地图都是加载中。
![default](https://cloud.githubusercontent.com/assets/14679127/10009374/548f1b28-610e-11e5-9b0f-72ed7b177976.PNG)

**Comment by wangfupeng1988** [comment]
这个问题其实我早就知道，之所以没有花时间研究。是因为：
1. 近期大家提出的需求都比较多，我也需要及时更新反馈
2. 有一些更加急迫的需求
3. 一个页面用多个富文本编辑器的时候，应该很少吧，所以优先级比较低。

你可以想大家分享一下，你是怎样的一个需求，需要一个页面多个富文本编辑器。如果确实急需，我会尽快修正这个问题。

**Comment by liaohui1080** [comment]
图标无法显示出来

**Comment by wangfupeng1988** [comment]
@liaohui1080 
第一，群公告中写了，不回答『一句话问题』。你这一句话，我不明白你的问题是什么，请按照群公告中的规定提交问题。
第二，你所说的问题和题目中提到的问题是否是一个问题？如果不是一个问题，请另起一个问题，要不就乱套了。

**Comment by wangfupeng1988** [comment]
@IceMapleDancer 你好，这个问题好久了，直到现在wangEditor2.x.x 都发布了，但是你提出来的这个位置的问题，还是没有很好的解决方案。因此，在目前的版本中，不支持在多个编辑器中同时使用位置菜单，如果使用了，浏览器的控制台会有错误提示的。

目前这也是一个无奈之举，只能先这样。如果找到问题原因，我一定会再次支持。
