### ISSUE TITLE
有序列表和无序列表无法设置列表项的行高

### ISSUE THREAD

**Issue by coix** [wangfupeng1988/wangEditor#442]
![qq 20161010144132](https://cloud.githubusercontent.com/assets/9411680/19228423/adb2271e-8ef7-11e6-8f3c-0219d43cca5e.png)
如图所示，当编辑内容选择列表时，无法设置列表项的行高。

**Comment by wangfupeng1988** [comment]
v2.x 版本编辑格式用的是浏览器原生的`document.execCommand`命令，不同浏览器的情况不一样，这个问题应该跟`document.execCommand`命令有关，v2.x版本不会再修改这块核心内容。
