### ISSUE TITLE
点击菜单栏按钮默认向下弹出，能否改成向上弹出？

### ISSUE THREAD

**Issue by hyf101070** [wangfupeng1988/wangEditor#446]
![image](https://cloud.githubusercontent.com/assets/6482094/19354534/a5184e22-9199-11e6-82bb-81b90ebe0c74.png)
默认是向下弹出的，有办法改成向上弹出吗？

**Comment by wangfupeng1988** [comment]
这个暂时不行，PC端的滚动还是以上下为主，左右滚动在手机端比较多。

**Comment by hyf101070** [comment]
额，我是指弹出框的方向改成向上方弹出，因为现在的弹出方式是向下方弹出的，这样如果编辑框处于底部的话页面有可能会出现滚动条

**Comment by hyf101070** [comment]
@wangfupeng1988

**Comment by wangfupeng1988** [comment]
哦 我看错了，不好意思哈。

你说的向上弹出，目前不支持。目前提出这个建议的应该就你一个人，绝大部分用户都没有这个问题，因此以后也不会修改。

> 这样如果编辑框处于底部的话页面有可能会出现滚动条

对于这个问题，我记录下，在大版本升级时候用其他方式来处理。

**Comment by hyf101070** [comment]
了解， 麻烦你了
