### ISSUE TITLE
在ie浏览器上，会报css3111:@font-face 遇到了未知错误

### ISSUE THREAD

**Issue by cbbaaa1989** [wangfupeng1988/wangEditor#447]
在ie浏览器上，会报css3111:@font-face 遇到了未知错误,
导致菜单加载不出来

**Comment by wangfupeng1988** [comment]
IE哪个版本？哪个系统？

**Comment by cbbaaa1989** [comment]
windows系统，用的是360兼容模式，ie11

**Comment by wangfupeng1988** [comment]
最近我的windows环境有点问题，等我弄好了尽早看看。

**Comment by wangfupeng1988** [comment]
非常抱歉，v2 此后不维护了，已经升级到 v3 版本了，个人业余精力有限，还请体谅。
