### ISSUE TITLE
destroy疑问

### ISSUE THREAD

**Issue by lihongkun** [wangfupeng1988/wangEditor#448]
destroy只是隐藏 ,是不是应该有个方法可以直接销毁编辑器.
如果在单页应用里面需要反复使用,但是对象没有销毁不是很消耗内存.

**Comment by wangfupeng1988** [comment]
目前还没有完全销毁的API，因为 destory 也是后来才补充的一个 API。针对单页面应用目前确实是一个问题，v2.x版本不计划再做大的改动，稳定为主。年底大版本升级，支持SPA是一个重要目标之一。
