### ISSUE TITLE
代码插入问题

### ISSUE THREAD

**Issue by Jframeye** [wangfupeng1988/wangEditor#45]
其实也不是很大的问题，就是感觉体验不好。

使用代码插入功能插入代码后，如果再次修改已插入的代码，换行的话，会将本来一体的代码分割开来，视觉上感觉不好，会让人认为这是两段代码（其实是一起的）

**Comment by liamwang** [comment]
可以通过 Shift + Enter 解决此问题

**Comment by wangfupeng1988** [comment]
这个没办法，除非你使用wangEditor的高亮代码。你看看文档，很简单的。使用了高亮代码，你这个问题就被解决了
