### ISSUE TITLE
如何将插入的图片另起一行

### ISSUE THREAD

**Issue by coolie1** [wangfupeng1988/wangEditor#450]
在文字中插入图片，默认是插入在文字中间，希望能图片另起一行。
wangEditor.js中插入图片的html原代码为：
![image](https://cloud.githubusercontent.com/assets/15683896/19470013/75e55b80-9550-11e6-996c-dd918981713e.png)
修改为：
![image](https://cloud.githubusercontent.com/assets/15683896/19470028/88cb057e-9550-11e6-9a85-f022edbec220.png)

但似乎结果添加的p标签都没有了。

请问，应该如何做？

**Comment by wangfupeng1988** [comment]
为`<img />`标签加上`display:block`试试

**Comment by wangfupeng1988** [comment]
暂时关闭，可继续留言

**Comment by coolie1** [comment]
谢谢，已经完美解决。
