### ISSUE TITLE
npm 安装问题

### ISSUE THREAD

**Issue by lzxb** [wangfupeng1988/wangEditor#452]
我的项目已经使用npm安装了jq 3.x，可是wangEditor的jq版本是2.x，
看了一下源码要设置wangEditorJQueryPath才能引入自定义的jq版本，这个地方感觉有点多余了，一不小心就打包了两个jq版本进去

**Comment by wangfupeng1988** [comment]
那你项目中用 3.x 而编辑器用 2.x，肯定需要两个jquery。目前编辑器 v2.x 版本不打算再做一些大的升级，保证稳定，接下来的大版本升级，将去掉对jquery的依赖。

**Comment by lzxb** [comment]
我现在修改了一些代码，不知道能不能顺利使用jq 3.x ，如果实在没办法，只能降级和你的编辑器同一个版本了

**Comment by wangfupeng1988** [comment]
恩。没看过 jq v3.x，它都有什么特点吸引了你来用？

**Comment by lzxb** [comment]
没什么，只是因为不需要考虑ie，所以直接用最新的好了

**Comment by wangfupeng1988** [comment]
OK
