### ISSUE TITLE
点击上传图片时限制最多上传5张图片，请问哪个api可以做。

### ISSUE THREAD

**Issue by skyroom** [wangfupeng1988/wangEditor#453]
文档中只有editor.config.uploadImgUrl = '/upload';editor.config.uploadParams = {
        token: 'abcdefg',
        user: 'wangfupeng1988'
    };editor.config.uploadHeaders = {
        'Accept' : 'text/x-json'
    };这几个api，

**Comment by wangfupeng1988** [comment]
目前没有限制上传图片数量的配置，你可以先自己从这里 https://github.com/wangfupeng1988/wangEditor/blob/master/dist/js/wangEditor.js#L6936 判断，判断数量大于5就终端程序，加一个 alert。

我记录下了这个问题，升级的时候加上。

**Comment by skyroom** [comment]
@wangfupeng1988    看到，好的。谢谢。
