### ISSUE TITLE
对内容的操作问题，第2次点击菜单，会把之前的内容改变？

### ISSUE THREAD

**Issue by leifeng** [wangfupeng1988/wangEditor#454]
在官网例子中也有这问题。
1.先随便输入一些内容
2.鼠标全选，然后点击加粗
3.继续输入内容（这个时候追加的文字也是加粗的）
4.（重点：这个时候我后续的内容不想加粗了）再次点击加粗，然后之前加粗的内容都被取消了。

我试了一下Simditor 、ueditor 和 kindeditor 同样上面的操作，是不会出现第4步的问题的。

**Comment by wangfupeng1988** [comment]
看到了，这是一个bug。

不过，v2.x的取消加粗的方式是：先选中一部分加粗的文字，然后点击“加粗”按钮

**Comment by wangfupeng1988** [comment]
非常抱歉，v2 此后不维护了，已经升级到 v3 版本了，个人业余精力有限，还请体谅。
