### ISSUE TITLE
图片上传的问题

### ISSUE THREAD

**Issue by coco9527** [wangfupeng1988/wangEditor#455]
请问一下，为什么点击上传图片后选择图片的调起会非常慢

**Comment by wangfupeng1988** [comment]
你是哪个系统、哪个浏览器？
我在 mac 下，试着 chrome 打开比较慢，其他浏览器还好。

**Comment by coco9527** [comment]
Windows下的chrome

**Comment by coco9527** [comment]
Windows下的chrome

**Comment by wangfupeng1988** [comment]
我的windows环境出了点问题，正在维修，修好我一起看看

**Comment by wangfupeng1988** [comment]
今晚就看看 @Leavesye

**Comment by wangfupeng1988** [comment]
非常抱歉，v2 此后不维护了，已经升级到 v3 版本了，个人业余精力有限，还请体谅。

v3 目前没有发现这个问题。
