### ISSUE TITLE
谷歌浏览器和360浏览器图片复制粘贴兼容问题

### ISSUE THREAD

**Issue by xiaoyu1987** [wangfupeng1988/wangEditor#456]
电脑上通过鼠标右键或者ctrl+v复制一张图片到无法通过粘贴或者ctrl+c粘贴到编辑器中，火狐是支持的，其他浏览器不兼容

**Comment by xiaoyu1987** [comment]
上传图片没有限制格式类型，如gif，jpg等等，其他类型格式上传前段应该限制住校验，没有此功能配置项

**Comment by wangfupeng1988** [comment]
粘贴图片这块，本来就浏览器兼容性不好，IE、safari都有兼容性问题，这很正常。而且不好解决，例如qq邮箱需要在safari下安装插件才能支持粘贴图片。
