### ISSUE TITLE
图片上传控件没有限制不匹配类型

### ISSUE THREAD

**Issue by xiaoyu1987** [wangfupeng1988/wangEditor#457]
如果上传非图片格式，应该前段直接校验返回错误弹出提示，比如加个配置项，限制上传图片后缀类型，还有是否有办法做到前段上传图片大小限制的配置项。后端我已经做了控制

**Comment by wangfupeng1988** [comment]
类型目前未做限制，但是支持html5的浏览器会默认过滤图片，其他浏览器不行。
图片大小的限制，目前也没有加，可后端做限制，也可用集成 plupload 来实现这个功能。

这俩需求我已经记录下，年底大版本升级加上，v2.x先不加了，先保证稳定

**Comment by lanxkk** [comment]
关于限制上传图片后缀类型和大小，你可以修改编辑器的源代码来实现，找到这一行：
$.each(files, function(key, value) {
在下面加上相应的代码即可。

注：
上传文件大小：value.size
上传文件类型：value.type

**Comment by wangfupeng1988** [comment]
非常抱歉，v2 此后不维护了，已经升级到 v3 版本了，个人业余精力有限，还请体谅。

v3 中显示了`size`，`type`还是用 html5 本身的过滤方式
