### ISSUE TITLE
关于txt-img-toolbar的自定义

### ISSUE THREAD

**Issue by datoulei** [wangfupeng1988/wangEditor#459]
业务上有需求对img-toolbar重新定义，希望能提供toolbar的开关配置

**Comment by wangfupeng1988** [comment]
`img-toolbar`就是一个我自己写的编辑器插件，没有开关配置。你如果要冲定义，就参照源码再自己写一份插件吧。插件的说明文档中有。

**Comment by wangfupeng1988** [comment]
暂时关闭，可继续留言
