### ISSUE TITLE
输入文字 光标会一直显示在左边 vue.js

### ISSUE THREAD

**Issue by dtchris** [wangfupeng1988/wangEditor#460]
版本 "wangeditor": "^2.1.21", 我输入1234 会显示4321.

**Comment by wangfupeng1988** [comment]
不受理“一句话问题”，请描述清楚。
另外，文档中有几成到vue的简单示例，可去参考。

**Comment by HarryQQ** [comment]
主要是因为 @jiangyoucai 的vue组件中
`<div id="editor" v-html="inputContent" @input="outputContent"></div>`
inputContent这个属性动态变的话，每变一次，光标都会自动跳到开始的位置。
我之前用vuex管理状态，也遇到过这个问题。
我自己的解决办法是在这个组件里加个监听器，v-html只绑定初始值
`watch: {
      inputContent: function (val, oldVal) {
        if (val && !oldVal) {
          this.initContent = val
        }
      }
    },`
`<div id="editor" v-html="initContent" @input="outputContent"></div>`

**Comment by lzxb** [comment]
我也遇到了这个问题，解决方案是修改了，2431行：https://github.com/wangfupeng1988/wangEditor/blob/master/src/js/wangEditor.js

```javascript
resultHtml = '<p>' + resultHtml + '</p>'; //修改前
resultHtml = pasteHtml; //修改后
```

**Comment by lzxb** [comment]
主要表现是在火狐浏览器下，粘贴文本，自动添加 了p标签，导致纯文本粘贴的时候，光标自动换到下一行。谷歌浏览器没有这个问题

**Comment by wangfupeng1988** [comment]
感谢各位的反馈！
