### ISSUE TITLE
还用过时的标签。。。

### ISSUE THREAD

**Issue by hasbug** [wangfupeng1988/wangEditor#463]
类似这种，还有其他，都被抛弃的了。< f ont color="#ff0000" >font标签< /font > 在手机端不一定能有效果。

**Comment by wangfupeng1988** [comment]
`< f ont color="#ff0000" >font标签< /font > `这是浏览器的`document.execCommand`执行的结果，不是我手动写的。我会在下一次大版本升级的时候关注这一点。

**Comment by wangfupeng1988** [comment]
欢迎跟新 v3 版本，v3 已经发布一段时间了
