### ISSUE TITLE
粘贴时自动添加额外的p标签

### ISSUE THREAD

**Issue by xdsnet** [wangfupeng1988/wangEditor#464]
任何情况下的粘贴都会对内容外面包含额外的p标签和多余的br标签

**Comment by wangfupeng1988** [comment]
我用chrome浏览器，复制了你写的`任何情况下的粘贴都会对内容外面包含额外的p标签和多余的br标签`然后打开官网粘贴，就没有出现p标签和br标签啊，你的复现场景是什么？

**Comment by FakeMr** [comment]
插入图片就会在后面追加P标签，这个不止黏贴外面内容

**Comment by wangfupeng1988** [comment]
非常抱歉，v2 此后不维护了，已经升级到 v3 版本了，个人业余精力有限，还请体谅。
