### ISSUE TITLE
图片上传弹出框问题

### ISSUE THREAD

**Issue by hjjoe1213123** [wangfupeng1988/wangEditor#465]
环境：jquery 2.1.4 + bootstrap 3.3.6

点击上传按钮，不弹出文件选择框：
![image](https://cloud.githubusercontent.com/assets/13696132/19721178/c121fd2a-9ba3-11e6-8481-75d663f87a7d.png)

代码如下：
function uploadInit () {
        // this 即 editor 对象
        var editor = this;
        // 编辑器中，触发选择图片的按钮的id
        var btnId = editor.customUploadBtnId;
        // 编辑器中，触发选择图片的按钮的父元素的id
        var containerId = editor.customUploadContainerId;

```
    //实例化一个上传对象
    var uploader = WebUploader.create({
        auto : true,
        swf : "Uploader.swf",
        server : MNG_DOMAIN + "/product/v1/upload.do",
        pick : "#filePicker",
        accept : {
            title : "Images",
            extensions : "gif,jpg,jpeg,bmp,png",
            mimeTypes : "image/*"
        },
        compress : {
            maxwidth : 1242,
            quality : 70
        },
        fileNumLimit : 1,
        fileSizeLimit : 50 * 1024 * 1024,
        fileSingleSizeLimit : 20 * 1024 * 1024
    });

    uploader.on("fileQueued", function(file) {
        console.log("fileQueued:"+file);
    });
    uploader.on("uploadProgress", function(file, percentage) {
        console.log("uploadProgress:"+percentage);
    });
    uploader.on("uploadSuccess", function(file, response) {
        console.log("uploadSuccess:"+response);
    });
    uploader.on("uploadError", function(file, response) {
        console.log("uploadError:"+response);
    });
    uploader.on("uploadComplete", function(file) {
        console.log("uploadComplete:"+file);
    })
}

var editor = new wangEditor('prdDesc');

// 隐藏掉插入网络图片功能。该配置，只有在你正确配置了图片上传功能之后才可用。
editor.config.hideLinkImg = true;
editor.config.customUpload = true;
editor.config.customUploadInit = uploadInit;
editor.create();
```

**Comment by wangfupeng1988** [comment]
解决了重新下载 js 更新一下 https://github.com/wangfupeng1988/wangEditor/releases/tag/v2.1.22

**Comment by hjjoe1213123** [comment]
@wangfupeng1988 
又测试出一个新问题，还是用的百度的WebUploader，代码如下：
   // 配置上传
    function uploadInit () {
        var editor = this;
        var btnId = editor.customUploadBtnId;
        var containerId = editor.customUploadContainerId;

        //实例化一个上传对象
        var uploader = WebUploader.create({
            auto : true,
            swf : "Uploader.swf",
            server : MNG_DOMAIN + "/product/v1/upload.do",
            pick : '#'+containerId,
            accept : {
                title : "Images",
                extensions : "gif,jpg,jpeg,bmp,png",
                mimeTypes : "image/*"
            },
            compress : {
                maxwidth : 1242,
                quality : 70
            },
            fileNumLimit : 1,
            fileSizeLimit : 50 * 1024 * 1024,
            fileSingleSizeLimit : 20 * 1024 * 1024
        });
        
        uploader.on("fileQueued", function(file) {
            console.log("fileQueued:"+file.name);
        });
        uploader.on("uploadProgress", function(file, percentage) {
            console.log("uploadProgress:"+percentage);
            // 显示进度条
            editor.showUploadProgress(percentage);
        });
        uploader.on("uploadSuccess", function(file, response) {
            console.log("uploadSuccess:"+response.imageMd5);
            // 隐藏进度条
            editor.hideUploadProgress();
            var value = global.httpPath+"/imgdownload/"+response.imageMd5
            // 插入到编辑器中
            editor.command(null, 'insertHtml', '<img src="' + value + '" style="max-width:100%;"/>');
        });
        uploader.on("uploadError", function(file, response) {
            console.log("uploadError:"+response);
        });
        uploader.on("uploadComplete", function(file) {
            console.log("uploadComplete:"+file);
        });
    }

    // 创建编辑器
    var editor = new wangEditor('prdDesc');
    editor.config.hideLinkImg = true;  // 隐藏网络上传
    editor.config.customUpload = true;  // 配置自定义上传
    editor.config.customUploadInit = uploadInit;  // 配置上传事件
    editor.create();

上传第一张图片可以，再次上传图片则事件不响应了，图片也不上传，debug也不进入了

**Comment by wangfupeng1988** [comment]
非常抱歉，v2 此后不维护了，已经升级到 v3 版本了，个人业余精力有限，还请体谅。
