### ISSUE TITLE
服务器增加nginx后，图片上传请求被拦截了

### ISSUE THREAD

**Issue by lwj0216** [wangfupeng1988/wangEditor#466]
你好，我在使用过程当中，服务器端在没有配置nginx之前图片上传是正常的，但是增加了nginx后，图片上传请求就超时了，后台没有接收到前端的图片上传请求，应该是被nginx拦截了，请问在wangEditor里需要设置什么上传配置项吗？灰常感谢！

**Comment by wangfupeng1988** [comment]
nginx的问题你得去nginx那里分析，你只要看到前端将http请求正确的发出去了，剩下的就是去server端排查

**Comment by lwj0216** [comment]
确实是服务端的问题，有一个地方没有配置好，我的疏忽，感谢感谢。
