### ISSUE TITLE
插入文本的时候，如果文本中有HTML标签，会有问题

### ISSUE THREAD

**Issue by wangsuiche** [wangfupeng1988/wangEditor#468]
editor.config.pasteText设置为true，然后粘贴以下文本，就会出现粘贴不全的情况。需要对HTML标签做转码，因为第一次使用github，所以不知道怎么提交，只好在这里说了。复制的文本如下：
`CSS loader has two parts: stylesheet and HTML part. Stylesheet is embraced in <style> tag so you can copy the file content into the place you want the icon to show.To increase reusability, you can separate stylesheet from html part into a standalone css file. For example:`

**Comment by wangfupeng1988** [comment]
我复制`CSS loader has two parts: stylesheet and HTML part. Stylesheet is embraced in <style> tag so you can copy the file content into the place you want the icon to show.To increase reusability, you can separate stylesheet from html part into a standalone css file. For example:`然后用chrome打开官网demo，粘贴进入之后没有问题。

你就告诉我如何一步一步复现问题就好了，最重要的是让我看到问题

**Comment by wangsuiche** [comment]
1.使用http://www.kancloud.cn/wangfupeng/wangeditor2/156691 提供的HTML例子；
2.把`CSS loader has two parts: stylesheet and HTML part. Stylesheet is embraced in <style> tag so you can copy the file content into the place you want the icon to show.To increase reusability, you can separate stylesheet from html part into a standalone css file. For example:` 复制到输入框中；
3.复制进来的内容就只有`CSS loader has two parts: stylesheet and HTML part. Stylesheet is embraced in `

**Comment by wangfupeng1988** [comment]
非常抱歉，v2 此后不维护了，已经升级到 v3 版本了，个人业余精力有限，还请体谅。
