### ISSUE TITLE
关于复制图片

### ISSUE THREAD

**Issue by uinz** [wangfupeng1988/wangEditor#469]
HI,

> 版本 wangEditor 2.1.20
> chrome 53.0.2785.143 (64-bit)
> macOS Sierra

请问怎么实现 粘贴图片 (qq 截图 )
我按照 demo 写完后, 不支持这种 粘贴方式(qq 截图)

是否有相关文档, 如果有 请及时关闭这个 issue 

我找了遍文档, 跟图片相关的 貌似只有 拖拽和选择文件的文档.

我想做的是 把 粘贴的图片(qq 截图) 上传到 七牛 然后替换原来的 base64

thanks

**Comment by uinz** [comment]
uploadImgUrl
设置了才可以, 我还是先仔细看文档吧.

**Comment by uinz** [comment]
看了一圈 是不是 使用 `customUpload = true` 就不支持 粘贴 图片上传了(qq截图)?

**Comment by uinz** [comment]
https://github.com/wangfupeng1988/wangEditor/blob/master/src/js/wangEditor.js#L6754

```js
// 跨域上传时，传cookie
xhr.withCredentials = true;
```
当我 设置 `editor.config.uploadImgUrl = '//upload.qiniu.com'`
会导致提示跨域错误.

**Comment by wangfupeng1988** [comment]
粘贴qq截图本来就支持 http://www.kancloud.cn/wangfupeng/wangeditor2/113991

七牛参照文档的说明来做 http://www.kancloud.cn/wangfupeng/wangeditor2/123691

**Comment by uinz** [comment]
@wangfupeng1988 

[7198行](https://github.com/wangfupeng1988/wangEditor/blob/master/src/js/wangEditor.js#L7198)

```js
        // 未配置上传图片url，则忽略
        if (!uploadImgUrl) {  /* 如果设置了 这里 return 掉了, 就没监听 粘贴图片了 */
            return;
        }
        // -------- 非 chrome 下，通过查找粘贴的图片的方式上传 --------
        function findPasteImgAndUpload() {
           // ...
        }

        // 开始监控粘贴事件
        $txt.on('paste', function (e) {
            // ...
        }
```

所以 集成七牛 的时候 **无法粘贴图片**

**Comment by Aaronphy** [comment]
我也想问 如何支持复制图片

**Comment by uinz** [comment]
@Aaronphy 自己写个吧, 推荐使用 draft.js 来做编辑器 真的强大

我看到这个教程里说和 react 配合 还需要 jq 就真的觉得..

**Comment by Aaronphy** [comment]
@uinz  你写了吗？能给看看吗？我觉得坑挺多的～

**Comment by uinz** [comment]
@Aaronphy 你着急用的话 把的源码改下就好了.

**Comment by yuweilan** [comment]
截屏粘贴的时候，发现粘贴的图片颜色会变，粘贴保存在其他地方是正常的
