### ISSUE TITLE
关于在requirejs 支持中，界面按钮事件绑定的问题。

### ISSUE THREAD

**Issue by huangsong** [wangfupeng1988/wangEditor#47]
界面按钮绑定事件很多都是 $(function(){do something}) 这样的形式来做绑定的，在require 引入中可能会导致事件绑定不上（即DOM还没渲染完，jquery就认为已经ready了）的情况。
如下代码：

    require([
	'jquery',
	'html!tpl/box',
    'css!css/basic',
    'css!wangEditorDir/css/wangEditor-1.3.11',
    'wangEditor'
	],function(jquery,box){

		$('body').append($(box));
        $('#editor').wangEditor();
    });

其中box.html中包含一个

    <textarea name="editor" id="editor" cols="30" rows="10"></textarea>

容器。
会导致 例如像是 源代码 按钮无法绑定上事件。

我想可否在这方面改善一下？渲染dom后统一回调下绑定事件。

**Comment by wangfupeng1988** [comment]
```
require([
'jquery',
'html!tpl/box',
'css!css/basic',
'css!wangEditorDir/css/wangEditor-1.3.11',
'wangEditor'
],function(jquery,box){
    $(function(){
        $('body').append($(box));
        $('#editor').wangEditor();
    });
});
```
这样写不行吗？把业务代码都包含在 ```$(function(){....})```中间

**Comment by huangsong** [comment]
举个例子
<code>
require([
	'jquery'
	],function(jquery,box){

        $(function(){
            console.log($('#abc'));//取不到
        })

        $('<div id="abc">abc</div>').appendTo($('body'));
        console.log($('#abc')); //取到了
});
</code>

**Comment by wangfupeng1988** [comment]
你以上的例子我没有看明白，这里的`abc`难道不是html节点之一吗？为何要先`$('abc').appendTo($('body'));`才能取到`$('#abc')`？

我觉得你最好能做一个简单的demo，发送到我的邮箱或者群空间，然后写一个详细一些的描述。

回复过于简单，会影响交流效率。

**Comment by huangsong** [comment]
我认为 把业务代码都包含在 $(function(){....})中间  不是一个好的方式。当在使用requeryjs的时候。

**Comment by wangfupeng1988** [comment]
你可以不包含在$(function(){...})中间啊，编辑器只是一个插件而已，它不会显示你的业务代码包含在什么地方。

想要在一个textarea上生成编辑器，只需要让jquery获取到这个textarea之后，即可生成。至于在什么地方才能让jquery获取到这个textarea，就看自己项目的代码怎么写了。

------------

其实我是很想看看你的问题到底是什么，复现一下，就是论事的解决这个问题。

**Comment by huangsong** [comment]
恩，我是在requeryjs项目里集成这个编辑器的时候，发现如果不用     $(function(){...})  这种方式去渲染编辑器的时候， 显示源代码 按钮会不起作用，然后我简单的阅读了下编辑器的源代码。 发现 
    editor.$btnContainer.find('.icon-wangEditor-code').parent()
会有取不到的情况。
代码 我打包 传到 百度云上
    http://pan.baidu.com/s/1i3yF2lf

**Comment by wangfupeng1988** [comment]
我下了班晚上看看

**Comment by wangfupeng1988** [comment]
我刚才测试了一下，发现没有什么问题呀，编辑器的功能都是正常的，你说的问题并没有复现啊
<img width="757" alt="qq20151008-1 2x" src="https://cloud.githubusercontent.com/assets/9583120/10365337/3db88738-6df5-11e5-8af5-cd6a8be1c5b1.png">

**Comment by huangsong** [comment]
![rrr](https://cloud.githubusercontent.com/assets/1814074/10383526/98455704-6e62-11e5-8397-b57c3ce468b7.gif)

**Comment by wangfupeng1988** [comment]
针对你上楼贴出来的这个gif动画：
1. 和你一开始提出的问题是不是一会儿事儿，要不是一会儿事儿，最好另外重新提一个问题；
2. 不管是不是和一开始的问题有关系，我这里都无法复现你说的那个bug。我希望你能通过 http://www.wangeditor.com/ 官网的demo复现这个bug，只要复现了，就搞定它。

**Comment by wangfupeng1988** [comment]
提问者长时间不回复，问题先关闭，再有疑问再另外提一个问题吧
