### ISSUE TITLE
只能获取纯文本内容

### ISSUE THREAD

**Issue by iningmeng** [wangfupeng1988/wangEditor#470]
在获取编辑区内容时，只能获取纯文本，不能获取地图、链接等纯文本内容，不能获取样式内容，虽然说可以通过editor.$txt.html()获取，但一般谁会把代码传回后台！

**Comment by uinz** [comment]
rss

**Comment by wangfupeng1988** [comment]
> 虽然说可以通过editor.$txt.html()获取，但一般谁会把代码传回后台！

不把代码传回后台，如何实现**富文本**效果啊？

你说的需求，看看这里 http://www.kancloud.cn/wangfupeng/wangeditor2/113969 如果这里没有那就得自己处理`editor.$txt.html()`获取的内容

**Comment by wangfupeng1988** [comment]
暂时关闭，有需要还可再留言。

**Comment by nicelj** [comment]
还有办法能传所有内容到后台吗
