### ISSUE TITLE
上传图片后回车键<br>的问题

### ISSUE THREAD

**Issue by sweetyluo** [wangfupeng1988/wangEditor#472]
上传好图片回车生成的`<br>`标签，在编辑器里没有占位置，但是生成文章后会占一行，这样的问题怎么处理呢？`<p><img src="http://oss.zhubaoyi.cn/images/article/200386253971.png" style="max-width:100%;" class=""><br></p> `img是80px 但是p会是110px 由于br在那里的原因

**Comment by wangfupeng1988** [comment]
我在官网看到这个问题了，回头找一下原因

**Comment by sweetyluo** [comment]
如果找到了原因跟我说一下哈，辛苦你了，谢谢你。

**Comment by wangfupeng1988** [comment]
非常抱歉，v2 此后不维护了，已经升级到 v3 版本了，个人业余精力有限，还请体谅。
