### ISSUE TITLE
引用功能

### ISSUE THREAD

**Issue by lincenying** [wangfupeng1988/wangEditor#473]
现在编辑器的引用功能是, 要当前行有内容, 或者选择文本的时候, 点引用按钮会有作用, 如果当前行没有内容时, 则没有效果, 这样感觉体验不太好, 能不能改下, 当前行没有内容时, 直接插入一个空的blockquote标签?
```javascript
            // 无文字，则不允许执行引用
            if (!$rangeElem.text()) {
                return;
            }
```

**Comment by wangfupeng1988** [comment]
v2.x这一版目前的所有的格式操作都是有内容的前提下才能生效，该版本不打算大改了。下次大版本升级会吧所有的格式操作都改成你所说的这种情况。

**Comment by wangfupeng1988** [comment]
v3 已发布，可支持预设置格式。
