### ISSUE TITLE
插入表情后会增加多余的P标签，光标点不好就会换行点到第二行

### ISSUE THREAD

**Issue by FakeMr** [wangfupeng1988/wangEditor#474]
![90b7sol5cq77rv4k2fa9xw](https://cloud.githubusercontent.com/assets/7379891/19915462/70e4a674-a0ed-11e6-8604-9e13b1f88b08.png)
插入表情后会增加多余的P标签，光标点不好就会换行点到第二行有时候做聊天的项目，真的不希望自动多这个P标签，觉得很影响输入体验

**Comment by wangfupeng1988** [comment]
你用的什么浏览器？

**Comment by wangfupeng1988** [comment]
非常抱歉，v2 此后不维护了，已经升级到 v3 版本了，个人业余精力有限，还请体谅。
