### ISSUE TITLE
图片上传问题

### ISSUE THREAD

**Issue by chenqiang1121** [wangfupeng1988/wangEditor#475]
win 10  chrome ， 使用编辑器一次性上传多个图片，监视到的网络请求，发现多次调用了上传图片的服务，console中的日志为 h5上传方式， 服务器端返回了图片的地址，但是这样的话 图片展示的顺序并不是我上传的顺序， 请问怎么设置一次性上传多个图片，由服务器端进行控制前后顺序，或者前端如何控制顺序显示呢？

**Comment by wangfupeng1988** [comment]
目前是如你所说的这样子的，v2.x不打算再做大改动了，以稳定为主。下次大版本升级，再把你说的建议做上，这个我早就已经记录下了。

**Comment by huanggm** [comment]
@wangfupeng1988 
我现在也遇到这个问题了，有点等不及你这边升级了，所以考虑自己有什么办法去实现这一点。但是我发现关于上传图片这块只有三个事件onload，ontimeout，onerror；

我想在图片上传之前，也就是选择完图片后，记录下图片的顺序，然后等待服务器端返回后，再一次性插入到编辑器中。现在关键的第一步就做不到。你有什么好的建议吗？
