### ISSUE TITLE
同时放两个编辑器，图片上传会默认到第二个中

### ISSUE THREAD

**Issue by hubinjie** [wangfupeng1988/wangEditor#477]
RT

网络图片是正常的，我用的是angular

```
aciAPP.directive('contenteditable', function(API_ENDPOINT,session) {
            return {
                restrict: 'A' ,
                require: 'ngModel',
                link: function(scope, element, attrs, ctrl) {
                    // 创建编辑器
                    var editor = new wangEditor(attrs.id);
                    // wangEditor.config.printLog = false;
                    // 配置自定义参数（举例）
                    editor.config.uploadHeaders = {
                        'Authorization' : session.token,
                    };

                    editor.config.uploadImgFileName = 'file';
                    editor.config.uploadImgUrl = API_ENDPOINT.url+'user_attachment/image';
                    editor.config.menus = [
                        'source',
                        '|',
                        'bold',
                        'underline',
                        'italic',
                        'strikethrough',
                        'eraser',
                        'forecolor',
                        'bgcolor',
                        '|',
                        'quote',
                        'fontfamily',
                        'fontsize',
                        'head',
                        'unorderlist',
                        'orderlist',
                        'alignleft',
                        'aligncenter',
                        'alignright',
                        '|',
                        'link',
                        'unlink',
                        'table',
                        'emotion',
                        '|',
                        'img',
                        'video',
                        '|',
                        'undo',
                        'redo',
                        'fullscreen'
                     ];

                    editor.config.uploadImgFns.onload = function (resultText, xhr) {
                        var originalName = editor.uploadImgOriginalName || '';  
                        resultText = JSON.parse(resultText);
                        console.log('editor', editor);
                        editor.command(null, 'insertHtml', '<img src="' + resultText.data.url + '"  class="img-responsive"/>');
                    };

                    editor.onchange = function () {
                        // 从 onchange 函数中更新数据
                        scope.$apply(function () {
                            var html = editor.$txt.html();
                            ctrl.$setViewValue(html);
                        });
                    };
                    editor.create();
                }
            };
        });
```

**Comment by hubinjie** [comment]
老板在么？

**Comment by hlerenow** [comment]
同问，遇到一样的问题了

**Comment by hlerenow** [comment]
@hubinjie 我看了下源码，和你一样的问题，你应该也是用了自定义上传事件吧，也就是重写了这个函数editor.config.uploadImgFns.onload,问题来了，这个函数是个公用的的对象，后面的会覆盖前面定义的编辑器定义的函数，所以第一个函数图片上传完成当回调时，内部的editor对象是第二个编辑器的，所以会出现这个情况，我的解决方案是，服务端返回一个一个标识，表示是第一个编辑器的返回结果，还是第二个编辑器的返回结果，然后在去调用对应的编辑器对象（这样的话，editor1和editor2必须和onload函数同一作用域下，不想改js源码就只有这样咯，o(︶︿︶)o 唉）

**Comment by hlerenow** [comment]
@hubinjie 后来发现，只要前面知道是那个编辑器上传的图片，获取到指定的编辑器对象就可以了插入了，根本不用走后台，尴尬

**Comment by hubinjie** [comment]
@hlerenow 朋友分享一下你的代码解决方案吧 ：）

**Comment by hlerenow** [comment]
基本 思路是 ，选我选择 某个编辑器时，就用个 全局个变量 表示当前使用的编辑器 是1 or 2，回调时 根据 全局变量 选择插入到指定编辑器.
<pre><code>
        editor2.config.uploadImgFns.onload = function(resultText, xhr) {
            // resultText 服务器端返回的text
            // xhr 是 xmlHttpRequest 对象，IE8、9中不支持

            // 上传图片时，已经将图片的名字存在 editor.uploadImgOriginalName
            var originalName1= editor.uploadImgOriginalName || '';
            var originalName2 = editor2.uploadImgOriginalName || '';


            var res = $.parseJSON(resultText);
            console.log(res);
            if (res.stateCode == "N01") {
                console.log(MENUEHANDLE.getNowView());
                if(MENUEHANDLE.getNowView()=="#publishMessageView"){
                    console.log("我是消息编辑器");                    
                    editor2.command(null, 'insertHtml', '<img src="' + res.contents.urlPath + '" alt="' + originalName1 + '" style="max-width:100%;" />');
                }else{
                    editor.command(null, 'insertHtml', '<img src="' + res.contents.urlPath + '" alt="' + originalName2 + '" style="max-width:100%;" />');
                }
            } else {
                alert("上传失败");
            }
        };
</code></pre>

**Comment by gxlfc** [comment]
出现同样的问题，不是和这个command中的null参数相关？

editor.command(null, 'insertHtml', ……）？

http://www.kancloud.cn/wangfupeng/wangeditor2/115832

**Comment by gxlfc** [comment]
@hubinjie ，最后你们是怎么解决的呢？

**Comment by he644017879** [comment]
我发现可以将两个editor设置的图片上传url，加一个无用的参数，就可以不会出现这种问题了，比如：editor.config.uploadImgUrl = '/system/product/multi-text-image.action?no=no1'

**Comment by gitdust** [comment]
思路是全局设置变量存储所有的editor，onload的时候再根据一个字段获取对应的实例。
```js
// editor 是实例
// selector = editor.txt.$txt.selector;
var editors = {};
var storeEditor = function(selector, editor) {
    return editors[selector] || (editors[selector] = editor);
};
// 存储
storeEditor(selector, editor);
// 取出
storeEditor(selector);
```

**Comment by xiaobao66** [comment]
出现这个问题是因为在获取配置时使用的是对象浅拷贝，所以第二个editor的自定义上传事件会覆盖第一个editor定义的上传事件。可以通过修改源码来解决这个问题。
源码中通过**initDefaultConfig**函数初始化配置，在源码的3546行，代码如下：
```
// 对象配置
_e(function (E, $) {

    E.fn.initDefaultConfig = function () {
        var editor = this;
        editor.config = $.extend({}, E.config);
        editor.UI = $.extend({}, E.UI);
    };

});
```
可以看到使用的是jquery浅拷贝，只要将其改为深拷贝，就可保证两个配置不会冲突，更改代码如下：
```
// 对象配置
_e(function (E, $) {

    E.fn.initDefaultConfig = function () {
        var editor = this;
        **editor.config = $.extend(true, {}, E.config);**
        **editor.UI = $.extend(true, {}, E.UI);**
    };

});
```

**Comment by wangfupeng1988** [comment]
V3版本正在发版中，已经解决了这一问题  http://www.kancloud.cn/wangfupeng/wangeditor3/332599
