### ISSUE TITLE
工具栏按钮的a标签的href属性不应该为"#"

### ISSUE THREAD

**Issue by ahirusan** [wangfupeng1988/wangEditor#478]
工具栏按钮的a标签的href属性不应该为"#"，如果页面使用HistoryAPI或HashChanged来动态加载内容，当点击了HTML编辑器的任何按钮，都会导致页面内容意外刷新。
如果一定要用a标签，请把href属性去掉，或者使用href="javascript:;"代替。

**Comment by Gavin-Gong** [comment]
集成到单页应用里面, 会把url搞得一团糟

**Comment by wangfupeng1988** [comment]
有道理。近期即将升级的下一个版本会改过来，目前版本先保持稳定吧
