### ISSUE TITLE
文字出现乱码

### ISSUE THREAD

**Issue by syq123456** [wangfupeng1988/wangEditor#48]
我配置了一个langConfig 然后在 $(function () {}）中

        var editor = $('#textarea1').wangEditor({
            'lang': langConfig//'en'
        });
了 但是 类似  网址锛�  这种乱码出现 我该如何解决

**Comment by wangfupeng1988** [comment]
0. 注意页面的编码，一般都用utf-8，看看是不是页面编码的问题；另外，你的浏览器访问官网demo有没有乱码？
1. 你要确定，乱码是不是因为配置语言引起的，去掉语言的配置有没有乱码？
2. 如果是语言引起的，看看配置其他语言是不是乱码，哪种语言会出现乱码。
3. 如果以上的判断都不能解决问题，你可以做一个静态的、简单的demo，发送到qq群文档，然后在此回复告诉我，我帮你调试一下看看。

------------

总之，一旦遇到bug，你首先要做的不是直接去问，而是要先通过自己的实验来最小化bug可能出现的范围，定好范围再求助。
但是一般情况下，80%的bug在确定范围的过程中就能解决掉。

这是我总结的最有效率的解决bug的途径。

**Comment by wangfupeng1988** [comment]
提问者长时间不回复，问题先关闭，再有疑问再另外提一个问题吧
