### ISSUE TITLE
QQ聊天窗口中的图片，通过复制粘贴到编辑器会报错？

### ISSUE THREAD

**Issue by xiaoyu1987** [wangfupeng1988/wangEditor#482]
源码显示` recoruse file：\\\`，文档写不支持，那怎么提示解决js报错问题

**Comment by wangfupeng1988** [comment]
从 QQ 直接赋值过来肯定是有问题的，如果能成功那也是只是部分浏览器可以。目前大部分的网页，还都是**上传**图片，没有直接能**复制、粘贴**图片的
