### ISSUE TITLE
结合Vue使用时在npm run dev时出现警告。

### ISSUE THREAD

**Issue by hongliming** [wangfupeng1988/wangEditor#483]
WARNING in ./~/wangeditor/dist/js/wangEditor.js
19:35 Critical dependency: the request of a dependency is an expression

WARNING in ./~/wangeditor/dist/js/wangEditor.js
22:42 Critical dependency: the request of a dependency is an expression

![image](https://cloud.githubusercontent.com/assets/2437125/20160913/b1941aa4-a725-11e6-824e-e339ba8e845c.png)

**Comment by hongliming** [comment]
vue，wangeditor 均最新版。

**Comment by erguotou520** [comment]
+1

**Comment by erguotou520** [comment]
发个自己集成的组件
https://gist.github.com/erguotou520/003b50961b426a99c45607b2ca7ab7fd

**Comment by hongliming** [comment]
然后问题解决了不？@erguotou520

**Comment by erguotou520** [comment]
只是警告，不影响使用

**Comment by jucloud** [comment]
同样问题

**Comment by yelingfeng** [comment]
来+个1

**Comment by mxm145** [comment]
+1

**Comment by xiaofeiapis** [comment]
+1

**Comment by ncodm** [comment]
+1

**Comment by wangfupeng1988** [comment]
这个问题已经修改了，关注下一个版本发布。多谢大家的反馈！
