### ISSUE TITLE
图片上传不了

### ISSUE THREAD

**Issue by Cindlla** [wangfupeng1988/wangEditor#484]
我把代码原封不动的粘到我的java项目里，就是无法上传图片，点击上传看见有个滚动条闪了一下，传不上去也不显示图片，也无法拖拽，总之这功能没反应，为什么，我一把这代码粘到外面运行马上又好使了

**Comment by wangfupeng1988** [comment]
> 我把代码原封不动的粘到我的java项目里

你把什么代码粘贴到java项目里？
