### ISSUE TITLE
关于表情复制得进编辑器，保存会出错的问题

### ISSUE THREAD

**Issue by sweetyluo** [wangfupeng1988/wangEditor#485]
http://www.oicqzone.com/tool/emoji/ 在这个网址最后一栏wechat的表情复制到编辑器，看上去是看得到表情的，但是保存的时候会出错，是不是一定要把这些表情都放进自定义特殊字符里面才可以用呢？

**Comment by wangfupeng1988** [comment]
emoji 表情应该是可以支持的。你保存时报什么错误？
