### ISSUE TITLE
ie8中字体不显示

### ISSUE THREAD

**Issue by zhaoleigege** [wangfupeng1988/wangEditor#487]
为什么在内网环境下ie8的字体加载不了，但是换成chrome可以正常显示字体，这属于浏览器设置问题还是别的问题。

**Comment by wangfupeng1988** [comment]
首先你用 IE8 访问官网时，图标没问题吧？

如果官网没问题，那就是网络或者浏览器的问题了，IE8 这种奇葩浏览器，遇到这种问题还真不好排查。
