### ISSUE TITLE
现在插入链接默认都是 _blank，能否增加“在新窗口打开”的选项？

### ISSUE THREAD

**Issue by taichenglu** [wangfupeng1988/wangEditor#489]
现在插入链接默认都是 _blank，能否增加“在新窗口打开”的选项？这样可以控制。

**Comment by wangfupeng1988** [comment]
这个暂时不会改动，应用场景比较少。wangEditor 求简，不常用的功能不会做。

如果后面提出需求的用户多了，会考虑增加这样的配置。

**Comment by sh4wn** [comment]
iOS上的WKWebView默认不会打开target="_blank"的超链接,建议增加一个选项,谢谢
