### ISSUE TITLE
关于ctrl+z效果

### ISSUE THREAD

**Issue by zhaopeiym** [wangfupeng1988/wangEditor#49]
这是wangEditor 效果
![1](https://cloud.githubusercontent.com/assets/5820324/10393759/480aac0e-6ec5-11e5-9900-be9c9756ccbf.gif)
这是百度编辑器的效果
![gif](https://cloud.githubusercontent.com/assets/5820324/10393778/63251f42-6ec5-11e5-85b4-62091da7d21e.gif)

wangEditor 的ctrl+z   直接回到了 最初 的状态  而百度的可以回到上一个编辑状态。

**Comment by wangfupeng1988** [comment]
恩，我通过官网的demo复现了你说的问题了。
其实，wangEditor撤销时，不是回到初始状态，而是回到编辑器上次`blur`的状态，不信你可以试试。
ueditor这样做，它需要监控用户每次的键盘事件，虽然会增加一点易用性，但是带来的肯定是大量内存和CPU的消耗，我觉得计算能力差的IE版本可能会出现性能问题。
------------------
从各方面权衡来讲，我还是坚持当前的这种做法，扯下时候回到上次blur的状态。这种简单的处理，相信不会带来差太多的用户体验。
至今你是第一个提出这个问题的用户。

**Comment by zhaopeiym** [comment]
嗯，试了下。确实是上次blur的状态。
根据你的解释   
我建议：折中下，在回车的时候 保存一次。望采纳。

**Comment by wangfupeng1988** [comment]
恩，你提出的这个建议我觉得可以采纳，可以在回车的时候保存一下，近期修改。

**Comment by wangfupeng1988** [comment]
已经增加了回车保存的功能，可以去github下载更新。
