### ISSUE TITLE
菜单栏格式设置使用方式与其它富文本编辑器不一致

### ISSUE THREAD

**Issue by MR-BH** [wangfupeng1988/wangEditor#491]
如粗体，下划线，斜体，颜色等菜单，在wangEditor中需要在编辑内容完成后，选中目标内容，然后分别设置各种格式。
而其它富文本编辑器，office word等都是在编辑内容前先设置格式然后编辑内容，在大多数用户都有使用word的经验的情况下，保持用户体验的一致性是否更合乎市场的需要？
是不是考虑**与其它富文本的格式设置方式保持一致呢？**

**Comment by wangfupeng1988** [comment]
这个问题在即将开始的下一个版本升级中会重点改进，优先级非常高。目前版本就先不做改动了，稳定为主。

感谢反馈！
