### ISSUE TITLE
字体大小的改进

### ISSUE THREAD

**Issue by cjhgit** [wangfupeng1988/wangEditor#495]
字体大小是固定的，不能设置特殊的字号，如20px

**Comment by yaqian012** [comment]
> 字体大小是固定的，不能设置特殊的字号，如20px

确实，而且只是利用font标签，字体大小限制的有点太窄，建议像设置背景颜色一样，提供style属性去控制字体大小。

**Comment by wangfupeng1988** [comment]
下一个版本会改进这些问题，近期即将启动升级。目前的版本先这样吧，保持稳定。感谢反馈
