### ISSUE TITLE
集成七牛云上传时服务器自己生成的key（根据年月日），是否可以由uploadToken接口一并获取

### ISSUE THREAD

**Issue by dxywx** [wangfupeng1988/wangEditor#498]
因为是服务器生成的key，所以上传的时候会报错{"error":"key doesn't match with scope"}
其实在获取uploadtoken的接口中我已经返回了key了，请问这是后怎样配置？

**Comment by wangfupeng1988** [comment]
非常抱歉，v2 此后不维护了，已经升级到 v3 版本了，个人业余精力有限，还请体谅。
