### ISSUE TITLE
对编辑器的内容获取之后如何正常显示

### ISSUE THREAD

**Issue by yuesf** [wangfupeng1988/wangEditor#499]
保存数据库之后是html 如何正常显示出来(按编辑的格式显示) 我使用的是普通的html , 之前有个人说他使用的nodejs 但啥都没有用, 很原生的那种.

**Comment by PengJiyuan** [comment]
按编辑器里边的css样式嵌套就行了

**Comment by wangfupeng1988** [comment]
> 按编辑器里边的css样式嵌套就行了

正解
