### ISSUE TITLE
无法将值赋予edit

### ISSUE THREAD

**Issue by syq123456** [wangfupeng1988/wangEditor#50]
$(function () {
        $.ajax({
            type: "POST",
            url: "GetQualificationType",
            data: { ServiceShopId: 1187 },
            datatype: "html",
            success: function (data) {
                var arr = data.split('$');
                $('#oDiv').html(arr[0]);
                $('#txtDetail').val(arr[1]);
                //alert(unescape(arr[2]));
                var editor = $('#textarea1').wangEditor();
                var $p = $(unescape(arr[2]));
                editor.append($p);
                
            },
            //调用出错执行的函数
            error: function () {
                alert("错误");
                //请求出错处理
            }
        });

editor 上面不但没有值 而且还弹框出现乱码  我发觉只要 var editor = $('#textarea1').wangEditor(); 不注释就好弹框出现乱码

**Comment by wangfupeng1988** [comment]
> editor 上面不但没有值 而且还弹框出现乱码 
这里的弹框出现乱码，截图贴出来。另外，你确定一下到底是哪一句代码，导致的弹框。另外，你要注意console.log里面的错误提示信息，也截图贴出来。

**Comment by wangfupeng1988** [comment]
提问者长时间不回复，问题先关闭，再有疑问再另外提一个问题吧
