### ISSUE TITLE
关于python上传图片400、413状态码

### ISSUE THREAD

**Issue by GitHubAFeng** [wangfupeng1988/wangEditor#500]
wang大 ，你好。
我后台使用python的flask，在视图函数中使用 file = request.files.get('imageName') 获取图片，但总是出现400请求错误，这个错误一般是由于请求接收参数不一致造成的，可是我已经反复检查了两天，还是没有头绪。
曾经有次上传成功，但没过多久又出现400错误，我怀疑是csrf-token跨域保护的问题，但又不知怎么排错，因为我其它我自定义上传文件等功能都正常，就编辑器这个不正常。
还有就413请求错误，一般是由于不符合上传尺寸的限制之类的原因造成，不知道编辑器是否能设置这个大小？
问题有点诡异，我已经纠结了三天了…… 
下面提供一些DEBUG信息，谢谢。

前端：

        var editor = new wangEditor('div1');

        //////////////// 这段开启图片上传
        // 上传图片（举例）
        editor.config.uploadImgUrl = '/image_update';
        // 配置自定义参数（举例）
        editor.config.uploadParams = {
            token: "{{ csrf_token() }}",
            user: "{{ current_user.id }}"
        };
        // 使用这个name获取文件
        editor.config.uploadImgFileName = 'imageName';
        // 设置 headers（举例）
        editor.config.uploadHeaders = {
           'Accept': 'text/x-json'
          // 'Accept': '*/*'

        };
        /////////////////

        // 隐藏掉插入网络图片功能。该配置，只有在你正确配置了图片上传功能之后才可用。
        //editor.config.hideLinkImg = true;

        editor.create();
————————————————————————————————————————
后端：

# 对图片上传进行相应处理
@blueprint.route("/image_update/", methods=['POST'])
@login_required
def GetImage():
    print request.headers
    file = request.files.get('imageName')
    # file = request.get_data().get('imageName')

    if file == None:
        result = r"error|未成功获取文件，上传失败"
        res = Response(result)
        res.headers["ContentType"] = "text/html"
        res.headers["Charset"] = "utf-8"
        return res
    else:
        if allowed_file(file.filename):
            filename = file.filename
            filepath = os.path.join(current_app.static_folder, UPLOAD_FOLDER, filename)
            folder = os.path.join(current_app.static_folder, UPLOAD_FOLDER)
            if not os.path.exists(folder):
                try:
                    os.makedirs(folder)
                except:
                    error = 'ERROR_CREATE_DIR'
                    return jsonify(error=error)
            file.save(filepath)
            imgUrl = url_for('static', filename='%s/%s' % (UPLOAD_FOLDER, filename))
            res = Response(imgUrl)
            res.headers["ContentType"] = "text/html"
            res.headers["Charset"] = "utf-8"
            return res
————————————————————————————————
请求信息：

Remote Address:127.0.0.1:5000
Request URL:http://127.0.0.1:5000/image_update
Request Method:POST
Status Code:400 BAD REQUEST
Response Headers
view source
Content-Length:754
Content-Type:text/html; charset=utf-8
Date:Tue, 22 Nov 2016 16:32:55 GMT
Server:Werkzeug/0.11.11 Python/2.7.12
Request Headers
view source
Accept:text/x-json
Accept-Encoding:gzip, deflate
Accept-Language:zh-CN,zh;q=0.8
Connection:keep-alive
Content-Length:115217
Content-Type:multipart/form-data; boundary=----WebKitFormBoundaryBEroMT1Ac0qBxcJn
Cookie:session=.eJzVUF1rwjAU_Ssjzz7EWIUVfJHY0kJSWlJLMkVq15KmjZN-0Bnxvy84t_2GPdxzuHDPvfecGzhWbd7Lsgfu2w28DN90Ai44ZTtTIO8s4vUa3GdgPzolzC1WCO7HFZpbXKLXChzus3-lPMys6a7sJXCHbixtV78D97knyhJJdCh5lhqK0kWEU0hwAakiDmVhI5RXE-VJrj3FTSI58hpqAifydy1HwYLiYCketf0UPoEUJ5qYnaSmbQgmk2C2slALFi84SmqaeSry7SwTOvIJstqr1SiqEs1VMXG2UcIPENexoX46Ubxp7Zzl-OGzyC9DIfPf_zm8iPiZQdF31XH4aMrznz0WQ3tuTlgBiUpagreTwI3DVYoICxVR8WRf1RTzq9DCcnP9iXTsy-4RFViB-xfb07AO.CxYAjg.5hr1wQEFhKrcBkTsrbwW-_HKUTw
Host:127.0.0.1:5000
Origin:http://127.0.0.1:5000
Referer:http://127.0.0.1:5000/wangeditor/
User-Agent:Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36
Request Payload
------WebKitFormBoundaryBEroMT1Ac0qBxcJn
Content-Disposition: form-data; name="imageName"; filename="8428010167554021.png"
Content-Type: image/png

------WebKitFormBoundaryBEroMT1Ac0qBxcJn
Content-Disposition: form-data; name="token"

1479835969##2b2b167f53dfc0d331fe1a4add545522c29fce1b
------WebKitFormBoundaryBEroMT1Ac0qBxcJn
Content-Disposition: form-data; name="user"

6
------WebKitFormBoundaryBEroMT1Ac0qBxcJn--

**Comment by wangfupeng1988** [comment]
建议分开来解决问题，将问题分开到前端和后端

自己做一个简单的图片上传功能，然后用你的 python 代码来接收图片文件，看是否也报错？
