### ISSUE TITLE
td表格默认宽度问题

### ISSUE THREAD

**Issue by jerry-he** [wangfupeng1988/wangEditor#51]
![qq 20151010195635](https://cloud.githubusercontent.com/assets/5547912/10411009/2d5d1cba-6f89-11e5-9751-4fe7c75d8ce8.png)
#如图

wangeditor会强制改变外部引入的表格宽度，赋予了最小值100px，建议修改为只给自己插入的表格赋值默认宽度

**Comment by wangfupeng1988** [comment]
收到你的问题，我会检查一下，如果真如你所说，那肯定是不合理的。
问题确定好之后，在此处反馈给你。

**Comment by jerry-he** [comment]
呃呃呃   我们测试过的，确定是这个问题   上次我们使用的时候wangeditor还没完善    好多东西我们直接改了源码，这一次我们想和你的源码保持一致，尽量不直接修改你的源码

**Comment by wangfupeng1988** [comment]
我会在这两天吧这个问题修改完，并发布出来。最快今晚，最慢也就这几天。完了会在此通知你。

**Comment by wangfupeng1988** [comment]
已修改完，去掉了`min-width:100px`，去github下载更新即可。
