### ISSUE TITLE
图片上传需改进的地方

### ISSUE THREAD

**Issue by baiyunchen** [wangfupeng1988/wangEditor#511]
最近发现这个富文本框编辑器，感觉非常不错，但是在实际使用中遇到一点不太爽的地方，希望作者能够改进一下！
---
事情是这样：
我后端使用WebAPI统一返回的是Json数据的格式，当图片上传完成，后端的返回是一个string类型时，框架自动序列化出来的字符串两边有双引号，例如：“http://www.baidu.com/test1.jpg”，这是编辑器就误认为我这不是一个http打头的路径，自动加上了我的当前富文本框编辑器所在域名，变成了：http://test.com/"http://baidu.com/test1.jpg"，最终我的解决办法是后端放弃使用框架自动序列化Json，改成手动指定返回类型为text/plain，问题得以解决。但是我觉得，编辑器应该要支持这样的返回结果~

**Comment by wangfupeng1988** [comment]
这个问题即将升级的新版本中肯定会修改，对于这个问题我也难受很久了，这个问题优先级非常高。

感谢反馈！
