### ISSUE TITLE
粘贴文字，光标定位不准，没有定位到文章最后

### ISSUE THREAD

**Issue by Yankj** [wangfupeng1988/wangEditor#514]
操作步骤
1.复制一段文字
2.进入消息编辑器，粘贴进来三段文字查看
预期：光标在三段文字结尾
实际：光标在三段文字中最后一段的开始位置

**Comment by wangfupeng1988** [comment]
没遇到你说的情况

不过在即将进行的下一版本升级中，会从新设计 selection 和 range 的功能

**Comment by Yankj** [comment]
这种情况肯定是存在的，你多复制粘贴几次肯定会遇到

**Comment by wangfupeng1988** [comment]
非常抱歉，v2 此后不维护了，已经升级到 v3 版本了，个人业余精力有限，还请体谅。
