### ISSUE TITLE
建议添加字数限制和字数显示功能

### ISSUE THREAD

**Issue by Mr9esx** [wangfupeng1988/wangEditor#516]
想在前端可以让用户知道目前字数是多少，不需要提交到后端才检验。

**Comment by wangfupeng1988** [comment]
这一个版本先不加这个功能了，优先保持稳定。即将开启的下一个版本更新，会将这个功能加上，我已经记录下来了。多谢反馈！

**Comment by sunOpar** [comment]
请问这个功能在哪里，怎么使用

**Comment by wangfupeng1988** [comment]
这个问题先自己开发吧。通过 onchange 实时获取编辑器的内容，然后自己计算字数。
