### ISSUE TITLE
复制其他地方信息过来，带了很多样式，保存的时候卡顿

### ISSUE THREAD

**Issue by xiaoyu1987** [wangfupeng1988/wangEditor#517]
比如复制邮箱带样式内容粘贴到编辑器中，统计过源码带空格有1700多字，保存不成功，请问要怎么修复

**Comment by wangfupeng1988** [comment]
开启了样式过滤了吗（http://www.kancloud.cn/wangfupeng/wangeditor2/113984）？带那么多样式保存，对内存、计算都有压力。
