### ISSUE TITLE
右对齐或居中对齐之后保存文本， 再次编辑的时候文本却成了左对齐，求解

### ISSUE THREAD

**Issue by dtchris** [wangfupeng1988/wangEditor#518]

**Comment by dtchris** [comment]
<div xss="removed">每一个单号只能对应一个包裹的寄送！如果您同时需要给一个人寄10个包裹，那您就需要下10个单，并将这10张不同单号的面单分别贴在这10个包裹上。</div><div xss="removed">如果您不小心贴重单了： &nbsp;由于面单单号对应信息唯一</div><p><br></p>
右对齐之后打印就出现xss=removed 如何处理这个问题

**Comment by wangfupeng1988** [comment]
> 再次编辑的时候文本却成了左对齐

看看再次编辑的时候 html 代码是什么？而此前设置右对齐或者居中对齐时的html代码又是什么？比较一下
