### ISSUE TITLE
ie全家桶都有问题

### ISSUE THREAD

**Issue by wuceyang** [wangfupeng1988/wangEditor#519]
貌似ie全家桶从8-11都不显示图标，ie7初始化都初始化不了
![2](https://cloud.githubusercontent.com/assets/1538757/20911958/292eeff4-bba7-11e6-8173-10bce897d128.png)

**Comment by wangfupeng1988** [comment]
我这边用IE验证是没有问题的。

页面显示一开始会有你截图的情况，但是后面立即就显示图标了。我怀疑可能是你那边网速慢或者github被墙的缘故。因此官网是托管到github上的。

**Comment by wuceyang** [comment]
经验证，可能是我电脑的问题，其他人电脑是ok的

**Comment by JunedanVan** [comment]
@wuceyang 在head里加<meta http-equiv="X-UA-Compatible" content="IE=Edge">

**Comment by JunedanVan** [comment]
@wuceyang 在head里加`<meta http-equiv="X-UA-Compatible" content="IE=Edge">`
