### ISSUE TITLE
css和font-awesome的css冲突

### ISSUE THREAD

**Issue by leebooe** [wangfupeng1988/wangEditor#52]
![Uploading image.png…]()

这个问题该怎么解决，css样式互换前后位置后会导致font-awesome的图标全部没了
![Uploading QQ截图20151011134012.png…]()

**Comment by leebooe** [comment]
![qq 20151011134012](https://cloud.githubusercontent.com/assets/15071751/10415113/b853fbce-701d-11e5-92fd-acc78248e68a.png)

**Comment by wangfupeng1988** [comment]
css覆盖的问题，没法从根本上解决。

**Comment by wangfupeng1988** [comment]
你所说的问题，贴一张图我也没法知道是什么原因，这种问题只能就事论事的详细分析。
你可以通过浏览器的控制台去监测一下菜单按钮的样式，到底你项目中其他的什么css样式导致了图标图片不显示。一个熟练的前端开发人员，会一下子就能看出来，先找到原因，然后在分析出解决方案。
-------------------
如果你觉得自己看不出来，不妨做一个静态的demo，发给我（网盘共享或者QQ群文档），我帮你来看看，给你找出原因，你再自己对症下药。

**Comment by wangfupeng1988** [comment]
请尽快回复，时间久了，我会暂时关闭这个问题

**Comment by leebooe** [comment]
我已经解决了，是icon跟另外的icon 冲突，我把编辑器的css和js里面改了下

**Comment by wangfupeng1988** [comment]
如果都是class选择器，应该不会有冲突，因为编辑器的class都是`icon-wangEditor-`开头的，你其他的样式不可能有`wangEditor`字样。肯定是有其他的原因冲突了，建议你最好分析一下根本原因。

另外，你吧编辑器的源码改了，你以后每升级一次都得改一次。
