### ISSUE TITLE
关于在编辑器粘贴图片时发生的异常情况

### ISSUE THREAD

**Issue by Quincy-Zh** [wangfupeng1988/wangEditor#520]
前提：编辑器的上传图片功能已经可用，直接通过上传方式是没有问题的。
但是，如果是粘贴的话，会出现以下两种现象，都是在windows7的系统上：
### firefox浏览器，版本50.0.2
  粘贴图片后，会在编辑器内出现两张一样的图片。通过调试工具发现，一个是
`<img src="data:image/png;base64,,.." alt="" class="clicked" style="">`
另一个是
`<img src="/attch/U20161206133520dl2e4c.png" alt="" style="max-width: 100%;" class="">`

### chrome 浏览器， 54.0.2840.50 beta-m (64-bit)
粘贴图片后，编辑器显示图片，但是图像时被base64编码过的：
`<img src="data:image/png;base64,,.." alt="" class="clicked" style="">`

我觉得第一个是一个bug，但是不知道是哪个地方的问题。
第二是应该不是问题，但是为什么不会出现src是一个正常URL的img标签呢？或者，哪种情况会出现base64编码，哪种情况会是上传文件~盼解答。

**Comment by wangfupeng1988** [comment]
感谢反馈！

这两个问题我去实际看一下再回复吧。由于几个月没有关注issue，我需要先把积累的issue全部都过一遍，再来看你这个问题，因此可能需要等待几天。请见谅。

**Comment by old-bin** [comment]
原来已经提过这个问题了，第一张图片我用来 ajax到后台存储 。第二图片我用 ev.preventDefualt() 阻止了。

**Comment by wangfupeng1988** [comment]
非常抱歉，v2 此后不维护了，已经升级到 v3 版本了，个人业余精力有限，还请体谅。
