### ISSUE TITLE
关于一个页面多个编辑器的问题

### ISSUE THREAD

**Issue by NchuXhg** [wangfupeng1988/wangEditor#521]
![image](https://cloud.githubusercontent.com/assets/16134826/20918775/9dc8de70-bbd3-11e6-8456-4ed36f2c2fe3.png)

自定义上传事件后，不管在那个编辑器内上传图片 ， 上传成功后都会插入同一个编辑器
![image](https://cloud.githubusercontent.com/assets/16134826/20918599/dfe13ab0-bbd2-11e6-8bf9-19b7df3f9b7a.png)
在上面的编辑器内上传图片成功后，会在下面的编辑器内插入图片

**Comment by NchuXhg** [comment]
不同editor实例的 配置项没有全部隔离 editor.config.uploadImgFns.onload事件会相互覆盖 ，图片总是被插入在未被覆盖的editor.config.uploadImgFns.onload所在的编辑器实例内

**Comment by hebinhui** [comment]
这个问题是否已经解决了呢，怎么没看到解决方案？

**Comment by NchuXhg** [comment]
我在angular用一个单例服务保存每个editor实例 用的时候用这个服务拿相应的ediotr实例
