### ISSUE TITLE
使用字體加粗按鈕和字體斜體按鈕沒有反應

### ISSUE THREAD

**Issue by frontHu** [wangfupeng1988/wangEditor#524]
使用字體加粗按鈕和字體斜體按鈕沒有反應

**Comment by wangfupeng1988** [comment]
具体说一下使用场景，否则我无法复现

**Comment by zhouyang1017** [comment]
![image](https://cloud.githubusercontent.com/assets/28047230/25429106/7b134262-2aaa-11e7-9ff8-fd836a239b72.png)
如此创建一个编辑器，字体下划线，字体斜体点击无效果。
另外：引入min.js时ie8无法初始化，非压缩版却可以

**Comment by wangfupeng1988** [comment]
看官网是否也有这个问题？另外官网已升级V3版本，看一下V3是否有这个问题，建议近期升级V3

**Comment by ZhangErin** [comment]
亲，斜体在V2的版本在IE8上面点斜体无效，看了源码没看出问题来 @wangfupeng1988
