### ISSUE TITLE
页面有多个编辑器时，建议增加获取活动编辑器的方法

### ISSUE THREAD

**Issue by zhangyanzt** [wangfupeng1988/wangEditor#527]
页面有多个编辑器时，建议增加获取活动编辑器的方法。
我在自己集成公式编辑器时遇到了这样的需求，需要确定哪个是活动编辑器从而把生成的公式追加上去。但是看文档似乎没有这个功能。

**Comment by wangfupeng1988** [comment]
该版本没有这个功能，暂时先不加，尽量保持稳定。即将开始的下一个版本，会加入这个功能。已经记录下。

感谢你的反馈和提议，我觉得这个功能对于解决多个编辑器的各种问题，非常有帮助作用。谢谢
