### ISSUE TITLE
文件上传，文件名被更改问题。

### ISSUE THREAD

**Issue by jiajianchang** [wangfupeng1988/wangEditor#528]
问题：主要是后台附件处理wangeditor上传的图片的时候，需要获取原文件名，但是获取到的都是随机数字串。如果想保持原名传递给后台，是否有办法可以解决。

**Comment by wangfupeng1988** [comment]
这一版本暂时不支持，先保持稳定，不改动。即将启动的下一个版本会处理这一问题，已经记录下。感谢反馈
