### ISSUE TITLE
使用多个富文本编辑器时会导致地图一直处于加载中

### ISSUE THREAD

**Issue by yk727228981** [wangfupeng1988/wangEditor#53]
当使用多个富文本编辑器时，点击插入地图时，地图画面一直显示加载中，估计是 window.baiduMapCallBack无法初始化，具体原因不详

**Comment by yk727228981** [comment]
但，最后编辑器一个是可以的

**Comment by wangfupeng1988** [comment]
请关注 https://github.com/wangfupeng1988/wangEditor/issues/44
