### ISSUE TITLE
顶部工具栏下面的菜单定位不准确

### ISSUE THREAD

**Issue by JosnLee** [wangfupeng1988/wangEditor#530]
请问我的外部是不是需要设置啥，或者外部定位导致这个问题

**Comment by wangfupeng1988** [comment]
不知道你是啥问题，无图无真相 😂

**Comment by panghongye** [comment]
![image](https://cloud.githubusercontent.com/assets/24952457/23545131/1529d9b0-0035-11e7-86e5-c6ade20460d5.png)

![image](https://cloud.githubusercontent.com/assets/24952457/23545147/22d9ae96-0035-11e7-8e8f-bbf73c0dd0a5.png)



我也遇到了  火狐会  chrome 不会

**Comment by wangfupeng1988** [comment]
非常抱歉，v2 此后不维护了，已经升级到 v3 版本了，个人业余精力有限，还请体谅。
