### ISSUE TITLE
上传图片可以支持去除`网络图片`的选项吗?为避免 xss 攻击

### ISSUE THREAD

**Issue by alankell** [wangfupeng1988/wangEditor#531]
上传图片可以支持去除`网络图片`的选项吗?为避免 xss 攻击,需要避免使用网络链接

**Comment by gxlfc** [comment]
可以，editor.config.hideLinkImg = false;就可以了吧？

**Comment by wangfupeng1988** [comment]
使用 `editor.config.hideLinkImg = false`
