### ISSUE TITLE
图片上传问题

### ISSUE THREAD

**Issue by SoupT** [wangfupeng1988/wangEditor#533]
浏览器直接访问，点击图片上传后输入框里面会显示要上传的图片。在Wamp环境里用localhost打开，输入框上面会显示像进度条一样的蓝线，图片不显示，缺少了“预览模拟上传”这个步骤。用的chrome浏览器。

**Comment by MattiaLiu** [comment]
下载的最新版点击添加图片按钮没有图片浏览反而是添加链接动作，是不是action写错了

**Comment by wangfupeng1988** [comment]
> 显示像进度条一样的蓝线，图片不显示

检查一下 http 请求返回的结果

> 缺少了“预览模拟上传”这个步骤

wangEditor 求简，不会涉及过于复杂的上传图片功能
