### ISSUE TITLE
多个富文本编辑器，随机点任意一个文本框的上传图片总是插入到最后一个编辑器中

### ISSUE THREAD

**Issue by gxlfc** [wangfupeng1988/wangEditor#538]
查看了code issues中，这个问题已经出现多次，并没有很好的解决方案，请大神出山解决问题呐。

https://github.com/wangfupeng1988/wangEditor/issues/477

https://github.com/wangfupeng1988/wangEditor/issues/277

angularjs-wangeditor-directive： https://github.com/gxlfc/code-snippet/blob/master/wangEditor/wang-editor-directive.js

**Comment by BTeam** [comment]
点击Menu时, self.editor.$txt.focus()一下不行么

**Comment by gxlfc** [comment]
@BTeam 
不行的，不是focus的问题。

![image](https://cloud.githubusercontent.com/assets/12656549/21415676/7cd54570-c847-11e6-8e08-ac747a3c71e3.png)

应该是这个原因

**Comment by xiaofeiapis** [comment]
这个问题没人跟吗

**Comment by ltfswe** [comment]
同这个问题......还在找解决方法

**Comment by gxlfc** [comment]
问题已经解决，详见github。

**Comment by Webfreshman** [comment]
@gxlfc 如何解决
