### ISSUE TITLE
同时使用有序/无序列表和右对齐时，列表符号一直在左边。

### ISSUE THREAD

**Issue by zhenbianshu** [wangfupeng1988/wangEditor#54]

**Comment by wangfupeng1988** [comment]
这是很正常的。

右对齐是针对文字的操作，而 ul 是一个 block ，它的宽度默认是 100%，它是无法设置左对齐右对齐的。右对齐的只能是其中的文字。

另外，右对齐 + 列表 这种情况用的多吗？

**Comment by wangfupeng1988** [comment]
提问者上时间不回复，暂时关闭。有问题再另起一个问题提问。
