### ISSUE TITLE
输入框初始提示不能自动删除

### ISSUE THREAD

**Issue by mikkyxu** [wangfupeng1988/wangEditor#540]
在输入框获取到光标后，文本框的初始提示字符   **请输入内容...* *，不能自动消失，也就是不能实现类似文本框placeholder的效果，需要手动删除，请问有什么解决办法？
是否可以让用户获取editor的focus事件进行判断？

**Comment by wangfupeng1988** [comment]
该版本不支持类似 placeholder 的功能，先以稳定为主。即将开始的下一个版本升级，会加入这个功能。感谢反馈
