### ISSUE TITLE
一个页面多个富文本图片上传问题

### ISSUE THREAD

**Issue by xiaofeiapis** [wangfupeng1988/wangEditor#543]
一个页面多个富文本的时候，上传图片总是添加在最后一个富文本域里面，我看issues里面有人提到过，请问有好的解决方案么
？

**Comment by gxlfc** [comment]
详见

https://github.com/gxlfc/code-snippet/blob/master/wangEditor/wang-editor-directive.js

**Comment by xiaofeiapis** [comment]
这样会有个bug的，如果焦点停在一段文本的中间位置的话，插入的图片 始终在当前富文本的最后，是不是这样的？

**Comment by fallingsoul** [comment]
我也遇到这个问题，怎么fix啊

**Comment by zxyan** [comment]
我也遇到这问题，请问是怎么解决的

**Comment by wangfupeng1988** [comment]
升级v3版本吧，v3解决了这个问题
