### ISSUE TITLE
上传图片必须先传到服务器上本地才能获取到吗

### ISSUE THREAD

**Issue by lanyusuifeng** [wangfupeng1988/wangEditor#544]
做一个发布文章的编辑器，在文章没发布之前，只是添加了图片，这个图片也被传到服务器上了吗？在本地获取这张图片，也只能通过服务器的url来获取吗？

**Comment by turboHZW** [comment]
同问啊，我只想在本地生成图片，base64格式，但是也要通过服务器url获取吗？

**Comment by wangfupeng1988** [comment]
这种线临时显示图片到网页，然后再一起跟随内容上传到服务器的方式，近期不打算支持。原因在于：第一，这种需求的用户群比较少；第二，这样设计会导致后端接口过于负责，用户接入的成本会比较高。

**Comment by liyuanqing** [comment]
在文章发布前添加的图片，通过服务器上传了，但是文章发布之前我又把这个图片删除了，如何监控这个删除动作，把已上传的图片从服务器删除？
