### ISSUE TITLE
如何在编辑区域分隔出几块输入区域

### ISSUE THREAD

**Issue by lyj6879668** [wangfupeng1988/wangEditor#545]
我想在编辑区域分三块，分别是标题，作者和内容，用两个input来放置标题和作者，内容区用p标签，但是在内容区按回删会把前面的input也删掉，这个改怎么解决？

**Comment by wangfupeng1988** [comment]
目前不支持这样分区，而且插件化的编辑器都不能很好的支持这种特性。除非是为了项目定制的编辑器。
