### ISSUE TITLE
浏览器兼容问题

### ISSUE THREAD

**Issue by IceMapleDancer** [wangfupeng1988/wangEditor#55]
插入链接这个功能，在火狐40和IE11下，没有反应，在chrome下没问题。在官网的demo上，也存在该问题。

**Comment by wangfupeng1988** [comment]
IE11我这里暂时没有环境，不过火狐和safari下都实验了，没啥问题的。就是拿官网首页的Demo测试的。
另外，我在虚拟机里使用IE6测试，插入连接这个功能也是没有问题的，虽然界面上差一些。

你可以再用其他多个机器试一下，如果实在有问题，麻烦再反馈给我。

**Comment by wangfupeng1988** [comment]
提问者长时间不回复，暂时关闭。有问题再重新提问。
