### ISSUE TITLE
【BUG】星号样式覆盖

### ISSUE THREAD

**Issue by fulicat** [wangfupeng1988/wangEditor#551]
wangEditor编辑器有个致命的问题， 只要页面引用的样式里写过这样的重置，编辑器里再怎么设置都是无效的，如下
```
星号 * {
    font-size:12px;
    font-familay: simsun;
    ......
}
```

分析：其他编辑器是用利用空白iframe代理处理当前编辑器的内容显示区域，能有效避免外部编辑器的干扰；

ps:  用 星号 * 来重置全局样式是不好的，但是还是很多人这样写，存在这样的场景；

**Comment by wangfupeng1988** [comment]
看看这样能否解决 http://www.kancloud.cn/wangfupeng/wangeditor2/131075
