### ISSUE TITLE
粘贴的时候自带换行，这个怎么解决呀？

### ISSUE THREAD

**Issue by skyroom** [wangfupeng1988/wangEditor#552]
我看到官方demo也有这个问题。应该就不是我自己的代码的问题了。麻烦告知

**Comment by wangfupeng1988** [comment]
具体什么场景？我这边该如何复现？

**Comment by skyroom** [comment]
比如，在官方demo页面，我的编辑器里面刚开始只有“我本来的文字”，然后我复制（ctrl+c）官方demo页面标题栏中的“Web富文本编辑器”这几个字，然后粘贴（ctrl+v）到编辑器中的“来”字和“的”字的中间，就会出现一个换行（源代码中多了一个p标签）。猜测应该是我粘贴的文字自带样式并和我的编辑器中的原来的文字的样式不一样，所以就会多一个p标签吧。

**Comment by wangfupeng1988** [comment]
试了，确实有这个问题。

这个版本我不打算做大的改动了，修改一些bug稳定为主。

我即将启动下一次升级，会对目前样式操作、文字操作积攒的一系列问题，重新做一遍设计，更好的应对之后的需求。因此，我想再下一次升级中将这个问题改掉。我已经记录下了。

感谢你的反馈！

**Comment by skyroom** [comment]
客气，愿wangEditor越来越好。
