### ISSUE TITLE
代码块显示无法换行的问题

### ISSUE THREAD

**Issue by sswaiting** [wangfupeng1988/wangEditor#555]
作者你好，感谢你提供的优秀的编辑器，最近在使用的时候遇到了以下问题，没有找到如何发图，简单描述如下：
1、在编辑器中点击插入代码块插入了一段代码，在编辑器中可以正常显示。
2、使用手册中提到的：editor.$txt.html()获取到所有html并发动到服务器，服务器存入数据库[redis]。
3、在显示页面拉取从服务器数据库得到的html块，并显示在一个div中，其中一段是之前插入的代码块。
4、这时背景颜色和关键字变色都可以正确识别，但是无法换行，所有的都挤在一行里，如果加了pre标签的自动换行，会变成普通的文本段落那种换行，无法达到在编辑器里显示时有缩进有换行的视觉效果。[页面引用的highlighter.js的js和css库显示高亮]。

第一次用代码块高亮这个功能，对于pre标签的换行理解不是很到位，是否因为存到数据库里之后换行消失了，再用于显示的时候就无法换行，请问这类问题是否有好的解决方法。
加了你的交流群但是没有一个人说话，看到群公告还是来这里提出问题了。

**Comment by wangfupeng1988** [comment]
> 是否因为存到数据库里之后换行消失了，再用于显示的时候就无法换行，请问这类问题是否有好的解决方法

存储的时候，把换行符号带着，不要去掉。

**Comment by sswaiting** [comment]
谢谢^_^ 已经解决了问题 是储存到数据库的时候换行符被转义了丢失了 再取出来就没了

**Comment by lihaihuahhhh** [comment]
我的问题也是类似，不过我发现editor生成的代码块里面没有br换行啥的，所以前端展示没有换行，我寻思着可不可以代码块要是有样式就好了，刚使用，不知道我哪里没设置，难受

**Comment by sswaiting** [comment]
***@***.***。
