### ISSUE TITLE
样式没有加载进来

### ISSUE THREAD

**Issue by cheqianxiao** [wangfupeng1988/wangEditor#556]
我使用npm install wangeditor --save安装了编辑器，require('wangeditor')后 ，样式没有加载进来

**Comment by infeng** [comment]
还要引用样式的，参考 http://www.kancloud.cn/wangfupeng/wangeditor2/126637

**Comment by cheqianxiao** [comment]
但是文档中说使用npm环境，require('wangeditor')后编辑器已经自动引入了jquery和css文件

**Comment by infeng** [comment]
你使用什么工具进行打包的？

**Comment by cheqianxiao** [comment]
gulp
