### ISSUE TITLE
图片上传请增加一个 beforeUpload的钩子

### ISSUE THREAD

**Issue by guopi** [wangfupeng1988/wangEditor#557]
经常在upload之前需要更新 header或者data里面的数据，
比如一个3分钟变一次的身份认证token。

如果用户使用editor时间较长，就会失效。

**Comment by wangfupeng1988** [comment]
目前的版本就不做大改动了，以稳定为主。接下来会启动下一个版本升级，会加上的，你的需求我已经记录下了。这个需求还是比较常用的。
