### ISSUE TITLE
截屏图片，粘贴的时候图片变色

### ISSUE THREAD

**Issue by yuweilan** [wangfupeng1988/wangEditor#561]
使用的是antdesign,
ant版本  "antd": "~1.6.2",
react版本 "react": "^15.0.2",
   "wangeditor": "^2.1.22"

**Comment by wangfupeng1988** [comment]
我暂时还没有使用 ant 的环境来试验编辑器，我试验之后给你回复

感谢反馈

**Comment by wangfupeng1988** [comment]
非常抱歉，v2 此后不维护了，已经升级到 v3 版本了，个人业余精力有限，还请体谅。
