### ISSUE TITLE
编辑器里插入的图片怎样隐藏掉图片工具栏

### ISSUE THREAD

**Issue by Mak-Lohho** [wangfupeng1988/wangEditor#563]
在编辑器里插入图片后，我不想显示这个图片工具栏和拉伸图片宽高的圆点，请问怎么隐藏掉？

![image](https://cloud.githubusercontent.com/assets/11450515/22198368/3cda73a6-e191-11e6-898b-78eebc0f62e9.png)

**Comment by wangfupeng1988** [comment]
这个暂时没法隐藏 😂

**Comment by wangfupeng1988** [comment]
非常抱歉，v2 此后不维护了，已经升级到 v3 版本了，个人业余精力有限，还请体谅。

建议升级 v3 版本，v3 解决了这一问题
