### ISSUE TITLE
使用onchange遇到问题

### ISSUE THREAD

**Issue by jjljyn** [wangfupeng1988/wangEditor#568]
你好，
我在使用onchange的时候遇到一点问题，
在文本框没有初始值的时候，每敲一个字母光标都会跳到最开始的位置；
而文本框有初始值的时候，不会出现这个情况。

**Comment by bulaye** [comment]
可以用editor.$txt.on('focusout', function () {})

**Comment by wangfupeng1988** [comment]
> 在文本框没有初始值的时候

具体啥情况，最好代码描述一下，否则我无法复现。

----

如果能用初始值来临时解决这一问题，建议使用。因为我接下来会花精力做升级，一些不管紧要的bug就先放一放了。
