### ISSUE TITLE
可否考虑增加上传附件和光标处插入内容的接口

### ISSUE THREAD

**Issue by praglody** [wangfupeng1988/wangEditor#569]
您好, 可否考虑增加上传附件和光标处插入内容的接口

**Comment by wangfupeng1988** [comment]
上传附件参见这里 http://www.kancloud.cn/wangfupeng/wangeditor2/119079

光标出插入内容的接口，这个版本不会加，接下来的升级会考虑开放，我记录下。

感谢反馈

**Comment by wangfupeng1988** [comment]
v5 已经支持上传附件 https://github.com/wangeditor-team/wangEditor-plugin-upload-attachment

v4 不再升级新功能了
