### ISSUE TITLE
 关于跨域方式插入图片时的form表单的位置问题

### ISSUE THREAD

**Issue by kevin82008** [wangfupeng1988/wangEditor#57]
如果把整个wangEditor做为某个具体form表单的一个控件，那么，在跨域方式插入图片时，生成的form表单就形成了form嵌套，就会衍生其他问题

是否可以考虑把 modalContainer 直接放到 document.body 然后弹出的时候再固定位置到正中间显示，这样就可以把需要弹出窗口的菜单的dom节点和form节点独立。

**Comment by wangfupeng1988** [comment]
我今晚回去研究一下，有结果在此回复

**Comment by wangfupeng1988** [comment]
1.3.12版本已经更新了，采纳了你的建议，将modalcontainer放在了body最下面。去下载更新吧。
有问题再提交。
