### ISSUE TITLE
ant.design为XHTML格式时，设置字号不可用

### ISSUE THREAD

**Issue by hsilence** [wangfupeng1988/wangEditor#570]
![image](https://cloud.githubusercontent.com/assets/20702713/22731524/ee316cb8-ee25-11e6-86f9-1a2228de8ed8.png)
无法更改字号

**Comment by hsilence** [comment]
W3C规定xhtml形式时，无法使用font标签中的size   而是应该使用css代替
![image](https://cloud.githubusercontent.com/assets/20702713/22731652/5d2c43c2-ee26-11e6-9378-024fa8e10caa.png)

**Comment by wangfupeng1988** [comment]
使用`<font size="7">`是浏览器的`document.execCommand`这个 API 的结果，而这个 API 目前已经好久没更新，跟不上标准的进化。

这个版本中，这个问题目前没法修改。我会在下一个版本中将这些不符合标准的情况全部自己实现，会尽快做出下一个版本。

感谢反馈和支持！
