### ISSUE TITLE
页面中有多个编辑器highlightjs重复添加到DOM节点问题

### ISSUE THREAD

**Issue by d4smart** [wangfupeng1988/wangEditor#571]
如果在一个页面加入多个编辑器的话，highlightjs会被重复添加到DOM节点。

代码中有这样的防止重复加载的方法
```javascript
if (window.hljs) {
    // 不要重复加载
    return;
}
```
但在dom生成阶段，在已经添加了相关script dom节点后（前一个编辑器的加载），并没有返回

我加入了一个查询dom节点的方法，加入了以下代码
```javascript
var scripts = document.getElementsByTagName('script');
var length = scripts.length;
if(scripts[length-1].attributes.src.value == "/js/highlight.min.js") {
   return;
}
```
好像可以解决问题，不过不是很好
请问有其他解决方法吗？

**Comment by wangfupeng1988** [comment]
一个页面多个编辑器的时候确实有一些问题，大家反馈的也比较多，是之前设计时没考虑到多编辑器各种场景导致的。

这个问题既然你有临时解决方案，就先这样，我接下来会尽快做出下一个大版本，把目前的设计问题都统一解决掉。

感谢反馈！
