### ISSUE TITLE
图片上传跨域出现问题

### ISSUE THREAD

**Issue by VersionFish** [wangfupeng1988/wangEditor#572]
问题描述：  
1、服务器设置Access-Control-Allow-Origin:*
![image](https://cloud.githubusercontent.com/assets/8171509/22780786/ec1a7bba-eefa-11e6-9b62-94ba5b895fad.png)  
2、上传图片报以下错误：Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://127.0.0.1:5000' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.  
3、定位一下问题，当xhr.withCredentials = true;设置为true的情况下，是不允许设置Access-Control-Allow-Origin:*，但是插件源码中将xhr.withCredentials = true;写死了，手动更改源码xhr.withCredentials = false;就可以上传成功

求助：
1、是否有什么办法可以解决这个问题，除了将＊设置成具体域名？
2、能否将xhr.withCredentials搞成可传参配置的形式？

**Comment by VersionFish** [comment]
@wangfupeng1988 @CongAn @GameHoo @Viao @arliang 各路大神，帮忙看看咯

**Comment by sinchang** [comment]
@VersionFish 今天同样遇到该问题，请问你解决了吗？

**Comment by VersionFish** [comment]
@sinchang 解决了，就是修改源码，修改成xhr.withCredentials = false;不过这样不好

**Comment by wangfupeng1988** [comment]
我已经将这里的改为

```
xhr.withCredentials = editor.config.withCredentials || true;
```

等待下一次版本的更新

**Comment by VersionFish** [comment]
@wangfupeng1988 好激动可以等到您的回复，谢谢，期待你下一版本的更新，超赞，支持～

**Comment by wangfupeng1988** [comment]
去下载最新的版本，这个已经改了发布了。

**Comment by VersionFish** [comment]
@wangfupeng1988 嗯，看到了，赞～

**Comment by VersionFish** [comment]
@wangfupeng1988 xhr.withCredentials = editor.config.withCredentials || true; 这里有问题，false || true = true，无法解决问题。。需要xhr.withCredentials = editor.config.withCredentials && true; 才对～

**Comment by wangfupeng1988** [comment]
@VersionFish 握草，这事儿怪我，脑袋短路了。你先自己改一下源码哈，我下次发版一起改了。

**Comment by VersionFish** [comment]
@wangfupeng1988 嗯 好的，thx

**Comment by chenhao6263** [comment]
我这边也遇到了这个问题,修改成了xhr.withCredentials = editor.config.withCredentials && true; 也不行还是报楼主的错

**Comment by VersionFish** [comment]
@chenhao6263 那你的editor.config.withCredentials有没有配置成false了
