### ISSUE TITLE
图标不显示，文档问题？

### ISSUE THREAD

**Issue by misakax** [wangfupeng1988/wangEditor#573]
文档的意思是fonts目录应该是css的子目录，但是我这样做了还是没有显示图标。

当我把fonts目录移动到上一级，即fonts和css同级时，图标就显示了。

是不是文档有错误？

![default](https://cloud.githubusercontent.com/assets/5242229/22863857/57ab34e4-f182-11e6-8c7b-ee5e0027a098.JPG)

**Comment by wangfupeng1988** [comment]
看一下css引用fonts的路径对不对，文档肯定没问题，这都是被很多用户验证过的。
