### ISSUE TITLE
无法调整多行行高和缩进

### ISSUE THREAD

**Issue by misakax** [wangfupeng1988/wangEditor#574]
行高和缩进按钮只能调整单行的行高和缩进，非常非常非常不友好

**Comment by wangfupeng1988** [comment]
行高和缩进仅仅是开发插件时的一个例子，我写的简单便于大家更快的了解。这种非常用功能，建议自己使用插件来实现。

**Comment by LancelotLewis** [comment]
@wangfupeng1988 我也在找多行行高的设置方法，也尝试查看插件的源代码，但是根据文档中的API来看，`getRangeElem`方法获取到的一定是多行外层的元素，也就是根的`div`元素，无法获取到对应几行的元素本身，所以目前看来，是没有办法完成多行行高设置的功能了
