### ISSUE TITLE
插入代码转义丢失"</"问题

### ISSUE THREAD

**Issue by Realybig** [wangfupeng1988/wangEditor#576]
正常插入html代码时候保存后在前台显示丢失了"</"，不知道是不是转义问题，求大佬指教。如图：
![qq 20170213143151](https://cloud.githubusercontent.com/assets/10878451/22873251/cd65411c-f1f9-11e6-9a22-a70a85500637.png)
![qq 20170213143226](https://cloud.githubusercontent.com/assets/10878451/22873267/f03f6bf4-f1f9-11e6-88c4-a2643587c2c7.png)

**Comment by fesiong** [comment]
经测试，没有发现有此问题。你出现这个问题很有可能是你后台的过滤写得不对
<img width="1069" alt="2017-02-14 9 30 17" src="https://cloud.githubusercontent.com/assets/9912496/22910938/4c2bcaf4-f298-11e6-812b-f403e61d9003.png">
<img width="902" alt="2017-02-14 9 29 48" src="https://cloud.githubusercontent.com/assets/9912496/22910937/4c2ad07c-f298-11e6-95b5-4321dc52866f.png">

**Comment by wangfupeng1988** [comment]
新咨询的问题，请另外提交一个issue
