### ISSUE TITLE
关于滑动页面，编辑器操作菜单栏吸附最顶端的问题

### ISSUE THREAD

**Issue by liu-weihao** [wangfupeng1988/wangEditor#577]
![image](https://cloud.githubusercontent.com/assets/20028139/22913077/b32599a0-f2a3-11e6-9254-934bacf043e9.png)

> 正常情况下，是上述这样子的。当我再把页面往下滑动一点点，就出现了下面的异常情况：

![image](https://cloud.githubusercontent.com/assets/20028139/22913174/33685a80-f2a4-11e6-9a89-8b69a8eedc35.png)

```
  var editor = $.editor.create({
			target: "description",
			uploadUrl: contextPath + "/common/file/upload.web",
			params: {
				"picType": "GOODS_DETAIL"
			},
			fileName: "file"
	});
```

**Comment by qq450979309** [comment]
我也遇到这样的问题。页面下滚的时候，编辑器的菜单就会吸附到屏幕上方。
我用的是vue的组件那个demo

**Comment by liu-weihao** [comment]
```
.wangEditor-menu-container {
    top:auto !important;
    position:static !important
}
```

在 wangEditor/dist/css/wangEditor.css中修改
