### ISSUE TITLE
超链接修改文本问题

### ISSUE THREAD

**Issue by cooper1x** [wangfupeng1988/wangEditor#579]
![image](https://cloud.githubusercontent.com/assets/9080789/22932441/e3e2fd1c-f302-11e6-8ce7-6f5540d239ae.png)
设置过的超链接不能编辑修改文本内容

**Comment by wangfupeng1988** [comment]
没有遇到过，你是怎么复现的？

**Comment by cooper1x** [comment]
先设置一个文本超链接，第二次设置会出现这个情况

**Comment by wangfupeng1988** [comment]
你是什么浏览器？我再chrome下没有发现你这种情况啊

**Comment by cooper1x** [comment]
我用的是chrome56。第一次设置没问题，简单说就是第二个修改超链接文本的时候文本被锁定不能修改。

**Comment by wangfupeng1988** [comment]
非常抱歉，v2 此后不维护了，已经升级到 v3 版本了，个人业余精力有限，还请体谅。
