### ISSUE TITLE
已发布内容的二次编辑，查看源代码为空？

### ISSUE THREAD

**Issue by job111lyckk1** [wangfupeng1988/wangEditor#58]
已经发布的内容，在编辑的时候可以获取内容，但是点击第一个查看源码，里面是空的~请教官方demo也是这个么

**Comment by wangfupeng1988** [comment]
我今晚回去做一个demo验证一下吧，到时候在此回复

**Comment by wangfupeng1988** [comment]
已经发布的内容，再次编辑显示在页面上有两种方式：第一，html方式；第二，js方式。文档中有。

对于这两个的例子我都做了测试，查看源码是没有问题的，你可以去看看文档中的链接demo

http://www.kancloud.cn/wangfupeng/wangeditor/65732

http://www.kancloud.cn/wangfupeng/wangeditor/65733

**Comment by wangfupeng1988** [comment]
提问者长时间不回复，暂时关闭问题

**Comment by sumengliang** [comment]
我的情况不是查看源码为空 获得了内容 但是到编辑器中 内容中的html标签没有解析出来 很混乱 和post提交前点击源码的内容一样 但是在此编辑是把内容当普通文本 而不解析 点击源码 只会更混乱 ？？？
是和angular集成的BTW
