### ISSUE TITLE
样式与其他库冲突 materializecss

### ISSUE THREAD

**Issue by Parasis** [wangfupeng1988/wangEditor#581]
本人正在使用materializecss开发一个页面，富文本编辑器选择了wangEditor，
无自己编写的样式，
`<link href="/css/materialize.css" type="text/css" rel="stylesheet"/>`
`<link href="/css/wangEditor.min.css" type="text/css" rel="stylesheet"/>`
浏览器渲染页面之后icon的排布变成竖着的，效果如下
![image](https://cloud.githubusercontent.com/assets/16928562/23004993/a260701c-f434-11e6-83f2-2a32962e2bc8.png)

**Comment by Parasis** [comment]
# 解决方法：
添加如下内联样式
`.clearfix {clear: none;}`

**Comment by wangfupeng1988** [comment]
帮！
