### ISSUE TITLE
使用英语设置图片上传里的文字没有变过来

### ISSUE THREAD

**Issue by tomoya92** [wangfupeng1988/wangEditor#583]
```
// 使用英语
editor.config.lang = wangEditor.langs['en'];
```
这样设置了，菜单都变了，但上传图片的弹出层没变过来
![image](https://cloud.githubusercontent.com/assets/6915570/23067899/3cd6b5de-f55c-11e6-95b5-19258223542c.png)

**Comment by wangfupeng1988** [comment]
已经修改，关注下一个版本的发布
