### ISSUE TITLE
上传图片功能，建议加入手动填写ALT，自动获取图片宽高功能！

### ISSUE THREAD

**Issue by jbksir** [wangfupeng1988/wangEditor#584]
上传图片功能，建议加入手动填写ALT，自动获取图片宽高功能！

**Comment by wangfupeng1988** [comment]
这个功能常见于早期的编辑器，它们追求大而全，现在比较精简的编辑器都没有这些功能了，wangEditor求简，因此不会加。

如果有很多用户需要，我会再近期升级时，考虑加入扩展机制来实现这个功能。
