### ISSUE TITLE
能不能把重复加载的alert改成console.log

### ISSUE THREAD

**Issue by maybeTomorrow** [wangfupeng1988/wangEditor#588]
在recat服务端渲染的时候，会加载两次js。于是就会弹框。

**Comment by wangfupeng1988** [comment]
你暂时先自己在代码中改一下吧。因为这个版本是一个强制的必须引用一次，如果改成 console.log 很多用户估计会忽略。

我下次版本升级会优化这一点，遇到第二次引用直接省略

**Comment by wangfupeng1988** [comment]
升级 v3 版本吧，v3 没有这个问题了
