### ISSUE TITLE
wangeditor和jquery validation有冲突

### ISSUE THREAD

**Issue by terrymyth** [wangfupeng1988/wangEditor#59]
wangeditor和jquery validation有冲突，导致两个都不能用

**Comment by wangfupeng1988** [comment]
我记得之前有人提出过这样一个问题，也是遇到jquery validation之后出现的问题。因此，首先你要确定是否下载了最新的版本。
---------------------
另外，提交问题时，不要出现这种『一句话问题』的情况，QQ群公告里面也明确写了。
有问题要把问题的场景尽量描述详细，并且最好有截图、关键代码、浏览器信息。
否则这样来回的回复，浪费时间。

**Comment by wangfupeng1988** [comment]
1.3.12版本的更新，将wangEditor里面自己添加的form都拿出来了，这时候再提交应该不会又什么影响了。你去下载更新试试看。

**Comment by terrymyth** [comment]
yeah，谢谢！
我已经跟技术说了，让他去尝试一下。谢谢了

**Comment by wangfupeng1988** [comment]
提问者长时间不回复，暂时关闭问题。

**Comment by terrymyth** [comment]
谢谢！已经搞定了！完美融合！谢谢！
