### ISSUE TITLE
可否增加个图片开始上传时 的api？

### ISSUE THREAD

**Issue by panghongye** [wangfupeng1988/wangEditor#590]
希望增加个图片上传时能执行 一个传入回调 的api 因为在上传时 我想让  “发送按钮”  禁止点击

**Comment by wangfupeng1988** [comment]
这个当前版本暂时还没有，也不打算在当前版本做了。即将规划下一个版本的升级，到时候会加上这个需求，我已经记下了。感谢你的反馈！
