### ISSUE TITLE
上传图片成功但是返回空数组

### ISSUE THREAD

**Issue by mohong** [wangfupeng1988/wangEditor#592]
在postman测试接口成功
![postman下返回正确的数据](http://ob9qd20l4.bkt.clouddn.com/p003.jpg)

在页面的上传图片控件中上传，成功，但是返回空数组（理想状态是返回图片地址）
![控制台打印的异常](http://ob9qd20l4.bkt.clouddn.com/p002.jpg)

**Comment by mohong** [comment]
后来我想了一下，可能是上传了空的字段，有办法解决吗

**Comment by wangfupeng1988** [comment]
看看这里 http://www.kancloud.cn/wangfupeng/wangeditor2/131049
