### ISSUE TITLE
关于内容内添加script标签这个问题

### ISSUE THREAD

**Issue by annofy** [wangfupeng1988/wangEditor#594]
添加script 标签 内容后，第一次显示是正常的，当再把编辑器生成的html字符串再次设置到编辑器的时候，编辑器竟然把script标签当成网页导入的js脚本资源。

**Comment by wangfupeng1988** [comment]
我在官网添加一个<script/>之后源代码是这样的

```
<p><br></p><pre style="max-width: 100%;"><code class="javascript hljs" codemark="1">&lt;script/&gt;</code></pre><p><br></p><p><br></p>
```

这样的源代码被存储后台。再次展示时，肯定从后台获取了，然后再赋值给编辑器的内容，没问题啊

**Comment by annofy** [comment]
是这样的，我是从富文本编辑器里面的 【代码】或者【文本】里面写入比如:<script src="http://xxx.com/xx.js"></script> 保存到mongodb中，然后从mongodb中读取html字符串，通过ejs的模板替换功能<%- html字符串 %>这样，直接给textarea初始化了内容，这个阶段是正常的。当我再次把带有script这段文本重新放入您的富文本编辑器中，也就是<textarea>文本内容</textarea>，这样初始化textarea变成富文本编辑器，然后编辑器把标签自动识别了网页导入的script脚本资源，如下图:
![image](https://cloud.githubusercontent.com/assets/22249411/23692495/1d0b4be0-040a-11e7-90af-822e4fba7df2.png)
再次编辑效果您看:
![image](https://cloud.githubusercontent.com/assets/22249411/23692536/55848e0a-040a-11e7-94c0-8e41538f7b47.png)
您看这里是正常的未编辑第一次生成的页面:
![image](https://cloud.githubusercontent.com/assets/22249411/23692571/8375a1be-040a-11e7-8f73-40aafc7f16d2.png)
再次导入副文本编辑器的时候:
![image](https://cloud.githubusercontent.com/assets/22249411/23692602/ad95735c-040a-11e7-9473-5e22287c6447.png)

这是ejs中样子:
![image](https://cloud.githubusercontent.com/assets/22249411/23692641/e57ad500-040a-11e7-868f-80ebe9d724eb.png)

这是editor配置
![image](https://cloud.githubusercontent.com/assets/22249411/23692668/040cde50-040b-11e7-90a9-739e69bf1d81.png)
这是配置文件:
![image](https://cloud.githubusercontent.com/assets/22249411/23692693/1e86d89e-040b-11e7-81d4-dfd481bc7e7d.png)

是我哪里写错了么？

**Comment by annofy** [comment]
![image](https://cloud.githubusercontent.com/assets/22249411/23692799/cc49123a-040b-11e7-86b5-779ad047baa6.png)

![image](https://cloud.githubusercontent.com/assets/22249411/23692805/d544b948-040b-11e7-8f73-987417e067e3.png)

官网演示直接消失了

**Comment by wangfupeng1988** [comment]
我再官网演示：

我在正常状态下输入以下文字：

```
这里插入了script脚本
<script src="http://xxx.com/xx.js"></script>
```

然后我查看编辑器的源码，出来的是这个：

```
<p>这里插入了script脚本</p><p>&lt;script src="http://xxx.com/xx.js"&gt;&lt;/script&gt;<br></p><p><br></p>
```

以上这一步，你是否跟我一样？

**Comment by annofy** [comment]
得到的是没有问题的。就是再次放入其中初始化的时候，出问题的

**Comment by annofy** [comment]
您可以看，就是我发的图片里面都是把这些放入其中，然后出问题，并不是获取问题。

**Comment by wangfupeng1988** [comment]
非常抱歉，v2 此后不维护了，已经升级到 v3 版本了，个人业余精力有限，还请体谅。
