### ISSUE TITLE
位置获取导致jquery验证报错

### ISSUE THREAD

**Issue by OckhamRazor** [wangfupeng1988/wangEditor#595]
点击位置选项（无论最后是否点击提交），都会在页面中添加三个表单（input）用于存储地图信息。导致jquery 验证时出现报错，从jquery validate库的log信息来看原因是该元素为undefined。这个editor组件用着很舒服

**Comment by wangfupeng1988** [comment]
> 从jquery validate库的log信息来看原因是该元素为undefined

jquery validate 这个插件一直报着有问题，我怀疑是否是这个插件的bug，因为提交的时候，这些 input 都是在一个 display:none 的 div 中的，怎么也需要验证？

**Comment by wangfupeng1988** [comment]
我再跟踪一下这个问题吧，另外你有好的解决方法的时候麻烦告诉我一声。

**Comment by OckhamRazor** [comment]
通过给表单设置disabled属性可以跳过验证和表单提交，可行否

**Comment by wangfupeng1988** [comment]
非常抱歉，v2 此后不维护了，已经升级到 v3 版本了，个人业余精力有限，还请体谅。
