### ISSUE TITLE
配置withCredentials为false没卵用

### ISSUE THREAD

**Issue by 0000QI** [wangfupeng1988/wangEditor#596]
`            // 跨域上传时，传cookie
            xhr.withCredentials = editor.config.withCredentials || true;
`
以上是wangEditor-2.1.23的源码中的一段，这一段意思岂不是只有当 editor.config.withCredentials为true时才能发挥作用，如果editor.config.withCredentials = false , 那么xhr.withCredentials = false||true,即xhr.withCredentials = true;
综上，配置editor.config.withCredentials没什么卵用，能够及时改掉就最好了，若有什么说的不对的还希望指出。

**Comment by wangfupeng1988** [comment]
先自己在源码中改一下，我本地已经改正了，只不过还没有发布。下一个小版本一起发布。

**Comment by wangfupeng1988** [comment]
建议升级 v3 版本，v3 解决了这一问题

**Comment by 0000QI** [comment]
了解，谢啦，支持大神
