### ISSUE TITLE
图片上传，今天刚接触这个，上传图片用了示例代码，一直报错

### ISSUE THREAD

**Issue by wwp0730** [wangfupeng1988/wangEditor#597]
![image](https://cloud.githubusercontent.com/assets/25031903/23696956/cd8cb7ae-0420-11e7-9f88-2a3861f21314.png)
上传本地照片报错！，网络图片没问题，报错代码如下；
![image](https://cloud.githubusercontent.com/assets/25031903/23696997/f6018052-0420-11e7-82a8-eea1ab0f81a3.png)
前端代码如下：
![image](https://cloud.githubusercontent.com/assets/25031903/23697050/2d5a9944-0421-11e7-97f0-a125e2acbd0c.png)
使用tomcat9  具体不知这个参数有何用途 editor.config.uploadImgFileName

**Comment by wangfupeng1988** [comment]
看文档中，有一篇专门讲上传图片报错，去看看那几个排错步骤

**Comment by wangfupeng1988** [comment]
> 看文档中，有一篇专门讲上传图片报错，去看看那几个排错步骤
 
根据这个查一查，后台的问题需要自己排查
