### ISSUE TITLE
如何把焦点定位在指定的位置

### ISSUE THREAD

**Issue by inteye** [wangfupeng1988/wangEditor#60]
我插入了一段代码，并且在结尾加了&lt;p&gt;&lt;/p&gt;标签，如何让焦点出现在&lt;p&gt;标签里面

**Comment by wangfupeng1988** [comment]
暂时还没有提供定位光标的API，后续重构会加上这个接口。

PS：这种通过程序自动定位焦点的场景比较少吧，一般用户都是使用鼠标来定位光标位置。可以说说你的想法

**Comment by inteye** [comment]
我们在编辑器中插入了一段样式组件的代码，希望用户能够添加完这个样式之后，可以直接继续在下一行编辑，而不是手动打回车，否则浏览器会复制上面的class和样式。有没有什么办法让我能定位光标？多谢了，非常急

**Comment by wangfupeng1988** [comment]
告诉你一些方法，你自己去解决吧。

首先，你无论用什么方法来定位光标，你都需要获取到编辑器这个txt，如下获取：
```js
var editor = $('#textarea1').wangEditor();
var $txt = editor.$txt;  //这样就能取出编辑器的编辑区域的这个div元素，可以 console.log 一下试试
```

其次，要通过js定位光标，需要了解js中的两部分知识点——selection和range 。这两个的知识内容就需要你来自己做了，可以百度搜索相关文档，例如 http://www.zhangxinxu.com/wordpress/2011/04/js-range-html%E6%96%87%E6%A1%A3%E6%96%87%E5%AD%97%E5%86%85%E5%AE%B9%E9%80%89%E4%B8%AD%E3%80%81%E5%BA%93%E5%8F%8A%E5%BA%94%E7%94%A8%E4%BB%8B%E7%BB%8D/

**Comment by inteye** [comment]
多谢多谢

**Comment by angry-bread** [comment]
mark
