### ISSUE TITLE
上传图片删除问题

### ISSUE THREAD

**Issue by liyuanqing** [wangfupeng1988/wangEditor#601]
图片上传后，如果不想要这个图片了，回退删除图片，那么如何监控这个删除事件，同时删除服务器上的图片？

**Comment by 2736629976** [comment]
同问啊，你有好的解决方法吗、

**Comment by wangfupeng1988** [comment]
这个在前端真的没法监控。

给你出一个建议：保存编辑内容后，后端拿到文章的内容，然后正则筛选出里面所有上传的图片，然后再和已经上传的图片对比，即可找到无用的图片文件，然后删除。

**Comment by 5780358** [comment]
那如果是用户编辑之后没有提交呢？后端就拿不到文章内容进行筛选删除了。
