### ISSUE TITLE
onchange is delayed, doesn't work as other dom, e.g. input

### ISSUE THREAD

**Issue by yuanjianpeng** [wangfupeng1988/wangEditor#602]
register onchange event:   
        editor.onchange = function () {
            editor_changed = 1;
        }

call:
    editor.$txt.html("");
    editor_changed = 0;

editor_changed will be 1, not 0, so I can't manually clear the change flag.
but onchange works on a input dom. wangEditor's onchange is different from others.

I read the source code, actually I should do like this:
    // to work around wangEditor's bug
    setTimeout(function(){
        editor_changed = 0;
    }, 105);

**Comment by wangfupeng1988** [comment]
建议升级 v3 版本，v3 解决了这一问题
