### ISSUE TITLE
能否做到编辑css和发布css分离

### ISSUE THREAD

**Issue by yuanjianpeng** [wangfupeng1988/wangEditor#603]
我编辑的文章的时候使用编辑css，这个css是最全的，包含菜单等。
但是发布文章之后，使用发布css，只需要少量的文章用到的样式。 并且支持嵌入到html，因为提供文章离线下载的时候，css就包含在html中，不需要额外的大css了。

**Comment by wangfupeng1988** [comment]
建议升级 v3 版本，v3 解决了这一问题
