### ISSUE TITLE
第一行字用斜体或者粗体等样式， 会导致不被p标签包裹

### ISSUE THREAD

**Issue by likun7981** [wangfupeng1988/wangEditor#607]
最后源代码成这样了
```
<b>123123123</b><p><b>123123123123</b></p><p></p><p><br></p><p></p>
```
然后样式就有问题了

**Comment by likun7981** [comment]
linehight会有问题

**Comment by wangfupeng1988** [comment]
到底有啥问题？详细描述出来

**Comment by likun7981** [comment]
你的样式表  不是给的 [p *](
https://github.com/wangfupeng1988/wangEditor/blob/master/src/css/wangEditor.css#L219) 下面的`line-height:1.8 ` 如果出现上面的问题， __line-height__ 就不对了，我的问题就是，应该文本域里面的东西都应该被 __p__ 包裹吧
