### ISSUE TITLE
firefox 51.0.1 粘贴截图多一张重复图片

### ISSUE THREAD

**Issue by old-bin** [wangfupeng1988/wangEditor#609]
如题，应该是在此状态下没有阻止默认事件: ev.preventDefault()  or return false;

**Comment by wangfupeng1988** [comment]
我业余看看这个问题吧，有答案再次回复。

**Comment by Missyanwen** [comment]
在firefox下我也遇到这个问题 了！！一张是服务器上的图片一个是base64位的，请问@wangfupeng1988是否已修复，如没有修复@old-bin在源代码里哪里加阻止默认事件？

**Comment by c3h0310** [comment]
我也遇到这个问题了,除了图片, 粘贴文字的时候,也会出现多份内容;

**Comment by wangfupeng1988** [comment]
还没有修复，下次发版之前看看这个问题，如果找到原因，就下次发版解决，注意关注新版内容。

**Comment by wangfupeng1988** [comment]
楼主的问题，我windows和mac上都没有复现

**Comment by wangfupeng1988** [comment]
非常抱歉，v2 此后不维护了，已经升级到 v3 版本了，个人业余精力有限，还请体谅。
