### ISSUE TITLE
插入代码保存后无换行效果，更新后也无换行效果

### ISSUE THREAD

**Issue by eyblog** [wangfupeng1988/wangEditor#61]
![1](https://cloud.githubusercontent.com/assets/11583677/10709154/42e627cc-7a54-11e5-8994-9ed2dd15e5b7.png)

第二张图片一直上传不上来，就是点了那个更新之后所有代码就变成一行了。。不点更新保存到数据库，再显示出来也是一样

**Comment by wangfupeng1988** [comment]
好，我看到这个问题了，今晚调试一下。有结果了给你回复。

**Comment by wangfupeng1988** [comment]
这个bug已经修改，可以通过以下链接验证：http://www.wangeditor.com/wangEditor/test/highlightJS/test.html
