### ISSUE TITLE
可否增加markdown 支持

### ISSUE THREAD

**Issue by liniu** [wangfupeng1988/wangEditor#610]
很简洁的一个编辑，可否增加markdown 支持？

**Comment by wangfupeng1988** [comment]
markdown 和富文本编辑器本来就是两套东西 http://www.kancloud.cn/wangfupeng/wangeditor2/119071

**Comment by liniu** [comment]
谢谢，我的意思是有个配置，可选择是用富文本还是markdown,而不是两者混用。照我想，界面显示层代码应该是差不多，然后一个“内核”，在富文本模式下，点粗体，指令就是插入"<b>abcd</b>",而在markdown 模式下 则 是 插入 “**abcd**” 。

**Comment by wangfupeng1988** [comment]
> 我的意思是有个配置，可选择是用富文本还是markdown,而不是两者混用

这应该是网站级别的配置，而非工具级别的配置。可以参考 jianshu.com 

> 然后一个“内核”，在富文本模式下，点粗体，指令就是插入`<b>abcd</b>`,而在markdown 模式下 则 是 插入 `**abcd** `

不一样的，富文本的操作要依赖于`document.execCommand`，如果要自己实现，那会相当复杂的。

**Comment by liniu** [comment]
好的，谢谢

**Comment by wangfupeng1988** [comment]
markdown 插件已经开发完了 https://github.com/wangeditor-team/wangEditor-plugin-md

不过只能用于 [v5](https://www.wangeditor.com/v5/) 。v5 近期会正式发布，v4 不再做功能升级了。
