### ISSUE TITLE
django后台怎么引用你的编辑器呢？

### ISSUE THREAD

**Issue by b1ueb0y** [wangfupeng1988/wangEditor#611]
console提示editor.config is undefined

**Comment by wangfupeng1988** [comment]
> console提示editor.config is undefined

看看前端 js 程序是否正确引用，这明显是 js 的异常

**Comment by b1ueb0y** [comment]
@wangfupeng1988　正确引用了，可以看看kindeditor的做法，http://hackteam.cn/2016/11/15/Django%E5%90%8E%E5%8F%B0%E4%BD%BF%E7%94%A8kindeditor/

**Comment by wangfupeng1988** [comment]
> 正确引用了，可以看看kindeditor的做法，

能引用 kindeditor，就能引用 wangEditor
