### ISSUE TITLE
跨域上传图片问题

### ISSUE THREAD

**Issue by liyuanqing** [wangfupeng1988/wangEditor#612]
我在用富文本跨域图片上传时，option请求通过了报200，但是不会发出post请求，紧接着就报错是什么原因？报错信息：`XMLHttpRequest cannot load http://192.168.1.235:7111/property/imag. Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://localhost:7777' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.`

**Comment by wangfupeng1988** [comment]
> `The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://localhost:7777' is therefore not allowed access`

从这里找找原因吧，应该是服务器端拒绝了
