### ISSUE TITLE
有考虑过对编辑器做主题吗？

### ISSUE THREAD

**Issue by tomoya92** [wangfupeng1988/wangEditor#613]
目前编辑器就一个css文件，不同的系统肯定会有不同的色彩风格，大大可想过做主题这块？

比如白天，黑夜，bootstrap, Material Design 等等

**Comment by wangfupeng1988** [comment]
这个版本没有这样的计划，下一次升级会让使用者控制样式多一些，不过需要耐心等待一段时间。

**Comment by tomoya92** [comment]
好的，期待
