### ISSUE TITLE
在IE10中出现一个虚线款，怎么解决，谢谢

### ISSUE THREAD

**Issue by StingHi** [wangfupeng1988/wangEditor#614]
在IE10中出现一个虚线款，怎么解决，谢谢
![default](https://cloud.githubusercontent.com/assets/26518814/24079617/ccad0768-0cc6-11e7-8812-8f2ab8bdd3c3.PNG)

**Comment by wangfupeng1988** [comment]
虚线部分，你查看源代码应该是`<div>`元素。要让文字用`<p>`包裹起来，就好了。如果初始化编辑器时候内容为空的话，初始化内容为`<p><br></p>`

**Comment by StingHi** [comment]
有用<p>的，问题还是有

**Comment by StingHi** [comment]
有用`<p>` 但是问题还在

**Comment by Mr-Welson** [comment]
IE11 出现上述问题，请问如何解决 ？ 查看标签是因为<p>嵌套

**Comment by wangfupeng1988** [comment]
看一下有虚线的标签，肯定是`<div>`
