### ISSUE TITLE
编辑器高度能否随内容增加自动扩高？

### ISSUE THREAD

**Issue by qqabcv520** [wangfupeng1988/wangEditor#615]
手动js设置高度自动后，工具栏不能吸附在浏览器顶部了。

**Comment by wangfupeng1988** [comment]
> 编辑器高度能否随内容增加自动扩高

可以的，看看文档

> 手动js设置高度自动后，工具栏不能吸附在浏览器顶部了。

没明白啥意思

**Comment by qqabcv520** [comment]
我设置了
`height: auto`
编辑器初始化之后高度就变成固定的了，
还有就是设置菜单吸顶也没用
`editor.config.menuFixed = 100`
不知道是不是我用了angular的router的原因。

**Comment by qqabcv520** [comment]
查看了源码，编辑器高度自动增加的方法找到了，但是菜单栏浮动的逻辑不会跟随编辑区高度实时更新，修改提交了一个pull request。

**Comment by wangfupeng1988** [comment]
升级的 v3 版本，用户可将菜单和编辑区域分离，更好的解决了这一问题： https://www.kancloud.cn/wangfupeng/wangeditor3/335771
