### ISSUE TITLE
在react中使用，然后跨域上传图片到PHP服务端，一直报错

### ISSUE THREAD

**Issue by wacxt** [wangfupeng1988/wangEditor#617]
ps:在PHP端已经配置了允许跨域了，并且已经测试成功，但是图片上传一直报错

react中的代码如下：
![image](https://cloud.githubusercontent.com/assets/17725632/24089328/b3ddca56-0d70-11e7-83a5-8fb740443b84.png)

报错如下：
```
XMLHttpRequest cannot load http://localhost:8080/v1/upload. Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://localhost:8888' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
```

**Comment by wangfupeng1988** [comment]
> The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://localhost:8888' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute

应该还是跨域的限制，根据这些关键字去查一下吧。或者自己弄一个上传的demo，去试一下跨域是否成功。

**Comment by mrdream24** [comment]
遇到了同样的问题，看似是options的预检请求报了错，真正的post的请求根本没有发出去。
应该是编辑器的bug，因为另一个附件上传的接口并没有报错。

**Comment by wangfupeng1988** [comment]
非常抱歉，v2 此后不维护了，已经升级到 v3 版本了，个人业余精力有限，还请体谅。

**Comment by zhroeqqtw** [comment]
源码6768行
```javascript
 // 跨域上传时，传cookie
  xhr.withCredentials = editor.config.withCredentials || true;

```
当配置withCredentials为false时，依然会取值为true，此处应修改为
```javascript
 // 跨域上传时，传cookie
  xhr.withCredentials = editor.config.withCredentials !== undefined ? editor.config.withCredentials : true;

```
望改进
