### ISSUE TITLE
有没有上传图片前的勾子函数

### ISSUE THREAD

**Issue by zfdai** [wangfupeng1988/wangEditor#619]
因为上传七牛的时候，是在上传之前调用后端的一个接口获取一个token,参数为文件的名称，之后再上传到七牛，现在有没有应急的方法？

**Comment by wangfupeng1988** [comment]
应急方法只能去修改源码了，上传图片的代码在这附近 https://github.com/wangfupeng1988/wangEditor/blob/master/dist/js/wangEditor.js#L6655

**Comment by zfdai** [comment]
好的，谢谢
