### ISSUE TITLE
存在安全问题

### ISSUE THREAD

**Issue by male110** [wangfupeng1988/wangEditor#62]
没有过滤JS。这是个问题。
http://kindeditor.net/demo.php
kindeditor，你在代码模式，输入JS，然后再切换回来看看，JS人家会过滤掉的

建义加入这个功能。

**Comment by eyblog** [comment]
发现这个问题了。进代码模式点更新，其中的js代码被执行了一次，然后才转义

**Comment by wangfupeng1988** [comment]
恩，增加这个功能。默认过滤js，如果想开启，自己增加选项

**Comment by wangfupeng1988** [comment]
该问题已经修复，可以通过官网的demo来验证。

默认情况下，会自动过滤js代码。如果想要取消这种过滤，可参考 http://www.kancloud.cn/wangfupeng/wangeditor/74753
