### ISSUE TITLE
能否不选中文字就可以设置斜体和粗体

### ISSUE THREAD

**Issue by chenhuixfyy** [wangfupeng1988/wangEditor#620]
现在的功能是我要设置斜体或者粗体，需要先输入文字后选择文字后再设置斜体和粗体，能否点击斜体或者粗体后输入状态就是斜体或者粗体，接下来输入的文字就是按照斜体或者粗体来的

**Comment by wangfupeng1988** [comment]
我明白你的意思，这个版本是没有的，现在已经开始的升级，这功能会作为重点升级加上。不过得等待一段时间，有进度我会在qq群和邮箱同步。

**Comment by chenhuixfyy** [comment]
期待！ @wangfupeng1988

**Comment by wangfupeng1988** [comment]
前些天升级的 v3 版本支持了

**Comment by Heart-lin** [comment]
为什么我现在看v4版本还是不支持上诉说的问题....

**Comment by wangfupeng1988** [comment]
@Heart-lin 支持啊，你在官网 demo 试试 https://www.wangeditor.com/
