### ISSUE TITLE
编辑器继承到angularjs中，页面无法双向绑定

### ISSUE THREAD

**Issue by richard1015** [wangfupeng1988/wangEditor#622]
我在编辑器onchange的时候，自己手动修改了里面的值，然后ctrl.viewValue赋值，对应的$scope的实际值变化了，但是您的编辑器没有变化，是否可以回答一下

代码是这样的

![image](https://cloud.githubusercontent.com/assets/13060263/24134928/473f8164-0e42-11e7-9eef-f760f96d0687.png)

**Comment by wangfupeng1988** [comment]
onchange 函数，是在编辑内容变化之后触发的。你在 onchange 函数中拿到 editor.$txt.html() 然后经过处理赋值给 ctrl.$viewValue ，没问题。但是你说“但是您的编辑器没有变化”是什么意思？

**Comment by richard1015** [comment]
不好意思，刚刚看到您的回复，我在  onchange函数中，其实就是想修改一下不符合的图片地址，然后处理后重新赋值  viewValue   但是  ng-mode里面对应的值发生了变化，但是ui显示的值 和ng-model的值不相同，     就是您wangedit编辑器显示的东西与 onchange中修改后的实际值不相同

**Comment by wangfupeng1988** [comment]
建议升级 v3 版本
