### ISSUE TITLE
使用customUpload时无法粘贴图片

### ISSUE THREAD

**Issue by bangbang93** [wangfupeng1988/wangEditor#623]
RT

`editor.config.customUpload = true;`
后无法通过粘贴和拖动上传图片，但是在设置`editor.config.uploadImgUrl`的前提下就可以正常

**Comment by wangfupeng1988** [comment]
> 但是在设置editor.config.uploadImgUrl的前提下就可以正常

那肯定啊，否则图片往哪里传啊？
