### ISSUE TITLE
后台返回图片链接后，编辑器有时能显示，大多数插入不到编辑器！

### ISSUE THREAD

**Issue by RuningToGoals** [wangfupeng1988/wangEditor#624]

**Comment by wangfupeng1988** [comment]
针对错误的情况，用下列方法试一下：http://www.kancloud.cn/wangfupeng/wangeditor2/131049

**Comment by liuxx001** [comment]
我也遇到这个问题了，经排查是ajax接收返回的字符串时带有引号，于是`var html = '<img src="' + resultText + '" alt="' + originalName + '" style="max-width:100%;"/>';`中src属性有两个引号，不能识别。
我的解决方式是：将服务端返回的字符串用eval()执行一次，就没问题了。
