### ISSUE TITLE
editor.config.withCredentials = false;设置无效

### ISSUE THREAD

**Issue by liuxx001** [wangfupeng1988/wangEditor#626]
设置了editor.config.withCredentials = false;后，在图片上传ajax请求时还是带上了cookie。跟源码发现：`//  xhr.withCredentials = editor.config.withCredentials || true;`这个一直是true吧？

**Comment by wangfupeng1988** [comment]
先自己把源码改一下，后面会统一改了这一个地方

**Comment by wangfupeng1988** [comment]
建议升级 v3 版本，v3 解决了这一问题
