### ISSUE TITLE
表情包跨域问题

### ISSUE THREAD

**Issue by aofong** [wangfupeng1988/wangEditor#627]
把js文件部署到cdn上面会出现跨域现象

**Comment by wangfupeng1988** [comment]
如果表情包是图片形式的，应该不会有跨域问题吧。
你说的是不是用 ajax 去加载表情包？那样的话，你只能暂时放弃 cdn 了

**Comment by wangfupeng1988** [comment]
建议升级 v3 版本，v3 解决了这一问题
