### ISSUE TITLE
支持响应式吗？

### ISSUE THREAD

**Issue by longxianlin** [wangfupeng1988/wangEditor#63]
需要编辑后发布到手机上。

**Comment by wangfupeng1988** [comment]
编辑后你得到的只是一段html代码段而已（注意是代码段，不是html页面完整代码）
之后之后发布在什么地方，都可以呀。

---------

不过，有一点你需要注意。就是如果编辑的内容过于复杂，例如上传了尺寸很大的图片或者很复杂的表格，你需要在你的显示页面做一些处理。例如图片最大宽度不得超过尺寸宽度、表格做成类似于百度百科那样的左右滚动等等。

看你自己需求，以上只是提醒一下。

**Comment by wangfupeng1988** [comment]
提问者长时间不回复问题，暂时关闭，再有问题再重新提交

**Comment by yuhaocan** [comment]
请问目前版本支持响应式吗？缩小页面工具类并没有换行 希望得到解决办法谢谢

**Comment by wangfupeng1988** [comment]
> 缩小页面工具类并没有换行

不支持换行了，建议在宽度不够时，隐藏掉某些菜单
