### ISSUE TITLE
editor.config.withCredentials = false 设置时没有用

### ISSUE THREAD

**Issue by 1012620005** [wangfupeng1988/wangEditor#630]
检查代码时发现 是 在源码中的   xhr.withCredentials = editor.config.withCredentials || true 不管我定义是的true还是false 这个永远是true  这个怎么解决

**Comment by wangfupeng1988** [comment]
这个先自己来手动处理一下，其实我再 V2 中已经修改过这个 bug了，只是没来得及发布，现在我正在全力升级 V3 ，V3中会有不一样的上传图片体验，望关注。

**Comment by brosegu** [comment]
我当时也是遇到这个问题，我直接在源码中注释掉了xhr.withCredentials =true;就好了

**Comment by webjyh** [comment]
`xhr.withCredentials = editor.config.withCredentials === false ? false : true;`

[我也遇到此问题了](https://github.com/wangfupeng1988/wangEditor/issues/656)

**Comment by wangfupeng1988** [comment]
建议升级 v3 版本，v3 解决了这一问题
