### ISSUE TITLE
编辑器与jquery.easydropdown下拉插件冲突，这个怎么解决

### ISSUE THREAD

**Issue by pshaoyi** [wangfupeng1988/wangEditor#633]
jquery.easydropdown与编辑器同时引入时下拉框无法使用

**Comment by wangfupeng1988** [comment]
我正在努力升级 V3 版本中，目前还没有精力来追踪 V2 反馈的问题，我会记录下，至少保证在 V3 中不会有这个的问题。感谢反馈！

**Comment by wangfupeng1988** [comment]
建议升级 v3 版本
