### ISSUE TITLE
如何实现文字环绕图片

### ISSUE THREAD

**Issue by daiyifei** [wangfupeng1988/wangEditor#634]
其它编辑器在设置居左居右时候是用的float:left/right，而wangeditor是text-align:left/right，无法实现多行文字环绕图片的布局，请问如何解决

**Comment by wangfupeng1988** [comment]
wangEditor 不支持文字环绕图片，需要如此复杂的编辑，还是建议选择其他更加大型的编辑器，例如 ueditor，或者直接上 office web application
