### ISSUE TITLE
插入优酷视频时报错了

### ISSUE THREAD

**Issue by miniMofish** [wangfupeng1988/wangEditor#635]
插入youku视频时提示：Uncaught ReferenceError: QS is not defined  at HTMLScriptElement.script.onload.script.onreadystatechange (XMTg3MzcyNjM0OA==:33)

这个QS是什么东西呢

**Comment by wangfupeng1988** [comment]
是按照这个方式插入的？

**Comment by miniMofish** [comment]
是的。我今天再试了一下，没有报错了，重现不了那个错误，不知道当时为什么报错。。后面有发现再告诉你，先关闭吧
