### ISSUE TITLE
添加文字和图片链接问题

### ISSUE THREAD

**Issue by miniMofish** [wangfupeng1988/wangEditor#636]
从用户操作角度来看，大部分设置链接的时候，链接都是直接从浏览器地址栏copy而来，windows下copy时不会自动带上http://，而mac下copy会自动带上http://，这里请问能否在添加链接时加个功能，链接input默认不要加http://，在添加的时候判断用户输入的url有没有带http://，如果没有的话自动加上，可以吗

**Comment by wangfupeng1988** [comment]
完全可以加，感谢反馈哈。不过我目前正在努力升级V3版本中，这个 bug 优先放在 V3 中保证修复没问题，到时候直接升级就好了。请关注qq群的升级动态。

**Comment by wangfupeng1988** [comment]
建议升级 v3 版本
