### ISSUE TITLE
求问，怎么在上传图片完成后读取对应的后台接口字段

### ISSUE THREAD

**Issue by ChanSun** [wangfupeng1988/wangEditor#637]
怎么在上传图片完成后，图片src获取接口返回的对象中的字段。而不是后台直接返回**纯字符串**

**Comment by wangfupeng1988** [comment]
这个问题 V2 中一直存在，确实是我考虑不周。目前我正在努力升级 V3 版本中，这个问题一定会再 V3 中修复，到时候可直接升级。请关注qq群邮件中V3的升级动态，感谢反馈！

**Comment by wangfupeng1988** [comment]
建议升级 v3 版本，v3 解决了这一问题
