### ISSUE TITLE
图片拖拽超出最小尺寸

### ISSUE THREAD

**Issue by 516018579** [wangfupeng1988/wangEditor#638]
当圆点拖到图片左边或上边时
图片的宽度和高度就变成0了 
然后图片就找不到了

**Comment by 516018579** [comment]
当出现滚动条时,先滚动到最底部时再向上拖到的话圆点会错位

**Comment by wangfupeng1988** [comment]
V2 中确实存在这个问题，作者正在努力升级 V3 中，在V3中会对图片的大小控制做一些调整，不会再出现这个问题，到时候直接升级即可。关注qq群邮件中V3 的升级动态，感谢反馈！

**Comment by wangfupeng1988** [comment]
建议升级 v3 版本，v3 将拖拽改成了更加简洁的设置`max-width`的方式
