### ISSUE TITLE
图片上传的顺序问题

### ISSUE THREAD

**Issue by joneqian** [wangfupeng1988/wangEditor#639]
我在上传图片的时候选择多张图片，发现图片在编辑器中展示的时候，既不是按照选择顺序，也不是按照文件名顺序，请问具体是按照什么顺序上传的，能对其进行控制吗？比如按选择顺序

**Comment by huanggm** [comment]
目前不支持的，需要自己hack。
因为他是对每一张选中的图片发出一个请求。每个请求返回的时间不一定。导致顺序不是固定的。

**Comment by joneqian** [comment]
请问该怎么hack？？

**Comment by wangfupeng1988** [comment]
作者正在奋斗在升级v3新版本功能上，这个问题会再新版本中解决，我记下，目前v2版本暂时不做改动。请关注新版本动态。

**Comment by joneqian** [comment]
@wangfupeng1988 有没有什么临时解决方案，目前在生产线上有这个问题，谢谢

**Comment by joneqian** [comment]
@huanggm 请问应该怎么hack？

**Comment by huanggm** [comment]
我创建了一个gist，可以参考一下：
https://gist.github.com/huanggm/79c48ea60e74c836aae4fc1c4924a0f4

主要是这两个方法：
changeGlobalUploadFilePrototype
sequenceUploadImage

changeGlobalUploadFilePrototype这个方法是改变wangEditor.UploadFile的prototype，所以只需要调用一次。
sequenceUploadImage这个方法需要传入一个editor实例对象。

缺点是：目前只支持了，点击按钮选中图片，对于拖拽上传和粘贴复制上传没有支持

**Comment by huanggm** [comment]
@wangfupeng1988 
hello，有个小小的建议：我觉得通过editor对象上增加original_name，然后在onload回调里面获取这个属性，还是存在问题的。最好是给回调函数在增加一个optiosn参数。可以任意参数了。

**Comment by shengalways** [comment]
@huanggm 你写的这两个方法直接放到源码里面么？

**Comment by shengalways** [comment]
@joneqian 请问你现在解决这个问题了么

**Comment by wangfupeng1988** [comment]
作者已经更新V3版本，上传图片有一些改进，欢迎关注  http://www.kancloud.cn/wangfupeng/wangeditor3/335779

**Comment by huanggm** [comment]
V3版本的插入图片默认实现有点问题，真正插入图片是在img.onload的回调函数中操作的，所以是异步的，导致多图上传的顺序仍然是不确定的。

小小的建议：服务器端返回的数据格式支持用户自定义，现在只能按照你设定的方式来返回

**Comment by wangfupeng1988** [comment]
OK 接受你的建议，后面增加一个自定义的上传回调操作
