### ISSUE TITLE
如何用seajs来加载

### ISSUE THREAD

**Issue by ikarosu** [wangfupeng1988/wangEditor#64]
提示jq修改过，不能使用。

**Comment by wangfupeng1988** [comment]
目前尚不支持cmd加载，因此会又这个错误。
不过很早就支持amd、requirejs了。

我还是在这两天加上CMD的支持吧，毕竟seajs也是国产神器，应该支持一下。

加上了之后，我会在这里回复。

**Comment by wangfupeng1988** [comment]
对于seajs的支持今晚已经更新并发布，可去官网下载最新代码。文档地址：http://www.kancloud.cn/wangfupeng/wangeditor/75850

**切记，一定要好好看看文档再使用！**

**Comment by daysgogogo** [comment]
我把编辑器的js和css放在 s.test.com 下，调用编辑器的页面URL是 http://www.test.com/a.php，
报这个错误：
Font from origin 'http://s.test.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.test.com' is therefore not allowed access.

请问，跨域的问题如何解决比较好？

**Comment by ikarosu** [comment]
实际上我找到方法加载了。seajs的define还支持一个参数，一个依赖项的数组，把没改过的JQ和js文件放在数组里，这个define下只写这个方法。另外，use是支持多个入口的，在use同时加载这个模块就好了

**Comment by wangfupeng1988** [comment]
OK seajs我没怎么用过，不过解决问题是关键。
