### ISSUE TITLE
能用在angular2中吗？

### ISSUE THREAD

**Issue by 760157714** [wangfupeng1988/wangEditor#640]

**Comment by wangfupeng1988** [comment]
目前尚无ng2的demo。

V3 版本正在升级中，发布时文档中会加入 ng2 的支持。V2版本实在没精力加了，抱歉。

**Comment by wangfupeng1988** [comment]
v3 版本已经发布，建议升级。v3 目前还没有支持 ng 的demo，已有支持 react 和 vue 的 demo了，后面有精力了会更新上，请关注升级动态。
