### ISSUE TITLE
CSS样式覆盖

### ISSUE THREAD

**Issue by qqabcv520** [wangfupeng1988/wangEditor#643]
bootstrap的选择器
`a:hover`
和
`.wangEditor-drop-list a`  
`.wangEditor-container a`
这些选择器的样式优先级相同，完全靠css引入顺序决定谁覆盖谁，打包的时候有点坑爹。
先引入wangEditor的css就会被bootstrap的css覆盖。

**Comment by wangfupeng1988** [comment]
v2 是一直有这个问题，作者正在全力升级 v3 ，v3中一定会解决这个问题，请关注 QQ群邮件中 v3 的升级动态。

**Comment by wangfupeng1988** [comment]
建议升级 v3 版本
