### ISSUE TITLE
图片上传csrf失效

### ISSUE THREAD

**Issue by Shurlormes** [wangfupeng1988/wangEditor#646]
项目用的是spring security做的安全认证，使用编辑器上传涂片是会出现403，csrf失效，请问该如何处理？

**Comment by YanfeiC** [comment]
你需要在页面添加一个meta标签,如果你是用的Thymeleaf模板,添加
` <meta th:name="_csrf" th:content="${_csrf.token}"/>`,
然后在js代码里加入如下代码
` var csrfToken = $("meta[name='_csrf'").attr("content");`
`editor.config.uploadHeaders = {'X-CSRF-TOKEN':csrfToken
    };`
