### ISSUE TITLE
插入超链接有XSS风险

### ISSUE THREAD

**Issue by jinkin1995** [wangfupeng1988/wangEditor#648]
![hj3yjta51](https://cloud.githubusercontent.com/assets/7165022/24944336/497c4a00-1f8d-11e7-96d3-07f6c7b60b17.PNG)
![c8k0gjta51](https://cloud.githubusercontent.com/assets/7165022/24944342/4d14aa9a-1f8d-11e7-9c2a-d2ef3e3cf3d6.PNG)

**Comment by wangfupeng1988** [comment]
参见这里  http://www.kancloud.cn/wangfupeng/wangeditor2/131436 过滤一下
