### ISSUE TITLE
在vue中，一个页面使用多个编辑器，导致上传冲突

### ISSUE THREAD

**Issue by hisan-web** [wangfupeng1988/wangEditor#649]
在vue中，一个页面使用多个编辑器，导致上传冲突，比如一个页面中使用两个编辑器，使用了自定义上传，结果执行的upload永远是第二个的事件，经多次测试都这样。。

**Comment by wangfupeng1988** [comment]
这是一个已知的问题，也有一些使用者之前反馈过。但是我正在全力升级 V3 版本中，当前没有精力跟踪这些问题，毕竟个人业余精力有限。

不过我肯定会再升级 V3 版本过程中一定注意这个问题，不会让它再发生。感谢反馈！

**Comment by hasbug** [comment]
@hisan-web  哥们  能提供下你的vue文件看看吗？ 我用了官方的集成vue+自定义上传配合一起，但没有生成隐藏的input控件，导致点击上传处后，没有打开本地文件选择框。求助：@wangfupeng1988

**Comment by wangfupeng1988** [comment]
建议升级 v3 版本，v3 解决了这一问题
