### ISSUE TITLE
关于字体跨域的问题

### ISSUE THREAD

**Issue by daysgogogo** [wangfupeng1988/wangEditor#65]
我把编辑器的js和css放在 s.test.com 下，调用编辑器的页面URL是 http://www.test.com/a.php，
报这个错误：
Font from origin 'http://s.test.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.test.com' is therefore not allowed access.

请问，跨域的问题如何解决比较好？

**Comment by wangfupeng1988** [comment]
首先，这是一个很典型的跨域访问的错误提示。但是你要确认是哪一条http请求触发的。

网页通过<script>和<link>来加载javascript和css文件，是没有跨域限制的。

**Comment by wangfupeng1988** [comment]
提问者长时间不回复，暂时关闭，再有问题再提问
