### ISSUE TITLE
粘贴带格式的html后，获取text内容，空格字符变成ascii字符0xa0

### ISSUE THREAD

**Issue by yuanjianpeng** [wangfupeng1988/wangEditor#651]
请一定要看一下这个问题，应该是粘贴过滤算法有问题。

比如粘贴（不是粘贴下述纯文本，而是带格式的，在页面上随便复制一段带空格的即可）：
html - PHP

打印出editor.$txt.text()的ascii码如下：
h[68] t[74] m[6d] l[6c]  [a0] -[2d]  [a0] P[50] H[48] P[50]

可见空格变成 0xa0编码的ascii字符。这影响页面显示，因为是非法字符，所以所有字符被认为是一个单词，超长后不会自动换行。

如果不能复现请，联系qq 785147217。

BR

**Comment by wangfupeng1988** [comment]
带格式的html粘贴本身是没有过滤算法的，完全是浏览器自己的行为，因此带格式的粘贴会有各种风险，建议使用过滤样式的粘贴方式。

我正在全力升级 V3 版本中，V3 版本将会强制使用过滤样式的粘贴。

**Comment by yuanjianpeng** [comment]
You are right. 粘贴时&nbsp;被浏览器处理为No Break Space Char (0xa0)，在编辑器中能正常显示，但是最终提交到页面时，显示会出大问题。不可换行，全部溢出了，所以应该期望替换成正常的space (0x20)

**Comment by wangfupeng1988** [comment]
建议升级 v3 版本
