### ISSUE TITLE
移动端，结合angularJS使用的时候报Cannot read property 'trim' of undefined(…)

### ISSUE THREAD

**Issue by pageZero** [wangfupeng1988/wangEditor#653]
完全按照wangEditor-mobile的基本配置写的，移动端使用了angularJS，在`var editor = new ___E("textarea1");`的时候出错，此处调用了`self.addTxt();`，最后定位到zepto.js的$trim方法，不知道是不是因为用了angularJS的缘故，还请作者解答。

**Comment by wangfupeng1988** [comment]
wangEditor-mobile 早就不维护了，官网和github都有说明。
