### ISSUE TITLE
wangEditor重复绑定了多个scroll和resize事件

### ISSUE THREAD

**Issue by xjArea** [wangfupeng1988/wangEditor#654]
使用火狐的控制台可以发现window上被重复绑定了多个resize事件和scroll事件。

**Comment by wangfupeng1988** [comment]
我正在全力升级 V3 中，这个问题我记录下来，会关注，在 V3 规避这个问题。尽快发布V3,用户尽快升级。

感谢反馈！

**Comment by wangfupeng1988** [comment]
建议升级 v3 版本，v3 解决了这一问题
