### ISSUE TITLE
把编辑器的DOM移除并且实例=null后，body依然会在滚动的时候被加上margin-top:32px

### ISSUE THREAD

**Issue by xjArea** [wangfupeng1988/wangEditor#655]
做单页面引用，编辑器的DOM已经被我remove了，并且实例也null了，numberOfLocation也-1变成0了，但是在滚动的时候，body依然会被加上margin-top:32px的值。

**Comment by wangfupeng1988** [comment]
> body依然会被加上margin-top:32px的值

看能自己手动兼容一下吗？我正在全力升级 V3 版本中，现在没有时间看这些问题。尽快发布V3，用户尽快升级。

**Comment by JYJQQ** [comment]
其实这问题不是很致命，我也不着急，如果V3能解决的，那我就坐等V3吧。

**Comment by wangfupeng1988** [comment]
建议升级 v3 版本
