### ISSUE TITLE
跨域图片上传时 xhr.withCredentials 设置问题 

### ISSUE THREAD

**Issue by webjyh** [wangfupeng1988/wangEditor#656]
因跨域图片上传时，可以配置 `xhr.withCredentials `，但因服务器那边设置发现不需要发送 Cookie 信息，将`xhr.withCredentials ` 设置为` false `时，上传时却发现  `xhr.withCredentials ` 的值一直为 `true`，查了下源码发现

```javascript
xhr.withCredentials = editor.config.withCredentials || true;
```
此语句有些问题，因为一但设置为 `editor.config.withCredentials = false` 时，只会执行后半句，导致 `xhr.withCredentials ` 一直为 ` ture` 所以本人稍微改了下，希望楼主更新下源码。

```javascript
xhr.withCredentials = editor.config.withCredentials === false ? false : true;
```

**Comment by wangfupeng1988** [comment]
先自己改一下源码吧，就这一句话的问题。我正在努力升级 v3 版本中……

**Comment by wangfupeng1988** [comment]
建议升级 v3 版本，v3 解决了这一问题
