### ISSUE TITLE
希望支持onPaste、ctrl+v 复制过滤掉html标签

### ISSUE THREAD

**Issue by easyku** [wangfupeng1988/wangEditor#66]
希望支持onPaste、ctrl+v 复制过滤掉html标签，word格式。

**Comment by wangfupeng1988** [comment]
**啊，干脆就过滤了？**
之前有人提过，说word粘贴过来格式不正确之类的，想让我支持word粘贴，我拒绝了。

直接过滤了，这样是不是太绝对，有时候粘贴过来也是需要有一些样式的。例如我在博客园写博客，一般都是从word写完了，然后粘贴到博客园编辑器里面。

**Comment by easyku** [comment]
有些使用场景，发布内容比较简单，只需要颜色，字体的改变，表情，以及图片上传，粘贴带有格式的内容会破坏网页布局。

**Comment by wangfupeng1988** [comment]
那只是『有些场景』，不能因为部分场景就全部过滤粘贴过来的样式。
不过，你可以自己为为`editor.$txt`增加一个粘贴事件，自己来处理这件事儿。
