### ISSUE TITLE
Uncaught SyntaxError: Unexpected token .

### ISSUE THREAD

**Issue by xifengxx** [wangfupeng1988/wangEditor#663]
按照文档引用js/css文件后，css文件报错
`
wangEditor.min.js:2 wangEditor提示: 本页面富文本编辑器由 wangEditor 提供 http://wangeditor.github.io/ 
webim.js?a425:1332 navigator.userAgent=mozilla/5.0 (macintosh; intel mac os x 10_11_6) applewebkit/537.36 (khtml, like gecko) chrome/57.0.2987.133 safari/537.36
webim.js?a425:1332 BROWSER_INFO: type=chrome, ver=57.0.2987.133
toast.js:187 DOMContentLoaded -> isToastRequested:false
core.es5.js?2754:3025 Angular is running in the development mode. Call enableProdMode() to enable the production mode.
wangEditor.min.js:2 wangEditor提示: 正在处理 微博表情 表情的数据...
wangEditor.min.js:2 wangEditor提示: 建议在配置中自定义百度地图的mapAk，否则可能影响地图功能，文档：http://www.kancloud.cn/wangfupeng/wangeditor2/113961`
![2017-04-21 17 41 21](https://cloud.githubusercontent.com/assets/15701172/25272278/d3de544e-26b9-11e7-842e-aff0a1a74832.png)
![2017-04-21 17 41 35](https://cloud.githubusercontent.com/assets/15701172/25272279/d3e390a8-26b9-11e7-8fb3-887e42da6d39.png)

**Comment by xifengxx** [comment]
通过npm安装wangEditor后引用里面的css/js文件，会出现上面的问题，但通过cdn引入wangEditor的css/js文件，则正常。

**Comment by DukeAnn** [comment]
同问

**Comment by DukeAnn** [comment]
你是不是把CSS引入写成了 <script src="/wangEditor/dist/js/wangEditor.js"></script>
应该是 <link href="https://cdn.bootcss.com/wangeditor/2.1.20/css/wangEditor.css" rel="stylesheet">

**Comment by DukeAnn** [comment]
<link href="https://cdn.bootcss.com/wangeditor/2.1.20/css/wangEditor.css" rel="stylesheet">

**Comment by wangfupeng1988** [comment]
建议升级 v3 版本，v3 解决了这一问题
