### ISSUE TITLE
希望增加附件上传功能

### ISSUE THREAD

**Issue by jixzfw** [wangfupeng1988/wangEditor#664]
上传一个文件后，在光标处添加一个超链接

**Comment by wangfupeng1988** [comment]
http://www.kancloud.cn/wangfupeng/wangeditor2/119079

看看这里

**Comment by wangfupeng1988** [comment]
v5 已经支持上传附件 https://github.com/wangeditor-team/wangEditor-plugin-upload-attachment

v4 不再升级新功能了
