### ISSUE TITLE
希望图片对话框增加在线图片选项卡

### ISSUE THREAD

**Issue by jixzfw** [wangfupeng1988/wangEditor#665]
增加一项在线图片读取url配置
单击插入图片

**Comment by wangfupeng1988** [comment]
这个功能自己去做吧，编辑器不会实现这个，用的人不是很多，用到的 API看这里 http://www.kancloud.cn/wangfupeng/wangeditor2/115832

**Comment by wangfupeng1988** [comment]
我正在全力升级 V3 版本，到时候会有更加丰富的 API 可用

**Comment by wangfupeng1988** [comment]
建议升级 v3 版本.

> 希望图片对话框增加在线图片选项卡

这个可以自己去实现，没不要在编辑器中统一支持
