### ISSUE TITLE
批量上传大图的时候，xhr是同时并发的，这样超时时间设的很长也没用

### ISSUE THREAD

**Issue by 740521985** [wangfupeng1988/wangEditor#671]
建议有个参数来控制上传队列的数量

**Comment by 740521985** [comment]
我改了下源码，现在可以串行，控制队列长度的功能还没加

**Comment by answer33** [comment]
请问 怎么设置超时时间

**Comment by wangfupeng1988** [comment]
> 我改了下源码，现在可以串行，控制队列长度的功能还没加
👍  V3已经更新了，我会加上你说的建议。

**Comment by 740521985** [comment]
您好，谢谢您的wangEditor对开源的贡献，不知道是否有兴趣来阿里钉钉事业部，最近急招前端~有兴趣可以邮件到：zongyuan.zy@alibaba-inc.com ，打扰

**Comment by wangfupeng1988** [comment]
@740521985 不去杭州，家人都在北京 🙃
