### ISSUE TITLE
react 引用失败  

### ISSUE THREAD

**Issue by yuxuan1125** [wangfupeng1988/wangEditor#673]
import React from 'react';
import WangEditor from 'wangeditor';

export default class TestPage extends React.Component {
 constructor(props) {
  super(props);
 }
 componentDidMount(){
  this.editor = new window.wangEditor('div1');
  this.editor.create();
 }
 render(){
  return (
    <div id="div1" style={{width:500,height:300}} contentEditable={true}></div>
  )
 }
};

**Comment by 740521985** [comment]
npm的方式么？那你为啥还从window取

**Comment by yuxuan1125** [comment]
那个我不用window的也不行啊  求支招啊
