### ISSUE TITLE
markdown兼容性，建议作者参考一下这个。

### ISSUE THREAD

**Issue by cmideal** [wangfupeng1988/wangEditor#674]
https://github.com/sofish/pen

penjs,实现了相对还算可以的效果

markdown,追求的是格式可控，简单，清晰，可以出一个格式化版的Markdown

**Comment by wangfupeng1988** [comment]
文档中说的很明白，markdown和富文本不可能在一起，各用各的

**Comment by wangfupeng1988** [comment]
markdown 插件已经开发完了 https://github.com/wangeditor-team/wangEditor-plugin-md

不过只能用于 [v5](https://www.wangeditor.com/v5/) 。v5 近期会正式发布，v4 不再做功能升级了。
