### ISSUE TITLE
内容超出编辑器的边界不能换行

### ISSUE THREAD

**Issue by adoubee** [wangfupeng1988/wangEditor#677]
在编辑区的内容超出了编辑器的边界后是光标会自动移到下一行 
但实际的html代码里并没有加换行 
也就是没有<p></p> 
如果没有手动按回车换行html代码里是不会换行的
所以有时候内容太多没换行显示出来的效果是一行很长的内容...
这个可以修复吗?
还是说我配置有问题?

**Comment by lifei6671** [comment]
我理解你的意思是说，在编辑器中编辑的时候超长文字会自动环境，然后你在页面显示的时候不会换行是吗？
如果是的话，你需要给你显示html的容器设置一个宽度。
