### ISSUE TITLE
添加链接能否显示标题，而非显示链接？

### ISSUE THREAD

**Issue by dongfenglong** [wangfupeng1988/wangEditor#68]
目前编辑器添加链接后显示的仍然是链接，只有鼠标移动到链接上才会显示标题，这样的样式并不美观和人性化。建议添加的链接直接显示标题，这样会更美观。

**Comment by wangfupeng1988** [comment]
没明白什么意思，能否提供一个具体的场景描述一下？

**Comment by wangfupeng1988** [comment]
刚才做了一个实验，知道了你说的意思，已经优化了，可以去github下载最新源码
