### ISSUE TITLE
页面多个编辑器，文本对比

### ISSUE THREAD

**Issue by airzhanglin** [wangfupeng1988/wangEditor#680]
您好，第一次使用你的写的编辑器，这是一个非常轻量且功能较为齐全的编辑器，我非常喜欢。现在我们产品有这么一个需求，刚刚适合您的这个编辑器。痕迹保留功能。比如我在第一个编辑器里面编写了东西--初稿、然后我在第二个编辑器里面进行编辑的时候是对初稿的修改，所以每当修改的时候都会标注不同的地方来让用户更好的显示用户修改过的地方。现在我能在textarea文本框总实现我这一个功能。我也尝试了在您的这个编辑器下面进行开发。在输入执行我的对比文本事件并复制到内容盒子上的时候出现很多空格，而且光标也一直往前面走。所以请问一下作者我该如何做

**Comment by wangfupeng1988** [comment]
没看明白你的场景是什么。。。
