### ISSUE TITLE
引用该编辑器，上传图片的方式只有一种了，本地上传不见了是怎么回事

### ISSUE THREAD

**Issue by py123456** [wangfupeng1988/wangEditor#681]

**Comment by lifei6671** [comment]
[http://www.kancloud.cn/wangfupeng/wangeditor2/113992](http://www.kancloud.cn/wangfupeng/wangeditor2/113992) 建议还是多看看文档。

**Comment by py123456** [comment]
大神，可以问下本地上传文件的参数怎么配置么

**Comment by lifei6671** [comment]
没看文档吗？ 配置了 editor.config.uploadImgUrl 会自动显示本地文件上传。

**Comment by py123456** [comment]
看了，就是那个本地上传图片时，参数没看懂

**Comment by py123456** [comment]
不晓得如何去配置

**Comment by wangfupeng1988** [comment]
这个文档中写的很明白了
