### ISSUE TITLE
一个页面内2个编辑器，图片上传其中一个生效，另一个为什么不生效?

### ISSUE THREAD

**Issue by allan2coder** [wangfupeng1988/wangEditor#682]
请问一个页面内多个编辑器，图片上传其中一个成功，另一个为什么不成功?
并且没有报错。

**Comment by rexsunces** [comment]
遇到同样的问题，大概知道哪里出了问题，已经初步解决。
应该是多个编辑器共享了config中的对象参数，即需要深拷贝参数。经过调试你可以发现，是最后定义的编辑器的uploadImgFns覆盖了前一个。
你可以 在初始化的时候，
editor1= new wangEditor('wangediotr-outer');
**editor1.config=deepClone(wangEditor.config);**
此处deepClone需要你自己实现一下深拷贝。示例如下：
function deepClone(obj) {
    var result, oClass = isClass(obj);
    //确定result的类型
    if (oClass === "Object") {
        result = {};
    } else if (oClass === "Array") {
        result = [];
    } else {
        return obj;
    }
    for (key in obj) {
        var copy = obj[key];
        if (isClass(copy) == "Object") {
            result[key] = arguments.callee(copy);//递归调用
        } else if (isClass(copy) == "Array") {
            result[key] = arguments.callee(copy);
        } else {
            result[key] = obj[key];
        }
    }
    return result;
}
//返回传递给他的任意对象的类
function isClass(o) {
    if (o === null)
        return "Null";
    if (o === undefined)
        return "Undefined";
    return Object.prototype.toString.call(o).slice(8, -1);
}

顺便@下作者，看看能不能优化一下。

**Comment by allan2coder** [comment]
@rexsunces 谢谢。

@wangfupeng1988 请问作者，这个问题该如何合理解决？

**Comment by wangfupeng1988** [comment]
建议接下来升级V3版本，正在发布中，官网和github已经更新了
