### ISSUE TITLE
图片可以上传，显示不了。

### ISSUE THREAD

**Issue by HeRui2812** [wangfupeng1988/wangEditor#683]
![image](https://cloud.githubusercontent.com/assets/28434965/25740364/c87179a6-31b8-11e7-9459-f445a5cf6b2a.png)
在浏览器里也打不开

**Comment by lifei6671** [comment]
返回的图片路径需要你自己去处理。

**Comment by HeRui2812** [comment]
@lifei6671 
![image](https://cloud.githubusercontent.com/assets/28434965/25744196/1edf699e-31cb-11e7-9553-537302eca3b4.png)
我再去看看视频吧

**Comment by HeRui2812** [comment]
可以了，哈哈哈，菜鸟搞了一下午...
