### ISSUE TITLE
火狐浏览器下，创建表格，编辑表格内容时，会出现两个控制点。

### ISSUE THREAD

**Issue by KDODIUNCNWERU** [wangfupeng1988/wangEditor#686]
[图片详情](https://cloud.githubusercontent.com/assets/23158772/25782187/1996c758-3378-11e7-8266-40d76e142c54.jpg)

**Comment by wangfupeng1988** [comment]
火狐确实会有许多兼容性问题。V3版本正在发布中，官网已经更新，可以去官网试一下，看看有没有这个问题

**Comment by KDODIUNCNWERU** [comment]
@wangfupeng1988 我刚刚在官网试过了，也会有这两个点
![5866995fce50a34988281b1551edf741](https://user-images.githubusercontent.com/23158772/26914701-5946d726-4c55-11e7-80de-df0f5c0046ea.png)

**Comment by KDODIUNCNWERU** [comment]
document.execCommand('enableObjectResizing', false, 'false');  
        document.execCommand("enableInlineTableEditing", false, 'false');
加这两个好像可以解决

**Comment by wangfupeng1988** [comment]
@KDODIUNCNWERU 感谢。

我试一下，如果可以搞定，下次发版加上，关注发版内容

**Comment by wangfupeng1988** [comment]
已解决
