### ISSUE TITLE
换行相关的样式问题

### ISSUE THREAD

**Issue by xixueru** [wangfupeng1988/wangEditor#687]
hi,你好，在使用editor开发中遇到如下问题，我一行一行的复制是没有问题的，但是，我在最后一行，摁enter换行就会出现第二幅图的现象，菜单栏不见了，然后内容超出。
![image](https://cloud.githubusercontent.com/assets/9957175/25789129/c5170f6c-33e0-11e7-9c51-56cd0007ff2f.png)
![image](https://cloud.githubusercontent.com/assets/9957175/25789137/d4ae5ef8-33e0-11e7-9abc-0d8003134ef4.png)

**Comment by wangfupeng1988** [comment]
官网可以复现复现这个问题吗？
