### ISSUE TITLE
编辑器内容过多时，添加链接、图片的弹窗存在的问题

### ISSUE THREAD

**Issue by dongfenglong** [wangfupeng1988/wangEditor#69]
如果编辑器内容过多，在内容底部添加链接或者图片时，必须把编辑器的下拉按钮拉到顶部，然后再添加链接或图片。否则弹窗不能显示出来，实际上是弹窗跟随编辑器顶部导致的该问题。

**Comment by wangfupeng1988** [comment]
我看到这个问题了，内容过多时，内容过多时，所有的modal类型的按钮都会有问题。
这是一个严重bug，感谢你提出来，我会尽快解决！

**Comment by wangfupeng1988** [comment]
该问题已经解决。

原因在于我当时考虑不周全，不过谢谢你的提醒！
