### ISSUE TITLE
编辑器动态改变高度时，菜单吸顶显示错误

### ISSUE THREAD

**Issue by istobran** [wangfupeng1988/wangEditor#691]
![image](https://cloud.githubusercontent.com/assets/7479006/25833113/87bc11a0-34a1-11e7-8360-b29ec591a3e3.png)
如图，我自己实现了一个展开正文和收缩正文的按钮，当用户点击展开正文时，编辑器高度会自动改为内容高度，即：
```javascript
const dom = document.getElementsByClassName("wangEditor-txt")[0];
dom.style.height = dom.scrollHeight + "px";
```
编辑器展开后，滚动到下方，会发现menu吸顶插件的editorHeight未跟随编辑器的高度变化而变化
![image](https://cloud.githubusercontent.com/assets/7479006/25833320/f892a528-34a2-11e7-9d94-5af3a3279a44.png)

期望：
编辑器高度变化时应重新计算editorHeight，以解决菜单栏吸顶显示不正确的问题

wangEditor版本：
2.1.23

**Comment by allan2coder** [comment]
我也遇到了同样的问题，把编辑器的菜单的position改为inherit可以解决。

**Comment by wangfupeng1988** [comment]
尽量少将多种动态的东西结合起来用。V3版本正在发布中，已经去掉了这些花哨的功能，更加精简
