### ISSUE TITLE
在服务器运行页面时，如果页面上有滚动条，wangEditor点全屏后的滚动条使用不了

### ISSUE THREAD

**Issue by shuaiLMZ** [wangfupeng1988/wangEditor#694]
代码都是用原来代码来测试过，也是不行的。
![Uploading QQ截图20170511165606.png…]()

**Comment by shuaiLMZ** [comment]
@wangfupeng1988

**Comment by shuaiLMZ** [comment]
![qq 20170511165606](https://cloud.githubusercontent.com/assets/28621450/25941438/0df85f32-366c-11e7-8e78-9595a8521d1a.png)

**Comment by Shijf** [comment]
全屏怎样引入他

**Comment by wangfupeng1988** [comment]
v3 已经不默认支持全屏功能了，需要的话自己去开发，文档中有说明
