### ISSUE TITLE
插入代码，缺失</

### ISSUE THREAD

**Issue by xupp** [wangfupeng1988/wangEditor#695]
两段代码一样，直接放编辑器外面能正确显示
![default](https://cloud.githubusercontent.com/assets/13492008/25988678/7a0b72b2-372b-11e7-98d7-035f8340b40e.png)

**Comment by wangfupeng1988** [comment]
试一下V3版本会不会与这个问题，官网已经更新了。V2的问题不打算再继续修复了，毕竟个人精力有限，专心做好V3
