### ISSUE TITLE
插入video标签，光标无法正确定位

### ISSUE THREAD

**Issue by rexsunces** [wangfupeng1988/wangEditor#696]
我自己改了video菜单的方法，直接插入我选择的一个video标签。显示没问题。问题如下：
不像iframe或者图片，我们可以把光标移到图片之前或者图片之后（也就是光标位于图片的同一行），在P标签内插入了video后，光标无法定位到该P标签内。

**Comment by wangfupeng1988** [comment]
你当时是使用的 v2 还是 v3 ？v3 升级之后 v2 已经没有精力维护了
