### ISSUE TITLE
你好，关于获取编辑器对象的问题。

### ISSUE THREAD

**Issue by mx4g** [wangfupeng1988/wangEditor#698]
能不能提供一个获取编辑器对象的方法(getEditor()) ,
假如我单独封装一个获取内容的方法，每次都要传入之前创建的Editor对象传给它，有些不方便。
能不能 提供 WE.getEditor("Id") ,直接拿到编辑器对象 ，这样就灵活了。

**Comment by lifei6671** [comment]
你可以自定义一个全局变量储存编辑器信息啊。

**Comment by mx4g** [comment]
是的，我现在就是这样做！但我觉得你可以提供一个这样的全局变量，这不是更好吗？

**Comment by mx4g** [comment]
这只是我的建议啦！哈哈

**Comment by sky0614** [comment]
oooooooooooooo

**Comment by wangfupeng1988** [comment]
感谢楼主建议，作者会考虑这种简单有效的API
