### ISSUE TITLE
图片上传后回调（建议）

### ISSUE THREAD

**Issue by ChrisJoy** [wangfupeng1988/wangEditor#70]
现在上传后回调用用的的 iframe，个人一向不喜欢，也不好用。我现在的做法是引用jquery.form.js：
$form.ajaxSubmit(function (ret) {
  if (ret.Success) { editor.command(e, 'customeInsertImage', { 'url': ret.Message, 'title': title }, uploadImg_callback);
  } else alert(ret.Message);
});

建议：把jquery.form.js里的 ajaxSubmit 抠出，集成到你的编辑器中使用

**Comment by wangfupeng1988** [comment]
是啊，跨域上传一直是我觉得一个不好用的地方，好在跨域用的不是特别多。
我已经下载了jquery.form.js了，抽时间阅读一下ajaxSubmit的源码试着集成一下。
谢谢！

**Comment by PeakTai** [comment]
+1，这一点确实用着不爽。希望能够改进，支持返回jsonp也可以呀。

**Comment by wangfupeng1988** [comment]
试试2.0的上传，只需要配置一下服务器端的url，然后服务器端返回一个图片url即可了。
