### ISSUE TITLE
上传图片如何改变请求方式

### ISSUE THREAD

**Issue by liuly181** [wangfupeng1988/wangEditor#700]
上传图片后台要求是post提交，wangEditor 好像默认是get 提交

**Comment by codinglilong** [comment]
真没办法。我的方法是覆盖他的上传方法。把他的xhrUploadImg方法覆盖掉用自己的！

**Comment by lifei6671** [comment]
@liuly181 

**目前 wangEditor 支持：**

基本的选择图片上传（IE8、9使用form方式上传，其他浏览器使用html5方式上传）
chrome、firefox、opera、IE11的粘贴截图上传
拖拽图片上传，支持到IE10
上传进度条，支持到IE10
跨域上传，支持到IE10

html5和form不可能是get上传的。

**Comment by wangfupeng1988** [comment]
get 方式怎么可能上传图片?
