### ISSUE TITLE
把他放到项目里就一直报500的错误，怎么回事

### ISSUE THREAD

**Issue by zhulinlin12** [wangfupeng1988/wangEditor#704]
![image](https://cloud.githubusercontent.com/assets/24427812/26183801/b61e8546-3bb3-11e7-88c7-435ce797771f.png)
![image](https://cloud.githubusercontent.com/assets/24427812/26183805/c272c316-3bb3-11e7-948f-22f5d0ace63e.png)

**Comment by lifei6671** [comment]
500错误是你服务器端出错了。和编辑器无关。

**Comment by wangfupeng1988** [comment]
楼上正解
