### ISSUE TITLE
修改字体时使用的是<font>标签，该标签已经不推荐使用了

### ISSUE THREAD

**Issue by wu-peng** [wangfupeng1988/wangEditor#705]
![image](https://cloud.githubusercontent.com/assets/6448721/26184729/189578b0-3bb9-11e7-9a18-fa16b68f6673.png)

**Comment by wangfupeng1988** [comment]
但是浏览器的`document.execCommand`还在用，富文本编辑器依赖于这个API，但是它又好久没更新并且标准化，所以比较蛋疼，只能暂时先这样了。
