### ISSUE TITLE
是否有自定义上传图片方法？

### ISSUE THREAD

**Issue by codinglilong** [wangfupeng1988/wangEditor#707]
由于公司的上传接口比较特殊。使用wangEditor提供的上传方式无法达到效果。有没有自定义上传事件的方法？

**Comment by lifei6671** [comment]
手册上有说道自定义上传图片啊

**Comment by codinglilong** [comment]
@lifei6671 手册是自定义上传回调事件。是回调不是自定义上传事件看清楚！

**Comment by lifei6671** [comment]
@codinglilong [http://www.kancloud.cn/wangfupeng/wangeditor2/123690](http://www.kancloud.cn/wangfupeng/wangeditor2/123690) 如果看不懂的话，估计作者也没办法。

**Comment by codinglilong** [comment]
@lifei6671 这不是还要下载plupload这个插件嘛！不知道能不能集成到我们开发环境中去。我们的环境是react+typescript。集成到里面是有条件的

**Comment by lifei6671** [comment]
@codinglilong 作者给了两个例子，一个是集成plupload，一个是集成七牛。你完全可以集成自己的上传组件啊。

**Comment by zhougonglai** [comment]
我也觉得集成插件这事很玄...我用一个自定义的uploader,但是我的表单每次要从外部传入params参数!怎么都感觉很难办吖.

**Comment by KDODIUNCNWERU** [comment]
有自定义上传图片的方法啊，我是用在vue里面的，自定义服务器路径，自定义参数，返回图片路径然后自定义img标签

**Comment by zhougonglai** [comment]
@KDODIUNCNWERU 你项目的需求还算简单,但是我们现在的要求是一个上传图片一个上传视频,要在上传图片的时候用图片的params,video用video的params..现在menu也没有click事件!现在需要项目在上传前根据不同的menu去set这个editor的config.params..还要根据不同reponse.data 插入不同 标签! 
项目用的ng.但是createMenu是jqCode.Editor还没有ng-scope作用域!.
