### ISSUE TITLE
请问是否可提供在package.json中 description 的英文版 (There is no English description of this Library)

### ISSUE THREAD

**Issue by sufuf3** [wangfupeng1988/wangEditor#709]
@wangfupeng1988 您好！
我是[CDNJS](https://cdnjs.com/) [注1] 团队的成员之一。我们正准备拖管 贵 Library。
在此请问 贵 Library 是否可以提供在`package.json`中 Description的英文版，让全世界更多人能够了解贵 Library 并使用您的 Library。

若您有任何宝贵的建议，还请您指教。
谢谢您！

注1: ​​CDNJS 是一个免费的前端CDN资源库。我们拖管许多的 Library。

---

Hi @wangfupeng1988  ,
I am a member of [cdnjs](https://github.com/cdnjs/cdnjs), we are going to host this library.
Could you please translate `description` which in `package.json` Chinese into English?

If you have any suggestions, please let me know.
Thank you.

cdnjs/cdnjs#11286

**Comment by wangfupeng1988** [comment]
wangEditor, your simple open-source easy-use rich text editor!

感谢你们的支持。

**Comment by wangfupeng1988** [comment]
另外，你能留一个联系方式吗，我感觉自己往cdnjs中提交好复杂，光`clone`你们的库，就好慢！希望能联系到你来支持一下，QQ或者微信什么的。

**Comment by sufuf3** [comment]
谢谢您提供的资讯！
关于连系方式，我不太使用QQ或维信，不好意思！
不过我正在处理贵Library，拖管后会通知您！
或是随时欢迎您关注这 cdnjs/cdnjs#11286 PR，谢谢您！

**Comment by wangfupeng1988** [comment]
我现在都升级到v3.0.0了，那个PR还是v2.1.3，我如何再把v3.0.0的提交上去？

**Comment by sufuf3** [comment]
感谢您的告知。
让我协助您将v3.0.0中的`release`档案夹向下的档案，提交到这个PR (这两天更新)

另外，CDNJS有自动更新机制(git auto-update)，只要新版本与就版本的档案结构相同，即可自动更新，未来您就可以不用手动增加。
谢谢您！

**Comment by sufuf3** [comment]
@wangfupeng1988
Now CDNJS host this library :+1: :)
https://cdnjs.com/libraries/wangEditor
