### ISSUE TITLE
编辑器bug

### ISSUE THREAD

**Issue by stop2stare** [wangfupeng1988/wangEditor#71]
安装默认的方法去编辑框里填写内容，则wangEditor-textarea里面都是p，但是如果编辑框加载出来的时候里面没有字，这里是可以退格(back space)的，光标往上移动一行，这时候wangEditor-textarea里的就是div了。。没有p。这个是bug么。。。

**Comment by wangfupeng1988** [comment]
默认情况下，在空白什么都没有时候，换行就会出现div，所以wangEditor在初始化时候加一个`<p><br></p>`

**Comment by stop2stare** [comment]
这里是出于什么情况的考量？

**Comment by wangfupeng1988** [comment]
加上`<p><br></p>`之后，往后的换行就会以`<p>`换行，否则就会以浏览器默认的`<div>`换行。
一般浏览器用什么标签换行都行，但是IE低版本浏览器，用`<div>`换行时，会出现兼容性问题。

就是基于对IE浏览器的支持考虑的。

**Comment by stop2stare** [comment]
没看太明白，IE浏览器低版本使用div会出问题，高版本使用div会影响体验，then why use it still, doesn't really understand.

**Comment by wangfupeng1988** [comment]
1. 没说高版本用div会影响体验；
2. IE低版本用div换行会影响体验，但是用p换行没问题；

---------------

总之，通过编辑器默认配置的，用`<p>`换行，就都没有问题。
