### ISSUE TITLE
如何控制上传图片的大小？

### ISSUE THREAD

**Issue by codinglilong** [wangfupeng1988/wangEditor#710]
查看了文档没有控制上传图片大小的。

**Comment by JunedanVan** [comment]
@codinglilong 
![image](https://cloud.githubusercontent.com/assets/24771641/26296247/68395400-3f00-11e7-83cc-d2684c061e5d.png)

**Comment by wangfupeng1988** [comment]
升级V3版本，直接配置支持  http://www.kancloud.cn/wangfupeng/wangeditor3/335782
