### ISSUE TITLE
在IE8/9下，本地上传图片只能选一次

### ISSUE THREAD

**Issue by JunedanVan** [wangfupeng1988/wangEditor#712]
在官网的文档指引下，看到[集成七牛的demo](https://github.com/wangfupeng1988/js-sdk)链接，下载之后只改了token、domain、加了key函数，在IE9运行，点击上传图片弹出选择文件的框，选择之后正常显示图片
![image](https://cloud.githubusercontent.com/assets/24771641/26478661/491b591c-4200-11e7-98b4-60a4493484eb.png)
但是，第二次点击上传图片并没有弹出选择文件的窗口

@wangfupeng1988

**Comment by wangfupeng1988** [comment]
> 看到集成七牛的demo链接 
试一下我制作的demo，是不是也有你这样的问题？

**Comment by JunedanVan** [comment]
是的，我是下载官网说的  集成七牛的demo链接  里的demo，出现这问题

**Comment by wangfupeng1988** [comment]
非常抱歉，v2 此后不维护了，已经升级到 v3 版本了，个人业余精力有限，还请体谅。
