### ISSUE TITLE
我只需要将图片转换成base64，不上传到服务器，怎么做

### ISSUE THREAD

**Issue by liujue** [wangfupeng1988/wangEditor#717]
官方的demo可以，我要怎么做

**Comment by lifei6671** [comment]
网上一搜一大堆文章，不明白为啥非得来这里提问呢？
[html5图片转base64](https://www.baidu.com/s?ie=utf-8&f=3&rsv_bp=1&rsv_idx=2&tn=baiduhome_pg&wd=html5%E5%9B%BE%E7%89%87%E8%BD%ACbase64&rsv_spt=1&oq=mysql%2520%25E5%2588%25A4%25E6%2596%25AD%25E6%2598%25AF%25E5%2590%25A6%25E5%25AD%2598%25E5%259C%25A8%25E5%25AD%2597%25E6%25AE%25B5&rsv_pq=8faa877e0004d0b8&rsv_t=0457al9%2B2Q1mNuQ3fMiw%2F2x5x%2BxWc1gWl8HjIwt5eHL%2BfvovGibGkiLaCy8WqJBqhPP3&rqlang=cn&rsv_enter=1&rsv_sug3=7&rsv_sug1=6&rsv_sug7=100&rsv_sug2=0&prefixsug=html5%2520%25E5%259B%25BE%25E7%2589%2587%25E8%25BD%25AC&rsp=1&inputT=6350&rsv_sug4=6350)

**Comment by liujue** [comment]
我也不明白，我是指的是用的你插件，又不是单独转换，单独转换我也不需要问你

**Comment by lifei6671** [comment]
本来就不需要用插件的，为啥要用插件实现呢？html5自带的API就能实现啊。
何况，你只是转换为base64。
这个编辑器的功能是富文本编辑，其他和富文本无关的，应该自己去实现吧。

**Comment by wangfupeng1988** [comment]
直接升级到V3版本吧，一个配置即可支持  http://www.kancloud.cn/wangfupeng/wangeditor3/335781
