### ISSUE TITLE
兄弟,新踩的坑还是热乎的!!!

### ISSUE THREAD

**Issue by Quiet95scholar** [wangfupeng1988/wangEditor#718]
<textarea id="wangEditor" ></textarea>
这个id  不能是"wangEditor".
如果把id设置成"wangEditor",
会因为未知原因导致重复加载JS,
从而提示一个页面不能重复引用JS文件

**Comment by wangfupeng1988** [comment]
多谢反馈！
V3版本已经发布了，以后就不允许使用 textarea 来实现编辑器了，必须是 div
