### ISSUE TITLE
如何自定义标题(head)

### ISSUE THREAD

**Issue by comeonbob** [wangfupeng1988/wangEditor#719]
目前支持的是标题1至标题5, h1-h5.
我想增加自定义的标签， 如大标题<h1>, 小标题<h4>, 引用<q>, 脚注<sub>等标签。

**Comment by comeonbob** [comment]
// 标题
        editor.config.head = {
          '<p>': '正文',
          '<h1>': '大标题',
          '<h2>': '段落标题',
          '<strong>': '正文强调词',
          '<q>': '引用'
        }
想实现这种..

**Comment by comeonbob** [comment]
// 创建 menu 对象
        var menu = new E.Menu({
            editor: editor,
            id: menuId,
            title: lang.head,
            commandName: 'formatBlock'
        });

        // 初始化数据
        var data  = {
            '<p>': '正文',
            '<h1>': '大标题',
            '<h2>': '段落标题'
        };

虽然该源码， 在head 菜单中可以实现我的需求。还是请问下，有没有其他方法可以实现

**Comment by wangfupeng1988** [comment]
网页编辑器肯定实现不了word那么强大的格式，我也不打算做的这么复杂，如果你有需求，直接使用在线的office就好了。
V3版本已经发版了，这块我反而做的更加简洁了，削减了一些功能。

**Comment by comeonbob** [comment]
@wangfupeng1988 
3q
