### ISSUE TITLE
使用手册中发现的两处小问题

### ISSUE THREAD

**Issue by mengweilong** [wangfupeng1988/wangEditor#721]
![image](https://cloud.githubusercontent.com/assets/15653688/26479602/3f3494c0-4207-11e7-8ab0-d88bba43ebf6.png)

使用手册中明明提示fonts和css文件夹要放在同一目录中但是这图片中好像不是啊...容易误导

![image](https://cloud.githubusercontent.com/assets/15653688/26479682/cd61db4a-4207-11e7-91bb-a4ec4626d57f.png)

强迫症表示打扰了-_-!

**Comment by wangfupeng1988** [comment]
多谢反馈，文档还是应该较真一些的，毕竟大家都看。
不过现在 V3 已经更新了，V2的文档估计慢慢就没人看了，😝
