### ISSUE TITLE
请问：在struts2框架下  如何向后台发送图片。谢谢

### ISSUE THREAD

**Issue by vzpd** [wangfupeng1988/wangEditor#723]
我做了小项目 ，使用struts2框架  使用struts2框架自带的文件上传功能  jsp页面里的form表单内的图片可以正常上传   jsp下配置editor.config.uploadImgUrl = 'upload.action';    不能正常上传图片  请问怎么处理？  谢谢

**Comment by lifei6671** [comment]
编辑器文件上传和后台无关，编辑器只负责将文件上传到你指定的URL上，至于你怎么接收是后端的事情了。
你这个文件也很简单，使用chrome浏览器打开，f12 调出控制台，看下编辑器上传的地址返回值是什么就知道错误在哪了。
