### ISSUE TITLE
怎么能让编辑器不转义<和>

### ISSUE THREAD

**Issue by froginfrog** [wangfupeng1988/wangEditor#724]
比如：&lt;b&gt;你好&lt;/b&gt;，
在保存之后都变成了：&lt ;b&gt ;你好&lt ;/b&gt ;
怎么设置呢？谢谢

**Comment by lifei6671** [comment]
切换到源码模式。

**Comment by wangfupeng1988** [comment]
编写html代码不是富文本编辑器的应用场景，你可以考虑使用其他工具。富文本编辑器是用来编辑图文文章的，工具要选对口合适的。

**Comment by froginfrog** [comment]
不好意思，我是新手，没明白你说的富文本编辑器的应用场景。我只是试了一下工具条上的字体加黑，提交到后台保存之后就被转义了。我并没有想用这个编辑HTML代码。

**Comment by lifei6671** [comment]
@froginfrog 有些后端框架会对前端提交的数据进行HTML转义。
