### ISSUE TITLE
富文本编辑器存在脚本注入问题，我之前发的issues作者硬是说没有问题

### ISSUE THREAD

**Issue by annofy** [wangfupeng1988/wangEditor#725]
我是做一个个人博客。在文本框内写入了
<script src="..."></script>这样的东西，能够得到正确的html内容，但是在此把这个html内容的导入到wangEditor以后，wangEditor 就把这个文本当成了脚本内容。

**Comment by annofy** [comment]
![image](https://cloud.githubusercontent.com/assets/22249411/26666165/1829dbdc-46d1-11e7-8232-2409bf53c691.png)
作者大人，不会没事找你麻烦。你自己好好看看，富文本编译器既要能编辑文本，也要能处理文本的。我不是高级大师，只是一个用轮子的人，请用点心，对待自己产品

**Comment by lifei6671** [comment]
没明白你的意思。你是说这个编辑器会把脚本当成真正的脚本解析？

**Comment by wangfupeng1988** [comment]
我也没明白楼主的意思，可以详细说一个具体的场景，把每一步详细描述一下

**Comment by cuijianxiong** [comment]
他的意思是说可能存在xss漏洞   比如<script>alert(document.cookie)</script>

**Comment by wangfupeng1988** [comment]
预防xss攻击，文档中给出解决办法了

**Comment by annofy** [comment]
@lifei6671 对的，这样问题。我在大概3个月前遇到的。我到官网去实验性的操作了给出示例富文本编辑器，依旧还是这样

**Comment by annofy** [comment]
@wangfupeng1988 不是xss 攻击问题，而是编辑器不能正确处理html，尤其当html中有<script>标签的时候

**Comment by annofy** [comment]
不说多次编辑，当第一次获取到编辑器返回的html文本以后，再次把html文本放入到富文本编辑器中就会存在这个问题。script 标签被解析成了本页面导入的脚本。不再是一个文本了

**Comment by annofy** [comment]
上面截图，就是第二从编辑器中获取内容，然后变成了页面的插入标签。可以看到pre和code标签下面script竟然不是文本

**Comment by annofy** [comment]
截图可以查看[https://github.com/wangfupeng1988/wangEditor/issues/594](url)

**Comment by annofy** [comment]
- #594

**Comment by lifei6671** [comment]
@annofy 你的意思是不是通过编辑器的API插入数据到编辑器，script标签不会被过滤是吧？

**Comment by annofy** [comment]
@lifei6671 对的

**Comment by wangfupeng1988** [comment]
非常抱歉，v2 此后不维护了，已经升级到 v3 版本了，个人业余精力有限，还请体谅。
