### ISSUE TITLE
上传图片返回路径编辑器不识别我系统中定义的常量

### ISSUE THREAD

**Issue by Iamfeiwang** [wangfupeng1988/wangEditor#726]
上传图片返回路径编辑器不识别我系统中定义的常量，比如路径/web/public的路径常量__PUBLIC__，编辑器不识别这个路径常量，系统其他地方是识别这个常量的

**Comment by lifei6671** [comment]
你说的这个常量是PHP中的常量吧！？，这个编辑器是在浏览器中执行的，看到读不到你的常量。

**Comment by wangfupeng1988** [comment]
这应该是你编程基础不过关，找身边人问一下吧。
