### ISSUE TITLE
关于插入代码后的体验问题

### ISSUE THREAD

**Issue by Ctonys** [wangfupeng1988/wangEditor#73]
输入一段文本，接着插入代码,如果要继续在插入的代码后台输入文本,只能切换到源码状态，在代码标签后面输入内容,有不有可修改的方法

**Comment by wangfupeng1988** [comment]
你说的是不是插入代码之后，在代码块中输入文字，回车时代码段会分成两个？

如果是这个问题，可以参考文档，看看如何配置高亮代码 http://www.kancloud.cn/wangfupeng/wangeditor/65742

这样就可以解决了。

如果不是我说的这个问题，请再详细描述一下你的问题的场景。

**Comment by Ctonys** [comment]
比如我现在打开了插入代码的窗口，输入代码并且点击插入，代码成功插入到了编辑器中。这个时候，我的光标是在代码块中,但是我想在代码块的下面继续输入文本(非代码),只有通过切换到源码窗口中在代码块后面加入文本，再次切换到非源码窗口才能继续录入

**Comment by wangfupeng1988** [comment]
不对吧，你去官网的demo实验一下，插入代码之后，编辑器会自动再后面加一个空行的，你可以再空行中输入任何内容。

估计你的版本太旧了，下载一个最新的试试。

**Comment by wangfupeng1988** [comment]
插入高亮代码之后，末尾不加入空行的bug已经修复，可以去github下载最新代码。
