### ISSUE TITLE
全屏菜单项在3.0没了吗？

### ISSUE THREAD

**Issue by qxwei** [wangfupeng1988/wangEditor#730]
全屏菜单项在3.0没了吗？

**Comment by wangfupeng1988** [comment]
菜单没有了，但是文档中有描述

**Comment by chris-peng** [comment]
写了个简单的全屏插件，你可以试试
https://github.com/chris-peng/wangEditor-fullscreen-plugin

**Comment by zazzlec** [comment]
> 写了个简单的全屏插件，你可以试试
> https://github.com/chris-peng/wangEditor-fullscreen-plugin

有vue版本的吗？
