### ISSUE TITLE
wangeditor3.0还能集成plupload么

### ISSUE THREAD

**Issue by kindevil** [wangfupeng1988/wangEditor#731]
wangeditor3.0还能集成plupload么

**Comment by hasbug** [comment]
个人认为没必要用plupload了呀。作者都实现了上传前 上传中  上传后的处理了，这不就plupload做的事么？
监听函数
可使用监听函数在上传图片的不同阶段做相应处理
`

editor.customConfig.uploadImgHooks = {
    before: function (xhr, editor, files) {
        // 请求发送之前
    },
    success: function (xhr, editor, result) {
        // 上传成功之后
        // result 是服务器端返回的结果
    },
    fail: function (xhr, editor, result) {
        // 上传失败之后
        // result 是服务器端返回的结果
    },
    error: function (xhr, editor) {
        // 请求发生错误
    },
    timeout: function (xhr, editor) {
        // 请求超时
    }
}`

**Comment by kindevil** [comment]
@hasbug 这个我知道，但是这个不是只能上传图片么，我如果还想上传文件什么的不是还得用plupload

**Comment by hasbug** [comment]
@kindevil 3.0貌似也加了附件上传 你可以去官方文档看看  具体我不太清楚了

**Comment by kindevil** [comment]
@hasbug 文档里就说了上传图片，没说附件的事

**Comment by hasbug** [comment]
@kindevil 哈哈 我下午折腾了一下，发现还是得整合plupload 目前发现官方是限制后台的返回格式，然后发现附带data没有随着图片提交···

**Comment by kindevil** [comment]
@hasbug 不知道怎么整合。。

**Comment by hasbug** [comment]
@kindevil +1 现在回滚2.X也不行 因为2.X的时候 我的plupload没有在vue里生效，没有生成input···

**Comment by kindevil** [comment]
@hasbug 等等看吧

**Comment by wangfupeng1988** [comment]
我后面（下次升级）会增加一个自定义的返回格式的处理，到时候可以实现上传附件了。

**Comment by kindevil** [comment]
@wangfupeng1988 好的

**Comment by lann1986** [comment]
@hasbug 请求发送之前判断一次上传文件个数后，如何阻止请求继续发送呢？alert?

**Comment by wangfupeng1988** [comment]
配置最多上传的文件格式，下一次发版加上。

**Comment by wangfupeng1988** [comment]
> 配置最多上传的文件个数，下一次发版加上。

已解决

> 会增加一个自定义的返回格式的处理

已解决
