### ISSUE TITLE
table样式问题

### ISSUE THREAD

**Issue by dante1234** [wangfupeng1988/wangEditor#733]
页面上看到的table是没有边框颜色，是不是还没有实现？

**Comment by IVANLEE99** [comment]
![image](https://cloud.githubusercontent.com/assets/18308725/26822761/c43bc678-4add-11e7-899e-144d3663a349.png)

生成的table就是border为0的，自己设置一下border就行了，略坑

**Comment by wangfupeng1988** [comment]
在展示页面，要自己设置table、code、quote这些标签的样式，我后面会不从到文档中，并把目前编辑器中的样式公开出来供参考。

**Comment by wangfupeng1988** [comment]
https://www.kancloud.cn/wangfupeng/wangeditor3/335775
