### ISSUE TITLE
复制粘贴图片上传失效

### ISSUE THREAD

**Issue by aozijian** [wangfupeng1988/wangEditor#736]
是这样的，我们现在的需求是从别的网站复制内容到编辑器里，内容包括文字和图片，但发现复制回来的图片地址是网络地址，而且有很多属性，所以我需要在粘贴内容之后把内容里面的图片上传到七牛云上，获取一个七牛云返回的地址，但是现在问题是无论我复制的是别人网站的图片还是本机的图片，在调试模式下发现都没有执行wangEditor.js里面遍历读取粘贴图片的方法，所以并没有实现粘贴上传的功能，请问如何解决？

**Comment by wangfupeng1988** [comment]
你复制其他网站的图片，本来就无法实现粘贴上传。

**Comment by 547011926** [comment]
现在这个问题解决了吗

**Comment by wangfupeng1988** [comment]
看我之前回复的，没说要解决啊

**Comment by shanezhiu** [comment]
@wangfupeng1988 请问，为什么从别的网站图片复制过来的图片无法粘贴上传了？

**Comment by wangfupeng1988** [comment]
@shanezhiu 粘贴图片上传的方案可参考 https://github.com/wangfupeng1988/wangEditor/issues/1469#event-1591170067
