### ISSUE TITLE
菜单栏默认是不可点击的

### ISSUE THREAD

**Issue by huanggm** [wangfupeng1988/wangEditor#737]
目前官网上的编辑器也是这样的效果。就是编辑器初始化后，菜单默认是不可点击的。
只有点击编辑器内部，获取焦点之后，菜单才能使用。
感觉在使用上有点不方便，比如我想直接上传图片，或者插入表格就不行了。

还有一个小问题就是菜单栏中的弹框不消失：我发现只有点击编辑器区域，菜单栏的弹框才会消失，但是点击编辑器外其他区域，弹框就不会消失。

谢谢！

**Comment by wangfupeng1988** [comment]
OK  接收你的建议，我记录下来，随着发版来更新这些问题。请关注发版记录

**Comment by wangfupeng1988** [comment]
已解决
