### ISSUE TITLE
菜单栏没有tooltips？

### ISSUE THREAD

**Issue by IVANLEE99** [wangfupeng1988/wangEditor#741]
![image](https://cloud.githubusercontent.com/assets/18308725/26809614/bea3ffe0-4a98-11e7-812d-2c300dbaac12.png)

**Comment by wangfupeng1988** [comment]
现在完全可以使用图标、droplist来表达各个功能，无需使用 tips了

**Comment by tomoya92** [comment]
图标颜色都变成灰色的了，看着不太舒服

**Comment by wangfupeng1988** [comment]
toolbar的背景色可以搞成白色，这样就好一些了。

**Comment by IVANLEE99** [comment]
![image](https://user-images.githubusercontent.com/18308725/40637069-4e400af8-6335-11e8-98b9-6195dd461147.png)


没办法，需求是有的只能结合[jq tooltips插件来完成了](http://tianshaojie.com/tooltips/example.html)
