### ISSUE TITLE
几点小小建议

### ISSUE THREAD

**Issue by hasbug** [wangfupeng1988/wangEditor#742]
1.随图片上传附带的数据能否和图片一样通过form-data传输，而不是拼接到url？
2.能否在图片上传before事件里设置最终图片上传地址
3.能否不限定后台返回格式，交由前端自己根据各自后端返回的信息判断是否上传成功，并通过一个钩子触发编辑器的成功事件，告知编辑器，我图片上传成功了，图片地址是多少多少。。。

**Comment by wangfupeng1988** [comment]
> 1.随图片上传附带的数据能否和图片一样通过form-data传输，而不是拼接到url？

可以，没问题，下次升级加上

> 能否在图片上传before事件里设置最终图片上传地址

不明白这个的使用场景是什么

> 能否不限定后台返回格式，交由前端自己根据各自后端返回的信息判断是否上传成功，并通过一个钩子触发编辑器的成功事件，告知编辑器，我图片上传成功了，图片地址是多少多少。。。

下次升级支持，关注升级报告

**Comment by hasbug** [comment]
@wangfupeng1988 嘿嘿  第二个场景其实是我们业务没有细分造成的，忽略吧。  谢谢回复！

**Comment by wangfupeng1988** [comment]
好，剩下的问题下一次升级更新上。

**Comment by WalterZou** [comment]
@wangfupeng1988 一个小建议：支持自己配置 fileName，很多后端会限制 formData 的 Key，例如：后端只接收 `images[]` 的 formData

**Comment by tomoya92** [comment]
还有一个小建议，图片比较小的可以转成base64, 比较大的就调用上传，我觉得这样比较好

**Comment by wangfupeng1988** [comment]
> 后端只接收 Key 为 images[] 的 formData
@WalterZou 这个具体啥意思？

**Comment by wangfupeng1988** [comment]
> 还有一个小建议，图片比较小的可以转成base64, 比较大的就调用上传，我觉得这样比较好

@tomoya92 这个先不加了，统一配置吧。

**Comment by WalterZou** [comment]
@wangfupeng1988 
源码中
```
 // 添加图片数据
        var formdata = new FormData();
        arrForEach(resultFiles, function (file) {
            formdata.append(file.name, file);
        });

```
`file.name` 改成可配置项，很多后端都是限制了的，比如限制成`images[]`，那就应该是
```
formdata.append('images[]', file)
```

**Comment by wangfupeng1988** [comment]
明白了

**Comment by wangfupeng1988** [comment]
那两个问题已经解决

**Comment by wangjiaqi0821** [comment]
字体颜色可以改为 设置为红色 然后打出来的字就是红色的吗
