### ISSUE TITLE
表格的删除事件，好像不能触发 编辑器的 onChange事件

### ISSUE THREAD

**Issue by kukufengfeng** [wangfupeng1988/wangEditor#743]
表格的删除按钮，没有触发 onChange事件调用

**Comment by wangfupeng1988** [comment]
v3版本已经暂时去掉了 onchange 事件，因为 onchange 事件触发的来源太多，不好监控，总是出问题。
你可以说一下你使用 onchange 事件的场景，我看能否通过其他操作解决。如果必须使用 onchange 事件，那我再在v3版本中加上。

**Comment by codinglilong** [comment]
@wangfupeng1988 onchange去掉了那我用react如何难道改变后的内容呢？

**Comment by zhouhao4221** [comment]
没有监听事件，vue里根本没法用

**Comment by wangfupeng1988** [comment]
别急别急，下次发版一定加上`onchange`，这个优先级定位最高！

**Comment by wangfupeng1988** [comment]
已增加 onchange
