### ISSUE TITLE
关于3.0版本编辑器的自动增长问题。

### ISSUE THREAD

**Issue by a864473066** [wangfupeng1988/wangEditor#745]
本人目前在做一个博客网站，在找编辑器时找到了这款，发现UI简单比较轻量级便使用了。

在使用过程中发现，编辑器似乎不支持自动增长（一般主流网站基本都是自增长，例如：知乎、简书等。去主站看了下API里面也没有提示）。

之后看了下源码：
`
js:
_initDom(){
...
$textElem.addClass('w-e-text');
...
}
css:
.w-e-text {
  padding: 0 10px;
  overflow-y: scroll;
}
`

应该是不支持自增长。
希望作者能够加入该功能，辛苦了。

**Comment by a864473066** [comment]
自己改了下代码，弄成自己想要的效果了。btw，3.0的编辑器为何不能处理图片的长宽了？

![1](https://user-images.githubusercontent.com/15086848/26963903-ac9a4e68-4d21-11e7-97d9-ee90a864dd1f.png)

感觉编辑器还是存在一些小瑕疵的，比如没选中编辑器toolbar就会失效（hover不会做出响应）。
表格、图片的弹窗是根据编辑器头来定位的，如果编辑器是自增长高度，每次插入图片便会跳至页头。
复制粘贴文本后不会自动换行等（如果复制的之后一行是code块，就很难另起一行，有点头大）。

**Comment by wangfupeng1988** [comment]
> 编辑器似乎不支持自动增长

我理解你意思应该是如果写的内容过多，编辑区域会自动增加高度，这样的话，编辑区域就不会出现滚动条，只有浏览器的滚动条。但是，如果这样的话，又会引出的问题就是，toolbar应该fixed顶部。

> 3.0的编辑器为何不能处理图片的长宽了

选中图片，再点击toolbar“图片”按钮，会提供`max-width`的选择

> 其他问题

v3 版本刚刚发布，接下来还会不断收集反馈、升级更新，会越做越好，请随时关注新版升版内容。不过奈何这是个个人开源项目，全靠业余时间维护，因此进度可能会慢一些。

**Comment by sanzewen** [comment]
真是巧啊,原来你就是"深入理解javascript原型和闭包系列"的博主.目前正在学js,高级编程那本书里面对于闭包的解释有些少,到网上搜到你的博文看了后对于闭包明白不少.

**Comment by wangfupeng1988** [comment]
@sanzewen 积极学习是好事儿
