### ISSUE TITLE
如何绑定事件？

### ISSUE THREAD

**Issue by jingxiawl** [wangfupeng1988/wangEditor#749]
如何对编辑器绑定事件，现在要对编辑器内容做校验。会添加一些样式，我想在编辑器获得焦点的时候去触发他，但是没有作用我该怎么去绑定事件。例如onchange onfocus事件。文档写的好简单，都找不到绑定事件的方法

**Comment by wangfupeng1988** [comment]
> 文档写的好简单，都找不到绑定事件的方法

文档中没写的就是没有。如果后面升级，我肯定会把升级的内容不从到文档中。文档虽然简单，但是不缺。

`onchange`下次升级会加上。`onfocus`可能不太好一下自己加上，我看看能否下一次升版加上。
请随时关注升版内容。

**Comment by wangfupeng1988** [comment]
> onchange下次升级会加上。onfocus可能不太好一下自己加上，我看看能否下一次升版加上

onchange 已经加上，onfocus 暂时不加
