### ISSUE TITLE
【请愿】希望开发出脱离JQ框架，只支持现代浏览器的版本

### ISSUE THREAD

**Issue by ikarosu** [wangfupeng1988/wangEditor#75]
我们公司是不用兼容IE的，希望开发出脱离JQ框架的版本

**Comment by wangfupeng1988** [comment]
这是不可能的，即使脱离jq，也有很多浏览器兼容性的问题，jq是最好的兼容方式。
离开jq多出很多代码和风险，增加很多工作量。

再者，即使你不兼容IE，多引用一个jq会为你带来多大影响？

**Comment by ikarosu** [comment]
@wangfupeng1988 JQ这种用来做兼容的大型框架我们都没采用，所有的东西都是自己用ES写的，没觉得现代的浏览器还有哪里需要写兼容的

**Comment by wangfupeng1988** [comment]
但是这个编辑器是要兼容IE的

**Comment by ikarosu** [comment]
所以我只是希望有精简的现代版本而已

**Comment by huangbinjie** [comment]
+1,jquery太恶心了

**Comment by wangfupeng1988** [comment]
开发脱离JQ框架的编辑器是不可能的，不说别的，光时间都不够。
如果实在讨厌或者不能用jq，那只能另外选择其他产品或者自己开发一个。
