### ISSUE TITLE
wangeditor 2版本 字体加粗与斜体不起作用

### ISSUE THREAD

**Issue by mengxuetong** [wangfupeng1988/wangEditor#751]
wangeditor 2和3版本 集成到vue 字体加粗与斜体不起作用，在源码里面点击打印也没有任何输出

**Comment by wangfupeng1988** [comment]
你看执行了操作之后是否变为`<b>`和`<i>`标签，如果有了相应的标签，但是没有起作用，那就可能是浏览器的问题或者其他样式覆盖了。

**Comment by tanxuewei** [comment]
这个问题你有解决么

**Comment by wangfupeng1988** [comment]
v2.x 早就不维护了，抱歉
