### ISSUE TITLE
3.0不能设置uploadImgFileName

### ISSUE THREAD

**Issue by lewis-geek** [wangfupeng1988/wangEditor#752]
3.0的文档没有写怎么设置uploadImgFileName 
我看到低版本里面有用到 editor.config.uploadImgFileName 3.0的不行
项目着急上线呢 卡在这了 群也加不进去 希望能帮帮忙 🙏

**Comment by mohong** [comment]
查看了代码，好像不能设置。。。这个功能可以加上去吗 @wangfupeng1988

**Comment by lewis-geek** [comment]
查看了源码 解决方案如下
在 wangEditor.js 中搜索 formdata.append 把第一个参数 file.name 改成你要设置的内容就行 数据格式是字符串 @mohong

**Comment by wangfupeng1988** [comment]
我会在下次发版时增加上 file.name 的设置，关注升级信息。
