### ISSUE TITLE
和element的dialog弹窗组件集成后，出现无法渲染的问题

### ISSUE THREAD

**Issue by xumjs8623** [wangfupeng1988/wangEditor#753]
和element的dialog弹窗组件集成后，出现无法渲染的问题

**Comment by wangfupeng1988** [comment]
第一，看看js报错了吗。第二，看看渲染出来的dom结构是啥，截图出来。

**Comment by xumjs8623** [comment]
@wangfupeng1988   不好意思哦 已经解决了，我把富文本直接单独写为一个组件，然后再弹窗表单内引入这个组件就ok了。无法渲染是，我在弹窗的表单内直接引入富文本。 上星期3.0.0 是没js报错的，今天我更新了3.0.1后有一个js报错了。dom结构跟没引入一样

![image](https://user-images.githubusercontent.com/12467615/27026490-7d5af8d4-4f90-11e7-8378-a78d38d25c85.png)
![image](https://user-images.githubusercontent.com/12467615/27026495-81735614-4f90-11e7-8fff-fd2d41318085.png)
![image](https://user-images.githubusercontent.com/12467615/27026514-9033e01a-4f90-11e7-96ee-d6622fce8b6d.png)

**Comment by wangfupeng1988** [comment]
如何操作导致的报错？

**Comment by xumjs8623** [comment]
@wangfupeng1988  页面打开的时候就报错

**Comment by cjsky666** [comment]
貌似现在还有此问题。是不是不能在dialog中直接初始化？
只能再次引入？或者说是写在view页面上 不能写在弹窗？

**Comment by cjsky666** [comment]
@xumjs8623 感谢你的解决之道

**Comment by kdming** [comment]
@xumjs8623 thanks dialog中直接加载确实有问题，用你的方法解决了。
