### ISSUE TITLE
关于移动端的一个小问题希望作者修复

### ISSUE THREAD

**Issue by lyl199655** [wangfupeng1988/wangEditor#755]
移动端由于弹出键盘会修改浏览器的高度，编辑框检测到改变就会关闭掉DropPanel，而类似超链接这种要弹出输入法的功能，DropPanel打开的一瞬间就会被输入法取消，希望作者能去掉这个机制

**Comment by wangfupeng1988** [comment]
别想着支持移动端了，再怎么支持，用户体验也好不到哪儿去，干脆就不支持了。

**Comment by lyl199655** [comment]
那只有我们的自己动手改了，您是没有这个需求，而我们有，如果您能定制也可以，我们可以付报酬

**Comment by lyl199655** [comment]
用户体验也是相对的，有总比没有好得多，有些东西不是您想象的那么绝对

**Comment by wangfupeng1988** [comment]
那你自己改一下吧，个人开源产品，精力没有那么多，不能兼顾所有，只能兼顾大部分，望体谅！
