### ISSUE TITLE
使用 base64 保存图片回车图片被删除

### ISSUE THREAD

**Issue by Sera18** [wangfupeng1988/wangEditor#756]
我参照kancloud里面的Demo使用 base64 在文字后面上传了一张图片，然后想要修改排版，将图片放到文字下面，就在图片之前回车，图片就不见啦，请问这是什么原因？
v3.0.0版本在Windows系统Chrome浏览器下

**Comment by wangfupeng1988** [comment]
这个问题我发现了，下次升版肯定会解决这个问题，高优处理！

**Comment by Sera18** [comment]
好的，谢谢，wangEditor更新速度还是很快的，今天发现又升级啦，期待更好的wangEditor
