### ISSUE TITLE
希望可以在配置种设置不显示图片上传的拖拉框

### ISSUE THREAD

**Issue by evil2333** [wangfupeng1988/wangEditor#757]
希望可以在配置种设置不显示图片上传的拖拉框，点击菜单的图片按钮可以直接打开文件选择上传图片。

**Comment by wangfupeng1988** [comment]
不好意思，目前不支持这种配置。毕竟还要兼顾插入网络图片，而不是仅仅只有上传图片，因此就做成了弹框的形式，而弹框的形式无法配置成你说的样子。
