### ISSUE TITLE
【建议】增加清空textarea内容的函数

### ISSUE THREAD

**Issue by dengfuwei** [wangfupeng1988/wangEditor#76]
目前貌似不能直接清空textarea，使用$("textarea").val("")后，页面仍然显示，但是已经获取不到内容

**Comment by wangfupeng1988** [comment]
要看文档，文档中根本没有说要用`$("textarea").val("")`来清空内容
看这个文档，http://www.kancloud.cn/wangfupeng/wangeditor/65733，把文档中的字符串改为空字符串。

你去试试吧，清空内容是我一早就验证过的。
