### ISSUE TITLE
V3的代码高亮什么实现

### ISSUE THREAD

**Issue by Lxjazni7** [wangfupeng1988/wangEditor#760]
V3的代码高亮什么实现

**Comment by wangfupeng1988** [comment]
V3版本暂时不会在这些体验上升级，代码高亮还得过一段时间。
接下来V3重点要升级的还是文字的编辑体验，这是核心的地方。个人业余时间精力有限，只能一步步来，望体谅。

**Comment by Lxjazni7** [comment]
好的thanks

**Comment by imtinge** [comment]
@Lxjazni7 
V2用的是hightlight.js,自己引用一下就解决了，先不管语言类型吧

**Comment by Lxjazni7** [comment]
@imtinge v2的我知道 谢谢
