### ISSUE TITLE
chrome 下未选择任何内容点击“加粗”会报错： Failed to execute 'setEnd' on 'Range'

### ISSUE THREAD

**Issue by jaryway** [wangfupeng1988/wangEditor#762]
chrome 下未选择任何内容点击“加粗”会报错： Failed to execute 'setEnd' on 'Range'

**Comment by wangfupeng1988** [comment]
我在官网并没有复现你的问题

**Comment by jaryway** [comment]
![qq 20170621194401](https://user-images.githubusercontent.com/5987056/27382526-f1fdd7ee-56b9-11e7-83d7-9b3519dda6d8.png)
不要选择任何内容

**Comment by wangfupeng1988** [comment]
好，我已经看到，记录下来，计划1-2个小版本修复这个问题，请关注升级动态。

**Comment by wangfupeng1988** [comment]
已经解决
