### ISSUE TITLE
wangEditor3.0.1在React父组件传值到子组件，动态设置值的时候，会导致光标复位到起始位置，而不是所输入的文本之后

### ISSUE THREAD

**Issue by cdhjava** [wangfupeng1988/wangEditor#765]
// 已加载组件，收到新属性时调用
  componentWillReceiveProps(nextProps) {
    const {editor} =  this.state
    if(!!editor && nextProps.html){
      editor.txt.clear()
     // 执行这句之后，光标会跳到初始位置（内容开头）
      editor.txt.html(nextProps.html);
    }
    this.setState({
      editor: editor
    })
  }

**Comment by wangfupeng1988** [comment]
应该是`editor.txt.html()`里面没有做光标定位，本周修复该问题，请关注新版本发布动态

**Comment by wangfupeng1988** [comment]
已解决

**Comment by leizhongli** [comment]
要是在中间位置插入写字，执行editor.txt.html()，光标会定位到最后，而不是刚才插入写文字的地方
