### ISSUE TITLE
有序无序不能取消 代码插入后都是显示在一行

### ISSUE THREAD

**Issue by Lxjazni7** [wangfupeng1988/wangEditor#766]
有序无序不能取消 
获取富文本的html进行页面显示的时候 code的那一块不是分行的都是在一行内显示了

**Comment by wangfupeng1988** [comment]
发现这两个问题了，我记录下来排查，如果及早找出原因则近期发版更新，有限解决 code 不换行的问题。请关注新版发布动态。

**Comment by wangfupeng1988** [comment]
针对第二个问题，我用 https://github.com/wangfupeng1988/wangEditor/blob/master/example/demo/test-get-content.html  这个demo试了一下，获取html时候，代码并不是值显示显示在一行，例如我获取的html是

```html
<p>欢迎使用 wangEditor 富文本编辑器</p><p>欢迎使用 wangEditor 富文本编辑器</p><pre><code>    // 获取 html
    html: function (value) {
        const elem = this[0]
        if (value == null) {
            return elem.innerHTML
        } else {
            elem.innerHTML = value
            return this
        }
    },</code></pre><p><br></p>
```

**Comment by wangfupeng1988** [comment]
> 有序无序不能取消

这个问题还在继续跟踪中

**Comment by s952787097** [comment]
@wangfupeng1988 能不能加一个让无序和有序缩进的功能  我发现他们不能缩进

**Comment by wangfupeng1988** [comment]
> 让无序和有序缩进的功能

你是只多级的列表吗？
