### ISSUE TITLE
建议：uploadImgHooks 中的逻辑处理不严谨

### ISSUE THREAD

**Issue by devmsg** [wangfupeng1988/wangEditor#767]
![image](https://user-images.githubusercontent.com/15261658/27176506-56bee462-51f5-11e7-948a-a1db0ebd1b2a.png)
针对现在大多数上传图片都会往又拍云上走，但是返回的数据结构不能进行重构，所以改成以上建议

**Comment by devmsg** [comment]
并且 success 走的都是一条线 🤦‍♀️

**Comment by WalterZou** [comment]
是的，`hooks.customInsert`基本无法执行到~
#764

**Comment by wangfupeng1988** [comment]
已经解决
