### ISSUE TITLE
使用npm install wangeditor成功安装后无法引用

### ISSUE THREAD

**Issue by youngsherlee** [wangfupeng1988/wangEditor#768]
在node.js下成功安装wangeditor，但使用
`			script(type='text/javascript', src='/wangEditor.min.js')
`
无法引用

**Comment by wangfupeng1988** [comment]
`script(type='text/javascript', src='/wangEditor.min.js')` 这是个啥？没见过

**Comment by wangfupeng1988** [comment]
长时间不回复，暂时关闭。有问题可继续追问
