### ISSUE TITLE
有序列表和无序列表的样式优先级太低了，随便一个全局的设置就没了

### ISSUE THREAD

**Issue by IVANLEE99** [wangfupeng1988/wangEditor#769]
![image](https://user-images.githubusercontent.com/18308725/27208172-b3e038ea-5276-11e7-8deb-e511a8f4094b.png)
有序列表和无序列表的样式优先级太低了，随便一个全局的设置就没了

**Comment by wangfupeng1988** [comment]
这个我也没办法啊，我只能通过 class 来设置样式

**Comment by IVANLEE99** [comment]
class选择器改成id选择器，这样会不会好一点呢，关键时候还得用

> !important
