### ISSUE TITLE
【建议】希望能支持动态移除编辑器的api

### ISSUE THREAD

**Issue by langzu292** [wangfupeng1988/wangEditor#77]
有些项目上用到动态添加和移除编辑器，wangEditor目前可以动态生成，但好像不支持移除~
比如我点击一个“edit”按钮，调用以下代码初始化生成wangEditor
var editor = $('.editor').wangEditor();
然后我点击'cancel'，希望能调用下面代码
editor.remove();
目的是将编辑器从DOM树上移除，但是目前不能使用，报错了~
希望能支持，谢谢!

**Comment by wangfupeng1988** [comment]
1. 你在生成wangEditor编辑器之前，`.editor`是一个`textarea`；
2. 现在你点击edit按钮，执行代码`var editor = $('.editor').wangEditor();`。此时`.editor`这个`textarea`隐藏，编辑器会生成生成一个`div`，这个`div`包含了菜单、编辑器区域。
3. 你下面要点击cancel按钮，将编辑器从DOM树移除。你是要移除什么？有下面几种选择：

- 移除编辑器的`div`，显示出原来的`.editor`这个`textarea`。这样导致的结果是，`textarea`中的内容是一些Html代码，因为**富文本**编辑，当然要生成复杂的html代码。但是此时你再次点击edit按钮，还能继续加载出来编辑器，因为`.editor`这个`textarea`依然存在。
- 移除编辑器的`div`连同移除`textarea`。这样倒是移除干净了，但是导致的后果就是你再次点击edit按钮时候，加载不出编辑器了，因为`.editor`这个`textarea`已经被移除了，没有了，找不到了。

-------------------

以上只是我想到的几种情况，但是你依然要执行类似于`editor.remove()`这样的代码进行移除，你可以去执行`editor.$editorContainer.parent().remove()`或者`editor.$editorContainer.remove`来移除，这两句代码就代表了我以上说的这两种情况，都有一些缺陷。

----------------

我疑问，你为何非要从DOM树中移除，而不是隐藏呢？

**Comment by langzu292** [comment]
谢谢你的回答 @wangfupeng1988 
我这的需求是wysiwyg，编辑只是个辅助工具，而且一个页面所在并不只有一个编辑的地方，当编辑完成后，这些辅助工具就都要移除的~

**Comment by wangfupeng1988** [comment]
恩，如果满足你的需求，你就按我说的试试吧，有问题再提问。
