### ISSUE TITLE
背景色设置了就无法设置为白色了，这是什么套路？

### ISSUE THREAD

**Issue by IVANLEE99** [wangfupeng1988/wangEditor#770]
![image](https://user-images.githubusercontent.com/18308725/27208906-36d28344-527b-11e7-8028-60172b65ae72.png)

**Comment by wangfupeng1988** [comment]
我看官网是可以的。可以详细说说你的场景，以及你用了哪个浏览器？

**Comment by wangfupeng1988** [comment]
长时间不回复，暂时关闭。有问题可继续追问

**Comment by IVANLEE99** [comment]
![image](https://user-images.githubusercontent.com/18308725/40636831-fc436aa2-6333-11e8-8aab-4671d53a0421.png)

![image](https://user-images.githubusercontent.com/18308725/40636843-11391754-6334-11e8-9fe4-8f4c664851cb.png)


咋眼一看，
（直到今天才发现）
才发现有个隐藏的白色 刷子
但只能鼠标移动在上面才可以发现是可以设置为白色的

所以现在的问题是，能将白色的显示得更明显一点吗？
不用鼠标移动上去记就可以直到有白色背景可以设置

**Comment by wangfupeng1988** [comment]
哈哈 这个确实是一个反人类操作，我想下怎么搞

**Comment by yangfan0095** [comment]
怎么设置无背景色
