### ISSUE TITLE
文档的命令API的commandForElem示例代码错误

### ISSUE THREAD

**Issue by panhezeng** [wangfupeng1988/wangEditor#771]
文档的命令API的commandForElem示例代码错误，用了command命令。
还有第一参数e，我看源码作用就是e.preventDefault();

我觉得这个参数没必要放在第一个，这个完全可以使用者在触发事件里面自己实现。

还有如果参数改成对象形式，这样顺序就不重要了，而且commandForElem就可以和command合并了。

**Comment by wangfupeng1988** [comment]
v2 版本的问题不再更新了，建议升级 v3 版本，以后只维护 v3 版本。个人业余时间精力有限，请体谅。
