### ISSUE TITLE
建议：可以增加一个给图片添加链接的功能

### ISSUE THREAD

**Issue by insertSweat** [wangfupeng1988/wangEditor#772]
很多时候需要给图片添加链接，使得点击图片时可以跳转到其他页面

**Comment by wangfupeng1988** [comment]
这个功能暂时不打算加。
因为升级v3的目标是让编辑器更加简洁易用，能去掉的功能尽量去掉，很显然这个功能，应用场景不是很大。
现在互联网的文章，点击图片跳转链接的，我基本发现不了。
