### ISSUE TITLE
require js下面报错

### ISSUE THREAD

**Issue by guansq** [wangfupeng1988/wangEditor#773]
报了一下这个错误
require.js?ver=170616:1 Uncaught Error: Mismatched anonymous define() module: function (){return t.hljs}

**Comment by wangfupeng1988** [comment]
这应该是 v2 版本，现在已经正式切换到 v3 版本了，建议升级。v2的问题不再维护，毕竟个人业余时间有限，请体谅。

**Comment by guansq** [comment]
好的

**Comment by ChiakiYu** [comment]
@guansq   请问你升级了吗？我也遇到这个问题了。
