### ISSUE TITLE
编辑区 z-index 默认值太大

### ISSUE THREAD

**Issue by Houcer** [wangfupeng1988/wangEditor#776]
目前的值是10000，然后我的modal就被挡住了，无法交互。如图：
<img width="318" alt="ba23a957-0e05-4baf-8273-44c466af3363" src="https://user-images.githubusercontent.com/12626936/27251645-ab57fb9c-537d-11e7-8ee6-e8b0d2e6e060.png">
也许可以能弄成可配置的？

**Comment by wangfupeng1988** [comment]
本周末发布新版，增加这块的可配置，请关注新版本发布的动态

**Comment by wangfupeng1988** [comment]
已解决
