### ISSUE TITLE
上传图片时 customInsert Hook 无效

### ISSUE THREAD

**Issue by hisan-web** [wangfupeng1988/wangEditor#777]
上传图片时 customInsert Hook 无效,一直提示上传失败，实际已经成功返回json {"url": "http://www.baidu.com/xxx.png"}

**Comment by wangfupeng1988** [comment]
已经有好几个反馈这个问题的了，本周末发布版本会解决这个问题，请关注新版发布

**Comment by wangfupeng1988** [comment]
已解决
