### ISSUE TITLE
wangeditor3.0还支持自定义菜单吗？

### ISSUE THREAD

**Issue by xtliyongqiang** [wangfupeng1988/wangEditor#778]
wangeditor3.0还支持自定义菜单么，若支持该怎么使用文档中没有提到

**Comment by wangfupeng1988** [comment]
3.0不再支持自定义菜单了，2.0曾经支持过，但是后来发现没几个人用，因此就干脆去掉了。如果想自己添加菜单，fork代码自己改吧，src/js/menus 中都是各个菜单的配置，参考着写就行了，有问题直接找我。

**Comment by xtliyongqiang** [comment]
好的，谢谢
