### ISSUE TITLE
wangEditor3只能inlinecss？能不能加个配置可以关闭inlinecss

### ISSUE THREAD

**Issue by panhezeng** [wangfupeng1988/wangEditor#779]
wangEditor3只能inlinecss？能不能加个配置可以关闭inlinecss

```
var style = document.createElement('style');
style.type = 'text/css';
style.innerHTML = inlinecss;
document.getElementsByTagName('HEAD').item(0).appendChild(style);
```
最后可以加个customConfig的配置项目，禁用inlinecss不执行上面这段代码，让使用者自己import css文件，比如使用webpack

**Comment by wangfupeng1988** [comment]
不可以的，这个是产出 wangEditor.js 时候就带进去的，没法通过后期的配置给去掉。再者，使用 webpack，直接将css内容inline进来，也没有问题呀

**Comment by panhezeng** [comment]
感谢你这么快回复，可能是我没讲清楚。
你这样就是强制在页面插入了一份内联css，就没法做公共缓存css优化。
我看gulp是通过这段脚本实现替换
```
   .pipe(gulpReplace(/__INLINE_CSS__/gm, function () {
                    // 读取 css 文件内容
                    var filePath = path.resolve(__dirname, 'release', 'wangEditor.css')
                    var content = fs.readFileSync(filePath).toString('utf-8')
                    // 替换 \n \ ' 三个字符
                    content = content.replace(/\n/g, '').replace(/\\/g, '\\\\').replace(/'/g, '\\\'')
                    return content
                }))
```
我的意思是可以在开发代码里面把`var inlinecss = __INLINE_CSS__ ....appendChild(style);` 这部分代码封装为类似this._initConfig();这样的方法，比如this._initCss();在create的时候调用，然后可以通过customConfig的配置项，比如customConfig.initCss = false，不执行this._initCss()方法，默认initCss = ture可以执行。这样也不影响之前的使用者。如果不传initCss=false，默认行为和之前一样，兼容之前使用的人。

**Comment by panhezeng** [comment]
当然这样如果一个页面有多个实例的时候，就会重复插入css，这个也能解决，我看源码有全局变量记录editorId，可以在this._initCss();内部判断
```
if(this.initCss === ture && editorId===2){
var inlinecss = __INLINE_CSS__ ....appendChild(style);
}
```

**Comment by panhezeng** [comment]
说实话，还是不建议你用gulpReplace把css插入js，这样等于加大了js的体积，一般没有库类开发者这样做的，你这样相当于同一个页面，在wangeditor.js里面已经有一份和页面<style>部分相同的字节。
无形中增加了使用wangeditor带来的冗余代码。

**Comment by panhezeng** [comment]
还是分离吧，让使用者另行导入。

**Comment by wangfupeng1988** [comment]
要不你自己修改一下，或者 fork 一份自己改改。我还得考虑绝大多数使用者的引入成本问题。
