### ISSUE TITLE
无法选中文本

### ISSUE THREAD

**Issue by YanfirePRO** [wangfupeng1988/wangEditor#78]
![image](https://cloud.githubusercontent.com/assets/12682624/11266262/4be8ad7e-8ede-11e5-846e-97766c2334d6.png)
在freemaker框架下，无法通过鼠标移动光标以及选中文本。

**Comment by wangfupeng1988** [comment]
freemaker是一款java的框架，可前端代码没有关系的。无论是java框架还是.net、C#框架，最终生成的不都是html、css和js吗？

遇到这种问题，你需要定位清楚问题的原因。单独运行wangEditor的demo光标选中肯定没有问题，你可以试试再freemaker框架下，自己创建一个 `<div contentEditable ="true">请输入内容...</div>`，然后看看在此能不能移动光标选中？

这样多查查，就定位出问题的原因了。

如果查不出来，你将网页存储为静态页面，然后单独放在服务器上，看看能不能复现错误？如果能复现，吧这个网页连同css、js等需要的文件发给我，我给你看看。

如果静态网页复现不了，那我也就没有有效的办法来帮助你了。

**Comment by YanfirePRO** [comment]
contentEditable="true"   下鼠标也无法移动光标选中

**Comment by wangfupeng1988** [comment]
正常情况下 `<div contentEditable ="true">请输入内容...</div>`就像 `textarea`一样可以编辑、光标选中。如果你实验的不能移动光标选中的话，那说明你的外部框架或者项目环境对它产生了影响，具体原因还得具体分析。
