### ISSUE TITLE
larave-admin整合wangeditor3的时候老是会报个错误

### ISSUE THREAD

**Issue by super13** [wangfupeng1988/wangEditor#780]
整合2的没问题，但是2没有base64的图片上传。。

wangEditor.js:3320 The given range isn't in document.
    // 恢复选区
    restoreSelection: function restoreSelection() {
        var selection = window.getSelection();
        selection.removeAllRanges();
        selection.addRange(this._currentRange);  //这一行
    },

**Comment by wangfupeng1988** [comment]
看报错信息和base64无关，你如何操作报错的，描述一下场景

**Comment by oska2011** [comment]
我也遇到这个问题，后来发现是传参不对
开始是var editor = new E(this);
后来改成var editor = new E("#"+this.attr("id"));
就没报这个错了，不知道你是不是这个问题。

**Comment by wangfupeng1988** [comment]
长时间不回复，暂时关闭。有问题可继续追问
