### ISSUE TITLE
wangEditor3自定义菜单模板的功能也没了

### ISSUE THREAD

**Issue by panhezeng** [wangfupeng1988/wangEditor#782]
感觉wangEditor3比wangEditor2少了好多东西，更封闭了，都没考虑覆盖扩展。希望把MenuConstructors的this.$elem字符串设置成可以通过配置修改的。

**Comment by wangfupeng1988** [comment]
> 少了好多东西，更封闭了，都没考虑覆盖扩展

封闭、不考虑扩展并不是一定是坏事。因为v2考虑了很多扩展，但是能用起来的人特别少。但是，v2的扩展却使得设计非常复杂，维护成本高。因此，我才会在v3中砍掉一些“费力不讨好”的功能。

个人业余精力有限，望体谅！
