### ISSUE TITLE
wangEditor-3.0.2 按回车之后，光标没有跳转到新的一行，又跳回原来的行

### ISSUE THREAD

**Issue by cdhjava** [wangfupeng1988/wangEditor#783]
1. 按回车之后，光标没有跳转到新的一行，又跳回原来的行
2. 若页面有两个编辑器，则第一个编辑如1描述的情况，第二编辑器则输入内容停顿时自动换行

**Comment by wangfupeng1988** [comment]
把具体的复现场景说一下，以及什么浏览器，越详细越好。

我没看到官网能复现这个问题

**Comment by cdhjava** [comment]
1. 浏览器为360极速8.x
2. 我使用react包装了一下wangEditor，自定义了一个Editor
common/editor/index.js

`import E from './wangeditor/release/wangEditor'
import React from 'react'

const { Component } = React

export default class extends Component {
  // 构造函数
  constructor(props, context) {
    super(props, context);
    this.state = {}
  }

  // 初始状态或状态变化会触发render
  render(ReactElement, DOMElement, callback) {
    return (
      <div ref = "editorElem" style = {{ textAlign: 'left'}}/>
    )
  }

  //准备：即将被重新渲染，状态未变化
  componentWillUpdate(nextProps, nextState){

  }

  //完成：正在被重新渲染，状态已变化
  componentDidUpdate(prevProps, prevState){
  }

  // 已加载组件，收到新属性时调用
  componentWillReceiveProps(nextProps) {
    const {editor} =  this.state
    if(!!editor && nextProps.html){
      // editor.txt.clear()
      editor.txt.html(nextProps.html);
    }
    this.setState({
      editor: editor
    })
  }

  // 插入真实 DOM
  componentDidMount() {
    const elem = this.refs.editorElem
    const editor = new E(elem)
    // 编辑器内容改变触发
    editor.customConfig.onchange = (html) => {
      this.props.onChange(html);
    }

    editor.customConfig.uploadImgServer = 'http://www.baidu.com/'
    editor.customConfig.getUploadCfg = this.props.getUploadCfg
    editor.customConfig.menus = [
      'head',
      'bold',
      'underline',
      'strikeThrough',  // 删除线
      'emoticon',  // 表情
      'image',  // 插入图片
      'table',  // 表格
    ]

    editor.create()

    if(this.props.html){
      // editor.txt.clear()
      editor.txt.html(this.props.html);
    }

    this.setState({
      editor: editor
    })
  }

}
`
3. 页面实例化了两个Editor
3.1 引入自定义编辑器 import Editor from '../../common/editor'
3.2 加入两个编辑器实例
<Editor html={homeResModel.notices.content} onChange={(e) => {inputChange(e, 'content', -1, 'notices')}} getUploadCfg = {getUploadCfg}/>

<Editor html={homeResModel.contact} onChange={(e) => {inputChange(e, 'contact', -1, 'contact')}} getUploadCfg = {getUploadCfg}/>

**html中为React的state中的参数**

4. 第二个编辑器正常换行，第一个编辑器换行之后光标跳回内容的末尾

**Comment by wangfupeng1988** [comment]
你上面说了那么多，内容太多，线索太多，范围太大，如何定位问题？

> 我没看到官网能复现这个问题

这种简单情况下能复现吗？

**Comment by wangfupeng1988** [comment]
时间太久，暂时关闭，有问题可继续追加留言
