### ISSUE TITLE
vue中把editor设置为一个组件，动态更新内容，自动换行

### ISSUE THREAD

**Issue by hisan-web** [wangfupeng1988/wangEditor#784]
vue中把editor设置为一个组件，动态更新内容，自动换行，看了下源码，会给自动加入`<p></br></p>`代码，导致内容自动换行。

**Comment by wangfupeng1988** [comment]
> 会给自动加入<p></br></p>代码，导致内容自动换行。

会在 1-2 个小版本修复这个问题，请关注升级动态

**Comment by wangfupeng1988** [comment]
已解决了，试下最新版本，有问题继续追问即可

**Comment by hisan-web** [comment]
您好，我已经升级到了3.0.3，但是依然会出现这个问题， 在输入过程中会自动换行。

**Comment by wangfupeng1988** [comment]
你用源码中 vue 的 demo，加上你的动态更新的功能（简单模拟一下也行），看是否有这个问题。

定位问题，得抛开复杂的环境，找个简单的环境来复现它。

**Comment by hisan-web** [comment]
我的情况是这样的，我自己封装了一个editor组建，通过props的content传入值，然后通过watch监听content，利用editor.txt.html(val)去刷新编辑器的内容，结果导致每输入一行，就自动换行了。经测试拿demo模拟后也出现了这个问题。

**Comment by wangfupeng1988** [comment]
你通过`editor.txt.html(val)`只将内容直接清空了重置了，何来“每输入一行，就自动换行”啊？

**Comment by hisan-web** [comment]
对，重置后编辑器会自动加入 <p></br></p>标签，尝试过好几次，后来查看源码发现会自动加入<p></br></p>标签。

**Comment by wangfupeng1988** [comment]
重置后会加入`<p><br></p>`。

你如果是追加内容，建议使用`append`函数

**Comment by hisan-web** [comment]
其实实质传回来的内容无法使用append，如果使用append就重复了，我封装为一个组建后，其实你Onchang后的值我都是重新传回给父组建的，如果你使用append,那么你的值将会重复。

**Comment by wangfupeng1988** [comment]
我看下，可以在重置内容的时候，传递一个参数进去，控制是否追加`<p></br></p>`

**Comment by hisan-web** [comment]
好的谢谢。。时刻关注着呢。

**Comment by wangfupeng1988** [comment]
我昨天更新的时候试过，就拿一个简单的demo来说，单纯执行`editor.txt.html('<p>abc</p>')`，编辑器是不会再自动追加`<p><br></p>`的，你是又自己追加了其他操作了吗？

**Comment by hisan-web** [comment]
没有追加，其实我封装的组件就是把你onchang得值传给了父组件，然后父组件绑定了子组件的prop然后子组件watch监听后txt.html了，然后他就自动加上了那段换行代码
