### ISSUE TITLE
新版改动量太大 导致后台改动量太..

### ISSUE THREAD

**Issue by blankhang** [wangfupeng1988/wangEditor#785]
本来想升级最新版本...结果搞了半天 各种报错 
配置名称修改 
图片上传返回响应格式要求修改 ==
建议在升级的时候 稍微考虑下 老版本用户升级的代价吧 谢谢

**Comment by wangfupeng1988** [comment]
> 配置名称修改

这个前台改一下就行了，工作量不大

> 图片上传返回响应格式要求修改 ==

可以使用 customInsert 来自己定义数据格式

如果你老版本中没有太多定制的功能，升级的成本应该不大，1天时间搞定应该没问题
