### ISSUE TITLE
希望3.0能自己控制图片上传，不仅仅是控制返回的数据结构

### ISSUE THREAD

**Issue by Yusoo** [wangfupeng1988/wangEditor#786]
因为项目之前已经封装了图片的压缩、上传进度、错误等等的处理，不太好集成到3.0里去

**Comment by Yusoo** [comment]
最好能自定义选择文件之后的方法

**Comment by wangfupeng1988** [comment]
> 最好能自定义选择文件之后的方法

会在 2-3 个小版本修复这个问题，请关注升级动态

**Comment by guji-david** [comment]
怎么自定义选择文件之后的方法

**Comment by wangfupeng1988** [comment]
@guji-david 上面已经回复了，正在排计划解决

**Comment by wangfupeng1988** [comment]
https://www.kancloud.cn/wangfupeng/wangeditor3/335782  其中的“自定义上传事件”可以解决你说的问题
