### ISSUE TITLE
整合easyUI弹出框问题

### ISSUE THREAD

**Issue by yanchangyou** [wangfupeng1988/wangEditor#788]
和easyUI整合时， easyUI的弹出框是z-index是10000，wangEditor的z-index也是10000，就把弹出框挡住了，无法点击确认按钮。
临时解决方案是修改源码：把编辑内容区 z-index:8000，菜单区z-index:9000
看了源代码，编辑器的z-index可以配置，菜单区好像不能配置

**Comment by wangfupeng1988** [comment]
> 看了源代码，编辑器的z-index可以配置，菜单区好像不能配置

下一次升级支持这个配置，请关注升级动态

**Comment by Xanthuim** [comment]
确实存在遮住的问题。easyUI的模态对话框弹出后，下面的是无法操作的，但是富文本编辑器的内容是可以编辑。

**Comment by wangfupeng1988** [comment]
菜单区域的`z-index`可以配置了，试一下最新版本，有问题再来追问
