### ISSUE TITLE
上传图片只有base64和直接上传到服务器两种方式么？

### ISSUE THREAD

**Issue by lixiaobin0303** [wangfupeng1988/wangEditor#789]
使用base64上传图片base64怎么解码成图片啊   字符串太长后台没法存储啊   
如果使用直接上传到服务器 上传成功文本框才能看到吧  那如果文本框想换一张的时候怎么换服务器中的图片啊   求一个好的解决办法

**Comment by wangfupeng1988** [comment]
> 那如果文本框想换一张的时候怎么换服务器中的图片啊 

暂时不支持，不支持手动替换url，因为我理解的用户都不懂什么是url，他们就会上传、调整大小和删除

**Comment by lixiaobin0303** [comment]
那么base64编码的图片后台获取的时候内容过长怎么弄  有什么好推荐的解码的代码么

**Comment by wangfupeng1988** [comment]
base64过长无法解决，你可以选择直接上传到服务器。
