### ISSUE TITLE
z-index的设置，只能设置编辑区域，无法设置toolbar的小图标

### ISSUE THREAD

**Issue by pmsun** [wangfupeng1988/wangEditor#790]

**Comment by wangfupeng1988** [comment]
感谢反馈，我下次升级修复这个问题，请关注升级动态

**Comment by pmsun** [comment]
还有一个问题，我通过编辑器保存的文章，都是带有html的标签，当我再把这个文章内容赋值给编辑器的时候，这些html标签会当成是文本内容给显示出来。

**Comment by wangfupeng1988** [comment]
参见 https://github.com/wangfupeng1988/wangEditor/issues/781#issuecomment-310950844
