### ISSUE TITLE
表情有bug，出现很多不识别的空格

### ISSUE THREAD

**Issue by Rainylengend** [wangfupeng1988/wangEditor#791]
var faceStr = '😃 😄 😁 😆 😅 😂 😊 😇 😉 😌 😍 😘 😚 😋 😜 😝 😎 😏 😒 😞 😔 😣 😖 😫 😩 😤 😠 😡 😶 😐 😲 😵 😳 😱 😨 😰 😢 😥 😭 😓 😪';

faceStr.split(/\s+/).forEach(function (item) {
            if (item) {
                faceHtml += '<span class="w-e-item">' + item + '</span>';
            }
  });

代码这样修改

**Comment by Rainylengend** [comment]
新版本的menus选项少了很多，字体大小、一键排版、显示源代码的功能都没了，什么时候会加上啊

**Comment by wangfupeng1988** [comment]
@Rainylengend 

> 字体大小

不加了，用标签控制字体大小

> 一键排版

这个本来就没有

> 显示源代码

不加该接口了，用户如果需要完全可以自己做
