### ISSUE TITLE
新版 无法集成七牛的sdk

### ISSUE THREAD

**Issue by Cedcn** [wangfupeng1988/wangEditor#792]
希望可以自定义上传.  可以开发三方插件功能.

**Comment by wangfupeng1988** [comment]
v3 为了保持编辑器的纯粹性，已经不再默认支持七牛上传了。不过我会考虑开放类似的接口，让使用者自己去控制图片的上传。
计划会在近3个小版本的升级中解决这个问题，请关注版本升级动态。

**Comment by cdhjava** [comment]
我是直接改了wangEditor的源码，具体思路如下：
1. 在选择完图片，或者粘贴图片的钩子中，调用uploadImg方法前调用一下自定义方法（用户从阿里云、七牛拿到上传服务器地址、bucket、签名串等）
2. uploadImg方法中注释掉url拼接上传参数的代码（阿里云、七牛只接收formData提交的参数）
3.  formData append file文件数据放到拼接其它参数之后（阿里云、七牛要求file必须是在key参数之后）

**Comment by wangfupeng1988** [comment]
https://www.kancloud.cn/wangfupeng/wangeditor3/335782 其中的“自定义上传事件”可以解决你说的问题

**Comment by ChiakiYu** [comment]
@Cedcn  @cdhjava  两位大神，使用“自定义上传事件”集成七牛上传有思路吗？
