### ISSUE TITLE
html5苹果手机软键盘点完成按钮，怎么能不失去文本输入框文字后面那个小竖杠？

### ISSUE THREAD

**Issue by jeremyxieze** [wangfupeng1988/wangEditor#797]
大神求告知！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

**Comment by wangfupeng1988** [comment]
不支持移动端
