### ISSUE TITLE
工具条，鼠标移到H上出现选项栏，然后鼠标还没移到选项栏，选项栏就消失了(mac chrome)

### ISSUE THREAD

**Issue by yylww** [wangfupeng1988/wangEditor#799]

**Comment by wangfupeng1988** [comment]
发现这个问题了，很严重，我紧急处理一下。

**Comment by wangfupeng1988** [comment]
我发现官网上有这个问题，然后我查了一下代码，发现具体的 demo 没有这个问题。于是我把官网的 js 重新更新了一下，好了。
你还在其他地方看到这个问题吗？

**Comment by loongfive** [comment]
在vue中使用有这个问题

**Comment by btfrankenstein** [comment]
demo里是没有这个问题了，但是npm装的还是会有这个问题

**Comment by zhangluhu** [comment]
同楼上，vue中有这个问题，如果插入图片，导航栏的级别是低于图片级别的，会出现遮挡

**Comment by wangfupeng1988** [comment]
<img width="1030" alt="2017-06-27 4 49 55" src="https://user-images.githubusercontent.com/9583120/27579031-ae938938-5b58-11e7-89a9-af29f4bbeb2c.png">

demo 中 vue 的例子没有这个问题，chrome 浏览器。这个例子也是用 npm 安装的

**Comment by loongfive** [comment]
![](http://7xpmmc.com1.z0.glb.clouddn.com/TIM%E6%88%AA%E5%9B%BE20170627174731.png)

奇怪，我这就不行，win10 chrome npm安装的

**Comment by zhangluhu** [comment]
楼上是正解。从GitHub上clone下的代码运行完就是这种效果。谷歌和QQ浏览器一样的情况

**Comment by feicong666** [comment]
我npm装的在react中使用也会有这种问题

**Comment by Ilovekerry** [comment]
我也遇到了这个问题

**Comment by zuibunan** [comment]
这个菜单建议还是不要用hover这种效果，我更倾向于点击工具栏图标再展开菜单

**Comment by wangfupeng1988** [comment]
> 我手动给 .w-e-toolbar .w-e-droplist 加上 z-index: 10001 之后就正常了

实在不行，大家就用这种方式试一试，这是`z-index`早就开始支持了。
