### ISSUE TITLE
代码高亮

### ISSUE THREAD

**Issue by qq0827** [wangfupeng1988/wangEditor#8]
在IE中没法使用,版本ie10

**Comment by wangfupeng1988** [comment]
代码高亮现在已经弃用了，改为简单代码了。

**Comment by zhaopeiym** [comment]
晕，代码高亮为什么不要了？

**Comment by wangfupeng1988** [comment]
从一个编辑器的简介易用来看，代码高亮用处不是特别大，除了像博客园、csdn等专业程序猿网站。
但是如果每个编辑器都加入代码高亮，这带来的效果将是配置复杂、生成代码杂乱。
因此，我从编辑器整体用户的角度考虑，把代码高亮去掉了。如果你有特别需要，可单独联系我
