### ISSUE TITLE
关于一个页面中出现多个编辑器的冲突问题

### ISSUE THREAD

**Issue by jerry-he** [wangfupeng1988/wangEditor#80]
我们的项目是单页应用，im聊天编辑器使用的是wangeditor   同样，我想在邮件中也使用wangeditor，但是目前出现了版本冲突的情况，不知道能不能处理？同样，我们也需要ui自定义，不知道什么时候能支持

**Comment by wangfupeng1988** [comment]
> 但是目前出现了版本冲突的情况，不知道能不能处理？
群公告中明确提出，不受理『一句话问题』，有问题请一定要描述清楚。具体如何描述看群公告的要求，要不然我也不知道你什么问题。

不要嫌弃我繁琐，我这是在提高你解决问题的效率。

另外，ui自定义计划春节前发布出来。

**Comment by jerry-he** [comment]
![qq 20151127140732](https://cloud.githubusercontent.com/assets/5547912/11434997/3eb7fef6-9510-11e5-96a2-b7e1cf77849e.png)

具体的场景如下，至于具体如何冲突，因为具体代码太多，如果需要，我提供静态demo

**Comment by wangfupeng1988** [comment]
给我提供一个静态demo吧，放在QQ群文件中，然后@我说一下

**Comment by wangfupeng1988** [comment]
长时间不回复，问题将被关闭
