### ISSUE TITLE
上传图片到服务器地址该如何上传？

### ISSUE THREAD

**Issue by jusheng** [wangfupeng1988/wangEditor#802]
上传图片地址不是本地的，是
![image](https://user-images.githubusercontent.com/20462348/27538704-dc729ef0-5aab-11e7-8d61-246f7bf82e3b.png)
，为什么报这个错呢，![image](https://user-images.githubusercontent.com/20462348/27538677-b67ce3d6-5aab-11e7-9d8a-f85360f0a822.png)

**Comment by wh469012917** [comment]
跨域了

**Comment by wangfupeng1988** [comment]
端口不一样吧
