### ISSUE TITLE
感觉3.0越做越倒退了

### ISSUE THREAD

**Issue by wh469012917** [wangfupeng1988/wangEditor#803]
记得之前版本，可以直接用一个textarea标签就可以实例化出一个编辑器。现在怎么不行了？
然后我就得在表单提交的时候，获取编辑器内容，然后组装表单数据，再post到服务器。
不觉得这样麻烦许多了吗？

**Comment by wangfupeng1988** [comment]
首先，你不觉得你一直使用form提交很麻烦吗？为何不改为 ajax

**Comment by wh469012917** [comment]
是这样没错，但是对于后台管理面板来说，只要开发效率块，能用即可，无需考虑那么多用户体验啥的。我后台传图片甚至直接一个input:file就行了

**Comment by wangfupeng1988** [comment]
作为一个很多人用的开源项目，我得考虑开发和维护的成本。之前想的太多，做的也太多，所以导致业余时间不够，维护不及时。现在我要简化再简化，做专，而不是求全。
