### ISSUE TITLE
请问这个问题是哪里出错了呢？

### ISSUE THREAD

**Issue by jusheng** [wangfupeng1988/wangEditor#804]
![image](https://user-images.githubusercontent.com/20462348/27576346-49a5f3ac-5b4f-11e7-9d77-6620b74ad384.png)
如何变成只显示一个上传菜单呢？哪里的问题额

**Comment by wangfupeng1988** [comment]
v2 版本已经没精力维护了，建议升级 v3 版本，v3 早就发布了
