### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by luocong2016** [wangfupeng1988/wangEditor#805]
版本：3.0.2，3.0.3
1.斜体I：如果不选中会报错
Uncaught DOMException: Failed to execute 'setEnd' on 'Range': The offset 2 is larger than the node's length (1).
2.React 中 设置标题H 文字颜色，背景颜色
鼠标移开弹框直接消失

**Comment by Sorzen** [comment]
vue 中 设置标题H 文字颜色，背景颜色
鼠标移开弹框直接消失，同样出现此问题

**Comment by wangfupeng1988** [comment]
下载源码中 react 和 vue 的 demo，运行试一下。我刚才试着没啥问题

**Comment by luocong2016** [comment]
@wangfupeng1988
版本：3.0.2，3.0.3中 确实存在上述，在3.0.0中则不会出现此类问题 。
我就是通过 react 的demo改写的

**Comment by wangfupeng1988** [comment]
> 建议：toolbar 权值>编辑框

可以自己修改`z-index`

> 编辑页面字体颜色和背景颜色，无法正确存入数据库，应该是onchange 触发不正确导致

源码中的 demo 修改颜色和背景色都能正确触发 onchange

**Comment by wangfupeng1988** [comment]
最后，提问题再写`BUG`这种一看就不知道啥意思的标题，以后不受理。提交问题相互交流，就得每个字都描述清楚了。
