### ISSUE TITLE
上传成功，并且在浏览器直接能看到图片，但是上传后富文本还是提示错误。

### ISSUE THREAD

**Issue by Xanthuim** [wangfupeng1988/wangEditor#807]
首先说明下服务端使用的是node.js，按照你提供的示例上传成功了，但是在返回给富文本的时候却提示错误。
{"errno":0,"data":["/admin/upload-files/Hydrangeas.jpg"]}

请注意上面的路径，我通过我的地址是可以访问的：http://localhost:3000/admin/upload-files/Hydrangeas.jpg

我觉得富文本不能识别是因为，我的路径问题，但是这个路径应该是可以自定义的吧。
注：
图片在public/admin/upload-files/ 目录下面，而html文件在views/admin目录下面，而public目录和views是在同级别的目录。

最后返回的代码：

// 重新设置静态文件缓存
        // setStaticCache()

        // 返回结果
        var json = JSON.stringify({
            errno: 0,
            data: imgLinks
        })
        console.log(json)
        res.json(json)

**Comment by Xanthuim** [comment]
后来我调整了下目录，并且加上函数监听editor.customConfig.uploadImgHooks = {}，并且分别执行了customInsert和success方法，这说明结果是对的，但是图片不能显示在编辑器中。

**Comment by Xanthuim** [comment]
调整json格式后，按照customInsert的说明可以显示了，但是问题又来了。上传的头一张没有显示，但确实是成功的。

**Comment by Xanthuim** [comment]
发现insertLinkImg这个函数存在问题，我调试没有出现错误，但是就是不显示。如果我自己创建img是可以插进去的。

**Comment by wangfupeng1988** [comment]
> 发现insertLinkImg这个函数存在问题，我调试没有出现错误，但是就是不显示。如果我自己创建img是可以插进去的。

insertLinkImg 函数就那么一点点代码，你是发现哪一行有问题？

**Comment by jacyhao** [comment]
我也遇到了这样的问题，服务端都是按照文档进行返回的。而且图片也上传成功了，但是就是编辑器显示上传失败。

![developer tools - http wanxiang dev service driver_notice add 2017-07-06 15-07-13](https://user-images.githubusercontent.com/375904/27899487-fc1fff64-625c-11e7-9812-14d673d6ee31.png)

![monosnap 2017-07-06 15-06-49](https://user-images.githubusercontent.com/375904/27899489-00bb1bda-625d-11e7-8f2e-70fb64cab083.png)

已经上传成功的图片地址：http://oskd18b0c.bkt.clouddn.com/20170706/595de18496aef.jpg

**Comment by wangfupeng1988** [comment]
@jacyhao 看清楚文档是怎么写的，是`errno`，不是`error`

**Comment by wangfupeng1988** [comment]
长时间未回复，暂时关闭，有问题可继续追加留言
