### ISSUE TITLE
能否增加行间距的项目？

### ISSUE THREAD

**Issue by dongfenglong** [wangfupeng1988/wangEditor#81]
目前编辑器中不能设置行间距(line-height)。能不能给编辑器添加行间距的选项？

**Comment by wangfupeng1988** [comment]
恩，这个暂时还没有。

行间距需要每一块都设置不同的吗？你如果觉得目前编辑器的行间距不合适，可以自己调整一下，给`editor.$txt`增加一个样式就可以了。

你是第一个提出增加行间距需求的用户，之前貌似还没有人提到过，说明需求不是很多。这个功能我暂时不加。待最近的这次重构结束之后，支持自定义扩展菜单，像行间距这种简单的操作，可以很容易的扩展出来。

**Comment by wangfupeng1988** [comment]
恩，这个暂时还没有。

行间距需要每一块都设置不同的吗？你如果觉得目前编辑器的行间距不合适，可以自己调整一下，给`editor.$txt`增加一个样式就可以了。

你是第一个提出增加行间距需求的用户，之前貌似还没有人提到过，说明需求不是很多。这个功能我暂时不加。待最近的这次重构结束之后，支持自定义扩展菜单，像行间距这种简单的操作，可以很容易的扩展出来。

**Comment by wangfupeng1988** [comment]
近期的重构，我会加上这个功能，已经记录下来了。但是，现在的实现，还只能靠自己呀！
