### ISSUE TITLE
字体颜色，背景颜色，格式样式

### ISSUE THREAD

**Issue by luocong2016** [wangfupeng1988/wangEditor#810]
测试版本：3.0.3
1.字体大小（正文和H1~H5之间切换才会触发onchang）字体/背景颜色，无法修改。只能在第一次生成有效，修改不会触发onchange事件
2.背景颜色白色，感觉是隐藏按钮
3.字体/背景颜色无法还原正常格式
4.无法清空现有格式（比如我想还原为正常状态：正常字体、无背景色、无字体颜色，不加粗，不斜体，不引用这些）

**Comment by luocong2016** [comment]
形成原因： 
            // 触发 change 的有三个场景：
            // 1. $textContainerElem.on('click keyup')
            // 2. $toolbarElem.on('click')
            // 3. editor.cmd.do()
在菜单栏（下拉，切换等功能不会触发这3类事件）

**Comment by wangfupeng1988** [comment]
在菜单栏（下拉，切换等功能不会触发这3类事件）

所有的操作都会走到`editor.cmd.do()`中

**Comment by wangfupeng1988** [comment]
长时间未回复，暂时关闭，有问题可继续留言
