### ISSUE TITLE
关于v3的默认样式

### ISSUE THREAD

**Issue by jiananle** [wangfupeng1988/wangEditor#811]
版本 v3.0.3
为什么现在要把样式直接写在标签里啊， 这样比如我想把toolbar的背景色改成红色，这就要多绕几步，
不能把样式文件独立出来吗， 这样自定义式样时只要覆盖就行了，简单明了

**Comment by wangfupeng1988** [comment]
> 比如我想把toolbar的背景色改成红色

直接使用 JS 修改就行了

> 不能把样式文件独立出来吗

这样会增加很多使用成本
