### ISSUE TITLE
菜单栏里面的下拉菜单，鼠标无法移动过去点击

### ISSUE THREAD

**Issue by popmanhe** [wangfupeng1988/wangEditor#815]
例如**文字颜色**和**背景色**下拉列表。鼠标一移动，下拉列表就消失，无法点击里面的内容。我在Chrome和Firefox都有这个情况。 代码是用例子的。 我知道demo网站上没有这个问题，但是我在react里面引用就会出现这个问题。 不知道是否有解决方式？

**Comment by wangfupeng1988** [comment]
源码中也有 React 的示例 https://www.kancloud.cn/wangfupeng/wangeditor3/335788 你试一下会否有你所说的问题？

**Comment by uuappli** [comment]
我的 vue 项目也有这个问题，源码的 demo 也有，单独建一个空项目只放编辑器 也有这个问题

**Comment by acwong00** [comment]
@wangfupeng1988 React demo 中同样有这个问题

**Comment by eelogic** [comment]
是有这个问题，我自己设的弹出层 z-index:10001 可以解决，官网 demo 是在哪里手动设置了吧？

**Comment by haolidong** [comment]
1. 自己手动设置.w-e-droplist样式(也可以设置.w-e-menu的样式)
.w-e-droplist {
  z-index: 10001;
}
在vue项目里，上述css不能放在scoped里面

2. 另外，建议把.w-e-toolbar也增加一个样式
.w-e-toolbar {
  flex-wrap: wrap;
}
这样当editor宽度不足以容纳工具栏的图标时会自动换行，这时在 1 中就只能设置.w-e-droplist的z-index了，设置.w-e-menu也会遮挡droplist

**Comment by wangfupeng1988** [comment]
> 这样当editor宽度不足以容纳工具栏的图标时会自动换行

不支持换行，宽度不够建议减少菜单数量
