### ISSUE TITLE
v3现在是去掉全屏功能吗

### ISSUE THREAD

**Issue by huangzhiyang166** [wangfupeng1988/wangEditor#816]

**Comment by wangfupeng1988** [comment]
可以自己开发，源码中有demo，可以去看看文档。

全屏、查看源码这些，都是核心的编辑功能之外的东西，暂时去掉吧。个人业余精力有限，我只能专注最核心的东西。

**Comment by chris-peng** [comment]
写了个简单的全屏插件，你可以试试
https://github.com/chris-peng/wangEditor-fullscreen-plugin
