### ISSUE TITLE
3.0.3 版本，vue2 集成，使用工具栏设置文本文本样式，功能不能重叠

### ISSUE THREAD

**Issue by uuappli** [wangfupeng1988/wangEditor#817]
3.0.3版本，vue2 集成后，工具栏功能不能重叠，比如先设置 H1，然后在设置下划线，文本样式只剩下下划线，H1效果没有了，点其他功能一样，只保留了最后一个样式，我看官网 demo 是正常的，不知道集成到 vue2 是什么情况

**Comment by wangfupeng1988** [comment]
源码中也有 vue2 的 demo，https://github.com/wangfupeng1988/wangEditor/blob/master/README.md 这里有运行 demo 的示例，看在你环境下，是否也有你所述的问题。

**Comment by uuappli** [comment]
demo 示例 是没问题的，会不会我的其他组件影响的？

**Comment by haolidong** [comment]
vue2实测没遇到这个问题
![image](https://user-images.githubusercontent.com/10570086/27894040-5ff091f0-623c-11e7-80a9-f3055fff3b5d.png)

**Comment by uuappli** [comment]
你测试只是单独一个组件吗？ 我单独一个组件也没问题，只是集成到项目中就不行了

**Comment by wangfupeng1988** [comment]
自己排查一下原因吧。我只能做到测试单独组建没问题，肯定不可能把你的整个项目都拿过来去了解，那得花费太多成本。望体谅
