### ISSUE TITLE
多语言支持

### ISSUE THREAD

**Issue by meowtec** [wangfupeng1988/wangEditor#818]
国内有些开发者开发的项目是面向国外用户的，所以需要英文。
wangEditor 对于编辑器界面多语言的支持上有没有计划？

**Comment by wangfupeng1988** [comment]
可以考虑加一个`replace`功能。使用者去配置这个函数，例如
```
function replace (word) {
  if (word === '视频') {
      return 'video'
  }

}
```
这样让用户自己去配置，将显示的中文替换成英文。
你看如何？

**Comment by meowtec** [comment]
我更喜欢这样：
```
new Editor('#div', {
  locales: {
    video: '视频',
  },
})
```
不过这样的话，要让使用者知道文案对应的 key， 就要么在文档里面把所有文案对应的 key 列出，要么给对应的源代码地址。

**Comment by wangfupeng1988** [comment]
功能已加上，看文档 https://www.kancloud.cn/wangfupeng/wangeditor3/356777

**Comment by fancyboynet** [comment]
有动态修改语言的方法吗，比如中文和英文互相切换
