### ISSUE TITLE
在编辑框底部插入位置后，调整地图大小会有bug

### ISSUE THREAD

**Issue by ucando** [wangfupeng1988/wangEditor#82]
当在编辑框底部插入图片后，通过右下角的黑色角标纵向缩小地图时，角标的位置显示有bug。纵向放大图片没有这个问题，在编辑框中部插入的地图也没有这个问题，只有地图在最底部才会出现这个bug。

**Comment by wangfupeng1988** [comment]
我刚才去官网的demo试了一下，没看到由什么明显的bug，要不你帮我复现一下，然后截个图给我？

**Comment by ucando** [comment]
![qq 20151203111023](https://cloud.githubusercontent.com/assets/7608353/11550825/760cd38e-99ae-11e5-9880-e86ce16a832d.jpg)
浏览器是chrome 46 64位版本，纵向缩小的时候才会出现

**Comment by wangfupeng1988** [comment]
恩，我看到了。是一个问题。
不过，好在只是小图标的位置不对，想缩小图片也能缩小的了。
我回头看看这个问题吧，最近忙着捣鼓移动端呢。

**Comment by ucando** [comment]
其实也不影响使用，有空再改吧^_^
