### ISSUE TITLE
3.0.3集成vue的demo问题bug反馈

### ISSUE THREAD

**Issue by lenvonsam** [wangfupeng1988/wangEditor#821]
运行demo-in-vue, 发现里面的字体，文字颜色，文字背景，列表样式，对齐方式鼠标悬浮出现后，都无法进行操作，而且相比于2.x的版本，减少了几个功能，比如图片上传原来可以本地上传图片，demo里面就没有，还有全屏编辑也消失了

**Comment by richardo2016** [comment]
同样的问题，不知道是不是在 Vue 下特有的问题，从之前的 issue 来看，好像在非 Vue 环境下也出现了。如果找到了问题所在会提 Pr，不知道会不会合并
 (⊙o⊙)… ？@wangfupeng1988 

环境：
Google Chrome	59.0.3071.115 (正式版本) （64 位）
修订版本	3cf8514bb1239453fd15ff1f7efee389ac9df8ba-refs/branch-heads/3071@{#820}
操作系统	Mac OS X
JavaScript	V8 5.9.211.38

现象：
编辑器初始化后，非悬浮框类的 menus button 在鼠标进入的时候会显示下拉菜单。
【问题】一旦移出按钮，哪怕是进入下拉菜单，下拉菜单也会消失，这不符合 menus button 的预期行为。

**Comment by lenvonsam** [comment]
尝试添加了
.w-e-toolbar .w-e-droplist {
    z-index: 100;
 }
这段代码还是不行

**Comment by haolidong** [comment]
.w-e-droplist {
  z-index: 10001;
}
因为.w-e-text-container的z-index是10000

**Comment by richardo2016** [comment]
@lenvonsam 你肯定要根据具体场景啊，在我的场景下 100 是合理的。

**Comment by lenvonsam** [comment]
z-index问题解决了，那字体、字号如何添加

**Comment by cookiejyt** [comment]
其实在costomConfig中提到了zindex默认问题，个人感觉zIndex默认值太高，将默认的zIndex设置低
` editor.customConfig.zIndex = 1 `
再修改css
`  .w-e-toolbar .w-e-droplist{z-index: 2;}`

**Comment by wangfupeng1988** [comment]
> 那字体、字号如何添加

字体字号 v3 之中不在支持了，统一用标签和css控制，向 markdown 看齐
