### ISSUE TITLE
请问java图片上传后台怎么写？

### ISSUE THREAD

**Issue by marscl** [wangfupeng1988/wangEditor#823]
请问java图片上传后台怎么写？

**Comment by wangfupeng1988** [comment]
自己去查吧，java我也不会写

**Comment by shandianlala** [comment]
#前台页面：
<div id="editor">
       <p>欢迎使用 <b>wang</b> 富文本编辑器</p>
</div>
<script>
     var E = window.wangEditor;
    var editor = new E('#editor')
    editor.customConfig.uploadImgServer = '${basePath }/ajax/upLoad';
    // 或者 var editor = new E( document.getElementById('#editor') )
    editor.create();
</script>

#后台java代码实现，使用的是springmvc：
    @RequestMapping("ajax/upLoad")
	@ResponseBody
	public Map<String,Object> upLoad(HttpServletRequest request, HttpServletResponse response) {
		//创建一个通用的多部分解析器  
        CommonsMultipartResolver multipartResolver = new CommonsMultipartResolver(request.getSession().getServletContext());  
        Map<String,Object> map = new HashMap<String,Object>();
        //判断 request 是否有文件上传,即多部分请求  
        if(multipartResolver.isMultipart(request)){  
            //转换成多部分request    
            MultipartHttpServletRequest multiRequest = (MultipartHttpServletRequest)request;  
            //取得request中的所有文件名  
            Iterator<String> iter = multiRequest.getFileNames();  
            List<String> data = new ArrayList<String>();
            while(iter.hasNext()){ 
                //取得上传文件  
                MultipartFile file = multiRequest.getFile(iter.next());  
                if(file != null){  
                    //取得当前上传文件的文件名称  
                    String myFileName = file.getOriginalFilename();  
                    //如果名称不为“”,说明该文件存在，否则说明该文件不存在  
                    if(myFileName.trim() !=""){  
                        System.out.println(myFileName);  
                        //重命名上传后的文件名  
                        String fileName = "/../upload/" + file.getOriginalFilename();  
                        //定义上传路径  
                        String appRoot = request.getSession().getServletContext().getRealPath("") + File.separator;
                        String path =  appRoot + fileName;  
                        File localFile = new File(path);
                        if(!localFile.exists()) {
                        	localFile.mkdirs();
                        }
                        try {
							file.transferTo(localFile);
							data.add(fileName);
						} catch (Exception e) {
							e.printStackTrace();
							map.put("errno", 1);
							map.put("data", data);
							return map;
						}  
                    }  
                }  
            }  
            map.put("data", data);
            map.put("errno", 0);
        }  
		return map;
	}

=========================================================
注意：map.put("data", data);中data里的图片路径必须是正确的，在浏览器页面可以访问的到，不然即使图片上传到本地成功，页面里的富文本编辑器还是没有显示图片的。
附上我上传后处理的图片路径：<img src="/../upload/Save-Rock-And-Roll.jpg" style="max-width:100%;">

**Comment by aaa7636602** [comment]
你这返回的是个map，文档是要求是map吗？不要复制粘贴了，动点脑子。

**Comment by shandianlala** [comment]
@aaa7636602 
- 后台返回的数据你可以自定义返回对应的两个参数data、errno的值，我这用的是springmvc，用map封装了data.errno这两个值，返回数据的时候自动转成json；你也可以把数据data.errno的值拼接成字符串，在页面上转json，这个灵活的。
- 我不知道你会不会用wangEditor，但我是真用了，这段代码是我实现了功能后再贴出来的，并不是你所谓的复制粘贴；昨晚特意写了个demo [wangEditor-web](http://download.csdn.net/download/shandianlala/10043129)，要是不会请继续提问。

**Comment by naboxCom** [comment]
> 你这返回的是个map，文档是要求是map吗？不要复制粘贴了，动点脑子。

你动脑子喷人前可以跑跑人家的代码，你是真的懒！
shandianlalal的代码肉测有效，赞！
