### ISSUE TITLE
建议回归【查看源码】【全屏】功能按钮

### ISSUE THREAD

**Issue by xingwen1987** [wangfupeng1988/wangEditor#825]
如题：建议回归【查看源码】【全屏】功能按钮
场景：用户屏幕显示分辨率不同，编辑富文本时，这两个功能是非常非常需要的，建议老王回归这两个特别实用的按钮。

**Comment by wangfupeng1988** [comment]
这俩功能都可以自己开发出来，为何不自己做？开源产品能保证核心功能以及足够的扩展性就可以了，你不能什么事儿都想着拿来主义呀？

着急用就自己开发，有问题随时来提问。

**Comment by chris-peng** [comment]
写了个简单的全屏插件，你可以试试
https://github.com/chris-peng/wangEditor-fullscreen-plugin

**Comment by mymickey** [comment]
@wangfupeng1988 源码编辑模式如何开发呢  有demo吗
