### ISSUE TITLE
多个代码块之间的间隔问题

### ISSUE THREAD

**Issue by YounianC** [wangfupeng1988/wangEditor#828]
![image](https://user-images.githubusercontent.com/10089176/27992843-dd6167be-64cf-11e7-8098-217f50bc6499.png)

在这个图片里面，如果从别的地方拷贝代码过来，有时候会刚好两个代码块之间没有换行，如果这个时候想要在之间插入一些文字什么的会比较麻烦（换行会拓展代码块），我一般是打开源码模式直接插入一点东西然后返回再删除正常添加，有没有什么更好的方案呢？或者优化一下？

**Comment by wangfupeng1988** [comment]
感谢反馈，有解决方案的——在第一个代码块的最后一行，点击两次回车，然后此时光标就跳出代码块。
我记录下来，排到近期的升级计划中。请及时关注新版发布动态。

**Comment by YounianC** [comment]
这是已经实现了吗？我看http://www.wangeditor.com/的demo好像还不行。点击两次依然是扩展代码块。

**Comment by wangfupeng1988** [comment]
还没实现，但已经拍到升级计划中了，计划1-2个小版本内加上该功能。

**Comment by YounianC** [comment]
好的，3Q
