### ISSUE TITLE
vue图片上传问题

### ISSUE THREAD

**Issue by yxrh** [wangfupeng1988/wangEditor#829]
按照文档配置editor.config.uploadImgUrl = '/upload';之后显示错误：
vue.esm.js?8910:434 [Vue warn]: Error in mounted hook: "TypeError: Cannot set property 'image' of undefined"
上传文件按钮并没有出现，反而都没有了

![111](https://user-images.githubusercontent.com/30033322/28000833-fa598dc0-655a-11e7-9a10-8abbef91d683.png)

**Comment by joe223** [comment]
你可能需要注意下，V3版本中自定义配置是 `editor.customConfig`，https://www.kancloud.cn/wangfupeng/wangeditor3/335782

（如果用的是V2版本，请检查下编辑器对象是否正确初始化~）

**Comment by yxrh** [comment]
谢谢啦
