### ISSUE TITLE
视频插入代码可能有问题，导致只能插入swf

### ISSUE THREAD

**Issue by yk727228981** [wangfupeng1988/wangEditor#83]
没法上传图片，只好给你写行数了，1.3.12之前的好像都有这个bug，我只测试了1.3.12的bug，在第2445行有一段代码
if(sec.indexOf('http://') !== 0 && sec.indexOf('https://') !== 0) || src.indexOf('swf') === -1){
alert( LangFormatError);
return;
}
在“||”之后的代码有些莫名，导致只能插入swf的视频
但<embed> 标签支持多种视频格式
：） 隔壁杨师傅（逃

**Comment by yk727228981** [comment]
第327的
embed src="{src}" allowFullScreen="true" quality="high" width="{width}" height="{height}" align="middle" allowScriptAccess="always" type="application/x-shockwave-flash"
这个type种类感觉也没必要

**Comment by wangfupeng1988** [comment]
当前的『插入视频』的功能，主要针对从优酷、爱奇艺、QQ视频这些地方的视频分享，他们都是swf格式，用flash播放的。

另外，我近期会增加编辑器对移动端的支持，支持手机浏览器的常用视频格式。
