### ISSUE TITLE
ie 10  和 ie 11 在复制图片的时候 没有任何反应也没报错 其他浏览器没问题 可以转换成base64编码 

### ISSUE THREAD

**Issue by LengYXin** [wangfupeng1988/wangEditor#830]
ie 10  和 ie 11 在复制图片的时候 没有任何反应也没报错 其他浏览器没问题 可以转换成base64编码

**Comment by wangfupeng1988** [comment]
IE浏览器暂时不支持图片粘贴，该功能依赖于浏览器的API开放程度。

如果查到了更好的解决方案，我会及时更新到代码中。
