### ISSUE TITLE
HI，php图片上传问题

### ISSUE THREAD

**Issue by Cjlyn** [wangfupeng1988/wangEditor#832]
首先感谢您的文本编辑器。非常的好用而且方便。

有没有php里上传的代码demo呢？浏览器返回http://localhost/upload-img?token=abcdef12345  301
返回的这个token值如何调用呢？初次使用，不是很清楚，望解答..非常感谢！

**Comment by Cjlyn** [comment]
wangEditor 以base64保存图片文件就可以正常工作了。。。

**Comment by weiLuoChen** [comment]
## 22ERFEWF
