### ISSUE TITLE
怎么能支持html显示呢？

### ISSUE THREAD

**Issue by momoxiaoqing** [wangfupeng1988/wangEditor#833]
将html代码显示为网页内容。

**Comment by hinoah** [comment]
同求

**Comment by wangfupeng1988** [comment]
我是没看明白你问的啥？

提问问题要描述清楚，之前就有规定——不受理“一句话问题”

**Comment by xiaoheige** [comment]
请参考 https://www.kancloud.cn/wangfupeng/wangeditor3/335784
