### ISSUE TITLE
Vue的v-model更新编辑器内容问题

### ISSUE THREAD

**Issue by ImPigerla** [wangfupeng1988/wangEditor#834]
编辑器是否有个状态表示在编辑的过程中的？
我是想，监听value变化时，就去更新内容。
例如代码：

> watch: {
>             'value' (newValue) {
>                // hasFocus是我假设的，有没有知道当前是非编辑状态的？
>                 if (newValue !== this.wangEditor.txt.html() && !this.wangEditor.hasFocus()) {
>                     this.wangEditor.txt.html(newValue)
>                 }
>          }
>  }

**Comment by ImPigerla** [comment]
我已经解决这个问题，所以关闭这个issue

**Comment by wangfupeng1988** [comment]
@ImPigerla 可以在这里回复下你是怎么解决的

**Comment by ImPigerla** [comment]
`this.wangEditor.customConfig.onchange = (html) => {
                    this.isChange = true;     // 增加多个状态标识
                    this.$emit('input', html)
                }
`

然后用在在watch里面判断

` watch: {
            'value' (newValue) {
                if (!this.isChange) {     // 如果是编辑引起的变化则跳过
                    this.wangEditor.txt.html(newValue)
                }
                this.isChange = false
            }
        },`

**Comment by iamziyue** [comment]
赞，好办法，我也在这个问题上纠结了好久，后来放弃watch了。editor只向父组件提交内容更改。

**Comment by zss1004504439** [comment]
能用
