### ISSUE TITLE
菜单栏中的引用问题及图片上传问题

### ISSUE THREAD

**Issue by ljc930611** [wangfupeng1988/wangEditor#836]
vue中使用wangEditor菜单栏中选中饮用后无法取消只有删掉引用的所有内容才能删除引用，这个是需要设置什么还是别的问题？另外文件上传能添加拖拽上传功能吗？

**Comment by wangfupeng1988** [comment]
> vue中使用wangEditor菜单栏中选中饮用后无法取消只有删掉引用的所有内容才能删除引用

我试着官网是可以的，按理说 vue 中也应该可以，你去试试你环境下，官网可以吗？

**Comment by wangfupeng1988** [comment]
> 另外文件上传能添加拖拽上传功能吗？

这个后面会支持，排到版本升级计划中，不会近期两个版本应该不会加，待排的升级功能还有点多，精力不太够。后面会加上。
