### ISSUE TITLE
如何获取文本框里的编辑好的内容？

### ISSUE THREAD

**Issue by Cjlyn** [wangfupeng1988/wangEditor#839]

**Comment by Cjlyn** [comment]
editor1.txt.text()只能显示在html页面显示的内容，在前端的编辑器里输入的内容如何获取呢？

**Comment by wangfupeng1988** [comment]
没明白啥意思。。。

不是用`editor1.txt.html()`吗？

**Comment by Cjlyn** [comment]
你好，我的意思是editor1.txt.html()输出的是html里默认的代码（<p>欢迎使用 wangEditor 富文本编辑器</p>），
当我在编辑器里输入自己的内容时，打印出来editor1.txt.html()显示的内容没有任何改变。。只显示 （<p>欢迎使用 wangEditor 富文本编辑器</p>）
如何获取自己在编辑器里输入的内容呢？

**Comment by Cjlyn** [comment]
@wangfupeng1988

**Comment by wangfupeng1988** [comment]
> 打印出来editor1.txt.html()显示的内容没有任何改变

估计是你的写法有问题，参考这里 https://www.kancloud.cn/wangfupeng/wangeditor3/335775

**Comment by wangfupeng1988** [comment]
或者，干脆你下载下来源码，按照文档说明运行 demo，然后在 demo 的页面，有获取源码的样例
