### ISSUE TITLE
IE8下上传图片无响应

### ISSUE THREAD

**Issue by beijishiqidu** [wangfupeng1988/wangEditor#84]
[demo.docx](https://github.com/wangfupeng1988/wangEditor/files/50594/demo.docx)

我在其他浏览器测试了上传图片没有问题，发现在ie上不能上传图片，怀疑是我本地代码的问题，特此写了这个demo进行测试，还是不行，定位思路如下：

1.定位看你的js源码，确认那个哪一行报错，在附件中的word中可以看到。

2.重新写个demo发现你有写一句必须把所有的js放到body之后否则可能会有问题的字样，因为调整了位置，还是不行，不报任何的js错误了。（把js放在body之前就报一个其他的错误）。

3.附件中的demo不知为何官网给的例子有点问题，在其他浏览器测试上传之后得到一个图片的路径返回作为ie8的返回数据，保证服务器不是因为ie8的问题返回了错误的数据。

结论如下：可能ie8的兼容性有点问题，麻烦帮忙看下，多谢。

**Comment by beijishiqidu** [comment]
![qq 20151203170321](https://cloud.githubusercontent.com/assets/14070935/11556126/d19144b6-99df-11e5-9278-4c4b9efbe926.jpg)

把ie8的调试打开之后，发现和我另外工程中的报错是一样的。

**Comment by wangfupeng1988** [comment]
上传图片的逻辑是这样的：
首先，要自己吧图片上传上去（非跨域推荐用plupload，跨域时wangEditor自带但是也是和编辑器分离的，当然也可以自己写一个上传组件）。
第二，图片上传上去之后，肯定有一个callback函数能收到消息。这个 callback 函数要接收刚刚上传上去的这个图片的url地址。
第三，然后，执行编辑器里面的一个command方法，将图片url地址插入到编辑器的div中，其实就是插入一个<img src="url">标签而已。（其实这一步和官网demo中的插入网路图片用的是一套逻辑）

我看你发的图片里面，标识的这个位置，和上传图片没有任何关系。

如果IE8上传图片有问题，你要确定：
1. 图片是否真的上传上去了，跟踪一下callback中返回的url是不是能真正的访问到这个图片；
2. 将得到的url，执行官网demo的插入网络图片，看有没有错误。

这样才能把bug定位清楚。

**Comment by beijishiqidu** [comment]
你看我我截图中的日志，打印出来服务器返回的路径就是这个url，用这个url插入网络图片可以展示，就是本地上传服务器就是没有返回值。
![qq 20151204092442](https://cloud.githubusercontent.com/assets/14070935/11579469/46d671ae-9a69-11e5-8372-520025eb6507.jpg)
![16](https://cloud.githubusercontent.com/assets/14070935/11579476/4f6f2d74-9a69-11e5-8825-b52e89345196.jpg)

**Comment by beijishiqidu** [comment]
说错了，不是服务器没有返回值，是服务器有返回值，我conselo.log()已经打印出来了，见上图，打印出出来的url通过插入网络图片的方式就是可以正常插入的，本地上传任意一张图片，服务器固定返回这个可以访问的url编辑器没有任何的反应，也没有报任何的错误，你在我上传的demo中应该能看得到。

今早上又折腾了一阵确认这个问题是客观存在的。

**Comment by beijishiqidu** [comment]
刚才又和同事进行了再一次的确认，最终确认这个位置报错，麻烦帮忙看下。
![qq 20151204111131](https://cloud.githubusercontent.com/assets/14070935/11580965/d1fc1e88-9a77-11e5-9659-aa1896835f6d.jpg)

**Comment by wangfupeng1988** [comment]
今晚看了看，我复现了你的问题，并且做出了调整。

IE7、8在使用plupload上传图片之后，插入图片的过程中确实有一个『参数无效』的错误，我目前还未找到解决原因（IE低版本各种奇葩你懂的）。不过我发现加一个try-catch可以避免这个问题，而且插入图片能够操作成功。
代码已经更新，可以去下载最新的js文件。

> 以上改动，我都已经在本地测试通过了，用的IE7、8的环境。

另外，在文档中也需要增加一个 try ... catch ... 语句，我已经维护到 http://www.kancloud.cn/wangfupeng/wangeditor/65748 中，在页面搜索`// 用 try catch 兼容IE低版本的异常情况`即可看到新增的内容。

> PS: 这次还调整了IE低版本的弹出框的样式（之前的边框有问题），可以一起下载更新。

OK，有问题继续再次反馈即可。

**Comment by beijishiqidu** [comment]
已经基本解决，偶尔也会发现无响应，概率很小，暂时不考虑，待后期继续跟踪，多谢福朋兄的辛勤付出。
