### ISSUE TITLE
修改高度问题

### ISSUE THREAD

**Issue by yxrh** [wangfupeng1988/wangEditor#840]
原文档对高度的设置是300px,怎么修改它的高度呀

**Comment by shadeofgod** [comment]
@yxrh 
https://github.com/wangfupeng1988/wangEditor/blob/master/src/js/editor/index.js#L70-L72

初始化的时候可以传入第二个参数来作为文字的容器，没传的话是固定的300高。

```html
<div id="div1"></div>
<div id="div2"></div>
```
```javascript
var E = window.wangEditor
var editor2 = new E('#div1', '#div2')
```
div1里只会有工具栏的东西，然后div2的样式可以自己写。

当然你也可以不用像上面这样，直接初始化后用jQuery直接修改容器的高度。
```javascript
$('#div1').css('height', 500)
```

不知道作者以后会不会把高度什么的加入到config的配置中。

**Comment by yxrh** [comment]
谢谢，已解决

**Comment by wangfupeng1988** [comment]
> 不知道作者以后会不会把高度什么的加入到config的配置中

高度不会加到配置中，建议自行配置
