### ISSUE TITLE
实现预览

### ISSUE THREAD

**Issue by Rossfen** [wangfupeng1988/wangEditor#842]
var editorText = document.getElementById('editor-text')；
editorText.contentEditable = false;
这样不能取消div可编辑，应该怎样取消编辑区域的可编编辑？

**Comment by shadeofgod** [comment]
最新版的话，
```javascript
$('.w-e-text').contentEditable = false
```

**Comment by Rossfen** [comment]
editor-text的div还是可以编辑的，而且直接把它的contentEditable = false；还是可以编辑

**Comment by shadeofgod** [comment]
editor-text是你自己加的id吧， 你要找到对应的编辑区域的DOM节点啊

**Comment by Rossfen** [comment]
谢谢啊，我知道了，框架内嵌有一个无名的div，它设置了contentEditable = false，要把最内层的div的可编辑性关掉才可以。

**Comment by souldjl** [comment]
这个问题和回答有关系吗 ？我看了好半天没看懂？Are You  kidding me？

**Comment by wangfupeng1988** [comment]
> 实现预览

自己添加一个按钮，获取编辑器的html，然后显示一个div覆盖到编辑区域，不就实现预览了？

另外，预览得自己实现，编辑器不会原生支持了。
