### ISSUE TITLE
图片上传失败，但是上传的文件夹里面有图片

### ISSUE THREAD

**Issue by gao1996916** [wangfupeng1988/wangEditor#843]
图片上传，提示图片上传失败，但是上传的文件夹里面有图片

**Comment by WuHongYan-WHY** [comment]
上传你是怎么做的？我的也失败  但是文件夹没有图片

**Comment by shandianlala** [comment]
图片上传本地成功，到页面提示失败，这种情况很有可能是返回的图片路径不正确，你可以仔细检查下返回的图片路径

**Comment by wangfupeng1988** [comment]
楼上正解，打开 debug 模式，看下控制台是否报错

**Comment by GloryCho** [comment]
大佬，解决了吗，可否把你的代码贴出来，让我借鉴一二

**Comment by shandianlala** [comment]
#前台页面：
欢迎使用 wang 富文本编辑器

<script> var E = window.wangEditor; var editor = new E('#editor') editor.customConfig.uploadImgServer = '${basePath }/ajax/upLoad'; // 或者 var editor = new E( document.getElementById('#editor') ) editor.create(); </script>
#后台java代码实现，使用的是springmvc：
@requestmapping("ajax/upLoad")
@responsebody
public Map<String,Object> upLoad(HttpServletRequest request, HttpServletResponse response) {
//创建一个通用的多部分解析器
CommonsMultipartResolver multipartResolver = new CommonsMultipartResolver(request.getSession().getServletContext());
Map<String,Object> map = new HashMap<String,Object>();
//判断 request 是否有文件上传,即多部分请求
if(multipartResolver.isMultipart(request)){
//转换成多部分request
MultipartHttpServletRequest multiRequest = (MultipartHttpServletRequest)request;
//取得request中的所有文件名
Iterator iter = multiRequest.getFileNames();
List data = new ArrayList();
while(iter.hasNext()){
//取得上传文件
MultipartFile file = multiRequest.getFile(iter.next());
if(file != null){
//取得当前上传文件的文件名称
String myFileName = file.getOriginalFilename();
//如果名称不为“”,说明该文件存在，否则说明该文件不存在
if(myFileName.trim() !=""){
System.out.println(myFileName);
//重命名上传后的文件名
String fileName = "/../upload/" + file.getOriginalFilename();
//定义上传路径
String appRoot = request.getSession().getServletContext().getRealPath("") + File.separator;
String path = appRoot + fileName;
File localFile = new File(path);
if(!localFile.exists()) {
localFile.mkdirs();
}
try {
file.transferTo(localFile);
data.add(fileName);
} catch (Exception e) {
e.printStackTrace();
map.put("errno", 1);
map.put("data", data);
return map;
}
}
}
}
map.put("data", data);
map.put("errno", 0);
}
return map;
}
=========================================================
注意：map.put("data", data);中data里的图片路径必须是正确的，在浏览器页面可以访问的到，不然即使图片上传到本地成功，页面里的富文本编辑器还是没有显示图片的。
附上我上传后处理的图片路径：img src="/../upload/Save-Rock-And-Roll.jpg" style="max-width:100%;"

**Comment by Liaozhenting** [comment]
我碰到了类似的情况，是跨域引起的问题。让后台的这个接口允许跨域就行了

**Comment by wangfupeng1988** [comment]
解决了就好！
