### ISSUE TITLE
是否需要提供destroy editor的方法，防止单页应用中频繁创建造成内存泄漏

### ISSUE THREAD

**Issue by sailai** [wangfupeng1988/wangEditor#845]

**Comment by wangfupeng1988** [comment]
通过`editor.id`可以获取每个编辑器的一个唯一的 id ，可以根据这个 id 判断是否要重新创建。

**Comment by yuantu** [comment]
这个感觉很重要，webpack的热更新会有bug，每次热加载，都会创建一个编辑器

**Comment by wangfupeng1988** [comment]
如果仅仅是解决webpack热更新的问题，那先自己写一个`destroy`方法吧，即把编辑器创建出来的DOM全部remove掉即可。
