### ISSUE TITLE
获取到的内容有h2，h1相互包含的情况

### ISSUE THREAD

**Issue by chen-yin** [wangfupeng1988/wangEditor#846]
写两行文字，全部设置为h2，再将第一行的文字设置为h1。获取到的是：`<h2><h1>测试1</h1>测试2</h2>`

**Comment by wangfupeng1988** [comment]
感谢反馈，我之前就关注到这个问题了，已经记录下来，近期升级时重点修改该问题。请及时关注新版升级动态。

**Comment by wangfupeng1988** [comment]
修改了。

不过目前的修改方式，只能是阻止用户选中多行设置标题，只能选中一行设置标题，就不会有这个问题了。

我看了一下，如果想全面解决这个问题，还是挺复杂的，暂时先这样，后面我再继续优化。
