### ISSUE TITLE
带样式的文字复制到富文本，样式会被取消

### ISSUE THREAD

**Issue by XcXerxes** [wangfupeng1988/wangEditor#848]
网页上带颜色的文字，复制到富文本上，颜色会被取消，希望能解决一下这个BUG

**Comment by wangfupeng1988** [comment]
如果你的需求只是要带着颜色，可以后面修改加上。如果你希望复制过来的所有样式都带着，那就不会支持了。

样式不能全部复制过去，否则会有非常多的冗余代码，现在的策略是全面禁止复制样式。你可以先调研清楚这一点。
