### ISSUE TITLE
按照官网的图片配置，打开不能加载编辑器，提示如下

### ISSUE THREAD

**Issue by sunsetsite** [wangfupeng1988/wangEditor#849]
配置代码：
```
var article_editor = new wangEditor('#article');
article_editor.config.uploadImgUrl = '/upload';
article_editor.create();
```

网页端打开加载不出编辑器，cosole错误代码如下：
`Uncaught TypeError: Cannot set property 'uploadImgUrl' of undefined`

请问这个是什么情况

**Comment by wangfupeng1988** [comment]
没好好看文档 `article_editor.customConfig.uploadImgUrl = '/upload';`
