### ISSUE TITLE
火狐不兼容的问题

### ISSUE THREAD

**Issue by feixiangdechibang** [wangfupeng1988/wangEditor#852]
我从网上黏贴的文字和图片，复制到编辑器里面，发现谷歌浏览器图片可以显示出来，但是火狐浏览器却不能显现，有解决办法吗

**Comment by wangfupeng1988** [comment]
火狐一直都存在各种各样的兼容性问题，我已记录下来，近期高优处理该问题。请及时关注版本升级动态。

**Comment by wangfupeng1988** [comment]
我试了一下，没有发现你说的问题，你是通过什么场景下复现的，复制了什么样子的图片和文字？

请详细说明复现问题的场景

**Comment by feixiangdechibang** [comment]
我就是从网上找到的新闻，然后复制到编辑器里面，图片显示不出来，我在群里问过这个问题，也有人遇到过这个问题，但是上一个版本是没有这个问题，我下载下来用了一下，但是css跟js不能分开。我这边无法使用




发自网易邮箱大师
在2017年07月28日 23:40，王福朋 写道：

我试了一下，没有发现你说的问题，你是通过什么场景下复现的，复制了什么样子的图片和文字？

请详细说明复现问题的场景

**Comment by wangfupeng1988** [comment]
问题描述不清晰，暂时关闭问题

都复制了哪个网站的新闻？什么内容？—— 再者，复制其他网页内容，图片显示不出来，有时候是很正常的事儿。
