### ISSUE TITLE
为什么3版本的比2版本少了好多功能

### ISSUE THREAD

**Issue by hzmming** [wangfupeng1988/wangEditor#853]
看了3版本的文档介绍，什么设置尺寸、禁用/启用、销毁 等好多功能都没有，到源码里面看也没有相应的方法，
难道3版本是最近才出的简化版？？
求教了，只能先用2版本了

**Comment by hzmming** [comment]
比如我想禁用编辑框，发现，，竟然3版本没有接口。。
可是2版本明明有嘛

真的不懂了
最后我直接用简单粗暴的方法

`editor.$textElem.attr('contenteditable', false);`
拿到它的文本域，直接设置属性

**Comment by wangfupeng1988** [comment]
由于这是个人业余开源项目，我个人精力有限，只能先保证核心功能，其他的外围功能，首先满足用户自己能通过二次开发做到即可。
还请体谅！

**Comment by hzmming** [comment]
谢谢你能回复我，我也是第一次用你这编辑器，总想着不对劲，3版本怎么比2版本还少功能，就问了下。
那我先使用2版本的，愿你能做出更好的产品

**Comment by wangfupeng1988** [comment]
多谢反馈！
