### ISSUE TITLE
怎么上传图片

### ISSUE THREAD

**Issue by GloryCho** [wangfupeng1988/wangEditor#854]
每次上传都显示上传失败，可否贴一下大佬们的上传代码

**Comment by he426100** [comment]
`

  |   |   |  
-- | -- | -- | --

  | die(json_encode(array('errno' => 1, 'data' => array() )));
  | }
  | $data = array();
  | ​_CFG ['bgcolor'] );
  | foreach (​key => $vo) {
  | ​image->upload_image ( $vo);
  | if($img_name !== false){
  | ​img_name);
  | ​key] = ​img_name;
  | }
  | }
  | if(!empty($data)){
  | ksort($data);
  | echo json_encode(array('errno' => 0, 'data' => array_values($data) ));
  | }else{
  | echo json_encode(array('errno' => 1, 'data' => $image->error_msg() ));
  | }

`

**Comment by wangfupeng1988** [comment]
开启 debug 模式看看什么错误 https://www.kancloud.cn/wangfupeng/wangeditor3/335778

你光说失败，谁知道你哪里失败了
