### ISSUE TITLE
如何让3.0 支持textarea? 

### ISSUE THREAD

**Issue by freehzw** [wangfupeng1988/wangEditor#856]
原来用 2.0 在wordpress里，想用3.0，但又不支持textarea，改wordpress相关文件又有点麻烦，想问问作者能不能继续支持 textarea?

**Comment by wangfupeng1988** [comment]
你去搜一下已有的issue或者close掉的issue，之前有人问过了。
答案很简单，将 textarea隐藏，或者干脆用一个隐藏的`<input type="hidden">`，然后编辑器 onchange 的时候，将值随时都同步到隐藏的标签中，最后用form提交。
