### ISSUE TITLE
上传图片之后有办法在文本编辑器里面修改图片大小吗

### ISSUE THREAD

**Issue by chendonghai** [wangfupeng1988/wangEditor#858]
上传图片之后有办法在文本编辑器里面增加修改图片大小功能吗，因为有的人上传好大的图片会把整个页面弄大，所以想在文本编辑器里面再修改图片大小功能

**Comment by wangfupeng1988** [comment]
上传之后，图片会加一个`max-width:100%`的属性。如果想调整大小，可点击选中图片之后，再次点击菜单栏里的图片菜单，即可选择大小

**Comment by chendonghai** [comment]
能够自己自定义大小吗，还有那个文字色也是固定的，这些为什么不搞成自己可以自定义的啊，不要限制就这几种

**Comment by wangfupeng1988** [comment]
暂时不可以。

图片`max-width`有这几种模式，即可满足大部分用户的需求，而且开发成本很小。

文字大小也不能自定义了，这一点像 markdown 的设计方式看齐，都通过标签和样式统一大小，不要自定义大小。

**Comment by chendonghai** [comment]
以后会改吗

**Comment by chendonghai** [comment]
因为我们是内部系统用的，定制要高一点

**Comment by wangfupeng1988** [comment]
这个近期不会改。开源编辑器是一种面向网络用户的通用能力，不会为了某个用户的定制而去修改功能。
