### ISSUE TITLE
怎么样去除默认菜单 而把图片上传事件绑定在自己的上传按钮上呢？

### ISSUE THREAD

**Issue by changbb** [wangfupeng1988/wangEditor#860]
如题，我需要利用wangEditor进行编辑，但是不需要做文字处理，只要图片和基本的文字即可，图片上传事件我想要绑定在自己写的按钮上？怎么做呢?求大神？

**Comment by wangfupeng1988** [comment]
菜单配置和上传图片，看文档，都有说明。
