### ISSUE TITLE
怎么利用插件的保存选区事件插入自己想要的内容啊？

### ISSUE THREAD

**Issue by changbb** [wangfupeng1988/wangEditor#861]
如题，大致看了下插件原生js,每次编辑区内的焦点区都会保存  然后插入图片或文字的时候再恢复，请问我怎么得到这个保存的选区，然后插入自己的内容呢？

**Comment by wangfupeng1988** [comment]
`editor.selection.getRange()` 可以得到选中的 range，然后把它放在你的选区即可。想插入自己的内容，可以使用`editor.cmd.do('insertHTML', `<p>xxxx</p>`)`

**Comment by changbb** [comment]
非常感谢作者能够回复！我这样写的，但是链接却不跳转，html里已经生成标签
  editor.command(null,'insertHtml','<p><a href="https://www.baidu.com">百度！</a></p>')
我想在编辑区插入一个链接（自定义绑定的事件），单击却不跳转，请问是什么原因？

**Comment by changbb** [comment]
非常感谢作者能够回复！我这样写的，但是链接却不跳转，html里已经生成标签
`editor.command(null,'insertHtml','<p><a` href="https://www.baidu.com">百度！</a></p>')
我想在编辑区插入一个链接（自定义绑定的事件），单击却不跳转，请问是什么原因？

**Comment by changbb** [comment]
非常感谢作者的回复！我的本意是点击按钮（自定义）插入一个链接
`editor.command(null,'insertHtml','<p><a href="https://www.baidu.com">百度！</a></p>') `
但是单击，却不生效，HTML里面标签已经生成，请问什么原因？

**Comment by wangfupeng1988** [comment]
你用的是v2版本的命令，我说的是v3版本的

**Comment by liping1994** [comment]
请问你找到办法了吗？

**Comment by ahfychangbb** [comment]
editor.command(null,'insertHtml','<p><a href="https://www.baidu.com">百度！</a></p>')  这样子就行了

**Comment by liping1994** [comment]
您好， 首先感谢您的帮助。
我是用的这个方法， 但是这样插入之后，看不到光标了， 需要再次点击下，光标才能出现， 请问您知道怎么让光标出来吗？
我试了focus（）方法 ， 却没有用。

let st = `<table style="width:60%; margin-left: 20%;"><tr><th>指标名称</th>${th}</tr>${tr}</table>`;
this.editor.editor.command(e, 'insertHtml', `${title}${st}`);
this.editor.editor.$txt[0].focus();

![image](https://user-images.githubusercontent.com/23331306/34345643-8f3fa6f4-ea2b-11e7-9bf8-5953060cf1d0.png)

**Comment by ahfychangbb** [comment]
我也没整明白这个插件的自动获得光标的事件是什么！ 我的插入之后是有光标的！ 还有就是我用的是v2版本 可能跟最新版不一样！
如果还没光标的话可以  在插入字符串后插入一个<p></p>就有光标了  但是会多一个空白行！你要确定自己的版本 再找解决方法！

**Comment by ahfychangbb** [comment]
插入一个'<p></p>'空的p标签

**Comment by liping1994** [comment]
我解决了这个问题，蟹蟹您。
我一直没有测试不放到项目中插入会不会有光标， 刚刚测试了一下， 有光标。
到项目中没有光标的原因和react的状态有一定关系， 但是我不明白为什么。
之前是通过状态控制弹出层的显示和隐藏
 _self.setState({display: true})
现在改为很原生的操作dom 光标就出来了
document.getElementById('index-popup').style.display = 'block';
再次感谢

**Comment by liping1994** [comment]
hi  你知道删除table的方法在哪吗？ 
我这里自定义插入一大块 东西包在div里面，在删除的时候，光标会跳到子元素的位置把子元素删掉，而div最后才可以删掉。
我想的办法是把那一大块东西放在iframe里面（iframe可以直接删掉），但是不方便的就是要把样式给他，在向后台存的时候也需要把iframe单独存起来。
所以我也想用删除table的方法， 直接把最外面的div删掉。

**Comment by liping1994** [comment]
还有一问题就是 我这里也插入了echarts的图表， echarts图表可以选择svg或者canvas两种方式渲染。
如果选择canvas 需要维护一个 div的id 和图表数据一一对应的map结构，在onchange的时候不断用数据重新渲染图表。
而svg则不用考虑onchange这些 但是听说svg性能不好。
你觉得从长远考虑 选哪个比较好呢？

**Comment by liping1994** [comment]
第一次尝试撤销
![image](https://user-images.githubusercontent.com/23331306/34379215-260e42a2-eb35-11e7-9f80-5c3b57036d68.png)
第二次尝试撤销
![image](https://user-images.githubusercontent.com/23331306/34379297-8b130728-eb35-11e7-859b-48b8e3db3f0d.png)
会出现错位的现象，所以我决定还是用canvas吧。 求解答第一个问题。

**Comment by ahfychangbb** [comment]
抱歉！这个插件我用的不是很熟悉 ，建议直接在issues里面提问题或者在群里问问 可能会有大神遇到过！

**Comment by liping1994** [comment]
找到一办法  大概是下面的流程  但是我感觉性能可能会不好，每次都没办法取舍， 纠结。
（1） 插入的时候插入一个有标记的div， 如他的class为 baibiao
![image](https://user-images.githubusercontent.com/23331306/34403476-679ff77a-ebe3-11e7-8097-b61e4207cdfd.png)
（2）监听编辑区域的onkeyup事件， 如果发现当前按的是退格键，并且该元素的父元素中存在class为baobiao的div， 对编辑区域的html进行替换。
![image](https://user-images.githubusercontent.com/23331306/34404379-30298cfc-ebe8-11e7-9d68-6121822282da.png)
这种方式和保存iframe的innerHTML的方式， 哪种方式更好？
