### ISSUE TITLE
设置文字颜色后如何清除

### ISSUE THREAD

**Issue by flyingzl** [wangfupeng1988/wangEditor#862]
比如通过工具设置好文字颜色后，我希望清楚文字颜色，如何做到？

同时，如何自定义文字颜色？ 看你代码里面颜色是hardcode的，应该是项目定制的

**Comment by wangfupeng1988** [comment]
这块近期不会修改，颜色就这些，绝大部分用户已经够用了，不会为了少部分用户的场景而做修改。

文字的清除，暂时也没有，选中文字，统一设置为黑色，就可以清除掉了。
