### ISSUE TITLE
换行后不自动撤销引用<blockquote>

### ISSUE THREAD

**Issue by yb3616** [wangfupeng1988/wangEditor#863]
正常情况下换行会自动撤销引用，但是如果有别的标签(如：下划线、删除线、斜体...)，换行后并不会自动撤销引用。

**Comment by wangfupeng1988** [comment]
> 正常情况下换行会自动撤销引用

不明白啥意思

**Comment by yb3616** [comment]
同时使用quotes和strikethrough(都是工具栏上的)，编辑完当前行，换行后，新行不会撤销这两个(quotes、strikethrough)。但是如果当前行只有quotes，换行后，新行会撤销它(quotes)。

**Comment by wangfupeng1988** [comment]
目前是这样的，quotes 和 strikethrough 的实现机制不一样，也存在一定的差异。

quotes 原则上只能应用于一段文字，而 strikethrough 可以换行之后继续生效。
