### ISSUE TITLE
wangEditor 没有 onblur 事件嘛？

### ISSUE THREAD

**Issue by youmingkuang** [wangfupeng1988/wangEditor#866]
对于一些业务上的需求有时一个页面中需要有多个富文本框，这些富文本中的内容是经常需要编辑的，但不需要单独的保存按钮。以减少保存的操作。这个事件能添加上吗？

**Comment by youmingkuang** [comment]
@wangfupeng1988 请问这功能能添加上去吗？

**Comment by wangfupeng1988** [comment]
`onblur`事件我之前调研过，不好加，可编辑的`<div>`监控不到 blur 事件。
针对你的问题，我给你一个方法，定时使用`editor.selection.getSelectionContainerElem()`检测选取的 elem，看看是否是在编辑器区域之内，如果不在其之内，则可认为是 blur
