### ISSUE TITLE
空格的问题

### ISSUE THREAD

**Issue by Liaozhenting** [wangfupeng1988/wangEditor#868]
在中文文本中有对齐问题。两个空格不会是空两个字，四个空格也不是空两个字。
归根结底是&nbsp:的问题。
希望能有个配置，选了之后保存空格为‘& e m s p ;‘就是一个空格对应一个中文字的宽度。这样就不会有中文空两个字对齐的问题了。

**Comment by wangfupeng1988** [comment]
这个`&nbsp;`并不是我生成的，而是你输入空格时，浏览器自己生成的，因此这里不是很好改呀。

**Comment by Liaozhenting** [comment]
我现在的策略是保存到数据库的时候用正则替换一下str.replace(/(&nbsp;| )/g,'&ensp;')

**Comment by wangfupeng1988** [comment]
你保存的时候替换没有问题，我在编辑过程中替换就很麻烦了。因为替换完了还要让光标定位准确，每个浏览器都有兼容性的问题。

**Comment by Liaozhenting** [comment]
用这个正则好一点`str.replace(/&nbsp; /g,'&ensp;')`
