### ISSUE TITLE
按钮绑定事件手动插入指定内容，回车后新插入的p标签会自带增加之前的事件，是什么情况？

### ISSUE THREAD

**Issue by changbb** [wangfupeng1988/wangEditor#869]
` editor.command(null,'insertHtml','<p onclick="showImgs()">百度！</p>'); `这样给光标处插入指定文字，按回车后，新生成的p元素也自带onclick事件，怎么破，插件自带的回车是生成新的p元素，没有事件的?求解！

**Comment by changbb** [comment]
代码是这样的
` editor.command(null,'insertHtml','<p onclick="showImgs()">百度！<br/></p>');`

**Comment by wangfupeng1988** [comment]
> 新生成的p元素也自带onclick事件，怎么破

你自己加了`onclick`，它能没有 click 事件吗？

> 插件自带的回车是生成新的p元素，没有事件的

是的
