### ISSUE TITLE
图书上传返回参数的问题

### ISSUE THREAD

**Issue by halower** [wangfupeng1988/wangEditor#87]
我目前使用asp.net webapi来接受跨域的图片，那么我返回参数
 //拼接最终结果 
    string result = "<iframe src=\"" + iframeSrc + "\"></iframe>";

    //返回
        response.Write(result);
这种肯定没法用了，那么是否可以直接返回OK（result ）？可行不

**Comment by wangfupeng1988** [comment]
这块文档中的代码写的很详细，成功和失败的返回格式，文档中都有。还有什么疑问吗？
http://www.kancloud.cn/wangfupeng/wangeditor/65757

-------

PS：我不知道你是否认真的看了文档，文档中根本没有`OK（result ）`这种格式的描述。
