### ISSUE TITLE
富文本框图片上传至服务器（事后删除）方案求教

### ISSUE THREAD

**Issue by hzmming** [wangfupeng1988/wangEditor#873]
图片若以base64编码，将得到很长一串字符串，所以我想采用 ”图片先上传至服务器，文本框再以url指向图片“的方式。但遇到了个**问题**，
”那就是图片何时删除？？因为图片的引用为wangEditor里的一个img标签，我要怎么妥善的监控文本域中的图片是否被删除，更何况文本框还有 撤销功能，只要不点保存，都可以还原

还有一个问题，那就是3版本的wangEditor**怎么销毁**。。。api文档没有，源码也没找着，会不会有**内存泄露**问题？？
求教了

**Comment by wangfupeng1988** [comment]
> 我要怎么妥善的监控文本域中的图片是否被删除

这个在后端去判断吧。编辑的时候图片都该上传就上传，撤销或者删除了也暂时不要删除图片。保存的时候，后端拿到内容中的所有图片，然后去对比之前保存的图片，如果用不到的就删除掉。这么做是最佳解决方案。

> 那就是3版本的wangEditor怎么销毁

首先，不要重复创建，通过`editor.id`可以拿到这个编辑器的 id ，可以判断不重复创建。其次，如果要销毁，把创建编辑器的 DOM 节点删除掉，然后将`editor=null`就搞定了。
