### ISSUE TITLE
图片调整大小能不能做成兼容浏览器的？

### ISSUE THREAD

**Issue by s952787097** [wangfupeng1988/wangEditor#874]
在火狐上可以调整图片的大小，但是在其他的浏览器上不可以调整大小

**Comment by wangfupeng1988** [comment]
点击图片之后，图片处于被选中状态，此时再点击菜单栏里面的“图片菜单”，即可调整图片大小。

**Comment by icepoint0** [comment]
@wangfupeng1988 只能33 66 100 的比例调整啊。

**Comment by s952787097** [comment]
@wangfupeng1988 可不可以吧固定的几个图片大小编程用滑块控制呢  这样的话1%到100%都能够用了

**Comment by wangfupeng1988** [comment]
暂时不会这样做，只支持三个比例的调整。因为，绝大部分编辑器用户，并不需要那么精细的调整图片大小，这三个尺寸的选择就已经足够满足 90% 的用户了。

**Comment by wangfupeng1988** [comment]
近两个版本，会对这块做一些用户体验上的处理，不过不会改变我上面说的方式
