### ISSUE TITLE
工具栏的图标鼠标悬浮的时候是否支持弹出自定义的提示文字？

### ISSUE THREAD

**Issue by mqhe2007** [wangfupeng1988/wangEditor#877]
翻看文档没有找到相关说明。

**Comment by wangfupeng1988** [comment]
目前已经不需要文字提示了，通过图表都能看明白什么意思，还需要文字提示吗？

**Comment by mqhe2007** [comment]
@wangfupeng1988 不单单是提示功能，可能是一些提示文字，比如我限制了图片大小，在哪告诉用户合适呢？

**Comment by wangfupeng1988** [comment]
> 比如我限制了图片大小，在哪告诉用户合适呢？

我很不赞同你的这种设计方式，我认为合理的方式应该是：加入80%的用户不会上传超过5m的图片，那你就限定图片大小是5m，这样80%的用户能成功上传并且不会收到任何提示，另外20%的用户，上传超过5m的图片失败的时候给出提示。

要尽量少的给用户提示信息，让用户无感知的去完成操作，尽量简单

**Comment by mqhe2007** [comment]
@wangfupeng1988 不好吧，我现在的应用合理的限制是500K以内，然而有一半用户上传的图片都会超出大小，这里能给出提示是最友好的。无感知的前提是无限制，加上限制必须要给用户明示才是友好的体验。

**Comment by wangfupeng1988** [comment]
对于你目前的这种情况，编辑器是暂时不支持了。
