### ISSUE TITLE
V3 版本的图片插入以后在谷歌浏览器下无法调整大小

### ISSUE THREAD

**Issue by icepoint0** [wangfupeng1988/wangEditor#878]
v2 版本统一页面多富文本，插入图片会到别的编辑器里去？另外怎么像textarea一样可以调整富文本大小

**Comment by wangfupeng1988** [comment]
问题标题与描述不符，请详细并具体描述你的问题，让我和大家都看懂才行。

**Comment by icepoint0** [comment]
@wangfupeng1988  问题1：.v3 版本中 选中图片可以在菜单栏编辑 但是无法在图片四周出现拖动块编辑。
问题2：v2版本的多编辑器插入图片事件编辑器a 插入的会到编辑器b中去（可以忽略此问题）
问题1 在火狐浏览器可以，但是在谷歌浏览器不行

**Comment by York-Liang** [comment]
希望快点解决谷歌浏览器的无法调整图片大小的问题

**Comment by wangfupeng1988** [comment]
> 问题1：v3 版本中 选中图片可以在菜单栏编辑 但是无法在图片四周出现拖动块编辑

暂时不会加这个拖拽修改尺寸的功能。因为：绝大部分编辑器的使用者，并不需要很精细的编辑图片的大小，30% 50% 100% 这几个尺寸的修改已经能满足大部分人使用了。

如果你对这个功能有迫切的需求，可以自己去开发一个。通过`editor.$textElem.find('img')`即可获取编辑区域的所有图片，然后就可以自定义操作了。

**Comment by York-Liang** [comment]
好的
