### ISSUE TITLE
关于异步上传图片的问题

### ISSUE THREAD

**Issue by xhj2015** [wangfupeng1988/wangEditor#88]
$(function () {
            var event;
            fileUpLoad();
            var $uploadContainer = $('#uploadContainer');
            var editor = $('#textarea1').wangEditor({
                //重要：传入 uploadImgComponent 参数，值为 $uploadContainer
                uploadImgComponent: $uploadContainer
            });
        });
        function fileUpLoad() {
            $("#btnFileUp").click(function (e) {
                if ($("#fileUpImage").val == "") {
                    $.messager.alert("提示", "请选择上传的图片", "info");
                    return;
                }
                event = e;
                $("#form1").ajaxSubmit({
                    type: "post",
                    url: "/Login/ImageUpLoad",
                    success: function (data) {
                        var severData = data.split(':');
                        if (severData[0] == "ok") {
                            $("#img").append("<img src='" + severData[1] + "' width='40px' height='40px' />");//追加到img标签可以成功
                            editor.command(event, 'insertHTML', '<img src="' + severData[1] + '"/>');//插入编辑器
                        }
                    }
                });
            })
                }
               
当我把上传功能应用到编辑器中的时候，之前的上传功能也不能用了，不知道是不是我的用法有错，还望版主帮我看看

**Comment by xhj2015** [comment]
<script type="text/javascript">
        $(function () {
            var event;
            fileUpLoad();
            var $uploadContainer = $('#uploadContainer');
            var editor = $('#textarea1').wangEditor({
                //重要：传入 uploadImgComponent 参数，值为 $uploadContainer
                uploadImgComponent: $uploadContainer
            });
        });
        function fileUpLoad() {
            $("#btnFileUp").click(function (e) {
                if ($("#fileUpImage").val == "") {
                    $.messager.alert("提示", "请选择上传的图片", "info");
                    return;
                }
                event = e;
                $("#form1").ajaxSubmit({
                    type: "post",
                    url: "/Login/ImageUpLoad",
                    success: function (data) {
                        var severData = data.split(':');
                        if (severData[0] == "ok") {
                            $("#img").append("<img src='" + severData[1] + "' width='40px' height='40px' />");//追加到img标签可以成功
                            editor.command(event, 'insertHTML', '<img src="' + severData[1] + '"/>');//插入编辑器
                        }
                    }
                });
            })
                }
               
    </script>

<div>
        @using (Ajax.BeginForm("AddUserInfo", "Login", new { }, new AjaxOptions() { HttpMethod = "post", OnSuccess = "afterAdd" }, new { id="form1", enctype = "multipart/form-data" }))
        {
           
                    
                        <textarea id="textarea1" style="width:400px;height:400px;"></textarea>
                 
        
            <div id="uploadContainer">
                <div><input type="file" name="fileUp" id="fileUpImage" /></div>
                <div><input type="submit" value="上传图片" id="btnFileUp" /></div>
                <div id="img"></div>
            </div>
        }

        

    </div>

**Comment by wangfupeng1988** [comment]
问题出在 `event`变量，问题出在你不熟悉js的上下文环境和作用域（这是关键，需要恶补）
你把第二行的`var event;` 挪到`function fileUpLoad() {`这一行的下面，试一下行不行。
