### ISSUE TITLE
字体图标冲突

### ISSUE THREAD

**Issue by TangGe1119** [wangfupeng1988/wangEditor#880]
当项目中引入了icomoon字体图标使用默认的“icomoon“作为字体名的时候，会与wangEditor中的icomoon字体冲突，导致加载wangEditor后，字体图标显示不正常。建议将wangEditor中的字体图标换一个字体名

**Comment by wangfupeng1988** [comment]
好，接受你的建议，下次发版就修改过来。请及时关注新版发布动态。

**Comment by wangfupeng1988** [comment]
v3.0.6 已经修复
