### ISSUE TITLE
默认上传图片最大为5M，但错误提示却说最大为5.24288M

### ISSUE THREAD

**Issue by hzmming** [wangfupeng1988/wangEditor#881]
看了下源代码，发现有处不一致
![image](https://user-images.githubusercontent.com/15829377/28746232-9849f02e-74ba-11e7-8ea3-1e3324fa407b.png)

![image](https://user-images.githubusercontent.com/15829377/28746242-ea574538-74ba-11e7-8bfd-351fb8999798.png)

转换时 变成了/1000/1000，和之前的*1024 * 1024不一致造成的
我直接把源代码改了，不知道这是不是个问题？

**Comment by hzmming** [comment]
顺便问下作者，要怎么禁用富文本框哈，3版本的
我自己试的土方法

`editor.$textElem.attr('contenteditable', false);`

**Comment by wangfupeng1988** [comment]
图片大小的限制，可以自行配置 https://www.kancloud.cn/wangfupeng/wangeditor3/335782

禁用编辑器，我下次发版会加上这个 API，不过事先方式会和你的实现方式一致。

**Comment by wangfupeng1988** [comment]
禁用浏览器没有做成 API，不过有文档说明 https://www.kancloud.cn/wangfupeng/wangeditor3/368562
