### ISSUE TITLE
全站https引入的非安全脚本

### ISSUE THREAD

**Issue by zhaorenjie110** [wangfupeng1988/wangEditor#883]
如果在https的网站上面引入wangeditor，会引入一个http协议的脚本http://apps.bdimg.com/libs/highlight.js/9.1.0/highlight.min.js。导致网站变为混合模式。错误如下：
![3tjph8cip3 7mz q_8k_gk](https://user-images.githubusercontent.com/9960574/28751433-f07212fc-7539-11e7-8777-c2c2f109447c.png)
我们的目前的解决方式是，修改源码，但是仍然希望wangEditor在源码里使用//apps.bdimg.com/libs/highlight.js/9.1.0/highlight.min.js代替http://apps.bdimg.com/libs/highlight.js/9.1.0/highlight.min.js。这样他会自适应https和http。感谢作者

**Comment by wangfupeng1988** [comment]
你用的是 v2 版本，升级 v3 之后 v2 版本就不再技术支持了。另外，v3 对插入代码做了简化，不再用`highlight.js`了。

如果你要做兼容，自己改一下，链接改成`//apps.bdimg.com/libs/highlight.js/9.1.0/highlight.min.js`

**Comment by zhaorenjie110** [comment]
好的，谢谢
