### ISSUE TITLE
编辑器中的表格不能进行黏贴操作

### ISSUE THREAD

**Issue by zerolidao** [wangfupeng1988/wangEditor#885]
编辑器插入表格后，无法在表格内使用粘贴快捷键，只能手动输入

**Comment by wangfupeng1988** [comment]
v2 的时候我记得是表格粘贴会有问题，v3 的时候我就沿用了，之前也没人提出。

尽然你现在提了，我就记下来，把这个问题再调研一下，如果可以修改，下次升级的时候给修复了。请及时关注新版发布动态。

**Comment by wangfupeng1988** [comment]
v3.0.6 已经可以了
