### ISSUE TITLE
textarea标签无法初始化编辑器，

### ISSUE THREAD

**Issue by Linus-gm** [wangfupeng1988/wangEditor#886]
可以以表单的方式提交编辑器的内容吗

**Comment by wangfupeng1988** [comment]
表单方式提交，很多人问过这个问题了，我也回答过很多次了。

大体意思是，在表单中弄一个的`<input type="hidden">`，然后编辑器的`onchange`事件的时候，实时把编辑器的内容同步到`<input type="hidden">`的`value`中，然后就可以表单提交了。
