### ISSUE TITLE
行高无效

### ISSUE THREAD

**Issue by yooRabbit** [wangfupeng1988/wangEditor#887]
选中两行设置行高无效
例：
`<p style="line-height: 2.5;">大三大撒多撒</p><p style="line-height: 3;">撒大声大</p><p><br></p>`
设置行高为1.0倍 无效
测试结果为：两段内容会生成两个P标签 同时选中无法修改行高 版本忘记了。。查了下issues 没人提

**Comment by wangfupeng1988** [comment]
你应该是用的 v2 版本，目前最新的是 v3 版本，v2 版本已经不再做升级了。

v3 版本把行高功能去掉了，编辑器内容的时候不能为不同`<p>`标签设置不同的行高，行高、字体等都统一用css来控制，和 markdown 看齐。
