### ISSUE TITLE
能否添加以下功能

### ISSUE THREAD

**Issue by chenweibo** [wangfupeng1988/wangEditor#888]
1，直接粘贴html 编辑器直接转换文字
2， 能从页面复制粘贴时候能把页面上粘贴的子的字体颜色大小这些各种样式以及HTML的格式什么保留下来。
 这两个功能很多富文本都有。 比如百度编辑器就有（但是百度UI太丑 又不维护 无奈放弃。）。 最近挺需要这个功能，比如对于那些不懂HTML 添加资料的人。他们能做到直接粘贴过来样式。不然有时候都需要程序员去给他数据库里面修改。

**Comment by wangfupeng1988** [comment]
这俩功能，暂时都不会支持，解释一下：

> 直接粘贴html 编辑器直接转换文字

富文本编辑器的用户，90%都不会写 html 代码，并且开放 html 粘贴是一件非常危险的事情，容易被注入代码。

> 能把页面上粘贴的子的字体颜色大小这些各种样式以及HTML的格式什么保留下来

v3 版本的编辑器，有一个很大的改进就是保证编辑内容的代码整体和统一性，因此去掉了字体和大小的功能，旨在让css 和标签来控制这些样式。如果如你所说，把粘贴的各个样式都开放出来，那就违背了这个原则，因为粘贴的代码中，什么标签都有。另外，如果把样式都带过来粘贴上，会造成很多冗余代码。
