### ISSUE TITLE
希望添加查看html的功能

### ISSUE THREAD

**Issue by York-Liang** [wangfupeng1988/wangEditor#889]
有时是需要直接上传写好的html的，或者需要调整一下部分的样式，感觉还是有必要加上

**Comment by York-Liang** [comment]
如何再加入查看源码是自动格式的样式，就跟好了 对于有需要的这方面的需求的来说，体验会更好

**Comment by wangfupeng1988** [comment]
可以自己去实现。文档里，获取内容和设置内容的 API 都有，就可以实现这个功能。

**Comment by York-Liang** [comment]
恩恩，我现在正在实现，在修改下样式就可以了，谢谢你的回复，同时希望看下谷歌浏览器图片不可以改变大小的问题，其他浏览器可以，github上也有人提了这个问题
