### ISSUE TITLE
请问编辑器中如何拿到上传的照片的

### ISSUE THREAD

**Issue by yixiaowei** [wangfupeng1988/wangEditor#89]
后台代码：（struts2中写在action）
String path = ServletActionContext.getServletContext().getRealPath("/images");
				System.out.println("path:"+path);
				String filePath = path+"\\"+wangEditor_uploadImgFileName;
				System.out.println("filePath:"+filePath);
		    	File file = new File(filePath);
		    	if (!file.getParentFile().exists())  
		    		file.getParentFile().mkdirs();
				//String fileName = "";// 文件名称
				FileUtils.copyFile(wangEditor_uploadImg, file);
				html = "<iframe src='toUploadPic#ok|http://localhost:8080/classSpacePlus/images/"+wangEditor_uploadImgFileName+"'></iframe>";
				return "success";

因为wangEditor_uploadImg_assist.jsp是放在web-inf下的，所以我用了'toUploadPic这个action的名字起访问来代替了demo中的jsp访问，但是上传的照片一直取不到编辑器中，希望版主给分析一下愿意，谢啦

**Comment by wangfupeng1988** [comment]
**跨域还是非跨域？没写清楚**，我猜测你这是跨域。（如果是非跨域你就自己去看文档吧，文档写的也很清楚）

非跨域上传后台代码说明，文档地址：http://www.kancloud.cn/wangfupeng/wangeditor/65757

文档中一个重点，无论是上传成功或者失败，最终返回的都是一个带有`iframe`的字符串：
```
string result = "<iframe src=\"" + iframeSrc + "\"></iframe>";
response.Write(result);
response.End();
```

你上面的代码中，那一句话体现了这一点？
