### ISSUE TITLE
无法调整编辑区域的大小（版本3）

### ISSUE THREAD

**Issue by zhangxu3486432** [wangfupeng1988/wangEditor#890]
作者你好，在使用中遇到了一点小问题，就是无法调整编辑区域的大小，我在qq群里面做了咨询，他们告诉我调整div的高度就好了，但是在3中这个并不能改变编辑区域的尺寸，实在不知道该怎么办了，所以才跑这来麻烦您...

**Comment by chenweibo** [comment]
css 这样写`.w-e-text-container{height: 500px!important;}`

**Comment by wangfupeng1988** [comment]
用这种方式试一试 https://www.kancloud.cn/wangfupeng/wangeditor3/335771

**Comment by zhangxu3486432** [comment]
但是还有一个问题就是无法设置高度的高度和设备的高度一直，只能手动调整！！！

**Comment by zerolidao** [comment]
希望可以手动拉伸改变编辑器的高度

**Comment by wangfupeng1988** [comment]
@zerolidao 

> 用这种方式试一试 https://www.kancloud.cn/wangfupeng/wangeditor3/335771

用这个，可以实现啊。还非得什么东西都让我给你写好了用现成的？

**Comment by TinyDevil** [comment]
这应该就是个小bug, 正如＠fly-koala所说，#editor.w-e-text-container决定了编辑器编辑框的高,  但源代码里面写死了300px, 所以无法通过指定#editor 来设定编辑框的高。
可以下载wangEditor.min.js 的源码，然后通过ctrl f 找"300px"，找到后将其修改为"height: 100%"，即可解决这个问题。
