### ISSUE TITLE
火狐下兼容有问题

### ISSUE THREAD

**Issue by chenweibo** [wangfupeng1988/wangEditor#892]
在编辑内容下发现。建了表格后选中表格后删除不了。 只能全选ctrl+a删除 这样前面编辑的就也要删了。
在谷歌下选中整个表格可以删除 。火狐下全选中表格删除不了

**Comment by chenweibo** [comment]
3.05 版本下

**Comment by wangfupeng1988** [comment]
光标定位表格中，然后点击菜单栏中的“表格”菜单，会出现操作和删除表格的面板

**Comment by tianjunguo** [comment]
> 光标定位表格中，然后点击菜单栏中的“表格”菜单，会出现操作和删除表格的面板

但是如果是回显回来的菜单栏中的“表格”菜单还是现实插入，没有删除操作

**Comment by tianjunguo** [comment]
> 光标定位表格中，然后点击菜单栏中的“表格”菜单，会出现操作和删除表格的面板
从word中复制过来的文本，文本中有表格，回显到编辑器里全选没法删除，全选菜单栏里的表格还是显示插入，没有删除操作

**Comment by zxh1307** [comment]
> > 光标定位表格中，然后点击菜单栏中的“表格”菜单，会出现操作和删除表格的面板
> > 从word中复制过来的文本，文本中有表格，回显到编辑器里全选没法删除，全选菜单栏里的表格还是显示插入，没有删除操作

请问有找到解决方案了吗?
