### ISSUE TITLE
关于wangeditor上传图片问题

### ISSUE THREAD

**Issue by HSdiana** [wangfupeng1988/wangEditor#893]
https://www.kancloud.cn/wangfupeng/wangeditor2/131049按照这个解决的，走到第三集就不对了

**Comment by wangfupeng1988** [comment]
这是 v2 的文档，你用的编辑器是 v2 还是 v3 ？

**Comment by HSdiana** [comment]
2的

**Comment by wangfupeng1988** [comment]
2 的现在不再技术支持了，升级 3 吧

**Comment by HSdiana** [comment]
。。。。。。。。。不要这个样子，我崩溃了
