### ISSUE TITLE
关于编辑器空格与换行的问题

### ISSUE THREAD

**Issue by pkjoebinbin** [wangfupeng1988/wangEditor#894]
感谢作者开发的编辑器。在使用过程中发现个问题。
1.编辑文字时，回车后想实现换行或者换多行，但操作时看了下结构是添加一个p标签，没有实现换行的效果。
2.键入空格时例如段落开头的空两格没有效果。

再次感谢作者。编辑器很实用

**Comment by wangfupeng1988** [comment]
第一，回车就是增加 p 标签，不是换行，也不会修改。
第二，这里可以考虑使用 tab 键，空格还是英文的空格。
