### ISSUE TITLE
点击图片打开编辑菜单

### ISSUE THREAD

**Issue by Wolferring** [wangfupeng1988/wangEditor#895]
目前是在选中图片之后，再点菜单栏的图片按钮，弹出编辑菜单，想要点击图片[直接]弹出，请问应该怎么处理呢

**Comment by wangfupeng1988** [comment]
> 想要点击图片之间弹出，请问应该怎么处理呢

是“直接”弹出吧？

你这是一个好建议，我正愁着如何去提示用户编辑图片呢，近期两个版本加上该功能。请关注新版本发布动态。

**Comment by Wolferring** [comment]
是的，而且是3.0版本是不支持插件开发了么，wangEditor.plugin直接没有了，也没看到对应的文档说明，想写个插件，在点击图片时弹出编辑。

**Comment by Wolferring** [comment]
所以我目前只能尝试改源码中的/text/index.js 中的_imgHandle

**Comment by Wolferring** [comment]
还有一个关于图片的问题，点击图片后会加上一个w-e-selected的class，然后编辑器失去焦点并不会移除这个class，然后我保存的内容里面就带上这个class了。

**Comment by Wolferring** [comment]
然后还有个问题。。你的www.wangeditor.com挂了。。全国都ping不通

**Comment by wangfupeng1988** [comment]
不再支持插件了
