### ISSUE TITLE
插入图片菜单怎么去掉弹出层，而是直接调取选中文件呢？

### ISSUE THREAD

**Issue by changbb** [wangfupeng1988/wangEditor#897]
如题，项目中用不到选择网络还是本地 想要实现的是点击插入图片按钮直接弹出选择图片的弹出层。，请问应该怎么做呢？

**Comment by wangfupeng1988** [comment]
这个暂时不支持。要做成这种可配置的，成本挺高的，而且这种场景用户也没有那么多。因此综合来考虑，就先保持原样。

**Comment by offeeyang** [comment]
editor.customConfig.linkImgCallback 可以自定义点击图片按钮后的事件，我是调出自己的图库对话框让用户选，但还是会弹出editor自己的那个超链接对话框。所以最后只要隐藏图片按钮，使用自己自定义的按钮，放在菜单栏旁边。

**Comment by elvisyang2016** [comment]
在图片按钮上额外绑定一个点击事件，这个事件延迟触发一个点击操作，具体如下：
document.querySelector('.w-e-icon-image').onclick = function() {
            setTimeout(function() {
                document.querySelector('.w-e-up-btn').click()
            }, 0)
        }
然后修改一下样式，将editor弹出的对话框，设一个css隐藏掉就可以了：
.w-e-panel-container {
      display: none;
}

**Comment by zhao-ping** [comment]
请问下，自定义上传，图片上传完毕后怎样插入进去的呢？ @offeeyang 
有没有暴露出来的插入图片的方法呢？我看到源码里有insertLInkImage，这个方法怎么能在外部使用呢？ @wangfupeng1988

**Comment by dlyt** [comment]
> 在图片按钮上额外绑定一个点击事件，这个事件延迟触发一个点击操作，具体如下：
> document.querySelector('.w-e-icon-image').onclick = function() {
> setTimeout(function() {
> document.querySelector('.w-e-up-btn').click()
> }, 0)
> }
> 然后修改一下样式，将editor弹出的对话框，设一个css隐藏掉就可以了：
> .w-e-panel-container {
> display: none;
> }

这样有个问题会导致所有的弹层都不显示的了，比如链接等功能都不能用了
