### ISSUE TITLE
文字可选颜色太少了

### ISSUE THREAD

**Issue by linyuzhao** [wangfupeng1988/wangEditor#898]
文字可选颜色太少了

**Comment by chenweibo** [comment]
确实 希望多点颜色今天编辑来问 颜色选的太少了。（以前用的是百度颜色很多还能写色值） 希望作者尽快升级啊

**Comment by chenweibo** [comment]
@wangfupeng1988

**Comment by wangfupeng1988** [comment]
你们都想要哪些颜色？把颜色值发出来

**Comment by linyuzhao** [comment]
能不能通过hex值直接设定颜色?

**Comment by wangfupeng1988** [comment]
不会让用户输入颜色值的，只会让用户去选择。富文本编辑器的真正使用者，他们又不是技术人员，懂得设置颜色值？

如果说颜色值较少，那就把想要的颜色值告诉我，我升版时候加上。

**Comment by elover** [comment]
这块的颜色可以抽成一个自定义的配置吗？颜色的确太少了，每次加个颜色也依赖发版，不太友好

**Comment by wangfupeng1988** [comment]
想要加颜色的，你们把需要的颜色列一下。

如果列不出来，那就是现在还没有需求，为何要多加一个配置项呢？

**Comment by IWANABETHATGUY** [comment]
还可以多提供一个可配置的api，里面给一个数组，自己设置想要的颜色，这样就可以满足所有开发者的需要，毕竟每个人给出的都不一样，还不如让他们自己设置。。

**Comment by wangfupeng1988** [comment]
想要加颜色的，你们把需要的颜色列一下。

如果列不出来，那就是现在还没有需求，为何要多加一个配置项呢？

**Comment by wizawu** [comment]
> 不会让用户输入颜色值的，只会让用户去选择。富文本编辑器的真正使用者，他们又不是技术人员，懂得设置颜色值？

不是这样的，很多公司、品牌都有自己专用的颜色（例如美团的`#2bb8aa`），如果插图（Logo、背景图）都是这样颜色，但是调不出这个颜色的字，多难受。

所以我还是希望能有自定义的颜色。另外我是刚发现您这个项目，感觉做的很好，谢谢您无私的贡献。

**Comment by dhshen** [comment]
'#000','#666','#333','#999','#ff0000','#00ff00','#0000ff','#ffffff','#13227a','#f9963b','#f4ea2a',
求最起码支持红绿蓝，特别是红色，标记重点的需求很大，而目前编辑器的红色太老了，另外几种常见的灰度颜色'#333','#666','#999'也可以支持一下，以表达不同的重要性

**Comment by wangfupeng1988** [comment]
https://www.kancloud.cn/wangfupeng/wangeditor3/455793

**Comment by dhshen** [comment]
哦，之前看的就是这个页面，然后使用editor.customConfig.colors去设置颜色，结果没生效，刚看了一下自己用的版本是3.0.12，而这个功能是3.0.14中才支持的，如果在文档里注释一下版本就更好了，谢谢大佬

**Comment by ponymym** [comment]
为什么颜色不做成颜色选择器？每次想要新的其它颜色，就要更新代码吗？太不方便了。

**Comment by JinChunCheng123** [comment]
> 不会让用户输入颜色值的，只会让用户去选择。富文本编辑器的真正使用者，他们又不是技术人员，懂得设置颜色值？
> 
> 如果说颜色值较少，那就把想要的颜色值告诉我，我升版时候加上。

此言差矣，运营同学根本不知道颜色块对应的具体色值，相反他们只会从UI那里拿色值，而不是颜色块选择
