### ISSUE TITLE
希望能提供v3版本中的七牛上传demo

### ISSUE THREAD

**Issue by ChiakiYu** [wangfupeng1988/wangEditor#899]
项目中一直在使用七牛上传图片，之前使用v2，因为有demo，很轻松就实现了。
但是v2在使用中发现了好几个问题，也找到对应问题的issue，作者大大都提示升级到v3，但是v3并没有七牛上传相关的文档，我又是个前端小白，没有文档，自己无法集成，希望能有相关的文档，谢谢了。

目前项目无法升级到v3的原因如下：
1. 项目依旧在使用form提交表单，虽然使用了jquery.form.js进行异步提交表单，但是依旧需要textarea/input
2. 七牛上传因没有文档无法集成到v3（我是个后端。。。。）

**Comment by wangfupeng1988** [comment]
> 项目依旧在使用form提交表单

v3 使用 form 提交是有解决方案的，去 close 的 issue 中搜一下，我近期就回复过

> 七牛上传因没有文档无法集成到v3

文档 https://www.kancloud.cn/wangfupeng/wangeditor3/335782 中，使用这个配置即可

```js
editor.customConfig.customUploadImg = function (files, insert) {
    // files 是 input 中选中的文件列表
    // insert 是获取图片 url 后，插入到编辑器的方法

    // 上传代码返回结果之后，将图片插入到编辑器中
    insert(imgUrl)
}
```
你既然在 v2 中使用过七牛，那肯定也可以移植过来用。自己去试试，不可能每种场景我都指望作者提供示例呀，有支持的 API 自己就可以去干了

**Comment by ChiakiYu** [comment]
试了一上午没成功。
七牛的上传sdk是需要“触发选择文件的按钮的id”和“触发选择文件的按钮的父容器的id”的，v3里并没有暴露这俩id。

**Comment by RainKolwa** [comment]
@ChiakiYu 你可以参考[这个](http://jsfiddle.net/gh/get/jquery/1.9.1/icattlecoder/jsfiddle/tree/master/ajaxupload?ref=developer.qiniu.com)

**Comment by iamziyue** [comment]
在Vue项目中要用七牛存储，搜了下资料确实比较少，我自己摸索了一下，测试通过，大家可以参考。
```
const editor = new E(this.$refs['editor'])
// 各个区域服务器网址不太一样，可以找七牛的文档看
editor.customConfig.uploadImgServer = 'https://up-z2.qiniu.com/'
// 七牛接收的是这个input元素名称
editor.customConfig.uploadFileName = 'file'
// 这儿要从自己服务器获取token了，由于ajax是异步的，所有后续操作要放到回调里面，这点要注意
this.$ajax.get('/qiniu/token').then(({ data: json }) => {
  // code为0表示成功，这是我自己服务器api约定的
  if (json.code === 0) {
    editor.customConfig.uploadImgParams = { token: json.data }
    // 下面这个wangeditor文档中有，就是七牛服务器响应后的处理
    editor.customConfig.uploadImgHooks = {
      customInsert(insertImg, result, editor) {
        // Message是iview的提示，可以用alert代替的
        if (result.error) { this.$Message.error('上传失败：' + result.error) }
        else {
          // 这个是在七牛的bucket主机地址，我免费用户，没有采用自定义域名
          const host = 'https://ov6d5y404.bkt.clouddn.com/'
          // key就是文件名，不带后缀，但是能够正常访问
          const url = host + result.key
          insertImg(url)
        }
      }
    }
    editor.create()
    // 我没找到高度设置办法，手动指定高度了
    document.getElementsByClassName('w-e-text-container')[0].style.height = '200px'
  }
})

```

**Comment by vxhly** [comment]
![image](https://user-images.githubusercontent.com/17906558/37963389-ae674462-31f0-11e8-9c5e-141c6ee155b1.png)报了401了，请问什么原因

```bash

<template lang="html">

<div ref="editor">
</div>

</template>

<script>

import E from 'wangeditor'
export default {
  name: 'WangEditor',
  data () {
    return {
      editor: ''
    }
  },
  mounted: function () {
    // 获取七牛
    this.seteditor()
  },
  methods: {
    seteditor () {
      this.editor = new E(this.$refs.editor)
      this.editor.customConfig.debug = true
      // this.editor.customConfig.qiniu = true
      // // 这里用的是七牛华南的服务器
      this.editor.customConfig.uploadImgServer = 'https://up.qiniu.com/'
      // // 这个地方是禁止网络上传tab
      this.editor.customConfig.showLinkImg = false
      // // 这个地方是显示上传本地图片的tab
      this.editor.customConfig.uploadFileName = 'file'
      // // 这里显示的是用户标识token
      this.editor.customConfig.uploadImgParams = {
        token: 'yiRnWhsJNle1E-hvsnjZVq9cdNOCgisHWwLufnj-:uWsYVNXSHVgv7JaAjbWIrJNvfKU=:eyJzY29wZSI6InFpbml1IiwiZGVhZGxpbmUiOjE1MjIxNTEzMzd9'
      }

      this.editor.customConfig.uploadImgHooks = {
        // before: function  (xhr, editor, files)  {
        // //   // 在这里你可以写一些loading什么之类的
        //   console.log('before', xhr, editor, files)
        // },
        // success: function  (xhr, editor, result)  {
        // //   // 在这里你可以写一些上传成功的提示
        // },
        // fail: function  (xhr, editor, result)  {
        // //   // 这里可以写一些上传错误的提示
        // },
        // error: function   (xhr, editor)  {
        // //   // 图片上传出错时触发
        // // },
        // timeout: function  (xhr, editor)  {
        // //   // 图片上传超时
        // },
        customInsert: function (insertImg, result, editor) {
          // 这个hash就是我前面说的key值啦
          // var url = this.img_url + result.hash
          // insertImg(url)
          console.log('customInsert', insertImg, result, editor)
          // result 必须是一个 JSON 格式字符串！！！否则报错
        }
      }

      this.editor.create()
    }
  }
}

</script>
```

**Comment by ppttfish** [comment]
> 在Vue项目中要用七牛存储，搜了下资料确实比较少，我自己摸索了一下，测试通过，大家可以参考。
> 
> ```
> import E from 'wangeditor'
> 
> const editor = new E(this.$refs['editor'])
> // 各个区域服务器网址不太一样，可以找七牛的文档看
> editor.customConfig.uploadImgServer = 'https://up-z2.qiniu.com/'
> // 七牛接收的是这个input元素名称
> editor.customConfig.uploadFileName = 'file'
> 
> // 这儿要从自己服务器获取token了，由于ajax是异步的，所有后续操作要放到回调里面，这点要注意
> this.$ajax.get('/qiniu/token').then(({ data: json }) => {
>   // code为0表示成功，这是我自己服务器api约定的
>   if (json.code === 0) {
>     editor.customConfig.uploadImgParams = { token: json.data }
> 
>     // 下面这个wangeditor文档中有，就是七牛服务器响应后的处理
>     editor.customConfig.uploadImgHooks = {
>       customInsert(insertImg, result, editor) {
>         // Message是iview的提示，可以用alert代替的
>         if (result.error) { this.$Message.error('上传失败：' + result.error) }
>         else {
> 
>           // 这个是在七牛的bucket主机地址，我免费用户，没有采用自定义域名
>           const host = 'https://ov6d5y404.bkt.clouddn.com/'
>           // key就是文件名，不带后缀，但是能够正常访问
>           const url = host + result.key
>           insertImg(url)
>         }
>       }
>     }
> 
>     editor.create()
>     // 我没找到高度设置办法，手动指定高度了
>     document.getElementsByClassName('w-e-text-container')[0].style.height = '200px'
>   }
> })
> ```

确实有用，不过我写的过程中遇到403的问题{"error":"key doesn't match with scope"}，这个挺好解决，我在设置editor.customConfig.uploadImgParams的时候多设置了key值就ok了，具体可参照这里：http://www.chenxm.cc/article/101.html。Thanks♪(･ω･)ﾉ
