### ISSUE TITLE
支持上传HTML5 video功能吗

### ISSUE THREAD

**Issue by liniu** [wangfupeng1988/wangEditor#9]
简洁明了的编辑器，我喜欢，目前需要一个功能，支持上传插入HTML5 video ，和插入图片类似。会增加这个功能吗

**Comment by wangfupeng1988** [comment]
目前你是第一个提出这个需求的人，不过近期还没有加入这个功能的计划，先完善基本的功能。
不过我会记录到升级列表中，后期会考虑加上。

**Comment by wangfupeng1988** [comment]
插入视频的功能已经做了，更新到github上了。也可以通过http://www.wangeditor.com/wangEditor/demo.html查看演示
