### ISSUE TITLE
编辑器实现 只读/编辑 切换效果

### ISSUE THREAD

**Issue by vxiaoxaiowen** [wangfupeng1988/wangEditor#90]
请问 怎么实现编辑器在触发摸一个按钮的 点击事件后 实现 只读/编辑 的相互切换效果？

**Comment by wangfupeng1988** [comment]
其实要实现这种效果不一定非得是编辑器的功能。例如，建立如下html结构：
```html
<button id="btn1">切换</button>
<div id="div1">
    <!--放置要预览的内容-->
</div>
<div id="div2">
    <!--放置编辑器内容-->
</div>
```
然后，在点击`btn1`的时候，切换`div1`和`div2`的显示与隐藏。但是有一点需要注意：**每次显示预览内容的时候，都要重新获取编辑器的html内容，然后重新赋值到给`div1`**

如果还有疑问可以接着回复。

**Comment by vxiaoxaiowen** [comment]
您的 意思是其实是用预览层与编辑器大小一致 位置相当 然后 交替显示的啦？可以这样理解吗？

**Comment by wangfupeng1988** [comment]
对
