### ISSUE TITLE
用最新版本发现mini引入菜单图标都没了。

### ISSUE THREAD

**Issue by chenweibo** [wangfupeng1988/wangEditor#901]
用最新版本发现mini引入菜单图标都没了。原来用的是3.05直接引入了你的那个cdn下的文件。 3.06 好像少了好几K。 现在引入图标都没了。
`//unpkg.com/wangeditor/release/wangEditor.min.js`
你测试下最新版本的min.js 一用菜单的图标全部失效。要怎么解决。

**Comment by chenweibo** [comment]
官网的案例也这样了。是不是没打包好

**Comment by wangfupeng1988** [comment]
感谢反馈，我下午紧急看一下问题。

**Comment by wangfupeng1988** [comment]
v3.0.7 搞定了，CDN 可能得过会儿生效
