### ISSUE TITLE
HI，可不可以移除控制台输出

### ISSUE THREAD

**Issue by slince** [wangfupeng1988/wangEditor#903]
![image](https://user-images.githubusercontent.com/3785826/29010590-f5d65660-7b5e-11e7-949d-8de2e8d3e2b0.png)
虽然能够理解作者推广wangeditor的意图，但从项目的角度考虑其实我们并不希望这种提示出现在控制台；最好还是能够去除吧

**Comment by wangfupeng1988** [comment]
升级 v3 版本，应该就没有了

**Comment by wangfupeng1988** [comment]
暂时不能升级的，就在 v2 版本的源码去掉吧。v2 的代码以后也不会升级了。
