### ISSUE TITLE
粘贴微信公众号文章内容，图片不显示

### ISSUE THREAD

**Issue by BruceLpc** [wangfupeng1988/wangEditor#906]
把微信公众号发的文章粘贴到编辑器中，有的图片不显示，猜测可能是防盗链，
解决方法：
让后台提供防盗链转换接口；
在前端绑定了onpaste事件，获取粘贴的所有图片路径，经过后台处理，返回后再重新赋值图片src，但有个问题 粘贴文章的样式全都没有了，源码是在哪边过滤掉了吗？

**Comment by wangfupeng1988** [comment]
> 粘贴图片

你说的这种方式使用起来非常复杂。光一个简单的图片上传，就有多少用户不会用、出问题，你可能是体会不到的。如果再加这么一个防盗链转换的接口，那估计大部分用户都会用错。因此暂时不会加。

> 样式过滤

我是不得已过滤样式的，如果不过滤样式，会产生非常多的冗余代码，输出的内容会非常混乱

**Comment by BruceLpc** [comment]
如果过滤掉样式，别人辛苦排版好的文章粘贴过来，样式没了，又得重新去排版，估计没几个人愿意这样做

**Comment by wangfupeng1988** [comment]
我可以把样式过滤关闭掉（用户自己通过配置来控制），但是你要调研清楚粘贴不过滤样式会导致代码冗余的后果再使用。

我记录下来了，放在近期版本的升级计划中，请关注新版升级动态。

**Comment by linyuzhao** [comment]
举手表示同样有这个需求~

**Comment by wangfupeng1988** [comment]
v3.0.8已经支持自定义配置是否过滤样式，看文档
