### ISSUE TITLE
删除键 backspace 没有作用

### ISSUE THREAD

**Issue by BruceLpc** [wangfupeng1988/wangEditor#908]
backspace删除没有反应， delete可以删除

**Comment by wangfupeng1988** [comment]
请说明那个系统哪个浏览器，以及官网能否复现这个问题。

有问题要说明白，以后不受理“一句话问题”

**Comment by Merryisly** [comment]
谷歌浏览器， 通过在窗口内open的方式把编辑器打开在页面里的，然后Back内容无效，只能del删除内容，back 删除没有反应，体验非常不好，
如果单独跳转过去编辑器页面的话，是OK的

**Comment by wangfupeng1988** [comment]
@Merryisly 这个我就没招了，我没对 back 按钮做任何特殊处理。直接使用编辑器和通过`window.open`打开页面使用编辑器，代码上没啥区别。
