### ISSUE TITLE
vue中使用报错

### ISSUE THREAD

**Issue by JakeLaoyu** [wangfupeng1988/wangEditor#909]
在vue组件使用时，浏览器控制台报下面错误

```
The given range isn't in document.
```

**Comment by wangfupeng1988** [comment]
看文档，运行源码中的 vue demo ，看是否也有这个问题？

**Comment by JakeLaoyu** [comment]
直接把 vue demo 中的代码copy过来的，也报这个错误

**Comment by wangfupeng1988** [comment]
不要 copy ，直接运行，看是否报错

**Comment by JakeLaoyu** [comment]
这回可以了，我看的是wangEditor2 使用文档的 demo了

**Comment by wangfupeng1988** [comment]
文档地址  https://www.kancloud.cn/wangfupeng/wangeditor3/335789
