### ISSUE TITLE
删除编辑器

### ISSUE THREAD

**Issue by Menc0** [wangfupeng1988/wangEditor#91]
是这样的，我在同一个地方初始化了两次编辑器会出现警告‘同一个地方不能初始化两次’，所以我就想把前面初始化的一个给删掉，所以问题就是如何删掉？

**Comment by wangfupeng1988** [comment]
`同一个地方不能初始化两次`的提示的原因是：你对同一个`<textarea>`执行了两次`.wangEditor()`方法。
那么现在我的疑问是：针对一个`<textarea>`执行一次`.wangEditor()`即可生成富文本编辑器，你干嘛要执行两次呢？这不是多此一举吗？
你把第二次执行去掉，不就可以正常运行了吗？

**Comment by RangerWolf** [comment]
实际上我也有类似的需求~ 当然有办法限制第二次不运行~ 但是程序写得就不够漂亮了。。。   
首先，是在bootstrap modal 显示出来之后再加载editor，如果一开始就editor.create() UI自动提示的文字有bug  
然后关闭modal并再次打开（会触发第二次create），这个时候就会有两个editor了~
