### ISSUE TITLE
请问3.0.7版本菜单栏标签名字提示如何设置

### ISSUE THREAD

**Issue by liubeihb** [wangfupeng1988/wangEditor#910]
请问3.0.7版本标签名字提示如何设置.
2.X版本里菜单栏当鼠标放到标签栏时会有提示. 
现在3.0.7里面没有提示了. 
请问是直接删除了这项功能呢. 还是需要进行配置?
我看3.0.7文档中又没有这块说明. 
能否给出个示例或API啊
感谢

**Comment by liubeihb** [comment]
![image](https://user-images.githubusercontent.com/8033610/29058845-1e582f50-7c45-11e7-895e-8db054e62e2e.png)

**Comment by liubeihb** [comment]
https://github.com/wangfupeng1988/wangEditor/issues/741
我看了这个回答. tooltips 不添加了?

**Comment by wangfupeng1988** [comment]
楼上正解。

现在每个菜单栏的语意性都很强，都能看得懂，没有必要再加提示。droplist 和 panel 形式的菜单，也都有文字提示。

**Comment by liubeihb** [comment]
我添加了这个插件.修改了你的源码.
发现了一个BUG. 你背景颜色方法与文字颜色方法搞反了.
下面第一图来源:
https://www.kancloud.cn/wangfupeng/wangeditor3/335777

![image](https://user-images.githubusercontent.com/8033610/29067155-2249e436-7c64-11e7-962b-f6f29e8ae661.png)

第二图来源:
https://github.com/wangfupeng1988/wangEditor/blob/master/release/wangEditor.js#L1601

![image](https://user-images.githubusercontent.com/8033610/29067231-79d66fda-7c64-11e7-8f61-5a5473d4fe67.png)

**Comment by wangfupeng1988** [comment]
额。。。真的，我也发现了。感谢反馈！
我下一个版本就修改过来，请关注新版升级动态。
