### ISSUE TITLE
icon能否添加几个字体

### ISSUE THREAD

**Issue by liubeihb** [wangfupeng1988/wangEditor#911]
历史记录: histroy   
保存: floppy-disk 
放大: enlarge2
缩小:  shrink2

或者能否告诉一下. 自己如何添加

**Comment by liubeihb** [comment]
解决了
使用 https://icomoon.io/ 重新生成了一个字体库.替换了你原有的字体库.

**Comment by wangfupeng1988** [comment]
正解
