### ISSUE TITLE
删除代码框后边内容会导致光标跳不出代码输入框无法继续输入内容

### ISSUE THREAD

**Issue by Muntime** [wangfupeng1988/wangEditor#913]
问题重现：插入代码abc 再输入正文content 
html重现：`<pre><code>abc</code></pre><p>content</p>`
此时用删除键删除content至代码abc中，此时光标会一直在代码编辑框`<pre><code>abc</code></pre>` 中无法跳出，无法换行输入正文，或者通过菜单栏/光标/键盘起行。不知是我输入逻辑有问题，还是怎么的，写内容时此输入场景很经常见。

建议：很喜欢wangEditor，写了一个wangEditor YII2框架的widget正在使用，但是我建议上传图片选择多图的时候，上传不要使用数组一起上传，用队列一个一个上传，再一个一个处理会更好一些，因为现在大多网站都是使用的webuploader改进而来，保持后端上传口一致的时候能更好的控制，要不就只有自己写事件。另uploadImgParams如何不自动拼接到url中。

版本：v3.0.7 
浏览器版本：Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36

**Comment by wangfupeng1988** [comment]
> 问题重现：插入代码abc 再输入正文content，html重现：`<pre><code>abc</code></pre><p>content</p>`

使用最新版，我没有复现。我这边的代码是`<pre><code>abc</code></pre><p>content</p>`

**Comment by wangfupeng1988** [comment]
上传图片的问题暂时不做修改，目前反馈你说的问题的用户，基本没有。因此，不会为了少数用户去修改当前的逻辑。
