### ISSUE TITLE
为什么我的laravel加入不了wangEditor呢？

### ISSUE THREAD

**Issue by osramywj** [wangfupeng1988/wangEditor#914]
显示错误

![_20170810090505](https://user-images.githubusercontent.com/26902133/29150146-2a36f1b4-7dab-11e7-8983-ddb150dc8d9a.png)

**Comment by wangfupeng1988** [comment]
编辑器是一个前端的脚本，和 laravel 没关系。你这个错误比较低级，去好好看看文档吧
