### ISSUE TITLE
是否支持动态修改内容样式?

### ISSUE THREAD

**Issue by liubeihb** [wangfupeng1988/wangEditor#916]
像这个网站: http://bj.96weixin.com/ 右边悬挂一个动态样式. 然后修改内容的样式?
v3.0.7是否支持这类操作啊?

**Comment by wangfupeng1988** [comment]
暂不支持。

该编辑器是一个比较简洁纯粹的编辑器，不支持你说的这种复杂的操作，个人开源项目，业余精力有限，做不了那么多。
