### ISSUE TITLE
在软件应用(360)中复制一段介绍文本，粘贴时出现自定义代码。

### ISSUE THREAD

**Issue by wenlisu** [wangfupeng1988/wangEditor#918]
在软件应用(360)中复制一段软件介绍文本，粘贴到wangEditor时出现自定义代码+介绍文本情况，但是粘贴到word文档或者其他电脑自带的文本编译器没出现代码。
粘贴出现情况如图所示。
![](https://ws2.sinaimg.cn/large/006tKfTcgy1fiep4uwknhj30ht0pmk2q.jpg)

**Comment by wangfupeng1988** [comment]
> 软件应用(360)

什么意思？我该如何复现这个问题？什么浏览器？

**Comment by wenlisu** [comment]
不好意思，我的疏忽，补充问题截图
> 在`360手机助手`里找一款软件，复制它的应用介绍。

![](https://ws3.sinaimg.cn/large/006tKfTcgy1fifl6nl3smj30qj0h6q5f.jpg)
![](https://ws3.sinaimg.cn/large/006tKfTcgy1fifles9uwoj30rk0flgm8.jpg)
> 测试环境

![](https://ws2.sinaimg.cn/large/006tKfTcgy1fiflibbs5fj30o10jmq3w.jpg)
![](https://ws3.sinaimg.cn/large/006tKfTcgy1fifliibbngj30lx0eaq2x.jpg)

**Comment by wangfupeng1988** [comment]
那这说明你复制出来的内容就是这些代码吧？

你把复制的内容粘贴到其他的编辑工具，会是什么样子？
