### ISSUE TITLE
不跨越不实用plupload上传图片后回调如何处理

### ISSUE THREAD

**Issue by legendweny** [wangfupeng1988/wangEditor#92]
不跨越不实用plupload上传图片后回调如何处理，后台图片上传后，返回url？然后在前端怎么处理，有案例吗.....

**Comment by wangfupeng1988** [comment]
其实，plupload只是一个我推荐的上传图片的工具而已。毕竟『术业有专攻』，人家专门搞这个的，做出来的东西会考虑的比我们自己重新做要多一些——让然，你如果不用，也没问题。

首先还是参照文档：http://www.kancloud.cn/wangfupeng/wangeditor/65748

**文档的第一步，要求你要自己自己用plupload创建一个上传图片的页面。**这一步你可以完全不用plupload，自己做，只要能传上去就行了。上传图片，你肯定需要以下的 html 代码：
```
<div id="uploadContainer">
    <input type="button" value="选择文件" id="btnBrowse"/>
    <input type="button" value="上传文件" id="btnUpload">
</div>
```

**第二步，要求你在现在的页面上使用`wangEditor`生成富文本编辑器。**具体如何做，这个看文档就可以了。

**第三步，将上传图片和wangEditor结合。**其实这个结合只需要注意以下内容：

重点1：在`wangEditor`方法中，传入第一步中的html元素，如下
```
var $uploadContainer = $('#uploadContainer');
var editor = $('#textarea1').wangEditor({
    //重要：传入 uploadImgComponent 参数，值为 $uploadContainer
    uploadImgComponent: $uploadContainer
});
```

重点2，在文件上传完成的 `callback` 中，将后台返回的 url，插入到编辑器中，
`editor.command(event, 'insertHTML', '<img src="' + value + '"/>');`

其他的，可参照文档阅读。文档中代码注释很详细。
再有不明白的，可指出那一点不明白，在这里回复。

**Comment by legendweny** [comment]
<div id="uploadContainer">
        <input type="file" value="选择文件" id="btnBrowse"/>
        <input type="button" value="上传文件"  id="btnUpload">
    </div>
文件选择后如何通过 btnUpload上传？ 用form表单？

**Comment by wangfupeng1988** [comment]
> 文件选择后如何通过 btnUpload上传？ 用form表单？

从你这句话的意思，我理解的是你还不会上传图片**（如果理解错了，请见谅）**，如果是这样的话，我觉得我上面回复写的那一大篇，你也不能够全理解了。
我之所推荐大家使用`plupload`这种插件，就是为了考虑到不会自己制作很成熟的上传图片的使用者。

至于点击`btnUpload`之后如何上传图片，方式有多种。可以考虑使用第三方插件；可以使用form；也可以使用html5提供的file API，看你的选择。
至于详细的使用方法，还得靠你去查询一些资料。毕竟使用`wangEditor`还是要有一定的基础。
