### ISSUE TITLE
在引入 3.0.7 版本时报错 the given range isn't in document

### ISSUE THREAD

**Issue by mygrows** [wangfupeng1988/wangEditor#921]
![wangeditor](https://user-images.githubusercontent.com/23335187/29240138-6e675602-7f91-11e7-9711-1082b0a24fc8.png)

**Comment by wangfupeng1988** [comment]
是不是还没有 DOM Ready ？

**Comment by mygrows** [comment]
@wangfupeng1988 DOM 应该是加载了， 我是在laravel-admin 中引入的，我刚刚引入 3.0.8 版本也是报同样的错误，可是我如果是引入 2.1.22 版本就没有问题，是不是少了 node_modules 模块的原因？前端不是很了解，望解答 :)

**Comment by wangfupeng1988** [comment]
跟 laravel 和 node_modules 都没有关系。这样吧，你先抛开 laravel 这个环境，用一个最简单的页面复现一个这个问题，然后我就能确定原因。最好是用一个静态的 html 页面复现这个问题。

**Comment by mygrows** [comment]
@wangfupeng1988  感谢回复，这个问题已经得到解决，是我自己引入时出错的问题，编辑器是没问题的，感谢

**Comment by wangfupeng1988** [comment]
OK

**Comment by alexli0707** [comment]
@mygrows 我在laravel-admin引入的时候也遇到同样问题,请问是如何解决的

**Comment by lxtac** [comment]
@alexli0707 It`s so easy,I think he could be into a wrong DOM id.

**Comment by yzfdjzwl** [comment]
@mygrows 请问是如何解决的，我发现同样一个问题，2.x版没有问题，但是3.x版就会出现这个问题。
