### ISSUE TITLE
设置标题的H无效, 代码保存到数据库好像格式会消失

### ISSUE THREAD

**Issue by Hao-Luo** [wangfupeng1988/wangEditor#922]
文字没有任何Style的时候，标题Style不能应用上去。
比如
H1不能应用在 abcde

但是可以应用在
`<p>abcde</p>`

已经在http://www.wangeditor.com/测试过，有同样的问题.你可以去source editor把p tag 去掉进行测试.

另外咨询下放代码在pre里面，保存到数据库后那个代码的换行没有保存，请问是怎么解决的

**Comment by wangfupeng1988** [comment]
> 你可以去source editor把p tag 去掉进行测试

我为何要去 source 去掉 p 标签？编辑器默认是不能编辑源码的，手动去掉 p 标签是合动机？

> 代码在pre里面，保存到数据库后那个代码的换行没有保存

你可以看看从前端拿到的数据有没有换行，如果前端有后端没有，那就是你处理的问题。我只能保证前端拿到源码有换行。

**Comment by Hao-Luo** [comment]
因为我有个编辑纯文字的功能，不过没有关系，我已经写了个代码自动加上去了。
后面那个问题是因为我用的是input,所以自动变成一行了。
谢谢解决.
