### ISSUE TITLE
是否能够开放该富文本编辑器的自定义功能？

### ISSUE THREAD

**Issue by Jer-X** [wangfupeng1988/wangEditor#924]
之前用的是2.0版本，并在上头新增了一些如插入名片之类的功能，现在想升级成3.0版本，但是目前还找到在3.0上支持自定义功能的方法。请问是否考虑开放相关的接口呢？

**Comment by wangfupeng1988** [comment]
暂时还不考虑。

如果自己想要做插件，我建议 fork 一份代码，然后自己去修改源码。v3 的源码环境，新增一个菜单非常简单，看源码结构就能明白。

有问题可以随时回复我。
