### ISSUE TITLE
ctrl+v带图片的内容，第一次粘贴图片可以正常显示，第二次粘贴和以后就只剩下不带图片的内容

### ISSUE THREAD

**Issue by xyz8772232** [wangfupeng1988/wangEditor#925]
![image](https://user-images.githubusercontent.com/7192860/29258399-e836895c-80eb-11e7-9b13-a976cfefb679.png)
原文链接：
https://mp.weixin.qq.com/s?src=3&timestamp=1502680740&ver=1&signature=8ymboW2EShgCmFhOPbhjW8OKf81t*bz70D3tWEkhXo2XKDEKIhgDoKgCvTgbZCvHZFmMTVG4AA4wLZzRbIU0zPNm6uDC2HptzwNa5BtY*XM3Nv3MHIJrx7hNcPiUtspNtPZ9d3otiUC0qp2yxdGzzKYoVEgtjqy0SRJGQCOh6NU=

**Comment by xyz8772232** [comment]
测试了下，感觉是如果前面有文字就无法ctrl+v粘贴图片，如果是刚初始化，没有编辑过，就可以ctrl+v图片

**Comment by wangfupeng1988** [comment]
这块和原文页面的图片防盗链有关系，复制外部的图片粘贴过来，粘贴不上，是很正常的事情

**Comment by wangfupeng1988** [comment]
我看有不少人提供这个问题了，我记录下来了。后面我调研一下，如何通过接口来处理防盗链的事情，然后升级版本加上这个功能。

请及时关注新版发布动态。

**Comment by xyz8772232** [comment]
这个感觉不是防盗链，我这边很容易复现。就是只要编辑区前面有内容，ctrl+v的内容里的图片就消失了。如果前面什么都没有就不会出问题。
比如，我在官网上的编辑器里，粘贴下面文章http://finance.sina.com.cn/stock/usstock/c/2017-08-14/doc-ifyixias0634571.shtml里的阴影内容：
![image](https://user-images.githubusercontent.com/7192860/29264334-363ee554-810f-11e7-83e1-b3be760b616c.png)
当编辑区有文字时，粘贴内容的图片消失了，而且浏览器也没有发请求：
![image](https://user-images.githubusercontent.com/7192860/29264367-63add568-810f-11e7-9a6b-f7129bfafb51.png)
无网络请求：
![image](https://user-images.githubusercontent.com/7192860/29264492-ea0491e2-810f-11e7-9557-96e5f511c8c1.png)


删除编辑区的文字后，同样的内容，可以粘贴上，浏览器也会图片发送请求：
![image](https://user-images.githubusercontent.com/7192860/29264451-ba25a290-810f-11e7-88d7-f3e8cfd60281.png)

有请求：
![image](https://user-images.githubusercontent.com/7192860/29264509-ffe63eb6-810f-11e7-9d51-66449d579b7f.png)
。
所以，应该不是防盗链问题，而是前面有文字的时候，onpaste,不处理图片。

我用的是macbook pro chrome。AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36

**Comment by xyz8772232** [comment]
![image](https://user-images.githubusercontent.com/7192860/29266341-04aa8a54-8117-11e7-854d-598072ba380d.png)应该是这个处理导致的，此时是p不是div

**Comment by wangfupeng1988** [comment]
> 应该是这个处理导致的，此时是p不是div

试一下这个配置  https://www.kancloud.cn/wangfupeng/wangeditor3/376122

**Comment by wangfupeng1988** [comment]
然后我也去优化一下这里，记录下来，近期优化并发布

**Comment by xyz8772232** [comment]
好的，辛苦~~~

**Comment by wangfupeng1988** [comment]
已解决，本周末发布。近期业余其他事情耽误了，因此慢了一些
