### ISSUE TITLE
上传 gif 图片到服务器后，查看 git 图片不动了

### ISSUE THREAD

**Issue by mygrows** [wangfupeng1988/wangEditor#926]
gif 图片是能上传成功的，可是通过网址访问 gif 图片就不动了，在编辑器中显示的gif 图片也是不动的，变成静态的图片了

**Comment by wangfupeng1988** [comment]
你自己起一个demo，或者官网，然后插入一个网络 gif 图片，我试着是可以的，你试一下。

至于你上传之后为何不行，你再查一下上传过程中的原因

**Comment by mygrows** [comment]
我是使用图片上传到服务器，而 官网demo 使用的是 base64 存图片，我这边就是使用了配置上传文件的名称 `editor.customConfig.uploadFileName = 'editorUploadImageName';` 然后通过这个名称拿到上传的图片，保存，没做处理，可就是 gif 图片不动了 :), 我在查查，谢谢 @wangfupeng1988

**Comment by wangfupeng1988** [comment]
> 官网demo 使用的是 base64 存图片

你不要用官网上传，用网络图片

**Comment by mygrows** [comment]
@wangfupeng1988 感谢回复，编辑器上传 gif 图片是没有问题的，是我这边用的图片扩展处理不支持 gif 图片的处理导致的，现在我单独对 gif 图片的上传定义了另外的处理逻辑就可以了，非常感谢
