### ISSUE TITLE
3.0如果在上传图片的时候想给img标签添加一个私有属性，该如何实现？

### ISSUE THREAD

**Issue by Alan201601** [wangfupeng1988/wangEditor#927]
项目中用到了3.0，但是没有办法直接给img标签设置私有属性的方法

**Comment by wangfupeng1988** [comment]
编辑器暂时不支持。

但是你要做，肯定是能实现的。后端保存数据的时候，处理一下内容——根据图片链接获取 img 标签，然后给手动加上属性

**Comment by Alan201601** [comment]
我看到2.0里面是可以的，
如：  editor.command(null, 'insertHtml', '<img class="project_desc_images" src="' + url + '" alt="" style="max-width:100%;" data-id="' + attachId + '"/>');
主要是后台在上传图片之后，需要返回一个id，我需要给这张图片绑定，等点击保存时候再传回去

**Comment by Alan201601** [comment]
我看到2.0里面有这样的情况，这样是符合我现在的需求的
 editor.command(null, 'insertHtml', '<img class="project_desc_images" src="' + url + '" alt="" style="max-width:100%;" data-id="' + attachId + '"/>');

**Comment by wangfupeng1988** [comment]
https://www.kancloud.cn/wangfupeng/wangeditor3/335782

```
editor.customConfig.customUploadImg = function (files, insert) {
    // files 是 input 中选中的文件列表
    // insert 是获取图片 url 后，插入到编辑器的方法

    // 上传代码返回结果之后，将图片插入到编辑器中
    // insert(imgUrl)

    editor.cmd.do('insertHtml', '<img  />')
}
```

试一下这种方式
