### ISSUE TITLE
wangEditor引入后出现组件区高度问题

### ISSUE THREAD

**Issue by fenis** [wangfupeng1988/wangEditor#93]
![20151222102356](https://cloud.githubusercontent.com/assets/9641123/11946595/21f9ccaa-a897-11e5-9833-3fea3a7e2014.jpg)

代码部分：
<div>
    <textarea name="" id="textarea1" style='height:200px;max-height:200px; width:100%;'></textarea>
</div>

<script>
    var editor = $('#textarea1').wangEditor({
        'menuConfig': [
            ['fontFamily','bold','setHead'],
            ['list','justify'],
            ['createLink','insertHr','undo']
        ]
    });
</script>

**Comment by wangfupeng1988** [comment]
我才你这是引用到项目中才出现的这个问题，如果是这样的话，估计是css冲突导致的，这样的话就得具体问题具体分析了。

你如果新建一个页面，做一个简单的demo，肯定不会出现这种问题的。

如果你找不到原因，你看能不能保存为一个静态网页，发出来我给你看看。
