### ISSUE TITLE
上传图片默认配置了示例代码中token和参数,该如何取消?向服务器上传图片显示上传失败如何解决?

### ISSUE THREAD

**Issue by beileixinqing** [wangfupeng1988/wangEditor#930]
editor.customConfig.uploadImgParams = {
    token: 'abcdef12345'   // 属性值会自动进行 encode ，此处无需 encode
}

**Comment by beileixinqing** [comment]
我直接让改对象为空,可以取消参数提交了,但是依然alert弹出了上传图片失败,但是接口是200,也正常返回数据了.

**Comment by wangfupeng1988** [comment]
> 上传图片默认配置了示例代码中token和参数

我下次发布注释掉，你先手动设置为空对象

> 依然alert弹出了上传图片失败,但是接口是200

看看 console 出来的错误信息

**Comment by beileixinqing** [comment]
console出来的返回信息 就是 图片地址，没有 任何报错，上传的接口配置没有问题，接口返回200，也可以正常返回上传的图片地址，但是只要一上传就提示上传失败，目前真的很棘手，之前2.多版本的时候，一样的接口一样的配置，可以正常上传。

**Comment by wangfupeng1988** [comment]
https://github.com/wangfupeng1988/wangEditor/blob/master/release/wangEditor.js#L3659  跟跟踪一下这个函数中，哪一行报错了，然后告诉我，我来看看原因

**Comment by beileixinqing** [comment]
您的代码配置都试过了,如果是base64格式的可以很轻松上传,但是以接口形式往服务器上传总会alert 上传失败,希望您可以尽快帮忙看一下,非常感谢!非常着急!

**Comment by wangfupeng1988** [comment]
> https://github.com/wangfupeng1988/wangEditor/blob/master/release/wangEditor.js#L3737 跟跟踪一下这里代码，哪一行报错了，然后告诉我，我来看看原因

你得告诉我上传失败的具体信息呀，光说“上传失败”四个字，我怎么帮你？

**Comment by beileixinqing** [comment]
只有这一个信息，alert图片上传失败，接口返回200，返回数据有上传的图片地址，console没有报错，用您的fail函数的response参数返回的也是上传的图片地址。

**Comment by wangfupeng1988** [comment]
没看文档——打开 debug 模式，就有详细错误信息了

**Comment by beileixinqing** [comment]
ntimeout
:
function ()
readyState
:
4
response
:
"http://x-test.oss-cn-shenzhen.aliyuncs.com/photo/597aa2c77533032890519f6e/20170815185836239.jpg"
responseText
:
"http://x-test.oss-cn-shenzhen.aliyuncs.com/photo/597aa2c77533032890519f6e/20170815185836239.jpg"
responseType
:
""
responseURL
:
"http://localhost:8080/upload_photo"
responseXML
:
null
status
:
200
statusText
:
"OK"
timeout
:
10000
upload
:
XMLHttpRequestUpload
withCredentials
:
false
__proto__
:
XMLHttpRequest
以上是返回的xhr数据
http://x-test.oss-cn-shenzhen.aliyuncs.com/photo/597aa2c77533032890519f6e/20170815185836239.jpg
以上是返回的result图片数据
string
以上是返回的图片数据的typeof,是一个字符串

您的源码中:
if ((typeof result === 'undefined' ? 'undefined' : _typeof(result)) !== 'object') {
                        try {
                            result = JSON.parse(result);
                        } catch (ex) {
                            // hook - fail
                            if (hooks.fail && typeof hooks.fail === 'function') {
                                hooks.fail(xhr, editor, result);
                            }

                            _this3._alert('上传图片失败', '上传图片返回结果错误，返回结果是: ' + result);
                            return;
                        }
                    }

您麻烦看一下会不会是判断的typeof为字符串所以显示了图片上传失败.谢谢

**Comment by wangfupeng1988** [comment]
你干脆，参见 https://github.com/wangfupeng1988/wangEditor#运行-demo  这里，运行 demo ，看一下 demo 的上传图片的示例吧。
