### ISSUE TITLE
Vue2.0怎么扩展一个两端对齐的菜单

### ISSUE THREAD

**Issue by Jijmin** [wangfupeng1988/wangEditor#933]

**Comment by wangfupeng1988** [comment]
不受理一句话问题

**Comment by Jijmin** [comment]
您好，我想问下我使用Vue2.0引入了您的富文本编辑器，但是想扩展一个类似您文档中扩展一个『缩进』菜单类似的功能，但是我不知道怎么在Vue2.0中进行扩展。
![6622dcf3-d630-4546-9319-28123155ca5a](https://user-images.githubusercontent.com/16509222/29272326-1a4f2bd8-8132-11e7-932b-3e578016414f.png)

**Comment by Jijmin** [comment]
我按照你写『缩进』菜单方式直接在vue中写，给p元素添加了，但是我按回车键，

**Comment by Jijmin** [comment]
好的，谢谢你了，我试试。

**Comment by wangfupeng1988** [comment]
关于修改源码的问题，可以随时给我提问

**Comment by Jijmin** [comment]
您好，我看了下您的源代码，我有一个地方不是很明白，`JustifyRight`这个命令字是有配置吗？

**Comment by Jijmin** [comment]
您好，我看了您的源代码，但是其中有个小疑问，`JustifyRight`这个命令字是有配置的吗？
![1502772454 1](https://user-images.githubusercontent.com/16509222/29302592-0b581d20-81b8-11e7-8014-a20ee94c0eb3.jpg)我在下面有模仿您写的做了一个两边对齐的操作
![1502772613 1](https://user-images.githubusercontent.com/16509222/29302621-5307b716-81b8-11e7-9266-34982c7e0e1a.jpg)但是我的`commandName: 'Justify'`这个命令字不能起作用。想问下这个是怎么进行配置的？万分感谢。

**Comment by wangfupeng1988** [comment]
不要再看 v2 的代码了，升级 v3 好久了

**Comment by Jijmin** [comment]
大神，可以更新一个这个两端对齐的菜单吗？
