### ISSUE TITLE
插入代码两行以上，回显到编辑器内，出现编辑器变没了。

### ISSUE THREAD

**Issue by lmyyyyyy** [wangfupeng1988/wangEditor#935]
我要修改文章，文章内带插入代码的，回显到编辑器内，两行以上就会发现编辑器没了，别的样式都正常回显

**Comment by wangfupeng1988** [comment]
官网可以复现吗？什么浏览器？

这些信息，提问是都要写上，要让我能复现问题

**Comment by lmyyyyyy** [comment]
什么浏览器都这样呀，其他的样式都能回显。
可能是我没有说明白，是存在了数据库中，再取出回显到编辑器里，就回出现这种问题。
我试了三个浏览器，应该不是浏览器的问题。

**Comment by wangfupeng1988** [comment]
> 再取出回显到编辑器里

把你取回到编辑器里面，要显示的源码贴出来，我看一下

**Comment by lmyyyyyy** [comment]
![image](https://user-images.githubusercontent.com/21278644/29317476-af72f33a-81fe-11e7-935f-149082b0a34a.png)
这是多行不好使的
![image](https://user-images.githubusercontent.com/21278644/29317523-d595f95e-81fe-11e7-9858-62dcd958a49c.png)
这是单行可以在编辑器里显示的。

**Comment by lmyyyyyy** [comment]
已解决，因为之前我在js中往编辑器内设值没反应，我给注释了，然后直接在div中插入，导致了我也不知道为什么的情况发生，现在好了
我学到了以后没用的js代码一定要删除，尽管它是注释的。
非常感谢大佬的帮助，谢谢

**Comment by wangfupeng1988** [comment]
OK
