### ISSUE TITLE
在vue引用 onchange生成文本有时候汉字显示不出来只显示键盘输入的英文字母

### ISSUE THREAD

**Issue by hwyyy** [wangfupeng1988/wangEditor#936]

**Comment by wangfupeng1988** [comment]
你下载源码，然后运行vue demo，看是否也会这样 

https://www.kancloud.cn/wangfupeng/wangeditor3/335789

**Comment by azraelim** [comment]
环境windows7 64 , vue 引入组件遇到了同样的问题，我把wangEditor封装到了一个自定义的weditor组件里，在使用输入法输入汉字时，生成的文本有时会与输入框不同步


![weditor](https://user-images.githubusercontent.com/21300286/29445150-a2066c84-8417-11e7-92c8-43c60ea8fd67.png)

临时的解决方式是监听键盘事件&每隔500毫秒对内容强制进行同步
`
let that = this;
`
`
document.onkeyup=function() {
         that.$emit('editorChange', editor.txt.html());    
 };
`
`
 setInterval(function () {
          that.$emit('editorChange', editor.txt.html());
  },500);
`

**Comment by iamziyue** [comment]
我这儿，输入过程中确实会出现字母，但是最后一步是汉字的。内容可以正常更新到父组件。
![qq](https://user-images.githubusercontent.com/9757064/29672516-12232f6e-891f-11e7-97d6-67ea54c71230.png)
子组件用的是`editor.customConfig.onchange = html => this.$emit('input', html)`更新到父页面的

**Comment by kelekexiao123** [comment]
在react中使用wangeditor时也会出现同样的问题

**Comment by krissss** [comment]
这个应该是所有js的问题，具体bug重现方式为：
打中文，在英文未敲空格键入的时候停顿几秒，之后敲空格键入，onchange里面的html一定最后是英文。

**Comment by wangfupeng1988** [comment]
> 打中文，在英文未敲空格键入的时候停顿几秒，之后敲空格键入，onchange里面的html一定最后是英文。
 
这个问题跟 React  vue 没关系，onchange 都会有的
