### ISSUE TITLE
关于直接粘贴图片在编辑区域时的问题

### ISSUE THREAD

**Issue by zhfin** [wangfupeng1988/wangEditor#938]
配置文件设置的是上传文件到服务器

直接粘贴时会触发upload  但是并未上传图片到服务器端

![image](https://user-images.githubusercontent.com/30734994/29351360-fde59234-8294-11e7-89f6-bd0bf6431f7c.png)

有没有办法实现粘贴图片自动上传服务器的功能

**Comment by wangfupeng1988** [comment]
周末排查一下

**Comment by wangfupeng1988** [comment]
我用 demo 实验着没啥问题。

你参见[这里](https://github.com/wangfupeng1988/wangEditor#运行-demo)运行 demo ，demo 跑起来之后访问 http://localhost:3000/demo/test-uploadimg.html 这个样例，试一下还有没有问题？
