### ISSUE TITLE
为什么字体会自己变成font-size: 0.8125em

### ISSUE THREAD

**Issue by devpuck** [wangfupeng1988/wangEditor#939]
hi，为什么使用的时候，部分字体的格式回自己变成font-size: 0.8125em？

**Comment by devpuck** [comment]
<p>测试测试测试测试测试测试测试<span style="font-size: 0.8125em;">测试测试测试测试测试测试测试<

**Comment by wangfupeng1988** [comment]
因此我在 v3 中去掉了字体大小的菜单。你现在还用的 v2 吧？

**Comment by devpuck** [comment]
我刚确认了下，我用的用的v3版本，从github上直接下的。这个问题并不是所有的字体都会变成font-size: 0.8125em 。只有在粘贴的时候，粘贴的字体会变成这个样子

**Comment by devpuck** [comment]
比如随便输入一些字符串，然后拷贝这些字符串，多拷贝几次，然后就出现这个问题了。完全用手工输入的话，就不会有这个问题

**Comment by devpuck** [comment]
我也不知道我i什么，我不是专业做前台的，刚强制设置成style="font-size:1em，问题就解决了。
