### ISSUE TITLE
 粘贴文本进入编辑区报错

### ISSUE THREAD

**Issue by hebe700** [wangfupeng1988/wangEditor#94]
![qq 20151222142013](https://cloud.githubusercontent.com/assets/12486535/11949169/493897fe-a8b7-11e5-8e0e-577c06145575.png)
在线演示示例，以及本地文件，只要复制粘贴文本进入编辑区，火狐浏览器firebug就会捕获一个错误。虽然这个错误并不影响实际使用，但觉得应该修复这个小问题。

**Comment by wangfupeng1988** [comment]
这不是`jquery`报错吗，不是`wangEditor.min.js`报错啊

**Comment by wangfupeng1988** [comment]
2.0发布了，你说的错误已经没有了。可去官网demo中验证一下。
