### ISSUE TITLE
我需要把图片上传到OSS，然后就自定义的上传，然后出现错误

### ISSUE THREAD

**Issue by hz91213** [wangfupeng1988/wangEditor#940]
![image](https://user-images.githubusercontent.com/29476419/29393941-bea28370-8339-11e7-972b-621d19916265.png)
这是代码，错误如下
![image](https://user-images.githubusercontent.com/29476419/29393963-d0814e96-8339-11e7-9a33-ca9188219c8a.png)
求助

**Comment by wangfupeng1988** [comment]
看提示，是 this 的问题，this 是啥？

**Comment by hz91213** [comment]
我用的vue，所以会用到this，我换个方法试试

**Comment by iamziyue** [comment]
https://github.com/wangfupeng1988/wangEditor/issues/899#issuecomment-324564529

**Comment by blackhilloldmonster** [comment]
因为是个闭包,所以这个this是有问题的

**Comment by im-zhangxi** [comment]
> ![image](https://user-images.githubusercontent.com/29476419/29393941-bea28370-8339-11e7-972b-621d19916265.png)
> 这是代码，错误如下
> ![image](https://user-images.githubusercontent.com/29476419/29393963-d0814e96-8339-11e7-9a33-ca9188219c8a.png)
> 求助

hi, 你能把直接前端上传图片到oss 的代码贴出来，让我参考下吗？ 万分感谢

**Comment by hz91213** [comment]
@im-zhangxi 我现在换了个编辑器了。至于上传到oss用的JavaScript客户端签名直传。
代码如下：
![QQ截图20190415120129](https://user-images.githubusercontent.com/29476419/56106953-3450c900-5f76-11e9-92db-1fa64d218468.png)
oss文档地址：https://help.aliyun.com/document_detail/31925.html?spm=5176.11065259.1996646101.searchclickresult.72ab5e05c1GlmS

**Comment by im-zhangxi** [comment]
能加下qq那   834688422？   万分感激。 上传图片到oss  我之前实现过，。只是不会集成到editor

**Comment by im-zhangxi** [comment]
> @im-zhangxi 我现在换了个编辑器了。至于上传到oss用的JavaScript客户端签名直传。
> 代码如下：
> ![QQ截图20190415120129](https://user-images.githubusercontent.com/29476419/56106953-3450c900-5f76-11e9-92db-1fa64d218468.png)
> oss文档地址：https://help.aliyun.com/document_detail/31925.html?spm=5176.11065259.1996646101.searchclickresult.72ab5e05c1GlmS

能加下qq那 834688422？ 万分感激。 上传图片到oss 我之前实现过，。只是不会集成到editor

**Comment by hz91213** [comment]
![image](https://user-images.githubusercontent.com/29476419/56109915-20609380-5f85-11e9-8064-22bce9a9d0a1.png)
@im-zhangxi 把oss事件写到这里面就可以了

**Comment by im-zhangxi** [comment]
> ![image](https://user-images.githubusercontent.com/29476419/56109915-20609380-5f85-11e9-8064-22bce9a9d0a1.png)
> @im-zhangxi 把oss事件写到这里面就可以了

嗯  成功后 需要
` editor.cmd.do('insertHtml', '<img src="' + url + '" style="width: 650px; max-width:100%;"/>')`
才可以。 目前已经解决了。万分感谢

**Comment by im-zhangxi** [comment]
> ![image](https://user-images.githubusercontent.com/29476419/56109915-20609380-5f85-11e9-8064-22bce9a9d0a1.png)
> @im-zhangxi 把oss事件写到这里面就可以了

嗯  成功后 需要
` editor.cmd.do('insertHtml', '<img src="' + url + '" style="width: 650px; max-width:100%;"/>')`
才可以。 目前已经解决了。万分感谢

**Comment by hz91213** [comment]
@im-zhangxi 客气
