### ISSUE TITLE
希望添加清除全部格式功能

### ISSUE THREAD

**Issue by bartdou** [wangfupeng1988/wangEditor#942]
有时候编辑很复杂的样式之后觉得太乱了，想推倒重来，希望添加清除全部格式功能。

**Comment by wangfupeng1988** [comment]
暂时不会加这个功能，因为你所说的场景，反馈的用户比较少。v3 本着尽量精简的原则，应用少的功能则不加。

如果自己需要，可以 fork 源码下来自己添加菜单，有疑问可以随时找我。

**Comment by TimeToBegin** [comment]
目前的项目也需求这个功能，忘能求解
