### ISSUE TITLE
传多个文件，PHP后台var_dump 只有一个文件。

### ISSUE THREAD

**Issue by cute001** [wangfupeng1988/wangEditor#943]
传多个文件，PHP后台var_dump `只有一个文件。设了多个文件可以同时上传，但只怎么传，都只看见一个文件。

**Comment by wangfupeng1988** [comment]
不会的，你可以下载源码，运行 demo 上传多个图片试试。

你监控下 http 请求

**Comment by krissss** [comment]
记得上传的uploadFileName 设置成数组形式：
editor.customConfig.uploadFileName = 'yourFileName[]'
