### ISSUE TITLE
360极速浏览器兼容性问题

### ISSUE THREAD

**Issue by Imagoodboy** [wangfupeng1988/wangEditor#946]
wangEditor版本：v3.0.8
内核版本号：50.0.2661.102
emoji表情无法加载
![test](https://user-images.githubusercontent.com/22674855/29507390-748f53b6-8682-11e7-8e16-3bd66adfd860.png)

**Comment by Imagoodboy** [comment]
@mablevi 我的是360极速浏览器，chrome内核。内核版本已经在开头注明，内核版本号：50.0.2661.102

**Comment by Yusoo** [comment]
和系统有关，换win10试试

**Comment by Imagoodboy** [comment]
@Yusoo 
![win10test](https://user-images.githubusercontent.com/22674855/29600799-9cd151c4-880a-11e7-8c38-ed5257c14292.png)
win10上表现有所增强。但似乎也不是完美显示

**Comment by wangfupeng1988** [comment]
emoji 的兼容性问题，我会在近期高优解决
