### ISSUE TITLE
富文本3.0.8版本中，当页面存在轮播图组件，轮播图切换到下一张时，会触发panel框自动隐藏

### ISSUE THREAD

**Issue by Resenel** [wangfupeng1988/wangEditor#948]
测试环境：

- 轮播图组件：Jquery.Shutter 

- 富文本编辑器：wangEditor 3.0.8

测试内容：

1. 当页面存在轮播图组件，轮播图切换到下一张时，会触发panel框自动隐藏。

**Comment by wangfupeng1988** [comment]
是不是触发了 body 的点击事件？

**Comment by Resenel** [comment]
这么说倒是提醒了我，应该是轮播图插件切换图片时触发了点击事件导致
