### ISSUE TITLE
新手，新增自定义表情但是一直提示emotions of undefined

### ISSUE THREAD

**Issue by majiang666** [wangfupeng1988/wangEditor#950]
一直提示 `Uncaught TypeError: Cannot set property 'emotions' of undefined`，是我哪里没有引用吗
`//配置表情包
	editor.config.emotions = {
    // 第二组，id叫做'weibo'
    'weibo': {
        title: '微博表情',  // 组名称
        data: 'https://api.weibo.com/2/emotions.json?source=1362404091'
    }`

**Comment by majiang666** [comment]
`$(function(){
	// wangeditor3:api地址 https://www.kancloud.cn/wangfupeng/wangeditor2/113961
	//初始化
	var E = window.wangEditor
    var editor = new E('#editor') 

    // 上传图片到服务器
	editor.customConfig.uploadImgServer = '/upload'  

	//配置表情包
	editor.config.emotions = {
    // 第二组，id叫做'weibo'
    'weibo': {
        title: '微博表情',  // 组名称
        data: 'https://api.weibo.com/2/emotions.json?source=1362404091'
    }
};





	editor.create();
});`

**Comment by wangfupeng1988** [comment]
你用的是 v3 版本，看的确是 v2 的文档
