### ISSUE TITLE
editor.cmd.do插入内容，IE有兼容性问题。

### ISSUE THREAD

**Issue by lhard66** [wangfupeng1988/wangEditor#951]
`editor.cmd.do('insertHTML', '<p>xxxx</p>')`
在IE浏览器11中，什么也插入不了。

**Comment by wangfupeng1988** [comment]
应该不会呀，你看下你那边 IE ，插入图片、链接、代码，都好使吗？

**Comment by HengistLee1** [comment]
我也遇到这个问题，请问楼主是怎么解决的？
