### ISSUE TITLE
没有字体大小的设置菜单？

### ISSUE THREAD

**Issue by huzhongchun** [wangfupeng1988/wangEditor#952]
初始化截图里面看上去有设置字体大小的信息，实例化之后却没有这个菜单？

**Comment by wangfupeng1988** [comment]
v3 不支持字体大小的设置了。应该使用标签和样式来控制字体大小，而不是使用 font-size

**Comment by huzhongchun** [comment]
你好，不明白为什么呢？标签来控制大小是有限无法实现定制，然后样式来控制字体大小，不也是设置font-size吗？ @wangfupeng1988

**Comment by wangfupeng1988** [comment]
该编辑器并不能实现无限定制

**Comment by huzhongchun** [comment]
好的 谢谢，再问你一个问题。现在使用的p包裹，但是当p包裹h等块级标签的时候，导出html实际输出到页面解析的时候就会有问题，因为文档规范p是不能包裹块级标签的，请问这个问题怎么解决呢？

**Comment by wangfupeng1988** [comment]
这个问题，我记得新版本解决了，你用的哪个版本？怎么复现这个问题？
