### ISSUE TITLE
菜单扩展功能

### ISSUE THREAD

**Issue by foooooouny** [wangfupeng1988/wangEditor#954]
看了wangEditor的文档，里面说支持了 createMenu 菜单扩展功能，但是在wangEditor3 中没有这项功能了，而且代码中也没有createMenu这个方法了。这个功能是移除了么？如果我想自主扩展菜单栏及相应功能的话，我该怎么做？

**Comment by wangfupeng1988** [comment]
v3 移除了。因为 v2 花费很大成本做出来，但是用的人并不多。因此，v3 干脆移除了，需要扩展菜单的，fork 代码自己修改。

文件在 src/menus 目录下，看一下其他菜单怎么写的。有问题随时找我

**Comment by foooooouny** [comment]
好的，谢谢
