### ISSUE TITLE
图片大小控制，能用进度条的形式展现吗？

### ISSUE THREAD

**Issue by foooooouny** [wangfupeng1988/wangEditor#956]
上传完毕图片之后，图片的大小控制目前是写死的三个值，这种控制能用进度条的形式展现么？

**Comment by foooooouny** [comment]
看了之前被close的pr，自定义大小还是有使用场景的，希望可以优化一下吧，感谢。

**Comment by wangfupeng1988** [comment]
根据反馈情况，自定义大小的场景肯定是有的，但是占比并不大，因此暂时不会支持
