### ISSUE TITLE
内容在编辑框上面，是什么情况？

### ISSUE THREAD

**Issue by Yusoo** [wangfupeng1988/wangEditor#957]
let editor = new WangEditor('#editor')
editor.create()
就这两行代码，生成的dom像下面这样
![qq 20170830093830](https://user-images.githubusercontent.com/10611107/29851559-4289fdb2-8d67-11e7-9925-dd2d1f5e11bd.png)

**Comment by wangfupeng1988** [comment]
这个不可能。你去参照源码中的 demo 做个试试
