### ISSUE TITLE
编辑器内容为空时，上传图片的图片无法显示，需要先编辑一些内容上传图片才可以正常显示

### ISSUE THREAD

**Issue by zhumeilu** [wangfupeng1988/wangEditor#961]
编辑器内容为空时，上传图片的图片无法显示，可以在console里面看到网络请求到到图片，在编辑器上输入一些文本之后，上传图片可以正常显示

**Comment by wangfupeng1988** [comment]
> 编辑器内容为空时

是什么都没有，还是内容是`<p><br></p>`
