### ISSUE TITLE
关于编辑的文本的回显问题

### ISSUE THREAD

**Issue by Syscrii** [wangfupeng1988/wangEditor#963]
我是通过 `.text.html()`插入的文本内容,想要回显编辑.但是发现一个问题,编辑框的滚动条失效了.
也就是说,当我的内容通过 `.text.html("<p>balablabla一大堆超长的文本</p>")` 重新设置内容后,滚动条会失效

**Comment by wangfupeng1988** [comment]
是`editor.txt.html('<p>123123123123</p><p>123123123123</p>')` 我试了一下，没啥问题

你确定是用的 v3 版本？
