### ISSUE TITLE
图片上传自动转动

### ISSUE THREAD

**Issue by FJHou** [wangfupeng1988/wangEditor#966]
别人给我两张照片，我上传到富文本自动转向了，我自己手机拍的照片上传没事。找了半天不知道哪里有问题。不知道有没有人遇到过同样问题。翻了30多页的issues没找到类似问题，所以才来提问。还有安卓浏览器里，上传图片的按钮只能生效一次是什么情况？？

**Comment by wangfupeng1988** [comment]
你看看电脑中会有这个问题吗？电脑中有的话，我来支持。

手机端，现在不支持

**Comment by FJHou** [comment]
就是在电脑上传的时候会发生转动，你可以试试这张图片
![143ad9d591a3bb532c3413cfbc4a33cc](https://user-images.githubusercontent.com/22517598/30356316-f1b63482-986a-11e7-8f20-3307f422e8c9.jpg)
这张也有问题
![53a5bd54c36fc19f5cf750a70b1e3a7d](https://user-images.githubusercontent.com/22517598/30356301-da21b03a-986a-11e7-8c32-9bfaad0afb6c.jpg)

**Comment by FJHou** [comment]
这两张在我桌面上显示都是正的，传到这里就转了

**Comment by wangfupeng1988** [comment]
这个问题我貌似无法解决，编辑器中是：你选择了什么图片，就给你上传什么图片，没有其他的处理。

你可以考虑通过后端或者显示的时候来处理吧
