### ISSUE TITLE
html2json

### ISSUE THREAD

**Issue by cmideal** [wangfupeng1988/wangEditor#967]
不支持作者有没有支持小程序的想法，应该对提升使用量有很大的作用，更实用

**Comment by wangfupeng1988** [comment]
暂时不支持移动端

**Comment by cmideal** [comment]
不是支持移动端，我的意思是，编辑富文本可以在 小程序端进行直接读取，转换为json小程序识别的模式

**Comment by wangfupeng1988** [comment]
哦 将 html 处理为 json 格式，对吧？

这个目前使用的人并不多，因此先自己实现吧。你可以拿到 html ，就可以将 html 处理为 json

**Comment by cmideal** [comment]
这个不是不多我觉得，小程序现在体量很大，作者可以看一下小程序的富文本，转换成那种，我觉得，这个对于wangeditor发展很有益处，因为现在，基本上很少有编辑器能实现，以ueditor这个为例也不行

**Comment by wangfupeng1988** [comment]
编辑器放在移动端会有很多问题的，此前我也做过一个移动版的 https://github.com/wangfupeng1988/wangEditor-mobile ，后来坑太多填不完，就弃疗了。

**Comment by cmideal** [comment]
我的意思不是放在移动端用，那个肯定会出现问题，我的意思，是把编辑器编辑的东西，支持转换为小程序支持的富文本。
https://mp.weixin.qq.com/debug/wxadoc/dev/component/rich-text.html

**Comment by wangfupeng1988** [comment]
哦 大体明白了，就是处理成小程序需要的json格式，我周末关注一下这个问题

**Comment by cmideal** [comment]
对啊，这样觉得是很有市场对，因为现在，小程序那些编辑器，完全就是ueditor加一个转换。1:转换效果太差，2:耗用小程序端资源，我们这个可以存两份，一份html,一份json的方式。绝对给力

**Comment by wangfupeng1988** [comment]
是这样的，多谢反馈哈

**Comment by wangfupeng1988** [comment]
https://www.kancloud.cn/wangfupeng/wangeditor3/455792
