### ISSUE TITLE
可使用 min-height 实现编辑区域自动增加高度 不能使用

### ISSUE THREAD

**Issue by liuchamp** [wangfupeng1988/wangEditor#969]
在帮助文档 https://www.kancloud.cn/wangfupeng/wangeditor3/335771 中，说的使用这个可以使得编辑器域高度自动增加。但是设置上去了，并不能起作用。

**Comment by wangfupeng1988** [comment]
https://github.com/wangfupeng1988/wangEditor/#运行-demo  参见这里，下载运行 demo ，demo 页有“菜单和编辑器区域分离”这个链接，点击进入页面。

这个页面的源码需要改动一下，源码地址在`example/demo/test-sperate.html`，将这个文件的`height: 400px;`修改为`min-height: 400px;`

然后刷新刚才打开的页面，试试能自动增加高度吧？我这边试着是可以的

**Comment by nszbf** [comment]
确实是不行，例子也是不行的，我用的chrome，firefox都不可以，官网的api不是很全面额，我记得2.0版本好像是有个设置高度的？

**Comment by wangfupeng1988** [comment]
我上面给出的 demo，我这里完全可以

**Comment by lijun1243939149** [comment]
不行的，运行过demo中的 example/demo/test-sperate.html，但是可编辑区域，仍然不是父级div的高度的100%～
我的是mac系统，chrome (Version 63.0.3239.84 )浏览器。。
【详见如下截图】
![wechatimg1811](https://user-images.githubusercontent.com/13789967/34337981-031a363a-e99f-11e7-99e2-12ad411bd70d.jpeg)
