### ISSUE TITLE
使用plupload组件上传，在ios设备上无法选择？

### ISSUE THREAD

**Issue by legendweny** [wangfupeng1988/wangEditor#97]
http://fork12.com/user/work/create 这里是我的站点，在ios设备上，点击 选择上传 按钮无法浏览图片

**Comment by wangfupeng1988** [comment]
1.这个PC版的定位，根本就没有打算再手机上用，手机上我也没测试。不支持手机。
2.plupload不好使，你可以换用其他插件，套路都是一样的。都是再文件上传完成的方法中，执行`editor.command`方法插入图片。

**Comment by wangfupeng1988** [comment]
手机版的，可以使用 http://wangeditor.github.io/m/
