### ISSUE TITLE
代码插入

### ISSUE THREAD

**Issue by devotion987** [wangfupeng1988/wangEditor#973]
http://www.wangeditor.com/index.html 首页中插入一段从idea中复制的代码，点“插入”，为什么没有反应？

**Comment by wangfupeng1988** [comment]
什么浏览器？

**Comment by devotion987** [comment]
试了下，火狐不行，谷歌和opera可以

**Comment by NikolasNull** [comment]
public void validate(){
        //调用getText方法取出国际化信息
        if(getAccount()==null||"".equals(this.getAccount().trim())){
            this.addFieldError("account", this.getText("account.required"));
        }
        if(this.getPassword()==null||"".equals(this.getPassword().trim())){
            this.addFieldError("password", this.getText("password.required"));
        }
    }

**Comment by wangfupeng1988** [comment]
> 火狐不行

我看到这个问题了，已经记录下，本周末升级改一下。请随时关注新版发布动态。

**Comment by wangfupeng1988** [comment]
@NikolasNull 

你发的这些代码，我完全没看明白

**Comment by wangfupeng1988** [comment]
@devotion987 问题已经解决，周末发布新版本，有问题再留言
