### ISSUE TITLE
以html形式存入的数据库，读出来之后，怎么在编辑器中显示？

### ISSUE THREAD

**Issue by SoupT** [wangfupeng1988/wangEditor#975]
编辑文章的时候，怎么把存在数据库里面的内容原样显示在编辑器内？

**Comment by yangxiaokun** [comment]
根据文档描述，你可以使用
editor.txt.html('<p>用 JS 设置的内容</p>')设置内容
或者 editor.txt.append('<p>追加的内容</p>') 追加内容
括号内就是你的 html片段

**Comment by wangfupeng1988** [comment]
楼上正解。参见 https://www.kancloud.cn/wangfupeng/wangeditor3/335774
