### ISSUE TITLE
在使用wangEditor时对上传图片功能的个人建议

### ISSUE THREAD

**Issue by VenusPP** [wangfupeng1988/wangEditor#976]
在使用wangEditor时上传图片功能时不能选择服务器端已有的图片，建议已上传的图片可以给个地方显示。
重复上传图片，会导致过多的资源。

**Comment by wangfupeng1988** [comment]
> 建议已上传的图片可以给个地方显示。重复上传图片，会导致过多的资源。

这个完全可以自己实现，编辑器只关注核心功能。
