### ISSUE TITLE
直接将一段富文本插入后，行高菜单有时不起作用

### ISSUE THREAD

**Issue by OneByOne123456** [wangfupeng1988/wangEditor#977]
直接将一段富文本插入后，行高菜单有时不起作用
![default](https://user-images.githubusercontent.com/31639264/30041977-bcd95eba-9220-11e7-884e-f398489a1408.png)
![default](https://user-images.githubusercontent.com/31639264/30042003-f616d036-9220-11e7-84a4-6e6af6cd6caf.png)

**Comment by wangfupeng1988** [comment]
1. 这是 v2 版本，现在已经升级到 v3 版本了
2. v3 版本开始，不支持行高的功能了，行高要求自己通过 css 控制
