### ISSUE TITLE
上传图片错误，有demo吗？

### ISSUE THREAD

**Issue by EthanDCX** [wangfupeng1988/wangEditor#979]
![image](https://user-images.githubusercontent.com/18240991/30042704-83f21bd2-9225-11e7-9c10-1a3f463c03fe.png)

**Comment by EthanDCX** [comment]
var editor = new E('#div5')
        editor.customConfig.customUploadImg = function (files, insert) {
            console.log(files)
            insert('https://ss0.bdstatic.com/5aV1bjqh_Q23odCf/static/superman/img/logo/bd_logo1_31bdc765.png')
        }
        editor.create()

这个insert参数没懂，怎么用？

**Comment by wangfupeng1988** [comment]
你拿到上传图片的url，执行`insert`方法，即可将图片插入到编辑区域
