### ISSUE TITLE
wangEditor-1.3.13.2.js 中2761行（上传图片显示与隐藏关系效果，异步初始化失效）

### ISSUE THREAD

**Issue by xcheese** [wangfupeng1988/wangEditor#98]
//处理 上传图片 和 插入网络图片 的显示与隐藏关系
$(function(){
  .....
})

这里如果是异步动态插入的textarea，再初始化带有本地的上传功能时候，就没有了切换功能

**Comment by wangfupeng1988** [comment]
没看明白啥意思，最好说的说一个应用场景。

**Comment by xcheese** [comment]
<div id="uploadContainer">
    <input type="button" value="选择文件" id="btnBrowse"/>
    <input type="button" value="上传文件" id="btnUpload">
    <ul id="fileList"></ul>
</div>
这一块要不是domready之后的内容的话，js生成的则无法绑定上切换显示的方法

**Comment by xcheese** [comment]
![image](https://cloud.githubusercontent.com/assets/9137396/12030578/d6299602-ae3b-11e5-8a96-0c9559c8f1a6.png)
这一块要不是domready之后的内容的话，js生成的则无法绑定上切换显示的方法

**Comment by wangfupeng1988** [comment]
对的，如果`#uploadContainer`是js动态生成的，可以先`append`到`body`里面，然后再绑定到编辑器中。
