### ISSUE TITLE
禁用编辑功能

### ISSUE THREAD

**Issue by zilan830** [wangfupeng1988/wangEditor#981]
您好，禁用编辑功能没大看懂。editor.$textElem.attr('contenteditable', false)。我直接这样写得并没有用。能否麻烦具体点？谢谢

**Comment by wangfupeng1988** [comment]
富文本编辑器的编辑区域，其实是一个`<div contenteditable="true">....</div>`，`editor.$textElem.attr('contenteditable', false)`这句话的用以就是设置`contenteditable="false"`，这样就能禁用编辑功能了。

**Comment by zilan830** [comment]
您好。首先很感谢您的回复。是这样的，我一开始也是想的是在这个dom上设置了属性，但是查看dom元素的时候并没有看到。所以后来以为是不是还要设置什么，主要是那样写了之后没有起作用。
`<div style="background-color:#f1f1f1; border:1px solid #ccc;" class="w-e-toolbar">
  <div class="w-e-menu" style="z-index:10001;"><i class="w-e-icon-header"><i></i></i></div>
  <div class="w-e-menu" style="z-index:10001;">
    <i class="w-e-icon-bold"><i>
    </i></i></div>
  <div class="w-e-menu" style="z-index:10001;">
    <i class="w-e-icon-italic"><i>
    </i></i></div>
  <div class="w-e-menu" style="z-index:10001;">
    <i class="w-e-icon-underline"><i>
    </i></i></div>
  <div class="w-e-menu" style="z-index:10001;">
    <i class="w-e-icon-strikethrough"><i>
    </i></i></div>
  <div class="w-e-menu" style="z-index:10001;"><i class="w-e-icon-pencil2"><i></i></i></div>
  <div class="w-e-menu" style="z-index:10001;"><i class="w-e-icon-paint-brush"><i></i></i></div>
  <div class="w-e-menu" style="z-index:10001;"><i class="w-e-icon-link"><i></i></i></div>
  <div class="w-e-menu" style="z-index:10001;"><i class="w-e-icon-list2"><i></i></i></div>
  <div class="w-e-menu" style="z-index:10001;"><i class="w-e-icon-paragraph-left"><i></i></i></div>
  <div class="w-e-menu" style="z-index:10001;">
    <i class="w-e-icon-quotes-left"><i>
    </i></i></div>
  <div class="w-e-menu" style="z-index:10001;">
    <i class="w-e-icon-happy"><i>
    </i></i></div>
  <div class="w-e-menu" style="z-index:10001;"><i class="w-e-icon-image"><i></i></i></div>
  <div class="w-e-menu" style="z-index:10001;"><i class="w-e-icon-table2"><i></i></i></div>
  <div class="w-e-menu" style="z-index:10001;"><i class="w-e-icon-play"><i></i></i></div>
  <div class="w-e-menu" style="z-index:10001;">
    <i class="w-e-icon-terminal"><i>
    </i></i></div>
  <div class="w-e-menu" style="z-index:10001;">
    <i class="w-e-icon-undo"><i>
    </i></i></div>
  <div class="w-e-menu" style="z-index:10001;">
    <i class="w-e-icon-redo"><i>
    </i></i></div>
</div>`

**Comment by wangfupeng1988** [comment]
我完全没看明白，上面回复的内容、代码是啥意思

**Comment by zilan830** [comment]
e .....没事

**Comment by cjcj5438** [comment]
editor.$textElem.attr('contenteditable', false)  禁止编辑内容
我在vue中怎么尝试都么有成功
`<template lang="html">
  <div class="editor">
    <div ref="toolbar" class="toolbar"></div>
    <div ref="editor" class="text"></div>
  </div>
</template>`


`
        this.editor = new E(this.$refs.toolbar, this.$refs.editor)
        this.editor.$textElem.attr('contenteditable', false)
        this.editor.customConfig.uploadImgShowBase64 = true // base 64 存储图片
.........
 this.editor.create()
`
或者正确的怎么写

**Comment by mariobeng** [comment]
> editor.$textElem.attr('contenteditable', false) 禁止编辑内容
> 我在vue中怎么尝试都么有成功
> 
> ```
> <template lang="html">
>   <div class="editor">
>     <div ref="toolbar" class="toolbar"></div>
>     <div ref="editor" class="text"></div>
>   </div>
> </template>
> ```
> 
> ```
>         this.editor = new E(this.$refs.toolbar, this.$refs.editor)
>         this.editor.$textElem.attr('contenteditable', false)
>         this.editor.customConfig.uploadImgShowBase64 = true // base 64 存储图片
> .........
>  this.editor.create()
> ```
> 
> 或者正确的怎么写

你好，麻烦问下你解决了吗？在vue中如何禁用编辑器呢？

**Comment by MzhouNiuniu** [comment]
vue 是一样的哦  但是注意需要在editor实例化后在操作具体代码如下

<script>
    import E from 'wangeditor'

    export default {
      name: 'editor',
        props:{
            disabled:{
                type: Boolean,
                default:false,
            }
        },
      data () {
        return {
          editorContent: '',
        }
      },
      methods: {
      },
      mounted() {
          var editor = new E(this.$refs.editor)
          editor.customConfig.onchange = (html) => {
              this.editorContent = html
              console.log(this.disabled)
          }
          editor.customConfig.uploadFileName = 'file'
          editor.customConfig.debug = true
          editor.customConfig.uploadImgMaxLength = 50
          editor.customConfig.pasteFilterStyle = false
          editor.customConfig.uploadImgServer = this.api.fileServer.uploadwang
          editor.customConfig.zIndex = 1
          editor.create()
          this.editor=editor
          if(this.disabled){
              this.editor.$textElem.attr('contenteditable', false)

          }
        
      }
    }
</script>
