### ISSUE TITLE
编辑器table单元格中，复制内容到光标所在单元格，但是内容加在了上一次文字位置

### ISSUE THREAD

**Issue by LaofanJiang** [wangfupeng1988/wangEditor#983]
![image](https://user-images.githubusercontent.com/19922739/30054140-a9e75a90-925d-11e7-8b32-ee95887e9eea.png)
您好，麻烦看下这个怎么解决 目前还在使用这个版本

**Comment by wangfupeng1988** [comment]
非常抱歉，v2 已经不做技术支持和升级了，建议升级 v3

**Comment by LaofanJiang** [comment]
好的 我已经解决了 应该是保存选区监听事件过多冲突导致 谢谢
