### ISSUE TITLE
关于图片上传 参数 被转异 问题

### ISSUE THREAD

**Issue by xiaoyinsss** [wangfupeng1988/wangEditor#984]
在使用图片上传功能时  发现参数会被转异 
举个栗子:"90fC8qNxjQDKPSU4AXSf9tIKfT4="
会被转成:"oIaZX8IV1tvIXMuGLmV7YMkPXzc%3D"

这样会导致图片上传 因参数错误失败

**Comment by xiaoyinsss** [comment]
再对例子进行一下补充
"90fC8qNxjQDKPSU4AXSf9tIKfT4="  会被转成  "oIaZX8IV1tvIXMuGLmV7YMkPXzc%3D"

**Comment by wangfupeng1988** [comment]
http请求中的参数肯定会被转移，你后端拿到再转回来就是了

**Comment by xiaoyinsss** [comment]
非常感谢您的解答，这个问题，我后来使用了自定义上传0.0
