### ISSUE TITLE
请问我该怎么在js外调用原型函数里的对象函数？

### ISSUE THREAD

**Issue by xie-du-kai** [wangfupeng1988/wangEditor#986]
![default](https://user-images.githubusercontent.com/22149096/30100224-aeabd67e-931a-11e7-83d4-708c2d4098fc.png)
如我要调用里面插入表情的那个对象函数。

**Comment by wangfupeng1988** [comment]
直接执行`editor.cmd.do('insertHTML', 'xxxx')` 就行了
