### ISSUE TITLE
新手请教如何增加代码高亮？我插入的代码都是一个颜色啊

### ISSUE THREAD

**Issue by king798284910** [wangfupeng1988/wangEditor#987]
例如`<html class='html'></html>`
我希望字符串的颜色不一样。
就像编辑器编辑的代码一样 ；
就像你官网贴的代码一样；

**Comment by king798284910** [comment]
搞定了，直接用了你文档推荐的高亮，挺好用

**Comment by wangfupeng1988** [comment]
你可能用的是 v2 版本，v2版本已经不做技术支持了。

目前早就升级到 v3 版本了，不过 v3 版本不支持代码高亮了。
