### ISSUE TITLE
这个编辑器真的不错！但是呢！有一点小问题

### ISSUE THREAD

**Issue by thousmile** [wangfupeng1988/wangEditor#989]
希望，作者能把 改一下自动适应 手机屏幕，我调试的时候，手机端   上面的工具了没有自动适应。
还有就是，那个编辑区，的框框能拉大就好了。或者高度自动变化更好，希望作者能越做越好

**Comment by wangfupeng1988** [comment]
> 自动适应 手机屏幕

编辑功能不支持移动端。如果编辑的内容在手机上显示有问题，可以具体提出来给我。

> 高度自动变化

参考 https://www.kancloud.cn/wangfupeng/wangeditor3/335771

**Comment by thousmile** [comment]
感谢。感谢！ 这个问题，我读了您的代码，从js里面修改了。我还是期待您在以后的版本中 能对移动端可以友好支持一下！

在 2017-09-11 15:12:03，"王福朋" <notifications@github.com> 写道：


自动适应 手机屏幕

编辑功能不支持移动端。如果编辑的内容在手机上显示有问题，可以具体提出来给我。

高度自动变化

参考 https://www.kancloud.cn/wangfupeng/wangeditor3/335771

**Comment by wangfupeng1988** [comment]
> 能对移动端可以友好支持一下！

建议可以提出的具体一些，然后我来看是否要升级加进来
