### ISSUE TITLE
富文本的弹出层调整为下拉面板

### ISSUE THREAD

**Issue by vxiaoxaiowen** [wangfupeng1988/wangEditor#99]
富文本 的插入视频
我把 modal 类型 改成了 dropPanel
然后 Panel 一点击 就隐藏掉了
下拉面板中的 文本框 输入也是 点击 就会 隐藏面板
这个 怎么控制呢？

改成 dropPanel 的前提是 
我的页面本来是弹出来的 层
然后加上 富文本后 
点击插入视频还要在弹出 modal 
就又是一个层
然后 这个层里边 视频的 地址 输入框 无法获取光标
就做了调整

代码调整如下

.
.
.
dropMyPanel:'<div class="wangEditor-drop-panel">{content}</div>',
.
.
.
insertVideo: {
		                title: e.insertVideo.title,
		                type: "dropMyPanel",
		                cssClass: "icon-wangEditor-play",
		                dropMyPanel: function(b) {
		                    var c = k.getUniqeId(),
		                    f = k.getUniqeId(),
		                    g = k.getUniqeId(),
		                    h = k.getUniqeId(),
		                    i = 480,
		                    j = 400,
		                    l = e.insertVideo.modal,
		                    m = l.url,
		                    n = l.width,
		                    o = l.height,
		                    p = d.insert,
		                    q = d.unsafeAlert,
		                    r = d.formatError,
		                    s = "<p>" + m + '：<input id="' + c + '" type="text" style="width:300px;"  placeholder="http://"/></p><p>' + n + '：<input id="' + f + '" type="text" style="width:50px" value="' + i + '"/> px（像素）</p><p>' + o + '：<input id="' + g + '" type="text" style="width:50px" value="' + j + '"/> px（像素） </p><p><button id="' + h + '" class="wangEditor-modal-btn" type="button">' + p + "</button></p>",
		                    t = a(k.htmlTemplates.dropMyPanelBig.replace("{content}", s));
		                    return t.find("#" + h).click(function(d) {
		                        var e, h = a.trim(a("#" + c).val()),
		                        l = +a("#" + f).val(),
		                        m = +a("#" + g).val(),
		                        n = function() {
		                            a("#" + c).val(""),
		                            a("#" + f).val(i),
		                            a("#" + g).val(j)
		                        };
		                        return k.filterXSSForUrl(h) === !1 ? void alert(q) : 0 !== h.indexOf("http://") && 0 !== h.indexOf("https://") || -1 === h.indexOf(".swf") ? void alert(r) : (isNaN(l) && (l = i), isNaN(m) && (m = j), e = k.htmlTemplates.videoEmbed.replace("{src}", h).replace("{width}", l).replace("{height}", m), void b.command(d, "insertHTML", e, n))
		                    }),
		                    t
		                }
		            },

...

其他代码 没有调整

**Comment by vxiaoxaiowen** [comment]
dropMyPanel:"\<"div class="wangEditor-drop-panel"\>"{content}"\</"div"\>",

**Comment by wangfupeng1988** [comment]
明白你什么意思了。你是说，你的编辑区域本来就是弹出层，插入视频再弄一个弹出层不好看，是吧？

但是很遗憾，你直接将`modal`形式改为`dropPanel`是不行的，因为`dropPanel`设计的是为特定的应用——表情、颜色快这种，你直接拿来去自定义内容，是不行的。

不过你的这个意见我会再元旦之后的重构中去考虑，即每个功能到底使用`modal`还是`dropPanel`用户自己可以定义，我会考虑增加的。

**Comment by vxiaoxaiowen** [comment]
好的 谢谢 期待你的新版本
