### ISSUE TITLE
请问v3如何实现事件监听

### ISSUE THREAD

**Issue by ickedesign** [wangfupeng1988/wangEditor#991]
比如focus，blur，onkeydown事件。我知道这些要自己定义方法，请问大概要怎么定义。
![image](https://user-images.githubusercontent.com/17939675/30236461-50b62fae-954c-11e7-9174-1bbb1dd531c1.png)

**Comment by wangfupeng1988** [comment]
`focus` `blur`目前还不支持。

`keydown`时间你可以自己监听编辑区域的DOM事件，跟普通JS事件一样。
