### ISSUE TITLE
easyui 配合使用上传图片后问题

### ISSUE THREAD

**Issue by manong2860686267** [wangfupeng1988/wangEditor#996]
您好 麻烦问下 有没有遇到过 easyui 配合使用上传图片后问题 如图 表单提交后显示问题  
![20170910192042](https://user-images.githubusercontent.com/20216300/30248582-3019ce74-965d-11e7-8b02-d604d1dd4286.jpg)
滚动滚动条到编辑器是 内容始终浮动在easyui 弹出框的上层

**Comment by wangfupeng1988** [comment]
红框中的浮层，是个啥？

**Comment by manong2860686267** [comment]
您好 是easyui的$.message.alert

**Comment by wangfupeng1988** [comment]
`$.message.alert`弹框，北京为何是菜单的图标？我不理解
