### ISSUE TITLE
图片上传中的验证提示如果设置多语言？

### ISSUE THREAD

**Issue by codinglilong** [wangfupeng1988/wangEditor#999]
如题 
![324](https://user-images.githubusercontent.com/20492424/30269849-fee1e006-971c-11e7-9f48-78e235802b89.png)
这里如何设置多语言？如果不行的话看来要我自己写了

**Comment by wangfupeng1988** [comment]
https://www.kancloud.cn/wangfupeng/wangeditor3/335782 

```js
editor.customConfig.customAlert = function (info) {
    // info 是需要提示的内容
    alert('自定义提示：' + info)
}
```

自己替换一下吧
